### ISSUE TITLE
Picons/Image Resizing

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1000]
As a bit of a hack, I managed to edit the renderer picon.py to scale smoothly using the PIL image library. 
My python skills and enigma2 code knowledge is limited. 

I managed to achieve this by the following.

from PIL import Image

then editing the def changed module code to this.

                        im = Image.open(pngname)
                        im = im.resize((self.piconsize), Image.ANTIALIAS)
                        tempfile = lastPiconPath + 'temp.png'
                        im.save(tempfile)
                        self.instance.setScale(1)
                        self.instance.setPixmapFromFile(tempfile)					
                        self.instance.show()

Does anyone know a better way of doing this, rather than saving to a tmp.png file and calling that?

Also on the same subject, after all these years of broken image scaling can someone possibly rewrite the eListboxPythonMultiContent BT_Scale and any other image scaling to either use a more modern library like PIL or somehow resize with smooth antialias. Ta

**Comment by iPkay** [comment]
I have tested this - the quality is lower than before with setScale command only.
old
![old](https://user-images.githubusercontent.com/7643228/42733812-c8e1f640-8838-11e8-894d-fa6732112471.png)
new
![new](https://user-images.githubusercontent.com/7643228/42733816-ccc031e6-8838-11e8-82e1-80575db22617.png)

**Comment by kiddac** [comment]
How can it be worse?
SetScale has no antialias. Its just resized by nearest neighbour algorithm. 
PIL library does a proper resize with antialias.

My results from my tests are here to highlight the benefit I am receiving.
https://linuxsat-support.com/thread/132144-picon-scaling/?postID=450104#post450104

**Comment by kiddac** [comment]
And the eListboxPythonMultiContent BT_Scale  has always been broke. I appreciate that is probably a big job to fix, as no one has ever seemed to address the issue. So I don't think the issue is closed. 

Example of picons in channel select. Scaled badly.

![image](https://user-images.githubusercontent.com/6818561/42734106-22269830-8836-11e8-8cbe-0d2706ad3896.png)

**Comment by iPkay** [comment]
Ok, the last poor quality is result from 8-bit picons - but with converted or native 32-bit picons can't see a relevant difference. Picons are scaled from 220x132 to 330x198.
with PIL resize
![neu](https://user-images.githubusercontent.com/7643228/42735781-6959d8b0-885a-11e8-85f2-f8ae772fefc0.jpg)
without PIL resize
![alt](https://user-images.githubusercontent.com/7643228/42735785-7415c28c-885a-11e8-81b3-d8bebfc5b78c.jpg)

**Comment by kiddac** [comment]
I will convert my picon set to 8 bit index files and do some further testing on upscaling and downscaling. 
From what you are saying setScale(1) seems to work fine with your indexed images. Where as RGB images through my testing don't scale well unless I use the PIL library.

**Comment by kiddac** [comment]
Did you fix your latest experimental commit. Someone was complaining it was crashing their box today. 

File "/home/oe1/atv62/build-enviroment/builds/openatv/release/8100s/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-skins-metrix-atv/2.1+gitAUTOINC+3622c4bd70-r7/git/usr/lib/enigma2/python/Components/Renderer/MetrixHDXPicon.py", line 80, in changed

14:18:15.1775 { D } File "/usr/lib/enigma2/python/Components/config.py", line 1846, in __getattr__

14:18:15.1777 { D } KeyError: 'MyMetrixLiteOther'

14:18:15.1778 [ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation instance at 0xb1b48468>>,(0,)) failed)

**Comment by arn354** [comment]
https://github.com/openatv/MetrixHD/commit/738ebf225ac945fee232b400a89fb7d76d304918

config initialization in  renderer was missing

**Comment by kiddac** [comment]
I have purposely used a transparent picon for this test. A solid image might not show up the differences that much. 

Upscaling from a 100x60 picon into a 220x132 space.

1) Index - using just setScale(1)
2) RGB - using just setScale(1)
3) Indexed - converted to rgba and resized using PIL and antialias.
4) RGB - converted to rgba and resized using PIL and antialias.

![image](https://user-images.githubusercontent.com/6818561/42773895-0cd8f84a-8928-11e8-98a4-3b17f29ddacc.png)

Downscaling from 400x240 into a 220x132 space. 

1) Index - using just setScale(1)
2) RGB - using just setScale(1)
3) Indexed - converted to rgba and resized using PIL and antialias.
4) RGB - converted to rgba and resized using PIL and antialias.

![image](https://user-images.githubusercontent.com/6818561/42775753-146a74ee-892d-11e8-94a9-4def6ca27cae.png)

**Comment by kiddac** [comment]
I noticed in your experiment you checked for the size of the original first.
If upscaling, you can try a tiny bit of sharpness. 

from PIL import Image, **ImageEnhance**

im = Image.open(pngname).convert('RGBA')	
im = im.resize((self.piconsize), Image.ANTIALIAS)
contrast = ImageEnhance.Sharpness(im)
im = contrast.enhance(1.25)

**Comment by iPkay** [comment]
I check this tomorrow.

**Comment by kiddac** [comment]
is that using im = Image.open(pngname).convert('RGBA')

**Comment by iPkay** [comment]
stefanbenno6 - Mirror Glass ZZZPicons Astra 19.2E

**Comment by kiddac** [comment]
tested alphatest="on" still ok.
have you got piconbg set to a colour and not transparent

**Comment by iPkay** [comment]
yes, but some not.

**Comment by kiddac** [comment]
what does your transparent piconbg look like in the skin you are using.
Does it still do it if you change the piconbg to disabled.

**Comment by iPkay** [comment]
MetrixHD - i using new experimental option ...

**Comment by kiddac** [comment]
I don't have piconbg in my skins. But I have just put it in and the set it to disabled in osd settings.

I get this. This is a 400x220 downscaled to 220x132

![image](https://user-images.githubusercontent.com/6818561/42783249-549e7504-8943-11e8-991f-6e9abbabbdf4.png)

**Comment by kiddac** [comment]
and just searching metrixhd code. They don't use piconbg either. So its a mystery.

**Comment by iPkay** [comment]
piconbg is not used - was no problem until now

**Comment by kiddac** [comment]
if you are saving a tmp.png. Open that up in a graphics program and see if you are getting them blue corners. If not it might be the picon but the background.

**Comment by kiddac** [comment]
my temp.png file looks like this
![image](https://user-images.githubusercontent.com/6818561/42783887-49b7acf8-8945-11e8-91eb-8a9d282ff5e9.png)

**Comment by iPkay** [comment]
I will test it later and attach the problem files here.

**Comment by iPkay** [comment]
Here ist a file was ok and was not ok.
https://www.dropbox.com/sh/l7g6d9d1yuhskbw/AABX3aNZrE9dHjX0rfD-C3oBa?dl=0

**Comment by kiddac** [comment]
what is this bit of code meant to be doing. 

try:
  a = im.getbands().index('A')
except:
  im = im.convert('RGBA')

You don't reference "a" anywhere else in your code.  

I read that code as if transparent don't do anything with it. If its not transparent change it to RGBA. 
Is that possible why you are not getting transparent.

**Comment by iPkay** [comment]
it only converts if there is no transparency - has nothing to do with the 'problem'.

**Comment by iPkay** [comment]
![source](https://user-images.githubusercontent.com/7643228/42817276-ed5f0076-89cd-11e8-9811-29e6b6367380.png)

the code :  Image.open('source.png').convert('RGBA').save('problem.png')

![problem](https://user-images.githubusercontent.com/7643228/42817312-05c4693a-89ce-11e8-95c2-8d8f06323578.png)

and the transparency is over ...

**Comment by kiddac** [comment]
i create my own picons and always run them through the png compressor pngyu. 
I have just checked everyone of my picons in metrixhd. Strangely only one shows incorrectly. 
And that one doesn't even seem to have any kind of opacity other than 0.
![image](https://user-images.githubusercontent.com/6818561/42841659-b0787e64-8a02-11e8-9706-bbb98d2a5396.png)

**Comment by iPkay** [comment]
fine, and now please a solution to the problem ..;)

I tried with different masks to transfer the transparency but did not make it. It is important that it is processed quickly. I realize that it is a mistake in the picons, but this must be fixed here - without this has the new function no future. I have holidays now and I hope for an idea from you :)
I open the source files with paint.net and can see the difference, but how to fix...

**Comment by kiddac** [comment]
All bloody day this took me trying hundreds of different ways to achieve fixing these broken pngs.
Eventually found some code by some clever genius. 

Here is your new file. 
[MetrixHDXPicon.zip](https://github.com/openatv/enigma2/files/2206946/MetrixHDXPicon.zip)

import is now this
`from PIL import Image, ImageFile, PngImagePlugin`

 new modules at the top before your picon class.

`def patched_chunk_tRNS(self, pos, len):`

`def patched_load(self):`

No need to check what png type it is anymore we just convert all to rgba. 
I have also removed the image enhance sharpening. You seem to have put it in for all. Sharpening is only needed if your upscaling.
