### ISSUE TITLE
OpenATV 6.2/HD51 - backup image

### ISSUE THREAD

**Issue by ser6pyton** [openatv/enigma2#1001]
02:28:06.6448 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 68, in action
02:28:06.6449 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
02:28:06.6450 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 329, in go
02:28:06.6451 { D }   File "/usr/lib/enigma2/python/mytest.py", line 327, in open
02:28:06.6454 { D }     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
02:28:06.6454 { D }   File "/usr/lib/enigma2/python/mytest.py", line 265, in instantiateDialog
02:28:06.6456 { D }     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
02:28:06.6457 { D }   File "/usr/lib/enigma2/python/mytest.py", line 287, in doInstantiateDialog
02:28:06.6459 { D }     dlg = screen(self, *arguments, **kwargs)
02:28:06.6460 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py", line 95, in __init__
02:28:06.6461 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py", line 195, in list_files
02:28:06.6463 { D } IndexError: list index out of range
02:28:06.6463 [ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap instance at 0xacd6ac38>>,('WizardActions', 'ok')) failed)

**Comment by opfans** [comment]
press blue key on your remote control ,click software manager,complete backup,select HDD or USB option ,then starting backup image.3-5mins later ,the backup image is on your HDD or USB stick,you can restore image if you need

**Comment by atvcaptain** [comment]
backup rework now include in last image
