### ISSUE TITLE
Git --set-upstream error

### ISSUE THREAD

**Issue by maxbambi** [openatv/enigma2#1014]
I have installed openatv build environment in a new pc with ubuntu 18.04, but I couldn't bake anything because process ended very soon.
I caught this error:
`ERROR: gnu-config-native-20150728+gitAUTOINC+b576fa87c1-r0 do_unpack: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1144"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/openatvbuilder/openatv/build-enviroment/openembedded-core/scripts/native-intercept:/home/openatvbuilder/openatv/build-enviroment/openembedded-core/scripts:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/bin/x86_64-linux:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/bin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/sbin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/bin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/sbin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/bin:/home/openatvbuilder/openatv/build-enviroment/bitbake/bin:/home/openatvbuilder/openatv/build-enviroment/builds/openatv/release/sf4008/tmp/hosttools"; export HOME="/home/openatvbuilder"; git -c core.fsyncobjectfiles=0 branch --set-upstream master origin/master failed with exit code 128, output:
fatal: the '--set-upstream' option is no longer supported. Please use '--track' or '--set-upstream-to' instead.`
Probably it's related to the version of git (2.17 instead of 2.7 in Ubuntu 16.04)

**Comment by arn354** [comment]
Use 16.04 like we do and like our build instructions mention Readme.md - or fix it, or wait :)

**Comment by maxbambi** [comment]
Understood!
But I have downloaded a newer version of bitbake and I will try...
