### ISSUE TITLE
Today's update has broken connection to TvHeadend

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#1028]
I don't know if its the new updated libudfread or not, but after updating the image today, connection to TvHeadend is no longer possible, in fact connection to most IPTV is also broken if it uses Transport Streams.

As soon as a backup is flashed, connection is possible again and everything works as it should.

**Comment by ian10951** [comment]
No I suspected it was not that, and when I replaced it with the old lib it was still broken, but I couldn't see anything else that was obvious to try. It has to be something else that's in Today's update the content of which I have no knowledge. Sorry I cannot be of more help other than to report the problem with Today's update.

**Comment by ian10951** [comment]
Just found out that if the bouquet is flagged to use Gstreamer then connection to Tvheadend is ok, its just when its flagged to use 5002 Exteplayer3 that Today's update has broken things.

Hope this helps in finding whatever has caused this issue.

**Comment by atvcaptain** [comment]
flash new here working  i installed ultimo 4k image, from 30.9 use 5002 and iptv works get plugin from bh

**Comment by ian10951** [comment]
Ok thanks for looking.

It seems a flash of a clean image is needed then as obviously the online update does not update everything as it should.

But good to know its fine for you with a clean image.

**Comment by atvcaptain** [comment]
i have test before ultimo4k one non vu box with ipk update 77 files, and working too, i have flash the image first on friday to this box

**Comment by ian10951** [comment]
Ok cheers.

It seems a flash of a clean install is the only way forward because I now believe its Serviceapp thats broken in the online update because other streaming plugins no longer work through Serviceapp, regardless of what Serviceapp is set to in the config. uninstalling and reinstalling Serviceapp from the feeds doesn't fix it either, at least not on a VU+ box, so a clean install is the only answer. You may find you get asked about this a few times in the coming days on your forum as its broken other streaming plugins through Serviceapp, so at least you can now tell them the answer, to install a clean image. So it wasn't a complete waste of time testing.

Many Thanks.
