### ISSUE TITLE
Feature request: full backup from CLI

### ISSUE THREAD

**Issue by rchovan** [openatv/enigma2#1041]
Hi, 
could you please add feature to create full backup of image from CLI ? I want to make regular weekly backup with cron. I have tried to create image from GUI and then look at ps, and I found several commands, but I'm not sure if it is everything:
```
/usr/sbin/mkfs.ubifs -r /tmp/bi/root -o /hdd/bi/root.ubi -m 4096 -e 1040384 -c 1984
/usr/sbin/ubinize -o /hdd/bi/root.ubifs -m 4096 -p 1024KiB /hdd/bi/ubinize.cfg
/usr/sbin/ubinize -o /hdd/bi/root.ubifs -m 4096 -p 1024KiB /hdd/bi/ubinize.cfg
nanddump -a -f /hdd/bi/vmlinux.gz /dev/mtd2
sh -c {  gzip -d /hdd/bi/vmlinux.gz -c > /tmp/vmlinux.bin; } 2>&1
gzip -d /hdd/bi/vmlinux.gz -c
cp -r /hdd/xpeedlx3/imageversion /hdd/xpeedlx3/kernel.bin /hdd/xpeedlx3/noforce /hdd/xpeedlx3/rootfs.bin /hdd/fullbackup_xpeedlx3/
```

There are some variables, like-m 4096 -e 1040384 -c 1984 and I'm not sure if image created with this script will work on other models too. 

Thank You.

**Comment by franz-josef-kaiser** [comment]
@rchovan Have you tried executing [the backup utility](https://github.com/openatv/enigma2/blob/43a97245297cca2abbf12767396ca3e255818cad/lib/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py) directly yet?

**Comment by rchovan** [comment]
@franz-josef-kaiser Hi, 
I have tried as you suggested, but it does not work. 

```
root@xpeedlx3:/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager# python ImageBackup.pyo
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py", line 7, in <module>
ImportError: No module named enigma
```

**Comment by arn354** [comment]
Add prints to ImageBackup.Py to get all commands
Check the log
Create a static script

And yes - you need to do that for every box/vendor - there is no “general” backup for every box, there are differences. you could script it dynamic if you consider using boxbranding informations also in your script.
