### ISSUE TITLE
zap timer breaks EPG

### ISSUE THREAD

**Issue by tbrandysky** [openatv/enigma2#1042]
1) running openatv 6.2 with latest updates
2) using default MAtrixHD skin
3) I've dvb-t2 channels sorted in favourites list
4) I open EPG, select the show and setup "zap" on this show
5) zap record kicks in and switch the channel but not to desired channel but to very first channel of the whole channel list 
6) I am now out of favourites list in "all channels" list. 
7) when I try to switch the channel from EPG I got black screen with "FROM BOUQUET "userbouquet.favourites.tv' string instead of channel name
8) I have to switch back to favourites list to see all my favourite channels
9) EPG is listing all shows for favourite channels but once I try to switch the channel I got the same result as described in 7)
10) I have to restart GUI to get back to normal state

**Comment by tbrandysky** [comment]
![screenshot from 2018-11-09 12-06-47](https://user-images.githubusercontent.com/3275770/48259340-f45e4680-e417-11e8-9446-7b47feba455f.png)

**Comment by tbrandysky** [comment]
this issue seems to be present for longer time: http://www.techkings.org/threads/timer-zap-problem.132846/

**Comment by jbleyel** [comment]
Can you please try ATV 7.0?
