### ISSUE TITLE
cleaned up ImageBackup.py

### ISSUE THREAD

**Issue by atom89** [openatv/enigma2#1054]
I made tekst translatable, fixed some tekst bugs and made the output on the screen more symetric.
(space between tekst and lines)

[ImageBackup.zip](https://github.com/openatv/enigma2/files/2637160/ImageBackup.zip)

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/commit/f3da72d33b3b1147cf809c6a3157dc01eb8658fd
