### ISSUE TITLE
Enigma2 crash when view serviceinfo on cavs service

### ISSUE THREAD

**Issue by opfans** [openatv/enigma2#1078]
Cavs  is a video compression standard,used in china .The recently openatv image  has one issue about cavs stream services.When view serviceinfo on cavs stream services,enigma2 crash then restart gui.I show logs here:

openATV Enigma2 crash log

crashdate=涓?1鏈? 9 04:51:33 2019
compiledate=Jan  7 2019
skin=MetrixHD/skin.xml
sourcedate=2019-01-07
branch=6.3
rev=2.8.0-19946-g8a4a2e4
component=Enigma2

stbmodel=sf4008
stbmodel=ultimo
stbmodel=dm800se
kernelcmdline=root=/dev/mmcblk0p4 rootwait rw vmalloc=692m bmem=700m@324m
nimsockets=NIM Socket 0:
imageversion=box_type=sf4008
imageissue=Welcome to openATV for %h

9964 as offset for 0
04:51:20.5427 [   ] dvb/dvb.cpp:2208 getNextSourceSpan [eDVBChannel] ok, resolved skip (rel: 0, diff 0), now at 000026ec
04:51:20.5523 [   ] service/servicedvb.cpp:1613 unpause [eDVBServicePlay] unpause
04:51:20.5525 { E } Components/Pixmap.py:133 setPixmapNum setPixmapNum(0) failed! defined pixmaps: []
04:51:20.5533 {   } Screens/Screen.py:150 show [SCREENNAME]  PVRState
04:51:20.5542 { E } Components/Pixmap.py:133 setPixmapNum setPixmapNum(0) failed! defined pixmaps: []
04:51:20.5546 {   } Screens/Screen.py:150 show [SCREENNAME]  PVRState
04:51:20.5549 { E } Tools/Notifications.py:36 RemovePopup RemovePopup, id = ZapError
04:51:20.5549 {   } Plugins/Extensions/EnhancedMovieCenter/InfoBarSupport.py:154 __serviceStarted new service started! trying to download cuts!
04:51:20.5614 {   } skin.py:1375 readSkin [SKIN] processing screen MessageBoxSimple:
04:51:20.5751 {   } skin.py:1375 readSkin [SKIN] processing screen MessageBoxSimple_summary:
04:51:20.5768 {   } Screens/Screen.py:150 show [SCREENNAME]  ['MessageBoxSimple_summary', 'SimpleSummary']
04:51:20.5780 {   } Screens/Screen.py:150 show [SCREENNAME]  ['MessageBoxSimple']
04:51:20.5805 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
04:51:20.5812 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 1 KEY_OK OK
04:51:20.5814 [   ] dvb/dvb.cpp:1944 pvrEvent [eDVBChannel] pvrEvent evtStopped
04:51:20.5817 [   ] dvb/pmt.cpp:214 PATready [eDVBServicePMTHandler] PATready
04:51:20.5817 [   ] dvb/pmt.cpp:225 PATready [eDVBServicePMTHandler] PAT TSID: 0x0015 (21)
04:51:20.5817 [   ] dvb/pmt.cpp:254 PATready [eDVBServicePMTHandler] use pmtpid 0103 for service_id 034b
04:51:20.5818 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux6
04:51:20.5818 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=259
04:51:20.5819 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux6
04:51:20.5819 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=0
04:51:20.5894 [   ] service/servicedvb.cpp:1209 serviceEvent [eDVBServicePlay] eventNewProgramInfo timeshift_enabled=0 timeshift_active=0
04:51:20.5900 <   > service/servicedvb.cpp:2905 updateDecoder [eDVBServicePlay] have 1 video stream(s) (0202), and 1 audio stream(s) (029e), and the pcr pid is 0202, and the text pid is ffffffff

04:51:20.5902 [   ] service/servicedvb.cpp:3590 setAC3Delay [eDVBServicePlay] Setting audio delay: setAC3Delay, 0 + 0
04:51:20.5903 [   ] service/servicedvb.cpp:3601 setPCMDelay [eDVBServicePlay] Setting audio delay: setPCMDelay, 0 + 0
04:51:20.5903 [   ] dvb/decoder.cpp:870 setState [eTSMPEGDecoder] decoder state: play, vpid=0202, apid=029e
04:51:20.5904 <   > dvb/decoder.cpp:488 setSlowMotion [eDVBVideo0] VIDEO_SLOWMOTION 0 ok
04:51:20.5904 <   > dvb/decoder.cpp:503 setFastForward [eDVBVideo0] VIDEO_FAST_FORWARD 0 ok
04:51:20.5904 <   > dvb/decoder.cpp:476 unfreeze [eDVBVideo0] VIDEO_CONTINUE ok
04:51:20.5905 <   > dvb/decoder.cpp:207 unfreeze [eDVBAudio0] AUDIO_CONTINUE ok
04:51:20.5961 {   } Plugins/Extensions/Volume_adjust/plugin.py:468 __evUpdatedInfo [Volume Adjust] Update Info
04:51:20.5967 {   } Plugins/Extensions/Volume_adjust/plugin.py:472 __evUpdatedInfo [Volume Adjust] Volume = 9
04:51:20.5968 {   } Plugins/Extensions/Volume_adjust/plugin.py:446 loadXML [Volume Adjust] load xml...
04:51:20.5992 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux6
04:51:20.5993 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=259
04:51:20.7306 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT FRAME_RATE_CHANGED 25000 fps

04:51:20.7308 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT PROGRESSIVE_CHANGED 0

04:51:20.7309 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT SIZE_CHANGED 1920x1080 aspect 3

04:51:20.7385 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT FRAME_RATE_CHANGED 25000 fps

04:51:20.7387 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT PROGRESSIVE_CHANGED 0

04:51:21.3293 {   } Plugins/Extensions/EnhancedMovieCenter/EMCMediaCenter.py:655 setAudioTrack ###############################################audio
04:51:21.4535 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
04:51:21.4543 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 0 KEY_OK OK
04:51:21.4545 {   } Components/ActionMap.py:46 action action ->  MsgBoxActions ok
04:51:21.4554 {   } Screens/Screen.py:150 show [SCREENNAME]  EMCMoviePlayerSummary
04:51:21.4585 {   } Screens/Screen.py:150 show [SCREENNAME]  EMCMediaCenter
04:51:21.4593 {   } Screens/Screen.py:150 show [SCREENNAME]  PVRState
04:51:21.4670 [   ] service/servicedvb.cpp:1626 seekTo [eDVBServicePlay] seekTo 162197999
04:51:21.4671 [   ] dvb/dvb.cpp:1958 cueSheetEvent [eDVBChannel] seek.
04:51:21.4671 [   ] dvb/filepush.cpp:332 pause [eFilePushThread] waiting for pause
04:51:21.4761 [   ] dvb/filepush.cpp:284 thread [eFilePushThread] PAUSED
04:51:21.4762 <   > dvb/decoder.cpp:183 flush [eDVBAudio0] AUDIO_CLEAR_BUFFER ok
04:51:21.5001 <   > dvb/decoder.cpp:452 flush [eDVBVideo0] VIDEO_CLEAR_BUFFER ok
04:51:21.5060 [   ] dvb/tstools.cpp:415 getOffset [eDVBTSTools] getOffset using: 139932000:174870000 -> 2330677924:2913344820
04:51:21.5063 {   } Screens/Screen.py:150 show [SCREENNAME]  EMCMediaCenter
04:51:21.5068 {   } Screens/Screen.py:150 show [SCREENNAME]  EMCMediaCenter
04:51:21.5077 [   ] dvb/dvb.cpp:1944 pvrEvent [eDVBChannel] pvrEvent evtStopped
04:51:21.5544 [   ] dvb/tstools.cpp:211 getPTS [eDVBTSTools] getPTS PCR        15835fd0d found at 2702023044 pid 202 (47 02 02 35 07 10 ac 1a fe 86 81)
04:51:21.5546 [   ] dvb/tstools.cpp:698 takeSample [eDVBTSTools] takeSample adding sample 2702011576: pts 162158804 -> pos 2702023044 (diff 11468 bytes)
04:51:21.5546 [   ] dvb/tstools.cpp:448 getOffset [eDVBTSTools] getOffset calculated diff -435 ms
04:51:21.5546 [   ] dvb/tstools.cpp:451 getOffset [eDVBTSTools] getOffset diff to big, refining
04:51:21.5546 [   ] dvb/tstools.cpp:415 getOffset [eDVBTSTools] getOffset using: 162158804:174870000 -> 2702023044:2913344820
04:51:21.5611 [   ] dvb/tstools.cpp:211 getPTS [eDVBTSTools] getPTS PCR        1583699a1 found at 2702699844 pid 202 (47 02 02 31 07 10 ac 1b 4d d0 81)
04:51:21.5612 [   ] dvb/tstools.cpp:698 takeSample [eDVBTSTools] takeSample adding sample 2702674652: pts 162198888 -> pos 2702699844 (diff 25192 bytes)
04:51:21.5612 [   ] dvb/tstools.cpp:448 getOffset [eDVBTSTools] getOffset calculated diff 9 ms
04:51:21.5612 [   ] dvb/tstools.cpp:465 getOffset [eDVBTSTools] getOffset aborting. Taking 2702674652 as offset for 162198888
04:51:21.5612 [   ] dvb/dvb.cpp:2208 getNextSourceSpan [eDVBChannel] ok, resolved skip (rel: 0, diff 162198888), now at a1178adc
04:51:21.5682 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
04:51:21.5691 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 1 KEY_OK OK
04:51:23.2591 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 ae 1
04:51:23.2599 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 174 0 KEY_EXIT EXIT
04:51:23.2601 {   } Components/ActionMap.py:46 action action ->  InfobarShowHideActions hide
04:51:23.4231 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 ae 1
04:51:23.4239 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 174 1 KEY_EXIT EXIT
04:51:24.3102 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 8b 1
04:51:24.3111 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 139 0 KEY_MENU MENU
04:51:24.3114 {   } Components/ActionMap.py:46 action action ->  InfobarMenuActions mainMenu
04:51:24.3167 {   } skin.py:1375 readSkin [SKIN] processing screen menu_mainmenu:
04:51:24.4817 {   } skin.py:1375 readSkin [SKIN] processing screen MenuSummary:
04:51:24.4864 {   } Screens/Screen.py:150 show [SCREENNAME]  MenuSummary
04:51:24.4871 {   } Screens/Screen.py:150 show [SCREENNAME]  ['menu_mainmenu', 'Menu']
04:51:24.4901 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 8b 1
04:51:24.4908 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 139 1 KEY_MENU MENU
04:51:27.2019 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:27.2027 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:27.2029 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:27.3651 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:27.3659 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:27.7873 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:27.7880 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:27.7883 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:27.9512 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:27.9521 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:29.0177 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
04:51:29.0186 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 0 KEY_OK OK
04:51:29.0188 {   } Components/ActionMap.py:46 action action ->  WizardActions ok
04:51:29.0189 { W } Components/ActionMap.py:53 action unknown action WizardActions/ok! typo in keymap?
04:51:29.0189 {   } Components/ActionMap.py:46 action action ->  OkCancelActions ok
04:51:29.0247 {   } skin.py:1375 readSkin [SKIN] processing screen menu_setup:
04:51:29.0701 {   } skin.py:1375 readSkin [SKIN] processing screen MenuSummary:
04:51:29.0714 {   } Screens/Screen.py:150 show [SCREENNAME]  MenuSummary
04:51:29.0720 {   } Screens/Screen.py:150 show [SCREENNAME]  ['menu_setup', 'Menu']
04:51:29.1322 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
04:51:29.1333 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 1 KEY_OK OK
04:51:29.5854 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 ae 1
04:51:29.5862 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 174 0 KEY_EXIT EXIT
04:51:29.5865 {   } Components/ActionMap.py:46 action action ->  WizardActions back
04:51:29.5865 { W } Components/ActionMap.py:53 action unknown action WizardActions/back! typo in keymap?
04:51:29.5866 {   } Components/ActionMap.py:46 action action ->  OkCancelActions cancel
04:51:29.5885 {   } Screens/Screen.py:150 show [SCREENNAME]  MenuSummary
04:51:29.5909 {   } Screens/Screen.py:150 show [SCREENNAME]  ['menu_mainmenu', 'Menu']
04:51:29.7492 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 ae 1
04:51:29.7500 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 174 1 KEY_EXIT EXIT
04:51:29.9674 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:29.9683 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:29.9684 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:30.2392 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:30.2400 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:30.3750 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:30.3758 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:30.3760 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:30.4892 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:30.4900 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:30.6198 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:30.6207 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:30.6209 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:30.7342 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:30.7351 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:31.0965 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:31.0974 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:31.0976 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:31.2112 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:31.2122 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:31.4621 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 6c 1
04:51:31.4630 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 108 0 KEY_DOWN DOWN
04:51:31.4633 {   } Components/ActionMap.py:46 action action ->  WizardActions down
04:51:31.5762 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 6c 1
04:51:31.5769 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 108 1 KEY_DOWN DOWN
04:51:31.7692 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
04:51:31.7700 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 0 KEY_OK OK
04:51:31.7702 {   } Components/ActionMap.py:46 action action ->  WizardActions ok
04:51:31.7703 { W } Components/ActionMap.py:53 action unknown action WizardActions/ok! typo in keymap?
04:51:31.7704 {   } Components/ActionMap.py:46 action action ->  OkCancelActions ok
04:51:31.7750 {   } skin.py:1375 readSkin [SKIN] processing screen menu_information:
04:51:31.8006 {   } skin.py:1375 readSkin [SKIN] processing screen MenuSummary:
04:51:31.8018 {   } Screens/Screen.py:150 show [SCREENNAME]  MenuSummary
04:51:31.8023 {   } Screens/Screen.py:150 show [SCREENNAME]  ['menu_information', 'Menu']
04:51:31.8842 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
04:51:31.8851 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 1 KEY_OK OK
04:51:32.4792 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
04:51:32.4800 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 0 KEY_UP UP
04:51:32.4803 {   } Components/ActionMap.py:46 action action ->  WizardActions up
04:51:32.6432 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
04:51:32.6440 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 103 1 KEY_UP UP
04:51:33.1275 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
04:51:33.1284 {   } Screens/InfoBarGenerics.py:248 actionA KEY: 352 0 KEY_OK OK
04:51:33.1289 {   } Components/ActionMap.py:46 action action ->  WizardActions ok
04:51:33.1289 { W } Components/ActionMap.py:53 action unknown action WizardActions/ok! typo in keymap?
04:51:33.1290 {   } Components/ActionMap.py:46 action action ->  OkCancelActions ok
04:51:33.1317 {   } skin.py:1375 readSkin [SKIN] processing screen ServiceInfo:
04:51:33.1466 {   } skin.py:1375 readSkin [SKIN] processing screen SimpleSummary:
04:51:33.1476 {   } Screens/Screen.py:150 show [SCREENNAME]  ['ServiceInfo_summary', 'SimpleSummary']
04:51:33.1489 { D } Traceback (most recent call last):
04:51:33.1489 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 68, in action
04:51:33.1492 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
04:51:33.1493 { D }   File "/usr/lib/enigma2/python/Screens/Menu.py", line 77, in okbuttonClick
04:51:33.1495 { D }   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
04:51:33.1496 { D }   File "/usr/lib/enigma2/python/Screens/Menu.py", line 92, in runScreen
04:51:33.1497 { D }   File "/usr/lib/enigma2/python/Screens/Menu.py", line 103, in openDialog
04:51:33.1498 { D }   File "/usr/lib/enigma2/python/mytest.py", line 317, in openWithCallback
04:51:33.1500 { D }     dlg = self.open(screen, *arguments, **kwargs)
04:51:33.1500 { D }   File "/usr/lib/enigma2/python/mytest.py", line 339, in open
04:51:33.1503 { D }     self.execBegin()
04:51:33.1503 { D }   File "/usr/lib/enigma2/python/mytest.py", line 246, in execBegin
04:51:33.1505 { D }     c.execBegin()
04:51:33.1505 { D }   File "/usr/lib/enigma2/python/Screens/Screen.py", line 98, in execBegin
04:51:33.1507 { D }   File "/usr/lib/enigma2/python/Screens/ServiceInfo.py", line 148, in information
04:51:33.1508 { D }     videocodec =  ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "HEVC", "H265", "CAVS", "-" )[self.info and self.info.getInfo(iServiceInformation.sVideoType)]
04:51:33.1509 { D } IndexError: tuple index out of range
04:51:33.1510 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap instance at 0xaee83bc0>>,('OkCancelActions', 'ok')) failed)

the log show tuple index out of range,can openatv team fix it .A lot of people in china wil be much happy if  fixed.

**Comment by opfans** [comment]
I use https://github.com/openatv/enigma2/pull/1077 the file authored by nx111,it does not work on this issue.

**Comment by tzyy1970** [comment]
I have the same problem, starting in 2019.

**Comment by lexlong2007** [comment]
I have the same problem, starting in 2019.

**Comment by ROCFM** [comment]
I have the same problem

**Comment by ROCFM** [comment]
I have the same problem

**Comment by atvcaptain** [comment]
you say a china video you have used and get the crash ?

**Comment by opfans** [comment]
> you say a china video you have used and get the crash ?

Enigma2 works ok when you watch  cavs program,but can not use your remote control to view cavs serviceinfo(serviceinfo includes sid ,vpid ,apid ,videosize,videocode...) ,it wil crash .Mpeg2 ,mpeg4, h264, hevc,h265 service have no this issue.This issue happened recently,it is ok with openatv image before 2019

**Comment by arn354** [comment]
https://github.com/openatv/enigma2/commit/277120cd4548e319627ce1802fc81cc5039a8d58 fixed thx
