### ISSUE TITLE
PIP not working corret with ZAP timer

### ISSUE THREAD

**Issue by drahdiwaberl1** [openatv/enigma2#1088]
when a ZAP timer is performed while watching TV using PIP, the "channel +" button does not work correct.

For example: 
watching channel 3 with PIP channel 4.
then ZAP timer is performed with zap to channel 2
then I watch channel 2 with PIP channel 4
then I turn off PIP, I only watch channel 2 (no PIP)
when I press "channel+" button, it switches to channel 4 and not to channel 3. 

Wenn ein programmiertes "umschalten" via Timer passiert während ich PIP schaue, funktioniert danach das weiterschalten ("Programm rauf" Taste) nicht korrekt. 

Beispiel:
Kanalbelegung:
1 ORF 1
2 ORF 2
3 ARD
4 ZDF

Timer Programmierung "umschalten" um 19:00 Uhr auf ORF 2.

Um 18:50 sehe ich ARD und im PIP das ZDF.
Um 19:00 wird umgeschalten auf ORF2. Dann sehe ich ORF2 und im PIP das ZDF. Wenn ich danach das PIP wegmache, schaue ich nur noch ORF2 (ohne PIP). Wenn ich dann die "Programm rauf" Taste drücke, sollte er eigentlich von ORF 2 (Kanal2) auf ARD (Kanal 3) umschalten. Tatsächlich schaltet er aber auf Kanal 4 (ZDF)...

**Comment by jogibaer1948** [comment]
Welche einstellung hast du im OSD?
![Uploading 1_0_19_5274_41D_1_C00000_0_0_0_20220703100155.jpg…]()

**Comment by 4l3x2k** [comment]
The behavior can be reproduced.

OpenATV 7.1 - 20220707 - sf8008

The last selected focus (main image or PiP) is decisive.

Is the focus on the main image while the shift timer is active
and the PiP is deactivated, then the expected channel (here
i.e. ARD) is displayed.

Is the focus on the PiP while the toggle timer is active and
the PiP is deactivated, then the channel (here ZDF HD) from the
PiP displayed in the main image.

Therefore, a temporary solution would be to focus on the main image
before the PiP is deactivated.

**Comment by 4l3x2k** [comment]
Problem still persists.

OpenATV 7.3 - 20230812 - sf8008

@drahdiwaberl1
Is this still a problem for you?
Does the temporary solution work for you?
