### ISSUE TITLE
ServiceInfo.py amends

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1089]
`elif self.type == self.IS_HD:
			if info.getInfo(iServiceInformation.sGamma) > 0:
				return False
			else:
				return video_width >= 721 and video_width < 1980`

needs amending to

`elif self.type == self.IS_HD:
			if info.getInfo(iServiceInformation.sGamma) > 0:
				return False
			else:
				return video_width >= 720 and video_width < 2160`

*************************************************************************************

`elif self.type == self.IS_4K: 
			if info.getInfo(iServiceInformation.sGamma) > 0:
				return False
			else:
return video_width > 2160 and video_width <= 3840`

needs amending to

`elif self.type == self.IS_4K: 
			if info.getInfo(iServiceInformation.sGamma) > 0:
				return False
			else:
return video_width >= 2160 and video_width <= 3840`

**Comment by kiddac** [comment]
In fact this entire componet is confusing. 
SD you reference height.
HD you reference width
4k you reference width

maybe it should be as openvix do

elif self.type == self.IS_SD:
			return video_height < 720
		elif self.type == self.IS_HD:
			return video_height >= 720 and video_height < 2160
		elif self.type == self.IS_1080:

elif self.type == self.IS_4K:
			return video_height >= 2160

**Comment by atvcaptain** [comment]
i have 4k videos detect as hd when change back
ideo
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 5 frames
Muxing mode                              : Header stripping
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 21 min
Width                                    : 3 840 pixels
Height                                   : 1 600 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant

**Comment by Ev0-BH** [comment]
I OBH we use:

elif self.type == self.IS_4K:
return video_height >= 1200

**Comment by jbleyel** [comment]
Hi @kiddac , can you please test your changes and make a pull?

**Comment by wedebe** [comment]
8K should also be considered ;)

**Comment by jbleyel** [comment]
> 8K should also be considered ;)

If we have the first 8K model . Yes

**Comment by AbuBaniaz** [comment]
Has this been resolved please?

**Comment by jbleyel** [comment]
> Has this been resolved please?

You can provide a pull.

**Comment by AbuBaniaz** [comment]
Please double check. I had to tweak the first part as 720x576 were showing as HD.

**Comment by IanSav** [comment]
I think that checking and managing resolution decisions should become a library function.  That was all interpretations of resolutions will be applied consistently.

**Comment by AbuBaniaz** [comment]
I agree that would be a better idea in the long term. For the present, is the pull request OK?

**Comment by IanSav** [comment]
If you mean https://github.com/openatv/enigma2/pull/2821 then it has failed its Sonar checks.  @jbleyel will need to explore and explain what went wrong.
