### ISSUE TITLE
minor bug on color red cancel button

### ISSUE THREAD

**Issue by nikkijd** [openatv/enigma2#110]
Azbox Premium HD+
Openatv 4.3

Setup > System 

I just notice that Cancel Red button don't work, i was expecting that when i press it would be same function when i click the "Exit" button.

i didn't check in other areas of the settings.

cheers

**Comment by arn354** [comment]
In which context?
Red Button is not always CANCEL.

**Comment by auxius** [comment]
Actually what i meant is BACK sir, sorry.
