### ISSUE TITLE
Kodi won't start on OpenATV 6.3

### ISSUE THREAD

**Issue by vojtechj** [openatv/enigma2#1103]
Hi, I created this issue so that it is easier to track the status of Kodi on OpenATV 6.3.
If you don't like this, just delete it, but I find it easier to look here than to search every time on the forum to see if it has already been resolved.
Can I somehow help with this issue? I know from the forum, that we have to wait for some developers to update something, but it was long ago.

**Comment by atvcaptain** [comment]
with dm800 yes not working :) some more infos needed

**Comment by vojtechj** [comment]
mutant hd51

**Comment by atvcaptain** [comment]
yes we have report to mutant for long time and wait for update gles libs, only mutant can fix it

**Comment by thawtes** [comment]
Hallo @atvcaptain I sent you a PM for https://github.com/openatv/enigma2/issues/1100

**Comment by atvcaptain** [comment]
issue we cant fix it only mutant self, must recompile the opengl driver, but looks support hd51 now stopped

**Comment by vojtechj** [comment]
Können wir wenigstens den source code oder Dokumentation bekommen?

**Comment by atvcaptain** [comment]
was open source is gibt es alles im git, aber Hersteller hat Treiber ja gefixt sodas kodi wieder geht

**Comment by vojtechj** [comment]
also kann ich ruich zum 6.3 updaten und kodi wird schon funktioniren?

**Comment by vojtechj** [comment]
It's working, thanks a lot.
