### ISSUE TITLE
HbbTV on ERT returns wrong page

### ISSUE THREAD

**Issue by MCelliotG** [openatv/enigma2#1108]
needs an AIT patch that is already implemented on OpenPLI/SDG and Vix images. Please do not ignore this, OpenATV is the only image ERT's HbbTV does not work as it should.

**Comment by arn354** [comment]
Which one?

**Comment by MCelliotG** [comment]
Oh sorry, did not paste the patch link. There you go!
https://github.com/OpenPLi/enigma2/pull/1212/commits/044ee64d1b4bc13937e93293420d1397a3f072ee

**Comment by MCelliotG** [comment]
So, anyone?

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/commit/b9d7cf3216b43bd395c19475088d23f9a02108c6

**Comment by MCelliotG** [comment]
thank you! Can't wait for the update to come!
