### ISSUE TITLE
H9combo & flashonline

### ISSUE THREAD

**Issue by TwolDE** [openatv/enigma2#1118]
Has anyone tried to flash the h9combo because the it doesn‘t work for me - had to change it to -r -k (and then it worked) you just get the going to flash msg from flashonline and then it completes .... without flashing. As you don‘t trap the ofgwrite output cannot see the issue.

**Comment by atvcaptain** [comment]
at the moment h9combo we wait for final solution for multiboot, flashonline and backup solution without the final solution cant fix, please wait

**Comment by atvcaptain** [comment]
now include
