### ISSUE TITLE
openatv-6.2-zgemmah9s-20190406_usb

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1120]
Hello this version is causing blue screen of death when trying to do manual scan and then press green button
![WhatsApp Image 2019-04-06 at 17 18 26](https://user-images.githubusercontent.com/45090310/55670704-608e8a80-5890-11e9-9e30-66ac7940c639.jpeg)

**Comment by atvcaptain** [comment]
thx for the info fixed tomorrow

https://github.com/openatv/enigma2/commit/ed27f97203e7e72b3db4032b26099e402fdb3d06
