### ISSUE TITLE
crash bluescreen

### ISSUE THREAD

**Issue by vuplususer** [openatv/enigma2#1126]
Hi hello I have problem when try to change to channel (Love Nature HD) at Eutelsat9B 9.0E and it give me crash and bluescreen
my box: VuSoloSE

-- also I have problem sometime when (Restart Gui) the box dont reboot and no respond until switch off/on the back switch 
Is it common problem in OpenATV image?
because I have friend who has Restart Gui problem as me

**Comment by atvcaptain** [comment]
we need the crash log, please send the file you found /home/root/logs thx

**Comment by vuplususer** [comment]
ok here log 
[enigma2_crash_1554913261.log](https://github.com/openatv/enigma2/files/3064861/enigma2_crash_1554913261.log)

also I like to add that I use Vhannibal Settings

**Comment by atvcaptain** [comment]
https://github.com/openatv/MetrixHD/commit/136386d4c8a415acca4426e1c9b2150987eb0883

some of your picons cant load, we add a workaround

**Comment by vuplususer** [comment]
ok thanks 
and how about Restart Gui problem is it normal thing

**Comment by atvcaptain** [comment]
without log no idea, you can test: menu -> system -> logs enable e2 log, reboot box and test, when you get the issue  send the log same place as the crash log

**Comment by vuplususer** [comment]
when I enable both debug log and twisted log as many times I try the box restart gui ok 
of course there
[Enigma2-debug-20190410_19-37-51.log](https://github.com/openatv/enigma2/files/3065109/Enigma2-debug-20190410_19-37-51.log)
 crash log every time 

when I disable debug log and twisted log still enable the box will not restart gui from first try and there no crash log 

and when enable debug log again and disable twisted log the box restart gui ok and there crash log
