### ISSUE TITLE
Remove Default Satellite Packages 

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1132]
Hello, 
Please remove the default sat packages that are created when we flash with openATV.
Let the user install the channels.

**Comment by atvcaptain** [comment]
use atv 6.3

**Comment by ozone1864** [comment]
I am planning to migrate to 6.3 everytime I think about it 
But its still in Public Beta so do you recommend migration ?
My Box is H9S

**Comment by atvcaptain** [comment]
flash new you can backup your settings, and restore, or wait some days we merge atv 6.3 changes to 6.2 too, when iam back at home

**Comment by ozone1864** [comment]
Backup of settings will backup everything including metrixHD skin settings and recording/EPG ....
As I see in advanced backup settings only /home is ticked do I need to include something else ?
