### ISSUE TITLE
OpenATV 6.2 (AC3/ DTS) Issue

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1134]
Dear Captain,
Playback on H9S of movies with DTS audio doesn't work if downmix to stereo is disabled.
Can you check !
Thanks,

**Comment by atvcaptain** [comment]
more infos needed, dts is not dts to many different codec version exist, and send sample file with mega

**Comment by ozone1864** [comment]
its like 10GB bluray movie .mkv
**Video**
ID                                       : 1
Format                                   : VC-1
Format profile                           : Advanced@L3
Codec ID                                 : V_MS/VFW/FOURCC / WVC1
Codec ID/Hint                            : Microsoft
Duration                                 : 2h 28mn
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Audio**
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Format profile                           : MA / Core
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 2h 28mn
Bit rate mode                            : Variable
Bit rate                                 : Unknown / 1 509 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Compression mode                         : Lossless / Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Comment by ozone1864** [comment]
On 6.3 same problem
DTS is not working unless downmix to stereo is on

**Comment by atvcaptain** [comment]
hw not support this we cant change any
