### ISSUE TITLE
Zgemma H9 Combo crash terrestrial 

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1135]
please fix this crash ChannelSelection
[enigma2_crash_1555596298.log](https://github.com/openatv/enigma2/files/3097972/enigma2_crash_1555596298.log)
...

**Comment by atvcaptain** [comment]
looks you add a private copy of this file: https://github.com/oe-alliance/oe-alliance-tuxbox-common/blob/master/src/terrestrial.xml, with old infos  ? when yes add the original and test again,
when you restore old settings atv before 6.1 etc. restore to factory and start with new settings again

**Comment by Marchella1983** [comment]
**atvcaptain**
Atv 6.3 installed in its pure form is not what copies is not added, Zgemma H7s no problem with that...

**Comment by atvcaptain** [comment]
send a copy from /etc/enigma2/settings

**Comment by Marchella1983** [comment]
[settings.zip](https://github.com/openatv/enigma2/files/3098051/settings.zip)

**Comment by Marchella1983** [comment]
crash occurs in ChannelSelection when selecting Terrestrial
![1_0_1_580_14_1_3522E18_0_0_0_20190419172132](https://user-images.githubusercontent.com/28537448/56423931-a3585580-62c7-11e9-9ad4-7e254c53335d.jpg)
