### ISSUE TITLE
openatv-6.2-zgemmah9s-20190513_usb (SOFTCAM ISSUE)

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1154]
Dear Captain,
In this last version softcam is not working using oscam servers. I have installed latest softcam panel 3.0 universal but after that no softcams category in the downloadable plugins menu were found.
So I installed manually the softcam oscam **enigma2-plugin-softcams-oscam-11392_openatv_all** didn't start the oscam at all. Can you check 
Regards,

**Comment by arn354** [comment]
no support for softcams, sorry.

**Comment by ozone1864** [comment]
RIP OpenATV
