### ISSUE TITLE
openATV 6.2/6.3 CAM issue for Captain

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1155]
Dear Captain,            **Only Captain close the issue**
Please check the problem which is used by thousand of people. Oscam and cccam are not working anymore tested many panels and cams they aren't appearing in feeds. Tried manual installation still the same.
You know that enigma2 box is useless without CAM so please check to avoid migration of users to other images.
Regards,

**Comment by arn354** [comment]
check forums how to solve the issue that the url of the secretfeed (3rdparty) is no longer reachable.
And which is maybe the new and current working url.
There is no issue with openATV.
