### ISSUE TITLE
fix Listbox.py

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1159]
Please add this fix for ATV (Edit mode on)
https://github.com/OpenPLi/enigma2/commit/1f8498f43388abebc969a5bcc6fadc01d055de5e#diff-e8acc63b1e238f3255c900eed37254b8
![1_0_1_5DF_15_56_3520000_0_0_0_20190516185128](https://user-images.githubusercontent.com/28537448/57859369-3b385900-780c-11e9-9464-bce695933a2d.jpg)

**Comment by atvcaptain** [comment]
added
