### ISSUE TITLE
multiboot broken

### ISSUE THREAD

**Issue by dj-garf** [openatv/enigma2#1221]
hi,
after installing any of your new images in from may multiboot refuses to change the partition on my zgemma h7s
i can select a different partition and confirm to reboot but it always boots back up to the new openatv image
solved this by flashing a older image and it then works again as it should

**Comment by atvcaptain** [comment]
flash one time a new image with usb http://images.mynonpublic.com/openatv/nightly/index.php?open=zgemmah7

**Comment by dj-garf** [comment]
forgot to put im using openatv 6.3

**Comment by atvcaptain** [comment]
older image not working you must install after install new usb image ,  new images from all teams
