### ISSUE TITLE
Flash Online not work !

### ISSUE THREAD

**Issue by thawtes** [openatv/enigma2#1231]
hi,
flash online not work
go to flash online 
Retrieving image list - Please wait...
result Cannot find images - please try later
but there is new image

device VU+ DUO2

thanks

**Comment by Tony-il-Capo** [comment]
It seems to work OK here, same device, latest OpenATV 6.3
Latest listed v6.2/6.3 image from 21-05-2019

Did not test actual image download.

**Comment by thawtes** [comment]
interesting, unfortunately not working on my device.
my device installed image openatv-6.3-vuduo2-20190519_usb.zip
openatv-6.3-vuduo2-20190521_usb.zip but does not appear in the list and does not download and install

**Comment by thawtes** [comment]
I have detected a problem with me, fault my ticket sorry....
