### ISSUE TITLE
add ModuleControl.py

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1251]
Captain please add Converter from Nicolasi ModuleControl.py for ATV
![1_0_1_19A_A_1_3522F30_0_0_0_20190528083941](https://user-images.githubusercontent.com/28537448/58449298-4cdf0200-8124-11e9-9021-6fb7340aad91.jpg)

https://mega.nz/#!5BNS3Swa!M5Xw4FHDTAN8EfBH7VCz54B6zvXCFcz-dVg4aGK2uRU

**Comment by jbleyel** [comment]
I will remove this, because not needed.
You can use check this.
https://github.com/littlesat/skin-PLiHD/search?q=CiModuleControl
