### ISSUE TITLE
Problem with auto subtitle selection on zgemma i55 plus

### ISSUE THREAD

**Issue by fonias1986** [openatv/enigma2#1268]
Hello

I have problem with subtitle selection on zgemma i55 plus. when i play a video with embedded subtitles does not automatically select any subtitle. the problem is in 6.2 and 6.3 also and i think has to do with the specific box which is arm. Because the same images in different box(es) are working fine with the same video and subtitles are autoselected.

Anyone has any clue?

**Comment by jbleyel** [comment]
Please try again with ATV 7.0 and reopen if not fixed
