### ISSUE TITLE
Progress Time and Resume playback on H9S

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1277]
Dear Captain,
After deep checking and testing, the problem causing fault in resuming playback and watching progress time of movies is the bug in service hisilicon.
When watching "**.TS**" files this feature is available since service hisilicon created two files for the movie below:
"**.cuts**" and "**.meta**" are created 

![TS](https://user-images.githubusercontent.com/45090310/57583890-f47df280-74dd-11e9-98ba-32f99a5e1015.png)

But when watching "**.mkv**" or "**.mp4**" or any other extension these two files are never created for the movie below:
no "**.cuts**" and "**.meta**" were created.

![walking](https://user-images.githubusercontent.com/45090310/57583899-0f506700-74de-11e9-8ff0-f930c8e23b08.png)

I tried on hundreds of movies with different codecs and extensions but the results are the same. Please fix this issue and we will appreciate that to make H9S box complete.

Best Regards and Keep on the good work,

System: OpenATV 6.2/6.3

**Comment by jbleyel** [comment]
cuts and meta is only for TS.
