### ISSUE TITLE
if the conffile variable remains as None, the code ends with an error

### ISSUE THREAD

**Issue by s3n0** [openatv/enigma2#1285]
Hello. Apparently, the `conffile` variable state is not well-treated when it is returned from the `self.confPath()` function. If the `conffile` variable remains as None, the code ends with an error.
https://github.com/openatv/enigma2/blob/a23dd118bb21e004a409089c39b8727482769e38/lib/python/Screens/OScamInfo.py#L94

The CrashLOG file is here: https://www.linuxsat-support.com/thread/137572-openatv-softcam-feed-discussion-thread/?postID=498895#post498895

> 23:21:32.7972 { } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-06-19 23:21:32+0100 [-] File "/usr/lib/enigma2/python/Screens/OScamInfo.py", line 94, in getUserData
> 
> 23:21:32.7978 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-06-19 23:21:32+0100 [-] TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by Schimmelreiter** [comment]
See my comment at the very bottom:
https://github.com/openatv/enigma2/commit/12b29fb7fb0d0ebe80331b2216c43ce8ad6b6e7b#commitcomment-34004838
