### ISSUE TITLE
SoftcamSetup.py

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1290]
class SoftcamSetup(Screen, ConfigListScreen):
	skin = """
	<screen name="SoftcamSetup" position="center,center" size="560,450" >
		<widget name="config" position="5,10" size="550,90" />
		<widget name="info" position="5,100" size="550,300" font="**Fixed;18**" />

font="Fixed;18" />

Fixed is not a standard font name. (is a metrx skin font name)

20:07:21.4282 [!W!] gdi/font.cpp:583 setFont [eTextPara] FONT 'Fixed' MISSING!

Surely this should be "Regular"

**Comment by Schimmelreiter** [comment]
This was taken from OpenPLi, so it seems to be a standard font name there ... so we probably will want to make "Fixed" a standard font in OpenATV too to increase compatibility (not only with this one).

**Comment by kiddac** [comment]
"Regular" is what skinners use and set. 
Making it a standard OpenATV achieves nothing, correct me if I am wrong, but this value is set in skin.xml in the skin and if no 3rd party skinners are using it, then its still going to result in an error and default back to "Regular". Even default openatv skin has never used it. 
We are not openpli.

**Comment by Schimmelreiter** [comment]
No, we aren't OpenPLi ... but images have to maintain a certain degree of compatibility if we want to continue getting good plugins that not only work on one image.

**Comment by Schimmelreiter** [comment]
https://github.com/KravenHD/KravenVB/commit/f515f9ba7604c0e6cd07dbeae62e5af0e575f37e

**Comment by kiddac** [comment]
So he has had to put an extra line in his skin because softcamsetup.py is wrong. :)

**Comment by Schimmelreiter** [comment]
Well, no ...
If PLi has it, plugins made by people using PLi will likely use it too ... so sooner or later you need it anyways :)

**Comment by arn354** [comment]
Should be added as alias or defintion to skin_default. A screen within enigma2 code should be defined using skin_default .

https://github.com/oe-alliance/oe-alliance-e2-skindefault/blob/master/skin_default.xml

or
https://github.com/openatv/enigma2/blob/6.3/skin.py#L28

**Comment by Schimmelreiter** [comment]
Abu Baniaz made the necessary change to skin_default.xml :)

**Comment by AbuBaniaz** [comment]
PLi have this in their skins
```
<font name="Fixed" filename="andale.ttf" scale="100"/>
```

**Comment by AbuBaniaz** [comment]
Almost all images have andale.ttf
I have added it to the emergency skin, skin_default.xml

**Comment by AbuBaniaz** [comment]
Can this issue be closed now or does it still need work?
