### ISSUE TITLE
PluginBrowser.py

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1308]
self["text"] that displays messages like "Downloading plugin information. Please wait..."
never clears when list has populated. Therefore if placed over the main list of plugins only a full background on the list with higher zposition will over ride it.  Not ideal for skinners.

Suggest adding 
self["text"].setText("")

to the end of 
def updateList(self) module.

**Comment by jbleyel** [comment]
please try again with 7.0 or 7.1 and reopen if not fixed
