### ISSUE TITLE
Recording Feature

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1316]
Dears,
When recording a channel, we can't pause recording if there is advertisements and then resume recording again.
Can you fix this issue or consider as enhancement feature ?
Regards,

**Comment by Tony-il-Capo** [comment]
Why would you need that? Normally, when we record something is to watch later, right?

 You can cut the parts you want out later using "Cutlist editor", with this you can actually edit (remove parts you don' t want) recording file, so you reduce recording file size to a minimum, useful if you plan to save the recording for future 're-watching', or you can simply jump advertisements using remote keys when watching?

**Comment by ozone1864** [comment]
Its better to have that option to pause recording its available everywhere

**Comment by Tony-il-Capo** [comment]
I personally don't see the point of this.
You will have to be simultaneous watching the channel that is recording and physically interacting with STB, much simpler taking the approach I described above.
To me personally, it's useless.

**Comment by rchovan** [comment]
That will be nice feature if it will be available without user interaction. In the past, TV providers sent special information on channel, that advertisement started and finished. I remember VHS devices which can pause recording during adv. But now, when TV providers depend on money from advertisement I'm not sure if this special information is broadcasted.

**Comment by ozone1864** [comment]
@Tony-il-Capo all other receivers got this feature , I am not asking your opinion about this thing.
Cutlist editor is shitty by the way and fucking useless.

**Comment by Tony-il-Capo** [comment]
Of course... :man_facepalming:  now you start offending the developers that make software for you for free.
You better go buy "all other receivers" then, or better go back to "VHS devices" as suggested. :rofl: 

But seriously, if you don't know how to use Cutlist Editor, or the 10 other ways of removing commercials without reencoding your recordings, blame only yourself.

You can also present us a code that magically detect commercials and stop recording and then start again.

**Comment by ozone1864** [comment]
Hahaha, do you call yourself a developer ?
Dude do you know how to read ?
You didn't even answer the main issue and talking with yourself ?
Next time I will mention captainATV directly its my fault, I didn't mention him from the beginning sorry.

**Comment by Tony-il-Capo** [comment]
:man_facepalming: 
Try again, read again! Where  did **I** said **I** was a developer?

> Cutlist editor is shitty by the way and fucking useless.

> now you start offending the developers that make software for you for free.

Mention atvcaptain again like you did already a dozen times... like a stupid baby crying for attention.
