### ISSUE TITLE
Oscam Info

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1335]
Another strange issue. 

If I visit oscam info screen via plugins menu, the OscamInfoMenu screen doesn't skin correctly. 

![image](https://user-images.githubusercontent.com/6818561/61150630-d0d62900-a4db-11e9-9af0-1d61337f3a9c.png)

yet if I visit the exact same screen via info panel (i renamed the red button to check this), then the screen appears how it should be skinned. 

Anyone know why this happens and how it can be fixed. 

![image](https://user-images.githubusercontent.com/6818561/61150739-0e3ab680-a4dc-11e9-8a96-a621c5041157.png)

I am using 	<widget name="mainmenu"
for the menu list in the skin???

**Comment by kiddac** [comment]
further testing this, all oscam info screens seem to be broken via the plugins menu?

![image](https://user-images.githubusercontent.com/6818561/61151772-9e79fb00-a4de-11e9-82aa-f04c49b21974.png)

**Comment by Schimmelreiter** [comment]
I can't skin for toffee and I didn't change anything skin related in oscaminfo, it must have been like this forever.
Anyways, anyone else, e.g. ipKay or HD75 have to look into this.

**Comment by kiddac** [comment]
Looking further in the files on my box, 
I have 2 oscaminfos. 1 a screen, the other a plugin.  

/lib/python/Screens/OScamInfo.py
/enigma2/python/Plugins/Extensions/OscamInfo/plugin.py

I presume one of them is no longer needed?

This is from a fresh flash, installing softcams via the secret feed. 

So these 2 different oscam Infos seem to be clashing

**Comment by kiddac** [comment]
Yep deleting the oscam info plugin, causes no issues and the oscam info in infopanel and decryption & parental control then display as it should. 
Therefore it looks like the plugin needs removing from the secret feed install, if that is the culprit. 
I am pretty sure I haven't installed oscam ifo plugin separately on top of the new way.

**Comment by kiddac** [comment]
I have just uninstalled oscam, and reinstalled and it doesn't seem to bring it in as a seperate plugin. 
So maybe it was a backup plugin that loaded when I re-flashed. 

There doesn't seem to be any issues with the current oscaminfo screen 
So I will close this issue and check again when I do a new flash.
