### ISSUE TITLE
Online Update Problem

### ISSUE THREAD

**Issue by thawtes** [openatv/enigma2#1347]
hello, online update not work pls look my logs

`openATV Enigma2 crash log

crashdate=01:03:14 24/07/2019
compiledate=Jul 19 2019
skin=MetrixHD/skin.MySkin.xml
sourcedate=2019-07-18
branch=6.3
rev=2.8.0-21098-g52258d5
component=Enigma2

stbmodel=duo2
stbmodel=dm8000
kernelcmdline=libata.force=1:1.5Gbps bmem=192M@64M bmem=384M@512M memc1=788M ubi.mtd=0 root=ubi0:rootfs rootfstype=ubifs rw rootflags=sync
nimsockets=NIM Socket 0:
imageversion=box_type=vuduo2
imageissue=

...
2019-07-24 01:03:14+0300 [-] KEY: 399 1 KEY_GREEN GREEN
01:03:14.6953 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] [ActionMap] Keymap 'ColorActions' -> Action = 'green'
01:03:14.7026 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] [SKIN] processing screen UpdatePlugin:
01:03:14.7643 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] [SKIN] processing screen UpdatePlugin_summary:
01:03:14.7716 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] [SCREENNAME]  ['UpdatePlugin_summary', 'SimpleSummary']
01:03:14.7748 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] [SCREENNAME]  UpdatePlugin
01:03:14.8035 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] Traceback (most recent call last):
01:03:14.8056 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 1655, in doActivityTimer
01:03:14.8083 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 1578, in CheckDate
01:03:14.8108 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 01:03:14+0300 [-] TypeError: not all arguments converted during string formatting
01:03:14.8114 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method UpdatePlugin.doActivityTimer of <class 'Plugins.SystemPlugins.SoftwareManager.plugin.UpdatePlugin'>>,()) failed)
dmesg
....
`

**Comment by atvcaptain** [comment]
what language do you use, possible problems with the PO file

**Comment by thawtes** [comment]
> 
> 
> what language do you use, possible problems with the PO file

turkish language

**Comment by atvcaptain** [comment]
i dont know not test i am not home

**Comment by hd75hd** [comment]
i think this is the fix ...

https://github.com/openatv/enigma2/commit/c11e5679cd3e55ccf6b8d6cfde5df4a8a96defde

**Comment by atvcaptain** [comment]
yes tr.po you can revert my first test

**Comment by thawtes** [comment]
> 
> 
> i think this is the fix ...
> 
> [c11e567](https://github.com/openatv/enigma2/commit/c11e5679cd3e55ccf6b8d6cfde5df4a8a96defde)



> 
> 
> yes tr.po you can revert my first test

i don't think this is the issue !

my SoftwareManager/plugin.py update last this [e75907e](https://github.com/openatv/enigma2/commit/e75907e53d0edd44c156936060fa4976e5ebda3b) commit.

after this log

`13:23:25.4873 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] KEY: 401 0 KEY_BLUE BLUE
13:23:25.7118 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 191 1
13:23:25.7197 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] KEY: 401 1 KEY_BLUE BLUE
13:23:25.7457 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] [ActionMap] Keymap 'InfobarExtensions' -> Action = 'quickmenu'
13:23:25.8244 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] [SKIN] processing screen QuickMenu:
13:23:25.8525 { W } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] warning, skin is missing element key_blue in <class 'Plugins.Extensions.Infopanel.QuickMenu.QuickMenu'>
13:23:25.8915 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] [SKIN] processing screen SimpleSummary:
13:23:25.8970 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] [SCREENNAME]  ['QuickMenu_summary', 'SimpleSummary']
13:23:25.9001 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:25+0300 [-] [SCREENNAME]  QuickMenu
13:23:26.9558 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 6c 1
13:23:26.9630 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:26+0300 [-] KEY: 108 0 KEY_DOWN DOWN
13:23:26.9659 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:26+0300 [-] [ActionMap] Keymap 'SetupActions' -> Action = 'down'
13:23:27.1908 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 6c 1
13:23:27.1987 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:27+0300 [-] KEY: 108 1 KEY_DOWN DOWN
13:23:27.4038 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 67 1
13:23:27.4109 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:27+0300 [-] KEY: 103 0 KEY_UP UP
13:23:27.4131 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:27+0300 [-] [ActionMap] Keymap 'SetupActions' -> Action = 'up'
13:23:27.6348 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 67 1
13:23:27.6424 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:27+0300 [-] KEY: 103 1 KEY_UP UP
13:23:28.2038 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 6a 1
13:23:28.2111 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] KEY: 106 0 KEY_RIGHT RIGHT
13:23:28.2132 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] [ActionMap] Keymap 'SetupActions' -> Action = 'right'
13:23:28.4350 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 6a 1
13:23:28.4423 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] KEY: 106 1 KEY_RIGHT RIGHT
13:23:28.5958 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
13:23:28.6028 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] KEY: 352 0 KEY_OK OK
13:23:28.6049 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] [ActionMap] Keymap 'SetupActions' -> Action = 'ok'
13:23:28.6130 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] [SKIN] processing screen SoftwarePanel:
13:23:28.7003 { W } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] warning, skin is missing element key_green_pic in <class 'Plugins.Extensions.Infopanel.SoftwarePanel.SoftwarePanel'>
13:23:28.7204 { W } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] warning, skin is missing element key_red_pic in <class 'Plugins.Extensions.Infopanel.SoftwarePanel.SoftwarePanel'>
13:23:28.7515 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:28+0300 [-] checkTraficLight
13:23:29.2535 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:29+0300 [-] executing opkg  --add-dest /:/ update
13:23:29.2539 [   ] base/console.cpp:110 execute [eConsoleAppContainer] Starting /bin/sh
13:23:29.2589 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:29+0300 [-] [SKIN] processing screen SimpleSummary:
13:23:29.2676 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:29+0300 [-] [SCREENNAME]  ['SoftwarePanel_summary', 'SimpleSummary']
13:23:29.2722 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:29+0300 [-] [SCREENNAME]  SoftwarePanel
13:23:29.2792 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
13:23:29.2876 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:29+0300 [-] KEY: 352 1 KEY_OK OK
13:23:33.2558 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:33+0300 [-] executing opkg list-upgradable
13:23:33.2562 [   ] base/console.cpp:110 execute [eConsoleAppContainer] Starting /bin/sh
13:23:33.2571 [   ] base/ebase.cpp:279 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 104(16)
13:23:35.3783 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:35+0300 [-] 89
13:23:35.3800 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:35+0300 [-] packagenr89
13:23:35.3816 [   ] base/ebase.cpp:279 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 104(16)
13:23:37.6648 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 18f 1
13:23:37.6718 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] KEY: 399 0 KEY_GREEN GREEN
13:23:37.8918 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 18f 1
13:23:37.8989 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] KEY: 399 1 KEY_GREEN GREEN
13:23:37.9015 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] [ActionMap] Keymap 'ColorActions' -> Action = 'green'
13:23:37.9076 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] [SKIN] processing screen UpdatePlugin:
13:23:37.9677 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] [SKIN] processing screen UpdatePlugin_summary:
13:23:37.9743 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] [SCREENNAME]  ['UpdatePlugin_summary', 'SimpleSummary']
13:23:37.9783 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:37+0300 [-] [SCREENNAME]  UpdatePlugin
13:23:38.0116 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:38+0300 [-] Traceback (most recent call last):
13:23:38.0139 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:38+0300 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 1656, in doActivityTimer
13:23:38.0189 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:38+0300 [-]     self.CheckDate()
13:23:38.0209 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:38+0300 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 1579, in CheckDate
13:23:38.0256 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:38+0300 [-]     "Do you still want to update?") % (getMachineBrand(), getMachineName())
13:23:38.0278 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-07-24 13:23:38+0300 [-] TypeError: not all arguments converted during string formatting
13:23:38.0283 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method UpdatePlugin.doActivityTimer of <class 'Plugins.SystemPlugins.SoftwareManager.plugin.UpdatePlugin'>>,()) failed)


dmesg
`

**Comment by thawtes** [comment]
i remove
code line 1579 arguments % (getMachineBrand(), getMachineName())
after work !!!
