### ISSUE TITLE
Zgemma H9S USB 3.0 Port Problem

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1384]
Dear OpenATV,
Today I did migration from openatv **6.2** to openatv **6.3** latest image stable version.
The problem is **usb 3.0 port** in zgemma h9s is not reading harddisks(**NTFS**) any more I tried many but same problem.
Tried flash memory(**fat32**)  it worked.
What could be the problem ?
@atvcaptain @Schimmelreiter @AbuBaniaz  @iPkay 
Regards,

**Comment by ozone1864** [comment]
@atvcaptain  @Schimmelreiter   @AbuBaniaz

**Comment by arn354** [comment]
dmesg?
you should check the buildfiles from your box - maybe something has changed.
Either it is a USB-Port issue or a filesystem format issue.

**Comment by arn354** [comment]
opkg list-installed |grep ntfs

probably ntfs simply is not installed.

**Comment by ozone1864** [comment]
Ntfs is working normal on the usb 2.0 port 
The problem is only on 3.0 port its reading fat32 only.
I am back now to openatv 6.2 and all working again

**Comment by ozone1864** [comment]
@atvcaptain is this problem have to do with the new zgemma h9s since it has usb 3.0 port missing ?
