### ISSUE TITLE
EPGCache Search Modes

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#140]
The original enigma2 has 4 search modes
    SIMILAR_BROADCASTINGS_SEARCH 
    EXAKT_TITLE_SEARCH
    PARTIAL_TITLE_SEARCH
    PARTIAL_DESCRIPTION_SEARCH

The openvix and openatv enigma2 has 4 search modes too, BUT the last is different
    SIMILAR_BROADCASTINGS_SEARCH 
    EXAKT_TITLE_SEARCH
    PARTIAL_TITLE_SEARCH
    START_TITLE_SEARCH

I think this could be an issue in some plugins.

**Comment by Schimmelreiter** [comment]
https://github.com/openatv/enigma2/commit/5e188f17ed7e2421cacbe5f5abe4c8248189e7a5 and ff.
