### ISSUE TITLE
black line on top of screen watching IPTV channel with 2160p60/50hz output

### ISSUE THREAD

**Issue by opfans** [openatv/enigma2#1400]
My receiver model is VU + Ultimo 4K using openatv6.3 image.When watching IPTV channel with 2160P 50/60HZ hdmi output,there is a black line on top of screen.There is no such issue with openpli or openblackhole image.Set receive 1080p 50/60HZ output,no such issue.

**Comment by iPkay** [comment]
https://github.com/openatv/enigma2/commit/7eb31407dcfdf8efec486c0ebd0cd338044b5a61
