### ISSUE TITLE
fix InputDeviceSetup Default

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1427]
if you select, for example, a Formuler remote control and return the Zgemma bullet to Default, it will only work if you select Zgemma H.S/H.2S/H.2H/H5/H7

**Comment by Marchella1983** [comment]
in the InputDeviceSetup default settings for Zgemma is default...

I select F1/F3/F4/F4-TURBO/TRIPLEX remote control from Formuler, it works...

I'm growing up with a Zgemma default remote, it doesn't work...

I choose Zgemma H.S/H.2S/H.2H/H5/H7, works...

**Comment by Marchella1983** [comment]
please fix this bug.
https://github.com/zgemma-star/meta-zgemma/issues/54

**Comment by atvcaptain** [comment]
we use the settings we get from zgemma

looks zgemma git https://github.com/zgemma-star/meta-zgemma/blob/master/conf/machine/h7.conf#L17

h7 use type 21 and not 28

28 are h9 and h9combo

**Comment by atvcaptain** [comment]
send a picture from your rcu with code 28

**Comment by atvcaptain** [comment]
i have add code 28 new model too

https://github.com/openatv/enigma2/commit/226258f56cfc2c9341942177fe5834c455e9eecd

**Comment by Marchella1983** [comment]
It's the same as H7's.

thanks to Captain, now it works...
