### ISSUE TITLE
openatv 6.4 and subssupport

### ISSUE THREAD

**Issue by vuplususer** [openatv/enigma2#1443]
Hi when I use subssupport 1.5.6 in OpenATV 6.4 with manual search for subtitle it give me green-screen and crash 

[enigma2_crash_1572573964.log](https://github.com/openatv/enigma2/files/3797674/enigma2_crash_1572573964.log)
[enigma2_crash_1572573949.log](https://github.com/openatv/enigma2/files/3797675/enigma2_crash_1572573949.log)
[enigma2_crash_1572488453.log](https://github.com/openatv/enigma2/files/3797676/enigma2_crash_1572488453.log)

**Comment by thawtes** [comment]
> 
> 
> Hi when I use subssupport 1.5.6 in OpenATV 6.4 with manual search for subtitle it give me green-screen and crash
> 
> [enigma2_crash_1572573964.log](https://github.com/openatv/enigma2/files/3797674/enigma2_crash_1572573964.log)
> [enigma2_crash_1572573949.log](https://github.com/openatv/enigma2/files/3797675/enigma2_crash_1572573949.log)
> [enigma2_crash_1572488453.log](https://github.com/openatv/enigma2/files/3797676/enigma2_crash_1572488453.log)

problem is SubsSupport plugin no openATV 6.4

**Comment by vuplususer** [comment]
but why I only have this problem with oatv 6.4 even if try automatic subtitle search
others images work like a charm.
did not try oatv 6.3 until now but probably work too I know 6.4 still under (beta) test phase but 
this image must stable image from OpenATV team since OpenATV 5.1

**Comment by thawtes** [comment]
> 
> 
> but why I only have this problem with oatv 6.4 even if try automatic subtitle search
> others images work like a charm.
> did not try oatv 6.3 until now but probably work too I know 6.4 still under (beta) test phase but
> this image must stable image from OpenATV team since OpenATV 5.1

SubsSupport codes need to be update

**Comment by vuplususer** [comment]
ok I probably closed this until fix comes from mx3L
