### ISSUE TITLE
EMC(Enhanced Movie Center) Issue on Zgemma H9S OpenATV 6.2/6.3

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1460]
Dears,
Please note that the following problem which will be state is not found in the old movie center or movielist plugin, it is being faced only in the enhanced movie center.
The problem is whenever you watch a movie it should save a progress in the bar, but some players don't work with cuts files, they have their own save and resume way without cuts files.
The old movie center still get the progress bar and resume function without cuts files, can this function be adjusted in the enhanced movie center ?
Thanks with best regards,

**Comment by 4l3x2k** [comment]
I think this issue can be closed as it does affect a external plugin which is not openatv's enigma2.

Please create an issue at https://github.com/betonme/e2openplugin-EnhancedMovieCenter.

Issue can be closed.
