### ISSUE TITLE
OpenATV 6.3 python-sqlite3-tests for installing cocy 0.41 not available

### ISSUE THREAD

**Issue by routi4444** [openatv/enigma2#1469]
Hi,
I would like to inform about a possibly missing package "python-sqlite3-tests" at OpenATV 6.3
escribed issue may also be related with this one: mnlipp/CoCy4Enigma2#2

**Comment by atvcaptain** [comment]
have you more infos
we dont have cocy 0.41 and sqlite3-test on feed

we have
python-cocy_0.1.6
python-sqlite3_2.7.15

and depends ask not for a test

Depends: libc6 (>= 2.28), libpython2.7-1.0 (>= 2.7.15), libsqlite3-0 (>= 3.25.3), python-core, python-datetime

Depends: python-distribute, python-misc, python-modules

**Comment by atvcaptain** [comment]
no answer i close now
