### ISSUE TITLE
OpenVPN Client

### ISSUE THREAD

**Issue by e2world** [openatv/enigma2#1475]
Status Window Information Stop OpenVPN

Buchstabendreher: OpneVPN wurde gestoppt!

**Comment by atvcaptain** [comment]
wo hast das gesehen, im de.po sehe ich das nicht

**Comment by e2world** [comment]
![1_0_19_10B_6_85_C00000_0_0_0_20191215135926](https://user-images.githubusercontent.com/34108544/70862967-49398e00-1f43-11ea-9836-1b7f5a793f03.jpg)

**Comment by atvcaptain** [comment]
irgend ein plugin installiert, weil in atv sehe ich den String nicht

**Comment by e2world** [comment]
Stimmt hast Recht, kommt aus VPN Config Changer im OpenVPN Plugin im ATV gibt es keine entsprechende Meldung beim Beenden des Dienstes. Dann schau ich mal ob ich im Source vom Plugin eine de.po finde ^^

**Comment by e2world** [comment]
Ist gefixt .. https://www.opena.tv/plugins/35693-openvpn-server-auswahl-post312321.html#post312321

Kannst Closen
