### ISSUE TITLE
FSTAB mounts and PIcons

### ISSUE THREAD

**Issue by leaskovski** [openatv/enigma2#1476]
Hi Team,

Whilst running OpenATV 6.2, I have noticed that Pions do not work when storing them in "/media/hdd/picon" if I am using FSTAB for mounting my NAS drive for use as a replacement HDD.  EPG and timeshift/recordings save fine as the mount is there at startup (as it should be), however picons don't seem to get pulled.  If I change the mount over to AutoFS, then Picons display fine from the NAS drive, however then I have to edit the locations of files from the /media/hdd location to /media/autofs/...

I believe this is down to how picon.py functions and how it pulls in mounts.  From what I have seen in the code, the autofs mounting and unmounting seems to connect in well with the harddisk manager code and thus the mounting of a device from autofs gets triggered and thus the globalsearch list used to store picon locations, gets populated correctly.  When using FSTAB, it doesn't look like this gets populated right and thus the picons cannot be found.

It should be fairly easy to replicate this issue, by having a single mount on your system that uses FSTAB and is a HDD replacement, and also contains a "picon" folder.

Thanks

**Comment by AbuBaniaz** [comment]
Does this issue exist on 6.3/6.4? The developers are working on 6.4 and the current branch is 6.3, so they wont be looking at older images

**Comment by leaskovski** [comment]
I upgraded my box to 6.3 with a fresh install and then did a similar setup and had the same issue.  If I use just FSTAB for mounting a drive (on my NAS), I see the exact same issue where the /media/hdd/picon doesn't get picked up.

**Comment by AbuBaniaz** [comment]
Almost all distros prohibit networked resources for picons. This is normal.

**Comment by leaskovski** [comment]
Ok, got you!  Thanks for the info.  I will close this then.

**Comment by arn354** [comment]
First - it depends on the Skin which picon renderer is used. You identified picon.py . I do not see any restriction related to hdd replacement setting. picon.py should show anything which is located on that path (or symlink) /media/hdd/picon - where ever it comes from (fstab, autofs, local files, local storage, symlink). Only problem could be that the mount is not yet available on start of enigma2 (wake up of NAS or anything else). A fstab mount is only triggered once on boot. If it is not there or fails before enigma2 starts - there is no reconnect for fstab mounts. I have no issues with picons from a NAS device using autofs an a symlink at for example /picon to /myautofsmount/picon

**Comment by Huevos** [comment]
"/media/net" is specifically disabled in OpenATV default picon renderer. "/media/autofs" is allowed.

In OpenViX both are disabled.
