### ISSUE TITLE
crash Zgemma H9Twin

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1478]
Hi, please fix this bug on the Zgemma H9Twin.
If the module is installed in the lower Ci slot we get crash...
https://mega.nz/#!YRdniIYD!qQrzUETM0-c_EjKrRilEJ7NJZGzL4JKA70gvZgczpd0

**Comment by jbleyel** [comment]
please try agin with 7.0 or 7.1 and reopen if not fixed .. we also need crashlog
