### ISSUE TITLE
Locking a channel with Parental Control causes crash

### ISSUE THREAD

**Issue by Katmai6** [openatv/enigma2#1516]
I am using Openatv 6.4 image on a Vu+ Uno 4k SE. Everything came pre-installed by the dealer. 

My problem is, if I enable "Parental Control" and lock any channel, then when I open that channel,it wants me to enter the pin,I enter it then it causes either a blue-screen error or just an error and it says if it happens 3 times it will reset.

**Comment by Katmai6** [comment]
Here is the bluescreen:

![DSC_1347](https://user-images.githubusercontent.com/6520753/73528594-d8c8cc80-441d-11ea-8054-a464a08786b1.JPG)

**Comment by s3n0** [comment]
Hi.
Just add debug-LOG, which the user forgot to add:
```
01:32:18.3656 {   } [SCREENNAME]  InfoBarSummary
01:32:18.3777 {   } Traceback (most recent call last):
01:32:18.3783 {   }   File "/usr/lib/enigma2/python/mytest.py", line 244, in processDelay
01:32:18.3790 {   }     callback(*retval)
01:32:18.3795 {   }   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
01:32:18.3803 {   }   File "/usr/lib/enigma2/python/Components/ParentalControl.py", line 177, in servicePinEntered
01:32:18.3808 {   }   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
01:32:18.3814 { E } TypeError: sc_playService() got an unexpected keyword argument 'adjust'
01:32:18.3815 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0xaf0dbe90>>,()) failed)
```
Discussion thread from this user is here: 
https://www.opena.tv/english-section/50773-locking-channel-using-parental-control-cause-bluescreen-2.html

**Comment by 4l3x2k** [comment]
This has been fixed.

Issue can be closed.
