### ISSUE TITLE
add  syntax

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1526]
Hi, please add  syntax 
.title ( )
https://github.com/openatv/enigma2/blob/49c1922d618350bab38d90e4c75109858bc34c8b/lib/python/Screens/Ci.py#L566

and

https://github.com/openatv/enigma2/blob/49c1922d618350bab38d90e4c75109858bc34c8b/lib/python/Plugins/SystemPlugins/CommonInterfaceAssignment/plugin.py#L68

**Comment by nickersk** [comment]
hi, PR would be better i think ...

**Comment by jbleyel** [comment]
Please provide more info or make a PR

**Comment by jbleyel** [comment]
Please reopen with more info.
