### ISSUE TITLE
24Hz and 25Hz Frames in playing

### ISSUE THREAD

**Issue by Kerberos1864** [openatv/enigma2#1531]
Dears,
When we set resolution to **1080P** in video settings and frame rate to auto.
We have noticed that it catches 3 types of frame rates only which are:
1. **60 Hz**
2. **50 Hz**
3. **24 Hz**

But not catching **25 Hz**, although if I change the settings to simple settings it catches **25Hz**
Can you solve the issue ?
Thank you,

**Comment by ozone1864** [comment]
@atvcaptain can you check please ?

**Comment by jbleyel** [comment]
Please provide more info.

**Comment by jbleyel** [comment]
Please reopen with more info.
