### ISSUE TITLE
Expanding the functionality of the graphical EPG

### ISSUE THREAD

**Issue by alec-cs** [openatv/enigma2#1532]
Hi,

I have upgraded the graphical EPG (EPG_TYPE_GRAPH) feature on my openATV 6.2 system.
I've modified the following:
- added Red button and Blue button options -> nextPage, prevPage, nextBouquet, prevBouquet
- Channel +/-  -> nextPage / prevPage or nextBouquet / prevBouquet

I made the modifications in the graphic EPG menu with the corresponding text additions.

I think this makes the system much more usable and functional. This way I can use my system better.

If I post my changes (Pull requests), will you merge them?

Regards,
Alec

**Comment by nickersk** [comment]
merged.
