### ISSUE TITLE
Discrepency in .eit file with actual programme recorded

### ISSUE THREAD

**Issue by trumpton** [openatv/enigma2#1534]
I have noticed a discrepancy in the contents of a .ts.meta file and a .eit file for the same recording, where the .ts.meta file contents agree with the recording, but the .eit file appears to be for a completely different programme - note that the correct programme is being recorded.
I've attached an example, which includes details of my setup.
It looks to me that the .ts.meta file is generated from information in the EPG (in my case, captured with CrossEPG), and the .eit file is extracted from the stream.
Steve
[eit.zip](https://github.com/openatv/enigma2/files/4270099/eit.zip)

**Comment by 4l3x2k** [comment]
Please try again with openatv's EPG.

If the problem persists please report any issue at either

https://github.com/E2OpenPlugins/e2openplugin-CrossEPG

or

https://github.com/oe-alliance/e2openplugin-CrossEPG

Issue can be closed.
