### ISSUE TITLE
Overriding plugin loadSkin is not longer possible

### ISSUE THREAD

**Issue by technic** [openatv/enigma2#1535]
Hi, this is cross-post from https://github.com/OpenPLi/enigma2/issues/2473. I believe, that we need to have common solution to this, because it is related to plugins API.

### Summary
Some bigger plugins do not store screen xml data in the python, but use separate xml file instead. Then it is loaded with help of `loadSkin(path)` function.
Some time ago it was possible to redefine plugin skin with the xml coming from global skin. The trick was that plugins are loaded before skin is loaded and `loadSkin` does not override screen entry if it already exists. Is there another option now?

However, In open-atv this feature was removed long time ago with this commit https://github.com/openatv/enigma2/commit/1d1b987a4fb603f409877e108f37c8c103677fac by @andyblac

**Comment by IanSav** [comment]
Please use the OpenPLi thread for any discussions on this topic.

**Comment by AbuBaniaz** [comment]
Does this resolve the issue:
https://github.com/OpenPLi/enigma2/commit/b23a0df2f82c4905d32a4ab2d10d9c097b6f0e08

**Comment by IanSav** [comment]
That patch has been reverted.  The skin and plugin that triggered the patch were the cause of the issue.

**Comment by atvcaptain** [comment]
so problem solve
