### ISSUE TITLE
Sat finder doesn't resume after signallost

### ISSUE THREAD

**Issue by pa4th** [openatv/enigma2#1545]
Hello, 

Sat finder remains on zero after  a complete signal lost.  I have to search each evening  to get the Astra sats due to mobile living.  But with the new Zgemma 9.2S latest openpli, openatv and EGAMI the sat finder works only when there is a signal, but after a lost it won't recover.

I hope that this is the correct form for this problem

Thijs

**Comment by 4l3x2k** [comment]
I'am not able to test this with sat equipment but with a simple antenna for dvb-t or dvb-t2 the signal can be completely lost but moving it to a comfortable position it gains a signal again.

Tested with signal finder.

This issue can be closed.
