### ISSUE TITLE
InitGeolocation crashing enigma2 when it receives invalid json

### ISSUE THREAD

**Issue by Azureit** [openatv/enigma2#1559]
InitGeolocation from mytest.py will crash enigma2 process if the request doesn't receive a valid json.(As an example this will happen with captive portals) 
> 08:04:07.2443 [   ] gdi/grc.cpp:211 thread [gRC] main thread is non-idle! display spinner!
08:04:07.7152 { D } Traceback (most recent call last):
08:04:07.7155 { D }   File "/usr/lib/enigma2/python/mytest.py", line 33, in <module>
08:04:07.7161 { D }     Tools.Geolocation.InitGeolocation()
08:04:07.7164 { D }   File "/usr/lib/enigma2/python/Tools/Geolocation.py", line 49, in InitGeolocation
08:04:07.7168 { D }   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
08:04:07.7172 { D }   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
08:04:07.7175 { D }   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
08:04:07.7181 { D } ValueError: No JSON object could be decoded

**Comment by nickersk** [comment]
@IanSav can you pls take a look on this?

**Comment by Azureit** [comment]
ok will test it. thanks

**Comment by IanSav** [comment]
If possible could you please capture the content coming back from the geolocation server so I can analyse what is going on.

**Comment by Azureit** [comment]
@IanSav It's a captive portal html

**Comment by Tony-il-Capo** [comment]
I got several reports about boot crashes and boot loops when using Prepaid data SIM cards. These need to "activate" using the "'Active portal'. 
Any first request will be redirected to that page.
Not sure if that mentioned commit fixed the issue because after 'activating' the SIM, internet works as normal.

Workaround is first access via browser or even block ip-api.com by hijacking DNS  to NXDOMAIN, or block STB connection(s), or just disconnect LAN cable. :unamused:

**Comment by IanSav** [comment]
This code update should address all these "unexpected data" crashes.  The code will now return with no geolocation data.  If the receiver has already been configured then this has no impact.  If the receiver is being set up for the first time then the standard image defaults will apply.

**Comment by nickersk** [comment]
@IanSav there are still some issues: https://www.opena.tv/openatv-6-4-rueckmeldungen/50949-nach-update-vom-13-02-2020-zeitzone-im-system-falsch-eingestellt.html

**Comment by IanSav** [comment]
I am not sure if the translations to English are correct but it seems that the newest code is not causing further issues.  If there is a problem please let me know exactly what the problem may be and please get me some logs so I can diagnose the problem.

If people manually correct their timezone are there any further issues?
