### ISSUE TITLE
Add support for Kathrein EXD 1532 and EXD 2532 in unicable.xml

### ISSUE THREAD

**Issue by MBollig** [openatv/enigma2#1589]
Please add the following code to the **Kathrein** element of **unicable.xml** to support **EXD 1532** and **EXD 2532**

`<product name="EXD 1532 1Sat 16UBs" positions="1" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140"/>`

`<product name="EXD 1532 1Sat 24UBs" positions="1" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140" scr17="1775" permpin17="022" scr18="1825" permpin18="136" scr19="1875" permpin19="227" scr20="1925" permpin20="177" scr21="1975" permpin21="044" scr22="2025" permpin22="123" scr23="2075" permpin23="210" scr24="2125" permpin24="097"/>`

`<product name="EXD 1532 1Sat 30UBs" positions="1" format="SCD2" scr1="970" permpin1="151" scr2="1010" permpin2="052" scr3="1050" permpin3="133" scr4="1090" permpin4="124" scr5="1130" permpin5="205" scr6="1170" permpin6="196" scr7="1210" permpin7="187" scr8="1250" permpin8="178" scr9="1290" permpin9="099" scr10="1330" permpin10="232" scr11="1370" permpin11="198" scr12="1410" permpin12="111" scr13="1450" permpin13="190" scr14="1490" permpin14="002" scr15="1530" permpin15="201" scr16="1570" permpin16="140" scr17="1610" permpin17="022" scr18="1650" permpin18="136" scr19="1690" permpin19="227" scr20="1730" permpin20="177" scr21="1770" permpin21="044" scr22="1810" permpin22="123" scr23="1850" permpin23="210" scr24="1890" permpin24="097" scr25="1930" permpin25="125" scr26="1970" permpin26="206" scr27="2010" permpin27="072" scr28="2050" permpin28="248" scr29="2090" permpin29="192" scr30="2130" permpin30="003"/>`

`<product name="EXD 1532 2Sat 8UBs " positions="2" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178"/>`

`<product name="EXD 1532 2Sat 16UBs" positions="2" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140"/>`

`<product name="EXD 1532 2Sat 24UBs" positions="2" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140" scr17="1775" permpin17="022" scr18="1825" permpin18="136" scr19="1875" permpin19="227" scr20="1925" permpin20="177" scr21="1975" permpin21="044" scr22="2025" permpin22="123" scr23="2075" permpin23="210" scr24="2125" permpin24="097"/>`

`<product name="EXD 1532 2Sat 30UBs" positions="2" format="SCD2" scr1="970" permpin1="151" scr2="1010" permpin2="052" scr3="1050" permpin3="133" scr4="1090" permpin4="124" scr5="1130" permpin5="205" scr6="1170" permpin6="196" scr7="1210" permpin7="187" scr8="1250" permpin8="178" scr9="1290" permpin9="099" scr10="1330" permpin10="232" scr11="1370" permpin11="198" scr12="1410" permpin12="111" scr13="1450" permpin13="190" scr14="1490" permpin14="002" scr15="1530" permpin15="201" scr16="1570" permpin16="140" scr17="1610" permpin17="022" scr18="1650" permpin18="136" scr19="1690" permpin19="227" scr20="1730" permpin20="177" scr21="1770" permpin21="044" scr22="1810" permpin22="123" scr23="1850" permpin23="210" scr24="1890" permpin24="097" scr25="1930" permpin25="125" scr26="1970" permpin26="206" scr27="2010" permpin27="072" scr28="2050" permpin28="248" scr29="2090" permpin29="192" scr30="2130" permpin30="003"/>`

`<product name="EXD 2532 1Sat 8UBs " positions="1" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178"/>`

`<product name="EXD 2532 1Sat 16UBs" positions="1" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140"/>`

`<product name="EXD 2532 1Sat 24UBs" positions="1" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140" scr17="1775" permpin17="022" scr18="1825" permpin18="136" scr19="1875" permpin19="227" scr20="1925" permpin20="177" scr21="1975" permpin21="044" scr22="2025" permpin22="123" scr23="2075" permpin23="210" scr24="2125" permpin24="097"/>`

`<product name="EXD 2532 1Sat 30UBs" positions="1" format="SCD2" scr1="970" permpin1="151" scr2="1010" permpin2="052" scr3="1050" permpin3="133" scr4="1090" permpin4="124" scr5="1130" permpin5="205" scr6="1170" permpin6="196" scr7="1210" permpin7="187" scr8="1250" permpin8="178" scr9="1290" permpin9="099" scr10="1330" permpin10="232" scr11="1370" permpin11="198" scr12="1410" permpin12="111" scr13="1450" permpin13="190" scr14="1490" permpin14="002" scr15="1530" permpin15="201" scr16="1570" permpin16="140" scr17="1610" permpin17="022" scr18="1650" permpin18="136" scr19="1690" permpin19="227" scr20="1730" permpin20="177" scr21="1770" permpin21="044" scr22="1810" permpin22="123" scr23="1850" permpin23="210" scr24="1890" permpin24="097" scr25="1930" permpin25="125" scr26="1970" permpin26="206" scr27="2010" permpin27="072" scr28="2050" permpin28="248" scr29="2090" permpin29="192" scr30="2130" permpin30="003"/>`

`<product name="EXD 2532 2Sat 8UBs " positions="2" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178"/>`

`<product name="EXD 2532 2Sat 16UBs" positions="2" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140"/>`

`<product name="EXD 2532 2Sat 24UBs" positions="2" format="SCD2" scr1="975" permpin1="151" scr2="1025" permpin2="052" scr3="1075" permpin3="133" scr4="1125" permpin4="124" scr5="1175" permpin5="205" scr6="1225" permpin6="196" scr7="1275" permpin7="187" scr8="1325" permpin8="178" scr9="1375" permpin9="099" scr10="1425" permpin10="232" scr11="1475" permpin11="198" scr12="1525" permpin12="111" scr13="1575" permpin13="190" scr14="1625" permpin14="002" scr15="1675" permpin15="201" scr16="1725" permpin16="140" scr17="1775" permpin17="022" scr18="1825" permpin18="136" scr19="1875" permpin19="227" scr20="1925" permpin20="177" scr21="1975" permpin21="044" scr22="2025" permpin22="123" scr23="2075" permpin23="210" scr24="2125" permpin24="097"/>`

`<product name="EXD 2532 2Sat 30UBs" positions="2" format="SCD2" scr1="970" permpin1="151" scr2="1010" permpin2="052" scr3="1050" permpin3="133" scr4="1090" permpin4="124" scr5="1130" permpin5="205" scr6="1170" permpin6="196" scr7="1210" permpin7="187" scr8="1250" permpin8="178" scr9="1290" permpin9="099" scr10="1330" permpin10="232" scr11="1370" permpin11="198" scr12="1410" permpin12="111" scr13="1450" permpin13="190" scr14="1490" permpin14="002" scr15="1530" permpin15="201" scr16="1570" permpin16="140" scr17="1610" permpin17="022" scr18="1650" permpin18="136" scr19="1690" permpin19="227" scr20="1730" permpin20="177" scr21="1770" permpin21="044" scr22="1810" permpin22="123" scr23="1850" permpin23="210" scr24="1890" permpin24="097" scr25="1930" permpin25="125" scr26="1970" permpin26="206" scr27="2010" permpin27="072" scr28="2050" permpin28="248" scr29="2090" permpin29="192" scr30="2130" permpin30="003"/>`

**Comment by MBollig** [comment]
#1595

**Comment by AbuBaniaz** [comment]
That was merged. You can close issue when ready.
