### ISSUE TITLE
Please correct the error

### ISSUE THREAD

**Issue by atefganm** [openatv/enigma2#1612]
ERROR: enigma2-6.7+gitAUTOINC+da5f04b887-r0 do_populate_lic: QA Issue: enigma2: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=751419260aa954499f7abaabaa882bbe
enigma2: The new md5 checksum is b234ee4d69f5fce4486a80fdaf4a4263
enigma2: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
                    GNU GENERAL PUBLIC LICENSE
                       Version 2, June 1991

 Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

                            Preamble

...
  `Gnomovision' (which makes passes at compilers) written by James Hacker.

  <signature of Ty Coon>, 1 April 1989
  Ty Coon, President of Vice

This General Public License does not permit incorporating your program into
proprietary programs.  If your program is a subroutine library, you may
consider it more useful to permit linking proprietary applications with the
library.  If this is what you want to do, use the GNU Lesser General
Public License instead of this License.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
enigma2: Check if the license information has changed in /home/atef/build-enviroment/builds/openeight/release/dm820/tmp/work/dm820-oe-linux/enigma2/6.7+gitAUTOINC+da5f04b887-r0/git/LICENSE to verify that the LICENSE value "GPLv2" remains valid [license-checksum]
ERROR: enigma2-6.7+gitAUTOINC+da5f04b887-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: Logfile of failure stored in: /home/atef/build-enviroment/builds/openeight/release/dm820/tmp/work/dm820-oe-linux/enigma2/6.7+gitAUTOINC+da5f04b887-r0/temp/log.do_populate_lic.1568
ERROR: Task (/home/atef/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb:do_populate_lic) failed with exit code '1'
WARNING: enigma2-6.7+gitAUTOINC+da5f04b887-r0 do_configure: QA Issue: enigma2: configure was passed unrecognised options: --with-bwlcd96 --with-gstversion --with-machinebuild [unknown-configure-option]
NOTE: Tasks Summary: Attempted 6916 tasks of which 5812 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb:do_populate_lic
Summary: There were 51 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:985: image] Error 1

**Comment by nickersk** [comment]
which distro are you building?

**Comment by nickersk** [comment]
ah, i see. openeight. so ask there. here we are on openatv. closing.

**Comment by betacentauri** [comment]
I will fix it. 
By the way only one line like this needs to be added:
https://github.com/oe-alliance/oe-alliance-core/blob/4.3/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb#L6

**Comment by nickersk** [comment]
yes and in the past i had an issue with some distro as they used diferrent deploy strategy. thats why i answered so.
