### ISSUE TITLE
HITUBE 4K COMBO: Stuck on boot after install satipclient on OpenATV6.4

### ISSUE THREAD

**Issue by g6094199** [openatv/enigma2#1649]
Hi,

FYI

today i received my new HITUBE 4K (my 1st ARM box ever) with default O-ATV 6.2 preinstalled. 
1st thing was to upgrade to the latest 6.4 nightly (20200512).
After that i installed satip-client (vtuner) and rebooted. Now the box is stuck in boot and never comes up again. I have to reinstall O-ATV now.

**Comment by atvcaptain** [comment]
driver not support vtuner at the moment, we wait for a solution from vendor
