### ISSUE TITLE
HITUBE 4K COMBO: minisatip server announces wrong tuner on OATV6.4

### ISSUE THREAD

**Issue by g6094199** [openatv/enigma2#1652]
Hi,

as is see the minisatip server on the HITUBE 4K COMBO announces not all capable tuner to the clients. Since the device is capable of DVB-S2/T2/C the S" is missing. 
See:
![image-4150120086](https://user-images.githubusercontent.com/37833326/82049295-5e634600-96b6-11ea-8258-7d8616289c65.jpg)

Also the capability is wrong since the has an DVB-T/C combo and a DVB-S tuner. So there might be the bug.

**Comment by atvcaptain** [comment]
its not a bug, driver not support vtuner at the moment, last info driver team working to add the feature in next  6-12 month

**Comment by g6094199** [comment]
Hi,
so its the same problem why the satipclient isnt wokring, right? No vtuner support, atm?

Sash

**Comment by atvcaptain** [comment]
driver not support vtuner at the moment, we wait for a solution from vendor
