### ISSUE TITLE
About.py 

### ISSUE THREAD

**Issue by Marchella1983** [openatv/enigma2#1660]
Hi, please correct the About.py line.
`		AboutText += _("Selected Image:\t\t%s") % _("STARTUP_") + str(slot) + "  (" + part + " " + bootmode + ")\n"`
for more accurate information
`                AboutText += _("Selected Image:\t\t") + part + " " + bootmode + "\n"`
![1_0_1_6979_1B_FE_2300000_0_0_0_20200519211333](https://user-images.githubusercontent.com/28537448/82351156-a6b39880-9a15-11ea-8f4e-495d2a1bd468.jpg)

**Comment by atvcaptain** [comment]
i see no issue

**Comment by Marchella1983** [comment]
It's not like I'm writing that it's a problem, I wanted a more colorful output...

But the choice is always yours, I just suggested my idea...
