### ISSUE TITLE
Zgemma H9S NTFS Problem

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1667]
Dears,
NTFS formatted devices cannot be read on the 3.0 USB port of  zgemma H9S 
Any help ?
I am using latest version 6.3 .
It was working fine on openatv 6.2 (15 may 2019 version).
Regards,

**Comment by ozone1864** [comment]
The new H9S box comes with no usb 3.0 port.
But why it should do a problem for me

**Comment by atvcaptain** [comment]
next image we have add full feature/speed NTFS driver check again in 2-3 days
