### ISSUE TITLE
Youtube Downloading Blue Screen

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1669]
Dear @Taapat and @atvcaptain ,

When I try to download a video from youtube and then checking the active download page.
My system crash. Any idea ?
Hardware: Zgemma H9S
Software: OpenAtv 6.3 latest version stable

Regards,
[enigma2_crash_1590392348.log](https://github.com/openatv/enigma2/files/4676901/enigma2_crash_1590392348.log)
[enigma2_crash_1590395386.log](https://github.com/openatv/enigma2/files/4676902/enigma2_crash_1590395386.log)

**Comment by ozone1864** [comment]
As discussed with @Taapat ,
Looks like this is a bug in OpenAtv in Tools/Downloader.py
In this commit @captain changed the function pageEnd in HTTPProgressDownloader and added to it from OpenPli using of variable self.end_callback: openatv/enigma2@917eb8c

Unfortunately, he missed that all changes must be like this, where self.end_callback is defined on init: OpenPLi/enigma2@bcfdaae

**Comment by arn354** [comment]
https://github.com/openatv/enigma2/commit/14fec2912b73efd7104859203e2042461d1b1b2e
