### ISSUE TITLE
XEaio 3.0.7 not working on a few different boxes in newest releases

### ISSUE THREAD

**Issue by wallie2912** [openatv/enigma2#1670]
Hope this is the right place to highlight this.
Tried on zgemma H2S, and VUDUO2. latest 6.4 AND 6.3 release. the plugin for no QR code. This normally happens when the box has no internet connection.

rolling back to xtream editor 2.12 it all works fine. 

Other boxes seems to be fine on latest releases, these are the only 2 I have been able to test and get this problem

thanks

**Comment by atvcaptain** [comment]
ask plugin dev
