### ISSUE TITLE
H9S NTFS(External HDD) on USB 3.0 Port

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1680]
Dears @zgemma-star and @atvcaptain ,
Installed the image openatv-6.3-zgemmah9s-20200530_usb
The NTFS external disks still not working on the USB 3.0 port.
Check dmesg log

tntfs: module license 'Commercial. For support email ntfs-support@tuxera.com.' taints kernel.
Disabling lock debugging due to kernel taint Tuxera NTFS driver 3017.7.4.6 [Flags: R/W MODULE].
Built against headers 4.4.35_hi3798mv2x
#1 SMP Tue Dec 12 14:16:24 CST 2017 arm Running on kernel 4.4.35
#1 SMP Thu May 28 17:20:10 UTC 2020 armv7l
WARNING: Running kernel does not match configured kernel headers the driver was built with! The driver needs to be rebuilt with the correct kernel headers!

[dmesgLog.txt](https://github.com/zgemma-star/meta-zgemma/files/4706170/dmesgLog.txt)

**Comment by ozone1864** [comment]
@atvcaptain any solution ?

**Comment by 4l3x2k** [comment]
This is an external kernel module that has nothing to do with openatv's enigma2.

Use an linux compatible format like ext2/3/4 or report any issues regarding this kernel module to https://github.com/oe-alliance/oe-alliance-core

This issue can be closed.
