### ISSUE TITLE
Enigma2.pot - "Choose what you want the PIP mode how to works". 

### ISSUE THREAD

**Issue by Snoete** [openatv/enigma2#1687]
Can somebody check: line #3823 msgid "Choose what you want the PIP mode _**how to works**_."  #3823 ?

Maybe: Choose how you want PIP mode to work.
Or: Choose what you want the PIP mode to do.

**Comment by neoatomic** [comment]
@Snoete , Solved with https://github.com/openatv/enigma2/pull/1702 . 
Should be fixed in the next build.
