### ISSUE TITLE
httplib.py

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#1707]
Can someone please explain to me the purpose of adding this to the httplib.py please ?

contains_disallowed_url_pchar_re = re.compile('[\x00- \x7f-\xff]')

and

match = _contains_disallowed_url_pchar_re.search(url) 
        if match: 
            raise InvalidURL("URL can't contain control characters.

It breaks many plugins namely the EPG Translator plugin which with this code included gives this crash on certain Eastern European languages

httplib.InvalidURL: URL can't contain control characters. '/m?hl=en&sl=auto&q=Skubi%20Du%203:%20Misteri%20filloi%20%20%20%207515%20Sub.%20Ang%207515%20Ata%20kan\xc3\xab%20zgjidhur%20misteret%20m\xc3\xab%20t\xc3\xab%20m\xc3\xabdha.%20Por%20ka%20mbetur%20ende%20nj\xc3\xab%20mister%20i%20pazbuluar,%20ai%20m\xc3\xab%20enigmatiku.Do%20t\xc3\xab%20shkojm\xc3\xab%20pas%20n\xc3\xab%20t\xc3\xab%20shkuar\xc3\xabn%20dhe%20do%20t\xc3\xab%20shohim%20si%20nisi%20gjith\xc3\xa7ka.%20Tek%20misteri%20i%20par\xc3\xab,%20q\xc3\xab%20i%20bashkoi%20dhe%20i%20b\xc3\xabri%20t\xc3\xab%20pandar\xc3\xab.' (found at least '\xc3')

Once the new code is removed from the httplib.py all is well again, so I would like to know the purpose of the new code because mines been removed now and I'm hoping that removing it wont cause any other adverse effects ?

Thanks.

**Comment by betacentauri** [comment]
Well, it's a security patch:
https://src.fedoraproject.org/fork/churchyard/rpms/python3/c/d3803a6dd6315aabaa684d77319cc25dddbee17d
If you speak about this. Do you use python3 or python2? I think in python2 we have reverted the patch.

**Comment by atvcaptain** [comment]
yes see this commit: https://github.com/oe-alliance/oe-alliance-core/commit/eb924b4b2d3ef5a0c6e27f8fc1b85b32d638ce5e#diff-edc64700710d890a7868f35486362064

**Comment by ian10951** [comment]
I use 2.7 still I think. ATV 6.4

As I say I've removed the code but was worried about other adverse effects, so I dont think its been reverted yet in 2.7

**Comment by betacentauri** [comment]
It seems it was also added here:
https://github.com/python/cpython/commit/e176e0c105786e9f476758eb5438c57223b65e7f#diff-2d7e33d530320d8491cb7d62326737d2

Well, reverting is not really a good solution. Why do we only have this problem??

**Comment by ian10951** [comment]
Yes that's where I've removed the code in order to address the crashes.

**Comment by betacentauri** [comment]
Then commit that.
For me not the best solution to revert security fixes, but I have no other idea how to fix that

**Comment by ian10951** [comment]
Sorry I've no idea how to commit something.

I just wanted to inform you of the problem and to ensure that my removal of this code didn't cause other problems. I am now satisfied that it wont and everything will be OK

Thanks.
