### ISSUE TITLE
Streams not closing

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1716]
Has anything changed in the last month or so, regarding the playing of IPTV streams.
Whether that be an amendment with HTTP client libraries or if streams are being kept alive and not closing correctly

I have 2 plugins
Jedi Maker Xtream which is a bouquet maker. Therefore using enigma2 to play the streams (this uses urllib2 library)
Xstreamity that is an IPTV player that plays the streams directly in the plugin. (this uses Requests library)

There has been lots of reports lately of IPTV streams not closing correctly on openatv 6.4
Therefore multiple lines are being opened at once causing the user issues if they only have a max connection of one user

This problem never used to happen.
Just trying to determine if this is something openatv 6.4 has changed or whether something else is the cause.

**Comment by atvcaptain** [comment]
no changes we work on 6.5 6.4 only little fixes not more see git logs
