### ISSUE TITLE
Enigma2 crash: eEPGCache_flushEPG expected 4 arguments, got 1

### ISSUE THREAD

**Issue by ToxicLand** [openatv/enigma2#1723]
Since the June 23 update (6.4), if i want to flush my EPG from the menu, enigma2 will crash with the following error: 

TypeError: eEPGCache_flushEPG expected 4 arguments, got 1
14:34:33.6848 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0xaf7e4328>>,()) failed)

Full crash log is attached. Also, EPG Import flush EPG is no longer functioning (same eEPGCache_flushEPG expected 4 arguments, got 1 error)
[enigma2_crash_1593088473.log](https://github.com/openatv/enigma2/files/4831222/enigma2_crash_1593088473.log)

**Comment by arn354** [comment]
https://github.com/openatv/enigma2/commit/2107a58011107ff32f75d1a34a0c70aa721c10ec

seems related to that change.
