### ISSUE TITLE
IPTV recordings maximum duration of 4 hours?

### ISSUE THREAD

**Issue by mitcd** [openatv/enigma2#1729]
IPTV recordings stop for a fixed 4 hours, although the timer has been set for longer
Recording file created is .stream

**Comment by nickersk** [comment]
recording on fat32? what is the size of saved file?

**Comment by mitcd** [comment]
.Stream File size : 8.40 GB
Duration  : 4 h 0 min
Recordings made by satellite or cable do not have this problem ... i have files with 20 Gb or more...
But they are in .ts format

**Comment by betacentauri** [comment]
I wrote the source code for this feature. I haven’t added such a limitation. Any errors/warnings in the logs?
Maybe webserver closes the connection. What happens when you watch a channel for 4 hours without zapping?

**Comment by 4l3x2k** [comment]
Issue is that OLD without any response to the developers question.

Issue can be closed.
