### ISSUE TITLE
A recent update has caused this

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#1736]
Can someone tell me the file used to bring up the single EPG so I can adjust the columns back to their correct sizes please ? 

https://i.ibb.co/stQjM0m/1-0-19-278-F-65-F020-FFFF0000-0-0-0-20200704051708.jpg

The same update has also added a stupid needless bracket to the time remaining in the InfoBar, which I would also like to remove.

**Comment by ian10951** [comment]
Further investigation into this has traced the issue to this update.

https://github.com/openatv/enigma2/commit/71e8847250cd0921bca1e90ae99b5a3ecac33316

I have reverted the new code added to the Epglist.py and the single EPG and information on the InfoBar are correct again. So some aspect of the new code added to incorporate the ICETV Plugin is not quite right.

**Comment by prl001** [comment]
My changes to EpgList.py that were adapted and applied by Captain do not affect buildSingleEntry(), which is what builds the list in the single channel EPG.

What seems to have happened is a change in how some time conversions work - the single EPG has a field for the day name, and then a field for the date/time, but the string that's being converted and put into the date/time field also includes the day names.

The "{" being added to date and time fields seems completely unrelated to the IceTV/EIT EPG merge change - those changes not only don't change buildSingleEntry() (though they do make other changes in EpgList.py, they make no changes at all to InfoBar, nor to the code that implements date formats.

**Comment by ian10951** [comment]
OK cool, thanks for the explanation.

What would you suggest is the best fix for this then ? Because I would prefer to add your new code back to the Epglist.py again, rather than having to use a single reverted py file in order to get the list to display correctly.

**Comment by prl001** [comment]
This appears to be the commit that caused the issue with the date formats in the single EPG:
https://github.com/openatv/enigma2/commit/91fb8f28375b8ca1a5d34363d9c97631432c6cc8#diff-876261af9a84d7655e748ee0fba5f589

It was made back in April, and not by me ;)

I'm still not sure about the wayward '{' charactes in the times, though.

**Comment by ian10951** [comment]
OK Thank You.

Adding your code back and just reverting https://github.com/openatv/enigma2/commit/91fb8f28375b8ca1a5d34363d9c97631432c6cc8#diff-876261af9a84d7655e748ee0fba5f589 does indeed fix the issue, so that commit does need reverting. However like you say, the bracket still remains in the InfoBar. Ive no idea whats adding this.

**Comment by prl001** [comment]
With 91fb8f2 reverted, do you still get the "{" in the list in the single EPG? And what about in the show duration (bottom right in the left-hand half of the single EPG screen)?

I've got some other stuff I need to do right now, but I'll have a dig around in the code to try to see where the "{" is coming from later this aftenoon my time (UTC+10).

**Comment by ian10951** [comment]
A picture is better than a thousand words.

[url=https://ibb.co/Lp6Mhs3][img]https://i.ibb.co/3hWwYPn/1-0-19-278-F-65-F020-FFFF0000-0-0-0-20200705055950.jpg[/img][/url]

But yes the rouge bracket is still there in the InfoBar and also bottom left of the Single List EPG screen too.

**Comment by prl001** [comment]
OK, I think I've found your "rouge" ;) brackets.

It's in some mistranslations in the en_GB.po file in
https://github.com/openatv/enigma2/commit/99ec3deb97725b8d79c62bad469beeff1fcc8002#diff-f12751a1ca92722305887179ed2c0f5a

Look for msgstr entries that contain `"{` In some places, the translation translates the date/time formats to a different format as well as adding the curly brace.

**Comment by artseluiko** [comment]
@prl001 you are right. I switched lang from en_GB to en_US and curly brackets were gone

**Comment by prl001** [comment]
The author of the commit might like to have a good look at fixing up the problems in those translations in en_GB.po.

**Comment by IanSav** [comment]
By the way, there shouldn't really need to be an en_US translation.  All code should be written using en_US as the base language.  All other languages including en_GB and en_AU should be translated from the base US language.
