### ISSUE TITLE
Recent update generate crash when modify mount partitions

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#1746]
Same problem with all OpenATV versions (6.3, 6.4 and 6.5). Use mount plugins to modify /dev/sdc1 mount to /medi/usb (instead /media/hdd and /dev/sda5 to /media/hdd instead /media/usb.
The mount modification is ok after reboot but there is a crash when do the modification, see log. Seems to be a kernel issue.
[enigma2_crash_1594539650.log](https://github.com/openatv/enigma2/files/4911000/enigma2_crash_1594539650.log)

**Comment by jbleyel** [comment]
please try again with ATV 7.0 and reopen if not fixed
