### ISSUE TITLE
enigma2.bb:do_compile

### ISSUE THREAD

**Issue by elhawaryna** [openatv/enigma2#1748]
ERROR: Task (/home/elhawary/openatv/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb:do_compile) failed with exit code '1'
Quando si costruisce openeight o non ora
Grazie

**Comment by nickersk** [comment]
hi, this is openatv e2 repo. if you build openeight, you should write there: github.com/Openeight/enigma2
