### ISSUE TITLE
Problem with Cyrillic in EIT in some transponders.

### ISSUE THREAD

**Issue by harryzz** [openatv/enigma2#1750]
After update i got some unreadable symbols  in EPG:  39E - 12271 H.  Only in this transponder i have problem with cyrlillic texts. On other transponders text are displayed correctly.

regards
Zahari

**Comment by mrslvd** [comment]
I have the same issue.
Best regards,
Miro

**Comment by Sentello** [comment]
Same here with Openatv 6.4

**Comment by mrslvd** [comment]
The file changed after update is  /usr/share/enigma2/encoding.conf . 
The attached file made cyrillic available at my place. I don't know exactly which row makes the magic. 
One problem exists - after updating very often this file is overwritten again.
[encoding.zip](https://github.com/openatv/enigma2/files/6020498/encoding.zip)

**Comment by mrslvd** [comment]
P.S. This file was shared with me in another forum...

**Comment by Sentello** [comment]
this helped me, thank you very much

**Comment by Sentello** [comment]
ok with every update  this config need to be recreated...

**Comment by jbleyel** [comment]
Please compare your encoding.conf with the original file.
>  https://github.com/openatv/enigma2/blob/6.4/data/encoding.conf

You file have many deleted entries.
Please do only add additional entries.
The syntax is very simple.

XXX YYY ZZZ	# 39E 12.271 H

XXX = TSID
YYY = ONID
ZZZ = Encoding 


Here an example:
13 1 ISO8859-2	# 0.8°W 11.823 H

**Comment by mrslvd** [comment]
I include the following line and it does not help:
1 1 ISO8859-5 # 39E 12.271 H
Also, I don't see anywhere in NOT original file something related with 39E
I still don;t understand where is the problem.
Regards

**Comment by jbleyel** [comment]
Are you sure about the transponder?
TSID = 1
ONID = 1

**Comment by mrslvd** [comment]
Yes, 
TSID: 0X0001
ONID: 0x0001
SID: 0x03f8
Video PID: 0x0210
Audio PID: 0x0211
PCR PID:  0x0210
PMT PID: 0x229
TXT PID: N/A

Modulation: QPSK
Orbital position: 39E
Frequency: 12271.0
Symbol rate: 30000
Polarization: H
Inversion: Auto
FEC: 7/8
Pilot: 2
Roll off: 0

**Comment by mrslvd** [comment]
P.S. I am not sure about encoding but I am not sure how to confirm it.

**Comment by jbleyel** [comment]
The zip file config has no default encoding:
`*   ISO8859-1`

The original file has also this line:
`1 1        # 0.8°W 12.687 H`

**Comment by jbleyel** [comment]
You can also check this file.

https://github.com/OpenPLi/enigma2/blob/develop/data/encoding.conf

**Comment by mrslvd** [comment]
Thanks,
I don't see any difference regarding 39E. My problem is that after software update I have to overwrite updated file with the one I attached in my post. I still don' understand why. In both files there is no row specifying anything about 39E.
Regards.

**Comment by jbleyel** [comment]
You should ask the contributors of the encoding file.

**Comment by jbleyel** [comment]
can we close this?

**Comment by mrslvd** [comment]
I made an update today and again encoding is not OK

**Comment by jbleyel** [comment]
Hi @nautilus7 , can you please take a look what’s wrong with this transponder?

**Comment by jbleyel** [comment]
Hi @thawtes , can you please help here?

**Comment by thawtes** [comment]
hi, @jbleyel
Of course I will help.
but as @mrslvd said there is no problem
see screenshot below (39E - 12271 H)
![NoProblem](https://i.imgur.com/bv1vDUJ.png)

I think @mrslvd  is doing something wrong.
There is no problem with openATV (and PLi) and all character encodings are working properly !

**Comment by mrslvd** [comment]
Hi twates,
Here is what I am experiencing:
1. After I made software update using the menu   TP 39E - 12271 H cyclic encoding gets incorrect (this not happens every time I did an update, I am not sure which download exactly cause the problem) ;
2. This happens when some of the updates replaces " /usr/share/enigma2/encoding.conf";
3. After I replace the new  "/usr/share/enigma2/encoding.conf" downloaded with the last update with one I got from another forum long time ago, everything is fine (the file I am using is in my second post).
4. OpenATV I am using is version 6.4 (more details on versions I will share later because I am not in home);
5. The skin I am using is default (I am not sure what this means :) ). Again, later I will add the version) .
6. I'll add screenshot when the problem appears again. When the problem appears again I'll place a link to the encoding.conf that comes from the update.

**Comment by thawtes** [comment]
> Hi twates, Here is what I am experiencing:
> 
> 1. After I made software update using the menu   TP 39E - 12271 H cyclic encoding gets incorrect (this not happens every time I did an update, I am not sure which download exactly cause the problem) ;
> 2. This happens when some of the updates replaces " /usr/share/enigma2/encoding.conf";
> 3. After I replace the new  "/usr/share/enigma2/encoding.conf" downloaded with the last update with one I got from another forum long time ago, everything is fine (the file I am using is in my second post).
> 4. OpenATV I am using is version 6.4 (more details on versions I will share later because I am not in home);
> 5. The skin I am using is default (I am not sure what this means :) ). Again, later I will add the version) .
> 6. I'll add screenshot when the problem appears again. When the problem appears again I'll place a link to the encoding.conf that comes from the update.

openATV was not up to date in 6.4 and I made the necessary fix.
you can use it as updated in the Image that will probably be released 1-2 days later.

@jbleyel  pls merge this request https://github.com/openatv/enigma2/pull/2432

**Comment by AbuBaniaz** [comment]
As the encoding file has been updated, shouldn't this issue be closed now?

**Comment by jbleyel** [comment]
> As the encoding file has been updated, shouldn't this issue be closed now?

I donno.
This must be checked by a Greek person.

**Comment by mrslvd** [comment]
I think this issue can be closed. I did not experienced this problem for a very long time while many updates has been passed.
In Greece the alphabet is very different than Bulgarian alphabet (aka Cyrillic), so I don't believe Greek person can help here ;)

Thanks and best regards!

**Comment by jbleyel** [comment]
Sorry, my fault.
