### ISSUE TITLE
[CI Assignment plugin] Crash

### ISSUE THREAD

**Issue by artseluiko** [openatv/enigma2#1755]
When I navigate to Common Interface Assignment and press Edit button I get this:
12:37:27.7330 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-07-16 12:37:27+0300 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/CommonInterfaceAssignment/plugin.py", line 115, in __init__
12:37:27.7334 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-07-16 12:37:27+0300 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 165, in setTitle
12:37:27.7339 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-07-16 12:37:27+0300 [-] KeyError: 'ScreenPath'
12:37:27.7340 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0xaa623030>>,('ColorActions', 'green')) failed)`

[enigma2_crash_1594892247.log](https://github.com/openatv/enigma2/files/4932786/enigma2_crash_1594892247.log)

Might be related to this PR:
#1747

**Comment by IanSav** [comment]
This is a problem in Plugins/SystemPlugins/CommonInterfaceAssignment/plugin.py I will fix it now.

**Comment by artseluiko** [comment]
The issue is fixed. Thank you
