### ISSUE TITLE
Missing Python Libraries

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1757]
Do not seem able to install some python libraries with openatv 6.5 on my vu zero 4k

Examples
```
opkg install python-requests
opkg install python-imaging
```

*unknown package* 

I have tried opkg update

Libraries seem to be in the folders though.
\usr\lib\python3.8\site-packages\requests

I need these modules for my plugins

**Comment by atvcaptain** [comment]
python-xxxx was python 2 packages
all new python 3 packages start with python3-xxxx

so simple replace  python-requests with python3-requests
and python-imaging is a very old version and python 3 version now use the new name python3-pillow

**Comment by kiddac** [comment]
Thanks for your answer
So how to we make plugin dependencies. That are compatible with python 2.7 and python 3

example control file
```
Package: enigma2-plugin-extensions-xstreamity
Version: 2.25-20200708
Section: misc
Priority: optional
Architecture: all
Maintainer: kiddac
Description: IPTV Xtream Codes playlists player by KiddaC
Depends: python-image, python-imaging, python-argparse, python-requests, python-multiprocessing
```

**Comment by atvcaptain** [comment]
this not working you must write too ipks one for py2 and one for py3

**Comment by atvcaptain** [comment]
or we build the plugins for you , and build system do all the job

**Comment by kiddac** [comment]
googling this can I use the | operator instead

For example

Depends: python-requests | python3-requests

**Comment by atvcaptain** [comment]
in your example python-argparse  is now include in python3.core and python3-core is default in the image you dont must depend to this same you dont depend to linux :)

**Comment by atvcaptain** [comment]
problem with or are feeds have py2 and py3 version one py2 plugin force the install form full python in the flash !

**Comment by kiddac** [comment]
My plugin is currently compatible with all boxes and images.
Some older boxes don't have them depends by default. 
Hence the requirement to try and install missing dependancies for people that have them missing and are not technical enough to manually install missing libraries

**Comment by atvcaptain** [comment]
at the moment py3 comes only with openatv 6.5 so we can build to feed your plugins and skins and user dont must instal with usb

**Comment by kiddac** [comment]
I know that. But my IPKs are downloadable via sat forums. Its a pain to create 2 versions every update. Just trying to find a solution that will work with both 2.7 and 3

**Comment by kiddac** [comment]
I will remove the dependancies for now. And see how much trouble if any, it causes
Thanks

**Comment by atvcaptain** [comment]
add to forum you py2 version and py3 only comes with feed

**Comment by atvcaptain** [comment]
or create you own kiddac feed and user must enable the feed and updates comes automatical to the users box
