### ISSUE TITLE
Recent changes to the screens.py causing crashes

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#1758]
The crashes occur when stopping and exiting a stream from any streaming plugin. Giving this.

Traceback (most recent call last):
File "/usr/lib/enigma2/python/Navigation.py", line 259, in dispatchEvent
File "/usr/lib/enigma2/python/Components/ServiceEventTracker.py", line 80, in event
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 429, in getEvent
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 558, in setEvent
File "/usr/lib/enigma2/python/Screens/Screen.py", line 150, in setTitle
File "/usr/lib/enigma2/python/Screens/Screen.py", line 150, in <genexpr>
TypeError: getTitle() takes exactly 2 arguments (1 given)

I think this commit is the culprit ? 

https://github.com/openatv/enigma2/commit/d8e66efa05f6344b4c1c05222da29c6b5cd3968e

I did see another post regarding the setTitle too, whereby it is giving crashes for the CI here

https://github.com/openatv/enigma2/issues/1755

I don't know if its related or not ?

EDIT: Actually its not the stopping of the stream causing the crash its the returning to the previous screen after its stopped ( I just have the exit button set to do both so this confused things )

**Comment by atvcaptain** [comment]
have you the name of the plugin with this crash ? send link to the ipk please

**Comment by IanSav** [comment]
Can you please confirm the build of OpenATV you are using.  The line numbers in the error log do not appear to line up with the repository source code.

getTitle() has no formal arguments!  It only uses self.

Please provide as much information as possible to help us identify the issue.

**Comment by ian10951** [comment]
No sorry I don't.

I was sent the plugin by a friend a couple of years ago, I don't even know if its public. However all was fine until the other day when these changes were made. I shall test other plugins too to see if those give this crash.

**Comment by IanSav** [comment]
Even with that complete log the errors don't line up with the source code.  Line 150 in Screen.py is "if self.instance:".  This code is nowhere near the getTitle() method that starts on line 168!

Perhaps you should wait until the other corrections made today are built into a fresh build and then test this again.

**Comment by ian10951** [comment]
OK will do.

Its very possible the image doesn't yet have all the changes I guess.

I will let you know.

**Comment by ian10951** [comment]
OK I've fixed it by completely reverting this commit.

https://github.com/openatv/enigma2/commit/903ac51ca80a1a29e1d0fccf05ccb6e10dd2ea5a

Overkill I know, but I could not establish which part of the recent changes were causing the crash. 

For now I will just keep all the files changed in that commit as py so I can continue to update the image, however it does mean I will have issues if any of these files are changed again in the future. 

Anyway I thought it best to inform you that something in this commit does cause issues with some plugins and others may or may not post about similar crashes in the future. At the weekend I will try to establish exactly what in this commit is causing it, but dont hold your breath lol.

**Comment by IanSav** [comment]
By this action I assume that you are using your own build of OpenATV?  It would be more helpful to identify the actual problem.

So far I have been finding poorly structured code as the reasons behind all the issues reported so far.  When the errors you posted don't line up with the source code then I get concerned about what is actually happening.

**Comment by ian10951** [comment]
No its the public build. Its a very recent fresh image too. Perhaps 1 month old.

I just took the code from the earlier files in history ( before this commit ) and added that to py files, as I say I do know it was complete overkill, but I dont know as yet how to find the exact issue. I don't understand at all why the errors are not lining up, so I've just updated the image again ( before reverting that commit ) and the crash that was on line 150 then became on line 149, however the information was exactly the same.

**Comment by Ev0-BH** [comment]
Crash is the same with OBH:

File "/usr/lib/enigma2/python/Screens/Screen.py", line 149, in setTitle
  self.screenPath = " > ".join(ds[0].getTitle() for ds in self.session.dialog_stack[1:])
File "/usr/lib/enigma2/python/Screens/Screen.py", line 149, in <genexpr>
  self.screenPath = " > ".join(ds[0].getTitle() for ds in self.session.dialog_stack[1:])
TypeError: getTitle() takes exactly 2 arguments (1 given)

**Comment by atvcaptain** [comment]
have you check fixes in openatv e2 git

**Comment by Ev0-BH** [comment]
Yes they don't work, they have been merged into openvix and openbh now too

**Comment by atvcaptain** [comment]
your log not show the screen name with the crash, same screen harddisc and  ci or other ?

**Comment by Ev0-BH** [comment]
I don't have the plugin installed now, I was sent it for a quick test (as I know ian10951 personally and asked to test it with OBH)

**Comment by IanSav** [comment]
Can someone please confirm that there isn't another getTitle() method getting in the way?

**Comment by atvcaptain** [comment]
we need the plugin send link

**Comment by ian10951** [comment]
Ive sent you a PM on the forum.

**Comment by atvcaptain** [comment]
the py file not use screen.getTitle() you have other addon installed send all infos

**Comment by ian10951** [comment]
This can be closed now as the issue is now fixed.

It turns out the new commit had named a def the same name as some defs were already named in the plugin. What are the chances lol ?

Anyway after renaming the def's in the plugin all is OK again.

**Comment by IanSav** [comment]
What were the method names?  I'll bet one was getTitle().  ;)  Developers need to be careful when playing with common Enigma2 methods.

I'm glad it is all sorted now.

**Comment by ian10951** [comment]
Yes that's the one.

Its now called getTitlePS in the plugin. That's never going to be used in the image I dont think.
