### ISSUE TITLE
Solo 4K Incorrect SNR dB values

### ISSUE THREAD

**Issue by ToxicLand** [openatv/enigma2#1771]
On my Solo 4K, OpenATV 6.4 reports 18,1dB 99% for all transponders (0.8W)
OpenPLI 7.3 reports accurate values, (relevant on weaker / more sensitive transponders, not everything is just 99%) with a maximum of 15.8dB (this is how the original image behaves as well)

**Comment by atvcaptain** [comment]
in both images vales only fake looks pli add a better fake :)

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/commit/d91f46471ca599dbe7be1c8529d6a9b247f5412f

include  in next image
