### ISSUE TITLE
HDMI-CEC problems

### ISSUE THREAD

**Issue by ToxicLand** [openatv/enigma2#1773]
Issues persist on Solo 4K and Zero 4K:
1. Forward volume keys stops working after an enigma2 restart. Only a box reboot fixes the problem.
2. When CEC is enabled on the box, it will not switch the soundbar to ARC source.

**Comment by MartB** [comment]
Slightly offtopic (sorry):
Can you shine some light on https://github.com/openatv/enigma2/issues/857 and whether or not this is still applicable?
I really want to switch to openatv.
