### ISSUE TITLE
README.md missing dependencies

### ISSUE THREAD

**Issue by LandRocket** [openatv/enigma2#1780]
On a brand new install of Ubuntu 20.04, following instructions on README.md won't build....

check internet connection: Online      
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/openatvbuilder/openatv/builds/openatv/dev/vuultimo4k/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 30039 at 2020-07-27 11:34:29.364777 ---
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  python

make: *** [Makefile:983: image] Error 1

Ubuntu suggests installing "python-is-python2" via apt-get..  but would prefer professional input into whether this is the correct method.

**Comment by nickersk** [comment]
run:
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
check if python3 is selected by this command: sudo update-alternatives --config python

**Comment by LandRocket** [comment]
Tested on virgin install of Ubuntu.  Working perfect :)  Possible to update README.md when convenient?
