### ISSUE TITLE
Known po translation file issues

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1789]
Using this to track po file issues.
---

- reinstate translator comments in enigma2.pot
- ~strip po file references to filename only~ #1809 #1819 
- ~update button labels~
- ~sort po files by msgid for easier subsequent diffing (may conflict with xml2po script)~
  - this will conflict with MSG tools as used in Makefile
- remove obsolete entries
- remove obviously-incorrect fuzzy entries (eg.: "REC" -> "FEC")
- update options screens
  - labels
  - descriptions
- update xml2po script
 - ~extract `*gettext(` strings~
 - ~add filerefs~ ~leverage Makefile for this instead #1819~
> labels
> values
> descriptions
- update menu entries
- ~update cleanup script to ignore keymap and other files which don't use translations~
 - ~else parse only strings prefixed by `_(` or `*gettext(`~

- clear up ambiguity around `Disk Initialisation` (clear/wipe whole disk? partition only? ...)

**Comment by wedebe** [comment]
Could someone assign this to me, please?

**Comment by nickersk** [comment]
there you go

**Comment by jbleyel** [comment]
Can we close this?

**Comment by wedebe** [comment]
A significant amount of (but noticeably not all) translation work was lost with the implementation of Weblate (I had been updating en.po rather that .py/.xml files directly up to that point).

I notice there are currently contributions being made to the English translation which differ from that previous work.

**Comment by jbleyel** [comment]
We plan to fix all strings in source to the correct en_US spelling.
en.po will be stay empty.

**Comment by jbleyel** [comment]
If you find wrong text in source then feel free and send me the corrected file.
Please do not change the source in git directly because I also need to fix the pot/po files.

**Comment by wedebe** [comment]
> We plan to fix all strings in source to the correct en_US spelling. en.po will be stay empty.

May I suggest that you use the versoin of translations at this commit:
https://github.com/openatv/enigma2/blob/7c8c88df5775cde7ec516e2765d5286f54a7828a/po/en.po

This was at the point of simplified, more-consistent English terminology, grammar and punctuation.

**Comment by wedebe** [comment]
> If you find wrong text in source then feel free and send me the corrected file. Please do not change the source in git directly because I also need to fix the pot/po files.

Do the po/updateallpo.sh and po/updatepot.sh scripts still work as intended for Weblate?

It would be handy to update the translation contribution section of the Readme.

**Comment by jbleyel** [comment]
> > We plan to fix all strings in source to the correct en_US spelling. en.po will be stay empty.
> 
> May I suggest that you use the version of translations at this commit: https://github.com/openatv/enigma2/blob/7c8c88df5775cde7ec516e2765d5286f54a7828a/po/en.po
> 
> This was at the point of simplified, more-consistent English terminology, grammar and punctuation.

Is this en_US or en_GB?

**Comment by jbleyel** [comment]
> > If you find wrong text in source then feel free and send me the corrected file. Please do not change the source in git directly because I also need to fix the pot/po files.
> 
> Do the po/updateallpo.sh and po/updatepot.sh scripts still work as intended for Weblate?
> 
> It would be handy to update the translation contribution section of the Readme.

I use the GitHub Action to create the pot file.
But this is only for new strings.
Existing strings needs to changed differently and I also update the files for weblate.
The workflow is not that easy but it's working.

**Comment by jbleyel** [comment]
We will lose all existing translations if we only fix the source and update the pot file only.
This is not my style.

**Comment by IanSav** [comment]
@jbleyel and I have been talking about creating so language styles for all future text changes in Enigma2.

Some of the key points, so far, include:
1. All text in code must be in en_US (English US).
2. There is no need for any text to be translated in en.po or en_US.po.
3. All titles and button should have the first letter of every word capitalised.
4. When titles or buttons are referenced in text the capitalization should be retained.
5. All references to buttons on the remote control should be in all upper case.  E.g. OK, RED, GREEN, MENU, etc.
6. All descriptions text should be written in concise English with proper and appropriate punctuation.
7. Currently help text does not include punctuation but this is up for review.
8. There should only be one space after punctuation marks.  Extra spacing for readability to separate options etc may still be appropriate.

These two documents and the link are some common writing style guides that are very popular:
- [The Elements Of Style](https://github.com/openatv/enigma2/files/8644897/TheElementsOfStyle.pdf)
- [The Elements Of Style - Updated 2011 Edition.pdf](https://github.com/openatv/enigma2/files/8644901/TheElementsOfStyle_Updated2011Edition.pdf)
- [A Quick Guide to Punctuation](https://www.lynchburg.edu/academics/writing-center/wilmer-writing-center-online-writing-lab/grammar/a-quick-guide-to-punctuation/)

This is a work in progress.  Suggestions, corrections and enhancements welcomed.

**Comment by jbleyel** [comment]
Continue here -> #3310
