### ISSUE TITLE
EPG regex search

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1790]
I'd like to ask whether there are any known issues with the full implementation of regex EPG searching?

epgcache.cpp already has (some) code for title and description searching by regex, but no frontend code wired up (it looks like it would be set as a case sensitivity option `eEPGCache.REGEX_CHECK` along with
```
eEPGCache.CASE_CHECK,
eEPGCache.NO_CASE_CHECK
```

```
else if (casetype == REGEX_CHECK)
{
  std::regex pattern(str);
  std::string input(contentptr,content_len);
  if (regex_search(input.begin(),input.end(),pattern))
  {
    descr.push_back(it->first);
  }
}  
```

**Comment by jbleyel** [comment]
This is not an issue of enigma2 the frontend is autotimer.
