### ISSUE TITLE
checkNetworkState and checkDNSLookup call Google/.de domains

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1791]
I'd like to suggest changing the following for more high-availability, international/local resolution, and privacy benefits

```
	def checkNetworkState(self,statecallback):
		self.NetworkState = 0
		cmd1 = "ping -c 1 www.openpli.org"
		cmd2 = "ping -c 1 www.google.nl"
		cmd3 = "ping -c 1 www.google.com"
```
to
```
	def checkNetworkState(self,statecallback):
		self.NetworkState = 0
		cmd1 = "ping -c 1 www.akamai.com"
		cmd2 = "ping -c 1 www.cloudflare.com"
		cmd3 = "ping -c 1 1.1.1.1" #Cloudflare DNS
```

as well as

```
	def checkDNSLookup(self,statecallback):
		cmd1 = "nslookup www.dream-multimedia-tv.de"
		cmd2 = "nslookup www.heise.de"
		cmd3 = "nslookup www.google.de"
```
to
```
	def checkDNSLookup(self,statecallback):
		cmd1 = "nslookup www.akamai.com"
		cmd2 = "nslookup www.cloudflare.com"
		cmd3 = "nslookup www.opena.tv"
```

**Comment by wedebe** [comment]
I'm happy to make the change following any thoughts or considerations.

**Comment by nickersk** [comment]
good idea

**Comment by IanSav** [comment]
I never wanted to bring this up but this has been in the code for many, many years but I was abused for adding and being up front about the geolocation calls I recently added!

**Comment by wedebe** [comment]
Do we have any stats on where users use or maybe even just download their OpenATV images?

**Comment by IanSav** [comment]
I would not assume users of *any* image are in any specific locality.  For example, at the moment openATV is seeing increased usage in Australia.

For the network connectivity test stick with bigger companies / infrastructure providers that are well connected and fast.  As you noted very few have the size and capacity to demand specific IP addresses worldwide.

Similarly for the DNS lookups, go with bigger names like, as you have, CloudFlare and Google and add something like Microsoft etc.

**Comment by wedebe** [comment]
PR created #1793

**Comment by wedebe** [comment]
> I never wanted to bring this up but this has been in the code for many, many years but I was abused for adding and being up front about the geolocation calls I recently added!

Oh, like this?

https://github.com/openatv/enigma2/pull/1793#issuecomment-668503846

**Comment by Schimmelreiter** [comment]
Your code checks literal IPv4 addresses.
It's the year 2020, years after IPv4 address exhaustion, so please do not modify code in a way that just introduces other problems.

Proper code would check IPv4 and IPv6 connectivity independently and also show it independently.
For the time being respectively quick fixes, it should just check both.

**Comment by IanSav** [comment]
> > I never wanted to bring this up but this has been in the code for many, many years but I was abused for adding and being up front about the geolocation calls I recently added!
> 
> Oh, like this?
> 
> [#1793 (comment)](https://github.com/openatv/enigma2/pull/1793#issuecomment-668503846)

No, I was hauled over the coals for making Internet connections to a geolocation server without seeking permission from the user first.  These tests leak just as much information without user permission but were never noticed by the users screaming bloody murder at me for my "violating" their privacy.

**Comment by wedebe** [comment]
> ...without seeking permission from the user first. These tests leak just as much information without user permission but were never noticed by the users screaming bloody murder at me for my "violating" their privacy.

>_<
https://www.facebook.com/untitlednerdnetwork/photos/a.841556079231026/3077089599010985/?type=3&theater

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/5aba545a2ac02357667d17dd5b56d25f414ce0ab
