### ISSUE TITLE
21:9 content appears as 'stretch nonlinear'

### ISSUE THREAD

**Issue by ToxicLand** [openatv/enigma2#1795]
So far I only noticed this issue on 0.8W 11843V 30000, with HBO HD. When the channel broadcasts >16:9 content, sometimes it appears as 'stretch nonlinear' even if my setting is 'letterbox'. I have to switch to another setting, then back to 'letterbox' to fix it. The issue appears again after a reboot. Video of the issue: https://streamable.com/w2ppp0

**Comment by Tony-il-Capo** [comment]
Similar behavior to this [issue](https://github.com/openatv/enigma2/issues/784)

As far as I am aware is not yet fixed, this only affects some STBs, still relying on boot workaround to fix it, by cycling AR settings like you describe

> I have to switch to another setting, then back to 'letterbox' to fix it

After this, the problem will only appear after reboot. Exactly as you describe it.

After a fresh (re)start, test the code in terminal to see if it woorks for you, then if so, you could use it as boot script...
`echo -n 'letterbox' > /proc/stb/video/policy2`

**Comment by ToxicLand** [comment]
The problem is now worse since a week, even 16:9 content on this channel will be stretched. If i do the "I have to switch to another setting, then back to 'letterbox' to fix it", it won't be stretched, but there will be black lines at the top and bottom. PiP is not affected. Example: https://i.imgur.com/qPkmfbe.jpg

**Comment by Tony-il-Capo** [comment]
What STB are you using?

If the comand I gave you works for you, then your better option is to do a small script and call it in rc.local, so it runs at every boot.
It needs to wait for full E2 initalization, so you need either a 'sleep' command or a 'while' loop checking in dmesg or something else where it can make sure live tv is playing

Personally I have something like this:
```
main() {
while :; do
	if dmesg | grep -F "FE tune" -m 1 &> /dev/null; then
		sleep 5
		echo -n 'letterbox' > /proc/stb/video/policy2
		break
	fi
	sleep 5
done
} 
main &
```

You can have it directly in /etc/rc.local
You need to make sure your dmesg have "FE tune" message, if not, it will never end loop and do nothing
Check output
`dmesg | grep "FE tune"`
