### ISSUE TITLE
please add to unicable.xml new LNB FTE dCSS24 24ch

### ISSUE THREAD

**Issue by fritzlc** [openatv/enigma2#1803]
this config work good on my VU+ZERO SOLO4k UNO4KSE

[http://ftemaximal.com/en/products/reception/lnc-s/lnc-s-unicable-series](url)

		</manufacturer>
		<manufacturer name="Fte PREMIUM dCSS">
			<product name="pemium dCSS24 24ch" format="EN50607"
				scr1= "1076" scr2= "1178" scr3= "1280" scr4= "1382" scr5= "1484" scr6= "1586" scr7= "1688" scr8= "1790"
				scr9=  "975" scr10="1025" scr11="1225" scr12="1330" scr13="1430" scr14="1535" scr15="1630" scr16="1730"
				scr17="1840" scr18="1880" scr19="1920" scr20="1960" scr21="2000" scr22="2040" scr23="2080" scr24="2125"/>
			<product name="pemium dCSS 8ch" format="EN50494"
				scr1= "1076" scr2= "1178" scr3= "1280" scr4= "1382" scr5= "1484" scr6= "1586" scr7= "1688" scr8= "1790"/>
		</manufacturer>

**Comment by atvcaptain** [comment]
done
