### ISSUE TITLE
Cablescan plugin doesn't work with SAT>IP

### ISSUE THREAD

**Issue by retrofan1979** [openatv/enigma2#1805]
The cablescan plugin doesn't work with SAT>IP server as VTUNER. I got this error: Scanning failed! I think it's because my SAT>IP server wants the (Spectrum) Inversion setting to be turned on and indeed I don't see this setting. Can you please add this option to the cablescan plugin?

Here's the sourcecode of the cable plugin:

https://github.com/openatv/enigma2/blob/bd29a5ca67db766d03f9a06afae1d1d15b2b4be4/lib/python/Plugins/SystemPlugins/CableScan/plugin.py

**Comment by retrofan1979** [comment]
And is it possible to add spacers between unused channel numbers instead of markers? With markers I see '-' in the channellist with unused channels. With spacers you don't see this behaviour which I prefer personally.

**Comment by retrofan1979** [comment]
This is probably the information you need:

https://dream.reichholf.net/pydoc/html/d8/d61/classenigma_1_1eDVBFrontendParametersCable.html

Thank you!

**Comment by retrofan1979** [comment]
I tried to add the inversion parameter, but the cablescan crashes when I start the cablescan. See attachment. What's wrong?
[debug.zip](https://github.com/openatv/enigma2/files/5083998/debug.zip)

**Comment by retrofan1979** [comment]
Nobody?
I'm using the Fritz!WLAN Repeater DVB-C, which is very common in Germany and can be used as virtual tuner in OpenATV.

**Comment by arn354** [comment]
13:39:19.3303 { D }     self.scan = eCableScan(self.scanNetwork, self.scanFrequency, self.scanSymbolRate, self.scanModulation, self.scanInversion, self.keepNumbers, self.hdList)
13:39:19.3308 { D } TypeError: __init__() takes at most 7 arguments (8 given)

that means you pass more arguments then the function can take.

from enigma import **eCableScan**, eDVBFrontendParametersCable, eTimer
...

self.scan = **eCableScan**(self.scanNetwork, self.scanFrequency, self.scanSymbolRate, self.scanModulation, self.scanInversion, self.keepNumbers, self.hdList)

i think any change you apply for python part of cablescan would also be needed to be implemented in c++ part of enigma2 CableScan. https://github.com/openatv/enigma2/blob/6.4/lib/dvb/cablescan.h#L52 https://github.com/openatv/enigma2/blob/6.4/lib/dvb/cablescan.cpp#L17

no idea if your desired change would have any effect or how it would have to be implemented.

**Comment by retrofan1979** [comment]
Hi, thanks for your reply. Can we investigate this?
I only need an IPK so I can install it on OpenATV 6.1 which works fine in all cases.

**Comment by retrofan1979** [comment]
If you tell me how I can compile an IPK on my own receiver I can try this new setting. I have a Formuler F1 which uses mips. Thanks!

**Comment by retrofan1979** [comment]
?

Is it possible for you to provide a new compiled mips IPK so I can test? Or can I compile it for myself and how?

**Comment by retrofan1979** [comment]
?

**Comment by retrofan1979** [comment]
And is it possible to add spacers between unused channel numbers instead of markers? With markers I see '-' in the channellist with unused channels. With spacers you don't see this behaviour which I prefer personally.

**Comment by retrofan1979** [comment]
@atvcaptain : can you please help with this? Thank you!

**Comment by retrofan1979** [comment]
Can someone provide a new compiled MIPS IPK so I can test it on Formuler F1 with OpenATV 6.x if it works? Thank you!

**Comment by retrofan1979** [comment]
And is it possible to let the cablescan plugin generate spaces instead of markers when a channelnumber isn't used. Now I see '-' in the channellist with unused numbers.

For example:

201. Channel 1
202. Channel 2
203. Channel 3
204. -
205. -
206. -
207. Channel 4

But I would like to see it this way:

201. Channel 1
202. Channel 2
203. Channel 3
207. Channel 4

**Comment by retrofan1979** [comment]
I close this topic as nobody replies on this issue.

**Comment by retrofan1979** [comment]
Found another solution, issue closed.
