### ISSUE TITLE
Can not decode ecm on twin tuner B if tuner A recording (Amiko Viper Twin E2)

### ISSUE THREAD

**Issue by easyyu** [openatv/enigma2#1806]
Hello..
After a lot of research I realise that this is bug, or simply unfinished image for Amiko Viper Twin E2.
I'm using last (17.Avg.2020) version of OATV v6.4.

The scenario is next: 
1. If I start recording on transponder X with tuner A, and wanna watch some **coded** channel on transponder Y on tuner B then oscam yelling error.
2. If I start recording on transponder X with tuner A, and wanna watch some **free** channel on transponder Y on tuner B then everything is OK, I have a picture.

The result of command: ls -l /dev/dvb/adapter0

> ls -l /dev/dvb/adapter0
crw-rw----    1 root     root      212,   1 Aug 18 17:30 audio0
crw-rw----    1 root     root      212,  17 Aug 18 17:30 audio1
crw-rw----    1 root     root      212,   6 Aug 18 17:30 ca0
crw-rw----    1 root     root      212,   4 Aug 18 17:30 demux0
crw-rw----    1 root     root      212,  20 Aug 18 17:30 demux1
crw-rw----    1 root     root      212,  36 Aug 18 17:30 demux2
crw-rw----    1 root     root      212,   5 Aug 18 17:30 dvr0
crw-rw----    1 root     root      212,  21 Aug 18 17:30 dvr1
crw-rw----    1 root     root      212,  37 Aug 18 17:30 dvr2
crw-rw----    1 root     root      212,   3 Aug 18 17:30 frontend0
crw-rw----    1 root     root      212,  19 Aug 18 17:30 frontend1
crw-rw----    1 root     root      212,   0 Aug 18 17:30 video0
crw-rw----    1 root     root      212,  16 Aug 18 17:30 video1

It is visible that I have not **/dev/dvb/adapter0/ca1** file

When I simulating the scenario 1. then oscam yelling:

> (dvbapi) ERROR: Can't open device /dev/dvb/adapter0/ca1 (errno=2 No such file or directory)

What is totally understandable becouse I have not that file.
I tried lot of combination to link for example:

> ln -f /dev/dvb/adapter0/ca0 /dev/dvb/adapter0/ca1

but then oscam yelling:
> (dvbapi) ERROR: Can't open device /dev/dvb/adapter0/ca1 (errno=16 Device or resource busy)

I even try to bind with **mknod** command to kernel ca1 like this:
> mknod /dev/dvb/adapter0/ca1 c 212 22

but again oscam log said:
>(dvbapi) ERROR: Can't open device /dev/dvb/adapter0/ca1 (errno=19 No such device)

In desperation I tried every number from 0 till 64 but result are same.

I tried even different version of oscam, as well as all type of dvbapi config (duckbox, dbox, ipbox...). The difference between different type of device in dvbapi is just would oscam ask on ca1 and ca2 or on ca0 and ca1. In my case do not helping because those "files" do not exist.

My question is is this box not supported for scenario 1. by OATV, or drivers are not still finished for this, or I'm doing something wrong.
I would be very happy for any kind of suggestion.
Thx

**Comment by arn354** [comment]
dvb devices are created from dvb-drivers provided from manufacturer. If some are not available - that might have several reasons (hardware limitations, feature restrictions, ... or a bug). Personally i doubt that there will be an update. You might want to contact the manufacturer and ask him directly.

**Comment by atvcaptain** [comment]
i send your bug report to  the manufacturer driver team

**Comment by easyyu** [comment]
Thank you very much..How can I know when you as a developers will implement the driver if they release new driver?

**Comment by atvcaptain** [comment]
i report the info or watch the git log : https://github.com/oe-alliance/oe-alliance-core/commits/4.4/meta-brands/meta-dinobot

**Comment by jbleyel** [comment]
ATV 6.4 is EOL.
