### ISSUE TITLE
ERROR: gperf-native-3.1-r0 do_unpack

### ISSUE THREAD

**Issue by atefganm** [openatv/enigma2#1807]
`NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.47.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-19.10"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openatv"
DISTRO_VERSION       = "6.5"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
meta                 = "HEAD:10221e578ffb3551ccefe15a523ceba0d289c086"
meta-oe              
meta-multimedia      
meta-networking      
meta-filesystems     
meta-python          
meta-webserver       = "HEAD:2cf66ec68f32e7fdebaf683ad9b05c399662960f"
meta-python2         = "HEAD:285c7a0140b91d3b1b6a0248dd703c668a8fe1de"
meta-oe              = "HEAD:c73b3c683f489c794ac0501d99c14c54ab0cdcc0"
meta-qt5             = "HEAD:c73416666673b36ac939606434cd9d0c9d13dce9"
meta-airdigital      
meta-amiko           
meta-ax              
meta-blackbox        
meta-beyonwiz        
meta-ceryon          
meta-cube            
meta-dags            
meta-dinobot         
meta-dream           
meta-edision         
meta-entwopia        
meta-formuler        
meta-fulan           
meta-gfutures        
meta-gigablue        
meta-ini             
meta-ixuss           
meta-maxytec         
meta-broadmedia      
meta-odin            
meta-octagon         
meta-protek          
meta-skylake         
meta-tiviar          
meta-tripledot       
meta-uclan           
meta-ultramini       
meta-vuplus          
meta-xp              
meta-xtrend          
meta-xcore           = "HEAD:c73b3c683f489c794ac0501d99c14c54ab0cdcc0"
meta-local           = "nextp3:ae267f47b9fafcb7441f6a4a4e866919e7d95336"

Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:11
Sstate summary: Wanted 4966 Found 0 Missed 4966 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
ERROR: gperf-native-3.1-r0 do_unpack: Unpack failure for URL: 'https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz'. Unpack command PATH="/home/atef/build-enviroment/openembedded-core/scripts/native-intercept:/home/atef/build-enviroment/openembedded-core/scripts:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/recipe-sysroot-native/usr/bin/x86_64-linux:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/recipe-sysroot-native/usr/bin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/recipe-sysroot-native/usr/sbin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/recipe-sysroot-native/usr/bin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/recipe-sysroot-native/sbin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/recipe-sysroot-native/bin:/home/atef/build-enviroment/bitbake/bin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/hosttools" tar xz --no-same-owner -f /home/atef/build-enviroment/sources/gperf-3.1.tar.gz failed with return value 2
ERROR: Logfile of failure stored in: /home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/x86_64-linux/gperf-native/3.1-r0/temp/log.do_unpack.13734
ERROR: Task (virtual:native:/home/atef/build-enviroment/openembedded-core/meta/recipes-extended/gperf/gperf_3.1.bb:do_unpack) failed with exit code '1'
NOTE: Tasks Summary: Attempted 181 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/home/atef/build-enviroment/openembedded-core/meta/recipes-extended/gperf/gperf_3.1.bb:do_unpack
Summary: There were 21 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:996: image] Error 1
atef@ganm:~/build-enviroment$ 
`

**Comment by atvcaptain** [comment]
can you delete the gperf-3.1.tar.gz'. from your source folder and test again, download issue or broken file ?

**Comment by atefganm** [comment]
Unfortunately, other problems arose. It seems that the source file has to be downloaded completely again
---------------------

`Sstate summary: Wanted 4966 Found 0 Missed 4966 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
ERROR: kmod-27-r0 do_unpack: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1722"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot-native/usr/bin/python3-native:/home/atef/build-enviroment/openembedded-core/scripts:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot/usr/bin/crossscripts:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot-native/usr/sbin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot-native/usr/bin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot-native/sbin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/recipe-sysroot-native/bin:/home/atef/build-enviroment/bitbake/bin:/home/atef/build-enviroment/builds/openatv/release/dm820/tmp/hosttools"; export HOME="/home/atef"; git -c core.fsyncobjectfiles=0 clone -s -n /home/atef/build-enviroment/sources/git2/git.kernel.org.pub.scm.utils.kernel.kmod.kmod.git/ /home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/git/ failed with exit code 128, output:
fatal: repository '/home/atef/build-enviroment/sources/git2/git.kernel.org.pub.scm.utils.kernel.kmod.kmod.git/' does not exist

ERROR: Logfile of failure stored in: /home/atef/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/kmod/27-r0/temp/log.do_unpack.24673
ERROR: Task (/home/atef/build-enviroment/openembedded-core/meta/recipes-kernel/kmod/kmod_git.bb:do_unpack) failed with exit code '1'
NOTE: Tasks Summary: Attempted 507 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/build-enviroment/openembedded-core/meta/recipes-kernel/kmod/kmod_git.bb:do_unpack
Summary: There were 21 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:996: image] Error 1
atef@ganm:~/build-enviroment$ 
`

**Comment by atvcaptain** [comment]
we build with ubunto 20-04 no idea at the moment, i have test again today and here all ok
