### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by atefganm** [openatv/enigma2#1833]
A strange problem that I had never encountered before
Construction stops when tree recipes are read
The construction is at 50% and does not complete and does not give any errors
I do not know the reason is there an explanation for that

![Screenshot_2020-09-05_22-14-55](https://user-images.githubusercontent.com/31848885/92309366-33726a00-efa5-11ea-8a3e-08fcd4c5d5a4.png)

**Comment by nickersk** [comment]
hi, this belongs to oe-alliance-core not to enigma2. currently oscam svn is down, thats why bitbake hangs.

**Comment by nickersk** [comment]
oscam svn is back online, so closing this issue
