### ISSUE TITLE
images.mynonpublic download site

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1848]
Hi, I'd like to find out if there would be any interest in having the image download site re-worked, it's a bit... dated, and I'd like to help out.

**Comment by nickersk** [comment]
hi, lets finish this first: https://github.com/openatv/enigma2/pull/1838

**Comment by atvcaptain** [comment]
we need help renew the download site, you are welcome

**Comment by jbleyel** [comment]
This is an issue of the forum.

**Comment by wedebe** [comment]
> we need help renew the download site, you are welcome

I guess the images.mynonpublic.com is closed source? If someone wants to email me the code I'll take a look during the summer.
