### ISSUE TITLE
Realtek rtl28xxu driver doesnt work on 6.4 Vuduo

### ISSUE THREAD

**Issue by Ntemis** [openatv/enigma2#1855]
Dmesg log:
usb 1-1.3.1: dvb_usb_v2: found a 'Realtek RTL2832U reference design' in warm state
usbcore: registered new interface driver dvb_usb_rtl28xxu
usb 1-1.3.2: dvb_usb_v2: found a 'Realtek RTL2832U reference design' in warm state
usb 1-1.3.1: dvb_usb_v2: will pass the complete MPEG2 transport stream to the software demuxer
DVB: registering new adapter (Realtek RTL2832U reference design)
usb 1-1.3.2: dvb_usb_v2: will pass the complete MPEG2 transport stream to the software demuxer
DVB: registering new adapter (Realtek RTL2832U reference design)
usb 1-1.3.1: dvb_usb_rtl28xxu: unknown tuner=NONE
usb 1-1.3.2: dvb_usb_rtl28xxu: unknown tuner=NONE
usb 1-1.3.1: dvb_usb_v2: 'Realtek RTL2832U reference design' error while loading driver (-19)
usb 1-1.3.2: dvb_usb_v2: 'Realtek RTL2832U reference design' error while loading driver (-19)
usb 1-1.3.1: dvb_usb_v2: 'Realtek RTL2832U reference design' successfully deinitialized and disconnected

http://feeds2.mynonpublic.com/6.4/vuduo/all/enigma2-plugin-drivers-dvb-usb-rtl2832_1.0-r0_all.ipk

**Comment by nickersk** [comment]
have you installed enigma2-plugin-drivers-dvb-usb-rtl2832 ?

**Comment by Ntemis** [comment]
root@vuduo:~# opkg install kernel-module-dvb-usb-rtl28xxu
Package kernel-module-dvb-usb-rtl28xxu-3.9.6 (3.9.6-oea4.1-r2) installed in root is up to date.
root@vuduo:~# opkg install enigma2-plugin-drivers-dvb-usb-rtl2832 
Package enigma2-plugin-drivers-dvb-usb-rtl2832 (1.0-r0) installed in root is up to date.

**Comment by Ntemis** [comment]
That ipk driver is empty only control file is there and it has this documentation inside
Package: enigma2-plugin-drivers-dvb-usb-rtl2832
Version: 1.0-r0
Description: USB DVB driver for Realtek RTL2832 chipset
 USB DVB driver for Realtek RTL2832 chipset.
Section: base
Priority: optional
Maintainer: OE-Core Developers <openembedded-core@lists.openembedded.org>
License: GPLv2+
Architecture: all
OE: enigma2-plugin-drivers-dvb-usb-rtl2832
Recommends: firmware-dvb-usb-af9015, firmware-dvb-usb-af9035-01, firmware-dvb-usb-af9035-02, kernel-module-dvb-usb-rtl2832, kernel-module-dvb-usb-rtl28xxu, kernel-module-e4000, kernel-module-fc0012, kernel-module-fc0013, kernel-module-mt2266, kernel-module-r820t, kernel-module-rtl2832
Source: enigma2-plugin-drivers-dvb-usb-rtl2832.bb

**Comment by Ntemis** [comment]
Both tuners work fine on Ubuntu Focal(20.04.x)
https://dpaste.com/DR73GA7W5

**Comment by Ntemis** [comment]
After some research i identify the issue , the driver is missing r820t 7-001a: Rafael Micro r820t driver.
Can it be fixed?

**Comment by arn354** [comment]
root@gbquad4k:~# opkg list |grep r820
kernel-module-r820t-4.1.20-1.9 - 4.1.20-r10 - r820t kernel module
 r820t kernel module; Rafael Micro r820t silicon tuner driver
root@gbquad4k:~#

at least in newer kernels there is a kernel-module available.

**Comment by nickersk** [comment]
root@vusolose:~# opkg list|grep r820
kernel-module-r820t-3.13.5 - 3.13.5-oea4.3-r5 - r820t kernel module

vuduo runs 3.9.6 if i am not wrong ...

**Comment by Ntemis** [comment]
you are not

**Comment by Ntemis** [comment]
I flashed openbh-4.4.001.release-vuduo_usb_release_42cd9fee on my VU+ DUO and now everything works fine.
If you have no intention to fix this for openatv you are welcome to close this issue down.

**Comment by nickersk** [comment]
this is weird then :-) since openbh afaik is built from same OE-core openatv is built from :-)

**Comment by jbleyel** [comment]
6.4 is EOL
