### ISSUE TITLE
Metrix Gui crashes on selecting an option inside menu VuDuo Openatv 6.4

### ISSUE THREAD

**Issue by Ntemis** [openatv/enigma2#1856]
[enigma2_crash_1603212864.log](https://github.com/openatv/enigma2/files/5416345/enigma2_crash_1603212864.log)
[enigma2_crash_1603213412.log](https://github.com/openatv/enigma2/files/5416347/enigma2_crash_1603213412.log)
[enigma2_crash_1603214413.log](https://github.com/openatv/enigma2/files/5416348/enigma2_crash_1603214413.log)

**Comment by nickersk** [comment]
have you restored settings from atv 6.3?

**Comment by Ntemis** [comment]
This fixed it self after the yesterday update 22/10/2020
