### ISSUE TITLE
network communication fails using SMBv2

### ISSUE THREAD

**Issue by docjochim** [openatv/enigma2#1862]
My edision OS1+ (OpenATV 6.3 and same in OpenATV 6.4) has no problems concerning networkmounts, if SMBv1 is used. Recorded TV-films (*.ts) can be watched from AVM-Fritz!NAS, from local HDD and from Win10PC-share.

But if I use SMBv2 (changing autofs/cifs-mount-options from 'vers=1.0' to 'vers=2.0' or 'vers=3.02'), network communication fails: films >2GB only show black for a moment, then return to EMC showing title and progressbar in green (watched till the end). Files >2GB are cut at 2GB (2^31 Byte) if I try to copy them to a network share using filecommander or EMC.

There seems to be a problem in handling files >2GB.

Why?

Is there a bug in SMB-protocol v2? Problem persists even if I perform a clean install of a new image without transmitting any preferences or plugins.

I already asked in german openATV-Forum, but until now, no one had an idea what could be the reason for this erroneous beaviour.

André

**Comment by jbleyel** [comment]
Please try ATV 7.1 or 7.2 and reopen if the error still exists.
