### ISSUE TITLE
 Fix an endless spiner in FF/FR

### ISSUE THREAD

**Issue by 101000** [openatv/enigma2#1863]
Sometimes, during fastforwading/rewinding a recorded movie (speed > 8x), spinner appear on the top left and decoder need to be rebooted.

The fix is already available here https://github.com/OpenViX/enigma2/commit/e3f0c6dd85c3ef2c4532f827206358dc636ccb61
in open atv the code seems affected by the same bug:

look for this assignment: 
m_skipmode_m = bitrate / 8 / 90000 * m_cue->m_skipmode_ratio / 8;

in dvb.cpp class

**Comment by AbuBaniaz** [comment]
Any update on this please?

**Comment by jbleyel** [comment]
I will check this.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/pull/2694
