### ISSUE TITLE
OpenaTV 6.4 compilation error

### ISSUE THREAD

**Issue by Nemcio** [openatv/enigma2#1873]
I can't compile OpenaTV 6.4 for several days.
I have this error all the time:
WARNING:/build-enviroment/builds/openatv/release/inihdp/tmp/work/x86_64-linux/gdbm-native/1.18.1-r0/temp/run.do_compile.165953:1 exit 1 from 'exit 1'
| 
ERROR: Task (virtual:native:/build-enviroment/openembedded-core/meta/recipes-support/gdbm/gdbm_1.18.1.bb:do_compile) failed with exit code '1'
OpenaTV 6.5 compilation was OK yesterday.

**Comment by nickersk** [comment]
gcc, g++ version used on build host?

**Comment by Nemcio** [comment]
gcc --version
gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by nickersk** [comment]
switch both to version 9.3.0 via update alternatives and retry

**Comment by Nemcio** [comment]
So I have to install:
sudo apt install gcc-8 g++-8 gcc-9 g++-9 gcc-10 g++-10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8

sudo update-alternatives --config gcc
and choose:
gcc-9
?

**Comment by nickersk** [comment]
yes, that should work

**Comment by Nemcio** [comment]
Now I have this error:
ERROR: Task (/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/image/oe-alliance-branding-remote.bb:do_compile) failed with exit code '1'
Waiting for 2 running tasks to finish:
0: boost-1.71.0-r0 do_compile - 4m2s (pid 103626)
1: rclone-1.52-DEV+gitAUTOINC+ddfde68140-r0 do_upx - 3m47s (pid 103659)
boost-1.71.0-r0 do_compile 10 hours hung and didn't end.

**Comment by Nemcio** [comment]
And:
ERROR: Task (/build-enviroment/openembedded-core/meta/recipes-support/boost/boost_1.71.0.bb:do_compile) failed with exit code '1'

**Comment by nickersk** [comment]
low ram or swap probably. part of log you pasted says nothing ...

**Comment by Nemcio** [comment]
Please write what you need to enter so that you know why.

**Comment by nickersk** [comment]
you have line which points to log, you have to read it and find error in that log ....log.do_compile
but if you have less then 4gb free ram you event dont need to :-) all that can help in such situation is large swap (16gb+)

**Comment by Nemcio** [comment]
The machine has a 4GB RAM i7 processor.
Compiles OK openvision.

**Comment by nickersk** [comment]
as i wrote above, you need to read bitbake output, find the log file and find the error inside it.

**Comment by Nemcio** [comment]
This is the use of RAM:
https://prnt.sc/w0m4sp
It hangs on for hours:
https://prnt.sc/w0m5hi

**Comment by Nemcio** [comment]
Sorry, I can't edit this post.
OpenATV 6.5 compiles OK.

**Comment by nickersk** [comment]
6.5 uses almost same buildsystem version as openvision uses ... 6.4 is older

**Comment by Nemcio** [comment]
I know.
I compile each version completely in different directories. Separately.
OpenaTV 6.5 is not an official version.
Stable is 6.4 and that's why I want to compile it.

**Comment by nickersk** [comment]
then you must find where it fails in compile log and after we can investigate what is the reason bitbake broke:-)

**Comment by Nemcio** [comment]
I get it.
Look at the pictures I added.
So the compilation hung all night without error. So enter the file from which I should provide the log.
It still doesn't compile, it hangs like that and that's the problem.
Htop is only 1 process related to python3:
https://prnt.sc/w0n37a
I have been compiling 2 years and never had a problem with your distribution.

**Comment by nickersk** [comment]
first brake this stucked build by pressing ctrl+c, then check and kill bitbake processes left. reboot and try again.

**Comment by Nemcio** [comment]
I have done this many times already.
If ctl + c and restarting the system helped, I would not write.
Does not help. It hangs on the same as in the picture.
That's why I'm writing.
Errors occurred when I forced BB_NUMBER_THREADS = "30".
They could be caused by uncompiled dependencies.

**Comment by nickersk** [comment]
thats exactly reason why bitbake hang. from openembedded ref manual: BB_NUMBER_THREADS
The maximum number of tasks BitBake should run in parallel at any one time. If your host development system supports multiple cores a good rule of thumb is to set this variable to twice the number of cores.

**Comment by nickersk** [comment]
on such strong hw you use i guess 4 cores cpu set BB_NUMBER_THREADS to 8, run build and look on htop in other console.

**Comment by Nemcio** [comment]
Mam ustawione BB_NUMBER_THREADS = "6". 30 dałem dla testu.
Wisi przy takiej konfiguracji site.conf:
SCONF_VERSION = "1"
BB_NUMBER_THREADS = "6"
PARALLEL_MAKE = "-j 6"
BUILD_OPTIMIZATION = "-O2 -pipe"
DL_DIR = "/build-enviroment/sources"
INHERIT += "rm_work"
Before I write Anywhere about a problem, first I check various possibilities and configurations and if it doesn't help, I report the problem.

**Comment by nickersk** [comment]
if it is 6core you can use BB_NUMBER_THREADS = "12" PARALLEL_MAKE = "-j 6"

**Comment by nickersk** [comment]
if each core has 2 threads you can use BB_NUMBER_THREADS = "24" PARALLEL_MAKE = "-j 12" etc.

**Comment by Nemcio** [comment]
I know how to calculate it.
I lowered the values so that there was enough space to compile those in the picture. that there was a reserve but it doesn't help and still hangs on those in the picture.
On 6.5 it compiles to the end and no problem on 6.4 it always hangs on those in the picture.
That's why I started reporting the problem.
Linux are my main systems that I use and I think I have some idea.

**Comment by nickersk** [comment]
wiped out tmp? nothing usefull in dmesg?

**Comment by Nemcio** [comment]
tmp cleaned. There is also nothing in dmesg. I do it from the machine to solve linux problems myself.

**Comment by Nemcio** [comment]
where are the build logs in what directory?

**Comment by nickersk** [comment]
tmp/work/... every bb recipe has its own work dir. but if bitbake hangs there will be no usefull logs since it writes them ...  maybe you can find something here: https://www.yoctoproject.org/docs/current/mega-manual/mega-manual.html

**Comment by Nemcio** [comment]
I just got this error:
ERROR: oe-alliance-branding-remote-6.4+gitAUTOINC+881d27ab29-r0 do_configure: oe_runmake failed
ERROR: oe-alliance-branding-remote-6.4+gitAUTOINC+881d27ab29-r0 do_configure: Execution of '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/temp/run.autotools_preconfigure.93206' failed with exit code 1:
Making clean in BoxBranding
make[1]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding'
Making clean in lib
make[2]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/lib'
rm -rf .libs _libs
test -z "boxbranding.la" || rm -f boxbranding.la
rm -f ./so_locations
rm -f *.o
rm -f *.lo
make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/lib'
Making clean in remotes
make[2]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/remotes'
Makefile:558: *** Recursive variable 'OUTDIRS' references itself (eventually).  Stop.
make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/remotes'
make[1]: *** [Makefile:492: clean-recursive] Error 1
make[1]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding'
make: *** [Makefile:462: clean-recursive] Error 1
WARNING: /build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/temp/run.autotools_preconfigure.93206:1 exit 1 from 'exit 1'

ERROR: Logfile of failure stored in: /build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/temp/log.do_configure.93206
Log data follows:
| DEBUG: Executing shell function autotools_preconfigure
| NOTE: make clean
| Making clean in BoxBranding
| make[1]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding'
| Making clean in lib
| make[2]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/lib'
| rm -rf .libs _libs
| test -z "boxbranding.la" || rm -f boxbranding.la
| rm -f ./so_locations
| rm -f *.o
| rm -f *.lo
| make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/lib'
| Making clean in remotes
| make[2]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/remotes'
| Makefile:558: *** Recursive variable 'OUTDIRS' references itself (eventually).  Stop.
| make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/remotes'
| make[1]: *** [Makefile:492: clean-recursive] Error 1
| make[1]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding'
| make: *** [Makefile:462: clean-recursive] Error 1
| ERROR: oe_runmake failed
| WARNING: /build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/temp/run.autotools_preconfigure.93206:1 exit 1 from 'exit 1'
| ERROR: Execution of '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/temp/run.autotools_preconfigure.93206' failed with exit code 1:
| Making clean in BoxBranding
| make[1]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding'
| Making clean in lib
| make[2]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/lib'
| rm -rf .libs _libs
| test -z "boxbranding.la" || rm -f boxbranding.la
| rm -f ./so_locations
| rm -f *.o
| rm -f *.lo
| make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/lib'
| Making clean in remotes
| make[2]: Entering directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/remotes'
| Makefile:558: *** Recursive variable 'OUTDIRS' references itself (eventually).  Stop.
| make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding/remotes'
| make[1]: *** [Makefile:492: clean-recursive] Error 1
| make[1]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/git/BoxBranding'
| make: *** [Makefile:462: clean-recursive] Error 1
| WARNING: /build-enviroment/builds/openatv/release/inihdp/tmp/work/mbultra-oe-linux/oe-alliance-branding-remote/6.4+gitAUTOINC+881d27ab29-r0/temp/run.autotools_preconfigure.93206:1 exit 1 from 'exit 1'
| 
ERROR: Task (/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/image/oe-alliance-branding-remote.bb:do_configure) failed with exit code '1

**Comment by nickersk** [comment]
start build from scratch remove whole builds dir

**Comment by Nemcio** [comment]
Sorry, I had a server crash at work.
I have to go to the directory:
builds/openatv/release/inihdp
And execute the command:
run source env.conf; bitbake -c clean -b oe-alliance-branding; bitbake -c clean oe-alliance-branding-remote; bitbake openatv-image
?

**Comment by Nemcio** [comment]
Please write down what to do.

**Comment by nickersk** [comment]
yes, run those commands one by one

**Comment by Nemcio** [comment]
So I have to execute each command in turn like this:
cd /builds/openatv/release/inihdp
enter
run source env.source
enter
bitbake -c clean -b oe-alliance-branding
enter
bitbake -c clean oe-alliance-branding-remote
enter
bitbake openatv-image
?

**Comment by nickersk** [comment]
without "run" only source env.source

**Comment by Nemcio** [comment]
cd /builds/openatv/release/inihdp
enter
source env.source
enter
bitbake -c clean -b oe-alliance-branding
enter
bitbake -c clean oe-alliance-branding-remote
enter
bitbake openatv-image
?

**Comment by Nemcio** [comment]
Can OTV 6.5 be compiled with gcc-9 or do I need to upgrade to gcc-10?

**Comment by nickersk** [comment]
good question, havent tried it yet.

**Comment by Nemcio** [comment]
Neither have I tried. That's why I ask.

**Comment by Nemcio** [comment]
Are enigma2-plugin-systemplugins-serviceapp and enigma2-plugin-systemplugins-servicemp3 compiled in OTV 6.4?

**Comment by nickersk** [comment]
serviceapp yes, servicemp3 if i am not wrong.

**Comment by Nemcio** [comment]
And could you ask to add?
I wanted to add both myself, but I get a compilation error.

**Comment by nickersk** [comment]
servicemp3 is part of atv enigma2. openpli separted it ti lib. dont forget to compile 6.4 with python 2, 6.5 with python3.

**Comment by Nemcio** [comment]
https://github.com/openatv/enigma2/tree/6.4
See the description (README.md).
It is written:

2 - Set python3 as preferred provider for python

sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
sudo update-alternatives --config python
select python3
I still have a copilation error with enigma2-plugin-systemplugins-serviceapp and enigma2-plugin-systemplugins-servicemp3.
That's why I asked.
I join bb.

**Comment by Nemcio** [comment]
enigma2-plugin-systemplugins-serviceapp.bb:
DESCRIPTION = "serviceapp service for enigma2"
AUTHOR = "Maroš Ondrášek <mx3ldev@gmail.com>"
LICENSE = "GPLv2"
LIC_FILES_CHKSUM = "file://COPYING;md5=b234ee4d69f5fce4486a80fdaf4a4263"

DEPENDS = "enigma2 uchardet openssl"
RDEPENDS_${PN} = "enigma2 uchardet openssl exteplayer3 python-json"
RCONFLICTS_${PN} = "enigma2-plugin-extensions-serviceapp"
RREPLACES_${PN} = "enigma2-plugin-extensions-serviceapp"

SRCREV = "${AUTOREV}"
SRCREV_openatv = "02956ea6b05a0186667582f9f25491f18334d31b"
SRC_URI = " \
    git://github.com/mx3L/serviceapp.git;branch=develop \
    "

S = "${WORKDIR}/git"

inherit autotools gitpkgv pythonnative pkgconfig gettext

CXXFLAGS_append = " -std=c++11"

PV = "0.5+git${SRCPV}"
PKGV = "0.5+git${GITPKGV}"

PR = "r0"

EXTRA_OECONF = "\
	BUILD_SYS=${BUILD_SYS} \
	HOST_SYS=${HOST_SYS} \
	STAGING_INCDIR=${STAGING_INCDIR} \
	STAGING_LIBDIR=${STAGING_LIBDIR} \
	"

PACKAGES = "${PN} ${PN}-src ${PN}-dbg"

FILES_${PN} = "\
    ${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceApp/*.pyo \
    ${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceApp/serviceapp.so \
    ${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceApp/locale/*/*/*.mo \
    "

FILES_${PN}-src = "\
    ${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceApp/*.py \
    ${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceApp/locale/*/LC_MESSAGES/*.mo \
    /usr/src/debug/* \
    "

FILES_${PN}-dbg = "\
    ${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceApp/serviceapp.la \
    /usr/src/debug/enigma2-plugin-systemplugins-serviceapp/*/*/*/*/*.cpp \
    /usr/src/debug/enigma2-plugin-systemplugins-serviceapp/*/*/*/*/*.h \
    /usr/src/debug/enigma2-plugin-systemplugins-serviceapp/*/*/*/*/*.c \
    /usr/src/debug/enigma2-plugin-systemplugins-serviceapp/*/*/*/*/*/*.cpp \
    /usr/src/debug/enigma2-plugin-systemplugins-serviceapp/*/*/*/*/*/*.h \
    /usr/src/debug/enigma2-plugin-systemplugins-serviceapp/*/*/*/*/*/*.c \
    "
enigma2-plugin-systemplugins-servicemp3.bb:
DESCRIPTION = "servicemp3 for enigma2"
AUTHOR = "OpenPLi team <info@openpli.org>"
LICENSE = "GPLv2"
LIC_FILES_CHKSUM = "file://COPYING;md5=b234ee4d69f5fce4486a80fdaf4a4263"

PACKAGE_ARCH = "${MACHINE_ARCH}"

PROVIDES += "virtual/enigma2-mediaservice"
RPROVIDES_${PN} += "virtual/enigma2-mediaservice"

GST_BASE_RDEPS = "\
	gstreamer${GST_VERSION}-plugins-base-alsa \
	gstreamer${GST_VERSION}-plugins-base-app \
	gstreamer${GST_VERSION}-plugins-base-audioconvert \
	gstreamer${GST_VERSION}-plugins-base-audioresample \
	gstreamer${GST_VERSION}-plugins-base-audiorate \
	gstreamer${GST_VERSION}-plugins-base-videoconvert \
	gstreamer${GST_VERSION}-plugins-base-ivorbisdec \
	gstreamer${GST_VERSION}-plugins-base-ogg \
	gstreamer${GST_VERSION}-plugins-base-opus \
	gstreamer${GST_VERSION}-plugins-base-playback \
	gstreamer${GST_VERSION}-plugins-base-subparse \
	gstreamer${GST_VERSION}-plugins-base-typefindfunctions \
	gstreamer${GST_VERSION}-plugins-base-vorbis \
	gstreamer${GST_VERSION}-plugins-base-rawparse \
	"

GST_GOOD_RDEPS = "\
	gstreamer${GST_VERSION}-plugins-good-apetag \
	gstreamer${GST_VERSION}-plugins-good-audioparsers \
	gstreamer${GST_VERSION}-plugins-good-autodetect \
	gstreamer${GST_VERSION}-plugins-good-avi \
	gstreamer${GST_VERSION}-plugins-good-flac \
	gstreamer${GST_VERSION}-plugins-good-flv \
	gstreamer${GST_VERSION}-plugins-good-icydemux \
	gstreamer${GST_VERSION}-plugins-good-id3demux \
	gstreamer${GST_VERSION}-plugins-good-isomp4 \
	gstreamer${GST_VERSION}-plugins-good-matroska \
	gstreamer${GST_VERSION}-plugins-good-mpg123 \
	gstreamer${GST_VERSION}-plugins-good-rtp \
	gstreamer${GST_VERSION}-plugins-good-rtpmanager \
	gstreamer${GST_VERSION}-plugins-good-rtsp \
	gstreamer${GST_VERSION}-plugins-good-soup \
	gstreamer${GST_VERSION}-plugins-good-udp \
	gstreamer${GST_VERSION}-plugins-good-wavparse \
	gstreamer${GST_VERSION}-plugins-good-wavpack \
	"

GST_BAD_RDEPS = "\
	gstreamer${GST_VERSION}-plugins-bad-autoconvert \
	gstreamer${GST_VERSION}-plugins-bad-dashdemux \
	gstreamer${GST_VERSION}-plugins-bad-mms \
	gstreamer${GST_VERSION}-plugins-bad-mpegpsdemux \
	gstreamer${GST_VERSION}-plugins-bad-mpegtsdemux \
	gstreamer${GST_VERSION}-plugins-bad-rtmp \
	gstreamer${GST_VERSION}-plugins-bad-smoothstreaming \
	gstreamer${GST_VERSION}-plugins-bad-faad \
	gstreamer${GST_VERSION}-plugins-bad-hls \
	gstreamer${GST_VERSION}-plugins-bad-opusparse \
	gstreamer${GST_VERSION}-plugins-bad-videoparsersbad \
	"

GST_UGLY_RDEPS = "\
	gstreamer${GST_VERSION}-plugins-ugly-amrnb \
	gstreamer${GST_VERSION}-plugins-ugly-amrwbdec \
	gstreamer${GST_VERSION}-plugins-ugly-asf \
	gstreamer${GST_VERSION}-plugins-ugly-cdio \
	gstreamer${GST_VERSION}-plugins-ugly-dvdsub \
	"

DEPENDS = "\
	enigma2 \
	gstreamer${GST_VERSION}-plugins-base gstreamer${GST_VERSION} \
	"

RDEPENDS_${PN} = "\
	enigma2 \
	"

RRECOMMENDS_${PN} = "\
	glib-networking \
	gstreamer${GST_VERSION}-plugin-subsink \
	${GST_BASE_RDEPS} \
	${GST_GOOD_RDEPS} \
	${GST_BAD_RDEPS} \
	${GST_UGLY_RDEPS} \
	"

SRC_URI = "git://github.com/openpli/servicemp3.git;branch=master"
SRCREV = "${AUTOREV}"

S = "${WORKDIR}/git"

inherit autotools gitpkgv pythonnative pkgconfig

PV = "git${SRCPV}"
PKGV = "git${GITPKGV}"

EXTRA_OECONF = "\
	--with-gstversion=${GST_VERSION} \
	BUILD_SYS=${BUILD_SYS} \
	HOST_SYS=${HOST_SYS} \
	STAGING_INCDIR=${STAGING_INCDIR} \
	STAGING_LIBDIR=${STAGING_LIBDIR} \
	"

FILES_${PN} = "\
	${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceMP3/*.pyo \
	${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceMP3/servicemp3.so"

FILES_${PN}-dev = "\
	${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceMP3/*.py \
	${libdir}/enigma2/python/Plugins/SystemPlugins/ServiceMP3/servicemp3.la"

**Comment by nickersk** [comment]
thx for notice, i updated readme for 6.4

**Comment by Nemcio** [comment]
ERROR: Task (/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb:do_compile) failed
Summary: 1 task failed:
  /build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:1025: image] Error 1
I have a problem with that.

**Comment by nickersk** [comment]
have you wiped out tmp after preferred python version changed?
look for error in coresponding do_compile log (path of log.do_compile is in bitbake error output)

**Comment by Nemcio** [comment]
I cleaned and compiled from python2. I'll let you know how it compiles.

**Comment by nickersk** [comment]
if you change any preferred version on host, you have to wipe out tmpdir since hosttools used by bitbake dont know of this change, and hosttools need to be recreated for new...

**Comment by Nemcio** [comment]
I know. But in the description it was using python3 as I compiled.
Still, the signal meter and% signal strength do not work. It shows either 0% or 99%.

**Comment by nickersk** [comment]
try to create thread on https://opena.tv forum regarding this. looks like drivers issue.

**Comment by Nemcio** [comment]
This problem was reported on the forum almost a year ago. There are even a few topics about it but no response from you.

**Comment by Nemcio** [comment]
rm -rf tmp and compile:
| ../../../git/src/serviceapp/serviceapp.h: In member function 'virtual RESULT eServiceFactoryApp::play(const eServiceReference&, ePtr<iPlayableService>&)':
| ../../../git/src/serviceapp/serviceapp.h:214:98: error: invalid new-expression of abstract class type 'eServiceApp'
|   214 |  RESULT play(const eServiceReference &ref, ePtr<iPlayableService> &ptr){ptr = new eServiceApp(ref); return 0;};
|       |                                                                                                  ^
| In file included from ../../../git/src/serviceapp/serviceapp.cpp:19:
| ../../../git/src/serviceapp/serviceapp.h:33:7: note:   because the following virtual functions are pure within 'eServiceApp':
|    33 | class eServiceApp: public sigc::trackable,
|       |       ^~~~~~~~~~~
| In file included from /build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-systemplugins-serviceapp/0.5+gitAUTOINC+1559e949a3-r0/recipe-sysroot/usr/include/enigma2/lib/service/service.h:6,
|                  from ../../../git/src/serviceapp/serviceapp.cpp:7:
| /build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-systemplugins-serviceapp/0.5+gitAUTOINC+1559e949a3-r0/recipe-sysroot/usr/include/enigma2/lib/service/iservice.h:957:17: note:       'virtual RESULT iPlayableService::setTarget(int, bool)'
|   957 |  virtual RESULT setTarget(int target, bool noaudio = false)=0;
|       |                 ^~~~~~~~~
| make[2]: *** [Makefile:576: serviceapp.lo] Error 1
| make[2]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-systemplugins-serviceapp/0.5+gitAUTOINC+1559e949a3-r0/build/src/serviceapp'
| make[1]: *** [Makefile:373: all-recursive] Error 1
| make[1]: Leaving directory '/build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-systemplugins-serviceapp/0.5+gitAUTOINC+1559e949a3-r0/build/src'
| make: *** [Makefile:402: all-recursive] Error 1
| WARNING: /build-enviroment/builds/openatv/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-systemplugins-serviceapp/0.5+gitAUTOINC+1559e949a3-r0/temp/run.do_compile.412107:1 exit 1 from 'exit 1'
| 
ERROR: Task (/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb:do_compile) failed with exit code '1'

**Comment by Nemcio** [comment]
MACHINE=mbultra
but the problem is for the whole ini:
https://github.com/oe-alliance/oe-alliance-core/tree/4.4/meta-brands/meta-ini
This problem has been around for a year for mispel processors:
"Still, the signal meter and% signal strength do not work. It shows either 0% or 99%."

**Comment by Nemcio** [comment]
It came out with the stable version 6.4 and was reported on the forum.

**Comment by nickersk** [comment]
have you wrote to manufacturer of the box?

**Comment by Nemcio** [comment]
Yes, a bug with compilation with gcc, g ++ 9.3.0 py 2., ubuntu 20.04x.

**Comment by Nemcio** [comment]
You can also add gcc, g ++ 9.3.0 in readme.

**Comment by nickersk** [comment]
built ok here.

**Comment by Nemcio** [comment]
I'm also OK.
There is only a problem with the signal meter and the% signal strength which forum reports are ignored.
I will check build 6.5 with gcc 9.
