### ISSUE TITLE
Full Image Backups are broken

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#1876]
The image appears to backup OK and all seems well, until you actually come to use the backup. It refuses to flash from either Online Backup within Software Management or from USB.

It gets as far as updating rootfs but then reboots and the box will then not boot at all. The only way to then get the box to boot is to flash a clean image. I don't know if its relevant, but the clean image always repartitions the flash after the failed attempt to flash the image backup.

**Comment by atvcaptain** [comment]
little more infos please, image you use, date and version, box model etc

**Comment by ian10951** [comment]
OpenATV 6.4, Dated 24th December 2020, VU+ Solo4K

Its been discussed in the English section of the ATV forum, where another user also has this issue, but I do not know what box he uses.
