### ISSUE TITLE
H9S usb 3.0 port problem Zgemma h9s USB3.0 port not reading 3.0usb drives

### ISSUE THREAD

**Issue by ravstar** [openatv/enigma2#1883]
Hi, 

I have Zgemma H9s with usb 3.0 port and USB 3.0 port does not read any USB 3.0 HDD / flash drive, it only reads USB 2.0 drive in 3.0 port on OpenAtv 6.2 and above

When I insert usb 3.0 HDD / flash drive in USB 2.0 port, it read it ok.

I can see it was working fine on OpenATV 6.1 image link http://images.mynonpublic.com/openatv/6.1/index.php?open=zgemmah9s

Look like there is driver issue. 

Please can you help to fix this issue. 

Thank you

**Comment by ozone1864** [comment]
@ravstar, I already reported the issue for Zgemma and @atvcaptain but still no solution.

**Comment by ozone1864** [comment]
#1680

**Comment by elnoelsi** [comment]
why is this ignored

**Comment by atvcaptain** [comment]
fixed https://github.com/oe-alliance/oe-alliance-core/commit/f6fb2a3f0896c3950670543de01ea1dc00850a9b
