### ISSUE TITLE
fatal: unable to access 'https://code.videolan.org/videolan/dvblast.git/': Failed to connect to code.videolan.org port 443: No route to host

### ISSUE THREAD

**Issue by atefganm** [openatv/enigma2#1884]
`Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "sh4-oe-linux"
MACHINE              = "spark"
DISTRO               = "openatv"
DISTRO_VERSION       = "6.4"
TUNE_FEATURES        = "sh4"
meta                 = "HEAD:b6abf7c201f7c9668bdf3c6e87c7dbc70c6427f9"
meta-oe              
meta-multimedia      
meta-networking      
meta-filesystems     
meta-python          
meta-webserver       = "HEAD:fd1a0c9210b162ccb147e933984c755d32899efc"
meta-oe              = "HEAD:481f0dec4d6373c993e1be1a990b94d73cbe7487"
meta-qt5             = "HEAD:22f3362cfc08453a97a01eedeeac6b03eee1b71d"
meta-airdigital      
meta-amiko           
meta-ax              
meta-blackbox        
meta-beyonwiz        
meta-ceryon          
meta-cube            
meta-dags            
meta-dinobot         
meta-dream           
meta-edision         
meta-entwopia        
meta-formuler        
meta-fulan           
meta-gfutures        
meta-gigablue        
meta-ini             
meta-ixuss           
meta-maxytec         
meta-broadmedia      
meta-odin            
meta-octagon         
meta-protek          
meta-skylake         
meta-tiviar          
meta-tripledot       
meta-uclan           
meta-ultramini       
meta-vuplus          
meta-xp              
meta-xtrend          
meta-xcore           = "HEAD:481f0dec4d6373c993e1be1a990b94d73cbe7487"
meta-local           = "4.4:8a59885634e20908ada9e7ae1694a8c2c295a20b"

Initialising tasks: 100% |##########################################################################################################################################################################| Time: 0:00:13
Sstate summary: Wanted 5008 Found 0 Missed 5008 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: Variable key FILES_${PN} ( ${bindir}/faac ) replaces original key FILES_faac ( ${bindir}/faac ).
WARNING: asn1compile-native-4.9.15-r0 do_patch: Fuzz detected:

Applying patch 301-Revert-source3-wscript-remove-pam_smbpass-option-as-it-was-removed.patch
patching file source3/wscript
Hunk #1 succeeded at 43 with fuzz 2 (offset -3 lines).
Hunk #2 succeeded at 932 (offset 1 line).

The context lines in the patches can be updated with devtool:

    devtool modify asn1compile-native
    devtool finish --force-patch-refresh asn1compile-native <layer_path>

Don't forget to review changes done by devtool!

WARNING: asn1compile-native-4.9.15-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]
WARNING: samba-4.9.15-r3 do_patch: Fuzz detected:

Applying patch 301-Revert-source3-wscript-remove-pam_smbpass-option-as-it-was-removed.patch
patching file source3/wscript
Hunk #1 succeeded at 43 with fuzz 2 (offset -3 lines).
Hunk #2 succeeded at 932 (offset 1 line).

The context lines in the patches can be updated with devtool:

    devtool modify samba
    devtool finish --force-patch-refresh samba <layer_path>

Don't forget to review changes done by devtool!

WARNING: samba-4.9.15-r3 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]
WARNING: samba-4.9.15-r3 do_configure: QA Issue: samba: invalid PACKAGECONFIG: netbios [invalid-packageconfig]
WARNING: gstreamer1.0-plugins-bad-1.17.0.1+gitAUTOINC+f2c75d548d-r0 do_configure: QA Issue: gstreamer1.0-plugins-bad: configure was passed unrecognised options: --disable-qt [unknown-configure-option]
WARNING: samba-4.9.15-r3 do_package_qa: QA Issue: samba: The compile log indicates that host include and/or library paths were used.
         Please check the log '/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/samba/4.9.15-r3/temp/log.do_compile' for more information. [compile-host-path]
WARNING: unjffs2-1.0+gitAUTOINC+505dc8c49a-r0 do_populate_lic: unjffs2: No generic license file exists for: GPL in any provider
WARNING: dvblast-3.4+gitAUTOINC+4270dcae7b-r0 do_fetch: Failed to fetch URL git://code.videolan.org/videolan/dvblast.git;protocol=https, attempting MIRRORS if available
ERROR: dvblast-3.4+gitAUTOINC+4270dcae7b-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1764"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/atef/build-enviroment/openembedded-core/scripts:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/recipe-sysroot-native/usr/bin/sh4-oe-linux:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/recipe-sysroot/usr/bin/crossscripts:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/recipe-sysroot-native/usr/sbin:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/recipe-sysroot-native/usr/bin:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/recipe-sysroot-native/sbin:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/recipe-sysroot-native/bin:/home/atef/build-enviroment/bitbake/bin:/home/atef/build-enviroment/builds/openatv/release/spark/tmp/hosttools"; export HOME="/home/atef"; LANG=C git -c core.fsyncobjectfiles=0 fetch -f --prune --progress https://code.videolan.org/videolan/dvblast.git refs/*:refs/* failed with exit code 128, output:
fatal: unable to access 'https://code.videolan.org/videolan/dvblast.git/': Failed to connect to code.videolan.org port 443: No route to host

ERROR: dvblast-3.4+gitAUTOINC+4270dcae7b-r0 do_fetch: Fetcher failure for URL: 'git://code.videolan.org/videolan/dvblast.git;protocol=https'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/atef/build-enviroment/builds/openatv/release/spark/tmp/work/sh4-oe-linux/dvblast/3.4+gitAUTOINC+4270dcae7b-r0/temp/log.do_fetch.190003
ERROR: Task (/home/atef/build-enviroment/meta-oe-alliance/meta-oe/recipes-multimedia/dvblast/dvblast_git.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 12981 tasks of which 247 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/build-enviroment/meta-oe-alliance/meta-oe/recipes-multimedia/dvblast/dvblast_git.bb:do_fetch
Summary: There were 771 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:1034: image] Error 1
atef@atef-ganm:~/build-enviroment$ 1
`

**Comment by nickersk** [comment]
videolan git is back online now. closing.
