### ISSUE TITLE
HDMI CEC issue OpenATV 6.5

### ISSUE THREAD

**Issue by Gouster4** [openatv/enigma2#1886]
13:08:46.0679 <Tx:> 0F 84 62 27 30 5C 78 30 30 5C 78 30 33 27       Broadcast Report Physical Address wrong data length

**Comment by Gouster4** [comment]
Same issue when reporting Address and Audio Contorol.

**Comment by Gouster4** [comment]
i changed values to 0x30, 0x00 (my device is connected to hdmi3 port) inside HdmiCec.py, and problem persist. so there must be issue at data sending part, as address part seems to be correct.

**Comment by jbleyel** [comment]
Please create a new issue if this is not fixed in 7.4
