### ISSUE TITLE
Recording with % in filename not working properly

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#1897]
This recording file name "20210315 2215 - NITRO HD - 100% Bundesliga - Fußball bei NITRO.ts"
Gets  this sref string "1:0:0:0:0:0:0:0:0:0:/<PATH>/20210315 2215 - NITRO HD - 100%25 Bundesliga - Fu\u00dfball bei NITRO.ts"

`serviceref.toString()` 

Why?

The correct sref string should be.

"1:0:0:0:0:0:0:0:0:0:/<PATH>/20210315 2215 - NITRO HD - 100% Bundesliga - Fu\u00dfball bei NITRO.ts"

Reproduce:

```
from Components.MovieList import MovieList

movielist = MovieList(None)
movielist.load(root=<PATH>)
for (serviceref, info, begin, unknown) in movielist.list:
 print(serviceref.toString())

```

**Comment by jbleyel** [comment]
We should change this :

https://github.com/openatv/enigma2/blob/e330adbbfea5c15dd4fa8afc29b0afde7bfb3f39/lib/python/Tools/Directories.py#L309

OLD:
`non_allowed_characters = "/.\\:*?<>|\""`
NEW:
`non_allowed_characters = "/.\\:*?<>|\"%"`

**Comment by AbuBaniaz** [comment]
I suppose we could do. Do you want a third opinion from @IanSav ?

**Comment by IanSav** [comment]
I wouldn't remove the "%' character as it is very popular in program names.  I would simply protect the "%" when used in a printf context.  That is, where there is a "%" use the "%%" syntaxt to output the real "%" and not try to do a substitution.

**Comment by IanSav** [comment]
By the way, all characters, except NUL, are valid in pathnames.  The directory specifier, "/" in Unix, is special but is part of the pathname syntax.  The trick is to ensure that the code handling the pathname doesn't try to interpret or process the pathname.  If any of the characters are meaningful to any part of the code then those characters need to be appropriately protected.

**Comment by IanSav** [comment]
@jbleyel, by the way, I assume you realised that "%25" is simply the URL coding for a "%" sign?

See (for example): [https://www.w3schools.com/tags/ref_urlencode.ASP](https://www.w3schools.com/tags/ref_urlencode.ASP)

**Comment by jbleyel** [comment]
Yes, but this will not fix the problem.

**Comment by IanSav** [comment]
I agree, I just wanted to explain what was happening.

I don't have time now (I am reworking the remote control system) but if I get some time I will explore this issue in more detail and report back.

**Comment by jbleyel** [comment]
Hi @IanSav can you please check these 2 issues or forward to someone else.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1216
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1295 (see last comment)
Thanks

**Comment by IanSav** [comment]
Hi @jbleyel, can you please give me some steps to reproduce the issue.  Perhaps a debug log showing the issue.  I am trying to identify the appropriate place to start my investigation.

**Comment by IanSav** [comment]
I'm sorry but I don't see the link between those threads and "%" characters in recording names.  I am still unsure where the "%" characters in a file name are causing issues.

(Remember that most of my work in in the Enigma2 UI.  I am happy to help but you will need to give me more information to help me find the area of code that needs investigation.)

**Comment by jbleyel** [comment]
A OK.
You need to create a recording with % and then try to stream this file via openwebif.

**Comment by IanSav** [comment]
I will try and set that up tomorrow.  It is 3:30 AM in Australia so I need to get some sleep now.

**Comment by IanSav** [comment]
Interesting, before going to sleep I renamed a recording to have a "%" sign in the name.  OpenWebif streams it with no issues but when I tried to rename the file in the movie player I got a "Error global 'newbasename' is not defined"!  Well this gives me something to start looking at.  ;)

**Comment by IanSav** [comment]
@Jbleyel, I have been trying to fault streaming of a recording with a "%" sign in its name.  I am unable to reproduce the issue.  I am using OpenVision 10.2 r384 with OpenWebif 1.4.5.2.

Can you give me any more information on how to reproduce the issue?

**Comment by jbleyel** [comment]
I have fixed this already ..

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f6853e60f4e5bed0c546d65544072cd5f20f5673#diff-23517c48710eb6c6228252c81c96554e9a00eb917d5bab28857c467cecb4182a

You need to remove the fix in OpenWebif.
