### ISSUE TITLE
audio ch0: tsm fail

### ISSUE THREAD

**Issue by A-nglea** [openatv/enigma2#1900]
Openatv 6.5
oot@dm920:/var/log# grep fail  messages*
messages.0:Mar 28 20:31:59 dm920 user.warn kernel: [98523.682657] audio ch0: tsm fail
messages.0:Mar 28 20:42:15 dm920 user.warn kernel: [99139.553037] audio ch0: tsm fail
messages.0:Mar 28 20:42:30 dm920 user.warn kernel: [99154.218204] audio ch0: tsm fail
messages.0:Mar 28 20:42:30 dm920 user.warn kernel: [99154.248690] audio ch0: tsm fail
messages.0:Mar 28 20:42:30 dm920 user.warn kernel: [99154.279090] audio ch0: tsm fail
messages.0:Mar 28 20:42:30 dm920 user.warn kernel: [99154.313443] audio ch0: tsm fail
messages.0:Mar 28 20:42:36 dm920 user.warn kernel: [99160.929320] audio ch0: tsm fail
messages.0:Mar 28 20:44:32 dm920 user.warn kernel: [99276.090131] audio ch0: tsm fail
messages.0:Mar 28 20:44:54 dm920 user.warn kernel: [99297.914456] audio ch0: tsm fail
messages.0:Mar 28 20:44:54 dm920 user.warn kernel: [99297.944877] audio ch0: tsm fail
messages.0:Mar 28 20:44:54 dm920 user.warn kernel: [99297.975448] audio ch0: tsm fail
messages.0:Mar 28 20:44:54 dm920 user.warn kernel: [99298.009764] audio ch0: tsm fail
messages.0:Mar 28 20:57:20 dm920 user.warn kernel: [100044.204052] audio ch0: tsm fail
messages.0:Mar 28 22:31:57 dm920 user.warn kernel: [105721.641755] audio ch0: tsm fail
messages.0:Mar 28 22:31:57 dm920 user.warn kernel: [105721.675933] audio ch0: tsm fail
messages.0:Mar 28 22:58:35 dm920 user.warn kernel: [107320.315862] audio ch0: tsm fail
messages.0:Mar 28 22:59:08 dm920 user.warn kernel: [107352.981699] audio ch0: tsm fail
messages.0:Mar 28 22:59:08 dm920 user.warn kernel: [107353.012165] audio ch0: tsm fail

**Comment by jbleyel** [comment]
Please try 7.2 and reopen with more details.
