### ISSUE TITLE
Expired Certificates

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1905]
I am not to sure if this is directly related to openatv, oe-alliance or the openssl package.

But there are now lots of expired certifcates in 

etc/ca-certificates.conf
usr/share/ca-certificates/mozilla

This is preventing some IPTV providers connecting.

On my box, these certificates are expired and need deleting from the list.

mozilla/AddTrust_External_Root.crt
mozilla/Certplus_Class_2_Primary_CA.crt
mozilla/Deutsche_Telekom_Root_CA_2.crt
mozilla/QuoVadis_Root_CA.crt
mozilla/Sonera_Class_2_Root_CA.crt
mozilla/Staat_der_Nederlanden_Root_CA_-_G2.crt

Addtrust one is particularly troublesome and resulting in failed connections.

**Comment by kiddac** [comment]
Version / Build: 6.4 (3 April 2021)
Kernel: 4. 4.35
Drivers: 28 August 2020
Last enigma 2 update: 2 Apirl 2021

**Comment by kiddac** [comment]
I have removed these certificates myself on my box. 
Just letting the community know that these old ones need removing from future releases

**Comment by nickersk** [comment]
hi, should be fixed for some time: https://github.com/nickersk/oe-alliance-core/commit/03cfcdf5390dbf5fe59fc7ad8211b471e1eced0f

**Comment by thawtes** [comment]
hi, please update again ca-certificates because expired.
@jbleyel @nickersk 
thanks

**Comment by atvcaptain** [comment]
you use openatv 7.2 ?

**Comment by thawtes** [comment]
> you use openatv 7.2 ?

yes i use openatv 7.2

**Comment by atvcaptain** [comment]
update ; https://github.com/oe-alliance/oe-alliance-core/commit/043f8a7f9bf332dabd040bad8d7da62b76d1b149

**Comment by thawtes** [comment]
> update ; [oe-alliance/oe-alliance-core@043f8a7](https://github.com/oe-alliance/oe-alliance-core/commit/043f8a7f9bf332dabd040bad8d7da62b76d1b149)

thank you ...
