### ISSUE TITLE
Installing python-xmlrpc downgrades default Python to v2

### ISSUE THREAD

**Issue by t5k6** [openatv/enigma2#1911]
Command causing the change:
`opkg install python-xmlrpc`

Sistem OE: OE-Alliance 4.5
OpenATV version: 6.5.20210411 (2021-04-11)

It was fixed after running
`update-alternatives --install /usr/bin/python python /usr/bin/python3 1`

While this is a trivial thing, it may cause issues in the long run if not caught

**Comment by nickersk** [comment]
hi, this behavior is ok, since pkgs prefixed with python- are depending on python2. python3 compatible pkgs are prefixed with python3-

**Comment by t5k6** [comment]
Thanks for the explanation. That was my first time checking out version 6.5
