### ISSUE TITLE
Build dev instead release

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#1928]
Hello,

Currently the following command buid a 6.5 image instead of a 6.4:

MACHINE=mutant51 DISTRO=openatv DISTRO_TYPE=release make image

Build Configuration:
BB_VERSION           = "1.47.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "hd51"
DISTRO               = "openatv"
DISTRO_VERSION       = "6.5"
TUNE_FEATURES        = "arm vfp cortexa15 neon vfpv4 callconvention-hard"
TARGET_FPU           = "hard"

**Comment by atvcaptain** [comment]
branch nextp3 build the py3 6.5 image and branch 4.4 the 6.4 py2 image , check the branch you have checkout

**Comment by jeepcook** [comment]
Ok sorry, I made a mistake when migrate from 18.04 to 20.04, I've lost the 6.4 branch !!

I close this issue
