### ISSUE TITLE
Open ATV 6.5 Video play crash

### ISSUE THREAD

**Issue by C74K** [openatv/enigma2#1929]
Open ATV 6.5 Video play crash i open by file menager and software  crash.
[enigma2_crash_1619747674.log](https://github.com/openatv/enigma2/files/6402623/enigma2_crash_1619747674.log)
[enigma2_crash_1619747761.log](https://github.com/openatv/enigma2/files/6402625/enigma2_crash_1619747761.log)

and gui bug 
![IMG_20210430_035838](https://user-images.githubusercontent.com/3368595/116640999-1c392000-a96c-11eb-8824-04a39a1d31a1.jpg)

**Comment by atvcaptain** [comment]
can you enable e2 log

menu -> setup -> system -> logs  settings -> enbale debug log yes
now restart e2

after crash send the log

**Comment by C74K** [comment]
[Enigma2-debug-20210430_10-59-41.log](https://github.com/openatv/enigma2/files/6404149/Enigma2-debug-20210430_10-59-41.log)

**Comment by jbleyel** [comment]
What's the exact video format an how exactly do you start the playback?
What action exactly creates the crash?

**Comment by C74K** [comment]
i play from file exploer.
i dont remember video data after month.

**Comment by jbleyel** [comment]
Please use ATV 7.0 and try again.
