### ISSUE TITLE
OpenATV 6.5 HDMI CEC Volume forwarding 

### ISSUE THREAD

**Issue by gomble** [openatv/enigma2#1934]
Hello , volume forwarding does not work.

Log while i pushed volume up and down:

`15:01:17.1739 <Rx:> 00 87 00 00 00 <TV><Device Vendor ID><0>
15:01:17.3494 <Rx:> 00 87 00 00 00 <TV><Device Vendor ID><0>
15:01:17.5144 <Rx:> 00 87 00 00 00 <TV><Device Vendor ID><0>
15:01:18.8896 <Rx:> 00 8C <TV><Give Device Vendor ID>
15:01:19.1409 <Tx:> 00 87 00 00 00 <TV><Device Vendor ID><0>
15:01:25.2193 <Tx:> 00 44 62 27 41 27 <TV><User Control Pressed><Record Function>
15:01:25.4288 <Tx:> 01 45 <Recording 1><User Control Released>
15:01:26.3209 <Tx:> 00 44 62 27 42 27 <TV><User Control Pressed><Record Function>
15:01:26.5302 <Tx:> 01 45 <Recording 1><User Control Released>`

OE-System:OE-Alliance 4.5
Firmware-Version:OpenATV 6.5.20210512 (2021-05-08)
Kernel / Treiber:4.4.35 / 20201218
Marke & Modell:GigaBlue UHD TRIO 4K
Chipsatz:3798mv200

To compare, here is the log from openmips 6.4 where it works:
`Tx: 14:22:34 > 44 41 [0x05]
Tx: 14:22:34 > 45 [0x05]
Tx: 14:22:34 > 44 41 [0x05]
Tx: 14:22:34 > 45 [0x05]
Tx: 14:22:35 > 44 41 [0x05]
Tx: 14:22:35 > 45 [0x05]
Tx: 14:22:35 > 44 41 [0x05]
Tx: 14:22:35 > 45 [0x05]
Tx: 14:22:35 > 44 41 [0x05]
Tx: 14:22:35 > 45 [0x05]
Rx: 14:22:43 <Device Vendor ID> < 87 00 E0 91
Rx: 14:22:43 <Device Vendor ID> < 87 00 E0 91
Rx: 14:22:43 <Device Vendor ID> < 87 00 E0 91
Rx: 14:22:43 <Device Vendor ID> < 87 00 E0 91
Tx: 14:24:22 > 44 42 [0x05]
Tx: 14:24:22 > 45 [0x05]
`

**Comment by Robot1982** [comment]
I have exactly the same problem on a DM900. Volume forwarding works with OpenATV 6.4 but it doesn't work with 6.5 (latest build).

**Comment by stachi** [comment]
Same here on Mutant HD51 and it still don't works in OpenATV 7.0.

**Comment by jbleyel** [comment]
Please check again with the latest version of ATV 7.0

**Comment by gomble** [comment]
> Please check again with the latest version of ATV 7.0

Nope does not work wit atv7

**Comment by stachi** [comment]
Can confirm. Mutant HD51 still don't works with OpenATV 7.0 build 2021-07-25

**Comment by grzegorz914** [comment]
same for me Ultimo 4K OATV7

**Comment by jbleyel** [comment]
Please provide debug log from 6.4 and 7.0 to compare the diff.
!! Not the complete log, only the part of the vol key action. !!

**Comment by gomble** [comment]
> Please provide debug log from 6.4 and 7.0 to compare the diff.
> !! Not the complete log, only the part of the vol key action. !!

I did, see my first post

**Comment by iPkay** [comment]
@jbleyel 
 
i noticed that the received data are not transmitted or there is a problem with the c ++ -> python interface. 

`
6.4
e2-log
[eHdmiCEC] received message 00 86 12 00
cec-log
<Rx:> 00 86 12 00                                     <TV><Set Stream Path><1.2.0.0>

7.0
e2-log
[eHdmiCEC] received message 00 86 12 00
cec-log
<Rx:> 00 86 00 00                                     <TV><Set Stream Path><0.0.0.0>
`

**Comment by gomble** [comment]
Any news in this ?

**Comment by jbleyel** [comment]
not yet .. this is not so easy to debug

**Comment by jbleyel** [comment]
please try again

**Comment by stachi** [comment]
Got an instant crash loop after Flashing and booting with CEC enabled.

`openATV Enigma2 crash log

crashdate=So Sep  5 18:13:04 2021
compiledate=Sep  4 2021
skin=MetrixHD/skin.MySkin.xml
sourcedate=2021-09-03
branch=7.0
rev=2.8.0-23309-gd534c60
component=Enigma2

stbmodel=hd51
stbmodel=hd51
kernelcmdline=brcm_cma=440M@328M brcm_cma=192M@768M root=/dev/mmcblk0p5 rw rootwait hd51_4.boxmode=1 brcm_cma=440M@328M brcm_cma=192M@768M console=ttyS0,115200
nimsockets=NIM Socket 0:
imageversion=box_type=mutant51
imageissue=Welcome to openATV for %h


[eDVBFrontend] Slow ioctl 'FE_GET_PROPERTY(DTV_API_VERSION)', potential driver issue, 338ms
[ePyObject] (PyObject_CallObject(<bound method HdmiCec.messageReceived of <Components.HdmiCec.HdmiCec object at 0xb0962250>>,(<enigma.iCECMessagePtr; proxy of <Swig Object of type 'ePtr< iCECMessage > *' at 0xaf181638> >,)) failed)
[ePyObject] (PyObject_CallObject(<bound method InfoBarHandleBsod.checkBsodCallback of <class 'Screens.InfoBar.InfoBar'>>,()) failed)
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[ePyObject] (PyObject_CallObject(<bound method HdmiCec.messageReceived of <Components.HdmiCec.HdmiCec object at 0xb0962250>>,(<enigma.iCECMessagePtr; proxy of <Swig Object of type 'ePtr< iCECMessage > *' at 0xae386f38> >,)) failed)
[ePyObject] (PyObject_CallObject(<bound method HdmiCec.messageReceived of <Components.HdmiCec.HdmiCec object at 0xb0962250>>,(<enigma.iCECMessagePtr; proxy of <Swig Object of type 'ePtr< iCECMessage > *' at 0xaf181650> >,)) failed)`

**Comment by stachi** [comment]
After this patch, it works again. https://github.com/openatv/enigma2/commit/419f7a16bdbc0487e6efc03588302a7955a6c845

**Comment by gomble** [comment]
I will test this today

**Comment by gomble** [comment]
Its working with newest OpenATV 7.0 👍
