### ISSUE TITLE
Blind scan fails; repeatable

### ISSUE THREAD

**Issue by A-nglea** [openatv/enigma2#1938]
Starting a blind scan from the set-up menu crashes enigma2. Dreambox DM920 HD

Part Log:-

openATV Enigma2 crash log

crashdate=Tue May 25 13:38:21 2021
compiledate=May 20 2021
skin=MetrixHD/skin.xml
sourcedate=2021-05-14
branch=6.5
rev=2.8.0-22795-g321a810
component=Enigma2

stbmodel=ultimo
stbmodel=dm920
kernelcmdline=bmem=640M@384M bmem=384M@2048M console=ttyS0,1000000 root=/dev/mmc
blk0p2 rootwait rootfstype=ext4 coherent_pool=2M
nimsockets=NIM Socket 0:
imageversion=box_type=dm920
imageissue=Welcome to openATV for %h

[eDVBFrontend] dvb-s mode not aktive!
[eDVBFrontend] dvb-s mode not aktive!
[eDVBFrontend] dvb-s mode not aktive!
[eDVBPESReader] Created. Opening demux
root@dm920:~/logs# cat enigma2_crash_1621946301.log 
openATV Enigma2 crash log

crashdate=Tue May 25 13:38:21 2021
compiledate=May 20 2021
skin=MetrixHD/skin.xml
sourcedate=2021-05-14
branch=6.5
rev=2.8.0-22795-g321a810
component=Enigma2

stbmodel=ultimo
stbmodel=dm920
kernelcmdline=bmem=640M@384M bmem=384M@2048M console=ttyS0,1000000 root=/dev/mmcblk0p2 rootwait rootfstype=ext4 coherent_pool=2M
nimsockets=NIM Socket 0:
imageversion=box_type=dm920
imageissue=Welcome to openATV for %h

[eDVBFrontend] dvb-s mode not aktive!
[eDVBFrontend] dvb-s mode not aktive!
[eDVBFrontend] dvb-s mode not aktive!
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap object at 0xaf0244f0>>,('OkCancelActions', 'ok')) failed)

dmesg

<4>[70654.856377] HDMI: CEC returned state 0
<4>[70654.856381] HDMI: CEC state now 800
<4>[70654.884479] HDMI: CEC Physical Addr 2.0.0.0 set from EDID
<4>[70654.884485] HDMI: EDID read ok
<4>[70654.884494] HDMI: CEC start ... state is now 1
<4>[70654.884577] HDMI: CEC returned state 1
<4>[70654.884582] HDMI: CEC state now 801
<4>[70654.947414] HDMI: CEC use logical address 3
<4>[70654.947431] HDMI: CEC init completed... state is now 3!
<4>[70654.947517] HDMI: CEC returned state 3
<4>[70654.947521] HDMI: CEC state now 803
<4>[70655.084209] HDMI: CEC send ok!
<4>[70668.832238] HDMI: force disconnect!
<4>[70668.832247] HDMI: now disconnected
<4>[70668.832251] HDMI: CEC RX stopped, state is now 0
<4>[70668.832262] HDMI: now powered down
<4>[70668.832376] HDMI: CEC returned state 0
<4>[70668.832381] HDMI: CEC state now 800
<4>[70668.860562] HDMI: CEC Physical Addr 2.0.0.0 set from EDID
<4>[70668.860569] HDMI: EDID read ok
<4>[70668.860579] HDMI: CEC start ... state is now 1
<4>[70668.860680] HDMI: CEC returned state 1
<4>[70668.860684] HDMI: CEC state now 801
<4>[70668.923516] HDMI: CEC use logical address 3
<4>[70668.923534] HDMI: CEC init completed... state is now 3!
<4>[70668.923613] HDMI: CEC returned state 3
<4>[70668.923617] HDMI: CEC state now 803
<4>[70669.060310] HDMI: CEC send ok!
<4>[70681.051237] HDMI: force disconnect!
<4>[70681.051247] HDMI: now disconnected
<4>[70681.051251] HDMI: CEC RX stopped, state is now 0
<4>[70681.051263] HDMI: now powered down

**Comment by jbleyel** [comment]
Please use ATV 7.0
