### ISSUE TITLE
[EPGCache] EPG titles contain `start/end of selected area` characters (OpenATV 6.5, 7.0)

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1954]
Debug mode shows:
<img width="476" alt="Screen Shot 2021-06-15 at 19 09 26" src="https://user-images.githubusercontent.com/9741693/122102349-3d1adf00-ce0d-11eb-9a28-7342b9e94fd5.png">

Copying/pasting shows `RecordTimerEntry(name=Dogs Behaving (Very) Badly, begin=T` as:
<img width="639" alt="Screen Shot 2021-06-15 at 19 09 59" src="https://user-images.githubusercontent.com/9741693/122102415-4c9a2800-ce0d-11eb-843b-e3c249e7e2cb.png">
This also appears in some places in OpenWebif EPG.

Character code (https://amp-what.com)
<img width="250" alt="Screen Shot 2021-06-15 at 19 07 55" src="https://user-images.githubusercontent.com/9741693/122102221-1eb4e380-ce0d-11eb-8974-2172d44e73db.png">

<img width="250" alt="Screen Shot 2021-06-15 at 19 15 17" src="https://user-images.githubusercontent.com/9741693/122103053-10b39280-ce0e-11eb-9580-5268c798578e.png">

Not all channels/times are affected:
<img width="1000" alt="Screen Shot 2021-06-15 at 19 18 02" src="https://user-images.githubusercontent.com/9741693/122103417-80c21880-ce0e-11eb-8387-8e9b4529b110.png">

Astra 28.2E; I don't have access to other satellites.

**Comment by jbleyel** [comment]
This needs to be fixed in epgchache. IMHO.

**Comment by jbleyel** [comment]
Strange ??

This is from OWF.

def removeBad(val):
	if val is not None:
		if PY3:
			return val.replace('\x86', '').replace('\x87', '')
		else:
			return val.replace('\xc2\x86', '').replace('\xc2\x87', '')
	return val

**Comment by wedebe** [comment]
This also affects timer-recorded movies

**Comment by jbleyel** [comment]
Any news here?
What's the source of your EPG Data?

**Comment by jbleyel** [comment]
Any news?

**Comment by jbleyel** [comment]
Hi @wedebe , any news here?

**Comment by wedebe** [comment]
I haven't seen this issue occur in ages, but that's probably because of a workaround being introduced to owif (I think)?

Happy to close
