### ISSUE TITLE
python 3 cannot compare None and Int

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#1959]
In python 3, If a data=None, you cannot for example compare None > -1

“TypeError: '>' not supported between instances of 'int' and 'NoneType'” 

In python 2 None is classed as -1.

An example of this is in PliExtraInfo.py

`def createMisPls(self, fedata):
		tmp = ""
		if fedata.get("is_id") > -1:
			tmp = "MIS %d" % fedata.get("is_id")
		if fedata.get("pls_code") > 0:
			tmp = addspace(tmp) + "%s %d" % (fedata.get("pls_mode"), fedata.get("pls_code"))
		if fedata.get("t2mi_plp_id") > -1:
			tmp = addspace(tmp) + "T2MI %d PID %d" % (fedata.get("t2mi_plp_id"), fedata.get("t2mi_pid"))
		return tmp`
		
when the info bar is first called on a reboot gui, this fedata information will be none.

for example
fedata ?

instead of for example
fedata {'tuner_type': 'Satellite', 'inversion': 'Auto', 'fec_inner': '3/4', 'modulation': '8PSK', 'orbital_position': '28.2E Astra 2E/2F/2G', 'orb_pos': '28.2°E', 'polarization': 'Vertical', 'polarization_abbreviation': 'V', 'system': 'DVB-S2', 'rolloff': '0.20', 'pilot': 'On', 'pls_mode': 'Gold', 'tuner_number': 0, 'tuner_state': 'LOCKED', 'tuner_locked': 1, 'tuner_synced': 1, 'tuner_bit_error_rate': 0, 'tuner_signal_quality': 65535, 'tuner_signal_power': 65520, 'frequency': 10847000, 'symbol_rate': 23000000, 'is_id': -1, 'pls_code': 0, 't2mi_plp_id': -1, 't2mi_pid': 4096}

this will crash and boot loop the box if pliextrainfo is used in the infobar.

I temporarily fixed this adding in an extra if catch. A better solution might be required.

`	def createMisPls(self, fedata):
		tmp = ""
		if fedata.get("is_id") and fedata.get("is_id") > -1:
			tmp = "MIS %d" % fedata.get("is_id")
		if fedata.get("pls_code") and fedata.get("pls_code") > 0:
			tmp = addspace(tmp) + "%s %d" % (fedata.get("pls_mode"), fedata.get("pls_code"))
		if fedata.get("t2mi_plp_id") and fedata.get("t2mi_plp_id") > -1:
			tmp = addspace(tmp) + "T2MI %d PID %d" % (fedata.get("t2mi_plp_id"), fedata.get("t2mi_pid"))
		return tmp`

**Comment by kiddac** [comment]
openvix seem to have already addressed this error in their latest python 3 dev build if you wish to compare.

**Comment by jbleyel** [comment]
We should fix this in PliExtraInfo.py imho.
