### ISSUE TITLE
problem compile maxytecmulti atv 7.0

### ISSUE THREAD

**Issue by sat-hd** [openatv/enigma2#1960]
problem compile maxytecmulti atv 7.0 ( build-enviroment/meta-qt5.15/recipes-qt/qt5/qtwebengine_git.bb:do_compile) failed with exit code '1' )

**Comment by nickersk** [comment]
if you'll find killed signal in dmesg output, then yours ram was overloaded. use 16G swap.

**Comment by sat-hd** [comment]
we use vps 
[https://www11.0zz0.com/2021/06/29/08/308825438.png](url)

**Comment by nickersk** [comment]
how much ram? have you installed yocto host packages as described here? https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html#build-host-packages
which numbers do you use in site.conf for BB_NUMBER_THREADS and PARALLEL_MAKE according to cpu?

**Comment by sat-hd** [comment]
I have installed yocto host packages the same problem

BB_NUMBER_THREADS = "8"
PARALLEL_MAKE = "-j 8"

`https://www12.0zz0.com/2021/06/29/09/732738596.png`

**Comment by nickersk** [comment]
how much ram?

**Comment by sat-hd** [comment]
Mem:           62Gi      used  8.0Gi      free  7.2Gi     
Swap:          31Gi       used 2.0Mi      free  31Gi

**Comment by nickersk** [comment]
please search for error in log.do_compile under qtwebengine build/temp dir as this seems to be no hw issue

**Comment by sat-hd** [comment]
https://www.mediafire.com/file/un8vegowrua4fd8/20210629100759.zip/file

**Comment by jaedon** [comment]
You need to install gcc-multilib and g++-multilib.

**Comment by nickersk** [comment]
https://github.com/openatv/enigma2/blob/7.0/README.md#building-instructions

sudo apt-get install -y autoconf automake bison bzip2 chrpath coreutils cpio curl cvs debianutils default-jre default-jre-headless diffstat flex g++ gawk gcc gcc-8 gcc-multilib g++-multilib gettext git git-core gzip help2man info iputils-ping java-common libc6-dev libegl1-mesa libglib2.0-dev libncurses5-dev libperl4-corelibs-perl libproc-processtable-perl libsdl1.2-dev libserf-dev libtool libxml2-utils make ncurses-bin patch perl pkg-config psmisc python3 python3-git python3-jinja2 python3-pexpect python3-pip python-setuptools qemu quilt socat sshpass subversion tar texi2html texinfo unzip wget xsltproc xterm xz-utils zip zlib1g-dev

**Comment by sat-hd** [comment]
`root@Ubuntu-2004-focal-64-minimal ~ # sudo apt-get install -y gcc-multilib
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc-multilib is already the newest version (4:9.3.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.
root@Ubuntu-2004-focal-64-minimal ~ # sudo apt-get install -y g++-multilib
Reading package lists... Done
Building dependency tree
Reading state information... Done
g++-multilib is already the newest version (4:9.3.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.
root@Ubuntu-2004-focal-64-minimal ~ #
`

**Comment by sat-hd** [comment]
1. root@Ubuntu-2004-focal-64-minimal ~ # sudo apt-get install -y autoconf automake bison bzip2 chrpath coreutils cpio curl cvs debianutils default-jre default-jre-headless diffstat flex g++ gawk gcc gcc-8 gcc-multilib g++-multilib gettext git git-core gzip help2man info iputils-ping java-common libc6-dev libegl1-mesa libglib2.0-dev libncurses5-dev libperl4-corelibs-perl libproc-processtable-perl libsdl1.2-dev libserf-dev libtool libxml2-utils make ncurses-bin patch perl pkg-config psmisc python3 python3-git python3-jinja2 python3-pexpect python3-pip python-setuptools qemu quilt socat sshpass subversion tar texi2html texinfo unzip wget xsltproc xterm xz-utils zip zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
autoconf is already the newest version (2.69-11.1).
automake is already the newest version (1:1.16.1-4ubuntu6).
bison is already the newest version (2:3.5.1+dfsg-1).
bzip2 is already the newest version (1.0.8-2).
coreutils is already the newest version (8.30-3ubuntu2).
cpio is already the newest version (2.13+dfsg-2).
debianutils is already the newest version (4.9.1).
default-jre is already the newest version (2:1.11-72).
default-jre-headless is already the newest version (2:1.11-72).
diffstat is already the newest version (1.63-1).
flex is already the newest version (2.6.4-6.2).
g++ is already the newest version (4:9.3.0-1ubuntu2).
g++-multilib is already the newest version (4:9.3.0-1ubuntu2).
gawk is already the newest version (1:5.0.1+dfsg-1).
gcc is already the newest version (4:9.3.0-1ubuntu2).
gcc-multilib is already the newest version (4:9.3.0-1ubuntu2).
gettext is already the newest version (0.19.8.1-10build1).
gzip is already the newest version (1.10-0ubuntu4).
info is already the newest version (6.7.0.dfsg.2-5).
iputils-ping is already the newest version (3:20190709-3).
java-common is already the newest version (0.72).
libncurses5-dev is already the newest version (6.2-0ubuntu2).
libperl4-corelibs-perl is already the newest version (0.004-2).
libtool is already the newest version (2.4.6-14).
make is already the newest version (4.2.1-1.2).
ncurses-bin is already the newest version (6.2-0ubuntu2).
patch is already the newest version (2.7.6-6).
pkg-config is already the newest version (0.29.1-0ubuntu4).
psmisc is already the newest version (23.3-1).
python3 is already the newest version (3.8.2-0ubuntu2).
python3-jinja2 is already the newest version (2.10.1-2).
python3-pexpect is already the newest version (4.6.0-1build1).
socat is already the newest version (1.7.3.3-2).
unzip is already the newest version (6.0-25ubuntu1).
wget is already the newest version (1.20.3-1ubuntu1).
xsltproc is already the newest version (1.1.34-4).
zip is already the newest version (3.0-11build1).
chrpath is already the newest version (0.16-2).
cvs is already the newest version (2:1.12.13+real-27build1).
gcc-8 is already the newest version (8.4.0-3ubuntu2).
help2man is already the newest version (1.47.13).
libproc-processtable-perl is already the newest version (0.59-2).
libsdl1.2-dev is already the newest version (1.2.15+dfsg2-5).
libserf-dev is already the newest version (1.3.9-8build1).
python-setuptools is already the newest version (44.0.0-2).
python3-git is already the newest version (3.0.7-1).
quilt is already the newest version (0.65-3).
sshpass is already the newest version (1.06-1).
subversion is already the newest version (1.13.0-3).
texi2html is already the newest version (1.82+dfsg1-5).
texinfo is already the newest version (6.7.0.dfsg.2-5).
curl is already the newest version (7.68.0-1ubuntu2.5).
git is already the newest version (1:2.25.1-1ubuntu3.1).
libc6-dev is already the newest version (2.31-0ubuntu9.2).
libglib2.0-dev is already the newest version (2.64.6-1~ubuntu20.04.3).
perl is already the newest version (5.30.0-9ubuntu0.2).
qemu is already the newest version (1:4.2-3ubuntu6.16).
tar is already the newest version (1.30+dfsg-7ubuntu0.20.04.1).
xz-utils is already the newest version (5.2.4-1ubuntu1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.2).
libegl1-mesa is already the newest version (20.2.6-0ubuntu0.20.04.1).
python3-pip is already the newest version (20.0.2-5ubuntu1.5).
xterm is already the newest version (353-1ubuntu1.20.04.2).
libxml2-utils is already the newest version (2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.

**Comment by nickersk** [comment]
if you installed some pkgs after the error occured you have to wipe out tmp dir first to get sysroots rebuilt with new headers.

**Comment by sat-hd** [comment]
okay, i will try the operation after delating tmp

**Comment by sat-hd** [comment]
it is the same problem,reaches 57  %

build-enviroment/meta-qt5.15/recipes-qt/qt5/qtwebengine_git.bb:do_compile) failed with exit code '1'

[url=https://www.0zz0.com][img]https://www14.0zz0.com/2021/06/29/13/883485384.png[/img][/url]

**Comment by nickersk** [comment]
same error in log.do_compile? if yes, then g++ multilib is broken somehow ...

**Comment by sat-hd** [comment]
i did not understand the last part of log 
https://www.mediafire.com/file/08hws3u2ldjp54y/20210629124149.log.zip/file

**Comment by sat-hd** [comment]
on nextp3 atv 6.5  compiled successfully meta-qt5.14

**Comment by nickersk** [comment]
it is searching for g++ version 10 header, do you have g++/gcc 10 installed ?

**Comment by sat-hd** [comment]
yes gcc 10 and 11

**Comment by nickersk** [comment]
sudo apt -y install g++-10-multilib gcc-10-multilib , rebuild

**Comment by sat-hd** [comment]
Today's updates ,successfully built
big thenks nickersk , jaedon and all team .

**Comment by nickersk** [comment]
closing as solved.
