### ISSUE TITLE
Question: OpenATV7.0 wallpaper

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1975]
There was a really nice, super-sharp professional-grade wallpaper for 7.0 up to last week, but now it's merely Microsoft Word Art level quality (sorry to whoever designed it).

Version 6.4 had a gorgeous, subtle dark screen but 6.5 went backwards.

Just wondering how wallpapers are decided on? I know it's possible to manually set any wallpaper, but anyone who's new to OATV will have a lasting impression of the quality very much based on the first screen they see.

**Comment by atvcaptain** [comment]
new 7.0 now 1080p bootlogo :)
