### ISSUE TITLE
ZGemma H7 build fails at linux-airdigital_4.10.12.bb:do_compile

### ISSUE THREAD

**Issue by lincsat** [openatv/enigma2#1994]
Any suggestions how to fix this?

**Comment by atvcaptain** [comment]
more infos logs etc

**Comment by lincsat** [comment]
I didn't have logs to hand as I was trying again. It still fails as does a ViX build. Here is the cooker and compile logs - do you need anything else?

[log.do_compile.log](https://github.com/openatv/enigma2/files/6939339/log.do_compile.log)
[cooker.log](https://github.com/openatv/enigma2/files/6939340/cooker.log)

**Comment by nickersk** [comment]
yylloc multiple defs patch is needed

**Comment by nickersk** [comment]
https://github.com/oe-alliance/oe-alliance-core/tree/5.0/meta-brands/meta-octagon/recipes-linux

**Comment by lincsat** [comment]
Thanks, I'll try to add that to my meta-airdigital and see if it builds

**Comment by lincsat** [comment]
I can confirm that built OK. Could somebody add that as I don't know how to format a PR - thanks
