### ISSUE TITLE
Radio RDS

### ISSUE THREAD

**Issue by flor62** [openatv/enigma2#1995]
I need a little help from a Developer.
I want to do a coding in the skin.xml only for radio-services. The following code doesn't create errors when starting the system, but define the value to 'IsRadio' in line 4 doesn't work:

1  <applet type="onLayoutFinish">
2   from enigma import ServiceReference.ServiceReference
3   def ServiceReference.ServiceReference.getType(self) 
4   isRadio = getType(ServiceReference self)
5   if isRadio == 'radio':
6       self.instance.move(ePoint(0,0))
7   else:
8       self.instance.move(ePoint(500,0))
9  </applet>

Could someone tell me the correct syntax to get the value from getType (ou of ServiceReference) to evatue it in line 5. 
The Value from getType from SericeReference shuld be 'radio' - ist this correct, I saw it so in a .py-code...?
Thank You.

**Comment by jbleyel** [comment]
```
ref = sref.toString().split(":")
isRadio = ref[2] == "2" or ref[2] == "A"

```

**Comment by flor62** [comment]
Thank you for your input.
I tried this:

1 <applet type="onLayoutFinish">
2 from enigma import ServiceReference.ServiceReference
3 def ServiceReference.ServiceReference.getType(self) 	
4 ref = sref.toString().split(":")
5 if ref[2] == "2" or ref[2] == "A":
6 	from enigma import eSize,ePoint, getDesktop
7	self.instance.move(ePoint(300,0))
8 else:
9 	from enigma import eSize,ePoint, getDesktop
10	self.instance.move(ePoint(0,300))
11</applet> 

Enigma starts without errors, but the code doesn't work. I think "sref" in line 4 get no value from enigma import ServiceReference.ServiceReference.
Is the import correct?
Do i need line 3 def... ???

**Comment by flor62** [comment]
Thank you for your input.
I tried this:
1 applet type="onLayoutFinish"
2 from enigma import ServiceReference.ServiceReference
3 def ServiceReference.ServiceReference.getType(self)
4 ref = sref.toString().split(":")
5 if ref[2] == "2" or ref[2] == "A":
6 from enigma import eSize,ePoint, getDesktop
7 self.instance.move(ePoint(300,0))
8 else:
9 from enigma import eSize,ePoint, getDesktop
10 self.instance.move(ePoint(0,300))
11 applet
Enigma starts without errors, but the code doesn't work. I think "sref" in line 4 get no value from enigma import ServiceReference.ServiceReference.
Is the import correct?
Do i need line 3 def... ???
PS: In original code Line 1+11 starts/ends with </>, because ist a part of skin.xml

**Comment by betacentauri** [comment]
Try this:
ref = session.nav.getCurrentlyPlayingServiceOrGroup()
But you need a session for this.

**Comment by flor62** [comment]
Does in this case "ref" contian "2" or "A", or the whole ServiceReference with should be "split" like line 4 above?

**Comment by betacentauri** [comment]
This only give you the service reference back. You then need to call split and check the result (lines 4,5)
But to be honest I don't know whether this works in the skin.xml

**Comment by 4l3x2k** [comment]
Applet code is commonly applied to the end of a screen and a screen should have a session.

```
...
ref = self.session.nav.getCurrentlyPlayingServiceOrGroup()
isRadio = ref[2] == "2" or ref[2] == "A"
...
```

I also think enigma2 does not expose ServiceReference. Instead it should read eServiceReference. More suitable would be eServiceReferenceDVB and its getServiceType method. But this seems not to be exposed to python and is not necessary with ref as string.

**Comment by 4l3x2k** [comment]
**Test C** is the best so far. You should check whether ref is defined and not None.
```
...
ref = self.session.nav.getCurrentlyPlayingServiceOrGroup()
if ref:
...
```

But I do not know whether the applet code is executed multiple times because the currently playing service or group could be None if the Skin and therefor the applet is being loaded and executed at start.

You could use eServiceReferenceDVB for example like
```
import NavigationInstance
from enigma import eServiceReference, eServiceReferenceDVB

# REFTYPE:FLAGS:STYPE:  SID: TSID: ONID:       NS:PARENT_SID:PARENT_TSID:UNUSED:PATH:NAME
#       1:    0:    2: C4EE: 2721: F001: FFFF0000:         0:          0:     0:    :DVB-C Bremen Next
#       ^           ^
#     idDVB       dRadio
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
	if eservicereference.type == eServiceReference.idDVB: # 1
		eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
		isRadio = eservicereferencedvb.getServiceType()
		if isRadio == eServiceReferenceDVB.dRadio: # 2
			print("playing radio")
		if isRadio == eServiceReferenceDVB.dRadioAvc: # 10 or 0xA
			print("playing radio")
```

You can use `ref.toString().split(":")` and check the positions. It is maybe easier and better to read.

**Comment by flor62** [comment]
@  4l3x2k, sorry but i dont have an ides how to check in Text C whether ref is defined and not None. I only see that there sit no effect by self.instance.move.

I've done some more tests:
Test E
_<applet type="onLayoutFinish">
import NavigationInstance
from enigma import eServiceReference, eServiceReferenceDVB
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
	if eservicereference.type == eServiceReference.idDVB: # 1
		eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
		isRadio = eservicereferencedvb.getServiceType()
		if isRadio == eServiceReferenceDVB.dRadio:        # 2
			from enigma import eSize,ePoint, getDesktop
			self.instance.move(ePoint(300,0))
		if isRadio == eServiceReferenceDVB.dRadioAvc:     # 10 or 0xA
			from enigma import eSize,ePoint, getDesktop
			self.instance.move(ePoint(300,0))
</applet> -->_

Result:
19:12:42.5910 { E } /usr/lib/python2.7/traceback.py:13 _print   File "skin applet", line 2, in <module>
19:12:42.5914 { E } /usr/lib/python2.7/traceback.py:13 _print ImportError: cannot import name eServiceReferenceDVB

Test F ( Import without „from enigma“)
_<applet type="onLayoutFinish">
import NavigationInstance
import eServiceReference, eServiceReferenceDVB
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
	if eservicereference.type == eServiceReference.idDVB: # 1
		eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
		isRadio = eservicereferencedvb.getServiceType()
		if isRadio == eServiceReferenceDVB.dRadio:        # 2
			from enigma import eSize,ePoint, getDesktop
			self.instance.move(ePoint(300,0))
		if isRadio == eServiceReferenceDVB.dRadioAvc:     # 10 or 0xA
			from enigma import eSize,ePoint, getDesktop
			self.instance.move(ePoint(300,0))
</applet> -->_

Result:
13:44:45.4523 { E } /usr/lib/python2.7/traceback.py:13 _print   File "skin applet", line 2, in <module>
13:44:45.4527 { E } /usr/lib/python2.7/traceback.py:13 _print ImportError: No module named eServiceReference

Test G (inspired from sample 12 from https://programtalk.com/python-examples/enigma.eServiceReference/ )

_from ServiceReference import ServiceReference
from Screens.ChannelSelection import service_types_tv, service_types_radio, FLAG_SERVICE_NEW_FOUND
from enigma import eServiceCenter, eServiceReference
def getProviders(stype):
    s_type = service_types_tv
    if s_type == "radio":
	from enigma import eSize,ePoint, getDesktop
	self.instance.move(ePoint(300,0))
   else:
	from enigma import eSize,ePoint, getDesktop
	self.instance.move(ePoint(300,0))_

Result:
System started wihtout errors, but no If-Reaktion

**I think it makes no sence with a „applet“ in skin.html**

I want tell you the goal i want to do.
I the skin i added in „“ this widgets:
	**<widget source="**session.CurrentService**" render="Label" position="200,130" size="1330,55" font="Regular2;42" halign="left" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3">
		<convert type="ServiceName">Name</convert>   
 		</widget>    
	<widget source="**session.Event_Now**" render="Label" position="200,200" size="1600,55" font="Regular2;42" halign="center" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3" >
		<convert type="EventName">Name</convert>  
		</widget>    
	<widget source="**global.CurrentTime**" render="Label" position="1530,130" size="200,55" font="Regular2;42" halign="right" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3" >
		<convert type="XionHDFClockToText">WithSeconds</convert>
		</widget>**

I want so see CurrentService, Event_Now and CurrentTime always on Radio-Screen.
It works, but this widgets are also shown on TV-Chanels
My Solution was to move the screen with the radio-widgets out of screen with „ self.instance.move(ePoint(xxx,xxx))“ when teh service ist no radio.

Perhaps there is another small solution to control the three new widgets so that they are shown only in radio-services … ?
If it’s complicate – no problem – close the topic.

**Comment by flor62** [comment]
@ 4l3x2k, sorry but i dont have an ides how to check in Text C whether ref is defined and not None. I only see that there sit no effect by self.instance.move.

I've done some more tests:
Test E

import NavigationInstance
from enigma import eServiceReference, eServiceReferenceDVB
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
if eservicereference.type == eServiceReference.idDVB: # 1
eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
isRadio = eservicereferencedvb.getServiceType()
if isRadio == eServiceReferenceDVB.dRadio: # 2
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
if isRadio == eServiceReferenceDVB.dRadioAvc: # 10 or 0xA
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
-->

Result:
19:12:42.5910 { E } /usr/lib/python2.7/traceback.py:13 _print File "skin applet", line 2, in
19:12:42.5914 { E } /usr/lib/python2.7/traceback.py:13 _print ImportError: cannot import name eServiceReferenceDVB

Test F ( Import without „from enigma“)

import NavigationInstance
import eServiceReference, eServiceReferenceDVB
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
if eservicereference.type == eServiceReference.idDVB: # 1
eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
isRadio = eservicereferencedvb.getServiceType()
if isRadio == eServiceReferenceDVB.dRadio: # 2
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
if isRadio == eServiceReferenceDVB.dRadioAvc: # 10 or 0xA
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
-->

Result:
13:44:45.4523 { E } /usr/lib/python2.7/traceback.py:13 _print File "skin applet", line 2, in
13:44:45.4527 { E } /usr/lib/python2.7/traceback.py:13 _print ImportError: No module named eServiceReference

Test G (inspired from sample 12 from https://programtalk.com/python-examples/enigma.eServiceReference/ )

from ServiceReference import ServiceReference
from Screens.ChannelSelection import service_types_tv, service_types_radio, FLAG_SERVICE_NEW_FOUND
from enigma import eServiceCenter, eServiceReference
def getProviders(stype):
s_type = service_types_tv
if s_type == "radio":
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
else:
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))

Result:
System started wihtout errors, but no If-Reaktion

I think it makes no sence with a „applet“ in skin.html

I want tell you the goal i want to do.
I the skin i added in „“ this widgets:
	_widget source="session.CurrentService" render="Label" position="200,130" size="1330,55" font="Regular2;42" halign="left" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3"
		convert type="ServiceName">Name</convert
 		/widget>    
	widget source="session.Event_Now" render="Label" position="200,200" size="1600,55" font="Regular2;42" halign="center" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3" 
		convert type="EventName">Name</convert  
		/widget  
	widget source="global.CurrentTime" render="Label" position="1530,130" size="200,55" font="Regular2;42" halign="right" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3" >
		convert type="XionHDFClockToText">WithSeconds</convert
		/widget_
(here without </>)

I want so see CurrentService, Event_Now and CurrentTime always on Radio-Screen.
It works, but this widgets are also shown on TV-Chanels
My Solution was to move the screen with the radio-widgets out of screen with „ self.instance.move(ePoint(xxx,xxx))“ when teh service ist no radio.

Perhaps there is another small solution to control the three new widgets so that they are shown only in radio-services … ?
If it’s complicate – no problem – close the topic.

**Comment by flor62** [comment]
@ 4l3x2k, sorry but i dont have an ides how to check in Text C whether ref is defined and not None. I only see that there sit no effect by self.instance.move.

I've done some more tests:
Test E

import NavigationInstance
from enigma import eServiceReference, eServiceReferenceDVB
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
if eservicereference.type == eServiceReference.idDVB: # 1
eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
isRadio = eservicereferencedvb.getServiceType()
if isRadio == eServiceReferenceDVB.dRadio: # 2
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
if isRadio == eServiceReferenceDVB.dRadioAvc: # 10 or 0xA
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
-->

Result:
19:12:42.5910 { E } /usr/lib/python2.7/traceback.py:13 _print File "skin applet", line 2, in
19:12:42.5914 { E } /usr/lib/python2.7/traceback.py:13 _print ImportError: cannot import name eServiceReferenceDVB

Test F ( Import without „from enigma“)

import NavigationInstance
import eServiceReference, eServiceReferenceDVB
eservicereference = NavigationInstance.instance.getCurrentlyPlayingServiceReference()
if eservicereference:
if eservicereference.type == eServiceReference.idDVB: # 1
eservicereferencedvb = eServiceReferenceDVB(eservicereference.toString())
isRadio = eservicereferencedvb.getServiceType()
if isRadio == eServiceReferenceDVB.dRadio: # 2
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
if isRadio == eServiceReferenceDVB.dRadioAvc: # 10 or 0xA
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
-->

Result:
13:44:45.4523 { E } /usr/lib/python2.7/traceback.py:13 _print File "skin applet", line 2, in
13:44:45.4527 { E } /usr/lib/python2.7/traceback.py:13 _print ImportError: No module named eServiceReference

Test G (inspired from sample 12 from https://programtalk.com/python-examples/enigma.eServiceReference/ )

from ServiceReference import ServiceReference
from Screens.ChannelSelection import service_types_tv, service_types_radio, FLAG_SERVICE_NEW_FOUND
from enigma import eServiceCenter, eServiceReference
def getProviders(stype):
s_type = service_types_tv
if s_type == "radio":
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))
else:
from enigma import eSize,ePoint, getDesktop
self.instance.move(ePoint(300,0))

Result:
System started wihtout errors, but no If-Reaktion

I think it makes no sence with a „applet“ in skin.html

I want tell you the goal i want to do.
I the skin i added in Screen „RdsInfoDisplay“ this widgets:
widget source="session.CurrentService" render="Label" position="200,130" size="1330,55" font="Regular2;42" halign="left" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3"
convert type="ServiceName">Name</convert
/widget
widget source="session.Event_Now" render="Label" position="200,200" size="1600,55" font="Regular2;42" halign="center" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3"
convert type="EventName">Name</convert
/widget
widget source="global.CurrentTime" render="Label" position="1530,130" size="200,55" font="Regular2;42" halign="right" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3" >
convert type="XionHDFClockToText">WithSeconds</convert
/widget
(here without </>)

I want so see CurrentService, Event_Now and CurrentTime always on Radio-Screen.
It works, but this widgets are also shown on TV-Chanels
My Solution was to move the screen with the radio-widgets out of screen with „ self.instance.move(ePoint(xxx,xxx))“ when teh service ist no radio.

Perhaps there is another small solution to control the three new widgets so that they are shown only in radio-services … ?
If it’s complicate – no problem – close the topic.

**Comment by 4l3x2k** [comment]
I already came up with a small snipped that show how to check whether ref is None or not [here](https://github.com/openatv/enigma2/issues/1995#issuecomment-896165739).

For **Test E**, which version of openatv do you use?

I think **Test F** won't work. You could try import enigma.eServiceReference but I this is also not going to work.

**Test G** I think these service_type_tv, service_type_radio come from OpenWebIf Plugin. You could try to add simple print() statements and enable debug log to see if your code is reached and flows like you would expect it.

Name your widgets. Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method. Add a new method that call .show() on you widgets and append it to onLayoutFinished.

To use applet code you could try
```
def __onClose():
    self["<YOUR_WIDGETS_CURRENT_SERVICE_NAME>"].hide()
    self["<YOUR_WIDGETS_EVENT_NOW_NAME>"].hide()
    self["<YOUR_WIDGETS_CURRENT_TIME_NAME>"].hide()
self.onClose.append(__onClose)
```

**Comment by flor62** [comment]
Your suggestion sounds very good: 
Name your widgets. Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method. Add a new method that call .show() on you widgets and append it to onLayoutFinished.

"Name your widgets" i did so (e.g.):
`<widget name="myService" source="session.CurrentService" render="Label" position="200,130" size="1330,55" font="Regular2;42" halign="left" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3">
		<convert type="ServiceName">Name</convert>   
 		</widget> `

"Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method" i did so:
`	def __init__(self, session):
		Screen.__init__(self, session)

		self.__event_tracker = ServiceEventTracker(screen=self, eventmap=
			{
				iPlayableService.evEnd: self.__serviceStopped,
				iPlayableService.evUpdatedRadioText: self.RadioTextChanged,
				iPlayableService.evUpdatedRtpText: self.RtpTextChanged,
				iPlayableService.evUpdatedRassInteractivePicMask: self.RassInteractivePicMaskChanged,
			})

		self["RadioText"] = Label()
		self["RtpText"] = Label()
		self["RassLogo"] = Pixmap()
		**self["myService"] = Label()
		self["myEvent"] = Label()
		self["myTime"] = Label()**

		self.onLayoutFinish.append(self.hideWidgets)
		self.rassInteractivePossible=False
		self.onRassInteractivePossibilityChanged = [ ]
		self.onText = [ ]

	def createSummary(self):
		return RdsInfoDisplaySummary

	def hideWidgets(self):
		for x in (self["RadioText"],self["RtpText"],self["RassLogo"],**self["myService"],self["myEvent"],self["myTime"]**):
			x.hide()
		for x in self.onText:
			x('')`

With this adds the system started, but doesn't show one of the new widget (Not on TV, not on Radio).

"Add a new method that call .show() on you widgets" - I've no idea. I searched a sample for "call" one of the original widget (name="RtpText") but i didn't find some code like this to copy add it for my widgets...

skin.html with
`def __onClose():
    self["<YOUR_WIDGETS_CURRENT_SERVICE_NAME>"].hide()
    self["<YOUR_WIDGETS_EVENT_NOW_NAME>"].hide()
    self["<YOUR_WIDGETS_CURRENT_TIME_NAME>"].hide()
self.onClose.append(__onClose)`
System started with default-skin not with modified skin , Log-file says:
16:54:24.4422 { E } /usr/lib/python2.7/traceback.py:13 _print   File "/usr/lib/enigma2/python/Screens/RdsDisplay.py", line 51, in hideWidgets
16:54:24.4423 { E } /usr/lib/python2.7/traceback.py:13 _print KeyError: 'myService'
It's strange, but without def__onClode() the system started with modified skin.

**Comment by flor62** [comment]
Your suggestion sounds very good:
Name your widgets. Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method. Add a new method that call .show() on you widgets and append it to onLayoutFinished.

"Name your widgets" i did so (e.g.):
<widget name="myService" source="session.CurrentService" render="Label" position="200,130" size="1330,55" font="Regular2;42" halign="left" backgroundColor="rds_text_bg" foregroundColor="brown" transparent="1" valign="center" noWrap="1" shadowColor="transpBlack" shadowOffset="-3,-3"> <convert type="ServiceName">Name</convert> </widget>

"Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method" i did so:
`def init(self, session):
Screen.init(self, session)

	self.__event_tracker = ServiceEventTracker(screen=self, eventmap=
		{
			iPlayableService.evEnd: self.__serviceStopped,
			iPlayableService.evUpdatedRadioText: self.RadioTextChanged,
			iPlayableService.evUpdatedRtpText: self.RtpTextChanged,
			iPlayableService.evUpdatedRassInteractivePicMask: self.RassInteractivePicMaskChanged,
		})

	self["RadioText"] = Label()
	self["RtpText"] = Label()
	self["RassLogo"] = Pixmap()
	self["myService"] = Label()
	self["myEvent"] = Label()
	self["myTime"] = Label()

	self.onLayoutFinish.append(self.hideWidgets)
	self.rassInteractivePossible=False
	self.onRassInteractivePossibilityChanged = [ ]
	self.onText = [ ]

def createSummary(self):
	return RdsInfoDisplaySummary

def hideWidgets(self):
	for x in (self["RadioText"],self["RtpText"],self["RassLogo"],self["myService"],self["myEvent"],self["myTime"]):
		x.hide()
	for x in self.onText:
		x('')`

With this adds the system started, but doesn't show one of the new widget (Not on TV, not on Radio).

"Add a new method that call .show() on you widgets" - I've no idea. I searched a sample for "call" one of the original widget (name="RtpText") but i didn't find some code like this to copy add it for my widgets...

skin.html with
`def __onClose(): 
self["<YOUR_WIDGETS_CURRENT_SERVICE_NAME>"].hide() 
self["<YOUR_WIDGETS_EVENT_NOW_NAME>"].hide() 
self["<YOUR_WIDGETS_CURRENT_TIME_NAME>"].hide() 
self.onClose.append(__onClose)`
System started with default-skin, not with modified skin, Log-file says:
16:54:24.4422 { E } /usr/lib/python2.7/traceback.py:13 _print File "/usr/lib/enigma2/python/Screens/RdsDisplay.py", line 51, in hideWidgets
16:54:24.4423 { E } /usr/lib/python2.7/traceback.py:13 _print KeyError: 'myService'
It's strange, because without "def__onClose()..." the system started with the modified skin.

**Comment by flor62** [comment]
Your suggestion sounds very good:
"Name your widgets. Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method. Add a new method that call .show() on you widgets and append it to onLayoutFinished."

"Name your widgets" i did so (e.g.):

> _widget name="myService" source="session.CurrentService" ..._

"Add these names to Screens/RdsDisplay.py, RdsInfoDisplay's hideWidgets method" i did so:

> def init(self, session):
> Screen.init(self, session)
> 
> self.__event_tracker = ServiceEventTracker(screen=self, eventmap=
> 	{
> 		iPlayableService.evEnd: self.__serviceStopped,
> 		iPlayableService.evUpdatedRadioText: self.RadioTextChanged,
> 		iPlayableService.evUpdatedRtpText: self.RtpTextChanged,
> 		iPlayableService.evUpdatedRassInteractivePicMask: self.RassInteractivePicMaskChanged,
> 	})
> 
> self["RadioText"] = Label()
> self["RtpText"] = Label()
> self["RassLogo"] = Pixmap()
> self["myService"] = Label()
> self["myEvent"] = Label()
> self["myTime"] = Label()
> 
> self.onLayoutFinish.append(self.hideWidgets)
> self.rassInteractivePossible=False
> self.onRassInteractivePossibilityChanged = [ ]
> self.onText = [ ]
> 
> def createSummary(self):
> return RdsInfoDisplaySummary
> 
> def hideWidgets(self):
> for x in (self["RadioText"],self["RtpText"],self["RassLogo"],self["myService"],self["myEvent"],self["myTime"]):
> x.hide()
> for x in self.onText:
> x('')

With this adds the system started, but doesn't show one of the new widget (Not on TV, not on Radio).

"Add a new method that call .show() on you widgets" - I've no idea. I searched a sample for "call" one of the original widget (name="RtpText") but i didn't find some code like this to copy add it for my widgets...

tried skin.html with

> def __onClose(): 
>     self["<YOUR_WIDGETS_CURRENT_SERVICE_NAME>"].hide() 
>     self["<YOUR_WIDGETS_EVENT_NOW_NAME>"].hide() 
>     self["<YOUR_WIDGETS_CURRENT_TIME_NAME>"].hide() 
> self.onClose.append(__onClose)

System started with default-skin, not with modified skin, Log-file says:
16:54:24.4422 { E } /usr/lib/python2.7/traceback.py:13 _print File "/usr/lib/enigma2/python/Screens/RdsDisplay.py", line 51, in hideWidgets
16:54:24.4423 { E } /usr/lib/python2.7/traceback.py:13 _print KeyError: 'myService'
It's strange, because without "def__onClose()..." the system started with the modified skin.

**Comment by flor62** [comment]
last was nonsense - i didn't add the correct widget-names ... :-(

**Comment by flor62** [comment]
tried skin.html with

> def __onClose():
>     self["myService"].hide()
>     self["myEvent"].hide()
>     self["myTime"].hide()
> self.onClose.append(__onClose)

System started, modified skin started, but my widget are not shown.

**Comment by 4l3x2k** [comment]
I do not know how to hide or disable these widgets.

Sorry for that. I hope you'll get it somehow.

**Comment by jbleyel** [comment]
Can we close this?

**Comment by 4l3x2k** [comment]
I think it can be closed with no solution.

This kind of question should be asked in a forum.
