### ISSUE TITLE
[lang/l10n] Start wizard missing EN-GB option & No text beside Israeli flag

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2033]
Newly flashed  image openatv-7.0-mutant51-20210816

openatv-7.0-mutant51-20210807 _did_ have EN-GB, I didn't notice the Israeli flag.

**Comment by 4l3x2k** [comment]
Isn't it fixed already with 20210818 and later?

**Comment by IanSav** [comment]
GB and IL flags should be available.

If you have any residual issues please report details to allow replication of the problem.

**Comment by wedebe** [comment]
Oh, latest image for my box is 20210816 so I'll test the next release.

**Comment by 4l3x2k** [comment]
@wedebe 

Please test again with 20210826 image and report back so we can close this issue.

**Comment by wedebe** [comment]
I can confirm both issues are resolved in image dated openatv-7.0-mutant51-20210831, closing :)
