### ISSUE TITLE
Automatic gain control frontend is not working

### ISSUE THREAD

**Issue by Loayelshall** [openatv/enigma2#2038]
Automatic gain control bar in frontend is showing no data

**Comment by atvcaptain** [comment]
this is depend from your hardware you have, you have not write any infos from yur model and tuner type you use

**Comment by Loayelshall** [comment]
![image](https://user-images.githubusercontent.com/11968453/131352439-efc9b83f-96ce-443c-a6aa-10e2ba6f02eb.png)

**Comment by atvcaptain** [comment]
Tuner-Treiber kommen vom Hardware-Hersteller, wir können nichts ändern, der Hersteller existiert nicht mehr, wir schließen hier.
