### ISSUE TITLE
Can you revert self["virtualKeyBoardActions"] back to self["VirtualKB"]

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#2047]
Can you revert self["virtualKeyBoardActions"] back to self["VirtualKB"] in ConfigList.py

every other image uses 

`self["VirtualKB"] = HelpableActionMap(self, "VirtualKeyboardActions", {
			"showVirtualKeyboard": (self.keyText, _("Display the virtual keyboard for data entry"))
		}, prio=1, description=_("Common Setup Actions"))
self["VirtualKB"].setEnabled(False)`

If a plugin is using there own settings page with virtual keyboard functionality then your new virtual keyboard variables dont work, every single plugin that references the old value will now crash unless the author writes in some conditionals to pick up this name change.
 
 self['VirtualKB'].setEnabled(True)

**Comment by jbleyel** [comment]
Hi @IanSav , please check this.

**Comment by jbleyel** [comment]
Hi @kiddac , please provide more info.
Where do you use "VirtualKB" and how?

**Comment by IanSav** [comment]
We checked all the source code and didn't find any issues.  As @jbleyel requested, please list / show us all the issues.

**Comment by jbleyel** [comment]
fixed with : https://github.com/openatv/enigma2/commit/5240ec2d468b24e4da686a11adf4a972aefbfdbe
