### ISSUE TITLE
4097 vor Kanalreferenz in Bouquet-Liste zeigt kein EPG

### ISSUE THREAD

**Issue by LevelOne2k** [openatv/enigma2#2059]
Hallo!

Mir ist aufgefallen, dass wenn man in der Boquet-Liste einen Eintrag am Anfang in der Kanalrefenz mit 4097 hat als z.B

`#SERVICE 4097:0:1:1:0:0:0:0:0:0:http%3A//XXX%3A8002/1%3A0%3A1%3A6DCA%3A44D%3A1%3AC00000%3A0%3A0%3A0%3A:BlaBla
#DESCRIPTION BlaBla `

Auch wenn man die echte Kanalreferenz des jeweiligen Senders nimmt, geht es nicht also Z.b.

`#SERVICE 4097:0:1:6DCA:44D:1:C00000:0:0:0:http%3A//XXX%3A8002/1%3A0%3A1%3A6DCA%3A44D%3A1%3AC00000%3A0%3A0%3A0%3A:BlaBla
#DESCRIPTION BlaBla `

das man dann kein EPG und keine Sendungsinfos hat.

**Comment by MrServo** [comment]
Der Service 4097 ist ein Zeichen für einen Internetstream und dort gibt es naturgemäß keine EGP-Informationen weil es EPG bei Internetstreams naturgemäß nicht gibt (ist ja ein DVB-Thema). Wenn aber der Streameinspeiser lieb ist, dann schickt er begleitende Streaminfos mit (bei InternetRadio dann Interpret - Album - Songtitel), aber das dann nicht in einem "EPG-Format" sondern als MPEG- oder ACC-Info. Das muß dann separat & anders ausgelesen/ausgewertet werden...
openATV (skin MetrixHD) wurde vor ca. 4 Wochen erweitert, so daß inzwischen StreamInfos in der OSD-Ausgabe erscheinen, dort wo normalerweise "current Event / next Event" angezeigt werden.

**Comment by jbleyel** [comment]
Hi Mr.Servo, EPG gibt es natürlich auch für IPTV. Entweder über Mapping und EPG Importer über Inet. Oder über Sat/Kabel wenn die Box über die sRef die EPG Daten holen kann.

Wenn du dann eine IPTV sRef hast wo die Box EPG Daten hat, dann geht das. 

Wenn du jetzt nur die 1 durch 4097 ersetzt, dann geht zwar das Picon aber EPG geht nicht.

Man könnte auch die 1 vorne lassen, aber dann funktioniert evtl. der Stream nicht richtig. 

5003 geht aber definitiv nicht und das braucht man manchmal, wenn der gst spinnt.

**Comment by 4l3x2k** [comment]
Ich kann das Problem nicht nachstellen.

Ich vermute dir wird keine EPG bei den 4097er Einträgen angezeigt, weil du den originalen Sender länger nicht mehr eingeschaltet hattest. Die EPG Daten kommen nur über den originalen Sender (DVB-S, DVB-C, DVB-T) auf die Box und nicht über den Internet-Stream.
Wird dir also beim DVB Sender keine EPG angezeigt, dann wirst du bei dem Stream auch keine EPG sehen.

Mit folgenden Einträgen funktioniert die EPG im Kabelnetz.
```
#SERVICE 4097:0:1:6DCA:44D:1:FFFF0000:0:0:0:http%3a//mcdn.daserste.de/daserste/de/master.m3u8:Das Erste
#SERVICE 4097:0:1:6D66:437:1:FFFF0000:0:0:0:http%3a//zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8:ZDF
```

Damit du den Sender nicht immer manuell einschalten musst kannst du das EPG Refresh Plugin verwenden.

Hast du für einen Stream keine DVB Quelle, dann bleibt nur der EPG Importer.

Issue kann geschlossen werden.
