### ISSUE TITLE
OPENATV 6.5 - Tone Burst.

### ISSUE THREAD

**Issue by miazza99** [openatv/enigma2#2085]
I really do not know it it is an OpenATV issue or if it is the Enigma 2 baseline driver;
The point is that in no way I can switch my Tone Burst Switch.

The Switch works OK if commanded from another Decoder (not Enigma).

I tried all the differen combination of DiseqC commands but the Tone Burst is not working (at least on my old switch that is a simple Mini-DiseqC Tone Burst at two positions)

May be someone have xperienced the same or am I alone in this ?

**Comment by jogibaer1948** [comment]
6.5 are end of live,try 7.* And report.

**Comment by miazza99** [comment]
At the end I changed the switch with a uncommited one.
This is OK.
BTW, with 7.1 same issue with Tone Burst Switch.

**Comment by atvcaptain** [comment]
tone burst comes from the tuner driver, which comes from the manufacturer of the device, since you have not provided any device information, we cannot ask any manufacturer what device it is ?

**Comment by miazza99** [comment]
I do not remember ... after 3 years I do not know if I still have it :)
Anyhow I substituted it with ab uncommitted switch and this works great.

**Comment by jbleyel** [comment]
Can we close this or do we need to do something?

**Comment by miazza99** [comment]
Yes, for me we can close. I solved with a committed switch and no way to have the previous Tone Burst working. I'm not investigating the issue anymore.

**Comment by miazza99** [comment]
Closed
