### ISSUE TITLE
Initialisation Wizard gets stuck on Refresh rate choice

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2090]
The ui disappears/boot logo appears after selecting resolution. Attempting to change Refresh Rate then causes a problem (leaving it at default does not), with the only solution being to unplug the box, after which the box restarts at the HDMI/Jack selection screen. This is regardless of language at the default of DE or changed to EN_GB.

Happened 5 times after upgrading from 20210923 to 20210924
(no log saved)

**Comment by jbleyel** [comment]
This looks like a hardware or driver issue because the wizard was not changed from 20210923 to 20210924

**Comment by hd75hd** [comment]
with a openatv 7.0 from 26.09. on my OSmio+ 4K, i cant reproduce it

**Comment by jbleyel** [comment]
Hi @wedebe , can you please check this again.

**Comment by wedebe** [comment]
Confirmed no longer an issue, closing.
