### ISSUE TITLE
Zgemma H9S usb 3.0 working only in 2.0

### ISSUE THREAD

**Issue by elnoelsi** [openatv/enigma2#2095]
Some people have already mentioned this but they seem to be ignored. Its a serious problem, needs to be fixed. 

It was working fine up to 6.2, right before 6.3 it stopped working as 3.0 port and only detects 2.0 devices.

Thanks

**Comment by jogibaer1948** [comment]
Is this problem aktuell?

**Comment by elnoelsi** [comment]
yes it is, never been fixed

**Comment by atvcaptain** [comment]
i have disable usb 3.0 uas mode, check next image update 7.2 only you must flash all new
