### ISSUE TITLE
Feature Request: Make streaming port configurable

### ISSUE THREAD

**Issue by resadent** [openatv/enigma2#2111]
Hi. Today I was trying to change my enigma2 box streaming port from the default 8001 to any other because I have two boxes and I want to access them from the internet and also from my local network. Anyway, I just found no way to do this apart from changing the file `lib/dvb/streamserver.cpp` and then compiling openatv by myself which is quite a hassle because it takes a ton of storage and cpu cycles.

So I thought perhaps someone could try and make this port configurable in the gui (or even using cli). Would make me and perhaps other very happy. Thank you for your time to read this.

**Comment by resadent** [comment]
Yes I can do that, however if I did that I would no longer be able to just play the stream via local network without modifying the m3u file.

**Comment by wedebe** [comment]
@jbleyel, wasn't there another issue posted related to this quite a while ago? If that's the case, I believe there was a hardcoded port number involved (somewhere).

**Comment by resadent** [comment]
@wedebe yes I think you're referring to the file I pointed in my first message. Default port number is hardcoded in that file I believe.

**Comment by Papi2000-new** [comment]
I just changed the streaming port of my ZGemma from 08001 to 28001 in the openWeb Config with the remote control, and saved. The generated *.m3u8 content changed from initial

#EXTM3U 
#EXTVLCOPT:http-reconnect=true 
#EXTINF:-1,zdf_neo HD
http://zgemmah9twin:08001/1:0:19:2B7A:3F3:1:C00000:0:0:0:

to 

#EXTM3U 
#EXTVLCOPT:http-reconnect=true 
#EXTINF:-1,zdf_neo HD
http://zgemmah9twin:28001/1:0:19:2B7A:3F3:1:C00000:0:0:0:

without restarting box or GUI immediately.
Perhaps i do not understand your request.

**Comment by jbleyel** [comment]
The m3u is correct. But the port 28001 only works from outside and not in-house.

**Comment by resadent** [comment]
Yes having openwebif detect wether its accesed via lan or not and changing the port of the file based on that would solve the problem.

**Comment by jbleyel** [comment]
Sorry for the delay.
The enigma streaming port of 8001 cannot be changed easily.
What you need is a different port in the m3u file.
Maybe by an extra setting in OWF.

**Comment by jbleyel** [comment]
I will close this and try to find a solution for OWI.
