### ISSUE TITLE
Problem with transparency on svg radius corners when alphatest is set to off

### ISSUE THREAD

**Issue by ziko-ZR1** [openatv/enigma2#2126]
Hello, 
as the title said when i use svg's with rounded corners with a background i can see the transparency around the edges i know i could use alphatest blend to fix this but it slows down the process to blit the pixmap 

![1_0_19_2B8E_3F2_1_C00000_0_0_0_20211126115151](https://user-images.githubusercontent.com/43075184/143569671-1d72f54c-de17-457a-826f-d1d0ec6e251d.jpg)

![Screenshot from 2021-11-26 11-52-13](https://user-images.githubusercontent.com/43075184/143569746-e0aa8565-868b-40d3-a7d9-696c385d8c86.png)

with no background everything looks just fine

![1_0_19_2B8E_3F2_1_C00000_0_0_0_20211126115533](https://user-images.githubusercontent.com/43075184/143570208-da126587-60c2-43ee-a660-b9420dec8c45.jpg)

![Screenshot from 2021-11-26 11-56-16](https://user-images.githubusercontent.com/43075184/143570248-15c69e12-a3be-4225-a425-4af3261e5294.png)

i hope this can be fixed without the need to set alpha blend

**Comment by jbleyel** [comment]
We plan to remove the svg support because the rendering is CPU and not GPU and the nano svg lib has not all needed features.
