### ISSUE TITLE
Why disabled changed() in ConfigElement setValue?

### ISSUE THREAD

**Issue by Taapat** [openatv/enigma2#2127]
@jbleyel why are you disabled disabled changed() in ConfigElement setValue?
https://github.com/openatv/enigma2/blob/7.0/lib/python/Components/config.py#L213

For example, I use the ConfigYesNo entry in the config list for which I use a notifier.
If I, on open config screen in python code change this value then the notifier does not work because changed() is not executed and the config screen does not change as it was before.

**Comment by jbleyel** [comment]
Please get the latest version and check.

**Comment by jbleyel** [comment]
This needs some refactor.

**Comment by Taapat** [comment]
Refactor in config code or workaround in my code?

**Comment by Taapat** [comment]
Thanx, fixed in: https://github.com/openatv/enigma2/commit/7f5be880fedda9accf8af84dd50b79fae9335f31
