### ISSUE TITLE
[InfoBarGenerics] subservices: add service name

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#2128]
Hello, 

Could you please add this fix to oatv enigma2 repository:
https://github.com/OpenViX/enigma2/commit/0059fd86de76868d41432233222a84de83a0faff

This update fix the missing channel name when using the goupedservices functionality.

Thanks

**Comment by jbleyel** [comment]
No .. because we need to fix the subservice in ATV. There is a bug.

**Comment by jeepcook** [comment]
OK, is this a project ? Is there already an opened issue ? Thanks

**Comment by jbleyel** [comment]
i will check this
