### ISSUE TITLE
Recording Settings in openatv 7.0

### ISSUE THREAD

**Issue by luka838** [openatv/enigma2#2129]
I installed openatv 7.0 on OMB everything works ok but in Recording Settings you can't descend (go up or down) through the menu
and there warning at end of menu that said ''media/hdd/ is not allowed''
and of course Recording Settings via Quick Launch Menu is complete empty
recoding menu in openat 6.4 with same OMB everything ok
same problem happened to me with openbh 4.4 and openvix 5.4 and never found fix for it which made me leave them.
please can you find fix 
![openatv7 0](https://user-images.githubusercontent.com/70975338/144029471-fc30d1f0-c490-4109-a782-7c11911b7031.jpg)

**Comment by jbleyel** [comment]
We need more info.
What ist /media/hdd exactly on your box?

**Comment by luka838** [comment]
thank you for your reply 
it's USB 8GB that I mounted. problem ''media/hdd/ is not allowed'' don't show up on openatv 6.4 only 7.0
on flash first I try openbh 5.0 
and then I try openatv 7.0 and openatv 6.4 after that.

**Comment by IanSav** [comment]
I suspect the issue is that the USB device is not mounted as /media/hdd/ and  as such /dev/hdd/ is still on the root (Flash) file system.  Recordings are not permitted to be saved on the root file system.

Can you please check where the USB device has been mounted and use that path as your recording device.  From memory USB devices get mounted as /media/usb/.

**Comment by luka838** [comment]
ok but why everything ok on openatv 6.4 on same USB
P.S: also notice that in mount manager for external (OMB) openatv 7.0 and 6.4 images is mounted as media/sda1/
_USB: USB Flash Disk Size: 8GB / dev/sda1                  media/sda1/_

but in flash the USB is mounted as media/hdd/

**Comment by IanSav** [comment]
Is this still an issue?

The error message in your original message should only appear if the recordings are being directed to the root flash device.

**Comment by jbleyel** [comment]
No answer.
