### ISSUE TITLE
7.0 Bug: Setting autotimer from EPG causes crash

### ISSUE THREAD

**Issue by TurtleRecall** [openatv/enigma2#2134]
On OpenATV 7.0 03/12/2021 build, when setting an autotimer from the EPG by pressing the red button with programme highlighted, this causes a crash (log attached).  Setting a normal timer works. 

I've noticed this on the beta nightlies for the last week or so but couldn't say for definite when it first started.  Hardware is a zGemma H9 Twin.

Let me know if you need any further info.

[enigma2_crash_1638639259.log](https://github.com/openatv/enigma2/files/7654500/enigma2_crash_1638639259.log)

**Comment by jbleyel** [comment]
Fixed -> 
https://github.com/oe-alliance/enigma2-plugins/commit/4c7ea65964c876d86fa8859f12c7b521e1de80ac
