### ISSUE TITLE
YouTube crashing OpenATV7.0 on DM7080HD

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2137]
I am having problems with the YouTube app (git897+21cbaf1-r0) on OpenATV 7.0 (version 11 December 2021).  Here is the crashlog, can anyone help please ?

openATV Enigma2 crash log

crashdate=Mon Dec 13 16:17:09 2021
compiledate=Dec 11 2021
skin=MetrixHD/skin.xml
sourcedate=2021-12-11
branch=7.0
rev=2.8.0-23642-gbf79da3
component=Enigma2

stbmodel=ultimo
stbmodel=dm7080
kernelcmdline=bmem=512M@512M memc1=768M console=ttyS0,1000000 root=/dev/mmcblk0p1 rootwait rootfstype=ext4
nimsockets=NIM Socket 0:
imageversion=box_type=dm7080
imageissue=Welcome to openATV for %h

16:12:57.9396 [Enigma] Python path is '/usr/lib/enigma2/python'.
16:12:57.9400 [Enigma] DVB API version 5, DVB API version minor 11.
16:12:57.9401 [Enigma] Enigma debug level 3.
16:13:24.3108 [eDVBPESReader] Created. Opening demux
16:13:24.3111 [eDVBPESReader] Created. Opening demux
16:16:58.0304 Traceback (most recent call last):
16:16:58.0306   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 252, in action
16:16:58.0327     response = self.actions[action](int(action))
16:16:58.0329   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 403, in keyNumberGlobal
16:16:58.0348     self["config"].handleKey(ACTIONKEY_0 + number, self.entryChanged)
16:16:58.0350   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 47, in handleKey
16:16:58.0359     changed = selection[1].handleKey(key, callback)
16:16:58.0362 TypeError: handleKey() takes 2 positional arguments but 3 were given
16:16:58.0363 [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0x6a4f5f70>>,('NumberActions', '0')) failed)
16:17:08.0636 Traceback (most recent call last):
16:17:08.0638   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 252, in action
16:17:08.0670     response = self.actions[action](int(action))
16:17:08.0671   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 403, in keyNumberGlobal
16:17:08.0698     self["config"].handleKey(ACTIONKEY_0 + number, self.entryChanged)
16:17:08.0700   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 47, in handleKey
16:17:08.0719     changed = selection[1].handleKey(key, callback)
16:17:08.0721 TypeError: handleKey() takes 2 positional arguments but 3 were given
16:17:08.0722 [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0x6a4f5f70>>,('NumberActions', '8')) failed)
16:17:09.0747 Traceback (most recent call last):
16:17:09.0748   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 252, in action
16:17:09.0770     response = self.actions[action](int(action))
16:17:09.0775   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 403, in keyNumberGlobal
16:17:09.0809     self["config"].handleKey(ACTIONKEY_0 + number, self.entryChanged)
16:17:09.0811   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 47, in handleKey
16:17:09.0833     changed = selection[1].handleKey(key, callback)
16:17:09.0836 TypeError: handleKey() takes 2 positional arguments but 3 were given
16:17:09.0837 [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0x6a4f5f70>>,('NumberActions', '8')) failed)

dmesg

Thank you

**Comment by jbleyel** [comment]
Where is the source of the YouTube app?

**Comment by willow5** [comment]
Hi, its in the plugin feed (green button)

**Comment by jbleyel** [comment]
Please open a new issue here -> https://github.com/Taapat/enigma2-plugin-youtube
