### ISSUE TITLE
Problem with '5' key on alphanumeric keyboard

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2138]
I have a DM7080 running ATV 7.0.20211214 and there is a problem with the '5' key on the keyboard.  I can never seem to select anything past the letter j.  Sometimes I get a k but mostly it is a j.  I tried different Apps like YouTube, MyMetrixLite and the problem is there in both of these apps so it seems like there is a problem with ATV 7.0 on DM7080.

**Comment by willow5** [comment]
Please can someone kindly reply or acknowledge this issue.

**Comment by 4l3x2k** [comment]
Do you mean a real keyboard or remote control?

Does the problem persist with latest ATV 7.0?

**Comment by willow5** [comment]
Hi, I mean using the remote control and this screen:

![1_0_1_2077_808_2_11A0000_0_0_0_20220105160851](https://user-images.githubusercontent.com/64496221/148250063-3cb579a5-a6b3-4b3d-aed5-01b7dfe9d9c0.jpg)

**Comment by 4l3x2k** [comment]
It is working here with key 5.

![image](https://user-images.githubusercontent.com/25264/148254698-edb68661-a607-4655-bab5-4dd4d8c516b3.png)

**Comment by atvcaptain** [comment]
possible language problem, we need more infos from your current settings

**Comment by willow5** [comment]
That's really strange, at best I can select 'j' but rarely do I get past 'j' especially if I am trying quickly. Do you have a DM7080 you can try?

**Comment by 4l3x2k** [comment]
Which locale is active?

Which keymap are you using?

Which keyboard keymap are you using (Menu - Setup - Usage & User Interface - Extended User Interface - Keyboard)?

Which repeat and delay settings (Menu - Setup - Usage & User Interface - Extended User Interface - Input Devices)?

**Comment by willow5** [comment]
Hi, here are the screenshots. I am using the old Dreambox Remote (learning)
![1_0_19_1B28_802_2_11A0000_0_0_0_20220105174343](https://user-images.githubusercontent.com/64496221/148264048-991975d2-dd24-4906-8379-4ae6c12b2294.jpg)
![1_0_19_1B28_802_2_11A0000_0_0_0_20220105174411](https://user-images.githubusercontent.com/64496221/148264073-fd2ecad8-bed2-4670-8f05-abc19df1b1be.jpg)
![1_0_19_1B28_802_2_11A0000_0_0_0_20220105174305](https://user-images.githubusercontent.com/64496221/148264108-94d91806-0e50-40d2-97be-427fe2c81264.jpg)

**Comment by 4l3x2k** [comment]
So you're using [this](https://github.com/oe-alliance/remotes/blob/master/png/dmm2.png) remote control.

You didn't answer
- Which keymap are you using?

Menu - Info Panel - Keymap Selection.

Do you need the "5" on you remote control often for example parental control pin? Maybe your key on the remote control is defect.

**Comment by willow5** [comment]
Hi, no I am using this remote: https://github.com/oe-alliance/remotes/blob/master/png/dmm1.png

Keymap is default (keymap.xml)

I can see the light coming on every time I press the 5 button so it is clearly trying to send the IR command but the receiver is ignoring it.

**Comment by 4l3x2k** [comment]
So there is no lag on choosing channel via pressing three times "5"?

**Comment by willow5** [comment]
Actually you are right, there is a lag pressing 5 three times

**Comment by 4l3x2k** [comment]
Moving your box or ir receiver a bit doesn't help?

If it does not, there seem no problem with your remote control but with your ir receiver.

Sorry.
Tried to follow all your descriptions to reproduce the lag. But here it is sf8008. So this might be box and specialized remote receiver related.

**Comment by willow5** [comment]
I have tried it standing right next to the receiver but still not working. Thanks for your help. Where can I now take this issue?

**Comment by jbleyel** [comment]
1.) try new battery -> if this fail then 2.
2.) test the key 5 via openwebif -> if this works then 3.
3.) Install ATV 6.4 or any other image and test the key 5 of the ir remote -> if the also fail then think about to get a new ir remote

**Comment by willow5** [comment]
Good suggestion about the webif. This works fine. I will try another remote too

**Comment by jbleyel** [comment]
Please try also an original dreamOS image.

**Comment by willow5** [comment]
Hi, not so far sorry I didn't get time.  I will try later in the week and report back.

**Comment by jbleyel** [comment]
Any News?

**Comment by jbleyel** [comment]
Now answer.
