### ISSUE TITLE
OpenATV all versions - Arabic Subtitles Problem

### ISSUE THREAD

**Issue by Kerberos1864** [openatv/enigma2#2145]
Greetings all,

I am having a problem from the first time I started to use Enigma2 receivers. But now I got time to do something about it.
The problem is that OpenATV/OpenPLI with all its versions is unable to play External Arabic Subtitles correctly 100%.
I changed thousands of skins, and tried hundreds of font types for replacement ( Arial, TimesnewRoman, Custom fonts for arabic language) but still the same.
Most Arabic words letters are seperated instead they should be 1 word. Like the first word. The letter which has an arabic symbol is the seperated one.
![4097_0_0_0_0_0_0_0_0_0_20211216164447](https://user-images.githubusercontent.com/45090310/147268789-b7d516ee-391a-449e-a9ea-c55d44ee3e5a.jpg)

Please note: Kodi/VLC/Mediaplayer classic plays the subtitles without any problem.
Problem is on all arabic subtitles.
Can someone elaborate please ? I don't think its a skin or font problem. Maybe encoding ?

**Comment by ozone1864** [comment]
@atvcaptain @AbuBaniaz 
Can you please check the problem. I literally tried everything..

**Comment by jbleyel** [comment]
Maybe @persianpros can help here.

**Comment by jbleyel** [comment]
Is this issue fixed?

**Comment by persianpros** [comment]
Sorry for my late answer, I'm fighting bowel cancer.

Regarding Arabic/Persian (RTL) languages you need to use https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/data/fonts/DejaVuSans.ttf only, all other fonts will fail probably.

**Comment by AbuBaniaz** [comment]
Sorry to hear. I pray that you make a full recovery.

**Comment by AbuBaniaz** [comment]
@persianpros 
How is your recovery going?

I have submitted a pull request to update from version 2.33 to 2.37

**Comment by AbuBaniaz** [comment]
@Kerberos1864 
Please try on last nights image or manually update the font
https://github.com/openatv/enigma2/raw/master/data/fonts/DejaVuSans.ttf

If fixed, please close the issue
