### ISSUE TITLE
Sprachen in oATV7.0

### ISSUE THREAD

**Issue by Masta2002** [openatv/enigma2#2158]
So wie im Forum schon diskutiert gibt es mit den Sprachen paar kleinigkeiten die man verbessern könnte
https://www.opena.tv/openatv-7-0-py3-9-openssl-1-1-1-entwicklung/58253-sprachen.html

-unter Plugins Herunterladen / Entfernen könnten sie ganz raus da das dort nicht mehr richtig bzw vollständig anfgezeigt wird und ja durch die neuen einstellungen unter MENU - Einstellungen - Bedienung & Oberfläche - Systemsprache ersetzt wurde

-nach onlineflash mit wiederherstellung müssen nicht wieder alle sprachen da sein sondern nur die die vorher auch installiert waren

--------------------- Google Translate
As already discussed in the forum, there are a few small things with the languages ​​that could be improved
https://www.opena.tv/openatv-7-0-py3-9-openssl-1-1-1-entwicklung/58253- Sprachen.html

-under plugins Download / Remove you could completely out because it is no longer displayed correctly or completely and has been replaced by the new settings under MENU - Settings - Operation & Interface - System Language

-After online flash with recovery not all languages ​​have to be there again but only those that were previously installed

**Comment by jogibaer1948** [comment]
Ja dieses thema ist schon oft diskutiert worden 
Ich würde mir auch wünschen,daß sich die spracheinstellung in der settings datei einträgt und so beim flashen und wiederherstellen nur eine sprache installiert wird

**Comment by jbleyel** [comment]
Löschen der Sprachen nach dem Online Flash. -> https://github.com/openatv/enigma2/issues/2413

**Comment by jbleyel** [comment]
Close because of #2413
