### ISSUE TITLE
Unable to install ATV 7.0 on DM7020HD

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2162]
I cannot install ATV 7.0 onto DM7020HD. It never completes the installation and always errors. Does anyone know why this is?

**Comment by atvcaptain** [comment]
we check it

**Comment by willow5** [comment]
Thank you. I always get "The connection was reset"

**Comment by atvcaptain** [comment]
![grafik](https://user-images.githubusercontent.com/974786/148661926-d9d2e67d-39e3-4261-bf2f-a05068212c41.png)

only a workaroud, dreambox bootloader a a major issue , max 100MB
i rework next weels, after flash install all parts i have removed :)

**Comment by willow5** [comment]
Thank you, how will I know when it is ok to try again?

**Comment by atvcaptain** [comment]
next image 2-3h

**Comment by willow5** [comment]
Brilliant thanks for your efforts!
