### ISSUE TITLE
Blue screen on DM7080 while software update

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2164]
Hello, I am getting a blue screen / crash log when hitting the blue button and trying to perform a software update on a DM7080HD.  

Here is the crashlog:

openATV Enigma2 crash log

crashdate=Mon Jan 10 10:32:45 2022
compiledate=Jan  9 2022
skin=MetrixHD/skin.xml
sourcedate=2022-01-08
branch=7.0
rev=2.8.0-23873-gac6ed61
component=Enigma2

stbmodel=ultimo
stbmodel=dm7080
kernelcmdline=bmem=512M@512M memc1=768M console=ttyS0,1000000 root=/dev/mmcblk0p1 rootwait rootfstype=ext4
nimsockets=NIM Socket 0:
imageversion=box_type=dm7080
imageissue=Welcome to openATV for %h

10:31:58.6186 [Enigma] Python path is '/usr/lib/enigma2/python'.
10:31:58.6190 [Enigma] DVB API version 5, DVB API version minor 11.
10:31:58.6191 [Enigma] Enigma debug level 3.
10:32:28.2153 [eDVBPESReader] Created. Opening demux
10:32:28.2156 [eDVBPESReader] Created. Opening demux
10:32:45.9286 Traceback (most recent call last):
10:32:45.9288   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
10:32:45.9304     response = self.actions[action]()
10:32:45.9306   File "/usr/lib/enigma2/python/Screens/SoftwareUpdate.py", line 149, in keyUpdate
10:32:45.9318     updateLimit = BoxInfo.get("UpdateLimit", 200)
10:32:45.9321 AttributeError: 'BoxInformation' object has no attribute 'get'
10:32:45.9323 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0x6bfc0cb8>>,('ColorActions', 'green')) failed)

dmesg

<4>[79594.019000] HDMI: CEC recv ok!
<6>[79596.636000] bcm4506: channel 0 is sleeping now
<4>[79596.744000] stop PCR0 on dmx 0 pid:1388
<4>[79596.744000] stop AUDIO0 on dmx 0 pid:138a
<4>[79596.745000] audio ch0: xpt stop
<4>[79596.745000] audio ch0: decoder stop
<4>[79596.766000] stop VIDEO0 on dmx 0 pid:1388
<4>[79596.767000] VIDEO0: stop decode
<4>[79596.767000] sync0 1fff no decoder left in sync handling so disable
<4>[79596.768000] sync0: was last pcroffset0 user so free it
<4>[79597.821000] sync0 is off so we enable it
<4>[79597.821000] sync0: allocated pcroffset 0
<4>[79597.822000] sync0: playback!
<4>[79597.822000] VIDEO0: total delay: 0 (0 ms)
<4>[79597.827000] VIDEO0: start decode
<4>[79597.828000] VIDEO0: flush video decoder
<4>[79597.828000] VIDEO0 use saved pts 0xf5660090 (ret 0)
<4>[79597.895000] VIDEO0: first pts 0x0
<4>[79597.896000] VIDEO0: resolution changed (1920 1080)
<4>[79598.046000] VIDEO0: enable tsm
<4>[79598.109000] VIDEO0: stop decode
<4>[79598.110000] sync0 1fff no decoder left in sync handling so disable
<4>[79598.110000] sync0: was last pcroffset0 user so free it
<3>[79598.518000] bcm_accel: invalid opcode! 00000080
<4>[79598.658000] HDMI: CEC device open ... state is 3, flushed 2 old messages from RX fifo
<4>[79598.659000] HDMI: CEC returned state 3
<4>[79598.660000] HDMI: CEC state now 803
<4>[79598.661000] tsmux set cisource reg 06 to val 06
<4>[79598.662000] tsmux set cisource reg 06 to val 06
<4>[79598.662000] tsmux set cisource reg 07 to val 06
<4>[79598.663000] tsmux set cisource reg 07 to val 06
<4>[79598.664000] tsmux set tsports reg 00 to val 06
<4>[79598.664000] tsmux set tsports reg 00 to val 06
<4>[79598.665000] tsmux set tsports reg 01 to val 05
<4>[79598.666000] tsmux set tsports reg 01 to val 05
<4>[79598.667000] tsmux set tsports reg 02 to val 01
<4>[79598.667000] tsmux set tsports reg 02 to val 01
<4>[79598.668000] tsmux set tsports reg 03 to val 00
<4>[79598.669000] tsmux set tsports reg 03 to val 00
<6>[79598.734000] bcm4506: channel 0 is in normal mode now
<6>[79598.742000] bcm4506: channel 1 is in normal mode now
<6>[79598.743000] bcm4506: channel 0 is sleeping now
<6>[79598.750000] bcm4506: channel 1 is sleeping now
<4>[79598.763000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[79598.764000] set current avs auto aspect to 16:9
<4>[79598.765000] set sb to 3(1)
<4>[79598.766000] VIDEO1: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[79598.787000] HDMI: CEC send ok!
<4>[79598.836000] VIDEO0: progressive changed (1)
<4>[79599.166000] HDMI: CEC recv ok!
<4>[79599.234000] HDMI: CEC recv ok!
<4>[79599.352000] 79536087 ms: 75 
<4>[79599.374000] 22 ms: 50 
<4>[79609.031000] HDMI: CEC recv ok!
<4>[79609.544000] 10170 ms: 50 
<4>[79610.082000] 537 ms: 57 
<4>[79610.257000] 175 ms: 58 
<4>[79611.252000] 995 ms: 58 
<4>[79611.311000] 59 ms: 64 
<4>[79611.312000] 1 ms: 65 
<4>[79611.323000] 11 ms: 65 
<4>[79611.324000] 0 ms: 65 
<4>[79611.326000] 1 ms: 65 
<4>[79611.350000] 24 ms: 65 
<4>[79611.471000] 121 ms: 66 
<4>[79611.478000] 7 ms: 66 
<4>[79611.497000] 19 ms: 66 
<4>[79611.498000] 1 ms: 66 
<4>[79611.616000] 118 ms: 66 
<4>[79611.622000] 6 ms: 68 
<4>[79611.629000] 7 ms: 68 
<4>[79611.707000] 77 ms: 68 
<4>[79611.713000] 6 ms: 68 
<4>[79611.729000] 16 ms: 68 
<4>[79611.730000] 1 ms: 68 
<4>[79611.731000] 1 ms: 68 
<4>[79611.738000] 6 ms: 68 
<4>[79611.740000] 1 ms: 68 
<4>[79611.789000] 49 ms: 68 
<4>[79611.831000] 42 ms: 68 
<4>[79611.833000] 2 ms: 68 
<4>[79611.834000] 1 ms: 68 
<4>[79611.839000] 5 ms: 68 
<4>[79611.850000] 11 ms: 68 
<4>[79611.851000] 1 ms: 69 
<4>[79611.856000] 5 ms: 69 
<4>[79613.062000] 1205 ms: 69 
<4>[79613.081000] 19 ms: 70 
<4>[79613.106000] set current avs auto aspect to 16:9
<4>[79613.106000] set sb to 3(1)
<4>[79613.108000] set current avs auto aspect to 16:9
<4>[79613.108000] set sb to 3(1)
<4>[79613.110000] set current avs auto aspect to 16:9
<4>[79613.110000] set sb to 3(1)
<4>[79613.112000] set input to 0
<4>[79613.112000] set fb to 2(-1)
<4>[79613.113000] set current avs auto aspect to 16:9
<4>[79613.113000] set sb to 3(1)
<4>[79613.129000] set mute 0 0
<4>[79613.131000] set ac3 to downmix
<4>[79613.134000] set ac3plus to hdmi_best
<4>[79613.136000] set dtshd to use_hdmi_caps
<4>[79613.138000] set wmapro to downmix
<4>[79613.140000] set aac to downmix
<4>[79613.183000] set current avs auto aspect to 16:9
<4>[79613.183000] set sb to 3(1)
<4>[79613.184000] set current avs auto aspect to 16:9
<4>[79613.185000] set sb to 3(1)
<4>[79613.188000] 107 ms: 70 
<4>[79613.194000] 5 ms: 71 
<4>[79613.205000] 11 ms: 71 
<4>[79613.882000] 677 ms: 71 
<4>[79614.081000] 198 ms: 72 
<4>[79614.181000] 99 ms: 72 
<4>[79614.186000] 4 ms: 72 
<4>[79614.388000] 201 ms: 72 
<4>[79614.413000] 25 ms: 73 
<4>[79614.502000] set current avs auto aspect to 16:9
<4>[79614.502000] set sb to 3(1)
<4>[79614.504000] set current avs auto aspect to 16:9
<4>[79614.505000] set sb to 3(1)
<4>[79614.506000] set current avs auto aspect to 16:9
<4>[79614.507000] set sb to 3(1)
<4>[79614.508000] set current avs auto aspect to 16:9
<4>[79614.509000] set sb to 3(1)
<4>[79614.533000] tsmux set ciclk reg 34 to val 00
<4>[79614.535000] tsmux set ciclk reg 34 to val 00
<4>[79623.368000] using 50.00Hz as MonitorRefreshRate
<4>[79623.368000] VIDEO1: shared window not available
<4>[79623.448000] SET FORMAT: display[0], format='1080p50'
<4>[79623.448000] HDMI mode
<4>[79623.449000] use EDID to detect colorspace
<4>[79623.449000] preferred colorspace: Itu_R_BT_709
<4>[79623.548000] VIDEO1: shared window not available
<4>[79623.628000] set current avs auto aspect to 16:9
<4>[79623.629000] set sb to 3(1)
<4>[79624.118000] HDMI: CEC recv ok!
<4>[79625.680000] rtc set to 1641810746
<4>[79625.683000] rtc set to valid now
<4>[79625.750000] HDMI: CEC send ok!
<6>[79627.273000] bcm4506: channel 0 is in normal mode now
<4>[79627.633000] HDMI: CEC send ok!
<4>[79627.758000] start PCR0 on dmx 0 pid:1388 index 2
<4>[79627.758000] audio ch0: clip stuff already freed
<4>[79627.759000] start AUDIO0 on dmx 0 pid:1389 index 3
<4>[79627.760000] audio ch0: xpt start
<4>[79627.760000] sync0 is off so we enable it
<4>[79627.760000] sync0: allocated pcroffset 0
<4>[79627.761000] sync0: demux-index 0 pcr pid 1388
<4>[79627.761000] sync0: using 2 as pcr pidchannel
<4>[79627.762000] audio ch0: AC3
<4>[79627.762000] audio ch0: streamtype set 1
<4>[79627.763000] audio ch0: streamtype_set: stop rave
<4>[79627.763000] audio ch0: decode
<4>[79627.764000] audio ch0: streamtype_set: restart rave
<4>[79627.764000] audio ch0: decoder start
<4>[79627.765000] audio ch0: video delay 0 (0 ms)
<4>[79627.765000] VIDEO0: total delay: 0 (0 ms)
<4>[79627.768000] VIDEO0: clip stuff already freed
<4>[79627.768000] VIDEO0: set streamtype!
<4>[79627.769000] ->      set H264
<4>[79627.769000] ->      sw rave disabled!
<4>[79627.770000] audio ch0 delay 18000 (200 ms)
<4>[79627.770000] VIDEO0: total delay: 18000 (200 ms)
<4>[79627.771000] start VIDEO0 on dmx 0 pid:1388 index 2
<4>[79627.772000] VIDEO0: total delay: 18000 (200 ms)
<4>[79627.777000] VIDEO0: start decode
<4>[79627.818000] audio ch0: lock
<4>[79627.818000] audio ch0: sample rate changed isr (48000)
<4>[79627.819000] audio ch0: tsm fail
<4>[79627.819000] audio ch0: ignore pts error when audio is not running
<4>[79627.820000] audio ch0: first pts 0x64168048, stc 0x64166a9e, pcr valid
<4>[79627.961000] HDMI: CEC send ok!
<4>[79628.068000] HDMI: CEC recv ok!
<4>[79628.127000] audio ch0: status ready isr
<4>[79628.128000] audio ch0: dialnorm change isr
<4>[79628.334000] HDMI: CEC send ok!
<4>[79628.510000] HDMI: CEC send ok!
<4>[79628.621000] rtc set to 1641810748
<4>[79628.624000] rtc set to valid now
<4>[79629.051000] VIDEO0: first pts 0x64190d2e
<4>[79629.201000] VIDEO0: enable tsm
<4>[79629.811000] VIDEO0: progressive changed (0)
<4>[79639.032000] HDMI: CEC recv ok!

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/4e4074b36047bbdc7aaa1511a8090fae6c3453f1

**Comment by jbleyel** [comment]
Do you have the new SoftwareUpdate.py

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/blob/4e4074b36047bbdc7aaa1511a8090fae6c3453f1/lib/python/Screens/SoftwareUpdate.py

**Comment by willow5** [comment]
Which folder do I upload onto the box? I could not find a lib/python/Screens folder

**Comment by willow5** [comment]
Please can someone kindly advise which folder on the enigma receiver to upload the SoftwareUpdate.py file ?
