### ISSUE TITLE
problem with fav - delete not work

### ISSUE THREAD

**Issue by LyxxSK** [openatv/enigma2#2165]
hi, i found maybe bug, when i use fastscan plugin - and fastscan skylink SK, and when 13 and 19 transponder not set in tunner, after fastscanned created in Favorites - extended - folder - - "0.0E - Services" , i tryed but dont work delete it ... when i set in tunner 13 and 19 transponder and again fast scan skylink SK, in fav created in extended: 13 and 19 folder. i try delete it and work.. not work when 13 and 19 transponder not saved in tunner.

**Comment by jbleyel** [comment]
I don't understand the issue.
Can you please explain this differently.

What is "extended folder"?
What is "fav"?
What exactly do you wanna delete?

You may should post some screenshots.

**Comment by jbleyel** [comment]
No. Updates
Please reopen with more info.
