### ISSUE TITLE
Kodi 19.3 subtitles Subssupport SubsMenu navigation

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2166]
Hi there!

Hope anybody could help with an issue in navigation (with keys Up and Down) on SubsMenu options list view after playback starts in E2Player.
So to detail the problem, i am running openAtv 7.0 with python 3 and subssupport 1.5.7 with kodi 19.1 with the external videoplayer E2Player for movie playback (changed the player in the playercorefactory.xml) on my Vu+ Zero 4K.

After the playback of the movie starts i press the blue key to show the SubsMenu that haves 3 options:

1st option -> "Select subtitles" (pre selected by default)
2nd option -> "Download subtitles"
3rd option -> "Subtitles definitions"

After this menu is loaded i can't navigate the option list with the navigation keys of the remote control to select the Download Substitles option and in the logs this is shown:

14:49:27.1139 [Screen] Showing screen '['KodiVideoPlayer']'.
14:49:27.1189 [Skin] Parsing embedded skin ''.
14:49:27.1201 [Skin] Processing screen '', position=(585, 240), size=(750x600) for module 'SubsMenu'.
14:49:27.1296 [Skin] Parsing embedded skin ''.
14:49:27.1307 [Skin] Processing screen '' from list 'SubsMenu_summary, SimpleSummary', position=(0, 0), size=(132x64) for module 'SimpleSummary'.
14:49:27.1339 [Screen] Showing screen '['SubsMenu_summary', 'SimpleSummary']'.
14:49:27.1358 [Screen] Showing screen 'SubsMenu'.
14:49:27.1365 [eRCDeviceInputDev] 0 191 1
14:49:27.1370 [InfoBarGenerics] Key: 401 (Break) KeyID='KEY_BLUE'.
14:49:27.1479 [eServiceMP3] ****STATE TRANSITION PLAYING -> PAUSED ****
14:49:27.1624 [Volume Adjust] Update Info
14:49:27.1626 [Volume Adjust] Volume = 18
14:49:27.1626 [Volume Adjust] load xml...
14:49:30.2627 "::ffff:192.168.0.200" - - [10/Jan/2022:14:49:29 +0000] "GET /web/currenttime HTTP/1.1" 200 82 "-" "Kodi/19.1 (X11; Linux aarch64) LibreELEC/10.0 App_Bitness/32 Version/19.1-(19.1.0)-Git:6402a50950ff6463042f8891ec4029c782730391"
14:49:31.2754 [eRCDeviceInputDev] 1 6c 1
14:49:31.2762 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
14:49:31.2765 [ActionMap] Keymap 'SetupActions' -> Unknown action 'down'! (Typo in keymap?)

Can anybody help?

**Comment by ruipisco** [comment]
@atvcaptain could you help in this issue?

**Comment by jbleyel** [comment]
please copy this file 
[subtitles.txt](https://github.com/openatv/enigma2/files/7857654/subtitles.txt)
to 
/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/subtitles.py

And try again.

**Comment by ruipisco** [comment]
Hi @jbleyel ,

The navigation of the menu works now!
Now when i enter in option 2 "Download Subtitles", in the next menu of the substitle search criteria with the description of the subtitles title, the digit keys of the remote control doesn't work to write the title of the movie (sometimes i need to change the Portuguese title to English to retrieve results of the subtitles). 

Here is the crash log and the interface log of the error:

[enigma2_crash_1642024710.log](https://github.com/openatv/enigma2/files/7858246/enigma2_crash_1642024710.log)
[Enigma2-debug-20220112_21-55-41.log](https://github.com/openatv/enigma2/files/7858247/Enigma2-debug-20220112_21-55-41.log)

**Comment by jbleyel** [comment]
https://github.com/oe-mirrors/subssupport/commit/ec1f630d84644e887b4949237f9730f4ab86f83f

**Comment by ruipisco** [comment]
@jbleyel the virtual keyboard woks fine now on the search Menu! only missing the download of the subtitles!

I don't know after the download works if the history of the downloaded subtitles works...

thank for your help!

**Comment by jbleyel** [comment]
please try again with this commit

https://github.com/oe-mirrors/subssupport/commit/0fed0b4b4e88a023e76b2c887e723c1d0d32b13f

**Comment by ruipisco** [comment]
Hi @jbleyel 

The same issues perssist on the subtitles download.

If selected an english subtitle it does the downlaod but it gives the error (see crashlog in attach of blue screen) if another language like portuguese PT it trows the error on the screen like this image:

![errorscreen](https://user-images.githubusercontent.com/32041748/149510189-2f23ef22-fa61-4345-b047-6cab3b27829a.jpeg)

[enigma2_crash_1642160333.log](https://github.com/openatv/enigma2/files/7870092/enigma2_crash_1642160333.log)

**Comment by jbleyel** [comment]
https://github.com/oe-mirrors/subssupport/commit/890e8413e8df1db5918dd1a4f68d7bcbbf84007b

**Comment by ruipisco** [comment]
Now for english subs it works fine but for other language like Portuguese is not working? maybe the enconding types?

**Comment by jbleyel** [comment]
Please provide the debug log for download error

**Comment by ruipisco** [comment]
Here the Logs:

Enigma2:

[Enigma2-debug-20220114_15-17-08.log](https://github.com/openatv/enigma2/files/7871479/Enigma2-debug-20220114_15-17-08.log)

CrashLog:

[enigma2_crash_1642173620.log](https://github.com/openatv/enigma2/files/7871489/enigma2_crash_1642173620.log)

**Comment by ruipisco** [comment]
English also crashed, in the history section i see that the english .srt file keeps the name but on other language it changes the file to a random string like 123are.srt

**Comment by jbleyel** [comment]
There are many strange log entries like this -> [OpenWebif] page 'b' .... in your debug log.
I have no idea why?
The subsdownloader has no link to the OpenWebif

**Comment by ruipisco** [comment]
yes i know! on open atv 7.0 the debug level 4 is activated, and that is my RPi4 that conects with Enigma2 pvr client add-on  to my Vu+ Zero 4K (for straeming the channels fo setup box to RPi4), so that's why the logs are there....

**Comment by ruipisco** [comment]
@jbleyel 

Leave here an image of the blue screen crash... hope it helps and it more objective...

![bluescreen](https://user-images.githubusercontent.com/32041748/149549321-38886cef-9627-4ea5-9591-11062c3eef55.png)
.

**Comment by jbleyel** [comment]
you do not have all changes

**Comment by jbleyel** [comment]
https://github.com/oe-mirrors/subssupport/commit/f2528b2888eb39e89a2ce4706d734406d9e3a5c2

https://github.com/oe-mirrors/subssupport/commit/5dad1c28f09a9b251aea7481569a7027eec18a4c

https://github.com/oe-mirrors/subssupport/commit/3240e7e14f26bd8ab688da56ed1a7818df04959c

**Comment by ruipisco** [comment]
@jbleyel i already have merged all the files and it seems to work fine now...
Only in portuguese subtitles in some .srt files it trowsback an error on subsupport viwe with the message "Is not possible to verify subtitle format" when loading the downloaded title, but i will test it more and then leave feedback!

**Comment by ruipisco** [comment]
@jbleyel 

Most of the portuguese subtitles trows an error.
Here is the Enigma2 Log of the Portuguese subtotle of the movie Wrath of Man below:

21:58:23.8843 [SubsSearch] download success /tmp/Wrath.of.Man.2021.1080p.BluRay.H264.AAC-RARBG.srt
21:58:23.8977 [Screen] Showing screen '['SubsMenu_summary', 'SimpleSummary']'.
21:58:23.9440 [eConsoleAppContainer] user send SIGINT(Ctrl-C)
21:58:23.9444 1 processes still running
21:58:23.9520 [Screen] Showing screen 'SubsMenu'.
21:58:23.9552 [Screen] Showing screen '['KodiVideoPlayer_summary', 'SimpleSummary']'.
21:58:23.9622 [Screen] Showing screen '['KodiVideoPlayer']'.
21:58:23.9684 [AVSwitch] reading edid modes failed, using all modes
21:58:23.9704 [AVSwitch] reading _preferred modes:  ['']
21:58:23.9714 [AVSwitch] preferend modes not ok, possible driver failer, len= 1
21:58:23.9844 [ePicLoad] setPara max-X=300 max-Y=300 aspect_ratio=1,000000 cache=0 resize=0 bg=#00000000
21:58:24.0173 [Screen] Showing screen 'SubsScreen'.
21:58:24.0188 [SubsLoader][info] <Wrath.of.Man.2021.1080p.BluRay.H264.AAC-RARBG.srt> loading ...
21:58:24.0198 [decode] trying encoding utf-8 ...
21:58:24.0200 [decode] decoded with utf-8 encoding
21:58:24.0201 [SubsLoader][info] looking for '.srt' parser
21:58:24.0203 [SubsLoader][info] found <SubRipParser> parser
21:58:24.0204 [SubsLoader][info] <SubRipParser> parsing...
21:58:24.0207 [SubsLoader][error] <SubRipParser>: 
21:58:24.0208 [SubsLoader][info] trying parsing with <SubRipParser>
21:58:24.0212 [SubsLoader][info] trying parsing with <MicroDVDParser>
21:58:24.0214 [SubsLoader][error] <MicroDVDParser>: cannot parse, FPS not provided
21:58:24.0300 [Skin] Processing screen 'MessageBox', position=(360, 240), size=(1200x600) for module 'MessageBox'.
21:58:24.0808 [Screen] Warning: Skin is missing element 'QuestionPixmap' in <class 'Screens.MessageBox.MessageBox'>(Não é possível analisar legendas. Formato de legendas não suportado).
21:58:24.0814 [Screen] Warning: Skin is missing element 'InfoPixmap' in <class 'Screens.MessageBox.MessageBox'>(Não é possível analisar legendas. Formato de legendas não suportado).
21:58:24.0818 [Screen] Warning: Skin is missing element 'ErrorPixmap' in <class 'Screens.MessageBox.MessageBox'>(Não é possível analisar legendas. Formato de legendas não suportado).
21:58:24.0825 [MessageBox] Timeout set to 5 seconds.
21:58:24.0878 [Skin] Parsing embedded skin '<embedded-in-MessageBoxSummary>'.
21:58:24.0886 [Skin] Processing screen '<embedded-in-MessageBoxSummary>' from list 'MessageBoxSummary, ScreenSummary, MessageBox_summary, SimpleSummary', position=(0, 0), size=(132x64) for module 'MessageBoxSummary'.
21:58:24.1035 [Screen] Showing screen '['MessageBoxSummary', 'ScreenSummary', 'MessageBox_summary', 'SimpleSummary']'.
21:58:24.1050 [Screen] Showing screen '['MessageBox']'.
21:58:24.1055 [SubsSupport] unpausing video

**Comment by ruipisco** [comment]
@jbleyel here are two .srt files of  the movie "Ghostbusters: Afterlife", the English version it's encoded in UTF-8 and the Portuguese version is encoded in Western European Windows (encoding used for Spain, France, Germany...), and the "subrip.py" parser can't read the file.

Can you help with this issue?

**Comment by jbleyel** [comment]
Please send me the srt file.

**Comment by ruipisco** [comment]
@jbleyel 

here are the files to test for the movie The Bourne Identity (2002):

English Working subtitle (UTF-8):
[The Bourne Identity.en.srt.zip](https://github.com/openatv/enigma2/files/7897545/The.Bourne.Identity.en.srt.zip)
 
Portuguese Non-Working subtitle (non UTF-8):
[The Bourne Identity.pt.srt.zip](https://github.com/openatv/enigma2/files/7897554/The.Bourne.Identity.pt.srt.zip)

**Comment by jbleyel** [comment]
I need the subsupport.log for the wrong srt file

**Comment by ruipisco** [comment]
Gere is the log of the subsupport 

[subssupport.log](https://github.com/openatv/enigma2/files/7901052/subssupport.log)

**Comment by ruipisco** [comment]
Hi @jbleyel,

Here are the Portuguese (PT - not UTF-8) subtitle file of teh Movie "The Bourne Identity" that trows the error and the log file of SubsSupport:

Subtitle (PT):
[The.Bourne.Identity.2002.1080p.BluRay.H264.AAC-RARBG.pt.srt.zip](https://github.com/openatv/enigma2/files/7907884/The.Bourne.Identity.2002.1080p.BluRay.H264.AAC-RARBG.pt.srt.zip)


SubsSupport Log File:
[subssupport.log](https://github.com/openatv/enigma2/files/7907889/subssupport.log)

**Comment by jbleyel** [comment]
There are no errors in subssupport.log

**Comment by ruipisco** [comment]
ok, look to the enigma2 log file in attach beetween lines 4300 and 4353
[Enigma2-debug-20220120_21-15-51.log](https://github.com/openatv/enigma2/files/7908613/Enigma2-debug-20220120_21-15-51.log)

**Comment by jbleyel** [comment]
https://github.com/oe-mirrors/subssupport/commit/175d27c32f2eddd713648a5607d5f19da45b6d9c

**Comment by ruipisco** [comment]
@jbleyel i will test it during the weekend and leave some feedback!

**Comment by ruipisco** [comment]
@jbleyel after testing everything now works fine on opentav 7.0 (python 3) with kodi Matrix 19.3 and external videoplayer E2Player, for all language encodings! Thank you for your help!
