### ISSUE TITLE
OpenATV 7.1 - Crypto

### ISSUE THREAD

**Issue by mtester270** [openatv/enigma2#2167]
Some plugins failed to load on Crypto.
build: openatv-7.1-vusolo4k-20220108_usb.zip

Log:
`
12:56:44.8743 Plugin  SystemPlugins/WirelessLan failed to load: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cpython-310-arm-linux-gnueabi.so': cannot load library '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.cpython-310-arm-linux-gnueabi.so': /usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.cpython-310-arm-linux-gnueabi.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.cpython-310-arm-linux-gnueabi.so', Trying '_MD5.abi3.so': cannot load library '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.abi3.so': /usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.abi3.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.abi3.so', Trying '_MD5.so': cannot load library '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.so': /usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.so'
12:56:44.8838 Traceback (most recent call last):
12:56:44.8846   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 57, in readPluginList
    plugin = my_import('.'.join(["Plugins", c, pluginname, "plugin"]))
12:56:44.8850   File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
    mod = __import__(name)
12:56:44.8854   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/WirelessLan/plugin.py", line 17, in <module>
    from .Wlan import iWlan, iStatus, getWlanConfigName
12:56:44.8856   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/WirelessLan/Wlan.py", line 16, in <module>
    from wifi.scan import Cell
12:56:44.8858   File "/usr/lib/python3.10/site-packages/wifi/__init__.py", line 1, in <module>
    from wifi.scan import Cell
12:56:44.8859   File "/usr/lib/python3.10/site-packages/wifi/scan.py", line 8, in <module>
    from wifi.utils import db2dbm, pass2psk, logger, PrivilegedCommand
12:56:44.8861   File "/usr/lib/python3.10/site-packages/wifi/utils.py", line 8, in <module>
    from pbkdf2 import PBKDF2
12:56:44.8862   File "/usr/lib/python3.10/site-packages/pbkdf2.py", line 62, in <module>
    from Crypto.Hash import HMAC, SHA as SHA1
12:56:44.8864   File "/usr/lib/python3.10/site-packages/Crypto/Hash/HMAC.py", line 38, in <module>
    from Crypto.Hash import MD5
12:56:44.8865   File "/usr/lib/python3.10/site-packages/Crypto/Hash/MD5.py", line 29, in <module>
    _raw_md5_lib = load_pycryptodome_raw_lib("Crypto.Hash._MD5",
12:56:44.8866   File "/usr/lib/python3.10/site-packages/Crypto/Util/_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
12:56:44.8875 OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cpython-310-arm-linux-gnueabi.so': cannot load library '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.cpython-310-arm-linux-gnueabi.so': /usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.cpython-310-arm-linux-gnueabi.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.cpython-310-arm-linux-gnueabi.so', Trying '_MD5.abi3.so': cannot load library '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.abi3.so': /usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.abi3.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.abi3.so', Trying '_MD5.so': cannot load library '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.so': /usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/python3.10/site-packages/Crypto/Util/../Hash/_MD5.so'
`

**Comment by atvcaptain** [comment]
have you same name of not loading plugins

**Comment by mtester270** [comment]
Which version want you to try? (latest 7.1 or 7.2)

**Comment by jbleyel** [comment]
I'm using 7.2 and I have no issues.
Do you have any 3rd party plugins installed?

**Comment by mtester270** [comment]
No plugins, that error rise in console when start enigma in debug mode in vu+ solo 4k, but long time ago (box must require that module, etc. Solo2 start without issue at that time)

**Comment by atvcaptain** [comment]
its fixed ? i flash solo4k 7.1 current image
init 4
enigma2 no hash crypt error message in he log

**Comment by mtester270** [comment]
As i sad long time a go. So you can close the ticket as resolved.
