### ISSUE TITLE
Unable to progress frame by frame or /2 speed when playing MPG files

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2168]
I am unable to progress frame by frame or at /2 speed when playing MPG files.  I can only fast forward x2 or rewind x2.  Can this be investigated please ?

**Comment by atvcaptain** [comment]
hardware model you use ?

**Comment by willow5** [comment]
DM7080 Dreambox

**Comment by willow5** [comment]
Is there any update on this please?

**Comment by atvcaptain** [comment]
we cant fix this issue with dream hw
