### ISSUE TITLE
Subtitles out of sync with the integrated player

### ISSUE THREAD

**Issue by olivluca** [openatv/enigma2#2175]
On a Uclan Ustym 4K PRO Twin, running OpenATV 7.0.20220112 (2022-01-11), the subtitles, when playing a recording, are way out of sync (several seconds early).
I tried the bbc channels at 27.5W and rai at 13.0E.
It doesn't happent while watching live tv or if I stream the recording to vlc (though I cannot test the rai channels there since vlc isn't showing the teletext subtitles).

**Comment by jbleyel** [comment]
Please create a new issue if still exists in 7.4.

I’m not able to reproduce this for Astra 19,2 channels.
