### ISSUE TITLE
DM7020HD: Sorry, feeds are currently unavailable

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2178]
I have just installed the latest openatv 7.0 image on my DM7020HD but when I hit the green button, I get this image:

![4097_0_1_203_0_0_0_0_0_0_20220120152817](https://user-images.githubusercontent.com/64496221/150357760-c6f4f968-7f1d-4906-b40d-7d09e385ba87.jpg)

I tried opkg update also which updates the feeds but still the same problem exists even after reboot.  Any help or advice please ?

**Comment by jbleyel** [comment]
please call 
opkg update
opkg upgrade
in console

**Comment by dazulrich** [comment]
I renamed var/lib/opkg in /mnt/hdd and then the feeds reappeared. not sure why its there and why its causing that problem.
Software update worked.. only not the plugin feed from the pluginbrowser.

**Comment by jbleyel** [comment]
I have changed the pluginbrowser, this should fix your issue.

**Comment by willow5** [comment]
Thanks. Does it mean I need to download the latest update for the new pluginbrowser to work now?

**Comment by jbleyel** [comment]
You need the latest version of pluginbrowser.py from git.

**Comment by willow5** [comment]
works well thanks !
