### ISSUE TITLE
OpenWebif in Zgemma H9.2S missing transcoding icons

### ISSUE THREAD

**Issue by vpont** [openatv/enigma2#2190]
Flashed: **openatv-7.0-zgemmah92s-20220122_usb.zip**

This box is capable of multitranscoding but OpenWebif is missing the transcoding icons (which where present in Open PLI):
![image](https://user-images.githubusercontent.com/3983093/152975113-06e4c067-e9b0-4e6b-9b93-a2d4c3be8f15.png)

In fact, adding `?bitrate=1000000&width=1028&height=720&vcodec=h265&aspectratio=2&interlaced=1` to the standard stream does transcode just fine.

**Comment by jbleyel** [comment]
you need to wait for an image after 2.2.

**Comment by jbleyel** [comment]
Please re-flash with a new image .
