### ISSUE TITLE
stream problem on OpenATV6.4

### ISSUE THREAD

**Issue by tempzi13** [openatv/enigma2#2197]
Hello! Have you checked this problem?
https://www.opena.tv/jamesdonkey-duo-hd/55112-streaming-frozen-changing-channel.html
I have the same problem on hitube4kcombo (OpenATV 6.4.20220204 (2022-01-25)). 

Also there are logs such this:
Feb 11 17:44:36 hitube4kplus user.warn kernel: [04:59:29:461 ERROR-HI_DEMUX]:DmxGetRecInstance[14863]:This Rec(0) instance has not alloced.
Feb 11 17:44:36 hitube4kplus user.warn kernel: [saveTsDataThread] HI_UNF_DMX_AcquireRecData failed 0x80150002
Feb 11 17:44:36 hitube4kplus user.warn kernel: !!!!record_stop with dmx 0!!!!
Feb 11 17:44:36 hitube4kplus user.err kernel: HI_UNF_DMX_DetachFilter error:80150002 ! filter 167903234
...
Feb 13 18:28:02 hitube4kplus user.warn kernel: vmap allocation for size 4194304 failed: use vmalloc=<size> to increase size.
Feb 13 18:28:02 hitube4kplus user.warn kernel: [HI_DRV_SMMU_AllocAndMap] Remap DMX_RecBuf[3] failed
Feb 13 18:28:02 hitube4kplus user.warn kernel: [05:42:55:098 ERROR-HI_DEMUX]:DmxAllocNonSecureRecBuf[15207]:mmu memory allocate failed, BufSize=0x3fe400
Feb 13 18:28:02 hitube4kplus user.warn kernel: [record_start - 220] HI_UNF_DMX_CreateRecChn failed 0x80150006
Feb 13 18:28:02 hitube4kplus user.warn kernel: cur group id is 0
Feb 13 18:28:02 hitube4kplus user.warn kernel: [05:42:55:215 ERROR-HI_DEMUX]:HI_DRV_DMX_AddRecPid[1410]:Invalid Rec Handle 0x0
Feb 13 18:28:02 hitube4kplus user.warn kernel: record_add_pid failed with pid:0 hChannel -359366656 -2146107390
Feb 13 18:28:02 hitube4kplus user.warn kernel: alloc_channel filterUnqId 0 pid:0x0 type:1

Also multitranscoding is not worked (not available by url).

**Comment by jbleyel** [comment]
Please use 7.1 or 7.2 because 6.4 is EOL

**Comment by flextcg** [comment]
This is still an existing issue with Hisilicon based devices. I'm struggling with it on the Amiko Viper Single box even on 7.6 alpha, and could not find a workaround using Sat>IP servers either.

[messages.log](https://github.com/user-attachments/files/18813489/messages.log)

**Comment by atvcaptain** [comment]
the model dont support satip

**Comment by flextcg** [comment]
It does. SatPI and minisatip locks up for the same reason, but works fine before the kernel error occurs.
