### ISSUE TITLE
OpenAtv 7.0 METRIX FHD SKIN

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2199]
After updating to Openatv 7.0 latest update of 14-02-2022, it thows the error in the image above:

![2E806150-28AA-4801-8BB4-A85C4FC1C0AC_1_105_c](https://user-images.githubusercontent.com/32041748/153920513-0b302dd9-0587-4d6b-a2db-8984d639599a.jpeg)

Kodi Matrix 19.3 also can't start.

This happens in VuPlus ZERO 4K, but probably it happens in any setup box that uses the FullHD skin of MetrixHD.

Can anybody help?

Thanks!

**Comment by jbleyel** [comment]
Please enable debug log and then goto Plugins MetrixLite enabled FHD and press green to apply settings.
Then provide the debug log.

**Comment by ruipisco** [comment]
@jbleyel above the log file with the error (between lines 3120 and 3180):

[Enigma2-debug-20220215_13-24-49.log](https://github.com/openatv/enigma2/files/8069459/Enigma2-debug-20220215_13-24-49.log)

Thanks!

**Comment by jbleyel** [comment]
Kodi fix -> https://github.com/oe-alliance/kodiext/commit/96a2bbf97434860249eb62bae2b7554dfd3b6b30

Metrix fix -> https://github.com/openatv/MetrixHD/commit/6fa8b60c71a0eef630e9d8c29a4ae0087031d95f
