### ISSUE TITLE
KODI 19.3 don't start in OpenATV 7.0 

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2200]
Hi @jbleyel after yesterday fix for kodi 19.3 it still does not boot.

I leave the log file of the error (kodi error on launching between lines 236 and 269) above, after todays update to help solving the error:

[enigma2_crash_1645002519.log](https://github.com/openatv/enigma2/files/8078416/enigma2_crash_1645002519.log)

Hope this will help!

**Comment by jbleyel** [comment]
What have you done?

**Comment by ruipisco** [comment]
@jbleyel i have removed kodi extension and install it from the feed again to pull the latest changes, after updating the OPEN ATV 7.0 to todays update 16-02-2022.
Kodi does not start, the screen is stucked in black.

**Comment by jbleyel** [comment]
You need to wait for the next update, the Kodi package on the feed is not updated yet.

**Comment by ruipisco** [comment]
@jbleyel , sorry i didn´t mention that after the update and the new pull of kodi i went o to file "plugin.py" and made the changes of the solution that you implemented on the file manualy and it work trows back the erros that i sent you... so the problem will not be solved with the update when the feed will be updated.

**Comment by jbleyel** [comment]
Please do not manually change the files on you box if you do not know exactly what you do.
You need to get the plugin.py from git and replace the complete file.
