### ISSUE TITLE
OpenATV 7.0 Navigation Menu error

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2201]
Hi @jbleyel in the navigation menu when entering in the option Menu "STB Display" (navigation path after pressing Menu button on remote: "Setup"->"Usage & User Interface"->"Front Panel Display Settings") it thows back some errors.

Above the log files of the error:

[enigma2_crash_1645003909.log](https://github.com/openatv/enigma2/files/8078638/enigma2_crash_1645003909.log)

[Enigma2-debug-20220216_08-54-02.log](https://github.com/openatv/enigma2/files/8078643/Enigma2-debug-20220216_08-54-02.log)

Hope this will help.

**Comment by jbleyel** [comment]
Please provide the screenshot right before you press OK to reproduce the crash.
I need to know what you wanna open next.

**Comment by ruipisco** [comment]
@jbleyel here it is step by step after clciking the "Menu" button on the remote control:

Frist Menu Option "Setup"

![1](https://user-images.githubusercontent.com/32041748/154283425-b97d7d16-737c-4915-a284-1d8d9ebca3e7.jpeg)


Second Menu Option "Usage & User Interface"

![2](https://user-images.githubusercontent.com/32041748/154283449-4e6b8eac-9ce7-426d-93c3-65eb8d936f25.jpeg)


Third Menu Option "Front Panel Display Settings"

![3](https://user-images.githubusercontent.com/32041748/154283497-18dc8a68-e7fb-4a36-8e15-79ab3626cff7.jpeg)


Error Screen after pressing "OK" button on the remote to go to next Menu OptionList

![IMG_2720](https://user-images.githubusercontent.com/32041748/154285032-4a3faf8e-0e16-46c6-aa3c-248c5401f9f3.JPG)
