### ISSUE TITLE
Video position bookmarking feature?

### ISSUE THREAD

**Issue by klorinczi** [openatv/enigma2#2208]
Hi,

I have VU+ DUO 4K SE PVR, installed OpenATV, but I did not find video position bookmarking feature. 

By bookmark I mean placing position marks (jump points) into the video recording.
Using this I could jump to any bookmarked point/location within the video during the playback.

Could be possible to implement such video bookmarking (jump points) feature?

Thanks!

**Comment by Papi2000-new** [comment]
Just use EnhancedMovieCenter for playback, and key "0" to insert / delete jump marks.
There are some special marks, that can not be deletet with "0" (epg, playback-stop for resume).
