### ISSUE TITLE
KODI 19.4 for Openatv 7.0

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2219]
@jbleyel is it possible to compile the newer version of Kodi Matrix 19.4 ?
This will solve some interface bugs...
Thanks

**Comment by nickersk** [comment]
this needs to be done in OEA-core. i will test.

**Comment by ruipisco** [comment]
@nickersk i leave you soem files that i've changed do to make it work for 4K resolution for large screen TV's, but the values are static. For this to work properly i would be good if the file "plugin.py" on line 69 and  198 could be fetched the system settings resolution to work fine in 2130p.

Here is the zip files with some changes in code of files and better quality images for a more clean external video player:

[Kodi.zip](https://github.com/openatv/enigma2/files/8199906/Kodi.zip)

**Comment by ruipisco** [comment]
hi @nickersk! after todays update i saw that kodi was updated to Matrix version 19.4! For this so many thanks! But there is an problem, that is after watching  a movie with the external E2Player when i try to quit kodi it be stuck and i just can quit be doing an hard reset. Could you please verify this issue? t

**Comment by djjjjj26** [comment]
Is possible to build Kodi Matrix 19.4  with ffmpeg 4.4.2. It solves the memory leak issue, this will solve the problem with stuck kodi when wathing  video.

**Comment by ruipisco** [comment]
After code cleanup of the stable release of OPENATV 7.0 Kodi can shutdown fine in VuPlus Boxes with external E2Player!
