### ISSUE TITLE
KODI 19.3 External player Error on OpenATV 7.0

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2220]
Hi @jbleyel 

When trying to open an internet stream in Kodi 19.3 with external player it crashes,  error log file bellow:

[enigma2_crash_1646764170.log](https://github.com/openatv/enigma2/files/8208753/enigma2_crash_1646764170.log)

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/kodiext/commit/e2887a73241e3835727588c3fb6d5fd37e157e20
