### ISSUE TITLE
Menu keeps appearing repeatedly 

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#2229]
This menu keeps appearing repeatedly every few minutes with the latest update. I have a DM7080HD.
![1_0_1_1847_7F3_2_11A0000_0_0_0_20220314220120](https://user-images.githubusercontent.com/64496221/158268535-392c59a9-4b46-479b-a65e-6a05f497aeed.jpg)

**Comment by jbleyel** [comment]
Please provide more info and debug log.
