### ISSUE TITLE
Feature request: EMC sorting like file explorer

### ISSUE THREAD

**Issue by oopptt** [openatv/enigma2#2254]
Hi guys,

I have tested a couple of Openatv versions, now in 6.4, and I've found a unexpected behavior (for me) in EMC. I would like to have all the files sorted alphabetically like a windows explorer, so directories first followed by the files. But if I try to order alphabetically, folders are mixed among the files, they don't remain at the top. If you test for example in a windows explorer, files are sorted alphabetically with folders remaining at the top. 

Is this expected? Could we have a sorting option like that for future releases?

Thank you so much in advance.

**Comment by jbleyel** [comment]
Are you sure about EMC?
The EMC sorting is correct on ATV 7.0.
The sorting of the "normal" movieselection is wrong in ATV 7.0 and will be fixed.

**Comment by oopptt** [comment]
Hi,

thanks for replying. I'm using 6.4. Let me explain, I'm not saying it's wrong. Imagine you have some folders and some files at the root folder. When you try to sort them alphabetically, everything is sorted alphabetically, but folders/directories are not at the top of the screen, they are mixed with the files. So alphabetically order works perfectly, but it'ts not as a windows explorer where directories remains at the top. 

Let me know if I explained it correctly, maybe I can upload some outputs. I have not tried with 7.0, maybe in 7.0 we have this option.

Regards.

**Comment by jbleyel** [comment]
Please try EMC on ATV 7.0 if possible.
We will only make fixes in ATV 7.0 because we plan to make 6.4 EOL in the near future.

**Comment by oopptt** [comment]
OK, sure, will test 7.0 and let you know, thanks again!

**Comment by jbleyel** [comment]
Please provide screenshots from 7.0 if there is an issue.

**Comment by Papi2000-new** [comment]
What is your setting in EMC setting for that point
![EMC sort order for folders](https://user-images.githubusercontent.com/80783721/161853963-594574c2-0485-45ea-acf6-04dcc3634fc8.png)
?

**Comment by oopptt** [comment]
> What is your setting in EMC setting for that point? It must be deactivated. ![EMC sort order for folders](https://user-images.githubusercontent.com/80783721/161853963-594574c2-0485-45ea-acf6-04dcc3634fc8.png) ?

Hi,

you made my day @Papi2000-new . I don't know why that setting was activated. Maybe I did by thinking that without that I wouldn't see any directories on the file list. Now I can see films sorted correctly. Thanks a lot guys and sorry the inconvenience. I will close the issue.

Have a nice day. Regards.
