### ISSUE TITLE
UDF-fs , UBI error

### ISSUE THREAD

**Issue by thawtes** [openatv/enigma2#2256]
hello,

device: vuduo2
image: openatv 6.4

in crashlog file, these lines caught my attention today and it's the first time I see it.

```
<4>UDF-fs: warning (device mtdblock2): udf_fill_super: No partition found (2)
<4>UDF-fs: warning (device mtdblock2): udf_fill_super: No partition found (2)
<3>UBI error: ubi_open_volume: cannot open device 0, volume 0, error -16
```

What does this mean and is there a way to fix it?
I'm not sure exactly but this happened after trying to do a recent install of openatv7.1
Something wrong with mtd blocks?

thx

**Comment by jbleyel** [comment]
Looks like a driver bug. This log entry is not new and not ATV specific.

https://vuplus-support.org/wbb4/index.php?thread/72603-ubi-error-bootlogs-duo2/&s=e7ca390acf4779f01ec2f54ab1347a9bf0cbd1fb

**Comment by jbleyel** [comment]
@atvcaptain: Can we close this?

**Comment by atvcaptain** [comment]
this is not image dependent, rather his box has problems with the NAND memory, if this happens again and again the nand memory will slowly fail I think
