### ISSUE TITLE
.MPD streams in OpenATV

### ISSUE THREAD

**Issue by rszwed987** [openatv/enigma2#2269]
I think OpenATV should play streams .MPD like "normal" .M3U8 strams natively. I will give an example of .MPD stream:
https://live-insysgo.cf.insyscd.net/echo24.720.smil/manifest.mpd

Such streams are often used today.

This stream are normally from Kodi. Normally Kodi requires this plugins:

https://github.com/xbmc/inputstream.adaptive 
 GPL-2.0 License

https://github.com/xbmc/inputstream.ffmpegdirect
 GPL-2.0 License

https://github.com/xbmc/inputstream.rtmp
 GPL-2.0 License

I think it would be worth adding it natively in OpenATV to be able to play .MPD streams (as in OpenATV it plays .M3U8 streams or as an additional plugin for OpenATV).

**Comment by 4l3x2k** [comment]
What do you mean by natively?

What image version of what date are you using?

Adding the link above to bouquet works out of the box. No need for serviceapp or the like.

File like userbouquet.dash.tv with the following contents:
```
#NAME DASH Test Assets - 4097
#SERVICE 1:64:1:0:0:0:0:0:0:0::IPTV-ORG
#SERVICE 1:64:1:0:0:0:0:0:0:0::https://iptv-org.github.io
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//live-insysgo.cf.insyscd.net/echo24.720.smil/manifest.mpd:Echo24
```

![image](https://user-images.githubusercontent.com/25264/167290573-503333d1-d63d-41cf-8f98-b235d38397a9.png)

**Comment by rszwed987** [comment]
I have OpenATV with version 7.1 (date 2 may 2022). I have a decoder: AX 4K-BOX HD61. I will try later

**Comment by rszwed987** [comment]
I have OpenATV with version 7.1 (date 2 may 2022). I have a decoder: AX 4K-BOX HD61. 

![Zrzut ekranu 2022-05-09 093252](https://user-images.githubusercontent.com/89768100/167361798-e7767a8e-17df-4bdf-a52c-765bf35f20e2.png)

I added it manually but I see black screen on this channel.

**Comment by 4l3x2k** [comment]
Look like hd61 is using servicehisilicon as media service.

Can you confirm that by looking at MENU - Information - About openATV / Enigma2 Information / Mediaservice?

If that is the case then it is a driver issue I think. Normally servicegstreamer handles dash and hls.

Getting new drivers isn't easy and depend on manufacturer, so you could try removing / uninstall enigma2-plugin-systemplugins-servicehisilicon **BUT MAKE A FULL BACKUP BEFORE**!

Maybe someone else can confirm that it is or is not working with servicehisilicon.

**Comment by 4l3x2k** [comment]
Maybe better solution is to use / install ServiceApp and change servicereftype from 4097 to 5002.

**Comment by rszwed987** [comment]
Yes. I can see servicehisilicon as media service.
When I changed serviceretype from 4097 to 5002 still doesn't work for me. 
In this case I don't see a name of channel "Echo24" but <N/A>

**Comment by 4l3x2k** [comment]
Puhhh ...

Then there is only the approach by removing enigma2-plugin-systemplugins-servicehisilicon which was my first tip.

Remove serviceapp
Remove servicehisilicon (command mentioned above)

**Comment by rszwed987** [comment]
Thanks :-)

**Comment by 4l3x2k** [comment]
Video and Audio running?

**Comment by rszwed987** [comment]
All .MPD links works.

Some M3u8 does't works 
Viva Russia doesn't works today https://live.prd.dlive.tv/hls/live/viva-russia.m3u8 On OpenATV worked earlier. No voice/video.
Channel "Strefa TV" doesn't work today http://stream.sferatv.pl:1935/sferalive/smil:sferalive.smil/playlist.m3u8  On OpenATV worked earlier. No video. Only voice.
Channel "Retro" doesn't work today http://89.185.253.55/retrotv/retrotvHQ1/playlist.m3u8   On OpenATV worked earlier. No video. Only voice.

All mentioned M3U8 links works on the computer only
