### ISSUE TITLE
Log Flooding / has_external_rotor

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#2272]
This is a part of one debug log.
There are more than 2000 log entries like this.

```
22:06:54.0051 has_external_rotor /home/root/rotor_0 no
```

This is not really useful.
Hi @olivluca , Please fix.

**Comment by olivluca** [comment]
Well, it was useful during debugging.
Is there a less spammy function than eDebug? If not I can simply remove the call (now that I know it works)

**Comment by jbleyel** [comment]
The log is not the only problem, You call the function has_external_rotor more than 2000 times and this is not correct.

**Comment by olivluca** [comment]
I call it just once, it's eDVBSatelliteEquipmentControl::prepare that's called thousands of times and I that's out of my control.

**Comment by jbleyel** [comment]
Looks like that :
eDVBSatelliteEquipmentControl::prepare was called 2000 times
Probably a channel scan or some extra plugin.

I have got the log from a user and not on my box.

**Comment by olivluca** [comment]
So, do you want me to remove the debug line or can I leave it?

**Comment by jbleyel** [comment]
We need to find the root cause of calling eDVBSatelliteEquipmentControl::prepare so often.
Looks like not your problem.

**Comment by olivluca** [comment]
Maybe it's the EPGImporter plugin?
See my pull request #2125

**Comment by jbleyel** [comment]
!simulated is after line 514.
maybe this can help:

`			bool useExternalRotorCmd = !simulate && has_external_rotor(slot_id_to_fe_id(slot_id));
`

**Comment by olivluca** [comment]
or simply change eDebug to eDebugNoSimulate

**Comment by jbleyel** [comment]
no .. has_external_rotor should only called if simulate is false.

**Comment by jbleyel** [comment]
Please check this : 

https://github.com/openatv/enigma2/commit/8f006b0500dd481da0eb6461f26da4221781b722

**Comment by jbleyel** [comment]
Yep your change is the same like mine.

**Comment by jbleyel** [comment]
You can pull.

**Comment by olivluca** [comment]
I'm building it, I'd prefer to pull once tested

**Comment by jbleyel** [comment]
good idea !!
Please also test EPGImporter

**Comment by olivluca** [comment]
Tested, no spam with EPGImporter (though I don't think that was calling eDVBSatelliteEquipmentControl::prepare that often).
I'm going to open a pull request.
I still think that the "simulate" flag should be taken into account to avoid moving a diseqc rotor (but, as I said before, since I don't have one I won't touch that part).
