### ISSUE TITLE
Dish.py crash log

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#228]
<?xml version="1.0" encoding="utf-8"?>
<openATV>
	<enigma2>
		<crashdate>Втр Авг 11 12:16:42 2015</crashdate>
		<compiledate>Aug 11 2015</compiledate>
		<contactemail>forum at www.opena.tv</contactemail>
		
		<skin>MetrixHD/skin.MySkin.xml</skin>
		<sourcedate>2015-08-10</sourcedate>
		<version>3.0.0</version>
	</enigma2>
	<image>
		<stbmodel>duo2</stbmodel>
		<kernelversion>
			<![CDATA[
Linux vuduo2 3.13.5 #1 SMP Fri Aug 7 10:01:57 CEST 2015 mips GNU/Linux
]]>
		</kernelversion>
		<kernelcmdline>libata.force=1:1.5Gbps bmem=192M@64M bmem=384M@512M memc1=788M ubi.mtd=0 root=ubi0:rootfs rootfstype=ubifs rw rootflags=sync</kernelcmdline>
		<nimsockets>NIM Socket 0:</nimsockets>
		<imageversion>
			<![CDATA[
box_type=vuduo2
build_type=0
version=5.1
build=0
date=20150808035055
comment=openATV
target=9
creator=openATV
url=http://www.opena.tv
catalog=http://www.opena.tv
]]>
.........
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 157, in show
  File "/usr/lib/enigma2/python/Screens/Dish.py", line 96, in __onShow
  File "/usr/lib/enigma2/python/Screens/Dish.py", line 226, in getTunerName
IndexError: list index out of range

please see openPli Dish.py:
	def getTunerName(self):
		nr = self.getCurrentTuner()
		if nr is not None:
			nims = nimmanager.nimList()
			if nr < 4:
				return "".join(nims[nr].split(':')[:1])
			return " ".join((_("Tuner"),str(nr)))
		return ""

**Comment by atvcaptain** [comment]
thx for info we have change it
