### ISSUE TITLE
Mute icon should change position to prevent screen burn-in

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2290]
Even though newer technologies reduce the likelihood of damage caused by long-term on-screen graphics, there are still screens that could suffer from burn-in. Hiding the icon is not preferable in many instances.

**Comment by jbleyel** [comment]
? On my box the mute icon is not permanent

**Comment by jbleyel** [comment]
There is s setting:

"Hide mute notification" 
"If muted, hide mute icon or mute information after few seconds."
config.av.volume_hide_mute

Default is True

**Comment by wedebe** [comment]
> Hiding the icon is not preferable in many instances.

This fix still hides the icon (which means (for example), I've to check my speakers are on, or at the right input, or not mute, or the receiver's not muted).

I have what I think is a better solution for mute button hold (a feature request I've previously logged - mute for X seconds (useful for _very_ annoying adverts)). I'd like to try work that on top of the groundwork you've added here :)

**Comment by Makumbo** [comment]
> Even though newer technologies reduce the likelihood of damage caused by long-term on-screen graphics, there are still screens that could suffer from burn-in.  

Thats not logical.  
What about the service logos in the upper corner - RTL - 7 - 1 - the huge DMAX and so on.  
They are WAY more prominent.  

> could suffer from burn-in  

I don't think so...

**Comment by wedebe** [comment]
> > Even though newer technologies reduce the likelihood of damage caused by long-term on-screen graphics, there are still screens that could suffer from burn-in.
> 
> Thats not logical. What about the service logos in the upper corner - RTL - 7 - 1 - the huge DMAX and so on. They are WAY more prominent.
> 
> > could suffer from burn-in
> 
> I don't think so...

Channel identifier logos are specifically designed to reduce screen burn and they're semi-transparent.

OpenATV's default (MetrixHD) skin on the other hand, uses a fully opaque, extreme contrast, sharp-edged white-on-black image.

<img width="478" alt="" src="https://user-images.githubusercontent.com/9741693/167274772-f9486ced-3183-451e-8066-04a2e8b4249a.png">

<img width="476" alt="" src="https://user-images.githubusercontent.com/9741693/167274783-53991420-5158-42b3-8872-89fe33a98415.png">

**Comment by IanSav** [comment]
When the code is changed all skins are affected.  As the issue appears to be the Metrix MUTE icon perhaps this should be the target of any attention.  Have you considered offering openATV a modified mute icon that is less sharp/harsh, more transparent to alleviate your burn in concerns?

**Comment by Makumbo** [comment]
> Channel identifier logos are specifically designed to reduce screen burn and they're semi-transparent.  

Hmm:  

![3Sat Logo](https://user-images.githubusercontent.com/38384409/167310252-6ccf2b0e-ef6f-4150-a8e8-033bce2b3bd2.jpg)

Seems really bright.

But if there is a method to change the mute icon then lets do it... ;)

**Comment by jbleyel** [comment]
The default setting is autohide of mute icon after 2 seconds.
So why do we talk about this?

	config.av.volume_hide_mute = ConfigYesNo(default=True)

**Comment by wedebe** [comment]
> The default setting is autohide of mute icon after 3 seconds. So why do we talk about this?
> 
> ```
> config.av.volume_hide_mute = ConfigYesNo(default=True)
> ```

Hiding the icon means (for example), I've to check my speakers are on, or at the right input, or not mute, or the receiver's at a high enough volume, or not muted, and having to find and use the appropriate remote control in each case - instead of just glancing at the screen and knowing exactly what to do.

**Comment by jbleyel** [comment]
Then you need to ask the skin developer and change the image file.
If you use Metrix then you can use custom skin parts and custom icons.
