### ISSUE TITLE
[VolumeControl] `volUp`/`volDown` step/jump sizes ignored when volume < 30

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2293]
https://github.com/openatv/enigma2/blob/253a5a02f51709ff1ac8975d79f2678e97a61d3f/lib/python/Components/VolumeControl.py#L59

User-configured values for volume increment and volume step/jump sizes are not honoured when changing volume < 30.

- Logarithmic volume should be user-disablable (not all audio systems (or indeed headphones) handle lower volumes similarly)
- Logarithmic step/jump size (when enabled) should differ from increment size

**Comment by IanSav** [comment]
I must admit that this logarithmic volume functionality has caught me out.  I would like to see this go but don't have a strong enough objection to negate the wishes of others.

**Comment by wedebe** [comment]
Having done some rudimentary research, I also believe that the scale should be calculated using a formula.

https://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by wedebe** [comment]
Closing as completed, thanks!
