### ISSUE TITLE
ClearMem Plugin

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#2296]
We should add this feature from opendroid.
https://github.com/opendroid-Team/enigma2/blob/7.1/lib/python/OPENDROID/ClearMem.py

**Comment by jbleyel** [comment]
We should also think about clear memory after close of media player.

**Comment by Masta2002** [comment]
on oATV Feed there is allready a CleanMem Plugin

[enigma2-plugin-extensions-clearmem_1.10_all.zip](https://github.com/openatv/enigma2/files/8936045/enigma2-plugin-extensions-clearmem_1.10_all.zip)

**Comment by IanSav** [comment]
MENU > Information > Memory also has an option to clear memory.  (YELLOW button.)
