### ISSUE TITLE
Youtube  streams in OpenATV

### ISSUE THREAD

**Issue by rszwed987** [openatv/enigma2#2304]
Hello

How to play Youtube streams like:
"wPolsce" https://www.youtube.com/watch?v=C4sEJQjIdyo
"EWTN Polska" https://www.youtube.com/watch?v=dVaYeXbebD8

In OpenATV natively?
I heard youtube changes stream addresses frequently

**Comment by azman26** [comment]
Zapoznaj się z tymi tematami podanymi poniżej

https://www.sat-4-all.com/board/topic/301666-lista-iptv-polskie-kana%C5%82y-lokalne-i-youtube-z-epg-i-piconami/
https://www.sat-4-all.com/board/topic/336405-streamlink-4xx-na-python-3-image/

**Comment by jbleyel** [comment]
> Zapoznaj się z tymi tematami podanymi poniżej
> 
> https://www.sat-4-all.com/board/topic/301666-lista-iptv-polskie-kana%C5%82y-lokalne-i-youtube-z-epg-i-piconami/ https://www.sat-4-all.com/board/topic/336405-streamlink-4xx-na-python-3-image/

Hello @azman26 , your links are not public accessible.

**Comment by 4l3x2k** [comment]
Report your native issue here: https://github.com/zgemma-star/servicehisilicon

Issue can be closed.
