### ISSUE TITLE
[HIGH] `Flash image` broken

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2311]
Error log attached:
[enigma2_crash_1652807940.log](https://github.com/openatv/enigma2/files/8710365/enigma2_crash_1652807940.log)

**Comment by jbleyel** [comment]
This is the old version and we are nearly finished with the new FlashManager.
https://github.com/openatv/enigma2/tree/FlashManager

The old flash_online will be removed. 
The crash is already fixed in FlashManager.

**Comment by wedebe** [comment]
@jbleyel , may I suggest that affected images are removed from the update feeds until the fixed version gets released - anyone who updates to these bug versions will lose the ability to update their image unless they have another usable image slot to upgrade from or reflash their box.

**Comment by jbleyel** [comment]
This is not a major bug. The crash is based on a mount on you Box.
