### ISSUE TITLE
Version 7.1 bootlogo image file query

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2315]
Hi, I'd like to update the spinner/wait*.png files by using an element of the OATV logo. Is there somewhere I could get the original 7.1 backdrop/bootlogo.mvi image file (ideally where I can remove the background layer). I haven't been able to find even the 7.1 bootlogo/backdrop.mvi file in meta-oe recipes.

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/oe-alliance-core/tree/5.1/meta-oe/recipes-distros/openatv/bootlogo
