### ISSUE TITLE
Feature Request: `Install local extension` acts differently to PluginManager when installing picons

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2321]
The option to select picon location to install to isn't presented when installing ipk from filesystem.

However, downloading (often outdated) picon plugins through the Plugin Browser provides options.

Request: present location options when installing local picon-* extensions.

PluginBrowser.py:
```
				if self["list"].l.getCurrentSelection()[0].name.startswith("picons-"):
					supported_filesystems = frozenset(('vfat', 'ext4', 'ext3', 'ext2', 'reiser', 'reiser4', 'jffs2', 'ubifs', 'rootfs'))
					candidates = []
					import Components.Harddisk
					mounts = Components.Harddisk.getProcMounts()
					for partition in harddiskmanager.getMountedPartitions(False, mounts):
						if partition.filesystem(mounts) in supported_filesystems:
							candidates.append((partition.description, partition.mountpoint))
					if candidates:
						from Components.Renderer import Picon
						self.postInstallCall = Picon.initPiconPaths
						self.session.openWithCallback(self.installDestinationCallback, ChoiceBox, title=_("Install picons on"), list=candidates)
					return
```

<img width="366" alt="" src="https://user-images.githubusercontent.com/9741693/169669015-c6f820c2-5816-4670-b215-92f0b8cc8569.png">

**Comment by jbleyel** [comment]
This feature has ben removed and is now implemented differently.

**Comment by wedebe** [comment]
> This feature has been removed and is now implemented differently.

I noticed this change this morning, thanks!
