### ISSUE TITLE
Website link issue (picons.eu no longer as it was)

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2322]
The picons.eu domain now redirects to a sex-based domain address, so I'd suggest any and all links to it are removed or changed.

Hopefully someone has direct contact with people who manage any of the enigma2 webpages.

(This also calls into question the security of externally-hosted ipk files. If the new site owners knew how, they could create and serve a malware ipk).

**Comment by jbleyel** [comment]
Where exactly do you found the link?

**Comment by AbuBaniaz** [comment]
There are three hits on the atv forum
Needs to be updated to `https://github.com/picons/picons/releases`  The ones on github are updated every Saturday. 

Once those three links are updated, issue can be closed

**Comment by jbleyel** [comment]
These 3 hits are old posts in forum.
