### ISSUE TITLE
images.mynonpublic.com links to 10-year stale picon repo

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2323]
http://images.mynonpublic.com/openatv/7.1/index.php?open=mutant51
links to https://github.com/openatv-picons

<img width="419" alt="" src="https://user-images.githubusercontent.com/9741693/169685221-585544b7-75eb-4c63-9115-ab6674eede69.png">

Perhaps this link should be changed to
https://github.com/picons/picons
and, if anyone has access, to archive/delete the old repos.

**Comment by BliNeR-KeY** [comment]
OpenATV are image E2 Support. 
Picons are extra , no means openatv need do everything
[enigma2-plugin-extensions-mmpicons_1.2_all.ipk.zip](https://github.com/openatv/enigma2/files/8749053/enigma2-plugin-extensions-mmpicons_1.2_all.ipk.zip)
[enigma2-plugin-extensions-gioppygio_10.4_all.ipk.zip](https://github.com/openatv/enigma2/files/8749055/enigma2-plugin-extensions-gioppygio_10.4_all.ipk.zip)

Repo ( https://github.com/openatv-picons ) are open source. means you and everyone are free to update picons.
no means OpenATV update also picons.

if you search google have lot of members make personal picons and share it.
have also lot of plugins .
i'm upload 2 plugins about picons.

**Comment by formiano** [comment]
Alternatives.
https://github.com/picons/picons
You have the option to create custom servicelists.

**Comment by wedebe** [comment]
> OpenATV are image E2 Support. Picons are extra
>...
> if you search google have lot of members make personal picons and share it. have also lot of plugins . i'm upload 2 plugins about picons.

Thanks, I'm already aware of alternatives - my point is that other visitors to the page may not know there are more frequently-updated versions available.


> Alternatives. https://github.com/picons/picons You have the option to create custom servicelists.

Yep, that's the repo I linked to in my submission :)

**Comment by jbleyel** [comment]
the link in ate forum is deleted

**Comment by wedebe** [comment]
Great, thanks 🙂
