### ISSUE TITLE
Spinner logic trap

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2330]
https://github.com/openatv/enigma2/blob/6a266549d1705d1e05a9f3f3cf91df097ae4b37a/main/enigma.cpp#L189

`config.skin.primary_skin` is set to `MetrixHD/skin.MySkin.xml` by default, so `replace(value, "skin.xml", "spinner");` will never actually do a replace.

**Comment by jbleyel** [comment]
not really an issue because Metrix do not have spinner

**Comment by wedebe** [comment]
> not really an issue because Metrix do not have spinner

![Screenshot_20220527_110335](https://user-images.githubusercontent.com/9741693/170678737-4f293785-0c73-4c30-8564-892f970a4d64.jpg)

**Comment by jbleyel** [comment]
Metrix do not have "extra" spinner. The default skin spinner will be used for Metrix.

**Comment by jbleyel** [comment]
This is an issue of metrix and not of enigma core.
I will try to fix this in Metrix.
