### ISSUE TITLE
boxbranding replace with Boxinfo

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#2335]
Boxinfo Replacements:

getBrandOEM -> brand
getMachineBrand  -> displaybrand
getMachineName -> displaymodel
getMachineBuild -> model

_**getBoxType -> ? (machinebuild , machine)**_

getDisplayType -> displaytype
getImageVersion  -> imageversion
getImageBuild -> imagebuild
getImageFolder -> imagedir
getMachineUBINIZE -> ubinize
getMachineMKUBIFS -> mkubifs
getMachineMtdKernel -> mtdkernel
getMachineMtdRoot -> mtdrootfs
getMachineKernelFile -> kernelfile
getMachineRootFile -> rootfile
getImageFileSystem -> imagefs
getImageDistro -> distro

**Comment by IanSav** [comment]
[BOXINFO.txt](https://github.com/openatv/enigma2/files/8790570/BOXINFO.txt)

This is the /doc manual that I have been preparing.  Do you want to use this as the base?

**Comment by BliNeR-KeY** [comment]
getBoxType -> machinebuild

already @atvcaptain fixed it https://github.com/oe-alliance/enigma2-kernel-module/commit/b7d8e2a7d1a925fdb9533cbc4a172edf4df4506f

**Comment by AbuBaniaz** [comment]
I don't think it is a good idea to use `displaybrand` when you actually mean `machinebrand`. Nothing to do with display, just the  machine.

**Comment by IanSav** [comment]
Did you read the manual?

The "display" prefixed variables are used to display the nominated variables in the UI in a human friendly format.  For example, the variable "model" may have a value of "h7" but "displaymodel" will have "H7" as that is more like what is printed on the front panel.  Another example, the variable "distro" may contain "openatv", "openpli", "openvision" or "openvix" but the "displaydistro" variable will show "openATV", "OpenPLi", "Open Vision" or "OpenPLi" respectively.  These strings are how the data should be presented to the user in the UI.  The base versions of the data are presented in lowercase and are generally used for code logic.

**Comment by AbuBaniaz** [comment]
Just to add, if the desire is to deal with the complication with receivers being sold under different names, maybe vendor or retail maybe terms/prefixes to consider.

**Comment by jbleyel** [comment]
We can talk about this later and change the "displaybrand" and "displaymodel" to "hrbrand" and "hrmodel" if "display" is not clear.
But these variables are for developers and not for users.
And we have a documentation.

**Comment by wedebe** [comment]
> So you are saying everything that a user sees should be prefixed with display?
> 
> Please use something that is less likely to be confused with display. Somewhere along the lines, display will need to be used for display.
> 
> Actually in the example above display is now type

`friendlyMake`, `friendlyModel`, etc. would be my preference. I agree that `display...` is confusing.
