### ISSUE TITLE
Atv7.0 - Show up eListboxPythonMultiContent menu causing fatal signal / enigma crashed

### ISSUE THREAD

**Issue by mtester270** [openatv/enigma2#2340]
image: **openatv-7.0-vusolo2-20220530_usb**

**debug log:**
16:07:49.5680 PC: 005f392c
16:07:49.5681     00000000 00000001 0000001e 00000000
16:07:49.5682     00000000 7fe81490 02000000 00000000
16:07:49.5683     76a73000 00000000 76a539f8 00000001
16:07:49.5683     76a539f8 00000001 00000000 007c0000
16:07:49.5684     008c5550 00000004 000004c4 000001f1
16:07:49.5686     00000000 73d8c6e0 7688a608 76898530
16:07:49.5686     007c2104 005e8694 00000100 00000000
16:07:49.5687     76a6faf0 7fe81478 00000000 005e6fcc
16:07:49.5698 Backtrace:
16:07:49.5706 enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x47BEA8]
16:07:49.5716 enigma2(_ZN7eWidget4hideEv) [0x5F392C]
16:07:49.5724 enigma2(_ZN8eListbox15updateScrollBarEv) [0x5E6FCC]
16:07:49.5732 enigma2(_ZN8eListbox13moveSelectionEl) [0x5E7768]
16:07:49.5741 enigma2(_ZN8eListbox10entryResetEb) [0x5E80EC]
16:07:49.5749 enigma2(_ZN26eListboxPythonMultiContent7setListE9ePyObject) [0x5EC828]
16:07:49.5758 enigma2(n/a) [0x617C9C]
16:07:49.5762 /usr/lib/libpython3.9.so.1.0(n/a) [0x7689860C]
16:07:49.5763 -------FATAL SIGNAL
16:07:53.2894 [gRC] Warning: Main thread is busy, displaying spinner!

**Comment by jbleyel** [comment]
This issue is fixed.
