### ISSUE TITLE
Streamlinkwrapper does not work with "okru" plugin

### ISSUE THREAD

**Issue by azman26** [openatv/enigma2#2345]
"Okru" plugin are functional and work in streamlink.
Verified on version 4.0.1 under Windows.

The problem is that streamlinkwrapper do not work properly with these plugin on Enigma2.
No image appears on the screen.

streamlink://https://ok.ru/live/3099174903444

root@sf8008:
streamlink https://www.ok.ru/live/3099174903444 --loglevel debug
PRZYKLAD: streamlink -l debug [ -o /tmp/fileName] "url" best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.4.35-armv7l-with-glibc2.35
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.0.1+54.gd8f0e1ea.dirty
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://www.ok.ru/live/3099174903444
[cli][debug]  --loglevel=debug
[cli][debug]  --hls-segment-threads=9
[cli][debug]  --http-no-ssl-verify=True
[cli][info] Found matching plugin okru for URL https://www.ok.ru/live/3099174903444
[utils.l10n][debug] Language code: en_US
Available streams: 240p (worst), 360p, 480p, 720p (best)
root@sf8008:

I don't know how to extract log from streamlinkwrapper.
Maybe someone from the OATV team will tell me how to do it.

**Comment by Billy2011** [comment]
> The problem is that streamlinkwrapper do not work properly with these plugin on Enigma2.

I think that's because Streamlink and E2 run in the same process, and on Windows, Streamlink runs in its own process.

With the modded streamlinksrv and PY3 there is the same problem.

To try, you could change the code `from socketserver import ThreadingMixIn as ForkingMixIn` to `from socketserver import ForkingMixIn` in the modded streamlinksrv.

**Comment by azman26** [comment]
@ Billy2011 thank you for your advice. After changing the entry in streamlinksrv plugin "okru" works perfectly without jams in OATV 7.1
Best regards and thank you for your knowledge and willingness to help.

**Comment by jbleyel** [comment]
> > The problem is that streamlinkwrapper do not work properly with these plugin on Enigma2.
> 
> I think that's because Streamlink and E2 run in the same process, and on Windows, Streamlink runs in its own process.
> 
> With the modded streamlinksrv and PY3 there is the same problem.
> 
> To try, you could change the code `from socketserver import ThreadingMixIn as ForkingMixIn` to `from socketserver import ForkingMixIn` in the modded streamlinksrv.

Hi @Billy2011 , can we change the import for all plugins in your streamlinksrv py3 version or is it only needed for okru?

**Comment by jbleyel** [comment]
Hi @Billy2011 , this is your code:


```
if PY2:
 	from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler
 	from SocketServer import ForkingMixIn
 else:
 	from http.server import HTTPServer, BaseHTTPRequestHandler
 	from socketserver import ThreadingMixIn as ForkingMixIn
```

**Comment by Billy2011** [comment]
> Hi @Billy2011 , can we change the import for all plugins in streamlinksrv py3 version or is it only needed for okru?

I used this import on Windows for the PY3 changes as there is no fork there. You can use `ForkingMixIn` permanently.

**Comment by aldo7410** [comment]
Hello everyone and thank you for your interest in enigma 2 and the ok.ru site...I have been having difficulty reading some videos outside of their site of course, or even more and more recently. ...I think they must have changed something, but what I don't know, it can't be read with enigma 2 or with VLC, like this one for example....
  https://ok.ru/video/281046813247
Thank you if you can help me IT pros....
Friendships...

**Comment by 4l3x2k** [comment]
I can recreate the problem.
None of the wrappers (streamlink, YTDL, YTDLP) work with the mentioned link.
The strange thing is that it works with streamlinksrv.

Until further notice, please switch to streamlinksrv. As far as I found out, it's not the user agent being sent.

**Comment by Andrew135815** [comment]
Hello,ok.ru.py python 3.12  not working Enigma 2 offline,please help,important..: streamlinksrv manualstart debug      

File "/usr/lib/python3.12/site-packages/streamlink/utils/module.py", line 34,
in exec_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3. File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3.12/site-packages/streamlink/plugins/vtvgo.py", line 13
in <module>
from streamlink.plugin.api.webbrowser.aws_waf import AWSWAF
File "/usr/lib/python3.12/site-packages/streamlink/plugin/api/webbrowser/aws_
af.py", line 6, in <module>
import trio
import trio
ModuleNotFoundError: No module named 'trio'
[streamlinksrv][debug] Arguments:
[streamlinksrv][debug] url=https://mobile.ok.ru/video/351615524467
[streamlinksrv][debug] stream=['best']
[streamlinksrv][info] Found matching plugin for URL https://mobile.ok.ru/video
351615524467
351615524467
[streamlinksrv][error] Unable to validate response text: ValidationError(xml_fin
d):
ElementPath query './/a[@data-video]' did not return an element
[streamlinksrv][debug] Send Offline clip

**Comment by jbleyel** [comment]
This needs to be fixed in streamlinksrv or streamlink.

**Comment by Andrew135815** [comment]
And what could be improved? Thank you for your help.

**Comment by Andrew135815** [comment]
This is plugin,.:

"""
$description Russian live-streaming and video hosting social platform.
$url ok.ru
$url mobile.ok.ru
$type live, vod
$metadata id
$metadata author
$metadata title
"""

import logging
import re
from urllib.parse import unquote, urlparse

from streamlink.plugin import Plugin, pluginmatcher
from streamlink.plugin.api import validate
from streamlink.stream.dash import DASHStream
from streamlink.stream.hls import HLSStream
from streamlink.stream.http import HTTPStream


log = logging.getLogger(__name__)


@pluginmatcher(
    name="default",
    pattern=re.compile(r"https?://(?:www\.)?ok\.ru/"),
)
@pluginmatcher(
    name="mobile",
    pattern=re.compile(r"https?://m(?:obile)?\.ok\.ru/"),
)
class OKru(Plugin):
    QUALITY_WEIGHTS = {
        "full": 1080,
        "1080": 1080,
        "hd": 720,
        "720": 720,
        "sd": 480,
        "480": 480,
        "360": 360,
        "low": 360,
        "lowest": 240,
        "mobile": 144,
    }

    @classmethod
    def stream_weight(cls, key):
        weight = cls.QUALITY_WEIGHTS.get(key)
        if weight:
            return weight, "okru"

        return super().stream_weight(key)

    def _get_streams_mobile(self):
        data = self.session.http.get(self.url, schema=validate.Schema(
            validate.parse_html(),
            validate.xml_find(".//a[@data-video]"),
            validate.get("data-video"),
            validate.none_or_all(
                str,
                validate.parse_json(),
                {
                    "videoName": str,
                    "videoSrc": validate.url(),
                    "movieId": str,
                },
                validate.union_get("movieId", "videoName", "videoSrc"),
            ),
        ))
        if not data:
            return

        self.id, self.title, url = data

        stream_url = self.session.http.head(url).headers.get("Location")
        if not stream_url:
            return

        return (
            HLSStream.parse_variant_playlist(self.session, stream_url)
            if urlparse(stream_url).path.endswith(".m3u8") else
            {"vod": HTTPStream(self.session, stream_url)}
        )

    def _get_streams_default(self):
        schema_metadata = validate.Schema(
            validate.parse_json(),
            {
                validate.optional("author"): validate.all({validate.optional("name"): str}, validate.get("name")),
                validate.optional("movie"): validate.all(
                    {
                        validate.optional("id"): str,
                        validate.optional("title"): str,
                    },
                    validate.union_get("id", "title"),
                ),
                validate.optional("hlsManifestUrl"): validate.url(),
                validate.optional("hlsMasterPlaylistUrl"): validate.url(),
                validate.optional("liveDashManifestUrl"): validate.url(),
                validate.optional("videos"): [validate.all(
                    {
                        "name": str,
                        "url": validate.url(),
                    },
                    validate.union_get("name", "url"),
                )],
            },
        )

        metadata, metadata_url = self.session.http.get(self.url, schema=validate.Schema(
            validate.parse_html(),
            validate.xml_find(".//*[@data-options]"),
            validate.get("data-options"),
            validate.parse_json(),
            {"flashvars": {
                validate.optional("metadata"): str,
                validate.optional("metadataUrl"): validate.all(
                    validate.transform(unquote),
                    validate.url(),
                ),
            }},
            validate.get("flashvars"),
            validate.union_get("metadata", "metadataUrl"),
        ))

        self.session.http.headers.update({"Referer": self.url})

        if not metadata and metadata_url:
            metadata = self.session.http.post(metadata_url).text

        log.trace(f"{metadata!r}")

        data = schema_metadata.validate(metadata)

        self.author = data.get("author")
        self.id, self.title = data.get("movie", (None, None))

        for hls_url in data.get("hlsManifestUrl"), data.get("hlsMasterPlaylistUrl"):
            if hls_url is not None:
                return HLSStream.parse_variant_playlist(self.session, hls_url)

        if data.get("liveDashManifestUrl"):
            return DASHStream.parse_manifest(self.session, data.get("liveDashManifestUrl"))

        return {
            f"{self.QUALITY_WEIGHTS[name]}p" if name in self.QUALITY_WEIGHTS else name: HTTPStream(self.session, url)
            for name, url in data.get("videos", [])
        }

    def _get_streams(self):
        return self._get_streams_default() if self.matches["default"] else self._get_streams_mobile()


__plugin__ = OKru

**Comment by jbleyel** [comment]
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/okru.py

**Comment by Andrew135815** [comment]
Example.: offline!Please help and plugin problem??or streamlink?

#SERVICE 5002:0:1:25c:521:d:0:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//mobile.ok.ru/video/1115050286838:Perviy Kanal HD*
#DESCRIPTION Perviy Kanal HD*
#SERVICE 5002:0:1:6:521:d:0:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//mobile.ok.ru/video/3574052691599:Rossiya 24*
#DESCRIPTION Rossiya 24*
#SERVICE 5002:0:1:0:0:0:0:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//mobile.ok.ru/video/351615524467:78 НОВОСТИ Live 
#DESCRIPTION 78 НОВОСТИ Live

**Comment by Andrew135815** [comment]
Yes sorry offline,

**Comment by jbleyel** [comment]
You are wrong here because this is not part of enigma.

Here is the plugin -> 
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/okru.py
and here is streamlinksrv -> 
https://github.com/oe-mirrors/livestreamersrv/blob/streamlinksrv/streamlinksrv

**Comment by Andrew135815** [comment]
This is plugin okay,And streamlinksrv the same.Hier Telnet add Streamlink,,serviceapp/gstplayer already ok,,and this is Telnet,and offline .:

opkg install python3-youtube-dl
opkg install python3-yt-dlp
opkg install enigma2-plugin-extensions-streamlinkwrapper
opkg install enigma2-plugin-extensions-ytdlpwrapper
opkg install enigma2-plugin-extensions-ytdlwrapper
opkg install streamlink 
opkg install streamlinksrv

**Comment by Andrew135815** [comment]
This is Telnet total error list.:

streamlinksrv manualstart debug

File "/usr/lib/python3.12/site-packages/streamlink/utils/module.py", line 34,
in exec_module
spec.loader.exec_module(mod)
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "/usr/lib/python3. File "", line 488, in call_with_frames_removed
File "/usr/lib/python3.12/site-packages/streamlink/plugins/vtvgo.py", line 13
in
from streamlink.plugin.api.webbrowser.aws_waf import AWSWAF
File "/usr/lib/python3.12/site-packages/streamlink/plugin/api/webbrowser/aws
af.py", line 6, in
import trio
import trio
ModuleNotFoundError: No module named 'trio'
[streamlinksrv][debug] Arguments:
[streamlinksrv][debug] url=https://mobile.ok.ru/video/351615524467
[streamlinksrv][debug] stream=['best']
[streamlinksrv][info] Found matching plugin for URL https://mobile.ok.ru/video
351615524467
351615524467
[streamlinksrv][error] Unable to validate response text: ValidationError(xml_fin
d):
ElementPath query './/a[@data-video]' did not return an element
[streamlinksrv][debug] Send Offline clip

**Comment by jbleyel** [comment]
Please stop posting here!

streamlink and streamlinksvr is not part of enigma .. so you are wrong here

Here is the plugin ->
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/okru.py
and here is streamlinksrv ->
https://github.com/oe-mirrors/livestreamersrv/blob/streamlinksrv/streamlinksrv
