### ISSUE TITLE
Main menu - icon

### ISSUE THREAD

**Issue by mtester270** [openatv/enigma2#2352]
Is it possible to set icon for custom plugin item which is dynamicly add to main menu? 

etc. 
PluginDescriptor(NAME, description=DESCRIPTION, where=PluginDescriptor.WHERE_MENU, fnc=menuFnc, icon="mymenuicon.png")
![IMG_20220607_213245](https://user-images.githubusercontent.com/26596112/172466968-bdcdb77b-e3cc-4a2e-9593-98676fd29814.jpg)

**Comment by jbleyel** [comment]
The upcoming menu can have an icon in the list but this isn't finished yet.

**Comment by wedebe** [comment]
> The upcoming menu can have an icon in the list but this isn't finished yet.

If menu icons are introduced, please make them a user-configurable global on/off option - there's nothing worse than a mix of icon and non-icon entries 🫣 

(OK, there are lots of worse things 🤭)
