### ISSUE TITLE
/usr/bin/grab returns all-black image on subsequent calls

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2369]
- Pause broadcast/playback

- Capture screenshot by either
  - using the OpenWebif url /grab?format=png&mode=all
  - or
  - from shell on e2 box, run `/usr/bin/grab`
- view image (whatever frame video is currently paused at)
- now repeat same step to capture screenshot
- view image (now all-black)

Expected: whatever frame video is currently paused at should be saved again, no matter how many times a screenshot is saved while the image remains the same on-screen.

I tried to work around this by adjusting e2's brightness, only to realise that process happens at a later stage.

Just to add: even showing OSD and screenshotting will capture OSD on an all-black background.

**Comment by jbleyel** [comment]
Please open the issue here -> https://github.com/oe-alliance/aio-grab
