### ISSUE TITLE
EMC: Setting EPG language: ar_AE (when user lang set to `en`)

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2384]
Debug log shows 
```
EMC: Setting EPG language: ar_AE
```
even though user-selected language is `English`

**Comment by jbleyel** [comment]
Please revert this change on your box and try again.

https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/commit/67df61d99fb01e841d3a73cd37f3b7f4b4538e0f

**Comment by wedebe** [comment]
From recollection, I believe this happened before the 11th of May but I will check your suggestion, thanks!

**Comment by jbleyel** [comment]
default (German):

EMC: Setting EPG language: de_DE

Set language to (en_us)

EMC: Setting EPG language: en_US

**Comment by jbleyel** [comment]
I cannot reproduce.

**Comment by wedebe** [comment]
> Please revert this change on your box and try again.
> 
> [oe-mirrors/e2openplugin-EnhancedMovieCenter@67df61d](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/commit/67df61d99fb01e841d3a73cd37f3b7f4b4538e0f)

This doesn't appear to have solved the problem, I'll check your recent commit now.

**Comment by wedebe** [comment]
> [oe-mirrors/e2openplugin-EnhancedMovieCenter@2641520](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/commit/2641520288c81fe02faaa5b032609ff555632c07)

I can confirm that this fixes the problem, thanks!
