### ISSUE TITLE
thay that

### ISSUE THREAD

**Issue by Makumbo** [openatv/enigma2#2391]
Still in:

This test checks whether your LAN adapter is set up for automatic IP address configuration with DHCP.
If you get a "disabled" message:
 - then your LAN adapter is configured for manual IP setup
- verify **thay** you have entered correct IP informations in the adapter setup dialog.
If you get an "enabled" message:
-verify that you have a configured and working DHCP server in your network.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/092c1fd9abc5f8b19ae7c0b25a2a95dbfd8ae868
