### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Belfagor2005** [openatv/enigma2#2396]
https://github.com/openatv/enigma2/blob/ee62afed43a9999fbaba3e7de4e69af7c2ea0e91/lib/python/Screens/CCcamInfo.py#L450

a crash on open infocccam

```
20:44:43.2300   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 256, in action
20:44:43.2331   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
20:44:43.2360   File "/usr/lib/enigma2/python/Screens/Menu.py", line 362, in okbuttonClick
20:44:43.2385   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 10, in __call__
20:44:43.2411   File "/usr/lib/enigma2/python/Screens/Menu.py", line 375, in runScreen
20:44:43.2440   File "/usr/lib/enigma2/python/Screens/Menu.py", line 386, in openDialog
20:44:43.2466   File "/usr/lib/enigma2/python/StartEnigma.py", line 153, in openWithCallback
20:44:43.2484     dialog = self.open(screen, *arguments, **kwargs)
20:44:43.2486   File "/usr/lib/enigma2/python/StartEnigma.py", line 164, in open
20:44:43.2502     dialog = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
20:44:43.2504   File "/usr/lib/enigma2/python/StartEnigma.py", line 103, in instantiateDialog
20:44:43.2517     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
20:44:43.2518   File "/usr/lib/enigma2/python/StartEnigma.py", line 125, in doInstantiateDialog
20:44:43.2532     dialog = screen(self, *arguments, **kwargs)  # Create dialog.
20:44:43.2536   File "/usr/lib/enigma2/python/Screens/CCcamInfo.py", line 393, in __init__
20:44:43.2562   File "/usr/lib/enigma2/python/Screens/CCcamInfo.py", line 450, in readConfig
20:44:43.2590 TypeError: expected str, bytes or os.PathLike object, not NoneType
20:44:43.2592 [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0xa5ee72e0>>,('OkCancelActions', 'ok')) failed)
```

regards

**Comment by jbleyel** [comment]
This can only happen if you don't have a cfg file.

**Comment by Belfagor2005** [comment]
i have a cfg file in /etc

**Comment by jbleyel** [comment]
can you please add debug print in 

`def searchConfig():
`
and 

`def confPath():
`

**Comment by jbleyel** [comment]
```
def searchConfig():
	global CFG, CFG_path
	CFG = confPath()
	CFG_path = '/var/etc'
	if CFG:
		CFG_path = dirname(CFG)
	print("[DEBGUG] searchConfig CFG=" % CFG)


def confPath():
	cmd = 'find /etc -iname "CCcam.cfg" | head -n 1'
	res = popen(cmd).read()
	if res == "":
		print("[DEBGUG] confPath None")
		return None
	else:
		print("[DEBGUG] confPath res=" % res.replace("\n", ""))
		return res.replace("\n", "")

```

**Comment by Belfagor2005** [comment]
but i don't have a .py file :(

**Comment by jbleyel** [comment]
[CCcamInfo.py.zip](https://github.com/openatv/enigma2/files/9035052/CCcamInfo.py.zip)

**Comment by jbleyel** [comment]
I need the debug log.

**Comment by Belfagor2005** [comment]
ps.: 
only from menu_cam open a ccaminfo plugin

debug error

```
17:41:22.9235 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
17:41:23.0906 [Screen] Showing screen '['Menucam', 'menu_cam', 'Menu']'.
17:41:23.1014 Traceback (most recent call last):
17:41:23.1016   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 256, in action
17:41:23.1042   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
17:41:23.1071   File "/usr/lib/enigma2/python/Screens/Menu.py", line 479, in okbuttonClick
17:41:23.1096   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 10, in __call__
17:41:23.1122   File "/usr/lib/enigma2/python/Screens/Menu.py", line 502, in runScreen
17:41:23.1148   File "/usr/lib/enigma2/python/Screens/Menu.py", line 508, in openDialog
17:41:23.1179   File "/usr/lib/enigma2/python/StartEnigma.py", line 153, in openWithCallback
17:41:23.1200     dialog = self.open(screen, *arguments, **kwargs)
17:41:23.1202   File "/usr/lib/enigma2/python/StartEnigma.py", line 164, in open
17:41:23.1220     dialog = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
17:41:23.1221   File "/usr/lib/enigma2/python/StartEnigma.py", line 103, in instantiateDialog
17:41:23.1235     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
17:41:23.1237   File "/usr/lib/enigma2/python/StartEnigma.py", line 125, in doInstantiateDialog
17:41:23.1252     dialog = screen(self, *arguments, **kwargs)  # Create dialog.
17:41:23.1254   File "/usr/lib/enigma2/python/Screens/CCcamInfo.py", line 393, in __init__
17:41:23.1291     searchConfig()
17:41:23.1293   File "/usr/lib/enigma2/python/Screens/CCcamInfo.py", line 45, in searchConfig
17:41:23.1305     CFG = confPath()
17:41:23.1306   File "/usr/lib/enigma2/python/Screens/CCcamInfo.py", line 59, in confPath
17:41:23.1323     print("[DEBGUG] confPath res=" % res.replace("\n", ""))
17:41:23.1327 TypeError: not all arguments converted during string formatting
```

**Comment by jbleyel** [comment]
Have you used my py?

**Comment by Belfagor2005** [comment]
and from telnet

root@dinobot4kmini:~# find /etc -iname "CCcam.cfg" | head -n 1
/etc/CCcam.cfg

**Comment by Belfagor2005** [comment]
yes.. i used your py

**Comment by jbleyel** [comment]
sorry .. old version..
please replace the 2 functions from here.

**Comment by Belfagor2005** [comment]
here?

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/issues/2396#issuecomment-1172962876

**Comment by Belfagor2005** [comment]
a log debug

17:49:47.0431 [ActionMap] Keymap 'HelpActions' -> Unknown action 'select'! (Typo in keymap?)
17:49:47.0433 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
17:49:47.0573 [Menu] Menu image for menu ID 'softcam_setup' is '/usr/share/enigma2/MetriXconfluencExp/icons/softcam.png'.
17:49:47.0671 [Menu] Menu image for menu ID 'parental_setup' is '/usr/share/enigma2/MetriXconfluencExp/icons/menu_setup_parental.png'.
17:49:47.0971 [Skin] Processing screen 'Menu' from list 'Menucam, menu_cam, Menu', position=(0, 0), size=(1920x1080) for module 'Menu'.
17:49:47.1377 [AVSwitch] reading edid modes failed, using all modes
17:49:47.1389 [AVSwitch] reading _preferred modes:  ['2160p24', '2160p25', '2160p30', '1080p', '1080p50', '1080p30', '1080p25', '1080p24', '1080i', '1080i50', '720p', '720p50', '576p', '480p', 'pal', 'ntsc', '']
17:49:47.1510 [ePicLoad] setPara max-X=125 max-Y=125 aspect_ratio=1,000000 cache=1 resize=1 bg=#FF000000
17:49:47.1581 [Screen] Warning: Skin is missing element 'menuimage' in <class 'Screens.Menu.Menu'>.
17:49:47.1648 [Skin] Processing screen 'MenuSummary' from list 'MenucamSummary, menu_camSummary, MenuSummary, ScreenSummary, Menucam_summary, menu_cam_summary, Menu_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'MenuSummary'.
17:49:47.1734 [Screen] Showing screen '['MenucamSummary', 'menu_camSummary', 'MenuSummary', 'ScreenSummary', 'Menucam_summary', 'menu_cam_summary', 'Menu_summary', 'SimpleSummary']'.
17:49:47.1772 [Screen] Showing screen '['Menucam', 'menu_cam', 'Menu']'.
17:49:47.1848 [ePicLoad] decode picture... /usr/share/enigma2/MetriXconfluencExp/WeatherIcon/32.png
17:49:47.1879 !!!!!!!!!![gAccel] pal_addr2 b1a33d98 clors=74!!!!!!!!!!
17:49:47.1889 !!!!!!!!!![gAccel] pal_addr2 b1a33d98 clors=74!!!!!!!!!!
17:49:47.1897 !!!!!!!!!![gAccel] pal_addr2 b1a33d98 clors=74!!!!!!!!!!
17:49:47.1912 !!!!!!!!!![gAccel] pal_addr2 b1a33d98 clors=74!!!!!!!!!!
17:49:47.2136 [eRCDeviceInputDev] 0 160 1
17:49:47.2146 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.
17:49:47.2546 !!!!!!!!!![gAccel] pal_addr2 b1a33d98 clors=74!!!!!!!!!!
17:49:47.2562 !!!!!!!!!![gAccel] pal_addr1 b1a3f470 clors=133!!!!!!!!!!
17:49:47.5720 [eRCDeviceInputDev] 1 6c 1
17:49:47.5729 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
17:49:47.5734 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
17:49:47.5754 !!!!!!!!!![gAccel] pal_addr2 b1a33d98 clors=74!!!!!!!!!!
17:49:47.7439 [eRCDeviceInputDev] 0 6c 1
17:49:47.7456 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
17:49:48.0624 [eRCDeviceInputDev] 1 160 1
17:49:48.0633 [InfoBarGenerics] Key: 352 (Make) KeyID='KEY_OK'.
17:49:48.0638 [ActionMap] Keymap 'HelpActions' -> Unknown action 'select'! (Typo in keymap?)
17:49:48.0640 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
17:49:48.4096 [DEBUG] confPath res=/etc/CCcam.cfg
17:49:48.4100 [DEBUG] searchConfig CFG=/etc/CCcam.cfg
17:49:48.4118 [Skin] Processing screen 'CCcamInfoMain', position=(0, 0), size=(1920x1080) for module 'CCcamInfoMain'.
17:49:48.4218 [gAccel] accel alloc failed
17:49:48.4218 [gSurface] ERROR: accelAlloc failed
17:49:48.4606 [Skin] Processing screen 'SimpleSummary' from list 'CCcamInfoMain_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'SimpleSummary'.
17:49:48.4632 [Screen] Showing screen '['CCcamInfoMain_summary', 'SimpleSummary']'.
17:49:48.4641 [Screen] Showing screen 'CCcamInfoMain'.
17:49:48.4666 [eRCDeviceInputDev] 0 160 1
17:49:48.4670 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.



mmm why work now ?

**Comment by jbleyel** [comment]
Probably a timing issue if debug enabled.
Let me try something different.

**Comment by Belfagor2005** [comment]
the fact is that one day it works and another day it doesn't, really weird, it always happens after an update.
I also wanted to point out that from the Blue button, quickMenu (atvpanel) does not open

**Comment by jbleyel** [comment]
[CCcamInfo.py.zip](https://github.com/openatv/enigma2/files/9035100/CCcamInfo.py.zip)

**Comment by Belfagor2005** [comment]
same.. Ok work

18:11:34.2799 [InfoBarGenerics] Key: 401 (Break) KeyID='KEY_BLUE'.
18:11:34.3687 [ActionMap] Keymap 'InfobarExtensions' -> Action 'quickmenu'.
18:11:34.5629 [Skin] Processing screen 'QuickMenu', position=(0, 0), size=(1920x1080) for module 'QuickMenu'.
18:11:34.5910 [gAccel] accel alloc failed
18:11:34.5910 [gSurface] ERROR: accelAlloc failed
18:11:34.6012 [Skin] Warning: Attribute 'scrollbarSliderBorderColor' has been deprecated, use 'scrollbarBorderColor' instead!
18:11:34.6014 [Skin] Warning: Attribute 'scrollbarSliderBorderWidth' has been deprecated, use 'scrollbarBorderWidth' instead!
18:11:34.6016 [Skin] Warning: Attribute 'scrollbarSliderForegroundColor' has been deprecated, use 'scrollbarForegroundColor' instead!
18:11:34.6076 [Skin] Processing screen 'QuickMenu_summary' from list 'QuickMenu_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'SimpleSummary'.
18:11:34.6130 [Screen] Showing screen '['QuickMenu_summary', 'SimpleSummary']'.
18:11:34.6149 [Screen] Showing screen 'QuickMenu'.
18:11:34.6215 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6228 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6232 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6235 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6246 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6254 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6258 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6265 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:34.6275 !!!!!!!!!![gAccel] pal_addr2 b1933898 clors=74!!!!!!!!!!
18:11:35.1865 [eRCDeviceInputDev] 1 6c 1
18:11:35.1874 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:35.1880 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:35.1915 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.1924 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.1932 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.1949 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.1975 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.3585 [eRCDeviceInputDev] 0 6c 1
18:11:35.3593 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:35.8363 [eRCDeviceInputDev] 1 6a 1
18:11:35.8377 [InfoBarGenerics] Key: 106 (Make) KeyID='KEY_RIGHT'.
18:11:35.8384 [ActionMap] Keymap 'NavigationActions' -> Action 'right'.
18:11:35.8397 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.8405 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.8412 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.8417 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:35.8423 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:36.0081 [eRCDeviceInputDev] 0 6a 1
18:11:36.0089 [InfoBarGenerics] Key: 106 (Break) KeyID='KEY_RIGHT'.
18:11:36.2460 [eRCDeviceInputDev] 1 6c 1
18:11:36.2471 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:36.2478 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:36.2490 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:36.2499 !!!!!!!!!![gAccel] pal_addr2 b1928fe8 clors=74!!!!!!!!!!
18:11:36.4205 [eRCDeviceInputDev] 0 6c 1
18:11:36.4214 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:36.6157 [eRCDeviceInputDev] 1 160 1
18:11:36.6165 [InfoBarGenerics] Key: 352 (Make) KeyID='KEY_OK'.
18:11:36.6170 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
18:11:36.7876 [eRCDeviceInputDev] 0 160 1
18:11:36.7884 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.
18:11:36.7890 [ActionMap] Keymap 'OkCancelActions' -> Unknown action 'OK'! (Typo in keymap?)
18:11:39.8542 [eRCDeviceInputDev] 1 ae 1
18:11:39.8550 [InfoBarGenerics] Key: 174 (Make) KeyID='KEY_EXIT'.
18:11:40.0261 [eRCDeviceInputDev] 0 ae 1
18:11:40.0270 [InfoBarGenerics] Key: 174 (Break) KeyID='KEY_EXIT'.
18:11:40.0275 [ActionMap] Keymap 'OkCancelActions' -> Action 'cancel'.
18:11:40.0311 [Screen] Showing screen 'InfoBarSummary'.
18:11:40.0450 [Screen] Showing screen 'InfoBar'.
18:11:40.1332 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1380 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1391 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1400 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1407 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1413 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1420 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1427 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1433 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.1438 !!!!!!!!!![gAccel] pal_addr2 b194f3f0 clors=192!!!!!!!!!!
18:11:40.3349 !!!!!!!!!![gAccel] pal_addr2 b1941938 clors=133!!!!!!!!!!
18:11:41.0942 [eRCDeviceInputDev] 1 ae 1
18:11:41.0954 [InfoBarGenerics] Key: 174 (Make) KeyID='KEY_EXIT'.
18:11:41.0962 [ActionMap] Keymap 'HelpActions' -> Unknown action 'cancel'! (Typo in keymap?)
18:11:41.0964 [ActionMap] Keymap 'InfobarShowHideActions' -> Action 'hide'.
18:11:41.2654 [eRCDeviceInputDev] 0 ae 1
18:11:41.2665 [InfoBarGenerics] Key: 174 (Break) KeyID='KEY_EXIT'.
18:11:42.2333 [eRCDeviceInputDev] 1 8b 1
18:11:42.2345 [InfoBarGenerics] Key: 139 (Make) KeyID='KEY_MENU'.
18:11:42.2350 [ActionMap] Keymap 'InfoBarMenuActions' -> Action 'showMenu'.
18:11:42.2359 [Menu] Found menu entry 'Main Menu' (1 of 1).
18:11:42.2843 [Skin] Processing screen 'menu_mainmenu' from list 'Menumainmenu, menu_mainmenu, Menu', position=(0, 0), size=(1920x1080) for module 'Menu'.
18:11:42.3239 [AVSwitch] reading edid modes failed, using all modes
18:11:42.3248 [AVSwitch] reading _preferred modes:  ['2160p24', '2160p25', '2160p30', '1080p', '1080p50', '1080p30', '1080p25', '1080p24', '1080i', '1080i50', '720p', '720p50', '576p', '480p', 'pal', 'ntsc', '']
18:11:42.3363 [ePicLoad] setPara max-X=125 max-Y=125 aspect_ratio=1,000000 cache=1 resize=1 bg=#FF000000
18:11:42.3430 [Screen] Warning: Skin is missing element 'menuimage' in <class 'Screens.Menu.Menu'>.
18:11:42.3494 [Skin] Processing screen 'MenuSummary' from list 'MenumainmenuSummary, menu_mainmenuSummary, MenuSummary, ScreenSummary, Menumainmenu_summary, menu_mainmenu_summary, Menu_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'MenuSummary'.
18:11:42.3575 [Screen] Showing screen '['MenumainmenuSummary', 'menu_mainmenuSummary', 'MenuSummary', 'ScreenSummary', 'Menumainmenu_summary', 'menu_mainmenu_summary', 'Menu_summary', 'SimpleSummary']'.
18:11:42.3613 [Screen] Showing screen '['Menumainmenu', 'menu_mainmenu', 'Menu']'.
18:11:42.3682 [ePicLoad] decode picture... /usr/share/enigma2/MetriXconfluencExp/WeatherIcon/32.png
18:11:42.3702 !!!!!!!!!![gAccel] pal_addr2 b19123d8 clors=74!!!!!!!!!!
18:11:42.3719 !!!!!!!!!![gAccel] pal_addr2 b19123d8 clors=74!!!!!!!!!!
18:11:42.3728 !!!!!!!!!![gAccel] pal_addr2 b19123d8 clors=74!!!!!!!!!!
18:11:42.3743 !!!!!!!!!![gAccel] pal_addr2 b19123d8 clors=74!!!!!!!!!!
18:11:42.4050 [eRCDeviceInputDev] 0 8b 1
18:11:42.4060 [InfoBarGenerics] Key: 139 (Break) KeyID='KEY_MENU'.
18:11:42.4540 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:42.4555 !!!!!!!!!![gAccel] pal_addr1 b193c3d0 clors=133!!!!!!!!!!
18:11:42.9629 [eRCDeviceInputDev] 1 6c 1
18:11:42.9638 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:42.9643 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:42.9665 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:43.1768 [eRCDeviceInputDev] 2 6c 1
18:11:43.1778 [InfoBarGenerics] Key: 108 (Repeat) KeyID='KEY_DOWN'.
18:11:43.1782 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:43.1802 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:43.3909 [eRCDeviceInputDev] 2 6c 1
18:11:43.3923 [InfoBarGenerics] Key: 108 (Repeat) KeyID='KEY_DOWN'.
18:11:43.3929 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:43.3948 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:43.5627 [eRCDeviceInputDev] 0 6c 1
18:11:43.5635 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:44.3920 [eRCDeviceInputDev] 1 160 1
18:11:44.3931 [InfoBarGenerics] Key: 352 (Make) KeyID='KEY_OK'.
18:11:44.3936 [ActionMap] Keymap 'HelpActions' -> Unknown action 'select'! (Typo in keymap?)
18:11:44.3938 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
18:11:44.7782 [Skin] Processing screen 'menu_setup' from list 'Menusetup, menu_setup, Menu', position=(0, 0), size=(1920x1080) for module 'Menu'.
18:11:44.7894 [AVSwitch] reading edid modes failed, using all modes
18:11:44.7899 [AVSwitch] reading _preferred modes:  ['2160p24', '2160p25', '2160p30', '1080p', '1080p50', '1080p30', '1080p25', '1080p24', '1080i', '1080i50', '720p', '720p50', '576p', '480p', 'pal', 'ntsc', '']
18:11:44.7931 [ePicLoad] setPara max-X=125 max-Y=125 aspect_ratio=1,000000 cache=1 resize=1 bg=#FF000000
18:11:44.7950 [Screen] Warning: Skin is missing element 'menuimage' in <class 'Screens.Menu.Menu'>.
18:11:44.7971 [Skin] Processing screen 'MenuSummary' from list 'MenusetupSummary, menu_setupSummary, MenuSummary, ScreenSummary, Menusetup_summary, menu_setup_summary, Menu_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'MenuSummary'.
18:11:44.7994 [Screen] Showing screen '['MenusetupSummary', 'menu_setupSummary', 'MenuSummary', 'ScreenSummary', 'Menusetup_summary', 'menu_setup_summary', 'Menu_summary', 'SimpleSummary']'.
18:11:44.8005 [Screen] Showing screen '['Menusetup', 'menu_setup', 'Menu']'.
18:11:44.8031 [ePicLoad] decode picture... /usr/share/enigma2/MetriXconfluencExp/WeatherIcon/32.png
18:11:44.8033 [eRCDeviceInputDev] 0 160 1
18:11:44.8036 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.
18:11:44.8038 [eRCDeviceInputDev] 1 6c 1
18:11:44.8040 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:44.8041 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:44.8052 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:44.8059 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:44.8063 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:44.8075 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:44.8378 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:44.8385 !!!!!!!!!![gAccel] pal_addr1 b194a888 clors=133!!!!!!!!!!
18:11:44.9459 [eRCDeviceInputDev] 2 6c 1
18:11:44.9464 [InfoBarGenerics] Key: 108 (Repeat) KeyID='KEY_DOWN'.
18:11:44.9466 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:44.9474 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:45.1178 [eRCDeviceInputDev] 0 6c 1
18:11:45.1187 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:46.0113 [eRCDeviceInputDev] 1 6c 1
18:11:46.0123 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:46.0129 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:46.0152 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:46.1846 [eRCDeviceInputDev] 0 6c 1
18:11:46.1853 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:46.4111 [eRCDeviceInputDev] 1 6c 1
18:11:46.4122 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:46.4127 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:46.4147 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:46.5830 [eRCDeviceInputDev] 0 6c 1
18:11:46.5839 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:46.7709 [eRCDeviceInputDev] 1 6c 1
18:11:46.7718 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:46.7722 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:46.7742 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:46.9427 [eRCDeviceInputDev] 0 6c 1
18:11:46.9436 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:47.1608 [eRCDeviceInputDev] 1 6c 1
18:11:47.1620 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:47.1629 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:47.1650 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:47.3325 [eRCDeviceInputDev] 0 6c 1
18:11:47.3336 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:47.5405 [eRCDeviceInputDev] 1 160 1
18:11:47.5417 [InfoBarGenerics] Key: 352 (Make) KeyID='KEY_OK'.
18:11:47.5422 [ActionMap] Keymap 'HelpActions' -> Unknown action 'select'! (Typo in keymap?)
18:11:47.5424 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
18:11:47.5797 [Skin] Processing screen 'Menu' from list 'Menucam, menu_cam, Menu', position=(0, 0), size=(1920x1080) for module 'Menu'.
18:11:47.6188 [AVSwitch] reading edid modes failed, using all modes
18:11:47.6197 [AVSwitch] reading _preferred modes:  ['2160p24', '2160p25', '2160p30', '1080p', '1080p50', '1080p30', '1080p25', '1080p24', '1080i', '1080i50', '720p', '720p50', '576p', '480p', 'pal', 'ntsc', '']
18:11:47.6316 [ePicLoad] setPara max-X=125 max-Y=125 aspect_ratio=1,000000 cache=1 resize=1 bg=#FF000000
18:11:47.6381 [Screen] Warning: Skin is missing element 'menuimage' in <class 'Screens.Menu.Menu'>.
18:11:47.6473 [Skin] Processing screen 'MenuSummary' from list 'MenucamSummary, menu_camSummary, MenuSummary, ScreenSummary, Menucam_summary, menu_cam_summary, Menu_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'MenuSummary'.
18:11:47.6571 [Screen] Showing screen '['MenucamSummary', 'menu_camSummary', 'MenuSummary', 'ScreenSummary', 'Menucam_summary', 'menu_cam_summary', 'Menu_summary', 'SimpleSummary']'.
18:11:47.6612 [Screen] Showing screen '['Menucam', 'menu_cam', 'Menu']'.
18:11:47.6694 [ePicLoad] decode picture... /usr/share/enigma2/MetriXconfluencExp/WeatherIcon/32.png
18:11:47.6719 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:47.6730 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:47.6741 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:47.6758 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:47.7123 [eRCDeviceInputDev] 0 160 1
18:11:47.7132 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.
18:11:47.7420 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:47.7435 !!!!!!!!!![gAccel] pal_addr1 b194a888 clors=133!!!!!!!!!!
18:11:48.3404 [eRCDeviceInputDev] 1 6c 1
18:11:48.3415 [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN'.
18:11:48.3421 [ActionMap] Keymap 'NavigationActions' -> Action 'down'.
18:11:48.3441 !!!!!!!!!![gAccel] pal_addr2 b1953da0 clors=74!!!!!!!!!!
18:11:48.5120 [eRCDeviceInputDev] 0 6c 1
18:11:48.5129 [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN'.
18:11:48.7999 [eRCDeviceInputDev] 1 160 1
18:11:48.8015 [InfoBarGenerics] Key: 352 (Make) KeyID='KEY_OK'.
18:11:48.8021 [ActionMap] Keymap 'HelpActions' -> Unknown action 'select'! (Typo in keymap?)
18:11:48.8024 [ActionMap] Keymap 'OkCancelActions' -> Action 'ok'.
18:11:48.8147 [Skin] Processing screen 'CCcamInfoMain', position=(0, 0), size=(1920x1080) for module 'CCcamInfoMain'.
18:11:48.9116 [Skin] Processing screen 'SimpleSummary' from list 'CCcamInfoMain_summary, SimpleSummary', position=(0, 0), size=(1x1) for module 'SimpleSummary'.
18:11:48.9198 [Screen] Showing screen '['CCcamInfoMain_summary', 'SimpleSummary']'.
18:11:48.9233 [Screen] Showing screen 'CCcamInfoMain'.
18:11:49.0008 [eRCDeviceInputDev] 0 160 1
18:11:49.0016 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.
18:11:49.0559 !!!!!!!!!![gAccel] pal_addr2 b193f870 clors=256!!!!!!!!!!


not work from blue button (quick_menu )
;)
