### ISSUE TITLE
Option to disable new menu item hint box?

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2407]
I've gone through UI settings as well as MetrixHD plugin options but can't find how to hide the new menu description section.
Is there an option? If not, could one be added, please? I love MetrixHD's clean, minimal interface.

![1_0_1F_1CEA_7F6_2_11A0000_0_0_0_20220701154546](https://user-images.githubusercontent.com/9741693/176941832-06441f64-beb4-44df-8123-858b47cf8f4c.jpeg)

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/pull/2408

**Comment by jbleyel** [comment]
https://github.com/openatv/MetrixHD/pull/502/commits/099d27c8fe07d1fdc6153e6cd05ef68acd9f1f39

**Comment by wedebe** [comment]
For reference:

![disable-menu-hints](https://user-images.githubusercontent.com/9741693/178971865-f977930a-faa1-42f9-8404-f6dc3d56dd72.jpeg)
