### ISSUE TITLE
PiP or PIP?

### ISSUE THREAD

**Issue by Makumbo** [openatv/enigma2#2410]
What is 'right' - "**PiP**" or "**PIP**"?

**Wikipedia says "PiP"** (Picture-in-picture).
(Well, must it then not be accurate "Picture-in-**P**icture"? Or "Pi**p**"?)

Anyway, **official it is "PiP"**.

But in the pot file I counted something like **38 "PiP"** and **21 "PIP"** like:
" (PiP)"
"12bit 4:2:0/4:2:2 no PIP"
"Disable PIP and try again?\n"
"Behavior of 0 key in PiP-mode"
"Big PiP"
"Box or driver is not support Quad PiP."
"Cascade PiP"
"Choose what you want the button '0' to do when PIP is active."
"Close PiP on exit"

and so on...

**Comment by IanSav** [comment]
"PiP" is the commonly accepted name.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/3cfb4e05d50900e0d32dd3fdacf70b064032f3d4
