### ISSUE TITLE
Sort Extensions not working

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#2414]
https://github.com/openatv/enigma2/blob/7.0/lib/python/Screens/InfoBarGenerics.py#L3161

https://github.com/openatv/enigma2/blob/7.0/lib/python/Screens/InfoBarGenerics.py#L3212

**Comment by jbleyel** [comment]
Crash on playback if sort enabled via #2433.

15:17:53.5276   File "/usr/lib/enigma2/python/StartEnigma.py", line 75, in processDelay
15:17:53.5281     callback(*retVal)
15:17:53.5282   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 261, in movieSelected
15:17:53.5286   File "/usr/lib/enigma2/python/StartEnigma.py", line 164, in open
15:17:53.5290     dialog = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
15:17:53.5290   File "/usr/lib/enigma2/python/StartEnigma.py", line 103, in instantiateDialog
15:17:53.5294     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
15:17:53.5294   File "/usr/lib/enigma2/python/StartEnigma.py", line 125, in doInstantiateDialog
15:17:53.5299     dialog = screen(self, *arguments, **kwargs)  # Create dialog.
15:17:53.5300   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 534, in __init__
15:17:53.5303   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3450, in __init__
15:17:53.5306   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3167, in addExtension
15:17:53.5309   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3165, in sortExtensions
15:17:53.5312   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3477, in getTogglePipzapName
15:17:53.5315 AttributeError: 'MoviePlayer' object has no attribute 'servicelist'
15:17:53.5316 [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session object at 0xb0930730>>,()) failed)

**Comment by GhostofGeeeee** [comment]
Permalinks
https://github.com/openatv/enigma2/blob/3cfb4e05d50900e0d32dd3fdacf70b064032f3d4/lib/python/Screens/InfoBarGenerics.py#L3161
https://github.com/openatv/enigma2/blob/3cfb4e05d50900e0d32dd3fdacf70b064032f3d4/lib/python/Screens/InfoBarGenerics.py#L3212
