### ISSUE TITLE
FCC no teletext on some channels, on some channels wrong video or audio

### ISSUE THREAD

**Issue by 420Dope** [openatv/enigma2#2422]
On some channels if FCC is enabled, teletext it not working.
https://www.opena.tv/vu-/59508-vu-oe-fast-channel-change-deutsch-diskussionsthread-3.html#post505123

And also on some channels, the video or audio is not from the correct channel. Maybe this is helpful.
https://www.opena.tv/openatv-7-1-py3-10-openssl-3-0-insider/58918-fcc-plugin-oe-6.html#post505728

**Comment by jbleyel** [comment]
I think we cannot fix this because this is a driver issue and there will be no driver update in the future.
