### ISSUE TITLE
[EPGCache] search() should accept a convertFunc

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2423]
https://github.com/openatv/enigma2/blob/0b591d3be139f89f1f3f8f41fab08d64eaa6130f/lib/dvb/epgcache.cpp#L2423

`lookupEvent` accepts a custom conversion function which `search` currently does not.
https://github.com/openatv/enigma2/blob/0b591d3be139f89f1f3f8f41fab08d64eaa6130f/lib/dvb/epgcache.cpp#L1658

Would it be possible to add this to `search`, to make the result set consistent with `lookupEvent`?

**Comment by wedebe** [comment]
> Who is using this crap and where?

Me 😬

Here:
https://github.com/wedebe/e2openplugin-OpenWebif/blob/abba33c4173b734db732753a403f902095e3eaf0/plugin/controllers/epg.py#L161

It helps avoid an additional iteration through event lists as each result is built at the time of lookup.

**Comment by jbleyel** [comment]
Except you make the convert in c.

**Comment by jbleyel** [comment]
You move the overhead to swig. This may not help and can be much worse.

**Comment by wedebe** [comment]
> You move the overhead to swig. This may not help and can be much worse.

Just curious, and from a learning point of view - why is swig worse?

**Comment by jbleyel** [comment]
You can compare the difference using cProfile.
