### ISSUE TITLE
Dinobot Crash on this line

### ISSUE THREAD

**Issue by Belfagor2005** [openatv/enigma2#2452]
https://github.com/openatv/enigma2/blob/a564743ada5cbc5bc111e3856fa1cbcf144f84d9/lib/python/Screens/Timeshift.py#L83

the timeshif menu now works for me, 
I have paused this code and now work all functions on my box

https://www.opena.tv/sezione-italiana/59406-timeshift-nessun-movimento-selezione-3.html#post508196

**Comment by jbleyel** [comment]
Can we close this?

**Comment by Belfagor2005** [comment]
Yes 
Thank's
