### ISSUE TITLE
Question: Translation process for .xml & .py files

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2470]
A bunch of translation work I previously did was lost when Weblate was implemented. This was because I had translated the US_EN po file (which no longer exists) and not the source.

I'm keen to re-implement the changes I had made, but want to make sure I do it in a way that follows the new process and allows Weblate to do its thing.

Could we get an entire step-by-step process (including scripts that need to be run, .pot file management, commit/push, where Weblate gets involved) of:
- changing a text string in a .xml file
- changing a text string in a .py file

**Comment by jbleyel** [comment]
Step 1: create a new branch
Step 2: change/fix the string in xml/py
Step 3: apply this change in POT and in all PO files
Step 4: tell me when you are finished

CAUTION .. don't change strings with line breaks for now

Info : I'm, also working on this.

Please send me your mail address.

**Comment by jbleyel** [comment]
This is part of this issue -> https://github.com/openatv/enigma2/issues/1789
