### ISSUE TITLE
MiniDLNA Settings menu page `Save` button doesn't follow Green button standard

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2475]
`Red` is normally used to `Close`/`Cancel`, but in this case it's `Save`

Expected: Red: `Cancel` | Green: `Save` | Yellow: `Shares`

[OATV7.0]

![1_0_1_196A_7E6_2_11A0000_0_0_0_20220816230850](https://user-images.githubusercontent.com/9741693/184994247-46a76c76-9400-45b5-b279-b403312d59b3.jpeg)

**Comment by jbleyel** [comment]
We plan to refactor all Network Settings Screens like MiniDLNA.

**Comment by jbleyel** [comment]
This will be covered by : https://github.com/openatv/enigma2/issues/2476
