### ISSUE TITLE
MiniDLNA Settings page text `:` placement

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2476]
Probably more skin-related, but the tickboxes here are left-aligned; the semi-colons are right of text labels.

Expected: Colons should not appear beside tickboxes (also suitable for skins where tickboxes follow labels).

[OATV7.0]

![1_0_1_196A_7E6_2_11A0000_0_0_0_20220816231320](https://user-images.githubusercontent.com/9741693/184994803-181a09a4-dff8-468a-aa0e-da6377a36f45.jpeg)

**Comment by jbleyel** [comment]
We plan to refactor all Network Settings Screens like MiniDLNA.

**Comment by jbleyel** [comment]
The Screen has been changed.
