### ISSUE TITLE
`Welcome to OpenATV` text should appear in secondary/accent colour

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2477]
I don't have yellow set for any skin elements, I would expect in my case a light grey.

![1_0_1_196A_7E6_2_11A0000_0_0_0_20220816230710](https://user-images.githubusercontent.com/9741693/184994981-e130baa5-c45f-47a0-8060-d03dbee10d6d.jpeg)

[OATV7.0]

**Comment by jbleyel** [comment]
The colors are here -> 

https://github.com/openatv/MetrixHD/blob/dev/usr/share/enigma2/MetrixHD/skin.xml#L311
