### ISSUE TITLE
[EPGCache] `PARTIAL_DESCRIPTION_SEARCH` seems to be missing from `if` check

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2488]
While testing OpenWebif's EPG search, I've found that searching EPG by description returns no results.

https://github.com/openatv/enigma2/blob/4bdfefadb6261b9e3223bca829230c694727a86f/lib/dvb/epgcache.cpp#L2533

The subsequent switch case, however, references `PARTIAL_DESCRIPTION_SEARCH`
https://github.com/openatv/enigma2/blob/4bdfefadb6261b9e3223bca829230c694727a86f/lib/dvb/epgcache.cpp#L2556

**Comment by jbleyel** [comment]
it's here -> 
https://github.com/openatv/enigma2/blob/4bdfefadb6261b9e3223bca829230c694727a86f/lib/dvb/epgcache.cpp#L2648

**Comment by jbleyel** [comment]
The debug line is wrong!

**Comment by wedebe** [comment]
Ah, I do get the `[eEPGCache] lookup events with 'click' in content (case insensitive)` message. But zero results for events I know for a fact are in the EPG.

**Comment by jbleyel** [comment]
Do you get this?
https://github.com/openatv/enigma2/blob/4bdfefadb6261b9e3223bca829230c694727a86f/lib/dvb/epgcache.cpp#L2658

**Comment by wedebe** [comment]
Yes, but nothing beyond that, and `None` result

**Comment by jbleyel** [comment]
This request is working on my box.

/ajax/epgdialog?sstr=click&full=1

**Comment by wedebe** [comment]
Ah ok, then I've found a (different) bug!
