### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by rchovan** [openatv/enigma2#249]
Hi, 
I'm running ATV5.1. I make  update  aprox. once in a week. After update this week is CPU load on 100%. I have tried 2 more updates every day. GUI freeze and does not respond, but stream is still running. I have only one option, login to shell an pkill enigma2. 

My STB is Xpeed LX3.

**Comment by atvcaptain** [comment]
then box freeze , make a dmesg and post output here, fist update to a image after 6.10
