### ISSUE TITLE
Audio Sync

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#2519]
This is available in the audio section when watching satellite channels, but it disappears from the menu when watching IPTV channels. Its with IPTV channels that this feature is really needed and is very rarely needed if ever with satellite channels.

So can this feature be made available to any IPTV channels in the userbouquets too ?

**Comment by jbleyel** [comment]
I have installed the audio_sync plugin and then switched to a IPTV channel and then press yellow ..
I can see the audio sync item.

**Comment by jbleyel** [comment]
Hi @ian10951, Can we close this?

**Comment by ian10951** [comment]
Yes jbleyel

I forget how I resolved it, but its now no longer an issue.
