### ISSUE TITLE
Event time Start and End  for Listboxservice  And Position  Event_progress_bar Top left,right , Bottom left,right

### ISSUE THREAD

**Issue by OpenVu** [openatv/enigma2#2538]
it is Possible To Add  Option For 

1 -Event time Start ,End Time in Listboxservice  
2 -Position  Event_progress_bar  [Top left,right , Bottom left,right]

Like [this]
https://j.top4top.io/p_24425tewg1.png

**Comment by jbleyel** [comment]
What Skin you are using?

**Comment by OpenVu** [comment]
Original Skin OpenATV [Metrix]

**Comment by jbleyel** [comment]
Please provide more detailed info what you wanna have?

**Comment by OpenVu** [comment]
I want to show the start event and the end event in the listboxservice as it is in the image I attached to you + I want to move the event_progress_bar just below the event_description in Show_twoLine Mode

**Comment by jbleyel** [comment]
You can ask the VTi developer to make the code open and then we can implement the feature.
