### ISSUE TITLE
"Time Shift" or "time shift"?

### ISSUE THREAD

**Issue by Makumbo** [openatv/enigma2#2547]
"**Time Shift**" or "**time shift**"?
Examples:
msgid "No **time shift** found to save as recording!"
msgid "Playback, Recording & **Time Shift**"
msgid "Saving **time shift** files"
msgid "Select **Time Shift** Location"
The file system on your **time shift** device does not support hard links.
msgid "**Time Shift** Settings"
msgid "**Time shift** buffer delete after zap"

**Comment by jbleyel** [comment]
time shift im Satz

Time shift am Anfang

Time Shift im Menü

**Comment by IanSav** [comment]
"No time shift found to save as recording!" could be better expressed as "No time shift buffer found to save as recording!"

"The file system on your time shift device does not support hard links." could be better expressed as "The file system on your time shift buffer storage device does not support hard links."

I agree with the explanations provided by @jbleyel.

**Comment by Makumbo** [comment]
And I agree - now, after explaining - with both of you.
