### ISSUE TITLE
[BackupRestore] Please add commandline-option 

### ISSUE THREAD

**Issue by MegaV0lt** [openatv/enigma2#2585]
Please add commandline-option for the settingsbackup to be startet via cron. 

Would be very helpful, because the only backup that works is the one witch is done automaticly

**Comment by geeeeeeeeeee** [comment]
You need help to create a .sh?
[There you can find the default paths.](https://github.com/openatv/enigma2/blob/f68b5e544340dd07f49cd2764020b6f7e37f2e72/lib/python/Plugins/SystemPlugins/SoftwareManager/BackupRestore.py#L43)

**Comment by MegaV0lt** [comment]
I know. Thank. No need anymore for backup.
