### ISSUE TITLE
Filecomander Ordner verschieben.

### ISSUE THREAD

**Issue by jogibaer1948** [openatv/enigma2#2592]
Wenn man im Filecomander einen Ordner zur anderen Seite verschieben will und der Ordner ist schon vorhanden. Geschieht troz meldung, vorhandenen Ordner Überschreiben, nichts.

**Comment by jbleyel** [comment]
Bist du sicher das das schon mal funktioniert hat?

**Comment by jogibaer1948** [comment]
Ja, da ich viel so gearbeitet habe. Ixh nutze nur den zum verwalten meiner box. Aber es geht auch in 6.4 nicht mehr,aber da war ich auch länger nicht mehr.
