### ISSUE TITLE
Filecomander fehlende icons und ..

### ISSUE THREAD

**Issue by jogibaer1948** [openatv/enigma2#2593]
Im Filecomander werden verschiedene icons von Dateien nicht mehr angezeigt. Die angezeigt werden sind schwer zu erkennen.
![1_0_19_5274_41D_1_C00000_0_0_0_20220929190052](https://user-images.githubusercontent.com/108607229/193094241-9c03a9f4-10e6-4bd4-a28a-a5bcfc7b1f92.jpg)
![1_0_19_EF10_421_1_C00000_0_0_0_20220929190319](https://user-images.githubusercontent.com/108607229/193094249-f1efe22c-3f48-4463-a9e5-bdc6410963b2.jpg)

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/oe-alliance-e2-skindefault/commit/c41e7be80e0bea886af212c4c2c44ed4b5684e37

**Comment by jogibaer1948** [comment]
Ich würde mir die Ordner icons der übersicht wegen in einer farbe wünschen. Weis find ich da unpassend.

**Comment by jbleyel** [comment]
Das Weisse Bild für Ordner wird auch noch an vielen anderen Stellen benutzt, dies währe dann auch farbig und da passt es nicht. Es gibt kein extra Ordner Bild für FileCommander.

**Comment by jogibaer1948** [comment]
Wo werden die den noch angezeigt? In all meinen ftp programmen werden Ordner in gelb dagestellt und im filecomander auch schon immer. Totalcomander zeigt die auch so an. Wie kommt man da auf weis?
![Screenshot_20220915-113347](https://user-images.githubusercontent.com/108607229/193424415-d72fd02e-0f32-48ac-872d-90dd46e4624a.png)

**Comment by jogibaer1948** [comment]
![Screenshot_20221001-210553](https://user-images.githubusercontent.com/108607229/193424513-4df5b231-37d7-4f53-a6a0-4a27c7c6753b.png)

**Comment by jbleyel** [comment]
Überall wo ein Verzeichnis angezeigt wird.
z.B. bei der Auswahl vom Timerverzeichnis

**Comment by jogibaer1948** [comment]
Das geht für mich in die falsche Richtung, da werd ich mich nie dran gewöhnen. Und hatte seinen grund das bei ftp browser das so allgemeine dagestellt wird. Was juckt mich da die z.b. mediaplayer ansicht. Manches kann auch mal einfach so bleiben wie es ist.

**Comment by jogibaer1948** [comment]
Mit einem skin vom Lutz sind sie auch nicht weis. Muss ich von metrix weg das sich die Ordner absetzen?
![filecommander](https://user-images.githubusercontent.com/108607229/193427601-fa7d6df5-e6e6-4fa6-b90e-7ab0c23c27c1.jpg)

**Comment by jbleyel** [comment]
Das Thema ist hier falsch, denn das ist ein Skin Problem und kein enigma Problem.

**Comment by jogibaer1948** [comment]
Danke,so gefällt mir das.
