### ISSUE TITLE
Umschalttimer 

### ISSUE THREAD

**Issue by jogibaer1948** [openatv/enigma2#2594]
Wenn man im Radiomodus einen Timer zum umschalten setzt und bis dahin TV schaut kommt das dabei raus.
![1_0_1_300_7_85_C00000_0_0_0_20220929193434](https://user-images.githubusercontent.com/108607229/193102978-124870be-387e-4bf4-89c6-ee5df97d34c9.jpg)

**Comment by geeeeeeeeeee** [comment]
https://www.opena.tv/allgemeine-image-informationen/60670-umschalttimer-sender-im-alle-ordner.html

**Comment by geeeeeeeeeee** [comment]
closed aber nicht gelöst!!

**Comment by jogibaer1948** [comment]
Hast ja recht, hier gehts weiter.
https://www.opena.tv/allgemeine-image-informationen/60670-umschalttimer-sender-im-alle-ordner-new-post.html

**Comment by jogibaer1948** [comment]
Jetzt geht auch das setzen im fav. Bouquet nicht mehr richtig selbst wenn man dort einen sender gugt. Das ging bis jetzt. Nun schaltet er auch in all tv um.

**Comment by jogibaer1948** [comment]
Bis her konnte ich bei meinem favoriten tv Bouquet  umschalttimer setzen z.b. auf ARD  und habe dann bis zum umschalten ZDF gegugt bis er umschaltet.  Nach dem umschalten war ich dann immer noch in meinem favoriten tv Bouquet.  Vorhin hatte ich einen für 14.00 uhr gesetzt, wurde auch umgeschaltet aber war dann in dem all tv Bouquet. 
Eben noch mal reproduziert. Das hatte ich in dem verlinktem thread auch schon geschrieben , das es nur bis dato , da zuverlässig ging. Nun nicht mehr.

**Comment by jbleyel** [comment]
Dann mal zuerst reflash von 7.1 machen und prüfen ob es geht.

**Comment by jogibaer1948** [comment]
Da hatte ich heute schon 2 mal gemacht. Backups bis 19.10 zurück wo es noch geht. Weil auch noch ein anderes problem mit der radio fav da war. Aber das ist ein neues thema. Bin für heute satt mit flashen und testen von atv.

**Comment by jbleyel** [comment]
Wie ist der Stand?

**Comment by geeeeeeeeeee** [comment]
Open!

**Comment by jbleyel** [comment]
Ich kann den Fehler nicht nachstellen, daher brauche ich mehr Details.

**Comment by 4l3x2k** [comment]
Ich kann den Fehler auch nicht mehr reproduzieren.

* TV schauen
* In das Radio Bouquet wechseln und einen Umschalttimer für einen beliebigen Radiosender setzen (Uhrzeit kann angepasst werden)
* In das TV Bouquet wechseln und einen TV Sender einschalten
* Warten bis der Umschalttimer aktiviert wird
* (a) Radiosender wird eingeschaltet und Senderliste kann geöffnet werden
* In das TV Bouquet wechseln
* (b) Letzter Sender wird eingeschaltet und Senderliste kann geöffnet werden

(a) Es wird die Senderliste des Radio Bouquet angezeigt.
(b) Es wird die Senderliste des TV Bouquet angezeigt.

Aus meiner Sicht kann das Issue geschlossen werden.

**Comment by geeeeeeeeeee** [comment]
This I use for my singlebouquet Issue:
`diff --git a/lib/python/RecordTimer.py b/lib/python/RecordTimer.py
index cd02ec4ba6..bbce0f6e79 100644
--- a/lib/python/RecordTimer.py
+++ b/lib/python/RecordTimer.py
@@ -971,5 +971,8 @@ class RecordTimerEntry(TimerEntry, object):
 						if found:
 							ChannelSelectionInstance.addToHistory(self.service_ref.ref)
-					if notFound:
+					if notFound and not config.usage.multibouquet.value:
+						ChannelSelectionInstance.servicelist.setCurrent(self.service_ref.ref, True)
+						ChannelSelectionInstance.zap()
+					elif notFound:
 						# Can we get a result for that?  See if you want to delete the running timer.
 						self.switchToAll()`

**Comment by jbleyel** [comment]
There is another call of self.switchToAll() in case of a failure in line 1452.
What should we do here?

**Comment by jbleyel** [comment]
So we better should move your extra 2 lines into self.switchToAll or what you think?

**Comment by geeeeeeeeeee** [comment]
Feel free... i'm not so fast.

**Comment by geeeeeeeeeee** [comment]
Never had this failure...

**Comment by geeeeeeeeeee** [comment]
I think we cant do it simply in switchall. then copy it to the failure function.

**Comment by geeeeeeeeeee** [comment]
I think it's wrong in `switchToAll()`, it should switchToAll() if `notFound` but this code is buggy and you don't need to fix it now.
Best ignore my solution...
