### ISSUE TITLE
Subsupport Embedded Subtitle Font Change

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2608]
Hello there, is it possible to change the default font from Regular to DejaVuSans for the Embedded subtitles (on kodi 19.4 with external E2Player) in subssuport?
For last some subtitles are not with the foreground in white, but in a light pink (it changes the color when a secondary voice it's in the dialog), is it possible to to change to be white for all?

Thanks!

**Comment by ruipisco** [comment]
@jbleyel  can you help with this change? Thanks

**Comment by jbleyel** [comment]
The subtitle font is part of the skin.

**Comment by ruipisco** [comment]
But I can change for external subtitles, for the embedded only the default! Can we force to change it or create the option on the embedded settings?

**Comment by ruipisco** [comment]
No solution implemented...
