### ISSUE TITLE
Im File Commander geht kein virtuelles Keybord

### ISSUE THREAD

**Issue by Anskar71** [openatv/enigma2#2620]
Auf der Fernbedienung kommt bei der TTX  Taste kein virtuelles Keybord und wird mit einem X oben links quttiert.

https://www.opena.tv/plugins/60806-file-commander-optimieren-post516818.html#post516818

**Comment by jbleyel** [comment]
Ist das gefixt?

**Comment by Anskar71** [comment]
Nabend jbleyel,  gefixt insofern das wenn ich die zu edditierende Datei mit OK öffnen und zu der Zeile gehe die ich bearbeiten möchte und da wiederum OK drücke, erscheint die virtuelle Tastatur. 
Das ist top so ,denke ich kann dann das issues schließen.
