### ISSUE TITLE
[Package/Plugin Manager] package "nss" postinst script returned status 134

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2628]
Quite often over the last couple of months, I've gotten the following message in the plugin install log:

```
Assertion failure: 0 == flags, at ../../../../nspr-4.29/nspr/pr/src/pthreads/ptio.c:3542
//var/lib/opkg/info/nss.postinst: line 2:  2410 Aborted                 shlibsign -i $FN * pkg_run_script: package "nss" postinst script returned status 134. * opkg_configure: nss.postinst returned 134.
```

**Comment by jbleyel** [comment]
Can you provide the plugin name?

**Comment by wedebe** [comment]
One example is `enigma2-plugin-extensions-shootyourscreen`, but there are others.

**Comment by jbleyel** [comment]
What's the opkg version?

**Comment by wedebe** [comment]
I've seen this issue again, details attached:

![screenshot_20230315220338](https://user-images.githubusercontent.com/9741693/225553561-871f3fa7-d0a2-42f8-8f82-dc8ba8c2ea7f.jpg)

`enigma2-plugin-drivers-dvb-usb-rtl2832`

opkg version 0.6.0

**Comment by wedebe** [comment]
> Please call "opkg update" "opkg -V4 upgrade" in a console and provide the output.

[V4_upgrade.log.txt](https://github.com/openatv/enigma2/files/10995099/V4_upgrade.log.txt)

**Comment by jbleyel** [comment]
There is no error in the log.
Looks like the error was only temporary.

**Comment by wedebe** [comment]
It appears to happen every time I restore a backup to a fresh flash.

**Comment by jbleyel** [comment]
Do you use a image from the feed or do you use an old image backup?

**Comment by wedebe** [comment]
> Do you use an image from the feed or do you use an old image backup?

Latest images downloaded through the GUI, settings backups usually fairly recent.

**Comment by wedebe** [comment]
This still happens, both on feed plugins and manual ipk install.
7.3-2023-05-30
Mut@nt HD51

![SES UHD Demo_20230530120400](https://github.com/openatv/enigma2/assets/9741693/6dff5b91-4a3b-4d71-9e8e-b9600ee33bcf)

[enigma2-plugin-systemplugins-servicescanupdates_1.0_all.ipk.zip](https://github.com/openatv/enigma2/files/11599283/enigma2-plugin-systemplugins-servicescanupdates_1.0_all.ipk.zip)

**Comment by wedebe** [comment]
Another example, `enigma2-plugin-extensions-eparted`:

```
 * opkg_install_pkg: Failed to download enigma2-plugin-extensions-eparted. Perhaps you need to run 'opkg update'? * opkg_solver_install: Cannot install package enigma2-plugin-extensions-eparted.
Assertion failure: 0 == flags, at /usr/src/debug/nspr/4.35-r0/pr/src/pthreads/ptio.c:3589
//var/lib/opkg/info/nss.postinst: line 2:  4345 Aborted                 shlibsign -i $FN * pkg_run_script: package "nss" postinst script returned status 134. * opkg_configure: nss.postinst returned 134.
Installing enigma2-plugin-extensions-eparted (7.3+gitr7534+03ee5c6) on root.
Downloading https://feeds2.mynonpublic.com/7.3/hd51/hd51/enigma2-plugin-extensions-eparted_7.3+gitr7534+03ee5c6-r8_hd51.ipk.
Removing corrupt package file /var/cache/opkg/01bf0bca0dde12b2232e0d4dd1915dc4_enigma2-plugin-extensions-eparted_7.3+gitr7534+03ee5c6-r8_hd51.ipk.
Configuring nss.
```

**Comment by atvcaptain** [comment]
the problem has nothing to do with your IPKS you mention here, it is difficult to recover the problem because when you flash the box again the problem is gone

pkg_postinst:${PN} () {
    for I in $D${libdir}/lib*.chk; do
        DN=`dirname $I`
        BN=`basename $I .chk`
        FN=$DN/$BN.so
        shlibsign -i $FN
        if [ $? -ne 0 ]; then
            echo "shlibsign -i $FN failed"
        fi
    done
}

I haven't had the nss bug yet, maybe you can recreate the problem with the script on your end and see what is causing it

**Comment by wedebe** [comment]
> the problem has nothing to do with your IPKS you mention here, it is difficult to recover the problem because when you flash the box again the problem is gone
> 
> pkg_postinst:${PN} () { for I in D{libdir}/lib*.chk; do DN=`dirname $I` BN=`basename $I .chk` FN=$DN/$BN.so shlibsign -i $FN if [ $? -ne 0 ]; then echo "shlibsign -i $FN failed" fi done }
> 
> I haven't had the nss bug yet, maybe you can recreate the problem with the script on your end and see what is causing it

Can you detail the steps I need to take to test this and result I need report back please, @atvcaptain
