### ISSUE TITLE
Fehlender etc/ hosts Eintrag

### ISSUE THREAD

**Issue by Anskar71** [openatv/enigma2#2629]
Bei Flashen mit Übernahme der Einstellungen und Plugins wird in der Datei etc/ hosts nicht der geänderte hostname übernommen.
Da ich zum Beispiel drei MutantHD51 in meinem Netzwerk habe, habe ich per GUI die Datei hostname geändert.
Dieser geänderte hostname wird aber beim "Flashen mit Übernahme der Einstellungen und Plugins" nicht in die Datei etc/ hosts geschrieben.

**Comment by wedebe** [comment]
/etc/hosts doesn't seem to be backed up by default (perhaps it should be?), but you can add it:

System > Software Management > Advanced Options > Select Additional Backup Files

From there, go to /etc > hosts, select/tick it, save, and perform a backup.


Hope that helps!

**Comment by Anskar71** [comment]
Das habe ich bis dato so gemacht, habe aber von Papi2000 die Info erhalten das die etc/ hosts nicht mehr gesichert werden muß.
Wenn man den hostname über die GUI ändert würde das wohl dann automatisch beim "Flashen mit Übernahme der Einstellungen und Plugins" in die etc/ hosts geschrieben.
Nur funktioniert das nicht.

**Comment by Anskar71** [comment]
@ webede, erstmal Danke das Du mir antwortest.
Laut Papi2000, eventuell kennst Du ihn, ist das wohl ins Image gekommen.
Ich habe ihn extra nochmal eben gefragt.
Ich hatte auch immer die etc/ hosts gesichert, aber es soll wohl nun anderst gehen, nur tut es leider nicht.

Sorry das ich nur deutsch schreibe aber englisch muß ich mir immer erst mit Google Übersetzer übersetzen.

**Comment by Anskar71** [comment]
@ Wesen, ich übermittel Dir hier mal die Antwort von Papi2000 an mich:

2 Sachen hat er missverstanden. Die hostname wird per GUI heute schon richtig befüllt, und ist bei restore auch korrekt geändert wieder da. Für webstream wird aber der Dienst auch an den hostnamen gekoppelt gestartet, der steht dazu wiederum in der hosts in der letzten Zeile.
 Wird das auch aktualisiert (synchronisiert zu hostname)?
 Die hosts (mit der eventuellen Namensänderung) muss spätestens nach Änderung in die zu sichernden Dateien aufgenommen werden. Sonst geht Stream aus Senderliste im WebIF nicht."

**Comment by wedebe** [comment]
(I'm using translate tools here too, lol!)

When I updated the hostname, the /etc/hosts file did not update.

I'm out of ideas here :(

**Comment by Anskar71** [comment]
Danke wedebe, genau, das ist das Problem.
Laut Papi2000 sollte das aber funktionieren.
Also noch ein Bug.

**Comment by wedebe** [comment]
Yep, I had to manually edit the hosts file, then set /etc/hosts as an additional backup file.

Another bug here is that after changing the hostname, the `Information > Network` screen showed the previous hostname until I restarted.

![1_0_1F_1CEA_7F6_2_11A0000_0_0_0_20221026085254](https://user-images.githubusercontent.com/9741693/197971746-c66213bb-8003-4f8e-94a1-0f6c4d793f6d.jpg)
![1_0_1F_1CEA_7F6_2_11A0000_0_0_0_20221026085338](https://user-images.githubusercontent.com/9741693/197971768-6891a191-b503-4651-b52c-33fea157f2fa.jpg)
![1_0_1F_1CEA_7F6_2_11A0000_0_0_0_20221026085412](https://user-images.githubusercontent.com/9741693/197971799-cc6ed88e-7892-4fed-8391-e88e58c7f5dd.jpg)

**Comment by jbleyel** [comment]
We can think about to add the hosts to the default backup.
The information screen shows the hostname from the kernel proc.

**Comment by wedebe** [comment]
> The information screen shows the hostname from the kernel proc.

In which case, the receiver needs to be rebooted on hostname change, not just the network adapter?

**Comment by Anskar71** [comment]
Wichtig wäre aber das die Änderung der hostname Datei auch in die Datei hosts kommt.
Die muß ja bis dato auch noch händisch editiert werden.

**Comment by Anskar71** [comment]
Guten Abend, jbleyel, 
ab wann soll die Änderung wegen der hosts in den gesicherten Dateien im Image sein?
Beim heutigen oatv7.1 Image, 31.10.22, ist es noch nicht drin.

**Comment by jbleyel** [comment]
Ist noch nicht drin.
https://github.com/openatv/enigma2/pull/2635

**Comment by Anskar71** [comment]
Letze Antwort war ja vor 24 Tagen.
Frage nochmal vorsichtig hier an.
Warum greift der Fix zur Datei hosts noch nicht in der Standartsicherung in aktuellen oatv Imagen?

**Comment by Anskar71** [comment]
Mit heutigem Image, 25.11.22 ist die Datei hosts in der Standartsicherung enthalten.

Danke dafür @jbleyel :+1:
