### ISSUE TITLE
Inconsistent `< Left` and `Right >` buttons actions

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2630]
`< Left` and `Right >` buttons don't follow the same functionality of AutoTimers list, channel list, plugin list - move page up/down, an 🛑 icon is shown in the top-left of the screen.

**Comment by IanSav** [comment]
This is not a consistent UI design.  LEFT and RIGHT should move left and right NOT up and down.

As each module is updated/refactored the navigation will be unified into a consistent implementation.

The new navigation options, if implemented into a screen, are:
goTop: Move to the first line / screen of the list.
goPageUp: Move up a page / screen.
goLineUp: Move up a line.
goFirst: Move to the first item in an option list.
goPageLeft: Not implemented but reserved for future use.
goLeft: Move to the previous item in an option list.
goRight: Move to the next item in an option list.
goPageRight: Not implemented but reserved for future use.
goLast: Move to the last item in an option list.
goLineDown: Move down a line.
goPageDown: Move down a page / screen.
goBottom: Move to the last line / screen of the list.

Where there is no natural navigation goLeft and goRight then these actions are used to select alternate panels available within the screen.  Going forward goLeft and goRight will no longer drastically change meaning from screen to screen.  If they do not offer a natural *and* predictable navigation option then the assigned buttons will be disabled!

The buttons allocated to these actions can be managed in keymap.xml.  On my machine (which is not what is used on openATV) I have:
goTop: REW
goPageUp: CH UP
goLineUp: UP
goFirst: PREV
goPagLeft: Not implemented
goLeft: LEFT
goRight: RIGHT
goPageRight: Not implemented.
goLast: NEXT
goLineDown: DOWN
goPageDown: CH DOWN
goBottom: FF

What this means is that each of these buttons will be predictable and generally always have the same function.  The navigation buttons will no longer have random functions that change from screen to screen.

**Comment by wedebe** [comment]
Thanks @IanSav. In that case, I guess my concern is with the general inconsistency, but with refactor work in progress this is inevitable.

In this case, Channel List currently uses
`CH+` Next bouquet
`CH-` Prev bouquet 
`< Left` Page up
`Right >` Page down

If such usability changes are made, may I suggest these are done on version updates (eg. 7.1 or even 7.2) rather than inexplicably expecting users to understand what's going on?

**Comment by wedebe** [comment]
I've updated the title and description of this issue.

**Comment by jogibaer1948** [comment]
In this case, Channel List currently uses flipped actions:
CH+ Next bouquet
CH- Prev bouquet
< Left Page up
Right > Page down
I also hope that this will never be changed because I use it the same way.

**Comment by wedebe** [comment]
@IanSav , please consider adding a global configuration option to enable `< Left` / `Right >` to be used as Page Up/Page Down in lists, particularly in places where the UI will just say **NO!**. 

I'm already finding it awkward to really quickly traverse lists by moving my thumb one button away from centre - it now has to feel around in low light for the `CH+`, `CH-` buttons at a different area of the remote which needs a grip change.

**Comment by IanSav** [comment]
When you use the UI how do you know what the LEFT and RIGHT buttons are going to do?  If they do different things on different screens how can you predict what they are going to do?  My intention is to make the UI predictable so that users can develop muscle memory and guess what the buttons will do even without using all the new help that we have also been adding.

**Comment by jbleyel** [comment]
Check this -> https://github.com/openatv/enigma2/pull/2637

This is a mockup and not finally finished and tested!

**Comment by jogibaer1948** [comment]
Puh mein senderlisten verhalten und ch +/- für Bouquet geht noch und rechts links blättert die seiten wie immer.
Wenn nicht mehr wäre ja auch die tasteneinstellungen obsolet.
![1_0_19_EF14_421_1_C00000_0_0_0_20221027122408](https://user-images.githubusercontent.com/108607229/198264011-7d3ee848-1a67-44c2-9559-dd5499806889.jpg)

**Comment by jbleyel** [comment]
Channel list keymap is not changed "yet".

**Comment by IanSav** [comment]
You all need to realise that we can't make navigation changes across all of the modules that make up Enigma2 at the same time.  The changes and improvements are being made progressively across all of Enigma2 as we visit those areas of the code.

I note that @jbleyel is making changes to the keymaps.  I don't think I agree with those changes but I won't be looking at the code until I fully recover from my surgery.  I hope to catch up with @jbleyel soon.

**Comment by wedebe** [comment]
> You all need to realise that we can't make navigation changes across all of the modules that make up Enigma2 at the same time. The changes and improvements are being made progressively across all of Enigma2 as we visit those areas of the code.

This is why I suggested the changes be made in a version update - so that users on OpenATV 7.0, for example, don't suddenly find what used to work not working anymore.

**Comment by IanSav** [comment]
I am not in control of what changes are merged into what branches.  Most of my commits are made to the 7.1 branch unless I am otherwise instructed.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/eae2f1811eeb34ca50ae290ab546512a4f2de1c4
