### ISSUE TITLE
[Feature Request] `Change hostname` directly under `Network` menu

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2632]
Currently this involves a convoluted journey through `Setup > System > Network > Mounts Settings > Mount manager > Change hostname`.

I'd like to suggest that a shortcut be added at `Setup > System > Network > Hostname`, with descriptive text along the lines of "You can access your receiver using this friendly name."

**Comment by jbleyel** [comment]
This is too much effort because the Mount manager is a plugin.
