### ISSUE TITLE
File Commander Bluescreen beim öffnen .sh Datei und .tar.gz

### ISSUE THREAD

**Issue by Anskar71** [openatv/enigma2#2639]
Guten Abend!
Bekomme im File Commander eine Bluescreen beim öffnen meiner "myrestore.sh" und meiner "enigma2settingsbackup.tar.gz".
Ich hänge hier beide Crashlogs an.
[20221030-175943-enigma-crash.log](https://github.com/openatv/enigma2/files/9896402/20221030-175943-enigma-crash.log)
[20221030-180134-enigma-crash.log](https://github.com/openatv/enigma2/files/9896403/20221030-180134-enigma-crash.log)

**Comment by jbleyel** [comment]
FileCommander is currently in development.

**Comment by Anskar71** [comment]
Warum muß man hier gleich schließen,  sollte man eher als Hinweis sehen worauf beim Umbau geachtet werden muß, sind schließlich Fehlermeldungen und Hilfe.
Verstehe dann den Sinn vom Github hier nicht.

**Comment by jbleyel** [comment]
Der FileCommander wird komplett umgebaut, der alte und neue Code ist nicht vergleichbar.

**Comment by Anskar71** [comment]
Verstehe Dich schon, dachte nur es könnte ein Hinweis sein worauf alles beim neuen File Commander geachtet werden muß, da es mit altem nicht geht.

**Comment by jbleyel** [comment]
Deine myrestore.sh ist nicht UTF-8 oder ASCII und könnte mit der neuen Version auch ein Problem sein.
Die tar.gz geht mit der neuen Version ganz sicher.

**Comment by Anskar71** [comment]
@jbleyel , danke für den Hinweis wegen der myrestore.sh. 
Ist nun in UTF-8 und es gibt beim Öffnen per File Commander nun keinen Bluescreen mehr.
