### ISSUE TITLE
OPEN ATV 7.0 EMC 

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2642]
Hi @jbleyel , on Media Player (EMC) in OpenAtv 7.0, if i have an playlist of music and movies after select with the up and down keys with the remote control and press the "OK" or Play key in the remote control it always skips the selected item and plays the last entry of the playlist. 

This causes that is not possible to select another item to play from the playlist, so it's not possible to play the selected item. I

Hi have some suggestions to for the remote control keymap of the EMC player, for you to try to implement on the button action for the media player: 

1 - Play button: Change to play action only and remove the pause action when an item is already playing.
2 - Pause button: Change to pause action only and remove the play action when an item is already paused.
3 - Stop button: Change to stop only and return to playlist and remove the direct action to Exit of the Media Player.

**Comment by geeeeeeeeeee** [comment]
Hey my friend!
The PlayKey works like you tell but the OK works like you want.
You can change the Keymap.xml too!?
But there is an option "EMC re-open list after STOP-press". (+"Leave Movie with Exit" you are new on EMC?)

**Comment by ruipisco** [comment]
Hi there @geeeeeeeeeee ! Sorry i have not explained correctly! The problem is not in EMC but on the Media Player! So let me explain bellow with images step by step:

1º - The problem is on the Media Player Plugin
![Captura de ecrã 2022-11-07, às 20 40 43](https://user-images.githubusercontent.com/32041748/200412162-9544accb-6b6c-406a-9fd3-4fd3e1999e59.png)

2º - After Media Player is open i access to any item in the playlist (in this example i select the first item of the playlist "Savage Garden - To The Moon Back (Extended Version).mp3"
![Captura de ecrã 2022-11-07, às 20 41 26](https://user-images.githubusercontent.com/32041748/200412623-8fe95c1e-ea37-4259-98ee-3c24cd32cc99.png)

3º - When the "OK"  or "Play" Button is pressed the selected item is ignored and it assumes every time the last item of the playlist, in this case you can see that the selected song is  "Savage Garden - To The Moon Back (Extended Version).mp3", but on the right pane you can see that the song that is playing is "Return to Innocence.mp3"
![Captura de ecrã 2022-11-07, às 20 41 58](https://user-images.githubusercontent.com/32041748/200413615-f1d357a9-f4e7-4512-ba29-3eca9d968292.png)

4º - In the next image you can see that the song "Return to Innocence.mp3" is the last entry of the playlist
![Captura de ecrã 2022-11-07, às 20 42 33](https://user-images.githubusercontent.com/32041748/200414103-c60825dd-a5e4-447b-af60-d0ae0885dbfa.png)

So there is a bug in Media Player while pressing the Button to select the item that is selected, and it plays always the last entry fo the playlist.

**Comment by geeeeeeeeeee** [comment]
It's a known Issue. [Here](https://github.com/openatv/enigma2/issues/2595) and there in a [german thread](https://www.opena.tv/openatv-7-1-py3-10-openssl-3-0-beta/60812-mediaplayer-bug.html).
If you can't remove the EMC mistake, you should close here...

**Comment by geeeeeeeeeee** [comment]
There should be a sign! A pointer for the playlist.
If u press play, playlist starts there.
Your skin?
I don't know how to start in the middle of playlist!
![200414103-c60825dd-a5e4-447b-af60-d0ae0885dbfa](https://user-images.githubusercontent.com/82714245/200557848-0fdfa774-8f0e-4528-8bf5-ce8ee88b94f7.png)

**Comment by ruipisco** [comment]
Hi there @geeeeeeeeeee ! My Skin is the default MyMetrix of Open Atv 7.0 for VuPlus... on the older versions like 6.4 the skin is basicly the same for the media player... only since an update this started to hapening and never had an pointer to select the song like you identify on the image... something had change and it had afected the way that Media Player works...

**Comment by jbleyel** [comment]
This plugin will be no longer maintained and removed as core plugin from image soon.
