### ISSUE TITLE
Restore after `Upgrade & restore all` should change language of UI at earliest possibility

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2643]
Restoring a backup once an image has been updated currently runs the (video mode) setup wizard and prompts to restore the backup through German, even though the user's backup was another language (English in my case).

Once the restore is done, OpenATV notifies the user in German while it `restarts network adapter`, `installs plugins from feed`, `restores Metrix-HD skin settings`, `your box is rebooting...`.

As soon as the settings file is restored, OpenATV should read the language preference, reload the UI _AND_ set a flag for the language of the setup wizard, or have the wizard read the settings file.

**Comment by jbleyel** [comment]
The language selection is now the first wizard page.
So we can close this. Right?

**Comment by wedebe** [comment]
I'll test this next new image flash.

**Comment by jbleyel** [comment]
Tested?

**Comment by wedebe** [comment]
> Tested?

Confirmed language is now first screen, thanks. I can't test on a Scart screen to see what (if anything) appears.
