### ISSUE TITLE
PluginDescriptor.WHERE_HOTKEY

### ISSUE THREAD

**Issue by geeeeeeeeeee** [openatv/enigma2#2648]
### German
Ich würde gerne ein (eigenes) Plugin dauerhaft auf einen Hotkey legen.
Dann brauche ich es aber nicht mehr im Erweiterungsmenü etc. aber da beißt sich die Katze...
Nur Plugins die in "PLUGINMENU, EXTENSIONSMENU, EVENTINFO" sind, lassen sich auf einen Hotkey legen.

**Wie wäre es mit einem PluginDescriptor.WHERE_BUTTONSETUP(HOTKEY)?**
Bin da jetzt shon das zweite Mal hängen geblieben, daher die Frage!
ButtonSetupFunctions ist leider auch nicht global/zugänglich.

### English Translator
I would like to put a (own) plugin permanently on a hotkey.
Then I don't need it anymore in the extension menu etc. but that's where the cat bites...
Only plugins that are in "PLUGINMENU, EXTENSIONSMENU, EVENTINFO" can be assigned to a hotkey.

**How about a PluginDescriptor.WHERE_BUTTONSETUP(HOTKEY)?**
I got stuck there for the second time, hence the question!
Unfortunately, ButtonSetupFunctions is also not global/accessible.

**Comment by geeeeeeeeeee** [comment]
Thanks for visit.
But then i don't need it in any menu.
Later I will try to change the code by my self.

**Comment by jbleyel** [comment]
This all sounds like a hack to modify the hotkey functionality and you may break this if you do this in your plugin.
And by the way, what key do you wanna define as hotkey.
Always the same?
How many plugins do you wanna change for this?

**Comment by geeeeeeeeeee** [comment]
Then it's possible to create a second extensionmenu on a hotkey with own plugins that have this descriptor.
And i don't have a plugin in the extensionmenu, that i never call this way, because its on a hotkey.

**Comment by geeeeeeeeeee** [comment]
Then it's possible to create a second "extensionmenu" on a hotkey with own plugins that have this descriptor.
And i don't have a plugin in the extensionmenu, that i never call this way, because its on a hotkey.
I can understand that usually public plugins will never have this desciptor!
It's practically possible to extend this list in a way by a the plugin:
`ButtonSetupFunctions.append((_("Show vertical Program Guide"), "Infobar/openVerticalEPG", "EPG"))
	ButtonSetupFunctions.append((_("Show graphical multi EPG"), "Infobar/openGraphEPG", "EPG"))
	ButtonSetupFunctions.append((_("Main Menu"), "Infobar/showMainMenu", "InfoBar"))
	ButtonSetupFunctions.append((_("Show help"), "Infobar/showHelp", "InfoBar"))
	ButtonSetupFunctions.append((_("Show extension selection"), "Infobar/showExtensionSelection", "InfoBar"))
	ButtonSetupFunctions.append((_("Zap down"), "Infobar/zapDown", "InfoBar"))
	ButtonSetupFunctions.append((_("Zap up"), "Infobar/zapUp", "InfoBar"))
	ButtonSetupFunctions.append((_("Volume down"), "Infobar/volumeDown", "InfoBar"))
	ButtonSetupFunctions.append((_("Volume up"), "Infobar/volumeUp", "InfoBar"))
	ButtonSetupFunctions.append((_("Show InfoBar"), "Infobar/toggleShow", "InfoBar"))
	ButtonSetupFunctions.append((_("Show service list"), "Infobar/openServiceList", "InfoBar"))
	ButtonSetupFunctions.append((_("Show favorites list"), "Infobar/openBouquets", "InfoBar"))
	ButtonSetupFunctions.append((_("Show satellites list"), "Infobar/openSatellites", "InfoBar"))
	ButtonSetupFunctions.append((_("History back"), "Infobar/historyBack", "InfoBar"))
	ButtonSetupFunctions.append((_("History next"), "Infobar/historyNext", "InfoBar"))
	ButtonSetupFunctions.append((_("Show eventinfo plugins"), "Infobar/showEventInfoPlugins", "EPG"))
	ButtonSetupFunctions.append((_("Show event details"), "Infobar/openEventView", "EPG"))
	ButtonSetupFunctions.append((_("Show single service EPG"), "Infobar/openSingleServiceEPG", "EPG"))
	ButtonSetupFunctions.append((_("Show multi channel EPG"), "Infobar/openMultiServiceEPG", "EPG"))
	ButtonSetupFunctions.append((_("Show Audioselection"), "Infobar/audioSelection", "InfoBar"))
	ButtonSetupFunctions.append((_("Enable digital downmix"), "Infobar/audioDownmixOn", "InfoBar"))
	ButtonSetupFunctions.append((_("Disable digital downmix"), "Infobar/audioDownmixOff", "InfoBar"))
	ButtonSetupFunctions.append((_("Switch to radio mode"), "Infobar/showRadio", "InfoBar"))
	ButtonSetupFunctions.append((_("Switch to TV mode"), "Infobar/showTv", "InfoBar"))
	ButtonSetupFunctions.append((_("Show servicelist or movies"), "Infobar/showServiceListOrMovies", "InfoBar"))
	ButtonSetupFunctions.append((_("Show movies"), "Infobar/showMovies", "InfoBar"))
	ButtonSetupFunctions.append((_("Instant record"), "Infobar/instantRecord", "InfoBar"))
	ButtonSetupFunctions.append((_("Start instant recording"), "Infobar/startInstantRecording", "InfoBar"))
	ButtonSetupFunctions.append((_("Start recording current event"), "Infobar/startRecordingCurrentEvent", "InfoBar"))
	ButtonSetupFunctions.append((_("Activate time shift End"), "Infobar/activateTimeshiftEnd", "InfoBar"))
	ButtonSetupFunctions.append((_("Activate time shift end and pause"), "Infobar/activateTimeshiftEndAndPause", "InfoBar"))
	ButtonSetupFunctions.append((_("Start time shift"), "Infobar/startTimeshift", "InfoBar"))
	ButtonSetupFunctions.append((_("Stop time shift"), "Infobar/stopTimeshift", "InfoBar"))
	ButtonSetupFunctions.append((_("Start teletext"), "Infobar/startTeletext", "InfoBar"))
	ButtonSetupFunctions.append((_("Show subservice selection"), "Infobar/subserviceSelection", "InfoBar"))
	ButtonSetupFunctions.append((_("Show subtitle selection"), "Infobar/subtitleSelection", "InfoBar"))
	ButtonSetupFunctions.append((_("Show subtitle quick menu"), "Infobar/subtitleQuickMenu", "InfoBar"))
	ButtonSetupFunctions.append((_("Letterbox zoom"), "Infobar/vmodeSelection", "InfoBar"))
	ButtonSetupFunctions.append((_("Seekbar"), "Infobar/seekFwdVod", "InfoBar"))
	if BoxInfo.getItem("PIPAvailable"):
		ButtonSetupFunctions.append((_("Show PiP"), "Infobar/showPiP", "InfoBar"))
		ButtonSetupFunctions.append((_("Swap PiP"), "Infobar/swapPiP", "InfoBar"))
		ButtonSetupFunctions.append((_("Move PiP"), "Infobar/movePiP", "InfoBar"))
		ButtonSetupFunctions.append((_("Toggle PiPzap"), "Infobar/togglePipzap", "InfoBar"))
		ButtonSetupFunctions.append((_("Cycle PiP(zap)"), "Infobar/activePiP", "InfoBar"))
	ButtonSetupFunctions.append((_("Activate HbbTV (RED button)"), "Infobar/activateRedButton", "InfoBar"))
	if BoxInfo.getItem("hdmihdin") or BoxInfo.getItem("hdmifhdin"):
		ButtonSetupFunctions.append((_("Toggle HDMI-In full screen"), "Infobar/HDMIInFull", "InfoBar"))
		ButtonSetupFunctions.append((_("Toggle HDMI-In PiP"), "Infobar/HDMIInPiP", "InfoBar"))
	if BoxInfo.getItem("LcdLiveTV"):
		ButtonSetupFunctions.append((_("Toggle LCD LiveTV"), "Infobar/ToggleLCDLiveTV", "InfoBar"))
	if BoxInfo.getItem("canMultiBoot"):
		ButtonSetupFunctions.append((_("MultiBoot Manager"), "Module/Screens.MultiBootManager/MultiBootManager", "InfoBar"))
	ButtonSetupFunctions.append((_("Hotkey Settings"), "Module/Screens.ButtonSetup/ButtonSetup", "Setup"))
	ButtonSetupFunctions.append((_("Software Update"), "Module/Screens.SoftwareUpdate/SoftwareUpdate", "Setup"))
	if BoxInfo.getItem("ci"):
		ButtonSetupFunctions.append((_("CI (Common Interface) Setup"), "Module/Screens.Ci/CiSelection", "Setup"))
	if BoxInfo.getItem("SoftCam"):
		ButtonSetupFunctions.append((_("Softcam Setup"), "Module/Screens.SoftcamSetup/SoftcamSetup", "Setup"))
	ButtonSetupFunctions.append((_("Videosetup"), "Module/Screens.VideoMode/VideoSetup", "Setup"))
	ButtonSetupFunctions.append((_("Tuner Configuration"), "Module/Screens.Satconfig/NimSelection", "Scanning"))
	ButtonSetupFunctions.append((_("Manual Scan"), "Module/Screens.ScanSetup/ScanSetup", "Scanning"))
	ButtonSetupFunctions.append((_("Automatic Scan"), "Module/Screens.ScanSetup/ScanSimple", "Scanning"))
	for plugin in plugins.getPluginsForMenu("scan"):
		ButtonSetupFunctions.append((plugin[0], "MenuPlugin/scan/" + plugin[2], "Scanning"))
	ButtonSetupFunctions.append((_("Network Settings"), "Module/Screens.NetworkSetup/NetworkAdapterSelection", "Setup"))
	ButtonSetupFunctions.append((_("Network menu"), "Infobar/showNetworkMenu", "Setup"))
	ButtonSetupFunctions.append((_("VPN"), "Module/Screens.NetworkSetup/NetworkOpenvpn", "Setup"))
	ButtonSetupFunctions.append((_("Plugin Browser"), "Module/Screens.PluginBrowser/PluginBrowser", "Setup"))
	ButtonSetupFunctions.append((_("Channel Info"), "Module/Screens.ServiceInfo/ServiceInfo", "Setup"))
	ButtonSetupFunctions.append((_("SkinSelector"), "Module/Screens.SkinSelector/SkinSelector", "Setup"))
	if BoxInfo.getItem("LCDSKINSetup"):
		ButtonSetupFunctions.append((_("LCD SkinSelector"), "Module/Screens.SkinSelector/LcdSkinSelector", "Setup"))
	ButtonSetupFunctions.append((_("RecordTimer"), "Module/Screens.Timers/RecordTimerOverview", "Setup"))
	ButtonSetupFunctions.append((_("Open AutoTimer"), "Infobar/showAutoTimerList", "Setup"))
	for plugin in plugins.getPluginsForMenu("system"):
		if plugin[2]:
			ButtonSetupFunctions.append((plugin[0], "MenuPlugin/system/" + plugin[2], "Setup"))
	ButtonSetupFunctions.append((_("Standby"), "Module/Screens.Standby/Standby", "Power"))
	ButtonSetupFunctions.append((_("Restart"), "Module/Screens.Standby/TryQuitMainloop/2", "Power"))
	ButtonSetupFunctions.append((_("Restart enigma"), "Module/Screens.Standby/TryQuitMainloop/3", "Power"))
	ButtonSetupFunctions.append((_("Deep Standby"), "Module/Screens.Standby/TryQuitMainloop/1", "Power"))
	ButtonSetupFunctions.append((_("SleepTimer"), "Module/Screens.SleepTimer/SleepTimer", "Power"))
	ButtonSetupFunctions.append((_("PowerTimer"), "Module/Screens.Timers/PowerTimerOverview", "Power"))
	ButtonSetupFunctions.append((_("Usage Setup"), "Setup/Usage", "Setup"))
	ButtonSetupFunctions.append((_("User interface settings"), "Setup/UserInterface", "Setup"))
	ButtonSetupFunctions.append((_("Recording Setup"), "Setup/Recording", "Setup"))
	ButtonSetupFunctions.append((_("Harddisk Setup"), "Setup/HardDisk", "Setup"))
	ButtonSetupFunctions.append((_("Subtitles Settings"), "Setup/Subtitle", "Setup"))
	ButtonSetupFunctions.append((_("Language"), "Module/Screens.LocaleSelection/LocaleSelection", "Setup"))
	if BoxInfo.getItem("SoftCam"):
		ButtonSetupFunctions.append((_("OscamInfo Mainmenu"), "Module/Screens.OScamInfo/OscamInfoMenu", "Plugins"))
		ButtonSetupFunctions.append((_("CCcamInfo Mainmenu"), "Module/Screens.CCcamInfo/CCcamInfoMain", "Plugins"))
	ButtonSetupFunctions.append((_("Movieplayer"), "Infobar/showMoviePlayer", "Plugins"))
	if isdir("/etc/ppanels"):
		for file in [x for x in listdir("/etc/ppanels") if x.endswith(".xml")]:
			file = file[:-4]
			ButtonSetupFunctions.append(("%s %s" % (_("PPanel"), file), "PPanel/%s" % file, "PPanels"))
	if isdir("/usr/script"):
		for file in [x for x in listdir("/usr/script") if x.endswith(".sh")]:
			file = file[:-3]
			ButtonSetupFunctions.append(("%s %s" % (_("Shellscript"), file), "Shellscript/%s" % file, "Shellscripts"))
	ButtonSetupFunctions.append((_("ScriptRunner"), "Module/Screens.ScriptRunner/ScriptRunner", "Plugins"))
	ButtonSetupFunctions.append((_("QuickMenu"), "Module/Screens.QuickMenu/QuickMenu", "Plugins"))
	if isPluginInstalled("Kodi"):
		ButtonSetupFunctions.append((_("Kodi MediaCenter"), "Kodi/", "Plugins"))
	if isPluginInstalled("BluetoothSetup"):
		ButtonSetupFunctions.append((_("Bluetooth Setup"), "Bluetooth/", "Plugins"))
	if isPluginInstalled("Chromium"):
		ButtonSetupFunctions.append((_("Youtube TV"), "YoutubeTV/", "Plugins"))
	return ButtonSetupFunctions`

**Comment by jbleyel** [comment]
I don't think I understand what you really want.
You want your plugin in the hotkey, but not in the plugin menu and not in the extension menu.
Is that what you want?

**Comment by geeeeeeeeeee** [comment]
Yes, that's it.
