### ISSUE TITLE
FileCommander <Parent Directory> of symbolic link

### ISSUE THREAD

**Issue by geeeeeeeeeee** [openatv/enigma2#2649]
https://github.com/openatv/enigma2/issues/2649#issuecomment-1381749494

**Comment by jbleyel** [comment]
Please try again with the new version

**Comment by geeeeeeeeeee** [comment]
Hatte das schon bevor es in den 7.1 Branch gelangt war, mal getestet, aber da ist mir nur aufgefallen, dass es nicht ging.
Hab extra neu geflasht.

Verändert aber geht nicht, Gelb lang geht aber.
Erkenne da leider immer noch kein konsistentes Verhalten.
Soll es eigentlich überhaupt eine Aufwärts-Funktion sein?

Versuche mal Internal flash->hdd.



Bei der Gelegenheit 2 Sachen.
Früher konnte ich zbsp eine .py mit der TXT-Taste im Editor öffnen. Gibts nicht mehr.
Und ein Bug:
Immer wenn oben <Liste der Speichermedien> ist/steht und es auch markiert ist und man auf die 2. Seite wechselt, fehlt unten Grün(Verschieben) und Gelb(Kopieren).

**Comment by jbleyel** [comment]
.py einfach OK

Wenn oben <List of Storage Devices> markiert ist, dann geht keine Aktion und deshalb sind die auch nicht sichtbar.

**Comment by geeeeeeeeeee** [comment]
Jetzt dachte ich schon wieder, ich hab dir ein falsches Beispiel gegeben aber nein.
> .py einfach OK

Aber leider nein, das öffnet nur das Menü.

Zurück zum Themen verwandten Bug:
> Wenn oben <List of Storage Devices> markiert ist, dann geht keine Aktion und deshalb sind die auch nicht sichtbar.

OK, aber
> und man auf die 2. Seite wechselt, fehlt unten Grün(Verschieben) und Gelb(Kopieren).

da sollte es dann wieder gehen aber es kommt nicht zurück -> Bug.

PS: Bitte einfach ignorieren, wenn das so ok ist:
MB Großes M und kB kleines k?

**Comment by geeeeeeeeeee** [comment]
Ich hab mich schwer getan, das überhaupt nachvollziehen zu können, jetzt gelingt es mir eventuell. Was wäre den eine Ausnahme(abgesehen von `/` um wo man unbedingt `<List of Storage Devices>` sehen sollte?
Ich würde immer nur /./.../das letzte/ ab schnipseln und eben bei `/` die Ausnahme bilden.

**Comment by jbleyel** [comment]
> 

Screenshot bitte wo die Buttons fehlen.

**Comment by jbleyel** [comment]
> Ich hab mich schwer getan, das überhaupt nachvollziehen zu können, jetzt gelingt es mir eventuell. Was wäre den eine Ausnahme(abgesehen von `/` um wo man unbedingt `<List of Storage Devices>` sehen sollte?
> Ich würde immer nur /./.../das letzte/ ab schnipseln und eben bei `/` die Ausnahme bilden.

Ich verstehe hier leider nur Bahnhof. Sorry.

**Comment by jbleyel** [comment]
> Weiterer Bug: Wenn ich eine Datei lösche, geht die Markierung nach ganz oben.

Da ist glaub schon immer so.

**Comment by geeeeeeeeeee** [comment]
>> Weiterer Bug: Wenn ich eine Datei lösche, geht die Markierung nach ganz oben.

> Da ist glaub schon immer so.

Also Jogibär schreibt es [hier](https://www.opena.tv/openatv-7-2-py3-11-openssl-3-07-beta/61269-filecomander-und-multiselect-fehler.html) sogar auch. Weil es neu ist.
Jogibär: Wenn man files löscht, springt er nach oben und bleibt nicht in der liste.


> Screenshot bitte wo die Buttons fehlen.

`<List of Storage Devices>` markieren und Seite wechseln.
Ein Screenshot kann das auch nicht erklären nur beweisen.

**Comment by geeeeeeeeeee** [comment]
https://github.com/openatv/enigma2/pull/2697

**Comment by geeeeeeeeeee** [comment]
https://github.com/openatv/enigma2/blob/7.1/lib/python/Plugins/Extensions/FileCommander/plugin.py#L436
Zum themenverwandten Bug hätte ich nun dieses als Vorschlag:
`if currentDirectory and srcPath and srcName and not srcName.startswith("<") and self.targetColumn.getCurrentDirectory() and currentDirectory() != self.targetColumn.getCurrentDirectory()`
Das Problem scheint das `self.targetColumn.getPath()` statt `self.targetColumn.getCurrentDirectory()` verwendet wurde.
Etwas was noch fehlt ist `currentDirectory() != self.targetColumn.getCurrentDirectory()`

**Comment by jbleyel** [comment]
Ich kann den Fehler nicht nachstellen.

**Comment by jbleyel** [comment]
should be fixed here -> https://github.com/openatv/enigma2/pull/2712

**Comment by geeeeeeeeeee** [comment]
I hope you understand the FileList.py (inhibitMounts getMountPoint getMountPointLink showMountPoints) code.
I don't.

`"yellowlong": (self.keyParent, _("Go to parent directory of the current column")),`
This is a workaround in the new version.
It's not fixed but if you close, i don't care.

**Comment by jbleyel** [comment]
You right.. it's not fixed and probably not possible to fix.

**Comment by jbleyel** [comment]
Hi @geeeeeeeeeee,
Can you please try again to explain what you are doing and how can I reproduce the issue.
Screenshot will be helpful.

**Comment by jbleyel** [comment]
Kannst du mir das noch mal anders beschreiben.
Am besten mit Screenshots.
Ich hab immer noch nicht so ganz verstanden was das Problem ist.

**Comment by geeeeeeeeeee** [comment]
/home/root/ ist eine andere Partition als /hdd/screenshots/
Erstelle ich einen Symlink(screenshots) von der einen auf die andere, kommt es zu diesem Problem.
![screenshot_2023-01-13_12-48-11](https://user-images.githubusercontent.com/82714245/212313839-53f3277b-9e27-42aa-8453-2c97ad802b8e.png)
![screenshot_2023-01-13_12-48-31](https://user-images.githubusercontent.com/82714245/212313845-22dd1ba6-6fbb-4fc0-b044-0a9a6d742d69.png)

**Comment by jbleyel** [comment]
Ich glaube das ist by Design zudem ist /hdd auch schon ein Link.

**Comment by geeeeeeeeeee** [comment]
Ich hatte erst /mnt/hdd bzw. /media/hdd aber egal...
By Design, mag sein aber so ganz klar eine Fehlfunktion.

**Comment by jbleyel** [comment]
Dann teste das mal mit 7.0 und mit 6.4

**Comment by geeeeeeeeeee** [comment]
Warum?

**Comment by jbleyel** [comment]
Weil ich wissen will ob es da genau so ist.

**Comment by geeeeeeeeeee** [comment]
Nein, das hatte sich etwas geändert und ist nun konsistenter.
Da musste man den FC schließen und erst beim erneuten öffnen kam es dazu.

**Comment by geeeeeeeeeee** [comment]
Ich weiß.

**Comment by geeeeeeeeeee** [comment]
Solange man den FC nicht geschlossen hat hatte es dort funktioniert aber es war wirklich verwirrend wenn man ihn neu geöffnet hat.

**Comment by jbleyel** [comment]
Dann beschreibe mal wie genau du es haben willst.
Bitte step by step.

**Comment by geeeeeeeeeee** [comment]
Naja, das ist schon nicht schlecht, wenn es mointpoints als Speichergerät identifiziert aber nicht jeder symlink auf einer anderen partition ist ein mointpoint und somit ein Speichergerät.
Soll heißen, das müsste besser von einander getrennt werden.
Wenn ich eine langen Pfad gefolgt bin /1/2/3/4/5/6/7/8/9 ist es nicht schön aus versehen bei 0 zu landen.
Dann lieber 0 = Speichergeräte und 1 = / (root) usw. und ganz auf die Erkennung verzichten.

Ich hoffe das ist dir nicht zu wild...
Sonst ganz einfach bei meinem symlink /home/root/sreenshots/ (-> /mnt/hdd/sreenshots/) sollte man nicht Speichergeräte sehen, sondern Übergeordnetes Verzeichnis!

**Comment by jbleyel** [comment]
Man kann einen Schalter in FC einbauen aber dann kannst du nirgends zurück auf <List of Devices>.
Damit haben dann sicher viele ein Problem.

**Comment by geeeeeeeeeee** [comment]
Einen Schalter, für mich brauche ich nicht. Danke

**Comment by jbleyel** [comment]
Also dann den issue hier zu machen?

**Comment by geeeeeeeeeee** [comment]
Mir egal

**Comment by jbleyel** [comment]
Du kannst ja gelb lang benutzen.

**Comment by geeeeeeeeeee** [comment]
genau danke dafür!!

**Comment by geeeeeeeeeee** [comment]
@jbleyel Bevor ich hier irgendwann mal aus langerweile noch ein Issue draus mache, vielleicht willst du vorher mal danach schauen.
https://www.opena.tv/allgemeine-image-informationen/59030-ein-todo-fuer-timeshift-py.html

**Comment by jbleyel** [comment]
Mach mal einen neuen issue.
ABER!! Verschoben wird es nur wenn das Ziel keine Hardlinks kann. Oder ist das Problem nur beim Split.

**Comment by geeeeeeeeeee** [comment]
> ABER!! Verschoben wird es nur wenn das Ziel keine Hardlinks kann.

Sowas in der Art habe ich auch gelesen und mich gewundert. Kann ich da nach helfen?

Beim Split muss es das zusammenfügen.
Bei mir(ohne split) wird das nicht verschoben obwohl dem nichts im Wege steht, weil es standartmäßig so gehandhabt wird.

**Comment by jbleyel** [comment]
Bitte einen neuen Issue machen .. den Timeshift Code haben wir noch nicht angepasst.
Nur die Timeshift Einstellungen sind neu.

**Comment by geeeeeeeeeee** [comment]
Ok danke Schönen Sonntag!

**Comment by geeeeeeeeeee** [comment]
Als Feature request?

**Comment by jbleyel** [comment]
Jo, weil Bug ist es offensichtlich nicht.
