### ISSUE TITLE
KODI 20 Beta 1 for Openatv 7.1

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2659]
Hi @nickersk hope you are fine!

Is it possible to compile the latest Kodi 20 Beta 1 Nexus for OPNATV 7.1 to allow some testing interface changes with some addons ? 

At the moment the Kodi Nexus version on OPENATV 7.1 is at Alpha 1 version.

Thank you!

**Comment by nickersk** [comment]
Hi @ruipisco, we are working on huge oe core updates, with latest Kodi 20 updates too...Just takes some time to finish, build and test. Hold on, wip :-)

**Comment by ruipisco** [comment]
Hi @nickersk ok i will wait to test it! Thank you once more!!!
