### ISSUE TITLE
Zgemma H9S Dolby-Digital Downmix

### ISSUE THREAD

**Issue by Kerberos1864** [openatv/enigma2#2672]
This problem is not bound by a specific version of openatv because it was tested on all versions on Zgemma H9S.
When Dolby-Digital Audio downmix to stereo option is set to "NO", we can't control volume any more even we decrease or increase the volume doesn't change.

**Comment by atvcaptain** [comment]
with other images works only ATV have this issue ?

**Comment by ozone1864** [comment]
@atvcaptain I haven't tried any other images. I only use openATV since I bought the receiver.
Do you think its Zgemma related ?
Cause after you downmix dolby-digital you can change volume and see it changing on screen but nothing happens

**Comment by Papi2000-new** [comment]
That cannot function. Downmix = off means signal unchanged passthrough. There has been no change since ever...
You can step down to1 without level cahnge. at step down to 0 ir will be switched off.
0 = 0
1-100 = 100% pegel
