### ISSUE TITLE
[Feature Request] `Show record indicator` - Add `Red event name` option

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2699]
When `show picons in service list` is set to `yes` and `Show channel numbers in channel selection` is set to `no`, the only usable `Show record indicator` option is `Right/Left of service name`, which will show a red disc between the picon and event name.

Current:
![1_0_19_CD5F_844_2_11A0000_0_0_0_20221204235325](https://user-images.githubusercontent.com/9741693/205523746-7e405dea-bbf3-4b1f-91e8-bd099e934114.jpg)

Desired:
![1_0_19_CD5F_844_2_11A0000_0_0_0_20221204235325-](https://user-images.githubusercontent.com/9741693/205523756-3804d038-9ad8-49c3-bb6a-bd8414d27851.png)

**Comment by jbleyel** [comment]
This will be completely changed and refactored.

**Comment by jbleyel** [comment]
This needs to be done by the skinner in the future.
