### ISSUE TITLE
Menu - Information - Scroll inconsistent

### ISSUE THREAD

**Issue by geeeeeeeeeee** [openatv/enigma2#2702]
All items in menu->info are module="Information" except for module="ServiceInfo".
module="ServiceInfo" have a different list type and are controlled differently.
module="Information" Up Down for scroll
module="ServiceInfo" Left Right for scroll

**Comment by jbleyel** [comment]
This is by design because the ServiceInfo is a complete different Screen.

**Comment by wedebe** [comment]
From a user experience point of view, this doesn't make sense, regardless of technical implementation.

**Comment by geeeeeeeeeee** [comment]
For me it's OK, a to do/comment for ServiceInfo.

**Comment by GhostofGeeeee** [comment]
This is [fixed](https://github.com/openatv/enigma2/commit/19f322e90f5bc90451e7e3567b0aef053405eac3).
