### ISSUE TITLE
Cant select new installed OSCam

### ISSUE THREAD

**Issue by romestylez** [openatv/enigma2#2705]
Since a few weeks there is a problem when you install a new OSCam version.

After installing the newest OSCam version lets say from Mohamed_OS - which is uninstalling the old version - when i then try to change the softcam via "Blue button" -> "Softcam" -> "Select softcam" 

![image](https://user-images.githubusercontent.com/7427681/206432845-689bdacf-30cc-48ed-af30-1d02b800f85c.png)

i end up in an infinity loop "Restarting softcam... Please wait"

![image](https://user-images.githubusercontent.com/7427681/206432127-7e520c69-3ad1-4dee-a67c-db7e81f65627.png)

There seems to be a bug that the old selected version needs to be present when changing from this version to the new version.

When i change the version to a other version and then update the version from Mohamed_OS i can select the new version.

I also tried to select the version from the feed and then update this version and try to select the new version i end up in a loop so its not a problem with the OSCam version from Mohamed or OSCam itself. It seems to be openATV related.

**Comment by jbleyel** [comment]
Mohamed_OS : What's this?

**Comment by romestylez** [comment]
A guy making OSCam versions at linuxsat-support

But like ive said its the same error with every version even the version from the feed.

If you select a softcam lets say from Mohamed_OS and uninstall it you cant select any another Softcam in the menu as youll end up in a loop.

**Comment by sgse** [comment]
> A guy making OSCam versions at linuxsat-support

Just ask this guy. :-)

**Comment by romestylez** [comment]
Nice answer... Ohhhhh wait let me quote myself

"Even when you select the version vom the feed and uninstall it and then install another version you cant select that new version."

You understand thats not a problem with his OSCam Version ? You can even replicate that problem with any other OSCam !

**Comment by romestylez** [comment]
No one else here got this problem ? When i check other forums like https://www.linuxsat-support.com/ there are a lot of people having this problem with openATV 7.1 and openATV 7.2

**Comment by jbleyel** [comment]
Please provide crashlog if exists and debug log.

**Comment by romestylez** [comment]
> 

Sadly there is no crash. Its just loading forever. I even waited like 2 hours but its just on this screen:

https://user-images.githubusercontent.com/7427681/206432127-7e520c69-3ad1-4dee-a67c-db7e81f65627.png

You can easy force this error to happen.

1.) Install a old OSCam
2.) Select this old version in the Softcam panel and save
3.) Install a new version and uninstall the old version
4.) Try to select the new version in the Softcam panel

It will forever stay on the screen which you can see on my first post. Like i have said it seems like when you try to select the new version openATV is trying to find the old version or something and its not saving.

**Comment by Papi2000-new** [comment]
Before deinstalling a softcam, it should be deactivated in the panel, to be shure the content of /etc/enigma2/settings stays consitent.
Before installing a new softcam with perhaps the same name, the old one should be deinstalled (after deactivating). Do not deinstall a softcam after installing a new one, if you don't know whatever the packages do.

**Comment by romestylez** [comment]
A few month/weeks back i could just install the newest version and then select it press save and done.

But since i dont know when you have to deactivate the old version before installing the new one and i dont see any sense in this. When im going to select the new version in the Softcam panel and click save just save the settings and good. But thats not working but it was working before !

This brings a lot of trouble when you are using a script to update to the newest OSCam as you cant deactivate the old version via this script.

**Comment by romestylez** [comment]
Even if i delete "config.misc.softcams=OSCam_11718-r798" from the settings i can see the actual version im using in the Softcam panel.

So from where the Softcam panel is taking the version used ? Then i maybe could change my script to directly set the version there.

But as i have said a few weeks ago it was possible just to install the newest version with a different name and uninstall the old version and then just select the new version in the Softcam panel. Thats how it should be like when i select a new version just do the settings as the Softcam panel is already reconizing the new version as its shown in the select. So i dont know why its then stuck when i press save.

**Comment by jbleyel** [comment]
I cannot reproduce your problem:
1. Install -stable and -trunk
2. Goto Softcam settings and stable
3. remove -stable
4. Goto Softcam settings and you will see "None" then select trunk and DONE.

No crash , No hang , No issue

**Comment by romestylez** [comment]
I have tested with some OScams which have names like "OSCam Version XXXX" and the new Version just changes the name and uninstalls the old one. And im not able to select the new installed version as the old version which isnt installed anymore is still selected.

And like ive said its not just me. But ok then i have to live with this and deselect the old version before installing a new one.

**Comment by jbleyel** [comment]
There is no such ipk on the feed.
How exactly do you install and remove these ipk’s.

**Comment by romestylez** [comment]
Im using this version

https://www.linuxsat-support.com/thread/143590-latest-oscamemu-for-all-images-mips-arm-sh4-ipk-deb-download-only-no-chat/?postID=700340#post700340

Downloading an older ipk then the newest and you will see the same problem. Its the same with every OSCam installed via ipk i have tested. You cant choose the new version after the old is uninstalled. This problem wasnt there a few weeks ago. Sadly all other people just accept this problem and just complain in the forum linked above but not reporting it here.

**Comment by jbleyel** [comment]
That's the problem, you are using 3rd party ipk and not from the feed.
The Softcam settings Screen is not prepared to use 3rd party ipk.

Please provide the output of this :

`ls -la /etc/init.d/softcam*`

**Comment by romestylez** [comment]
Okay but it was working thats why im wondering ;)

> root@vuzero:~# ls -la /etc/init.d/softcam*
lrwxrwxrwx    1 root     root            24 Dec 27 12:05 /etc/init.d/softcam ->                                                                                                                                                              softcam.OSCam_11718-r798
-rwxr-xr-x    1 root     root            25 Dec 27 12:04 /etc/init.d/softcam.Non                                                                                                                                                             e
-rwxr-xr-x    1 root     root           836 Dec 27 12:04 /etc/init.d/softcam.OSC                                                                                                                                                             am_11718-r798
-rwxr-xr-x    1 root     root           649 Jul  9 16:10 /etc/init.d/softcam.Osc                                                                                                                                                             am

Right now its working but if needed i can just install a old version to provoke the error or you try it yourself. When its not wanted to use 3rd party ipks for OSCam then im fine and its just sad its not working like it did before.

Thanks for your help !

**Comment by jbleyel** [comment]
Is this the correct output?
You have spaces in the file names.

**Comment by jbleyel** [comment]
Please install a new version and provide the ls.
Then remove the old and provide the ls again.

**Comment by romestylez** [comment]
Newest version is installed.

when i install a old version the actual version will be uninstalled

**Comment by jbleyel** [comment]
Softcam settings Screen reads the files `/etc/init.d/softcam*` on start.
The current selected is the link target of `/etc/init.d/softcam`.
I don't see any issue if the file in `/etc/init.d` are correct.

**Comment by jbleyel** [comment]
You are right. The link is wrong.
This needs to fix in the installation script of the ipk.

**Comment by romestylez** [comment]
Has nothing to do with the installation Script as its for all other ipks also. When you choose the new version the old link gets deleted but the new links isnt created nothing related to the ipk as the Softcampanel is creating this link ?

**Comment by jbleyel** [comment]
Please try this:

https://gist.github.com/jbleyel/edcfd35e9b15d9b644e4fd0ccf759c18#file-softcamsetup-py

**Comment by Schimmelreiter** [comment]
The link is there from the very beginning, linking to softcam.None
Each Softcam ipk is supposed to add its own startup *script* and leave the link alone, except it is set to "None", so the first cam auto-activates itself.
When the ipk gets uninstalled it sets the "softcam" link to "None" again, when it was the active cam or leaves the link untouched when a different cam was active.

**Comment by romestylez** [comment]
But when the file is there linking to a non existing file shouldnt be the Softcampanel so resistant and just create it linked to the version you have selected ?

I mean in my eyes that would be the most stable way.

**Comment by jbleyel** [comment]
How can I know the correct target if the link is wrong?
There is no module called "cristal ball".
There is no way to fix this if you have more than one.

**Comment by Schimmelreiter** [comment]
The link **is** the selection.

**Comment by romestylez** [comment]
> 

Why cristal ball ? I select the new Version so Softcampanel should just create the link to the selected version. What happens now is i select the new version the link gets deleted but the new link isnt created. Or iam thinking the wrong way that it should be clear where the link should point when i select the version from the Softcampanel

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/1d123298305e44bba96fca9d81e541b845dad879

**Comment by romestylez** [comment]
Could you let me know how to test ? Just download the py files and upload them to the box and restart it ?

**Comment by jbleyel** [comment]
Download the new files and copy to the correct target folder on your box.
Then reboot.

**Comment by romestylez** [comment]
I can just name them .py and after reboot they should be compiled to pyc or ? Thats not working :-/

**Comment by jbleyel** [comment]
Do you have the latest 7.2 Image?

**Comment by romestylez** [comment]
Ah no im on openATV 7.1 as i didnt want to use a beta. Should i switch ?

**Comment by jbleyel** [comment]
The latest 7.1 is also OK.

**Comment by jbleyel** [comment]
You should update your box first and then copy the 2 py files.
compile all is not needed

**Comment by romestylez** [comment]
I need to switch to 7.2 can do this when im back home as im on vacation and just have remote access. I had to compile both files but still not working on 7.1 i will then try end of the week with a update to 7.2

**Comment by jbleyel** [comment]
Please run :

```
opkg update
opkg upgrade

```
and then reboot.
Then you should have the lastest updates from 7.1

**Comment by romestylez** [comment]
I did that already and then just replace the files with your two files correct ? Wasnt working as something was missing in the SystemInfo.

Will try again tomorrow. Thx for your help !

**Comment by romestylez** [comment]
@jbleyel Updated to openATV 7.1 copied your files and now i can upgrade/downgrade how ever i want ! The Softcampanel shows "none" when the symlink is deleted.

Thats a nice fix thank you for that !!
