### ISSUE TITLE
[BUG] Full EPG - Wrong bouquet name when user zaps to a non-bouquet channel 

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2717]
Recreate:
- zap to a channel in (eg.) `Favourites` bouquet
- open Full EPG

Observe:
- title says `<    Favourites    >`
- channel list is correct for contents and order

Now:
- close Full EPG
- open `Channel List` (using `UP` or `DOWN` button
- press `RED` ('All')
- zap to a channel that's not in a bouquet
- open Full EPG

Issue:
- EPG title has kept name of bouquet that was previously selected (eg. in this case: `<    Favourites    >`), but channel list is seemingly random.
- Pressing `Previous` button then goes to relevant bouquet with correct title and correct list of channels

Resolution:
- an appropriate `<    Title    >`

**Comment by GhostofGeeeee** [comment]
No Bug and not a real Issue but maybe a question, please let me add this. (For all 3 multi-EPG's)
In my case it shows "<    favourites    >"(not "<    Favourites    >")
I think we need titles like _("Favorites"), _("All Services"), _("Providers"), _("Reception Lists") and their subs.
(A good point is that on a "press RED ('All')"-Channel the switch bouquet keys let you choose/change to the singlebouquet)

**Comment by IanSav** [comment]
I can't reproduce this issue.

I open ChannelSelection and press "All Services" (RED) and the select a service that is not in the current list, the Favourites (TV) bouquet, and reopen the EPG and I see the bouquet is called "Terrestrial".  This happens to be the default bouquet that is created by TerrestrialScan code that performed the original DVB-T scan.  (This bouquet contains all the services discovered during the scan.)

If it is a requirement that the target service is in NO bouquets then I suggest that fact be added to the original bug report.  :)

As for the name of the BLUE button in the ChannelSelection screen, this will be changed to the name "Bouquets" in the next change to the code.  This new name far better represents the content behind this button.  @jbleyel tells me that this will remain "Favourites" in the German translation as the word means the same thing.  :)

**Comment by IanSav** [comment]
@GhostofGeeeee, the bouquet name "Terrestrial" is created by the "Terrestrial Scan" plugin that is used in DVB-T service scanning.

**Comment by jbleyel** [comment]
This problem is deeper.
Any multi channel EPG view is not prepared for "all channels" because this is not a bouquet.

**Comment by jbleyel** [comment]
Hi @wedebe , Please get the latest devel build and then try this:

[InfoBarGenerics.py.zip](https://github.com/openatv/enigma2/files/15210817/InfoBarGenerics.py.zip)

**Comment by GhostofGeeeee** [comment]
This is not deeper but more precise then mine!

**Comment by jbleyel** [comment]
> This is not deeper but more precise then mine! I agree with this([InfoBarGenerics.py.zip](https://github.com/openatv/enigma2/files/15210817/InfoBarGenerics.py.zip)).
> 
> But include this too. [#3309 (review)](https://github.com/openatv/enigma2/pull/3309#pullrequestreview-2039322349)

NO

**Comment by jbleyel** [comment]
Please take the latest devel build and test again.
