### ISSUE TITLE
[BUG] [SF8008M] decoding problem after update

### ISSUE THREAD

**Issue by gurek** [openatv/enigma2#2720]
Hi,

after update octagon-reader-sf8008m and reboot my box have a problem with image decoding. After a few switches, even FTA channels and movies from the disk do not work.

Downgrade octagon-reader-sf8008m from 20221216-r0 to 20200612-r0 solving a problem.

**Comment by Papi2000-new** [comment]
Yes - known problem, and downgrading helps for the moment.
Do not make upgrades, until new drivers available.
Problem allready reported to the DEV.

**Comment by atvcaptain** [comment]
i get new updates, its fixed, wait now for drivers for all models
