### ISSUE TITLE
I' tested the least version and same Error crash SoftcamSetup

### ISSUE THREAD

**Issue by MOHAMED19OS** [openatv/enigma2#2727]
I' tested the least version and same Error

[20221225-094025-enigma-crash.log](https://github.com/openatv/enigma2/files/10299624/20221225-094025-enigma-crash.log)

_Originally posted by @MOHAMED19OS in https://github.com/openatv/enigma2/issues/2726#issuecomment-1364646248_

**Comment by jbleyel** [comment]
Please provide step by step : How to reproduce the crash.

**Comment by jbleyel** [comment]
We also need the debug log.

**Comment by jbleyel** [comment]
I need step by step how to reproduce the crash and the debug log.

**Comment by jbleyel** [comment]
Should be fixed with the last changes
