### ISSUE TITLE
BUG: Can't install Kodi (20-r0) - openATV 7.2 (2023-01-04)

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2743]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Yes - 7.2 (2023-01-04)

**Describe the bug / Actual behaviour:**
Attempting to install Kodi fails with error

**Expected behaviour:**
Kodi should install successfully

**Has this issue started to happen just recently?**
If yes, roughly when did it last work fine for you?
Yes, worked up to at least 7.2 (2022-12-16), which was the version I previously had installed.

**To reproduce:**
Go to plugin manager and add `Kodi (20-r0)` from `Extensions` list

**Screenshots**
![1_0_1F_1CE9_7F6_2_11A0000_0_0_0_20230104131737](https://user-images.githubusercontent.com/9741693/210787941-84bb872f-9de7-4366-9a34-afaea9b08033.jpg)

**Image (please complete the following information):**
 - Version: [e.g. 7.2]

**Additional context**
7.1 (2023-01-03) and 7.0 (2022-12-31) are unaffected.
Mut@nt HD51

**Comment by atvcaptain** [comment]
boxname please

**Comment by wedebe** [comment]
Mut@nt HD51

**Comment by atvcaptain** [comment]
please check again feed  sync issue fixed for hd51
