### ISSUE TITLE
OPENATV 7.2 KODI 20 NEXUS

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#2752]
*!* Before you log an issue, have you updated to the most recent version? Yes i am running the latest update of OPENATV 7.2 day 14-01-2023, i think it start hapening when the logaritmic steps configuration on audio settings of openatv was released.

**Describe the bug / Actual behaviour:**
No audio in KODI interface and on external player while playing an movie. Have default settings on OPEN ATV Audio and on definitions  under Kodi System-> Audio Configuration.

**Expected behaviour:**
Ear interface audio on menu navigation and on movie playback on external E2Player.

**Has this issue started to happen just recently?**
No, on Open ATV 7.1 it hapened to since around the 15 of September of 2022 Update.

**To reproduce:**
after an fresh installation of open atv 7.2, install kodi 20 extension and open it without any configuration change under openatv configuration and under kodi settings and you will notice that the interface navigation has no sound while navigating in the interface and the issue repeats under the playback of a movie.

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - Version: OPEN ATV 7.2
 - BoxModel: VuPlus Zero 4K

**Additional context**

**Comment by ruipisco** [comment]
@jbleyel or @nickersk can anyone help with this issue?

**Comment by jbleyel** [comment]
I cannot help here because I don’t use Kodi.

**Comment by ruipisco** [comment]
@nickersk can you help?

**Comment by nickersk** [comment]
hello, i dont have vuzero box to test on, what is content of /tmp/kodi/kodi.log? before starting kodi, try to remove hidden .kodi folder both from home and if using external hdd from /hdd/ too, then try to play something ...

**Comment by ruipisco** [comment]
@nickersk is it possibele to compile the new stable version of kodi that solves video playback issues for vuplus for OPENATV 7.2? thanks

**Comment by atvcaptain** [comment]
new version in 7.3

**Comment by ruipisco** [comment]
The interface UI Suonds does not work, but to play videos properly with soiund and the external E2Player need to go to OpenAtv 7.3 Settings->Sound-Sound Settings and set the bellow options values like:

3D Surround-> HDMI
3D Surround Speaker Position -> center
Auto Audio Volume Level -> HDMI
