### ISSUE TITLE
OpenATV 7.2 - servicemp3 generate thread error

### ISSUE THREAD

**Issue by mtester270** [openatv/enigma2#2755]
**Describe the bug / Actual behaviour:**
When start live stream (proxy) with servicemp3 (4097) player than in the debug console it throw thread error below. It occurs when content of a stream was handled/provided by local thread server so in the e2 code something must generate some not thread safe operation this i just guessing...
(when i change player to 5002 than no thread error occure so the issue must be somewhere in embended player.
In old atv6.4/py2 is the same behaviour.)

> 12:08:48.4181 [eRCDeviceInputDev] 1 160 1
12:08:48.4185 [InfoBarGenerics] Key 'KEY_OK' (352) Make.
12:08:48.4187 [ActionMap] Map context 'OkCancelActions' -> Action 'ok'.
12:08:48.4194 [Navigation] playing ref 4097:0:1:1:0:0:0:0:0:0:http%3a//127.0.0.1%3a1111/channel/555
12:08:48.4200 [eDVBCAService] free slot 0 demux 0 for service 1:0:19:13A7:3EA:1:C00000:0:0:0:
12:08:48.4202 [eDVBCAService] free service 1:0:19:13A7:3EA:1:C00000:0:0:0:
12:08:48.4235 [eTSMPEGDecoder] decoder state: play, vpid=ffffffff, apid=ffffffff
12:08:48.4236 [eDVBPCR0] DEMUX_STOP ok12:08:48.4237 [eDVBPCR0] destroy
12:08:48.4237 [eDVBVideo0] DEMUX_STOP  ok12:08:48.4237 [eDVBVideo0] VIDEO_STOP ok12:08:48.4238 [eDVBVideo0] destroy
12:08:48.4239 [eDVBAudio0] AUDIO_STOP ok12:08:48.4239 [eDVBAudio0] DEMUX_STOP ok12:08:48.4239 [eDVBAudio0] AUDIO_CONTINUE ok12:08:48.4239 [eDVBAudio0] destroy
12:08:48.4240 [eDVBText0] DEMUX_STOP okTuxTxt stopped service 7ac
12:08:48.4309 [eDVBText0] destroy
cleaning up
TuxTxt cache cleared
12:08:48.4328 [eDVBResourceManager] start release channel timer
12:08:48.4538 [eServiceFactoryMP3] **** dvb_audiosink created ***
12:08:48.4673 [eServiceFactoryMP3] **** dvb_videosink created ***
12:08:48.4745 [eServiceFactoryMP3] **** dvb_subsink created ***
12:08:48.4746 [eServiceFactoryMP3] ****new play service total services played is 1****
12:08:48.4749 [eServiceMP3] playbin uri=http://127.0.0.1:1111/channel/555
12:08:48.5341 [eServiceMP3] *** starting pipeline ****
12:08:48.5365 [Screen] Showing screen 'InfoBarSummary'.
12:08:48.5388 [eServiceMP3] ****STATE TRANSITION NULL -> READY ****
12:08:48.5451 [Screen] Showing screen 'InfoBar'.
12:08:48.5457 [Screen] Showing screen '['InfoBarMetrixWeather1']'.
12:08:48.5666 [eServiceMP3] pause(ePtr<iPauseableService> &ptr)
12:08:48.5668 [Pixmap] setPixmapNum(0) failed!  Defined pixmaps: [].
12:08:48.5678 [eServiceMP3] pause(ePtr<iPauseableService> &ptr)
12:08:48.5680 [Pixmap] setPixmapNum(0) failed!  Defined pixmaps: [].
12:08:48.5687 [Notifications] RemovePopup id = ZapError
12:08:52.5419 [gRC] Warning: Main thread is busy, displaying spinner!
12:08:53.7355 [eServiceMP3] PLAYBIN WITH BLOCK READY TO PAUSED state:READY pending:PAUSED ret:ASYNC
12:08:53.7361 StackTrace
12:08:53.7480 [DVBCAHandler] no more services
12:08:53.7506 [eDVBResourceManager] release cached channel (timer timeout)
12:08:53.7507 [eDVBLocalTimerHandler] Remove channel 0x2fe74b0.
12:08:53.7507 [eEPGTransponderDataReader] remove channel 0x2fe74b0
12:08:53.7514 [eDVBResourceManager] stop release channel timer
12:08:53.7597 [eRCDeviceInputDev] 0 160 1
12:08:53.7600 [InfoBarGenerics] Key 'KEY_OK' (352) Break.
12:08:56.7518 [eDVBFrontend] try to close frontend 0
12:08:56.7692 [eDVBFrontend0] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 0 FE_SET_VOLTAGE 2
12:08:57.6174 ========== Stacktrace of active Python threads ===========
12:08:57.6175 ========== Thread ID  0xaaeff3c0 =========================
12:08:57.6175 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6176 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6176 File: "/usr/lib/python3.11/threading.py", line 975, in run
12:08:57.6176 File: "/usr/lib/python3.11/site-packages/twisted/_threads/_threadworker.py", line 46, in work
12:08:57.6177 File: "/usr/lib/python3.11/queue.py", line 171, in get
12:08:57.6177 File: "/usr/lib/python3.11/threading.py", line 320, in wait
12:08:57.6177 ========== Thread ID  0xac2ff3c0 =========================
12:08:57.6178 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6178 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6179 File: "/usr/lib/python3.11/queue.py", line 171, in get
12:08:57.6179 File: "/usr/lib/python3.11/threading.py", line 320, in wait
12:08:57.6180 ========== Thread ID  0xaccff3c0 =========================
12:08:57.6180 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6180 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6181 File: "/usr/lib/python3.11/threading.py", line 975, in run
12:08:57.6182 File: "/usr/lib/python3.11/site-packages/waitress/task.py", line 72, in handler_thread
12:08:57.6182   self.queue_cv.wait()
12:08:57.6183 File: "/usr/lib/python3.11/threading.py", line 320, in wait
12:08:57.6183 ========== Thread ID  0xa34f13c0 =========================
12:08:57.6183 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6184 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6184 File: "/usr/lib/python3.11/threading.py", line 975, in run
12:08:57.6184 File: "/usr/lib/python3.11/site-packages/waitress/task.py", line 72, in handler_thread
12:08:57.6185   self.queue_cv.wait()
12:08:57.6185 File: "/usr/lib/python3.11/threading.py", line 330, in wait
12:08:57.6185 ========== Thread ID  0xa2cf03c0 =========================
12:08:57.6186 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6186 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6186 File: "/usr/lib/python3.11/threading.py", line 975, in run
12:08:57.6187 File: "/usr/lib/python3.11/site-packages/waitress/task.py", line 72, in handler_thread
12:08:57.6187   self.queue_cv.wait()
12:08:57.6187 File: "/usr/lib/python3.11/threading.py", line 330, in wait
12:08:57.6188 ========== Thread ID  0xa24ef3c0 =========================
12:08:57.6188 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6188 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6189 File: "/usr/lib/python3.11/threading.py", line 975, in run
12:08:57.6189 File: "/usr/lib/python3.11/site-packages/waitress/task.py", line 72, in handler_thread
12:08:57.6189   self.queue_cv.wait()
12:08:57.6190 File: "/usr/lib/python3.11/threading.py", line 320, in wait
12:08:57.6190 ========== Thread ID  0xa1cee3c0 =========================
12:08:57.6190 File: "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
12:08:57.6191 File: "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
12:08:57.6191 File: "/usr/lib/python3.11/threading.py", line 975, in run
12:08:57.6192 File: "/usr/lib/python3.11/site-packages/waitress/__init__.py", line 18, in serve
12:08:57.6193   server.run()
12:08:57.6193 File: "/usr/lib/python3.11/site-packages/waitress/server.py", line 329, in run
12:08:57.6193   self.asyncore.loop(
12:08:57.6194 File: "/usr/lib/python3.11/site-packages/waitress/wasyncore.py", line 247, in loop
12:08:57.6194   poll_fun(timeout, map)
12:08:57.6195 File: "/usr/lib/python3.11/site-packages/waitress/wasyncore.py", line 193, in poll
12:08:57.6196   for fd in e:
12:08:57.6196 File: "/usr/lib/python3.11/site-packages/waitress/wasyncore.py", line 106, in read
12:08:57.6196   obj.handle_read_event()
12:08:57.6197 File: "/usr/lib/python3.11/site-packages/waitress/wasyncore.py", line 493, in handle_read_event
12:08:57.6197   self.handle_accept()
12:08:57.6197 File: "/usr/lib/python3.11/site-packages/waitress/server.py", line 325, in handle_accept
12:08:57.6198   self.channel_class(self, conn, addr, self.adj, map=self._map)
12:08:57.6198 File: "/usr/lib/python3.11/site-packages/waitress/wasyncore.py", line 429, in accept
12:08:57.6198   return conn, addr
12:08:57.6199 File: "/usr/lib/python3.11/socket.py", line 300, in accept
12:08:57.6199 ========== MainThread 0xb4e94700 =========================
12:08:57.6199 File: "/usr/lib/enigma2/python/StartEnigma.py", line 950, in <module>
12:08:57.6200   runScreenTest()  # Start running the first screen.
12:08:57.6200 File: "/usr/lib/enigma2/python/StartEnigma.py", line 440, in runScreenTest
12:08:57.6200   runReactor()
12:08:57.6201 File: "/usr/lib/enigma2/python/StartEnigma.py", line 615, in runReactor
12:08:57.6203   reactor.run(installSignalHandlers=False)
12:08:57.6204 File: "/usr/lib/python3.11/site-packages/twisted/internet/base.py", line 1318, in run
12:08:57.6204 File: "/usr/lib/python3.11/site-packages/twisted/internet/base.py", line 1331, in mainLoop
12:08:57.6204 File: "/usr/lib/enigma2/python/e2reactor.py", line 167, in doPoll
12:08:57.6205 File: "/usr/lib/enigma2/python/e2reactor.py", line 48, in poll
12:08:57.6205 ========== Stacktrace end ================================
12:08:57.9594 [eServiceMP3] ****STATE TRANSITION READY -> PAUSED ****
12:08:57.9614 [eServiceMP3] PLAYBIN WITH BLOCK PLAYSTART state:PLAYING pending:VOID_PENDING ret:SUCCESS
12:08:57.9619 [eServiceMP3] GST_MESSAGE_ASYNC_DONE before evUpdatedInfo
12:08:57.9727 [eServiceMP3] ** START USE LAST SEEK TIMER
12:08:57.9769 [VolumeAdjust] Normal volume is 3.
12:08:57.9773 [eServiceMP3] ****STATE TRANSITION PAUSED -> PLAYING ****

**Expected behaviour:**
Not generate any thread error.

**Has this issue started to happen just recently?**
no, its there long time (in openpli no error occurs)

**Image/Box Model (please complete the following information):**
 - Version: 7.2 latest

**Note:**
If exception doesn't tell anyone anything than feel free the close that bug.
(nevertheless the stream start playing normally, no errors on UI and but maybe a bit slower because the error)

**Comment by 4l3x2k** [comment]
It is **not** a thread error.

This output is normal when enigma2 shows the spinner and you have enabled "Log python stack trace on spinner" in the log settings. This should be the case by default.
If you no longer want to see these outputs in the log, then deactivate the log setting mentioned.

The spinner means that something is consuming enigma2 resources so that it can no longer continue. If such a weirdo occurs, all currently running Python threads are output. That's what you see in the log.
So the spinner is a sign that thread safety is given. The system waits until the corresponding resources are free and available again.

In this case you can see, for example, that "python waitress" is blocking itself to ensure thread safety.
So if there are problems, it is not the fault of enigma2 but of the previously mentioned Python package.

According to your statement, the stream is running. Therefore this issue can be closed.

**Comment by mtester270** [comment]
Thanks for nice and clear clarification
