### ISSUE TITLE
OpenATV7.2 - eConsoleAppContainer not working properly

### ISSUE THREAD

**Issue by mtester270** [openatv/enigma2#2756]
**Describe the bug / Actual behaviour:**
When plugin use eConsoleAppContainer and add callbacks to stdoutAvail, stderrAvail, appClosed then not possible to receive a message after write to sys,stdout, for me it looks like dont wanna wait after write was complete or maybe write data was gone. Its from plugin subssupport (searchsubs.py - methods send|recieve). Maybe the issue is somewhere else but same code runs on atv71 and on atv72 not.

**Expected behaviour:**
get data from stdin which i write to stdout before

**Has this issue started to happen just recently?**
Yes, in atv71 (version 24.9.22) it works without issues and also in atv71 (latest, 17.1.2023)

**To reproduce:**
look at the subssupport plugin (searchsubs.py and subtitles.py-> class SubsSearchProcess ... etc. in case when data['message'] == Messages.MESSAGE_DELAY_CALLBACK

**Image/Box Model (please complete the following information):**
 - Version: 7.2 latest for 18.01.23

**Additional context**
I guess the problem is in eConsoleAppContainer but of course i could be wrong

**Comment by jbleyel** [comment]
eConsoleAppContainer in 7.1 and 7.2 is 100% identical.
The difference of 7.1 and 7.2 is only the python version.

**Comment by mtester270** [comment]
Ok thanks for the chceck. So the reason is python.
Closing
