### ISSUE TITLE
EGP won't scroll in SecondInfoBar screen

### ISSUE THREAD

**Issue by pizzelnet** [openatv/enigma2#2758]
Hi! After installing openATV 7.2, I have noticed that by pressing both keys up and down the epg description widget does not scroll (when event length makes it scrollable) despite displaying the scroll bar. This does not happen in version 6.4 (the one I had been using so far).

1. Make sure to switch to TV service that has a long event description.
2. Press 'OK' to open 'SecondInfobar' (this key behavior must have been previously set up).
3. Providing that a scroll bar is displayed, press 'KEY_UP' or 'KEY_DOWN'.
4. See result/error: nothing happens in screen.

I have tried different skins with both widgets "FullDescription" and "epg_description".

It seems to take the key action from 'InfobarChannelSelection' and not from '2ndInfobarActions':

00:50:28.7751 [InfoBarGenerics] Key 'KEY_UP' (103) Make.
00:50:28.7834 **[ActionMap] Map context 'InfobarChannelSelection' -> Action 'switchChannelUp'.**
00:50:28.8753 [eRCDeviceInputDev] 0 67 1
00:50:28.8758 [InfoBarGenerics] Key 'KEY_UP' (103) Break.
00:50:29.8774 [eRCDeviceInputDev] 1 6c 1
00:50:29.8780 [InfoBarGenerics] Key 'KEY_DOWN' (108) Make.
00:50:29.8859 **[ActionMap] Map context 'InfobarChannelSelection' -> Action 'switchChannelDown'.**
00:50:29.9782 [eRCDeviceInputDev] 0 6c 1
00:50:29.9789 [InfoBarGenerics] Key 'KEY_DOWN' (108) Break.

 - Version: 7.2
 - BoxModel: SF8008

**Comment by jbleyel** [comment]
Is this fixed?
