### ISSUE TITLE
OpenATV 5.1 There is no HDMI Colorspace option

### ISSUE THREAD

**Issue by EXcomZkko** [openatv/enigma2#276]
Hello,

I'm using Golden Media 990 LX image. My problem is; there is no HDMI Colorspace option in video menu. 

Default one is RGB and it makes some detail loss on picture. (Especially darker areas) I can switch to YCbCr via "stfbcontrol hy" command but I have to do it after every reboot.

I saw some images that have this option in menu.

Thanks.

**Comment by atvcaptain** [comment]
please check plugin: enigma2-plugin-systemplugins-videoenhancement, with this plugin more option possible

**Comment by EXcomZkko** [comment]
Tried it already. Those plugin says "no such file or directory cat can't open /proc/stb/video/hdmi_colorspace_choice".

I've checked /proc/stb/video/ directory myself. "hdmi_colorspace_choices" and "hdmi_colorspace" files are does not exist.

**Comment by atvcaptain** [comment]
then not exist the drivers dont support this

**Comment by EXcomZkko** [comment]
I see...

Thank you again.

**Comment by sklnet** [comment]
Check if new drivers work with videoenhancement plugin.

**Comment by EXcomZkko** [comment]
I've tried latest build now, and no luck.

**Comment by sklnet** [comment]
You have to wait until the new build is finished and pt in the feed. Try again later.
