### ISSUE TITLE
Multi-EPG `REC` button `Add Record Timer` doesn't honour `config.usage.timer_path`

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2761]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Yes

**Describe the bug / Actual behaviour:**
Multi-channel EPG `Add Record Timer` uses `/media/hdd/movie` by default, but this isn't set or settable anywhere.

**Expected behaviour:**
Ability to set a pref for EPG timer default path

**Has this issue started to happen just recently?**
Not that I'm aware of (previously used /hdd so didn't notice the issue)

**To reproduce:**
1. In multi-channel EPG, press `[REC]` button
2. Select an upcoming event
3. Select `Add a Record Timer`
4. Check timer location/path

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - OpenATV7.2
 - Mut@nt HD51

**Additional context**
Using `Green` button `Add Timer` works as expected

```
config.misc.epgcachepath=/media/mmc/
config.movielist.last_timer_videodir=/media/usb/movie/
config.movielist.videodirs=['/media/mmc/movie/', '/media/hdd/movie/', '/media/usb/movie/']
config.usage.instantrec_path=/media/usb/movie/
config.usage.timer_path=/media/usb/movie/
```

**Comment by jbleyel** [comment]
I can reproduce this.

The question is:
Should we use the instand record path setting for this action or the normal timer record path?

**Comment by wedebe** [comment]
> The question is: Should we use the instand record path setting for this action or the normal timer record path?

I reckon `instantrec_path` should _only_ be used for immediate recordings (outside of any EPG).

`timer_path` is what should be used here... although... the question of which pref `Record Now` from the channel list then arises (probably best to keep that as it is).

**Comment by jbleyel** [comment]
Then we can close because it's fixed.
