### ISSUE TITLE
[Timeshift] - Save - Don't copy

### ISSUE THREAD

**Issue by ghost** [openatv/enigma2#2763]
Es gibt "Timeshift-Dateien sendungsbasiert aufteilen"/"config.timeshift.filesplitting". (Standard: Ja)
Mit "Nein" kann man das splitten also verhindern aber:
Beim Timeshift beenden und "Ja, als Aufnahme speichern und stoppen." wird die Aufnahme nicht einfach verschoben, sondern immer kopiert. Das dauert und bringt nichts, den die Datei vorher und nachher ist gleich nur mit anderem Namen.

**Ist Ihr Verbesserungsvorschlag ein Problem?**
Ja, ich nutze deswegen kein Timeshift, um das unnötige kopieren zu verhindern.

**Lösung:**
Einfach nur umbenennen und nicht kopieren.

**Alternativen:**
Auf Timeshift verzichten.

**Comment by jbleyel** [comment]
Passiert das wirklich nur bei wenn "config.timeshift.filesplitting" auf JA steht?

**Comment by geeeeeeeeeee** [comment]
Was bei JA passiert? Das interessiert mich wenig.
Da würde ich aber akzeptieren, dass es aus den Teilen eine Datei macht, was heutzutage nur durch Datentransfer geschieht.
Ich will die Timeshift-Datei behalten ohne...
Alternativ muss ich das halt mit dem FileCommander machen!

**Comment by 4l3x2k** [comment]
Das sind mindestens 2 Themen auf einmal.

Woran siehst du das "kopiert" und nicht "verschoben" beziehungsweise "umbenannt" wird?

Ein Kopiervorgang zwischen mehreren Medien oder auch Partitionen ist unumgänglich. Dafür brauchst du ein sehr spezielles Setup, wenn das funktionieren soll.

**Comment by geeeeeeeeeee** [comment]
> Woran siehst du das "kopiert" und nicht "verschoben" beziehungsweise "umbenannt" wird?

Um so größer die Datei ist, umso langer dauert es.

> Ein Kopiervorgang zwischen mehreren Medien oder auch Partitionen ist unumgänglich. Dafür brauchst du ein sehr spezielles Setup, wenn das funktionieren soll.

Ich weiß nicht, ob es üblich ist den "timeshift"-Ordner auf einer anderen Partition als den "movie"-Ordner zu haben!

> Das sind mindestens 2 Themen auf einmal.

Kann ich nicht verstehen.

**Comment by GhostofGeeeee** [comment]
Bitte schließen.
Das dauert doch wegen was anderem(createapscfiles) so lange.

**Comment by jbleyel** [comment]
Ist das Problem behoben?

**Comment by GhostofGeeeee** [comment]
Es war keins! Aber ja.

**Comment by GhostofGeeeee** [comment]
Do you have an issue with `createapscfiles`?
