### ISSUE TITLE
Aufnahmen mit Taste-Rot

### ISSUE THREAD

**Issue by geeeeeeeeeee** [openatv/enigma2#2764]
[Hier](https://www.opena.tv/openatv-7-2-py3-11-openssl-3-07-current/61812-timer-doesnt-stop.html#post526857) 
hat sich einer gemeldet, ich hatte nun vorhin das Selbe aber schlimmer.

Nachstellen:
Rote Taste(Aufnahme beginnen?)
Aufnahme hinzufügen (Aufnahmeendzeit eingeben) 
Geänderte Zeit eingeben
Timerübersicht öffnen(Start- und Endzeit stimmen aber die Dauer in Minuten ist sehr seltsam)
Timeredit öffnen(zeigt wieder ganz andere Werte)

Nachstellen 2: (Wiederholung aus oben genanntem Thread)
Rote Taste(Aufnahme beginnen?)
Aufnahme hinzufügen (Aufnahmelänge eingeben) 
Keine Zeit eingeben und Abbrechen(So sollte eine 24h Aufnahme getätigt werden/unbegrenzt)
Timerübersicht öffnen(Start- und Endzeit stimmen aber die Dauer in Minuten ist sehr seltsam)
Timeredit öffnen(siehe Endzeit)

**Comment by jbleyel** [comment]
Bitte Screenshot wo man das Problem sehen kann.

**Comment by jbleyel** [comment]
2. ist mir nicht ganz klar.
Rote Taste -> Aufnahmelänge -> Exit ist nicht dafür gedacht um 24h aufzunehmen.

Dafür gibt es:
Rote Taste -> Aufnahme hinzufügen (unbegrenzt).

**Comment by geeeeeeeeeee** [comment]
Darum habe ich auch das "unbegrenzt" mit hingeschrieben. Aber so war dem ersten klar, dass dort etwas nicht funktioniert.
Ich mache Screenshots wenn sie wirklich? nötig sind aber nicht aus langerweile nur weil es besser? ist.
Die dauer wird korrekt angezeigt?
Lässt sich kein ungewolltes Verhalten nachstellen?
Ich hab da Sachen erlebt, die ich garnicht reproduzieren kann...

**Comment by jbleyel** [comment]
Bei Aufnahmeendzeit die falsche Anzeige hab ich bei mir schon gefixt.

Bei unbegrenzt ist ein Fehler, denn da wird nur die aktuelle Sendung aufgenommen.
Das werde ich auf 24h ändern.

Bei Aufnahmelänge + Exit sollten nur die aktuelle Sendung aufgenommen werden.
Das muss man noch mal prüfen.

**Comment by geeeeeeeeeee** [comment]
> Bei Aufnahmelänge + Exit sollten nur die aktuelle Sendung aufgenommen werden.
Das muss man noch mal prüfen.

Bei 6.4 waren es 24h somit wäre das ein neues Verhalten, was noch nicht fertig ist, OK


> Bei Aufnahmeendzeit die falsche Anzeige hab ich bei mir schon gefixt.

Das würde ich testen!
Um eventuelle noch kleinere Problem genauer Beschreiben zu können.

**Comment by jbleyel** [comment]
Bitte testen:
https://github.com/openatv/enigma2/commit/de91f941fc1c19997612dce38f9fa1c650c2a14a
