### ISSUE TITLE
Zap timer from standby immediately prompts to enter standby

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2773]
**Describe the bug / Actual behaviour:**
Zap timer from standby immediately prompts to enter standby

**Expected behaviour:**
- box should wake up and not prompt to enter standby

**Has this issue started to happen just recently?**
Possibly(?) related to a recent change for end-time-less zap timer

**To reproduce:**
- Set a zap timer (default settings, no end time) for an upcoming event
- Change channel and manually put box into standby
- Box wakes up when zap timer is initiated
- Prompt appears immediately (see screenshot), with timer to automatic standby

**Screenshots**
![1_0_1_27AB_805_2_11A0000_0_0_0_20230131230052](https://user-images.githubusercontent.com/9741693/215905018-4c28953c-eab7-4c0b-ab78-e0d9c0f8e797.jpg)

**Image/Box Model (please complete the following information):**
 - openATV 7.2.20230131 (2023-01-29)
 - Mut@nt HD51

**Additional context**
-

**Comment by jbleyel** [comment]
Are you sure.

The default of a zap timer has no end time from the very beginning.
There is probably an issue if you define an after event action.

**Comment by jbleyel** [comment]
We probably need to check the 6.4 code.

**Comment by wedebe** [comment]
My apologies, after years of owning an Enigma box,  I've just now realised what the `Auto` value of the ~After Event` setting does 😄

*(for reference, `Auto` returns the box to thee state it was in before the timer started).

**Comment by jbleyel** [comment]
No problem.
