### ISSUE TITLE
Mediaplayer crash if creating automatic playlist by button green

### ISSUE THREAD

**Issue by olwaldi** [openatv/enigma2#2775]
Mediaplayer crashes if one tries to add a directory with MP3 files to playlist by pressing "green" button.

One gets errors like:
`
07:54:51.9015 [Enigma] Python path is '/usr/lib/enigma2/python'.
07:54:51.9017 [Enigma] DVB API version 5, DVB API version minor 11.
07:54:51.9017 [Enigma] Enigma debug level 3.
07:55:02.5522 [eDVBPESReader] Created. Opening demux
07:55:02.5524 [eDVBPESReader] Created. Opening demux
07:55:05.9557 2023-02-02 07:55:05,955 - DEBUG - Starting new HTTP connection (1): www.msn.com:80
07:55:06.0947 2023-02-02 07:55:06,094 - DEBUG - http://www.msn.com:80 "GET /de-de/wetter/vorhersage/in-Murr%2CGermany?weadegreetype=C HTTP/1.1" 301 0
07:55:06.1044 2023-02-02 07:55:06,104 - DEBUG - Starting new HTTPS connection (1): www.msn.com:443
07:55:06.7175 2023-02-02 07:55:06,717 - DEBUG - https://www.msn.com:443 "GET /de-de/wetter/vorhersage/in-XXXX,Germany?weadegreetype=C HTTP/1.1" 200 None
07:55:16.2207 [eDVBPESReader] Created. Opening demux
07:55:16.3316 [eDVBPESReader] Created. Opening demux
07:55:16.3318 [eDVBPESReader] Created. Opening demux
07:55:49.0279 Traceback (most recent call last):
07:55:49.0280   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 260, in action
07:55:49.0283   File "/usr/lib/enigma2/python/Plugins/Extensions/MediaPlayer/plugin.py", line 962, in xplayEntry
07:55:49.0286   File "/usr/lib/enigma2/python/Plugins/Extensions/MediaPlayer/plugin.py", line 799, in copyDirectory
07:55:49.0289   File "/usr/lib/enigma2/python/Components/FileList.py", line 535, in __init__
07:55:49.0292   File "/usr/lib/enigma2/python/Components/FileList.py", line 166, in __init__
07:55:49.0294   File "/usr/lib/enigma2/python/Components/FileList.py", line 194, in setSingleSelectMode
07:55:49.0297   File "/usr/lib/enigma2/python/Components/FileList.py", line 305, in refresh
07:55:49.0300   File "/usr/lib/enigma2/python/Components/FileList.py", line 243, in changeDir
07:55:49.0303   File "<frozen posixpath>", line 76, in join
07:55:49.0304 TypeError: expected str, bytes or os.PathLike object, not NoneType
07:55:49.0304 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xad868d50>>,('MediaPlayerActions', 'play')) failed)
`

Howto reproduce:

1. Start Mediaplayer
2. Navigate into any directory containing a set of MP3
3. Move to the first MP3 file
4. Press button green (to move the whole directory into playlist --> crash

Works fine on OpenATV 7.1 as of 2022-12-27, fails starting with OpenATV 7.2 middle of january, 2023.
Crash happens on Edision OS mio 4k plus.

[20230201-121745-enigma2-crash.log](https://github.com/openatv/enigma2/files/10608218/20230201-121745-enigma2-crash.log)

**Comment by jbleyel** [comment]
OpenATV 7.1 is end of live, please use 7.2
