### ISSUE TITLE
ScrollLabel with scrollbarMode="showOnDemand" trims lines at the end in some cases

### ISSUE THREAD

**Issue by pnevyk** [openatv/enigma2#2777]
**Describe the bug / Actual behaviour:**

In ScrollLabel widget with `scrollbarMode="showOnDemand"` (default), the height of the widget for certain texts is calculated incorrectly, causing several lines at the end not to be displayed. This does not happen for scrollbar mode "showAlways" nor "showNever".

**Expected behaviour:**

ScrollLabel widget displays all text in all cases.

**Has this issue started to happen just recently?**

No. It is reproducible in all 7.x versions. But in 6.4 it works fine.

**To reproduce:**

We created a minimal plugin for reproducing:

<details>
<summary>Source code</summary>

```python
from Plugins.Plugin import PluginDescriptor
from Screens.Screen import Screen
from Components.ActionMap import ActionMap
from Components.ScrollLabel import ScrollLabel
from Screens.MessageBox import MessageBox

class ScrollLabelTest(Screen):
    skin = """
        <screen position="center,65" size="1240,620" title="Test Python - mizející řádky na konci">
            <widget name="label" position="10,48" size="1220,550" font="Regular;19" scrollbarScroll="byLine" />
            <!-- <widget name="label" position="10,48" size="1220,550" font="Regular;19" scrollbarScroll="byLine" scrollbarMode="showAlways" /> -->
        </screen>
    """

    def __init__(self, session):
        Screen.__init__(self, session)
        self.session = session
        self["label"] = ScrollLabel("")

        self["actions"] = ActionMap(["OkCancelActions", "DirectionActions", "ColorActions"],
        {
            "left": self.pageUp,
            "right": self.pageDown,
            "up": self.lineUp,
            "down": self.lineDown,
            "cancel": self.close,
            "yellow": self.showSize,
        })

        self.onShow.append(self.showText)

    def showText(self):
        with open("/usr/lib/enigma2/python/Plugins/Extensions/ScrollLabelTest/lines.txt", "r") as fh:
            self["label"].setText(fh.read())
        self["label"].show()

    def pageUp(self):
        self["label"].goPageUp()

    def pageDown(self):
        self["label"].goPageDown()

    def lineUp(self):
        self["label"].goLineUp()

    def lineDown(self):
        self["label"].goLineDown()

    def showSize(self):
        labelSize = self["label"].leftText.calculateSize()
        totalTextHeight = self["label"].totalTextHeight
        self.session.open(MessageBox, "%s x %s | %s" % (labelSize.width(), labelSize.height(), totalTextHeight), MessageBox.TYPE_INFO, timeout=60)

def main(session, **kwargs):
    session.open(ScrollLabelTest)

def Plugins(**kwargs):
    return PluginDescriptor(
        name = "ScrollLabel Test",
        description = "ScrollLabel Test (missing lines at the end of the text)",
        where = PluginDescriptor.WHERE_PLUGINMENU,
        fnc = main)

```
</details>

<details>
<summary>Text (lines.txt)</summary>

```
Python 3

 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema1 Ad1
 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema1 Ad12
-1 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema1 Ad123
-1 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema1 Ad1234

 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema12 Ad1
-1 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema12 Ad12
-1 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema12 Ad123
 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zema12 Ad1234

-1 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zeman123 Ad1
 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zeman123 Ad12
 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zeman123 Ad123
 0 azskeho, od r. 1968), rady Korejse (Panoptikum Mesta prazskeho, od r. 1987) a majora Zemana (3 pripadu majora Zemana, od r. Zeman123 Ad1234

The last line has the number 000
Line -007 (7 lines missing)
Line -006 (6 lines missing)
Line -005 (5 lines missing)
Line -004 (4 lines missing)
Line -003 (3 lines missing)
Line -002 (2 lines missing)
Line -001 (1 line missing)
Line 000 (no line missing)
```
</details>

1. Add the attached plugin to the system + create the text file with attached contents
2. Open the plugin
3. Press "page down" key
4. See that some lines at the end are missing

**Screenshots**

<details>
<summary>ScrollLabel scrollbarMode="showOnDemand" (buggy)</summary>

![OpenATV7 x_scrollbarMode=showOnDemand1](https://user-images.githubusercontent.com/2601371/217646454-22ba2088-edad-497e-803c-ebe450ce0281.png)

![OpenATV7 x_scrollbarMode=showOnDemand2](https://user-images.githubusercontent.com/2601371/217646474-825f389c-e7c7-4f06-b771-15c9b5ad3eed.png)

</details>

<details>
<summary>ScrollLabel scrollbarMode="showAlways" (correct)</summary>

![OpenATV7 x_scrollbarMode=showAlways1](https://user-images.githubusercontent.com/2601371/217646632-7ad35c14-ff2d-4c95-8aaa-413b4032b5d4.png)

![OpenATV7 x_scrollbarMode=showAlways2](https://user-images.githubusercontent.com/2601371/217646655-efd4cb2e-11c8-4408-9ec8-92a268fb0409.png)

</details>

<details>
<summary>Widget width difference for slider visible and not visible</summary>

![OpenATV7 x_ScroolBarYES](https://user-images.githubusercontent.com/2601371/217647115-7e117deb-26e7-4b63-a9b7-827a6700080a.png)

![OpenATV7 x_ScroolBarNO](https://user-images.githubusercontent.com/2601371/217647204-277b3147-f066-41a1-90fb-e271abf8c48f.png)

</details>

**Image/Box Model (please complete the following information):**
 - Version: 7.0, 7.1, 7.2
 - BoxModel: VU+ Duo 4K

**Additional context**

The problem is that `self.totalTextHeight = self.leftText.calculateSize().height()` [here](https://github.com/openatv/enigma2/blob/a319168cecab6b530cc2bb0d0f6a6a351b998177/lib/python/Components/ScrollLabel.py#L197) calculates the text height for scrollbarMode="showOnDemand" as if the widget had full width without slider. From what I saw in the Python code for ScrollLabel, there is no difference in height calculation of `totalTextHeight` for showOnDemand and showAlways. Yet they get different value, which is confusing.

This can be reproduced with attached testing plugin. After the plugin loads, press yellow button. It will show a message box with these values: `ScrollLabel.leftText.calculateSize().width()`, `ScrollLabel.leftText.calculateSize().height()` and `ScrollLabel.totalTextHeight`. The values we get are:

* showAlways: 1197 x 875 | 875
* showOnDemand: 1197 x 875 | 750
* showNever: 1219 x 750 | 750

For some reason, _`ScrollLabel.totalTextHeight` for showOnDemand is the same as for showNever, while it should be the same as for showAlways instead_.

_However_, after closing the message box with the debug values, the ScrollLabel is rerendered and correctly displays all lines even for showOnDemand. When pressing the yellow button again, the values are now as expected.

**Comment by pnevyk** [comment]
We discovered that calling `showText` twice also fixes the issue. If you do the following change in the testing plugin, it displays the text correctly:

```python
with open("/usr/lib/enigma2/python/Plugins/Extensions/ScrollLabelTest/lines.txt", "r") as fh:
    text = fh.read()
    self["label"].setText(text)
    self["label"].setText(text)
```

**Comment by IanSav** [comment]
Just a quick note to say that this issue has come to the top of the list and is being investigated.  We have discovered a few issues with this control and look towards fixing all of them.  We also hope to improve the speed and performance of this control.

There will be updates as the work proceeds.

**Comment by IanSav** [comment]
Please test the new version and report if you still have any issues.

**Comment by pnevyk** [comment]
We tested the version from GitHub and it works correctly. Thanks!

**Comment by IanSav** [comment]
Thank you for such a good bug report.  It helped my to find the issue.  A similar test actually worked on my box.  You sample lead me to the issue.
