### ISSUE TITLE
Enigma2 crash in VideoChangeDetect - ValueError: invalid literal for int() with base 10: '50.5'

### ISSUE THREAD

**Issue by mb555444** [openatv/enigma2#2778]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
Enigma2 crashes when switching to UHD channel
Happens in both OpenATV 7.1 and 7.2
Possibly due to HDMI settings

**Expected behaviour:**
Should not crash

**Has this issue started to happen just recently?**
After changing HDMI settings

**To reproduce:**
Switch to UHD channel
Crash happens reproducibly

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - Version: OpenATV 7.2
 - BoxModel:  wwio bre2ze 4K

**Additional context**
Crash logs attached

**Comment by mb555444** [comment]
[20230211-003554-enigma2-crash.log](https://github.com/openatv/enigma2/files/10712011/20230211-003554-enigma2-crash.log)
[20230211-003615-enigma2-crash.log](https://github.com/openatv/enigma2/files/10712012/20230211-003615-enigma2-crash.log)
[20230211-003605-enigma2-crash.log](https://github.com/openatv/enigma2/files/10712013/20230211-003605-enigma2-crash.log)

**Comment by jbleyel** [comment]
Please provide the debug log.

**Comment by jbleyel** [comment]
And we need a screenshot of your video settings

**Comment by mb555444** [comment]
![1_0_19_2B66_3F3_1_C00000_0_0_0_20230211101715](https://user-images.githubusercontent.com/105666143/218250577-b0d4c5ff-82e7-40ba-b171-f1c926a8c10f.jpg)
![1_0_19_2B66_3F3_1_C00000_0_0_0_20230211101641](https://user-images.githubusercontent.com/105666143/218250579-99cdeece-c7f3-48ab-aaf8-e723ca3d3396.jpg)
[20230211-101409-enigma2-debug.log](https://github.com/openatv/enigma2/files/10713042/20230211-101409-enigma2-debug.log)
