### ISSUE TITLE
Timer margin challenge

### ISSUE THREAD

**Issue by SoSoSoStupid** [openatv/enigma2#2800]
It's possible the issue may have already been fixed. But no... let me report it.

I start a instantRecord -> Add recording (stop after current event).
The timer has 0 marginAfter and the End time isn't correct(end + marginAfter).
The timer should have a correct End time and a marginAfter.

Bug: The parseEvent add the marginAfter direct to the end.

**Comment by Papi2000-new** [comment]
That was the behavior since ever.
Maybe, you have a feature request "Add recording (stop after current event + marginAfter)".

**Comment by SoSoSoStupid** [comment]
@Papi2000-new Be sure, i like want say it friendly...
Please think one more.
The marginAfter is a new Feature and so the marginAfter should hold the value, not the destination.

**Comment by jbleyel** [comment]
The marginAfter is not a new feature.
New is only the option to edit the margins for each timer separately.
The default margins are exactly like before and not used for instand record.

**Comment by SoSoSoStupid** [comment]
But in this case instantRecord use marginAfter.

**Comment by jbleyel** [comment]
I'm confused?
You have written that the marginAfter is not used.
And now you write marginAfter is used.

WHAT?

**Comment by SoSoSoStupid** [comment]
Please try to reproduce it. Have a look at end Time and margin after.

**Comment by jbleyel** [comment]
The instand record has no endMargin by design.
That's the case since years.

**Comment by SoSoSoStupid** [comment]
The default endMargin isn't added to End time on your reproduced?
![Unbenannt](https://user-images.githubusercontent.com/128249258/226182275-4605f2bd-5708-43f0-bf55-12bf4b64acc9.PNG)
->       Event end is 15:15

**Comment by jbleyel** [comment]
This is correct because the instand record has no endmargin by default and by design.

**Comment by SoSoSoStupid** [comment]
WHAT?
15:15 is the same like 15:19???

**Comment by SoSoSoStupid** [comment]
> This is correct because the instand record has no endmargin by default and by design.

Then the "Endzeit" should be 15:15!

**Comment by jbleyel** [comment]
Sorry. My fault.
The Endtime is correct because the endmargin will be added to the endtime.
But the timer display is wrong.

**Comment by SoSoSoStupid** [comment]
> But the timer display is wrong.

Don't understand?

**Comment by jbleyel** [comment]
Simple.

Your screenshot shows 15:19 as Endtime and this should be 15:15.
The Endmargin is 0 and should be 4 Minutes.
