### ISSUE TITLE
Timer margin challenge #2

### ISSUE THREAD

**Issue by SoSoSoStupid** [openatv/enigma2#2806]
**Can we get a patch for autotimer on openatv to handle margin(before/after)/offset(begin/end)?**

A autotimer with a "Changed default recording offset" get the config.recording.margin_... additional now and isn't set as margin, it's included in begin/end time.

A autotimer with a  "Changed default recording offset", -1 minutes (before) + 2 minutes (after) for a event from 18.30 to 19.00 create a timer:
3 min before(default value)
start 18.29
end  19.02
5 min after(default value)
duration 41 minutes

This is a bug now.

correct should be:
1 min before
start 18.30
end  19.00
2 min after
duration 33 minutes

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/enigma2-plugins/commit/0941515acec94aded20f647306273b8c1d19aab7

**Comment by SoSoSoStupid** [comment]
Nice, works!
Thank you!!!
