### ISSUE TITLE
add source 

### ISSUE THREAD

**Issue by Haithameng84** [openatv/enigma2#2809]
It is possible to add the modification source to the list of style plugins, as in the pictures
source
This is a code that is made in Enigma with the build
source 
https://github.com/fairbird/enigma2-dreambox/commit/256b5787b4ffda8fcdc4e3f7d2de173b9b7dd86d
![1736881](https://user-images.githubusercontent.com/83375925/229293109-e135f4bf-36f6-43b1-a8a6-ae5f94f2df6a.jpg)
![dreamDroid_1679936786216](https://user-images.githubusercontent.com/83375925/229293113-8376c2e5-ae55-40e6-ad04-e47bc95a4c7b.jpg)

**Comment by atvcaptain** [comment]
new pluginbrowser grid view now include in 7.3
