### ISSUE TITLE
Since updating today EMC is now broken

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#2810]
After this mornings update EMC no longer opens from the video button and if you enter the plugin setup you cannot change anything because it will not save, nor can you then exit it either. You have to reboot from telnet in order to get out of the EMC setup plugin.

I've had to completely remove EMC in order to access and play my Movies and TV shows on my HDD

**Comment by jbleyel** [comment]
This is already fixed .. please wait 2 days before you update and then you can use EMC.
