### ISSUE TITLE
Language change issue 

### ISSUE THREAD

**Issue by AbuBaniaz** [openatv/enigma2#2818]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Just flashed 09 April image on a Vu Duo 4K

**Describe the bug / Actual behaviour:**
When the language is changed, some terms are shown in the new language, others are still in the old language . This applied to the first install wizard (FIW) as well as after box has booted and you change the language

**Expected behaviour:**
Everything should be in the newly selected language (provided it is translated)

**Has this issue started to happen just recently?**
This has been like this for several years. About time we we fix it.

**To reproduce:**
Flash a new image. change language to English GB. You will then see a mixture of German and English terms. Especially when you are setting up timezone and tuners. Even after you have finished FIW, changing the language has the mix-match until you restart GUI .

**Screenshots**
1. A video showing the First install wizard is below. I have then gone into AutoBouquetsMaker as an example, you will see a mix-match of languages. The plugin is translated, you don't get the mix-match after you restart GUI
 ```https://www.mediafire.com/file/k6mifb4m323yzi1/FIW_language_change.ts/file```

A video showing a change in language is here. As soon as I select German and exit, you can see tehat Monday is in German, but rets of the text is in English. When I enter the reception Menu, the terms change to German. I then go to ABM as an example and you see the mix-match
```https://www.mediafire.com/file/fu78a7gcaynwf1s/language_change_in_image.ts/file```
  
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.
FIW -setting timezone
![FIW timezone](https://user-images.githubusercontent.com/6644489/231017963-fefc1378-26d1-4555-a276-b83a431857e6.jpg)

FIW then gone to ABM
![FIW then ABM](https://user-images.githubusercontent.com/6644489/231017991-e40e3c0b-0589-4976-8d05-f54f782e4522.jpg)

**Image/Box Model (please complete the following information):**
 - Version: [7.3 but has been the case for several years]
 - BoxModel: [I used a duo 4k  but affects most boxes with more than one language]

**Additional context**

**Comment by IanSav** [comment]
I have identified the fault.  It seems that a fix @jbleyel and I implemented has been broken.  I am still looking for what changed.

**Comment by IanSav** [comment]
When the system is fully booted and you change the language can you nominate any screens that don't update the language?

Is the issue only in plugins?  If so, are the plugins using the *CORRECT* hooks to update their languages?  @jbleyel and I found many plugins had not correctly registered for language updates!  I did a quick scan of some common repositories and didn't see any issues that would be of concern.

The only issue I can see at the moment may be things that are launched from within the Welcome Wizard.  In particular I am hoping that the only issues are for any of the Boolean string translations (Yes/No, On/Off, True/False and Enable/Disable).  I found what has changed but I need to discuss those changes with @jbleyel and then we will workshop the required corrections (again).  @jbleyel should be back on deck next week.

**Comment by wedebe** [comment]
I've just updated to the latest image so took screenshots of the wizard in the hope it helps.

I also logged #2643 in the hope that a user's preferred language could be applied during the `Restore Settings` process.

![screenshot_20230422113047](https://user-images.githubusercontent.com/9741693/233776566-7521c628-8bfc-4f2d-b4ad-af3cab0ac954.jpg)
![screenshot_20230422113115](https://user-images.githubusercontent.com/9741693/233776573-bb9351e7-0226-4786-a332-b862ff26290f.jpg)
![screenshot_20230422113144](https://user-images.githubusercontent.com/9741693/233776576-d5b32044-7531-4411-9634-10a5b614957f.jpg)
![screenshot_20230422113155](https://user-images.githubusercontent.com/9741693/233776578-f665312d-f3ce-49fa-b73f-5155b6ddf6ec.jpg)
![screenshot_20230422113231](https://user-images.githubusercontent.com/9741693/233776579-f2f9e622-c8ad-44c5-bef5-47eb9bc753b3.jpg)
![screenshot_20230422113256](https://user-images.githubusercontent.com/9741693/233776580-bbc181dd-af59-477c-94c8-508d6bbea80e.jpg)
![screenshot_20230422113306](https://user-images.githubusercontent.com/9741693/233776583-2c57fc76-265c-41a9-815d-fa4cfe7dacdd.jpg)
![screenshot_20230422113315](https://user-images.githubusercontent.com/9741693/233776585-8f2cf581-e459-45a8-a37c-2653572f7c61.jpg)
![screenshot_20230422113324](https://user-images.githubusercontent.com/9741693/233776586-321a5f96-e737-4ccc-88ae-2443cd6137bd.jpg)
![screenshot_20230422113338](https://user-images.githubusercontent.com/9741693/233776588-6b8587a5-b23d-4ea9-ab51-715546a285fd.jpg)
![screenshot_20230422113347](https://user-images.githubusercontent.com/9741693/233776590-b7ca7923-e688-4c08-8e86-df2348f6a652.jpg)
![screenshot_20230422113425](https://user-images.githubusercontent.com/9741693/233776592-c29fdfc3-0ba8-4239-842a-bd2a4dbcad03.jpg)
![screenshot_20230422113655](https://user-images.githubusercontent.com/9741693/233776595-2a8bf237-ec46-49fb-988d-05d094737d1c.jpg)

**Comment by wedebe** [comment]
@AbuBaniaz , which plugin do you use to record OSD video? 🤩

**Comment by IanSav** [comment]
@wedebe, this is off topic but what device and remote control are you using.  The XML template for your remote control need fixing.  The highlights are not aligning with the buttons.

**Comment by AbuBaniaz** [comment]
Hauppuage HD capture card  which sometimes do not play ball, I have 3. Sometimes HDMI input on other Xtrend ET1000, GI LX3, Vu DUO 4K, GB Quad 4k. There are HDMI capture devices for about £10 online.

**Comment by AbuBaniaz** [comment]
> @wedebe, this is off topic but what device and remote control are you using. The XML template for your remote control need fixing. The highlights are not aligning with the buttons.

Mutant HD51

**Comment by wedebe** [comment]
Some more examples of 'stuck' text labels and values after changing language (from German to English) during the setup/initialisation wizard:

![screenshot_20230425195333](https://user-images.githubusercontent.com/9741693/234362996-3a0b110d-f11c-4da1-b3a8-f474685d4c80.jpg)
![screenshot_20230425195209](https://user-images.githubusercontent.com/9741693/234363003-26711aa0-1673-4250-9c2c-41d4a6204007.jpg)
![screenshot_20230425195142](https://user-images.githubusercontent.com/9741693/234363006-d7597cb7-6770-4eef-b973-ba45a909eb0c.jpg)

**Comment by jbleyel** [comment]
Hello @AbuBaniaz ,

we have investigate the issue and we have found one simple solution.

The very first page of the Wizard will become the Language Selection and enigma will be restarted automatically after you have changed the language and continues the Wizard.
The Red key for Language change in Wizard will be removed.

All other solutions are too complex to implement and may have a lot of side effects.

**Comment by wedebe** [comment]
> Hello @AbuBaniaz ,
> 
> we have investigate the issue and we have found one simple solution.
> 
> The very first page of the Wizard will become the Language Selection and enigma will be restarted automatically after you have changed the language and continues the Wizard. The Red key for Language change in Wizard will be removed.
> 
> All other solutions are too complex to implement and may have a lot of side effects.

This is by far the best, and most user-friendly solution. Just about every multi-lingual device does this on initial startup anyway :)

**Comment by wedebe** [comment]
OpenSPA keeps the red button after language selection screen

**Comment by jbleyel** [comment]
> OpenSPA keeps the red button after language selection screen

And we plan to remove the red button.

**Comment by AbuBaniaz** [comment]
In the interim, can we not just do a GUI restart? Rest of changes can come later.

**Comment by jbleyel** [comment]
No.. we have other important thing to do first.
And then we will refactor the Wizard completely.

**Comment by IanSav** [comment]
The code to do a GUI restart has already been written but not yet committed as I am also involved in the other priority tasks.

**Comment by IanSav** [comment]
The code for LocaleSelection from the menu is done but there are changes in the Wizard that will probably need matching changes in this module.  I was going to fix both halves before making the commit.  We are hoping this should be finished soon.

**Comment by AbuBaniaz** [comment]
Just saw the commit. That fixes the bug for most people who change language during FIW.  Many thanks.

However, it looks like the bug when changing language without doing a restart will not be addressed. Not many people do this, so not a big deal.

**Comment by jbleyel** [comment]
> Just saw the commit. That fixes the bug for most people who change language during FIW. Many thanks.
> 
> However, it looks like the bug when changing language without doing a restart will not be addressed. Not many people do this, so not a big deal.

Nope .. there is an enigma gui restart after language change.

**Comment by AbuBaniaz** [comment]
I have just tested this, there is no GUI restart.  You still get the mixed translations/no translation for yes/no. I can upload a video if you don't believe me. Also, very unituitive that you have to press OK then Green to change the language.  Just pressing Green after highlighting the language does nothing.
