### ISSUE TITLE
bouquet edit

### ISSUE THREAD

**Issue by Makumbo** [openatv/enigma2#2820]
This error is in there since Image 6.4:

1. Show Channellist
Headline = "**(TV)Favourites**"

2. MENU - enable bouquet edit
Headline = "**(TV) [bouquet edit]**"

3. Yellow/Providers
Headline= "**edit]**"

4. Click on "ARD"
Headline= "**edit]ARD**"

Maybe put a space after the "]" - [bouquet edit] ARD"?

And don't forget MENU - abort bouquet edit...

**Comment by IanSav** [comment]
I have started looking at this issue.  I will need @jbleyel to get back from holidays in about a week so he can make some of the required language adjustments.

**Comment by IanSav** [comment]
@Makumbo what do you mean by "Click on "ARD""?

I have already fixed item 2 where the bouquet name gets removed.

**Comment by Makumbo** [comment]
"Click on "ARD"" means that I first press Yellow (to show the Providers) and then I click on the Provider "ARD".
And than it should show "[bouquet edit] ARD" and not "edit]ARD" in the headline...

**Comment by IanSav** [comment]
@Makumbo thanks for that information.  I am in Australia and have a different set of providers and services.  ;)

**Comment by Makumbo** [comment]
Then in your case:  "Click on "FOXTEL"" means that I first press Yellow (to show all the Providers)
and then click on the Provider "FOXTEL".
And than the headline should show "[bouquet edit] FOXTEL" and not the cropped "edit]FOXTEL".

**Comment by IanSav** [comment]
I have the bug trapped in a single method and am now working out a refactor that will squash it.  This looks like a very long standing bug.

**Comment by Makumbo** [comment]
It is at least since 6.4 in the image...
Thank for your efforts!

**Comment by IanSav** [comment]
I have found and fixed the errors.  I need to clean up my code and then the new code needs to be tested by people with access to more services than I have available to me here in Australia.  (We only have DVB-T sources, no DVB-C and no DVB-S.)  @jbleyel will test the new code on his return.  If he approves the new code I will pass it on to others for wider testing.

**Comment by Makumbo** [comment]
Yes. (Short for "Wonderful - I like it - That's it - Thank you (and jbleyel))  ;)

**Comment by wedebe** [comment]
I can help test this :)

Seeing this before the fix:
<img width="247" alt="Screenshot 2023-04-24 at 21 13 14" src="https://user-images.githubusercontent.com/9741693/234106024-8a996858-b5dd-4874-8436-33abb5373709.png">

**Comment by jbleyel** [comment]
We are currently in refactor / test phase.
An update will be available soon.

**Comment by Makumbo** [comment]
> Seeing this before the fix:  

I wanted to show that in my first post but I couldn't include a screenshot... :(

**Comment by IanSav** [comment]
A proposed fix for ChannelSelection titles has just been committed in https://github.com/openatv/enigma2/pull/2894.  Please test the new code and report if all the title issues are fixed.

**Comment by Makumbo** [comment]
I have to wait for the 2023 05 22 image, it's not yet in the 05 21 image for my STB.
But then ...

**Comment by jbleyel** [comment]
> I have to wait for the 2023 05 22 image, it's not yet in the 05 21 image for my STB.
> But then ...

You need to wait aprox. 1 week.

**Comment by Makumbo** [comment]
I will do that ;)

**Comment by Makumbo** [comment]
And I did.
And everything is ok now.
Thanks.
