### ISSUE TITLE
[BUG] Remote control graphic highlights not aligning with buttons

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2824]
The XML template for Mut@nt (also known as Ax) HD51 original remote control need fixing.  The highlights are not aligning with the buttons.

'AX HD51'
'Mutant HD51'

![Screenshot 2023-04-22 at 12 42 17](https://user-images.githubusercontent.com/9741693/233782499-f32449f9-e11a-4c54-b5c0-56e4e79b0b12.png)

```
12:36:51.7426 [InputDevice] Default remote control identified as 'Mutant HD51'.  (model='hd51', rcName='hd1100', rcType='16')
12:36:51.7433 [InputDevice] Loading remote control '/usr/share/enigma2/hardware/hd1100.xml'.
12:36:51.7447 [InputDevice] Remote control image file 'None'.
```

```
12:36:45.1690 [eInit] + (21) input device driver
12:36:45.1690 [eInputDeviceInit] adding device /dev/input/event0
12:36:45.1692 [eRCInputEventDriver] EVIOCGRAB: Function not implemented
12:36:45.1692 [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
12:36:45.1693 [eInputDeviceInit] adding device /dev/input/event1
12:36:45.1693 [eRCInputEventDriver] devicename=dreambox advanced remote control (native)
12:36:45.1693 [eRCInputEventDriver] devicename=dreambox advanced remote control (native)
12:36:45.1694 [eRCInputEventDriver] EVIOCGRAB: Function not implemented
12:36:45.1694 [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
```

_Originally posted by @IanSav in https://github.com/openatv/enigma2/issues/2818#issuecomment-1518610026_

**Comment by AbuBaniaz** [comment]
Surely this is a a box branding issue and not openatv?
https://github.com/oe-alliance/branding-module/tree/master/BoxBranding/remotes/hd1100

**Comment by wedebe** [comment]
> Surely this is a a box branding issue and not openatv? https://github.com/oe-alliance/branding-module/tree/master/BoxBranding/remotes/hd1100

Thanks, I've logged it there.
