### ISSUE TITLE
[Flash Manager] Improvement: `Delete Image` should confirm user action 

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2825]
Destructive operations should always be confirmed by the user.

Issue:
Pressing `Delete Image` silently performs a file deletion.

Ideal scenario:
Prompt user with a confirmation dialog before continuing with deletion.

![20230423121715](https://user-images.githubusercontent.com/9741693/233836926-37d74c94-2019-4599-ba66-c42dd6fa5974.jpg)

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/03c414c61833aef9e0a3f1c6da9a4c92237eb70d
