### ISSUE TITLE
[Kodi] Navigation broken/Remote control does nothing after 2023-03-23

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2838]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
openatv-7.2-mutant51-20230427_multi.zip

**Describe the bug / Actual behaviour:**
Kodi starts up but using Up/Down/Left/Right/OK has no effect.

**Expected behaviour:**
Using Up/Down/Left/Right/OK should have an effect, navigating through UI.

**Has this issue started to happen just recently?**
Works fine up to and including image dated 2023-02-23
Broken since image 2023-02-25 (I don't have and image from the 24th)

**To reproduce:**
1. Open Kodi
2. Press any nav key
3. Choose your favourite expletive
4. Mumble result of 3. above

**Screenshots**
N/A

**Image/Box Model (please complete the following information):**
 - openatv-7.2-mutant51-20230427
 - Mut@nt HD51
 - [enigma2-plugin-extensions-kodi (20-r0)](http://192.168.43.216/#)

**Additional context**
Kodo 20.1 is latest release, per startup notification.

**Comment by jbleyel** [comment]
Fixed with the next image.

**Comment by wedebe** [comment]
> Fixed with the next image.

Confirmed working again, thanks! :)
