### ISSUE TITLE
Q: Is there a PEP8 config file?

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2840]
Is there a config file we can all use so that our (mainly) Python code becomes more consistent across the board?

Eg. to avoid stuff like #2839 getting into the codebase and for dev environments to hint at improvements and code smells.

https://web.archive.org/web/20230108181312/https://openbase.com/python/autopep8/documentation
"Also, if setup.cfg, tox.ini, .pep8 and .flake8 files exist in the directory where the target file exists, it will be used as the configuration file."

This could also potentially be used across the plugins repos.

**Comment by jbleyel** [comment]
We use this for autopep8:

E401,E701,E70,E502,E251,E252,E20,E211,E22,E224,E241,E242,E27,E225,E226,E227,E228,E231,E261,E301,E302,E303,E304,E305,E306,W291,W292,W293,W391
