### ISSUE TITLE
`Select Media Location` <Parent Directory> appears below <Current Directory> in file list.

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2850]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-04-30

**Describe the bug / Actual behaviour:**
`<Parent Directory>` appears below `<Current Directory>` in file list.

**Expected behaviour:**
`<Parent Directory>` is an action which changes directory.

`<Parent Directory>` should follow pretty standard file manager positioning (also `..`) and be paced at the top of the file list.

**Has this issue started to happen just recently?**
No

**To reproduce:**
Steps to reproduce the behaviour:
1. Go to any settings screen that provides an option to select path (eg. `Recording`)
2. Open path option

**Screenshots**
![parent20230501102440](https://user-images.githubusercontent.com/9741693/235435259-27945fdb-130e-4a50-9920-6c9c6790eef1.jpg)

**Image/Box Model (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by IanSav** [comment]
Under Linux, current directory is "." and parent directory is "..".  The current directory is shown first followed by the parent directory.  This is what FileCommander does as well.

**Comment by jbleyel** [comment]
The current directory should be the 1st element as @IanSav describes also to avoid accidental actions.
