### ISSUE TITLE
Stream recordings in the movie list

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#2864]
When I record a stream (via gstreamer, 4097), it creates an MPEG-TS file with a .stream extension. There is also an .eit file (if EPG data was available), and a .stream.meta file.

 

So far pretty standard.

 

However, in the movie list, it displays the name of the file, so "20230502 - Some Channel - Some file.stream". I can rename the file using the blue button, and I can see in the meta file the name is changed.

 

But when I reload the movie list, I don't see the name from the meta file, I till see the name of the file.

 
Case of a hardcoded "if file is .ts then" somewhere?

Please help.

**Comment by jbleyel** [comment]
There is another issue in movie list for .stream files.
The name looks odd.

**Comment by Dima73** [comment]
Thanks

**Comment by Dima73** [comment]
Next question.
How to create a file (gstreamer, 4097).ap in order to use the plugin "MovieCut"?

**Comment by jbleyel** [comment]
int eMPEGStreamInformationWriter::stopSave(void)

creates the ap file.

**Comment by Dima73** [comment]
Yes, I know about this(stopSave), but

> Anyone ever tried using the cut list editor on a recorded stream?

 

First it complains that it doesn't know the extension.

After renaming .stream to .ts, it complains that the .ap file is missing.

Reconstructapsc plugin not help

**Comment by jbleyel** [comment]
Do we need the ap in Cutlisteditor or is it also possible to define cuts with the ap data?

**Comment by jbleyel** [comment]
The stream recording may have a similar information like the transporter stream accesspoints. But do we really need that?

**Comment by Dima73** [comment]
Cutlisteditor not need *.ap,but necessary [[reconstructapsc] add option "Change type '.stream' to '.ts'"](https://github.com/OpenPLi/enigma2-plugins/commit/08b1f3878b709085fade46e1da95f4a0b30277d0)
MovieCut plugin need *.ap

**Comment by jbleyel** [comment]
What is this plugin doing in addition to changing the extension of the files?

**Comment by Dima73** [comment]
> What is this plugin doing in addition to changing the extension of the files?

Reconstruct AP/SC files for *.ts

**Comment by Dima73** [comment]
I think you should check it yourself.
Record *.stream
Use Cutlisteditor and run MovieCut

**Comment by jbleyel** [comment]
I don’t use these plugins.

**Comment by Dima73** [comment]
Moreover, you should check it yourself.
You are the only one who can help.
This is the only way to edit video through the Enigma2 shell.
Many users use it
And the stream takes first place in the modern world.
The possibility of timeshift is also necessary.

**Comment by Dima73** [comment]
I will try to make the timeshift myself in Python, through a fake record.

**Comment by jbleyel** [comment]
I think we should do this differently.

https://github.com/oe-alliance/enigma2-plugins/commit/ce1e67935df65aa0b0f3cfc8b7159c2d0eb11c9d

**Comment by jbleyel** [comment]
Do you have tested the mcat for a renamed stream file?
Is this working?

**Comment by jbleyel** [comment]
please try this:

https://github.com/oe-alliance/enigma2-plugins/commit/b2678f41f3ce5d79dc13b1dd0454377e791c9949

**Comment by Dima73** [comment]
Thank you, I can check only tomorrow.

**Comment by WanWizard** [comment]
> Do you have tested the mcut binary for a renamed stream file? Is this working?

No, the mcut binary returns exit code 4: "failed to open input ap file", which is correct, this does not exist, it is not created during recording of the stream (note: using servicemp3, gstreamer), and can also not be recreated by the reconstructapsc plugin (that only creates the sc file).

**Comment by jbleyel** [comment]
So .. the question is now : Is mcut also working without ap file or can we create the ap file also for a stream?

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/373468268515b312577fc911166aee2ee85f0236

**Comment by WanWizard** [comment]
If the reconstructapsc plugin can be believed, there are no accesspoints in the stream, as it runs fine, recreates the .sc file, but doesn't recreate the .ap file.

Unfortunately, I lack the technical knowledge of MPEG to comment further on it.

From what I can see in the code, it uses the accesspoints in the ap file to read blocks of data from the ts file, so it looks like a list of pointers of some sort. 

But nothing else in E2 seems to be missing the .ap file, I can watch it, wind of rewind it, skip through it, ...

**Comment by jbleyel** [comment]
You can create the ap and sc with "createapscfiles".

**Comment by jbleyel** [comment]
root@vuultimo4k:/media/hdd/movie/1# ls -l
-rw-r--r--    1 root     root      90270268 Oct  7 18:22 1.ts
-rw-r--r--    1 root     root             0 Oct  7 18:24 1.ts.ap
-rw-r--r--    1 root     root         72192 Oct  7 18:24 1.ts.sc

The sc was created but the ap is empty.

**Comment by Dima73** [comment]
It is necessary to write a code that creates a .ar file with the correct data at the end of the recording servicemp3.cpp

**Comment by jbleyel** [comment]
> It is necessary to write a code that creates a .ap file with the correct data at the end of the recording servicemp3.cpp

I have no idea why the createapscfiles don't work for stream files.
It looks like that the stream file have no pts infos and you cannot create the ap file.

This means you probably not need the ap file for moviecut of stream files.

**Comment by betacentauri** [comment]
"When I record a stream (via gstreamer, 4097), it creates an MPEG-TS file with a .stream extension"
This is in general wrong. A .stream file can contain all sorts of data. It can be a MPEG-transport stream, but it can also be a MKV or mp3 or wmv or what else gstreamer supports.
E2 don't know what is in the .stream file. Gstreamer handles it. Gstreamer chooses the demuxers/decoders according to the recognized file format. So if you want to know what is in the file use e.g. mediainfo.

It depends on the source which format is send and whether it's an e2/MovieCut compatible MPEG TS stream or not. And as you see even MPEG-TS streams can be different so that some are compatible and some not.
I didn't wrote MovieCut, but I guess it was build ONLY to be able to cut MPEG-TS streams broadcasted via SAT/cable and stored by e2 and not every MPEG-TS, MKV or whatever stream.

It might be possible to improve e2 (ap creation) or Moviecut, but it will never be a cutting program which will support all kinds of codecs I guess. I don't believe that somebody will build this.

**Comment by betacentauri** [comment]
https://github.com/openatv/enigma2/commit/373468268515b312577fc911166aee2ee85f0236
I don't know whether this is a good idea. As said createapscfiles expects MPEG-TS streams, but .stream files can also contain other data. This MIGHT lead to crashes. Maybe.

**Comment by WanWizard** [comment]
> This is in general wrong. A .stream file can contain all sorts of data. It can be a MPEG-transport stream..

True, but the statement was "When I", so not generally speaking, but in his specific case. As you can see above, the recording I want to cut is also an MPEG-TS file. I understand that moviecut is only about TS file, so perhaps that could be checked to prevent users doing stupid things?

From what I can see in analysis, the MPEG-TS was created by ffmpeg, so if it was originally broadcasted, it has been processed / compressed.

**Comment by jbleyel** [comment]
I will close this because createapscfiles won't work.

**Comment by Dima73** [comment]
ok
