### ISSUE TITLE
VU+ DUO4K display not working

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#2866]
Need to add localextra.rules to udev
https://github.com/OpenPLi/openpli-oe-core/blob/00a220eb69b1b19e817ca56cd2087329dbbbd3f4/meta-openpli/recipes-core/udev/files/localextra.rules#L4
and not /dev/misc/vtuner*
is only /dev/vtuner*
this entry KERNEL=="vtuner[0-9]*", SYMLINK+="misc/vtuner%n"

**Comment by atvcaptain** [comment]
i check atv 7.2 and 7.3 display works i cant see any issue

**Comment by Dima73** [comment]
DUO4K
 not SE version

**Comment by atvcaptain** [comment]
yes i check the duo4k not the duo4kse
with both images, display works normal

i flash the image new with usb

**Comment by Dima73** [comment]
Strange.
I'll check again.
But I'm sure the result will be the same until I add the localextra.rules.

Again
My vu+ duo4k/solo4k
not /dev/misc/vtuner*
is only /dev/vtuner*
this entry KERNEL=="vtuner[0-9]*", SYMLINK+="misc/vtuner%n"

/dev/misc/vtuner* need satipclient

**Comment by atvcaptain** [comment]
ls /dev/misc/
pvr      vtuner0  vtuner1  vtuner2  vtuner3
 ls /dev/dbox/
fp0    oled0

looks ok, we use mdev rules not udev rules

**Comment by Dima73** [comment]
By the way, I set the openATV image through a new VU+ multiboot.
