### ISSUE TITLE
 Standby: fix stop service in standby if box automatic wake up, e.g. for record timer

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#287]
Please merge this
https://github.com/OpenPLi/enigma2/commit/4a6b43ebfc1c6128b606d1cd6a4a2a202900e3a2
and
https://github.com/OpenPLi/enigma2/commit/0a01e48e453e4185712d864b819898977140a909

Users complain that the play service is not disabled.

**Comment by rx5670** [comment]
I confirm this.
When stb goes form deep sleep into standby the channel that was opened before deep sleep becomes active.

**Comment by sorin84** [comment]
I have the same problem

**Comment by arn354** [comment]
Try that /Screens/Standby.py if you are familiar with testing python code changes.
https://github.com/openatv/enigma2/raw/DEV/lib/python/Screens/Standby.py

**Comment by rx5670** [comment]
**arn354**
Hello!
I tried your .py and it works as it should.
I just tried to reboot the box and when it boots to standby softcam's log shows only a couple of requests. Much better then it was before.
Thank you!
When this .py will be integrated into the distribution?

**Comment by atvcaptain** [comment]
thanks for testing, we merge at weekend

**Comment by rx5670** [comment]
Hello!
I installed "openatv-5.1-vusolo2-20160217_usb.zip" and the bug is still there.
