### ISSUE TITLE
Question: Is there a Event/Program name/title index as part of EPGCache?

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2879]
I'd like to know if it's possible to lookup just event names without overhead (idea for a search autocomplete).

Is EPGCache considered sufficiently efficient for search by a simple field? I envisage a store of unique string values.

**Comment by jbleyel** [comment]
It depends what exactly do you wanna get.
Only one channel?
Only search in title?
What EPG fields do you wanna return?

Limit will be minimum 3 chars to prevent performance issues.

**Comment by wedebe** [comment]
Essentially the query would be `SELECT UNIQUE programTitle FROM epg ORDER BY programTitle`

**Comment by jbleyel** [comment]
The result list of the titles is very huge.
I have tested this with an epg cache of a few channels and I get more than 10000 different titles.
So you need to define a filter because the full list of titles will blow up your box.

**Comment by jbleyel** [comment]
Hi @wedebe , what’s next?
My mock-up version is not efficient and not really useful.

**Comment by wedebe** [comment]
> Hi @wedebe , what’s next? My mock-up version is not efficient and not really useful.

I had hoped to try out some autocomplete/find-as-you-type api functionality. Seems a direct hit on an epgCache instance would be the most efficient method. It's not something I'd have time for right now though.

Many thanks for investigating :)

**Comment by jbleyel** [comment]
It's working but it's probably slow depending on the query string.
If you provide a minimum of 2 or 3 starting letters you may get the result faster.

Getting the full list of all titles is not good.

**Comment by jbleyel** [comment]
I have another idea but this takes some time.

**Comment by wedebe** [comment]
> It's working but it's probably slow depending on the query string. If you provide a minimum of 2 or 3 starting letters you may get the result faster.
> 
> Getting the full list of all titles is not good.

Yeah in my experience, a minimum of 3 characters and debouncing queries by a few hundred milliseconds is an absolute necessity!
