### ISSUE TITLE
 not connect openatv-7.3-dm820-20230512_flash

### ISSUE THREAD

**Issue by elhawaryna** [openatv/enigma2#2883]
I have a problem with the device that does not perform a rollback for that version
Only the screen blinks

**Comment by jbleyel** [comment]
Please provide more info and log files otherwise we cannot help.

**Comment by atvcaptain** [comment]
fixed with next update: https://github.com/oe-alliance/oe-alliance-core/commit/3f7098fe3309cdfe7e181248f92905041e7b63c8
