### ISSUE TITLE
[Flash Manager] Add option to `Download` image

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2898]
An option to download an image without flashing would be a nice convenience.

(Should be blue button action, not yellow per my mockup)

![20230521000617](https://github.com/openatv/enigma2/assets/9741693/af36f5ec-af3b-4096-a9bb-9d3daca3c83a)

**Comment by AbuBaniaz** [comment]
OpenPLi added this to their image recently. However, it is on the flashing options as they did not want to add extra steps in the flashing process. Their flashimage is not too dissimilar to ATVs

https://github.com/OpenPLi/enigma2/commit/76bc2283e923028a78d08729a8a6433b622f6a52

**Comment by wedebe** [comment]
> OpenPLi added this to their image recently. However, it is on the flashing options as they did not want to add extra steps in the flashing process. Their flashimage is not too dissimilar to ATVs
> 
> [OpenPLi/enigma2@76bc228](https://github.com/OpenPLi/enigma2/commit/76bc2283e923028a78d08729a8a6433b622f6a52)

![Screenshot - buttons](https://github.com/openatv/enigma2/assets/9741693/768944a5-b55a-4916-b6df-ac6e16a23ff1)
![Screenshot - menu](https://github.com/openatv/enigma2/assets/9741693/c1fbd9f4-4305-4810-b151-997bd97449b8)

**Comment by AbuBaniaz** [comment]
Good work. Please submit a pull request for the team to consider adding it.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/5c858a14fad9e8d82eb2c068587ae5b7965f17f4
