### ISSUE TITLE
[Plugin Browser] Nav by letter

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2902]
The `all channels` list allows to jump to entries by name/number (eg, pushing `[3]` twice would jump to `E4`*).

It would be nice to implement this in the plugin browser and other alphabetically-sorted lists.

*Depending on user setting of number-first (3, D, E, F) or letter-first (D, E, F, 3).

**Comment by IanSav** [comment]
This feature has been added to the PluginBrowser main screen.  It has not been added to the PluginAction screen (this is an updated version of the PluginDownload based screens).  A new navigation option to step to previous and next catagories has been added for this screen.

This code is actively being developed at the moment and should be published soon.

**Comment by jbleyel** [comment]
Quickselect is now implemented.
