### ISSUE TITLE
[Flash manager] OpenPLi, OpenHDF, OpenSPA sections appear above `Downloaded images`

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2906]
OpenATV images appear *below* `Downloaded images`. This is not the case when `OpenPLi`,`OpenHDF` or `OpenSPA` is selected as distribution.

![20230525102607](https://github.com/openatv/enigma2/assets/9741693/c210f657-73e9-4d80-a166-ddb89c581d9b)

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/5c858a14fad9e8d82eb2c068587ae5b7965f17f4
