### ISSUE TITLE
[Flash manager] No online images found for OpenBH 

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2908]
When OpenBH, Open8eIGHT, OpenDroid, TeamBlue, EGAMI are selected as distribution, no images are available to flash.

![20230525102734](https://github.com/openatv/enigma2/assets/9741693/ac258317-8a44-4b21-bc5e-84fb12f5dcab)
![20230525102953](https://github.com/openatv/enigma2/assets/9741693/116b8ad0-f30a-4d8b-a5a4-36087b79195a)

**Comment by jbleyel** [comment]
This is not a bug because the other distributions do not build all images.

**Comment by wedebe** [comment]
Perhaps a notification or text to advise the user that `There are no images available to download.` would be useful

**Comment by AbuBaniaz** [comment]
Please have a look at how PLI do this. They look up a file and only offer distros that are available.

The download but not flash request is also catered for.

**Comment by jbleyel** [comment]
> Please have a look at how PLI do this. They look up a file and only offer distros that are available.
> 
> The download but not flash request is also catered for.

What you mean with lookup a file?

**Comment by jbleyel** [comment]
I think you mean this:
https://github.com/OpenPLi/FlashImage/

This is a massive manual task to create all models.
We have many more images and we have oem builds.

**Comment by AbuBaniaz** [comment]
PLI created that list, we only need to add what is missing.

Also, from what I understand (please correct me if I am wrong), the lookup is done when you select other images. The "native/home" image does not check that list.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/5c858a14fad9e8d82eb2c068587ae5b7965f17f4
