### ISSUE TITLE
[Restore] `Installing plugins from feed` never times out or retries on bad/lost connection

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2914]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-05-28

**Describe the bug / Actual behaviour:**
During the _install plugins_ phase of restore, the process hangs indefinitely if the internet connection drops briefly.
If the user presses the [red] button, confirms exit, and presses [green] when back on the list of plugins to install, error messages abound.

![screenshot_20230529142339](https://github.com/openatv/enigma2/assets/9741693/39c31359-58bb-4cd4-b71b-f77973388f5a)

**Expected behaviour:**
Silently retry after a timeout for # attempts. Cleanup between tries as necessary.

**Has this issue started to happen just recently?**
No

**To reproduce:**
1. Create a settings backup which includes user-installed plugins (eg. Kodi as it takes a while to install)
2. Flash an image - Clean install
3. Restore settings, but during the process, disconnect the router from the internet for a minute
4. Progress stalls

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
N/A

**Comment by atvcaptain** [comment]
i refresh soon the STATIC FEED, in 3-4 Days is fixed
