### ISSUE TITLE
Set up wizard, unable to change langage

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#2944]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Not fixed with 7.3 20230611

**Describe the bug / Actual behaviour:**
[[A clear and concise description of what the bug is.]]
Until few releases, unable to change langage during the setup wizard. Red button has no effect

**Expected behaviour:**
[[A clear and concise description of what you expected to happen.]]
Enable red button

**Has this issue started to happen just recently?**
If yes, roughly when did it last work fine for you?
Yes with 20230608 I think, but not sure

**To reproduce:**
Do a fresh install and try to change langage

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.
![screenshot_20230613113808](https://github.com/openatv/enigma2/assets/17811804/6c3aa6d2-739c-4c64-8564-423ec8353df6)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel:  SF8008

**Additional context**
none

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/94cd774752a10d51c15102d4628d0e83a74560bb
