### ISSUE TITLE
Multiboot problem

### ISSUE THREAD

**Issue by Haithameng84** [openatv/enigma2#2945]
It is not possible to add more than one solt after completing the multi-boot system in the event that it needs to be added while I am on the recovery image, but it is on the last image I made on the external one as shown in the pictures
![IMG_٢٠٢٣٠٦١٣_٢٠٥٧١٧](https://github.com/openatv/enigma2/assets/83375925/b694744a-8778-43ed-aa02-6d2fefd2cd21)
![dreamDroid_1686618706968](https://github.com/openatv/enigma2/assets/83375925/d1a0e828-6e5f-42ef-b223-1fb081bfab92)

**Comment by atvcaptain** [comment]
we have restricted usb slot expansion to the root image, when you are in a guest image the blue button is removed and you can only delete images that are not active more not, or what do you mean exactly if i misunderstood you

**Comment by Haithameng84** [comment]
[multiboot for 7.3 is best](https://www.mediafire.com/file/h1w07n3yt3e7ogb/multiboot_for_7.3_is_best/file) 
Explanation video

**Comment by atvcaptain** [comment]
fixed with next update: https://github.com/openatv/enigma2/commit/76829dd63bfc7760875b9e8a86926e52d9820ca1
