### ISSUE TITLE
Default skin transparent option ?!

### ISSUE THREAD

**Issue by fairbird** [openatv/enigma2#2961]
Some skins does not work correctly like this one 
![11](https://github.com/openatv/enigma2/assets/1761779/661218ae-f07e-4791-8a9f-e7099ae5e1f0)

Should be skins like this
![1_0_1_9_3B_800_DCA0000_0_0_0_20230630025628](https://github.com/openatv/enigma2/assets/1761779/9feb7e71-2b9d-4183-baec-820cf485d781)

**Comment by atvcaptain** [comment]
issue with your pli e2 ?
Box Model ?
skin download link ?

**Comment by fairbird** [comment]
-With latest version of OpenATV
-DM920
-Download link
https://www.mediafire.com/file/kgkn91t3wacykqb/Skin-FULLHDLine-By-MIC71-MOD-By-RAED_Poster.ipk/file
