### ISSUE TITLE
Allow streamlink to groupedservices

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#2975]
**Is your feature request related to a problem? Please describe.**
- Currently if the file /etc/enigma2/groupedservices for a channel contains streamlink%3a// the subservices function is broken for this channel, only http(s)%3a// is working
- Another think, if ServiceRef is lowercase, the subservice function is broken. Only uppercase is working

**Describe the solution you'd like**
- Allow streamlink prefix in groupedservices file. I think the file to mod is lib/python/Screens/InfoBarGenerics.py
- Allow lowercase in groupedservices file

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jbleyel** [comment]
Duplicate #1889
