### ISSUE TITLE
RTE 1 HD or SD crashes when the Service Ref is added

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#2980]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
[[A clear and concise description of what the bug is.]]

**Expected behaviour:**
[[A clear and concise description of what you expected to happen.]]

**Has this issue started to happen just recently?**
If yes, roughly when did it last work fine for you?

**To reproduce:**
1. Go to...
2. Press ...
3. Press ...
4. See result/error

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - Version: [e.g. 7.2]
 - BoxModel: [e.g. SF8008]

**Additional context**

It doesnt matter if you try to use Sat or IPTV it still crashes if the sref's are present giving 

17:17:56.4823 Traceback (most recent call last):
17:17:56.4824   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 131, in updateEventInfo
17:17:56.4831   File "/usr/lib/enigma2/python/Components/Sources/ServiceEvent.py", line 33, in newService
17:17:56.4835   File "/usr/lib/enigma2/python/Components/Element.py", line 91, in changed
17:17:56.4839   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
17:17:56.4843   File "/usr/lib/enigma2/python/Components/Converter/MyEventList.py", line 84, in changed
17:17:56.4856     Converter.changed(self, what)
17:17:56.4859   File "/usr/lib/enigma2/python/Components/Element.py", line 91, in changed
17:17:56.4868   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
17:17:56.4873   File "/usr/lib/enigma2/python/Components/Renderer/EventListDisplay.py", line 61, in changed
17:17:56.4883     self.pull_updates()
17:17:56.4885   File "/usr/lib/enigma2/python/Components/Renderer/EventListDisplay.py", line 53, in pull_updates
17:17:56.4889     self.instance.writeText(eRect(value[0], y+int((self.rowHeight-value[4])/2), value[1], self.rowHeight), value[2], self.backgroundColor, value[3], item[value[5]], value[6])
17:17:56.4895 TypeError: in method 'eCanvas_writeText', argument 6 of type 'char const *'
17:17:56.4896 [ePyObject] (PyObject_CallObject(<bound method SelectionEventInfo.updateEventInfo of <class 'Screens.ChannelSelection.ChannelSelection'>>,()) failed)

The only way to prevent the crash when you select RTE 1 is to remove the Service Reference from the channel lists and therefore have no EPG

This is the sref used in case you do not have it.

1:0:19:1AA2:7EB:2:11A0000:0:0:0

To reproduce this you dont need to be able to open the channel, just select it on 28.2E and if the sref's are there it will crash. I do not know if any other channels have the same problem, so far this is the only one I've found.

**Comment by jbleyel** [comment]
EventListDisplay.py is not part of enigma2.

This is an extra plugin -> https://github.com/oe-alliance/enigma2-plugins/tree/master/eventlist
