### ISSUE TITLE
Übersetzung von Channel selection und Channellist menu

### ISSUE THREAD

**Issue by Snoete** [openatv/enigma2#2983]
In die enigma2.pot stehen die Englische Umschreibungen "Channel **S**election" und "Channel List Menu". Im Metrix skin sind die aber nicht gut übernommen worden. 
In die Senderliste steht z.b. "Channel **s**election" mit "s" klein geschrieben. Und im Senderlisten Menu steht "Channellist menu" statt "Channel List Menu".

Könnt ihr das kontrollieren und ändern, wodurch die Übersetzung wieder stimmt?   

![Channel selection](https://github.com/openatv/enigma2/assets/5354551/2ed832fc-e8b6-4de8-965b-abf41fcc1d03)

![Channellist menu](https://github.com/openatv/enigma2/assets/5354551/da27bfed-5b65-4f61-9c52-f2021c0af4be)

**Comment by jbleyel** [comment]
https://github.com/openatv/MetrixHD/commit/193b27aca573f9effc0ab94374db13642cbad03e

**Comment by Snoete** [comment]
Wow war Schnell, THX! 

Kann sein das dass gleiche auch gilt für "Channel List Menu" ?
Im Metrix steht noch "Channellist menu".

Müssen die gleiche files dafür angepasst werden?

**Comment by jbleyel** [comment]
Ich hab noch mehr im Metrix geändert.

**Comment by Snoete** [comment]
Oké Danke! Hab schon en comment auf dein Commit geschrieben, also wahrscheinlich doppelt.
