### ISSUE TITLE
Backuprestore: file "/tmp/removed-list.txt" is not created

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#2986]
**Describe the bug / Actual behaviour:**
Backuprestore: file "/tmp/removed-list.txt" is not created

**Expected behaviour:**
With the last commit 2378bbe a file named "/tmp/removed-list.txt has to be added to the backup settings file. The condition is to have deleted packages from the image. It's exactly the same as "/tmp/installed-list.txt" but for removed packages.

I have deleted some packages:
opkg remove --force-depends enigma2-plugin-extensions-imdb
opkg remove --force-depends enigma2-plugin-extensions-pictureplayer
opkg remove --force-depends enigma2-plugin-extensions-programmlistenupdater
opkg remove --force-depends enigma2-locale-{ar,bg,ca,cs,da,el,en-au,en-gb,es,et,fa,fi,fr,fy,he,hr,hu,id,is,it,ku,lt,lv,nb,nl,nn,no,pl,pt,pt-br,ro,ru,sk,sl,sr,sv,th,tr,uk,vi,zh-cn,zh-hk}

**Has this issue started to happen just recently?**
It's a new implementation

**To reproduce:**
1. Remove plugin packages from image
2. Backup settings
3. Display the content of enigma2settingsbackup.tar.gz and there is no removed-list.txt in /tmp

**Screenshots**
NA

**Image/Box Model (please complete the following information):**
 - Version: 7.3 20230803
 - BoxModel: SF8008

**Additional context**
NA

**Comment by jbleyel** [comment]
You need to reflash 7.3 from the feed or you need to get "/usr/lib/package.lst" from a 7.3 image and copy to your box if you don't wanna reflash.

**Comment by jeepcook** [comment]
I don't understand why you closed the issue. I did a fresh installation from the feed, 20230803 and the file removed-list.txt isn't created in the backup settings file.

**Comment by jbleyel** [comment]
Do you have this file?
"/usr/lib/package.lst"

**Comment by jbleyel** [comment]
Do you have installed the devel feed?

**Comment by jeepcook** [comment]
> Do you have this file? "/usr/lib/package.lst"

Yes

> Do you have installed the devel feed?

now yes. this implementation is only on devel ?

**Comment by jbleyel** [comment]
> 

It’s only in master branch for testing first.

**Comment by jeepcook** [comment]
> > 
> 
> It’s only in master branch for testing first.

Ok so sorry for the issue, I didn't understand that. In devel 7.4 it works, I have the file. It's very useful.

**Comment by atvcaptain** [comment]
after test with devel we merge all soon to 7.3 too
