### ISSUE TITLE
[Record Timer Overview] BUG: list sort issue

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2990]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Yes

**Describe the bug / Actual behaviour:**
There's also a sorting issue in the Record Timer Overview list. (`Done timers at end of list` setting is `ON`).

Note that DONE timers are sorted by oldest DATE first, but within each date, newest TIME.

ie.:
- 3 Aug 1900-2100
- 3 Aug 1730-1900
- 4 Aug 1900-2100
- 4 Aug 1800-1900
- 6 Aug 1430-1500

**Expected behaviour:**
Sort by date&time combined, either ASCending or DESCending (separate issue - add YELLOW `Sort` button)
ie.:
- 3 Aug 1730-1900
- 3 Aug 1900-2100
- 4 Aug 1800-1900
- 4 Aug 1900-2100
- 6 Aug 1430-1500

**Has this issue started to happen just recently?**
If yes, roughly when did it last work fine for you?

**To reproduce:**
1. Open Record Timer Overview with several timers, some complete

**Screenshots**
![20230806164150 copy](https://github.com/openatv/enigma2/assets/9741693/5a65f21a-efd6-4e95-87e9-279777f4ae37)

**Image/Box Model (please complete the following information):**
 - Version: [e.g. 7.2]
 - BoxModel: [e.g. SF8008]

**Additional context**

**Comment by jbleyel** [comment]
Please try this :

[Timers.py.zip](https://github.com/openatv/enigma2/files/12295796/Timers.py.zip)

**Comment by wedebe** [comment]
> Please try this :

Looks good, sorting as expected, thanks!
