### ISSUE TITLE
Show specific reason for recording failure

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2995]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
`Write error at start of recording. Disk full?` seems to be guessing what went wrong. It also references 'disk', when it may be a flash drive.

**Expected behaviour:**
Provide the user with the exact reason (Recording device isn't available (eg. unplugged USB), There's no space left on the device, The location is read-only etc.

**Has this issue started to happen just recently?**
No

**To reproduce:**
1. Set a timer to record on a device with no space.

**Screenshots**
![20230807114016](https://github.com/openatv/enigma2/assets/9741693/b5b9e17f-b709-4b53-9075-8b0883f4d7fa)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
N/A

**Comment by jbleyel** [comment]
Already done:

`			AddPopup(text=_("Write error while recording. %s") % (_("An unknown error occurred!"), _("Disk was not found!"), _("Disk is not writable!"), _("Disk full?"))[err], type=MessageBox.TYPE_ERROR, timeout=0, id="DiskFullMessage")
`
