### ISSUE TITLE
favourites(TV) - Übersetzung?

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#2998]
In Folge von https://github.com/openatv/enigma2/pull/2894

Bei mehrere Favoritenlisten erlauben "Off", ist der Titel der Senderliste: favourites(TV), favourites(Radio)
Ich denke zumindest in diesem Fall sollte die Übersetzung für favourites genutzt werden, passend zur Blauen-Taste.
Früher wurde nur TV angezeigt, aber das war wohl auch nicht richtig, obwohl in diesem Fall die Anzeige von favourites(TV) ungewohnt zu viel erscheint.

**Comment by GhostofGeeeee** [comment]
[ChannelSelection] buildTitle DEBUG: Service Name Before='favourites', After='favourites'.
[ChannelSelection] buildTitle DEBUG: Setting title='favourites (TV)'.

**Comment by jbleyel** [comment]
[ChannelSelection.py.zip](https://github.com/openatv/enigma2/files/12293082/ChannelSelection.py.zip)

**Comment by jbleyel** [comment]
UND?
Ist das Problem weg?

**Comment by GhostofGeeeee** [comment]
Sorry war AFK, ja ist weg!
Danke

**Comment by GhostofGeeeee** [comment]
Sobald man eine Empfangsliste(Grün) oder einen Anbieter(Gelb) auswählt, ist der Titel auch "Favoriten (TV)"

OT: 
```
# self.setTitle("%s: %s%s" % (mode, title, functionType))
self.setTitle("%s (%s)%s" % (title, mode, functionType))
```

Die andere Variante ist besser, ob Doppelpunkt oder " - " da kenne ich die Konventionen nicht, ich mag " - ".
Weil das (TV) wandert/springt sonst:
TV - Alle Sender
TV - Empfangslisten
TV - Favoriten

Alle Sender (TV)
Empfangslisten (TV)
Favoriten (TV)
