### ISSUE TITLE
Senderliste TV/Radio

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#2999]
Getestet mit 6.4 und höher aber war es schon immer so?
Jemand der noch alte Versionen testen kann? 6.3 und abwärts für die Frage seit wann das Problem auftritt.

TV schauen und die Senderliste öffnen
Zu Radio wechseln, ändert die Senderliste aber **TV-Kanal bleibt**
Schließen der Senderliste
Erneutes öffnen der Senderliste -> Senderliste(Radio) **nicht Senderliste(TV)**
CH+/- schaltet auf einen Radio-Kanal, erwarten würde man beim TV schauen aber natürlich einen TV-Kanal

Alternativ sollte es beim Wechseln zu Radio auch den Kanal von TV zu Radio ändern, aber das wäre vielleicht nicht die beste Lösung.

**Comment by jbleyel** [comment]
Senderliste + Radio wechseln + Schliessen sollte wieder zurück auf TV wenn man nicht auf einen Radio Sender umgeschaltet hat.
Damit sollte das Problem gefixt sein.
Ist aber vermutlich nicht so einfach.

Alles andere ist schlecht.

**Comment by GhostofGeeeee** [comment]
Einverstanden!
Also hab ich das als erster richtig als Bug identifiziert.

**Comment by jbleyel** [comment]
Bitte ausgiebig testen!!!

[ChannelSelection.py.zip](https://github.com/openatv/enigma2/files/12295252/ChannelSelection.py.zip)

**Comment by GhostofGeeeee** [comment]
Das Szenario ist recht einfach und soweit sieht das gut aus!!!
