### ISSUE TITLE
Default groupedservices file

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#3000]
Hello @GhostofGeeeee,

What's the intension of this block:

https://github.com/openatv/enigma2/blob/master/data/groupedservices#L153-L178

I plan to remove this block because this is a massive performance bottleneck.

hasActiveSubservicesForCurrentChannel is called every 10 seconds.

**Comment by GhostofGeeeee** [comment]
Like i said, I don't use it...
But it's not save to require that subservices are on same transponder!
How about Sky...?

**Comment by GhostofGeeeee** [comment]
I think this are not subservice and a misappropriation.

**Comment by jbleyel** [comment]
Sorry .. may fault .. you do not have added the HD Plus Block.
