### ISSUE TITLE
Please Update Depends For Skin MadMax

### ISSUE THREAD

**Issue by MOHAMED19OS** [openatv/enigma2#3005]
In your feed, Skin Mad Max still used the old Depends
 Depends: enigma2-plugin-extensions-weatherplugin, enigma2-plugin-skincomponents-weathercomponent, enigma2-plugin-systemplugins-weathercomponenthandler

but the New Depends will be used
Depends: enigma2-plugin-extensions-oaweather

https://github.com/m4dhouse/MadMax-Atv/blob/main/MadMax-Impossible-Skin/CONTROL/control

**Comment by jbleyel** [comment]
Wrong repro.
