### ISSUE TITLE
SF8008 Zeritier and other VPNs do not work after kernel update to 4.4.35 on 7.3

### ISSUE THREAD

**Issue by yzfr1** [openatv/enigma2#3007]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
When install Zerotier error in dependency 
Cannot satisfy the following dependencies for zer                                                                                                                                   otier:
 *      kernel-module-tun *

**Expected behaviour:**
kernel-module-tun-4-4.4.35_4.4.35-32_sf8008.ipk on which zerotier depends was installed and then zerotier itself.

**Has this issue started to happen just recently?**
About 2-3 weeks. I think when update kernel from 4.4.35-32 to 4.4.35-33.

**To reproduce:**
1. connect ssh
2. opkg update
3. opkg install zerotier

4. See result/error

root@sf8008:/tmp# opkg install zerotier
 * calculate_dependencies_for: Cannot satisfy the following dependencies for zerotier:
 *      kernel-module-tun *
 * opkg_solver_install: Cannot install package zerotier.

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - Version:  7.3.20230810 (2023-08-09)  
 - Kernel: 4.4.35 / 20230802
 - BoxModel:  SF8008

**Additional context**

**Comment by atvcaptain** [comment]
allready fixed https://github.com/oe-alliance/oe-alliance-core/commit/d7fd18b818f6809a125c0824149b518bd5127b08
