### ISSUE TITLE
[Keyboard] `Activating keymap: 'German keyboard'.` - even though locale/lang is set to English (US)

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3009]
locale/lang is set to English (US), but..

```
00:10:21.0218 [Keyboard] Activating keymap: 'German keyboard'.
00:10:21.0222 [Console] Processing command line 'loadkmap < /usr/share/keymaps/de.kmap'.
```

![20230812001602](https://github.com/openatv/enigma2/assets/9741693/feee549c-ed91-4ef9-b370-d680476a9fac)

**Comment by jbleyel** [comment]
The keyboard locale is a different setting and the default is de for most of the box vendors.
This issue can be improved by changing the default.
