### ISSUE TITLE
Restore Plugins fails on locally-installed ipks

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3012]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
Plugins which were installed locally prior to backing up settings appear on the `Restore Plugins` screen.

**Expected behaviour:**
Ideally, the installation source path is saved as part of the backup, and installed from there (if file still exists at that path).
Otherwise, list it but make it unselectable.

**Has this issue started to happen just recently?**
Yes. Previously, the plugin just wasn't listed

**To reproduce:**
1. Download a plugin ipk file and save to a memorable path (not `/tmp`)
2. Install plugin
3. Back up settings & plugins
4. Flash fresh image
5. Choose to restore plugins
6. See locally-installed plugin listed
7. During plugin restore, `Unknown package 'enigma2-plugin-systemplugins-servicescanupdates` message appears

**Screenshots**
![screenshot_20230810072622](https://github.com/openatv/enigma2/assets/9741693/f3257ce3-648f-4d9f-b207-4c7540f8c5ff)
![screenshot_20230811170846](https://github.com/openatv/enigma2/assets/9741693/eb3a68f0-a417-4bb4-bc86-5361558d5c29)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
N/A

**Comment by jbleyel** [comment]
Why don't you install the plugin from a shared place like /media/usb ?
Why not put this plugin on the feed?

**Comment by jbleyel** [comment]
Your ipk must be in one of these folders ->

["/media/hdd/images/ipk", "/media/usb/images/ipk", "/media/mmc/images/ipk", "/media/cf/images/ipk"]

**Comment by wedebe** [comment]
> Why don't you install the plugin from a shared place like /media/usb ? Why not put this plugin on the feed?

This is a plugin created by someone else. 

How do we get plugins added to feed?

**Comment by wedebe** [comment]
> Your ipk must be in one of these folders ->
> 
> ["/media/hdd/images/ipk", "/media/usb/images/ipk", "/media/mmc/images/ipk", "/media/cf/images/ipk"]

Confirmed this does exactly what I need, thanks!

@jbleyel , what's the process to have plugins added to thee feed?

**Comment by jbleyel** [comment]
If you want to have an open source plugin on the feed then make a request here ->

https://github.com/oe-alliance/oe-alliance-core

If the plugin is on GitHub.

If you have only the source files then send me the files. But you need to get the approval from the developer.
