### ISSUE TITLE
[Plugin Browser] Poor user experience - Manual restart to change grid/list view

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3013]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
User needs to exit Plugin Manager and re-open to activate layout change (grid <-> list)

**Expected behaviour:**
Reload layout without user intervention.

(in the meantime, a `*` in the settings item should point to the footnote)

**Has this issue started to happen just recently?**
Yes, grid view is a relatively recent addition

**To reproduce:**
1. Go to...
2. Press ...
3. Press ...
4. See result/error

**Screenshots**
![20230815113358](https://github.com/openatv/enigma2/assets/9741693/5d9f7fd3-fad2-497b-9f0a-2471d7638feb)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: N/A

**Additional context**

**Comment by jbleyel** [comment]
This is by design and not possible to fix because of Metrix.
Restart of enigma2 is nonsense if you only need to close and reopen the screen.

**Comment by jbleyel** [comment]
Hi @wedebe , just for information .. Goto OSD settings and change the menu style from horizontal to vertical.

**Comment by wedebe** [comment]
> Hi @wedebe , just for information .. Goto OSD settings and change the menu style from horizontal to vertical.

Similar problem in that the user needs to press save, exit the resulting menu page, then go into a level in the menu stack to see the change.

**Comment by jbleyel** [comment]
Exactly. And no user has a problem with this.
We have many other real issues and should focus on these.
