### ISSUE TITLE
fix snr for rs6060

### ISSUE THREAD

**Issue by popking159** [openatv/enigma2#3016]
can you fix snr for rs6060 in frontend.cpp file ??
this is fixed in openvix and openbh , it will be great to be done in openatv .
thanks in advance .

**Comment by popking159** [comment]
After update , SNR still not fixed .

**Comment by jbleyel** [comment]
We do always commit to master first and then to the release branch.

https://github.com/openatv/enigma2/commit/d9ca31b45bb35db717023bd4a5e9a1b1a421b9d8
