### ISSUE TITLE
Remove accents from subtitle

### ISSUE THREAD

**Issue by popking159** [openatv/enigma2#3017]
**Is your feature request related to a problem? Please describe.**
accents in arabic subtitles makes text looks broken " disconnected letters " .

**Describe the solution you'd like**
remove accents from external subtitle , maybe add yes/no option in subtitle settings .

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jbleyel** [comment]
I need more info.

**Comment by popking159** [comment]
![Screenshot_2023-08-15-21-58-39-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/openatv/enigma2/assets/47087407/59f4c1af-25c8-4ea2-8dd8-f54587353d4f)

I hope this screenshot helps , I mean the diacritics in Arabic letters " tashkeel " . When it is present the line will looks broken .

**Comment by wedebe** [comment]
Perhaps a more appropriate solution would be for openATV to use a font which can better display diacritics.

**Comment by popking159** [comment]
It is better to remove diacritics when playing subtitle, so any font supporting Arabic will be fine , rather than selecting specific font  .

**Comment by jbleyel** [comment]
Sorry .. I cannot read Arabic.
What is "diacritics" / "tashkeel"?
So what exactly has to be removed from the string?

**Comment by popking159** [comment]
![images](https://github.com/openatv/enigma2/assets/47087407/39d68eeb-66e5-443f-adc9-e97ee7af7e57)

Diacritics is not only for Arabic .
Example :
I want this litter "è" to be shown as "e"
" Cómo estás " ----> " Como estas "

**Comment by jbleyel** [comment]
Understood, this will be difficult because you need a letter mapping.
I have no idea how many letters needs to be replaced.

**Comment by wedebe** [comment]
> Understood, this will be difficult because you need a letter mapping. I have no idea how many letters needs to be replaced.
> 
> Except the diacritics is an extra utf-8 char and we can remove this char from the string.

https://bobbyhadz.com/blog/python-remove-accents-from-string

Worth looking at, but I'm not sure how Arabic text would be handled.

**Comment by jbleyel** [comment]
> > Understood, this will be difficult because you need a letter mapping. I have no idea how many letters needs to be replaced.
> > Except the diacritics is an extra utf-8 char and we can remove this char from the string.
> 
> https://bobbyhadz.com/blog/python-remove-accents-from-string
> 
> Worth looking at, but I'm not sure how Arabic text would be handled.

Not really working for Arabic text.

**Comment by jbleyel** [comment]
more info:

https://stackoverflow.com/questions/66988153/removing-arabic-diacritic-using-python

**Comment by popking159** [comment]
![Screenshot_2023-08-15-23-09-12-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/openatv/enigma2/assets/47087407/21adc932-9da0-47a2-919b-61671c7479d6)
The 8 main Arabic diacritics with their unicode , if it removed during playing subtitle, it will be better .

Thanks for your patience.

**Comment by jbleyel** [comment]
Not that easy.
I think the magic is here -> https://github.com/openatv/enigma2/blob/master/lib/gdi/font_arabic.cpp

This needs to be done by someone with high c++ enigma skills who can read arabic.

**Comment by jbleyel** [comment]
Hi @popking159 , is it fixed?

**Comment by popking159** [comment]
> Hi @popking159 , is it fixed?

Yes , it is fixed now .
