### ISSUE TITLE
Lost old files?

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3022]
As result on [[Feature Request] Astra2 default channel list](https://github.com/openatv/enigma2/issues/2700):

[wedebe](https://github.com/wedebe) commented [last week](https://github.com/openatv/enigma2/issues/2700#issuecomment-1679565265)
Perhaps we could remove these files then?

```
/openatv/enigma2/
    userbouquet.orf.tv
    userbouquet.premiere.tv
    userbouquet.srgssr.tv
```
These were last updated 18 years ago!

[GhostofGeeeee](https://github.com/GhostofGeeeee) commented [last week](https://github.com/openatv/enigma2/issues/2700#issuecomment-1680185873)
These files belongs to:

```
/openatv/enigma2/
    bouquets.tv
    userbouquet.favourites.tv
```
They where moved and [removed](https://github.com/openatv/enigma2/commit/8c421660301ef7b76f560aced85822da7493df65). **-> Delete them(orf, premiere, srgssr) too!?**
How about

`/openatv/enigma2/lamedb`
too?

**Comment by jbleyel** [comment]
Where are these 3 files are come from?
They are not in the current default settings.

**Comment by GhostofGeeeee** [comment]
The question should be why they were not deleted.
Maybe at this point, where they were partially deleted, they are not obsolete and useful, but a long time ago...

**Comment by jbleyel** [comment]
No .. the question is .. where are you getting these files.
They are not part of the default settings.

**Comment by GhostofGeeeee** [comment]
I hope this was a misunderstanding.
See last files on [list](https://github.com/openatv/enigma2).

**Comment by jbleyel** [comment]
You mean this -> 

<img width="926" alt="Bildschirmfoto 2023-10-12 um 11 13 28" src="https://github.com/openatv/enigma2/assets/964927/9853becc-cf8a-4e45-a707-8f75a283c13f">

**Comment by jbleyel** [comment]
I think these files are only here on GitHub and not used at all.

**Comment by GhostofGeeeee** [comment]
You are right, but 

> not used at all

and 18 Years old!

**Comment by GhostofGeeeee** [comment]
Can I ask, these files are for what?
