### ISSUE TITLE
[Plugin Manager] Unintuitive user experience - buttons hidden when offline

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3033]
When the box isn't connected to the internet, the `Install` and `Update` buttons are hidden. The user isn't advised as to why this has happened. 

As a long-time user of Enigma2 and generally tech-savvy, this confused me (I initially thought it was a bug).

An intuitive approach (where dimming/disabling a button isn't possible), is to provide the user with a reason as to why they can't do what they want to do.

In this case, showing a dismissible notification to say `Your box isn't connected to the internet` would be more appropriate.

Even better (but I don't think this is done anywhere in E2), would be to ask the user if they want to go to Network Settings so they can sort the issue.

![screenshot_2023-08-26_12-29-31](https://github.com/openatv/enigma2/assets/9741693/48cbb260-3325-4389-8b89-e9adf961440c)
![20230826130843](https://github.com/openatv/enigma2/assets/9741693/1658361a-9d2c-49ed-bf54-59fb9370d51b)
![20230826132114](https://github.com/openatv/enigma2/assets/9741693/888aa8ea-d76c-4c55-b382-e8917e0e5456)

**Comment by IanSav** [comment]
I disagree that the UI is unintuitive.  It is consistent with many/most of the screens in Enigma2 when controls are removed if the functions those controls represent are not available.  The screen is "Plugin Browser", it has a number of functions.  Some functions may not be available if the user is offline, though other functions remain available.  Users may still browse the installed plugins, they may select a plugin to run and they can remove any plugins that they no longer require.  If this was the "Plugin Installer" then it would be appropriate to acknowledge the lack of a network connection as the code would be completely non functional.

Another point worth making is that many user do not like so many pop ups all over the UI.  Adding one here may not be welcomed by many users.  I could suggest a change where there is an Internet connectivity widget to be added to the screen but I am sure that @jbleyel and all the other skinners will not be happy having to change their skins.  Another idea might be to change the title if there is no Internet connectivity.  I am not sure I like the visuals of this idea but it would not require a skin change.  If this change is satisfactory and significantly desirable then let us know and I will discuss the option with @jbleyel.

Something else I should mention is that there is more work being done on PluginBrowser that I will commit when I fully return to Enigma2.  One of the changes is to no longer check for Internet connectivity on every screen update.  This is being done to speed up the UI.  The current code has the ability to update the buttons if the Internet connectivity changes.  We discussed the constant Internet checks and its effect on the UI and it was decided that only one check is needed when the code first starts.

**Comment by jbleyel** [comment]
If a function is not available then the button will not be displayed. This is the case everywhere or will be soon.

That you need an internet connection to install a plugin, that should be clear to everyone and therefore I find it useless to add something here.

**Comment by jbleyel** [comment]
I close this because adding extra things here is not that easy in Metrix and needs changes in all skins.
