### ISSUE TITLE
Using the MetrixHD gui to install usb tuner driver fails on fresh installed 7.3 (vuduo2)

### ISSUE THREAD

**Issue by Ntemis** [openatv/enigma2#3034]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Latest 24/08/23 as of today so yes
**Describe the bug / Actual behaviour:**
you cannot install any usb tuner drivers the gui crashes
**Expected behaviour:**
to be able to perform the asked task

**Has this issue started to happen just recently?**
Yes , was working fine on v7.2 where am coming from

**To reproduce:**
try to install a usb driver module over internet

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Vuduo 2

**Additional context**
I tried to install over telnet and noticed some weird bugs
https://dpaste.org/s3K03

Points of interest
after issuing an opkg install enigma2-plugin-drivers-dvb-usb-rtl2832
you get this warning
enigma2-plugin-drivers-dvb-usb-rtl2832: unsatisfied recommendation for kernel-module-dvb-usb-rtl2832
then it installs some not needed at all Afatech firmwares and the rest you can check from the log i posted

**Comment by jbleyel** [comment]
What exactly is the problem?
What is "metro gui"?


"unsatisfied recommendation" is a well known warning in this case and this warning cannot be removed because it's by design.

**Comment by Ntemis** [comment]
@jbleyel 
[20230826-191905-enigma2-crash.log](https://github.com/openatv/enigma2/files/12458316/20230826-191905-enigma2-crash.log)

[20230826-181315-enigma2-crash.log](https://github.com/openatv/enigma2/files/12458315/20230826-181315-enigma2-crash.log)

**Comment by wedebe** [comment]
I've got a rtl2832-based tuner, I'll try it on my Mut@nt HD51 in the next few days.

**Comment by wedebe** [comment]
I'm getting the extraneous af90*5 package installs too. Don't recall seeing them when I installed several times last year. Not causing a crash here though.

The `enigma2-plugin-drivers-dvb-usb-rtl2832` ipk states that it's `Version: 1.0-r0`
[control.txt](https://github.com/openatv/enigma2/files/12569695/control.txt)

I've run the following and rebooted without negative effect, I can still view the channels on the 2832 dvb stick:
```
opkg remove firmware-dvb-usb-af9015  --force-depends
opkg remove firmware-dvb-usb-af9035-01  --force-depends
opkg remove firmware-dvb-usb-af9035-02  --force-depends
```

af9105 and af9035 have their own plugins, so something's seems to bee wrong in the `enigma2-plugin-drivers-dvb-usb-rtl2832` plugin.
![20230910195910](https://github.com/openatv/enigma2/assets/9741693/2a65256d-8127-448c-89f8-c4a4cca88b3c)

**Comment by wedebe** [comment]
[enigma2-plugin-drivers-dvb-usb-rtl2832.bb.txt](https://github.com/openatv/enigma2/files/12581119/enigma2-plugin-drivers-dvb-usb-rtl2832.bb.txt)

This file is dated 10th April 2022 (when I last pulled that repo)

**Comment by Ntemis** [comment]
i think the logs are very clear, the packages need cleaning and the gui fixing from crashing
let me put it here as simple as i can
From **enigma2-plugin-drivers-dvb-usb-rtl2832**
need to go
- firmware-dvb-usb-af9015
- firmware-dvb-usb-af9035-01
- firmware-dvb-usb-af9035-02
From **enigma2-plugin-drivers-dvb-usb-it913x** 
need to go
- kernel-module-af9033-3.13.5
- kernel-module-dvb-usb-af9035-3.13.5.

**Comment by jbleyel** [comment]
This is not an enigma issue.
Drivers and kernel modules are part of the build system.

-> https://github.com/oe-alliance/oe-alliance-core
