### ISSUE TITLE
5002 Recording rephrased so its not deemed to be support for illegal things

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3037]
There are many legal streams that users would like to record when using 5002 Exteplayer3 and Serviceapp

Its never been possible to do this so can someone please look into this ?

If it cannot be done then please just say so rather than just closing the issue like the last one I raised here about this.

**Comment by jbleyel** [comment]
Record feature of 5002 streams must be implemented in ServiceApp as I remember.
And this is probably very complex or maybe impossible.

**Comment by ian10951** [comment]
Okay thanks for the reply.

I was hoping it was just a simple patch of Serviceapp similar to the degree of difficulty of the new user agent patch thats due to be built into images in the next few days.

**Comment by jbleyel** [comment]
Close because of wrong repro.
