### ISSUE TITLE
[Timeshift] Start of timeshift shows incorrect duration

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3039]
Should start at 00:00 but shows a seemingly random number (based on available space on device?)

(I haven't tested > 60mins but this should be formatted 1:00:00 if not already the case)

This has been a long-time bug.

![20230831232835](https://github.com/openatv/enigma2/assets/9741693/198e5885-314a-4091-83f4-3a013569e270)

**Comment by wedebe** [comment]
Possibly this?

```
00:52:31.0593 [eDVBTSTools] calcEnd [@ML] m_streaminfo.getLastFrame failed, fallback
00:52:31.0594 [eDVBChannel] getLength failed - can't seek relative to end!
```

**Comment by GhostofGeeeee** [comment]
> Possibly this?
> 
> ```
> 00:52:31.0593 [eDVBTSTools] calcEnd [@ML] m_streaminfo.getLastFrame failed, fallback
> 00:52:31.0594 [eDVBChannel] getLength failed - can't seek relative to end!
> ```

Looks logical, a stream Issue!?
On TV you get this too? Normal not.
You can edit "Steps to reproduce"!

**Comment by wedebe** [comment]
This still happens on 7.5 2024-10-25

![timeshift](https://github.com/user-attachments/assets/7de0d72a-e73c-4fb1-9119-a4fce607cd72)

**Comment by jbleyel** [comment]
Then fix was for negative values and I had never such big positive value while I have tested this.
So I'm not able to reproduce this.
