### ISSUE TITLE
OpenATV Build - Unable to obtain same feeds as https://feeds2.mynonpublic.com

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3040]
Following the build instructions on page https://github.com/openatv/enigma2, I have differences between my build feeds and the ones in https://feeds2.mynonpublic.com/7.3/

Example:
Package enigma2-plugin-systemplugins-serviceapp
- in my cortexa15hf-neon-vfpv4 directory I have 0.5+git184+afdd0ca-r2 version
- in the feeds2.mynonpublic.com the 0.5+git184+afdd0ca-r2.2 is available

Packages sysvinit and sysvinit-pidof:
- in my sf8008 directory I have sysvinit_3.04-r0.1_sf8008.ipk and sysvinit-pidof_3.04-r0.1_sf8008.ipk
- in the feeds2.mynonpublic.com the 3.04-r0.2 are available for booth packages

Is there a missing instruction ? a missing repository ?

Thanks

 - Version: 7.3
 - BoxModel: SF8008
 - Feeds and images build on Ubuntu 22.04 LTS

**Comment by atvcaptain** [comment]
its not a issue, only a rebuild fix for some issue after last e2 update master to 7.3 branch

**Comment by jeepcook** [comment]
Ok thanks. I will clean everything and do a full rebuild.

**Comment by jeepcook** [comment]
Hello,
Did a full end clean rebuild after deleting build-enviroment directory. This took the night to be completed.
But I still have the same problem, some package are not in their last version and different from the official feed.
Sames examples as my first post.
I think this issue has to be reopened to be investigate further more.
Thanks

**Comment by jbleyel** [comment]
There is no issue. 
This package : 0.5+git184+afdd0ca-r2 and this 0.5+git184+afdd0ca-r2.2 is exactly the same.
The revision at the end is because of force update if you do not make flash.

You can ignore these differences.

**Comment by jeepcook** [comment]
The comportment of these 2 versions are different, one (r2.2) add user agent to exteplayer3 process, the other no (r2)

And what about  sysvinit and sysvinit-pidof?

**Comment by jbleyel** [comment]
sysvinit is from open embedded.

**Comment by jeepcook** [comment]
serviceapp change something in the exteplayer3 command line:

here with 0.5+git184+afdd0ca-r2 version:
exteplayer3 http://localhost:8088/https://www.youtube.com/watch?v=gxG3pdKvlIs -a 0 -n 0

here with 0.5+git184+afdd0ca-r2.2:
exteplayer3 http://localhost:8088/https://www.youtube.com/watch?v=gxG3pdKvlIs -h User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 -a 0 -n 0

For sysvinit and sysvinit-pidof I have on my own feeds v3.04-r0.1 end on feeds2.mynonpublic.com 3.04-r0.2.

So excuse me but there are real differences.

**Comment by atvcaptain** [comment]
i said because of rebuild, because there was change in openatv git, that all

**Comment by jeepcook** [comment]
Your explanation isn't clear, "because" "that's all"... so now we are simply unable to build exactly the same packages as the one generated by you...

**Comment by nickersk** [comment]
@jeepcook are you sure you have updated meta-oe-alliance submodule?

**Comment by jeepcook** [comment]
Exactly as describe in the documentation:

Switch to folder openatv7.3

cd openatv7.3
Clone oe-alliance repository

git clone https://github.com/oe-alliance/build-enviroment.git -b 5.3
Switch to folder build-enviroment

cd build-enviroment
Update build-enviroment

make update

**Comment by nickersk** [comment]
output of "cd meta-oe-alliance;git status;git log"?

**Comment by jeepcook** [comment]
`commit 17e49fd5b211483af921ee20dd9817a813663ab2 (HEAD, origin/HEAD, origin/5.3, 5.3)
Author: Captain <captain.onboard@web.de>
Date:   Sat Sep 2 12:59:33 2023 +0200

    wsdd start async, add wsdd init start script, to fix issue on some models, box not visible in windows explorer

commit e7801e50fc757f7013d175e396a60b968c162a38
Author: Huevos <rowland@moralet.com>
Date:   Sat Sep 2 12:56:10 2023 +0200

    [dreambox-buildimage_1.5.bb] update protocol
    Updates: 768e6a1becee617ddc4aebe8a37933d4f4e0b919

commit 09c2215e93482bf8b3bc340c0ccc267f13372234
Author: openvix-build <openvix-build@moralet.com>
Date:   Sat Sep 2 10:44:43 2023 +0000

    openvix: developer 6.4.005.007

commit 7b147e902e586336319bcacdba3a1b82f813cf3d
Author: s3n0 <s3n0@users.noreply.github.com>
Date:   Sat Sep 2 09:09:05 2023 +0200

    Update enigma2-plugin-extensions-chocholousek-picons.bb (#840)

    minor adjustment... development support year... during the period of years - changed 2022 to 2023

commit 325ea8a9f35db7c09cdc2b70ad0257db96eb9f6d
Author: Ev0-BH <Ev0_BhT@outlook.com>
Date:   Sat Sep 2 00:08:56 2023 +0100

    openbh: release 5.3.006`

**Comment by atvcaptain** [comment]
i merge the last rev only for you

**Comment by jeepcook** [comment]
It wasn't a whim. I have detected differences, I'm reporting them to try to understand and help resolve them. You made 2 commits, the ones I spotted but there are perhaps others.

**Comment by jeepcook** [comment]
@atvcaptain What is this commit? For serviceapp it's just to have r2.2 instead of r2? But what about the content, this new r2.2 is not the same in the one available in the feeds! The comportment of the plugin is not the same. There is a real difference between r2 and r2.2 not just the name of the ipk....

Are you serious ?

**Comment by jeepcook** [comment]
On the left the real r2.2 version, on the right your fake version
![image](https://github.com/openatv/enigma2/assets/17811804/94edc240-0be9-474d-9511-9ced224520c5)

**Comment by atvcaptain** [comment]
?? different build host, different gcc Updates, so no idea what you are hoping for
