### ISSUE TITLE
[File Commander] Queued file moves don't refresh file list when operation completes

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3047]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Yes

**Describe the bug / Actual behaviour:**
Initiating the move of large files (eg. recordings across USB) results in a `...queued...` notification.
Once the move has completed successfully, the notification reappears, but the files that were moved still show in the source side.

**Expected behaviour:**
Once a file move has completed, refresh the file list panels.

**Has this issue started to happen just recently?**
No

**To reproduce:**
As above

**Screenshots**
N/A

**Image/Box Model (please complete the following information):**
 - Version: N/A
 - BoxModel: N/A

**Additional context**
Manual file list refresh works as expected.

**Comment by GhostofGeeeee** [comment]
For me it works as expected.
You start moving and wait without interaction? (Time?)
It doesn't work correctly in any situation?
Please help me to reproduce!

**Comment by jbleyel** [comment]
This should be fixed.
