### ISSUE TITLE
[Mouunt Manager] USB pen drive not listed in `Setup Mounts` page

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3051]
![20230920014411](https://github.com/openatv/enigma2/assets/9741693/75e2e105-ffb8-4634-b71d-3d1604b9d751)

```
root@mutant51:~# blkid
/dev/mmcblk0p3: <snip>
/dev/mmcblk0p1: <snip>
/dev/sda1: LABEL_FATBOOT="EFI" LABEL="EFI" UUID="67E3-17ED" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="8e575668-32be-4695-8c74-bc6aa24cf6c5"
/dev/mmcblk0p8: <snip>
/dev/sda2: LABEL="MBP17" UUID="620E-0434" BLOCK_SIZE="512" TYPE="exfat" PARTUUID="a41218dc-50f8-4d3a-975f-76b69b8d80aa"
/dev/mmcblk0p7: <snip>
/dev/sdb: LABEL_FATBOOT="HD51" LABEL="HD51" UUID="7D08-1606" BLOCK_SIZE="512" TYPE="vfat"
/dev/mmcblk0p4: <snip>
/dev/mmcblk0p2: <snip>
/dev/mmcblk0p5: <snip>
/dev/mmcblk0p6: <snip>
```
(HD51)

/etc/fstab content:
```
rootfs         /             auto     defaults        1 1
proc           /proc         proc     defaults        0 0
devpts         /dev/pts      devpts   mode=0620,gid=5 0 0
usbdevfs       /proc/bus/usb usbdevfs noauto          0 0
tmpfs          /var/volatile tmpfs    defaults        0 0
/dev/mmcblk0p7 none          swap     defaults        0 0
```

`sfdisk -l` shows
```
Disk /dev/sdb: 62.5 MiB, 65536000 bytes, 128000 sectors
Disk model: Flash Disk      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc2730f1a
```

I can manually edit fstab to set
`UUID=7D08-1606  /media/mmc      vfat    defaults        0 0`
which allows access in File Manager via `/media/mmc`

But can't manage it in Mount Manager. From recollection, that drive never appeared.

Two other USB sticks *DO* appear (not connected in screenshot above):
```
/dev/sdc1: UUID="436f797b-160e-48b6-9399-b70e58754610" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="3b689f73-01"
/dev/sdd1: LABEL_FATBOOT="32GB FAT" LABEL="32GB FAT" UUID="063C-1F1D" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="Basic data partition" PARTUUID="55fe1593-9864-45b0-9bfe-6099380369a5"
```

**Comment by atvcaptain** [comment]
looks wrong,, mount manager cant mount 
/dev/sdb: LABEL_FATBOOT="HD51" LABEL="HD51" UUID="7D08-1606" BLOCK_SIZE="512" TYPE="vfat"

what makes me wonder about your usb key, why is the partition number missing the device should be named /dev/sdb1 and not just the device without partitions: /dev/sdb

**Comment by atvcaptain** [comment]
i read some info technically is possible format a usb key without a partition table, but its a bad idea, many os not see this drive correctly or show only as free, we support only usb keys with partition table, please reformat you usb key, its not a bug
