### ISSUE TITLE
`Single EPG` & `Multi EPG` buttons missing

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3061]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Yes, 2023-09-25

**Describe the bug / Actual behaviour:**
Event Info page accessed via Channel List (then Info Button) doesn't show `Single EPG` & `Multi EPG` buttons
However, Event Info page accessed via Info Button directly shows both buttons.

**Expected behaviour:**
Both Event Info pages should show the same buttons

**Has this issue started to happen just recently?**
No

**To reproduce:**
See above

**Screenshots**
Info Button from Channel List:
![BBC RB 1 HD_20230927010832](https://github.com/openatv/enigma2/assets/9741693/8320374f-7ce5-494c-a908-6dd0d74ae66f)

Info Button directly:
![BBC RB 1 HD_20230927010808](https://github.com/openatv/enigma2/assets/9741693/0978678d-63d2-4915-a534-56f8655b3520)

**Image/Box Model (please complete the following information):**
 - Version: N/A
 - BoxModel: N/A

**Additional context**
N/A

**Comment by GhostofGeeeee** [comment]
> **Expected behaviour:**
> Both Event Info pages should show the same buttons

I think, then this page will not have these buttons. You want this?
On open Single/Multi EPG by the Info Button from Channel List, will open this on top and you have a stack with these and all want to be closed later.

This is not a bug, look at https://github.com/openatv/enigma2/blob/a54771b52d6b3886584fdd5202c2d2af168d8a98/lib/python/Screens/EventView.py#L286
```
		if singleEPGCB:
			self["key_yellow"] = StaticText(_("Single EPG"))
			self["epgActions2"] = HelpableActionMap(self, ["EventViewEPGActions"], {
				"openSingleServiceEPG": (singleEPGCB, _("Open the single service EPG view"))
			}, prio=0, description=_("EventViewEPG Actions"))
		else:
			self["key_yellow"] = StaticText("")
			self["yellow"].hide()
```

**Comment by wedebe** [comment]
>> Both Event Info pages should show the same buttons

>> I think, then this page will not have these buttons. You want this?

Both Event Info pages should show the `Single EPG` & `Multi EPG` buttons.

It's possible the code you linked to was originally written to simplify implementation (window stacking/navigation/closing) rather than for a streamlined user experience.

**Comment by GhostofGeeeee** [comment]
You really understand my comment?
You have to exit 3 times or more. This is not a wanted workflow!


> Both Event Info pages should show the & buttons.`Single EPG``Multi EPG`



>> I think, then this page will not have these buttons. You want this?

**Comment by GhostofGeeeee** [comment]
Buttons with unavailable functions are now in many screens hidden.
The way you want maybe is a unavailable way.

**Comment by GhostofGeeeee** [comment]
Technical but...
Your FoodStore can sell Cars, Travelings and Toilets but i don't want it.
Who decide what's available!?

**Comment by jbleyel** [comment]
Link #3119
