### ISSUE TITLE
EPGImporter added the ability to download EPG data cyclically at a set hourly interval.

### ISSUE THREAD

**Issue by azman26** [openatv/enigma2#3066]
Due to the capabilities of current receivers and the increasing access to FAST platforms, the function of cyclical EPG downloading at a specific time interval would be extremely useful.

I am thinking about service providers such as PlutoTV, SamsungTVPlus, etc., where we can obtain EPG for 6-8 hours for a given FAST platform from various sources, either from https://i.mjh.nz/ or https://www.apsattv/ .com/

Plugins @Billy2011 (Rakuten, Pluto, Samsung) also have this functionality and even E2m3u2 Bouquet Maker by Dorik1972.

In order not to mess with the scripts that launch the EPGImporter plugin, which is not convenient because remote control commands are used for this purpose via the WebIf interface, it would be very welcome to add such a function in the plugin settings.

Please consider my request, which will be useful to most plugin users.
I think it's no problem for developers to add such a function to their code.

Regards.

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/XMLTV-Import/issues
