### ISSUE TITLE
[Audio] Changing between Dolby/Non-Dolby channels when volume offset is set unmutes volume

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3072]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Yes, 2023-10-03

**Describe the bug / Actual behaviour:**
When a `Default Dolby Digital / AC3 offset`  is configured (see screenshot below), the user has muted the box, then changes channel between a *Dolby/Non-Dolby audio* capable  channel, mute gets unset.

**Expected behaviour:**
Mute state should not change between channel changes.

**Has this issue started to happen just recently?**
Not that I'm aware of.

**To reproduce:**
1. As above

**Screenshots**
![20231004171159](https://github.com/openatv/enigma2/assets/9741693/293abaed-21f5-4e71-94a2-75017bd40669)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
N/A

**Comment by GhostofGeeeee** [comment]
(Sorry) Please let me add a similar thing, because i never know, is it bug or feature...
If you start a movie in EMC, the mute state is changed to not mute!

**Comment by wedebe** [comment]
> (Sorry) Please let me add a similar thing, because I never know, is it bug or feature... If you start a movie in EMC, the mute state is changed to not mute!

Confirmed here too. Weirder still is that using the Up/Down nav keys to select a different movie mid-playback doesn't change mute state between *Dolby/Non-Dolby audio* movies, but Stopping and starting playback from the list DOES!

**Comment by jbleyel** [comment]
This is a driver issue and cannot fixed without complete refactoring volume control..
The current mute state will always set to off if you change the volume by writing /proc/stb/avs/0/volume to the proc.

**Comment by jbleyel** [comment]
I see only one workaround as solution.
If mute is on then ignore the offset on channel changes.

**Comment by jbleyel** [comment]
Hi @wedebe , is my workaround ok?

**Comment by jbleyel** [comment]
Friendly reminder.

**Comment by wedebe** [comment]
> Hi @wedebe , is my workaround ok? If yes then i can implement it.

@jbleyel , I think if the offset has been applied, the user mutes, changes to a channel that _should_ have the offset _de/un-applied_, unmutes, then changes to a channel that causes the offset to be applied, the volume has changed twice in the same direction.

**Comment by jbleyel** [comment]
> > Hi @wedebe , is my workaround ok? If yes then i can implement it.
> 
> @jbleyel , I think if the offset has been applied, the user mutes, changes to a channel that _should_ have the offset _de/un-applied_, unmutes, then changes to a channel that causes the offset to be applied, the volume has changed twice in the same direction.

I see no way to implement this without massive refactor and this can also cause breaking other plugins.

**Comment by wedebe** [comment]
TBH, it's not a big enough issue to have to refactor and risk regression.

Thanks for investigating.

**Comment by GhostofGeeeee** [comment]
I think you do not have to close unfixed bugs. 
jbleyel don't like to do it now(no problem) but please help him to solve Issues he is answering!!
