### ISSUE TITLE
crash when file with CZ&SK diacritics is on usb drive

### ISSUE THREAD

**Issue by grumpynho** [openatv/enigma2#3083]
Hi,
my boxes crashes when I want open USB drive with file named contain czech and slovak diacritics(á, ä, é, í, ó, ô, ú, ý, č, ď, ě, ň, ř, š, ť, ž, ů) in file commander or EMC.

[20231016-121904-enigma2-debug.log](https://github.com/openatv/enigma2/files/12915189/20231016-121904-enigma2-debug.log)
[20231016-121925-enigma2-crash.log](https://github.com/openatv/enigma2/files/12915190/20231016-121925-enigma2-crash.log)

 I did try flash clean from 8.10.2023 but result is the same.

**Image/Box Model (please complete the following information):**
 - Version: 7.3 15.(16).10.2023
 - BoxModel: [independent] - uclan ustym 4k pro, amiko viper 4k v20

**Comment by jbleyel** [comment]
Please connect to your box via ssh/telnet.
Then goto the folder where the file is located.

Then start this command:

`
python -c 'import glob;print(glob.glob("*"))'
`

and post the result here.

**Comment by grumpynho** [comment]
Is it OK?
['Kal\udcedf\udce1t Chal\udcedf\udce1t.mp4']
File is named Kalifát Chalifát.

**Comment by jbleyel** [comment]
Your filename is not valid.

https://charbase.com/dced-unicode-invalid-character
https://charbase.com/dce1-unicode-invalid-character
