### ISSUE TITLE
[Picons] Channel List & Movie List use different picon path to Info Bar & Event Info

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3090]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-10-23

**Describe the bug / Actual behaviour:**
If `/picons` and (eg.) `/media/usb/picons` exist, the former will be used for the `Channel List` & `Movie List`
and `Info Bar` & `Event Info` will use the latter.

**Expected behaviour:**
There should be a single, ultimate picon path provided by ~Pecan pie~ Picon.py, ordered consistently if there is more than one path (eg. to set preferred picon path)

**Has this issue started to happen just recently?**
Hadn't noticed, probably not.

**To reproduce:**
1. Install picons on /picon
2. Install a different style of picon (eg. blue background) on another path, eg. /media/usb/picon or /media/mmc/picon
3. Restart GUI
4. Check Channel List, Movie List, Info Bar & Event Info
5. Notice different picon styles

**Screenshots**
![MovieList-20231024144903](https://github.com/openatv/enigma2/assets/9741693/0704228c-153e-4849-ad34-505ebd49332a)
![EventInfo-20231024144839](https://github.com/openatv/enigma2/assets/9741693/96fc5223-61fe-4170-8c3e-ef90da3faf48)
![InfoBar-20231024144802](https://github.com/openatv/enigma2/assets/9741693/5d7bc1de-2fe8-4db7-8185-24f9b0ea2423)
![ChannelList-20231024144742](https://github.com/openatv/enigma2/assets/9741693/3fe0b043-4f6c-42c5-86fc-f27d835340a5)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
Furthermore, Info Bar & Event Info don't load picons from (listed in Plugin Manager's picon install path options) /media/usb2 (and possibly other paths)

Should this be enigma core functionality?

**Comment by jbleyel** [comment]
This is a Metrix issue because MetrixHDXPicon renderer is using different path's

**Comment by jbleyel** [comment]
Please try this -> 
[MetrixHDXPicon.py.zip](https://github.com/openatv/enigma2/files/13189900/MetrixHDXPicon.py.zip)

**Comment by jbleyel** [comment]
Should be fixed now.
Please check and close the issue.

**Comment by wedebe** [comment]
@jbleyel , this has fixed the issue in question, thanks

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/issues/3126
