### ISSUE TITLE
[Plugin Manager] Picon target location list missing available partitions

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3091]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-10-23

**Describe the bug / Actual behaviour:**
Opening the `Picon package target location` option list shows an incomplete list of locations.

**Expected behaviour:**
The options should list all available partitions (subject to supported filesystems).

**Has this issue started to happen just recently?**
Previously there seemed to have been no configurable picon path, then there was a popup selector at time of picon package install, the current implementation differs.

**To reproduce:**
1. Open Plugin Manager
2. Press `Menu`
3. Go to `Picon package target location` option
4. Press `OK` to see list
5. Observe that not all (supported) partitions are listed

**Screenshots**
![ITV1 HD_20231024154133](https://github.com/openatv/enigma2/assets/9741693/177a8afc-c0bf-439a-b2f8-b0a9e679afe1)
![ITV1 HD_20231024154312](https://github.com/openatv/enigma2/assets/9741693/9c454af4-7f66-4cef-b5c6-77ecc51c891a)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
```
/dev/sda1: TYPE="vfat" LABEL_FATBOOT="EFI" LABEL="EFI" UUID="67E3-17ED" BLOCK_SIZE="512" PARTLABEL="EFI System Partition" PARTUUID="8e575668-32be-4695-8c74-bc6aa24cf6c5"
/dev/sda2: TYPE="exfat" LABEL="MBP17" UUID="620E-0434" BLOCK_SIZE="512" PARTUUID="a41218dc-50f8-4d3a-975f-76b69b8d80aa"
/dev/sdb1: TYPE="vfat" LABEL_FATBOOT="1GB FAT32" LABEL="1GB FAT32" UUID="3D8C-1B10" BLOCK_SIZE="512" PARTUUID="93117b44-01"
/dev/sdb2: TYPE="ext4" LABEL="4GB ext4" UUID="9bbd328f-4ad8-4059-9150-c0fe2d4061ca" BLOCK_SIZE="4096" PARTUUID="93117b44-02"
/dev/sdb3: TYPE="exfat" LABEL="24GB exFAT" UUID="0AC2-771B" BLOCK_SIZE="512" PARTUUID="93117b44-03"

Filesystem                Size      Used Available Use% Mounted on
/dev/sda1               196.9M     80.1M    116.8M  41% /media/hdd2
/dev/sda2                 1.8T      1.8T    111.9M 100% /media/hdd
/dev/sdb1              1022.0M    751.9M    270.1M  74% /media/mmc
/dev/sdb2                 3.9G      2.8G    904.2M  76% /media/usb2
/dev/sdb3                24.0G     23.5G    465.6M  98% /media/usb

So in this example, I'd expect 
internal flash, /media/hdd2, /media/mmc and /media/usb2
to be listed, not just internal and usb2
```

USB to SATA drive adapters should be taken into account as acceptable devices

**Comment by jbleyel** [comment]
You need a partion with hardlink support.

**Comment by wedebe** [comment]
Ah ok, thanks.
