### ISSUE TITLE
[Plugin Manager] Installing multiple plugins results in oversized prompt

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3092]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-10-24

**Describe the bug / Actual behaviour:**
When a large number of plugins are selected for installation, the prompt becomes huge.

**Expected behaviour:**
Change prompt to
1 plugin selected: Do you want to download the selected plugin?
more than 1:  Do you want to download the selected plugins?

**Has this issue started to happen just recently?**
Since the Plugin Manager was refactored.

**To reproduce:**
1. See above

**Screenshots**
![20231025113743](https://github.com/openatv/enigma2/assets/9741693/28772f9e-5df9-4305-80e0-293093dee972)

**Image/Box Model (please complete the following information):**
 - Version: N/A
 - BoxModel: N/A

**Additional context**
N/A

**Comment by jbleyel** [comment]
This is not really a bug because nobody select normally more than 10 packages.

**Comment by jbleyel** [comment]
fixed with 
https://github.com/openatv/enigma2/pull/3138
