### ISSUE TITLE
[Service Scan] `Cancel` should change to `Close` on completion of scan

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3095]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-10-24

**Describe the bug / Actual behaviour:**
The red button label never changes from `Cancel` to `Close`

**Expected behaviour:**
The red button label should change from `Cancel` to `Close`
OR
results of scan should be discarded after user confirmation when red button is pressed.

**Has this issue started to happen just recently?**
No

**To reproduce:**
1. Do a manual channel scan
2. Observe non-changing text of reb button when scan finishes

**Screenshots**
![screenshot_20231027131859](https://github.com/openatv/enigma2/assets/9741693/7c34a0a0-f959-4bdd-82a1-69f96ccfa2a3)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: Mut@nt HD51

**Additional context**
N/A

**Comment by jbleyel** [comment]
Please try this.

[ServiceScan.py.zip](https://github.com/openatv/enigma2/files/13625413/ServiceScan.py.zip)

**Comment by wedebe** [comment]
> Please try this.
> 
> [ServiceScan.py.zip](https://github.com/openatv/enigma2/files/13625413/ServiceScan.py.zip)

`Cancel` changes to `Close` when scan has completed 👍🏻

I've just noticed that `🟩 OK` shows while scanning, but does nothing when pressed.
Perhaps on completion, this should change to `🟩 Re-scan`? Should I log a separate improvement request?

**Comment by jbleyel** [comment]
Rescan is not possible i this version.
This needs a full refactor.

And i think rescan is not needed.

**Comment by jbleyel** [comment]
There is a problem.
If you need to press OK / green if the scan is complete to run post actions.
These actions will not called if you press red.

**Comment by jbleyel** [comment]
I think this needs more attention and probably a complete refactor.

**Comment by wedebe** [comment]
> Rescan is not possible i this version. This needs a full refactor.
> 
> And i think rescan is not needed.

Re-scan is certainly a superfluous feature, just thought it might be worth asking about 👍🏻

**Comment by wedebe** [comment]
> There is a problem. If you need to press OK / green if the scan is complete to run post actions. These actions will not called if you press red.

Oh, I think Green button shows during scan but disappears after. I'll need to try this again later.

**Comment by wedebe** [comment]
> I think this needs more attention and probably a complete refactor.

Service Scan does what it needs to do from what I can see so wouldn't justify any sort of priority regarding refactor work :)

**Comment by wedebe** [comment]
Thanks!

**Comment by GhostofGeeeee** [comment]
There was no commit!?

**Comment by wedebe** [comment]
A similar issue has appeared recently. The green button now says `Select`, which makes no sense.

![screenshot](https://github.com/user-attachments/assets/f39c3cdd-213e-471b-bd16-600cacff6f45)

**Comment by jbleyel** [comment]
> There was no commit!?

https://github.com/openatv/enigma2/commit/7c4f8d6a500f0fa246786264889e294ffe2185e3

**Comment by jbleyel** [comment]
> A similar issue has appeared recently. The green button now says `Select`, which makes no sense.
> 
> ![screenshot](https://private-user-images.githubusercontent.com/9741693/380438023-f39c3cdd-213e-471b-bd16-600cacff6f45.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzE1NDYsIm5iZiI6MTcyOTk3MTI0NiwicGF0aCI6Ii85NzQxNjkzLzM4MDQzODAyMy1mMzljM2NkZC0yMTNlLTQ3MWItYmQxNi02MDBjYWNmZjZmNDUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMTkzNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE1MDVkOTA3MzU4NThmMDEwMjVhNTVmNTMxYTdiNzhhMjczYTdmMDcxOGI0ZThjODljMjIzM2FlMzAwZTc3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0LNH8_-gzCFb-ydAvI6ItihOKkG8kUpP6rnI-Kvms9s)

Please press Green and check what happens in comparison to Red.

**Comment by IanSav** [comment]
The reason that GREEN is now select is that if you press RED (Close) then the code will try to restore the previous service.  If you select GREEN (Select) the the currently highlighted service will be selected as the new current service.

**Comment by wedebe** [comment]
Ah I see. "Select" infers that a set of actions will apply (such as _Move_, _Rename_, _Delete_, etc.)

Perhaps `Zap to channel` or `Zap to selected` would be clearer to the user.

**Comment by IanSav** [comment]
The problem is that something like "Zap To Selected" is too long for the button size and will probably be to long in many of the translations.
