### ISSUE TITLE
[Timers] Can't re-enable a disabled timer

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3107]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
2023-10-31

**Describe the bug / Actual behaviour:**
Once a `record timer` has been disableed, there's no way to re-enable it.

**Expected behaviour:**
The yellow `Disable` button should change to `Enable`

**Has this issue started to happen just recently?**
No

**To reproduce:**
1. Set a timer from the EPG
2. Go to the Timer List
3. Use the yellow button to disable the newly-created timer
4. Scroll to the disabled tiimer
5. There is no yellow button to `Enable`
6. Going into timer details, there's still no way to enable

**Screenshots**
![20231101093857](https://github.com/openatv/enigma2/assets/9741693/73c708f5-c642-4605-bff0-835c403da252)
![20231101094112](https://github.com/openatv/enigma2/assets/9741693/931828ce-7d55-4c2f-a2ec-1a2d601d71fd)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: N/A

**Additional context**
The only workaround is to re-create the timer

**Comment by GhostofGeeeee** [comment]
Let me add: You can open the timer log and there is no entry disabled!

**Comment by wedebe** [comment]
> Let me add: You can open the timer log and there is no entry disabled!

Good point, in fact timer logging seems to be missing for several actions.

```
	<timer begin="1698878100" end="1698881700" marginBefore="0" eventBegin="1698878100" eventEnd="1698881700" marginAfter="0" hasEndTime="True" serviceref="1:0:16:83F:3EA:2174:EEEE0000:0:0:0:" eit="44548" cridSeries="crid://rtenl.ie/ebsp123921" cridEpisode="crid://rtenl.ie/ebsp12099950" cridRecommendation="[]" repeated="0" rename_repeat="1" name="The Way We Were" description="A trawl through the archives to reveal how the Irish styled themselves as the 20th century progressed into the 21st. (S)" tags="AutoTimer" afterevent="auto" disabled="1" justplay="0" always_zap="1" descramble="1" record_ecm="0" isAutoTimer="1">
		<log code="500" time="1698220460">[AutoTimer] Try to add new timer based on AutoTimer The Way We Were.</log>
		<log code="509" time="1698220460">[AutoTimer] Timer start on: Wed Nov  1 22:35:00 2023</log>
	</timer>
```

**Comment by GhostofGeeeee** [comment]
I think this(#3120 ) is the fix but do we need to deactivate a running record too?
I think then we need something like a restart(, maybe for failed records too), i'm out.
