### ISSUE TITLE
Create ua.kmap

### ISSUE THREAD

**Issue by free777cat** [openatv/enigma2#3115]
Hello!
Could you please create a ua.kmap
Ukrainian

**Comment by IanSav** [comment]
Can we please have some more information.  What are you trying to achieve?

I assume that you have a keyboard connected to your receiver, is that correct?  If so, what does the keyboard look like?

**Comment by free777cat** [comment]
Hi !
looks like this
![keyboard](https://github.com/openatv/enigma2/assets/149939500/2269e982-5af9-4cd0-ae80-8efd24c49d09)


Ukrainian keyboard layout

**Comment by IanSav** [comment]
That layout looks like a normal QWERTY layout.  What problems are you currently experiencing?

**Comment by free777cat** [comment]
It is impossible to use Ukrainian letters.
The youtube plugin does not enter requests in Ukrainian.

**Comment by free777cat** [comment]
For example, the German keyboard layout de.kmap

**Comment by free777cat** [comment]
![Зняток екрана як 2023-11-06 16-52-16](https://github.com/openatv/enigma2/assets/149939500/8a40fe41-4195-48a7-9c7b-f0008d19546a)
maybe pieterg can explain how to create a kmap

**Comment by IanSav** [comment]
If you can provide me with the kmap file I can add it to the system.  (I happen to be updating the International files at the moment.)

**Comment by jbleyel** [comment]
please try this:

[ua.kmap.zip](https://github.com/openatv/enigma2/files/13269701/ua.kmap.zip)

**Comment by jbleyel** [comment]
Extract the zip and copy the kmap file to the box.
Open a console and goto the folder of the kmap file on your box.
Then run this in console on your box.

`loadkmap < ua.kmap`

**Comment by IanSav** [comment]
@free777cat, have you been able to test the new kmap that @jbleyel offered?  I need your confirmation of success before I will add this to my new code.

**Comment by free777cat** [comment]
Hi!
I'm not at home now.
I think I can do it on Sunday.

**Comment by IanSav** [comment]
There is no rush.

I jus wanted you to know that I won't add the kmap until we know that it is working.

**Comment by IanSav** [comment]
@free777cat, the code to support new kmap files is now installed into Enigma2.  When you approve the kmap file it can now be quickly added.

**Comment by IanSav** [comment]
@free777cat, we haven't heard from you for a while.  Have you tested the kmap file?  Do you want it added or do you want to close this issue?

**Comment by jbleyel** [comment]
It seams we can close this.

**Comment by free777cat** [comment]
it doesn't work!!!

**Comment by IanSav** [comment]
What does "it doesn't work!!!" mean?  What happened?  What didn't happen?  Are there any logs that demonstrate the issue?

You need to give us something with which to work?

**Comment by free777cat** [comment]
I did everything as described.
You can connect a USB keyboard and check.
With ua.kmap, after pressing "S" we should get "і" (in Ukrainian).
"L" (lat)>>> "Д" (ukr).
But it doesn't work for me.

**Comment by IanSav** [comment]
As we told you, we don't have access to Ukrainian equipment.  It is not possible for us to test.  Is the keyboard configured to output the Ukrainian characters?  The keyboard looks like it also does English, perhaps you are not outputting the Ukrainian characters?

What do the logs show for character input when you use the keyboard?

**Comment by free777cat** [comment]
Switched the interface to a German USB keyboard.
Enabled the virtual keyboard in the "YouTube" plugin. I put the German language in the virtual keyboard.
My keyboard allows you to type all the special characters of the German language.


Selecting the usual German keyboard in the interface (no usb) does not reproduce the specific characters of the German language.

**Comment by free777cat** [comment]
You could do the same with the Ukrainian language.

**Comment by free777cat** [comment]
Didn't find anything in the LOGs.

**Comment by jbleyel** [comment]
For log and debug you cannot use YouTube Plugin.
You need to use something else.
You can use a timer and edit the description or name.
Then you should see the key codes in debug log.

**Comment by free777cat** [comment]
Try to reproduce my simple experiment.
1. Use the German USB keyboard layout. 
2. Use the German no-USB keyboard layout. 
3. Use the Ukrainian (suggested) keyboard layout.

You will see everything yourself.

**Comment by jbleyel** [comment]
This is my log if i press A..F

18:04:32.3858 [eRCDeviceInputDev] KEY_A Break
18:04:32.3859 [eRCDeviceInputDev] KEY_A Break
18:04:32.3862 [InfoBarGenerics] Key 'KEY_A' (30) Make.
18:04:32.4738 [eRCDeviceInputDev] KEY_A Make
18:04:32.4739 [eRCDeviceInputDev] KEY_A Make
18:04:32.4742 [InfoBarGenerics] Key 'KEY_A' (30) Break.
18:04:33.0658 [eRCDeviceInputDev] KEY_B Break
18:04:33.0659 [eRCDeviceInputDev] KEY_B Break
18:04:33.0662 [InfoBarGenerics] Key 'KEY_B' (48) Make.
18:04:33.1537 [eRCDeviceInputDev] KEY_B Make
18:04:33.1538 [eRCDeviceInputDev] KEY_B Make
18:04:33.1542 [InfoBarGenerics] Key 'KEY_B' (48) Break.
18:04:33.6258 [eRCDeviceInputDev] KEY_C Break
18:04:33.6258 [eRCDeviceInputDev] KEY_C Break
18:04:33.6262 [InfoBarGenerics] Key 'KEY_C' (46) Make.
18:04:33.6978 [eRCDeviceInputDev] KEY_C Make
18:04:33.6979 [eRCDeviceInputDev] KEY_C Make
18:04:33.6982 [InfoBarGenerics] Key 'KEY_C' (46) Break.
18:04:34.2499 [eRCDeviceInputDev] KEY_D Break
18:04:34.2500 [eRCDeviceInputDev] KEY_D Break
18:04:34.2504 [InfoBarGenerics] Key 'KEY_D' (32) Make.
18:04:34.3217 [eRCDeviceInputDev] KEY_D Make
18:04:34.3218 [eRCDeviceInputDev] KEY_D Make
18:04:34.3221 [InfoBarGenerics] Key 'KEY_D' (32) Break.
18:04:34.7858 [eRCDeviceInputDev] KEY_E Break
18:04:34.7859 [eRCDeviceInputDev] KEY_E Break
18:04:34.7862 [InfoBarGenerics] Key 'KEY_E' (18) Make.
18:04:34.8499 [eRCDeviceInputDev] KEY_E Make
18:04:34.8500 [eRCDeviceInputDev] KEY_E Make
18:04:34.8504 [InfoBarGenerics] Key 'KEY_E' (18) Break.
18:04:35.2737 [eRCDeviceInputDev] KEY_F Break
18:04:35.2738 [eRCDeviceInputDev] KEY_F Break
18:04:35.2742 [InfoBarGenerics] Key 'KEY_F' (33) Make.
18:04:35.3217 [eRCDeviceInputDev] KEY_F Make
18:04:35.3218 [eRCDeviceInputDev] KEY_F Make
18:04:35.3221 [InfoBarGenerics] Key 'KEY_F' (33) Break.
