### ISSUE TITLE
Timer margin challenge #5

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3130]
Today a simple bug similar than #2800.
I start a instantRecord -> Add recording (enter recording end time).
The timer should not have a marginAfter.

**Comment by wedebe** [comment]
I don't use timer margins so hadn't seen this before now.

In this instance...
`Margin before` set to 4 mins
`Margin after` set to 6 mins
![20231120235123](https://github.com/openatv/enigma2/assets/9741693/076ab673-9dfb-413d-b007-7003c891104b)

The timer's settings incorrectly show the ignored `Margin after`.
![20231121002503](https://github.com/openatv/enigma2/assets/9741693/5d5215d9-5b55-4cca-b8e5-b89b4998be66)

Instant recording with an end time manually specified as 23:53 correctly stops and is marked done at 23:53, _however_, the timer list entry shows an incorrect duration with `before` and `after` as part of the string.

![20231120235553](https://github.com/openatv/enigma2/assets/9741693/5c276e16-66bd-4e7d-b80b-e8386a07b4fb)

I can't extract the timer xml 'cos it's not flushed to disk and the entry disappears on restart.

Separate issue - Timer log contains very little in the way of useful detail:
![20231120235505](https://github.com/openatv/enigma2/assets/9741693/dda5e94e-e3c2-4e61-8760-f3955c8d1c7e)

**Comment by GhostofGeeeee** [comment]
@wedebe If you like, you can test it!
[InfoBarGenerics.py](https://github.com/openatv/enigma2/blob/7774c47e9b8c0ca1b7c7404ddc30d2afa79f0d03/lib/python/Screens/InfoBarGenerics.py)
And report [there](https://github.com/openatv/enigma2/pull/3143).

**Comment by IanSav** [comment]
Who decided that padding should be removed from Instantrecord timers?

This was specifically added for a reason.  Please make any corrections you wanted without breaking or removing features used by others.

**Comment by GhostofGeeeee** [comment]
It was a reported bug for some cases.
What case is used by others and now broken?

**Comment by IanSav** [comment]
My Instant recordings no longer have their end padding and I am now having recordings cut off before the end of the show.

**Comment by GhostofGeeeee** [comment]
A Instant recording current event still have a margin after!
Again, what case?

**Comment by IanSav** [comment]
I am busy on other projects but I noticed code changes with code something like padding = 0 and noticed that the end of one of my recordings was missing.

Given that there are no useful commit notes on these changes I have no idea what was done or why.

**Comment by jbleyel** [comment]
Sorry .. I was too fast with the merge and we need to revert this or make this differently.

We should add a new setting to define Instant record End Margin.

**Comment by GhostofGeeeee** [comment]
I'm sorry but I can't reproduce!

**Comment by IanSav** [comment]
Perhaps, if the changes are properly documented, the changes may not need to be reverted.

Making people jump hoops to find what a commit is for and what it does is unacceptable.

**Comment by GhostofGeeeee** [comment]
I know my documentation is bad but we have some bugs!

**Comment by IanSav** [comment]
Document the bugs and what the code changes did to fix the bug.  Did your testing ensure that no other changes were triggered?

From what I could find, trying to work out what this was all about, there was some sort of display issue for InstantRecordings.

**Comment by GhostofGeeeee** [comment]
This wasn't my interpreation(display issue) it was more!

**Comment by IanSav** [comment]
As I posted above, I can't understand the problem and the solution isn't explained either.

Now that I have finished the new PluginBrowser I can update my machine to the latest code and I will re-test recordings to see if I can see what went wrong for my broken recording.

I still ask that the changes made be documented to explain what was done and why.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/pull/3145

**Comment by GhostofGeeeee** [comment]
"When talking about timers the use some descriptive sample times to demonstrate the problem you are trying to report."
Please let me know the problem now!
I'm not good a documentation but we have some bugs.
I like to do drafts only... better then no fix.

@jbleyel 
with #3145 
I think Instand recordings (indefinitely, manualduration) will now have a marginAfter and this is not serious.

**Comment by IanSav** [comment]
@jbleyel just told me that my broken recording *may* be because of errors in the code.  I will wait until there is a new master build with all these issues addressed and I will test my recordings again.
