### ISSUE TITLE
Hotkey settings regression

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3132]
Since few releases, hotkey settings has no effect for function keys, example for F1:

config.misc.ButtonSetup.f1=Module/Screens.ServiceInfo/ServiceInfo
--> doesn't work anymore

config.misc.ButtonSetup.red=Module/Screens.PluginBrowser/PluginBrowser
--> is OK

 - Version: 7.3
 - BoxModel: SF8008

**Comment by GhostofGeeeee** [comment]
It's the Screen(Module/Screens.ServiceInfo/ServiceInfo) which doesn't exist anymore.

**Comment by jeepcook** [comment]
Why has it been removed? And how to have a shortcut to menu, information, service?

Thanks

**Comment by jbleyel** [comment]
I’ll fix that soon.

**Comment by jeepcook** [comment]
Thank you.
