### ISSUE TITLE
image does not support parseParameter  '3*f' ?!!

### ISSUE THREAD

**Issue by fairbird** [openatv/enigma2#3133]
Before I think month ago no problem with this skin
https://github.com/Taapat/skin-SimpleGray
But after latest commits there is some crash error

> 18:13:29.7009 Traceback (most recent call last):
18:13:29.7011   File "/usr/lib/enigma2/python/StartEnigma.py", line 850, in <module>
18:13:29.7026     InitSkins()
18:13:29.7029   File "/usr/lib/enigma2/python/skin.py", line 112, in InitSkins
18:13:29.7034   File "/usr/lib/enigma2/python/skin.py", line 163, in loadSkin
18:13:29.7037   File "/usr/lib/enigma2/python/skin.py", line 1225, in loadSingleSkinData
18:13:29.7040   File "/usr/lib/enigma2/python/skin.py", line 163, in loadSkin
18:13:29.7042   File "/usr/lib/enigma2/python/skin.py", line 1280, in loadSingleSkinData
18:13:29.7045   File "/usr/lib/enigma2/python/skin.py", line 560, in parseParameter
18:13:29.7048 ValueError: invalid literal for int() with base 10: '3*f'

https://github.com/Taapat/skin-SimpleGray/blob/master/usr/share/enigma2/SimpleGray-HD/skin_screens.xml#L26-L29

**Comment by jbleyel** [comment]
```
# Convert a parameter string into a value based on string triggers.  The type
# and value returned is based on the trigger.
#
# Usage:  *string   : The paramater is a string with the "*" is removed (Type: String).
#         #aarrggbb : The parameter is a HEX color string (Type: Integer).
#         0xABCD    : The parameter is a HEX integer (Type: Integer).
#         5.3       : The parameter is a floating point number (Type: Float).
#         red       : The parameter is a named color (Type: Integer).
#         font;zize : The parameter is a font name with a font size (Type: List[Font, Size]).
#         123       : The parameter is an integer (Type: Integer).


```

**Comment by jbleyel** [comment]
Please note !!!

openATV provides a complete different scaling functionality.

**Comment by fairbird** [comment]
Thank you !! clear !!

**Comment by fairbird** [comment]
From my side on my source I have solved by this commit !!
https://github.com/fairbird/enigma2-dreambox/commit/18c3787dbd4b06c80eb08a45f5e5d3f7b5a675c1
