### ISSUE TITLE
[FileCommander] bookmarks_order

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3134]
I want to add a folder "1,2" but it's always last on bookmarks.

**Comment by GhostofGeeeee** [comment]
I could push a draft but I have questions:
[config.misc.pluginlist = ConfigSubsection()](https://github.com/openatv/enigma2/blob/55013b264b372cc27d2afc978b71e3027eeda8e9/lib/python/Screens/ChoiceBox.py#L10)
Is this ConfigSubsection and this "[reorderConfig](https://github.com/openatv/enigma2/blob/55013b264b372cc27d2afc978b71e3027eeda8e9/lib/python/Screens/ChoiceBox.py#L32C1-L32C37)" code used anywhere outside?

**Comment by jbleyel** [comment]
config.misc.pluginlist.fc_bookmarks_order is the setting for sort the bookmarks

**Comment by jbleyel** [comment]
You can change the bookmarks inside of the ChoiceBox check this -> 

https://github.com/openatv/enigma2/blob/master/lib/python/Screens/ChoiceBox.py#L129-L130

**Comment by GhostofGeeeee** [comment]
Sorry this is not completed.
config.misc.pluginlist.fc_bookmarks_order uses comma as seperator and can't handle my folder("1,2").

**Comment by jbleyel** [comment]
Misunderstood. Sorry.
Folders with , are not supported. Yet

**Comment by GhostofGeeeee** [comment]
No problem.
Reopen?

**Comment by jbleyel** [comment]
This is a Problem in ChoiceBox and not FileCommander.
Refactor of ChoiceBox is already planned.

**Comment by GhostofGeeeee** [comment]
I think both uses
```
split(",")
",".join()
```

**Comment by GhostofGeeeee** [comment]
I have a workaround but i like to reopen! You can rename if you like!
