### ISSUE TITLE
Missing /dev/shm on 7.3

### ISSUE THREAD

**Issue by defkev** [openatv/enigma2#3140]
I am not even sure wherever this is the proper repository to report this since it is more an OA/OpenATV problem rather than an OE/enigma2 problem so bear with me.

I just upgraded a VU+ Solo 4K from 6.4 to 7.3 and noticed that one of my Python scripts using `multiprocessing` doesn't work any more because `/dev/shm` required for semaphore/IPC is missing:

```
root@vusolo4k:~# ls -al /dev/shm
ls: /dev/shm: No such file or directory
```

This can be reproduced using the introductory example from Python's documentation at https://docs.python.org/3/library/multiprocessing.html#introduction

Prerequisite: `opkg install python3-multiprocessing`

```python
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))
```

Which yields a:
```python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    with Pool(5) as p:
         ^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/context.py", line 119, in Pool
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 191, in __init__
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 346, in _setup_queues
  File "/usr/lib/python3.11/multiprocessing/context.py", line 113, in SimpleQueue
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 341, in __init__
  File "/usr/lib/python3.11/multiprocessing/context.py", line 68, in Lock
  File "/usr/lib/python3.11/multiprocessing/synchronize.py", line 162, in __init__
  File "/usr/lib/python3.11/multiprocessing/synchronize.py", line 57, in __init__
FileNotFoundError: [Errno 2] No such file or directory
```

Same with `ThreadPool()`

For whats it worth i recalled seeing the exact same error on Amazon ECS before they added shared memory support to docker so the workaround is the same:

```bash
mkdir /tmp/shm
ln -s /tmp/shm /dev/shm
```

or persistent in `/etc/rc.local`:
```
...
if [ ! -e /dev/shm ]; then 
    mkdir -p /tmp/shm
    ln -s /tmp/shm /dev/shm
fi
...
```

The question is why was shared memory support dropped in 7.3?

**Comment by jbleyel** [comment]
First and important question.

Do you wanna use multiprocessing in a separate python process or inside of a Plugin?

**Comment by defkev** [comment]
For the time being its a seperate process but may(be) become a plugin at some point.

**Comment by jbleyel** [comment]
> For the time being its a seperate process but may(be) become a plugin at some point.

If you start a new python process separated from enigma you may not have a problem.
If you use multiprocessing inside of the enigma main thread you may get into trouble.

Are you sure that `/dev/shm` exists in ATV 6.4?

**Comment by defkev** [comment]
I am currently restoring 6.4 to see for myself but both Pool and ThreadPool were definitely working out of the box.

**Comment by atvcaptain** [comment]
/dev/shm  some addons create this too openhbbtv
but we can add this to the mdev script, its include with next update

**Comment by defkev** [comment]
6.4 doesn't havea /dev/shm either which leaves me to believe this is a Python 3 problem.

**Comment by atvcaptain** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/0797dfe9ff5207d902efa7f9ddda43ae60e7a5bd

**Comment by defkev** [comment]
For whats it worth, creating SharedMemory on the main thread yields a similar error if /dev/shm is missing:

```python
from multiprocessing import shared_memory
shared_memory.SharedMemory(create = True, size = 10000000*4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/multiprocessing/shared_memory.py", line 93, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/psm_ba90b897'
```

I'll wait for the update to hit upstream.
Cheers
