### ISSUE TITLE
Fix for greyed out channels of other packages when using Stream Relay

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3149]
Can we have this added to ATV please

https://github.com/OpenViX/enigma2/commit/639030fedf984cbdf0c32d7d8c70c034d7feba6f

Also I believe there are other fixes too for obtaining the transponder data in the infobar, it would be nice to have these as well so ATV doesnt fall behind other images in this area.

**Comment by jbleyel** [comment]
To be honest. This Vix solution is crap.
This needs to be implemented correctly and not like this hack.

**Comment by ian10951** [comment]
Regardless it seriously needs sorting and previously its been stated on here that the degree of dificulty in doing so was immense, and therefore very unlikely to ever be implemented, so because of that why not use their solution if it works and has the desired effect, at least until a better solution can be added.

**Comment by jbleyel** [comment]
I have already started a solution for the greyed out services weeks ago and I have a notably performance issue if you have a lot of recordings that's why the vix solution is not good.
The new sream relay whitelist feature is also not supported.

**Comment by ian10951** [comment]
Thats marvelous news.

**Comment by jbleyel** [comment]
We will find a proper solution but this will take some time to implement this correctly.
I don't like half solutions or hacks if there is a better way.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/50d884f1c7e1a2f1fcbd9afe688102c01933d3d8
