### ISSUE TITLE
@jbleyel

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3150]
I've tested your fix for the greyed out channels and it works a treat so many thanks for that.

I now believe they also have a fix for showing the signal strength too when using stream relay, so would it be possible to have this as well ?
It seems they're spending a lot of time and effort in this area which has to be good for everyone.

**Comment by jbleyel** [comment]
They have only fixed PliExtraInfo Converter.
This is not helpful if you use other Converter and plugins and and and.

**Comment by ian10951** [comment]
Oh OK

It was just that Evo told me last night on Telegram that Huevos has now fixed it, I do not know if its been added to their Git yet or not.

**Comment by jbleyel** [comment]
We will fix this but this takes some time to do it proper.
