### ISSUE TITLE
Further testing has shown a crash with the fix for greyed out channels

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3151]
If you open the channel list then press the menu button it will crash, so you cannot move anything or for that matter even add or remove the stream relay setting.

Crash log attached.
[20231125-110804-enigma2-crash.log](https://github.com/openatv/enigma2/files/13463979/20231125-110804-enigma2-crash.log)

**Comment by jbleyel** [comment]
This crash is not possible if you use the latest code.
You have mixing version on you box.

**Comment by ian10951** [comment]
Ok no problem

I will now wait for the official update. I only wanted to test what you have done, I did suspect that it might be because I'd only added the one py file but thought id better report it just in case.

**Comment by jbleyel** [comment]
You can use the development feed.

`
wget -O - -q https://feeds2.mynonpublic.com/devel-feed | bash
`
