### ISSUE TITLE
Display subservices from channel selection screen

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3163]
The idea could be to add a way to display the subservices for the selected service on the Channel selection screen.

Example: program a hotkey, for example Playlist and when pressed the subservices for this channel are displayed.

**Comment by jbleyel** [comment]
The subservice info is only available for the active channel.
There is no way to get this for any other channel in Channel selection.

**Comment by jeepcook** [comment]
Hello. 
Ok I understand and if we select by ok a channel containing subservices and the system configured to stay in the channel list selection on first ok, is there a way to implement this or will this be confusing for users?

**Comment by jeepcook** [comment]
@GhostofGeeeee 

It's an idea. No problem to create a virtual bouquet if necessary even if I don't use this list, but I'm not sure to really understand you proposal in fact ;-(

**Comment by GhostofGeeeee** [comment]
I can easily add some code but i need a test ref that hold more then one ref. Find no examples.

**Comment by jeepcook** [comment]
examples from my groupedservices file

`#EURONEWS
5002:0:1:16D1:924C:D596:DDDD0000:0:0:0:http%3a//localhost%3a8088/https%3a//www.youtube.com/watch?v=NiRIbKwAejk:EURONEWS FR IPTV
4097:0:1:1CC9:CD9:4DBB:DDDD0000:0:0:0:https%3a//i.mjh.nz/SamsungTVPlus/FRBA3300065KW.m3u8:EURONEWS STORIES

#CLUBBING TV
4097:0:1:7412:B8B2:D596:DDDD0000:0:0:0:https%3a//i.mjh.nz/SamsungTVPlus/FRBB1900001FA.m3u8:CLUBBING TV FR
4097:0:1:FEBB:BC7B:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/600ad8f86e1eba00081da3ce/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:CLUBBING TV FR
4097:0:1:EACC:7979:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/5f984784ccb4de0007dfad74/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:CLUBBING TV DE
4097:0:1:23A:8972:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/600ad4ad6537680007be2ea6/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:CLUBBING TV ES
4097:0:1:67EA:405E:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/60802de3fd2d70000763bb83/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:CLUBBING TV IT

#MTV CLASSIC
4097:0:1:EEC4:5F2F:D596:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/635bfb89b5cd9b0007ca9d63/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:MTV CLASSIC UK
4097:0:1:50BA:A17E:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/6329ceeac55af500083077e3/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:MTV CLASSIC DK
4097:0:1:FEFE:B708:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/6329cd8809e10300073236c2/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:MTV CLASSIC NO
4097:0:1:7BE:DCAA:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/6329cf28ef924b00078a9dc1/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:MTV CLASSIC SW
4097:0:1:C18D:B43F:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/6076cd1df8576d0007c82193/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:VH1 CLASSICS ES
4097:0:1:70B:E4A1:4617:DDDD0000:0:0:0:http%3a//stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/62e8cc10ca869f00078efca8/master.m3u8?deviceType=unknown&deviceMake=unknown&deviceModel=unknown&deviceVersion=unknown&appVersion=unknown&deviceDNT=unknown&deviceId=unknown:VH1 MUSIC LEGENDS IT

`

**Comment by GhostofGeeeee** [comment]
Maybe if we create userbouquet.subservices.tv:
#SERVICE 1:0:19:6C:C:85:C00000:0:0:0::Sky Sport HD
#SERVICE 1:0:19:81:6:85:C00000:0:0:0::Sky Sport HD
#SERVICE 1:0:19:72:D:85:C00000:0:0:0::Sky Sport HD

eServiceReference('1:7:1:0:0:0:0:0:0:0:(name == "Sky Sport HD") FROM BOUQUET "userbouquet.subservices.tv" ORDER BY name'))
Thats what I need!

**Comment by jeepcook** [comment]
So with the same ServiceName ? And no iptv url?

**Comment by GhostofGeeeee** [comment]
@jeepcook
You can try [these 2 files](https://github.com/GhostofGeeeee/enigma2/commit/4a4c2d7fed73ed5a4eb560f40386e9ee1926003b) if you like.

**Comment by jeepcook** [comment]
Hello,

Cool, now I have a subservices list on Reception lists and it contains the subservices for the active channel. Great ;-)
![4097_0_1_EEC4_5F2F_D596_DDDD0000_0_0_0_20240225092556](https://github.com/openatv/enigma2/assets/17811804/bcd7b7d6-e0f8-4ee6-b217-be5ad3e3d100)

Questions:
- The sort order is an alphanumeric order, not the one configured in the groupedservices file.
-  Is it possible to have a shortcut to access directly to this subservices list with a simple choosen button?

Thanks for the job.

**Comment by GhostofGeeeee** [comment]
- Make # in front of this [line ](https://github.com/GhostofGeeeee/enigma2/blob/4a4c2d7fed73ed5a4eb560f40386e9ee1926003b/lib/python/Screens/ChannelSelection.py#L1502) to disable sort.
- 
  - Extract the folder Subservices to /user/lib/enigma2/python/Plugins/Extensions/ https://github.com/GhostofGeeeee/Subservices/archive/refs/heads/main.zip 
  - restart
  - Add a hotkey(Subservices)
  - plugin.py line 9 ( # CS.saveRoot()), you can try to remove the # in front, this this will change your channellist/bouquet if you close and reopen.

**Comment by GhostofGeeeee** [comment]
Yes that's the difference if you remove the #.
You prefer with # that's good, me too. (then restore it)

**Comment by jeepcook** [comment]
I don't understand why I have the same comportment with or without the # in front of CS.saveRoot())

**Comment by GhostofGeeeee** [comment]
If you select one, the list changed always, if you only open and close, it do only without #.

**Comment by jeepcook** [comment]
My manipulations:
1- I'm on a list and I click on the hotkey configured to display subservices
2- The list appears and I select one subservice, click on it, preview is displayed (mini TV), click again and I have the subservice in full screen.
3- If I do a up or dow key the subservices list appears, not the initial list
4- If I select a channel number, the zap is done into my initial list not in the subservices one. So that point is good. 

It seems I am in my initial list but no way to display it when I have selected a subservices. I have to click blue button, select my list, search and select the channel.

**Comment by GhostofGeeeee** [comment]
I have no miniTV in use, but I can confirm that number zap will not work.
In my case there is absolut no action. Same on Current Transponder List. If you look at these list, there are no numbers, but I'm not sure, that numbers should not work in these lists.
I'm not sure how to reproduce your 4-.

Thank you for your feedback...

**Comment by jeepcook** [comment]
I'm not really using service number, just when I click 1 or 2, the zap goes to the 1st or second channel of my list, that's all.

**Comment by GhostofGeeeee** [comment]
Numbers not work but sms works. 2abc 3def...

**Comment by GhostofGeeeee** [comment]
Do you understand now the difference between with and without # on line 10?
> the zap goes to the 1st or second channel of my list

Random behavior?

If you think it's an issue, I need more(steps and screenshots) to reproduce it.

**Comment by jeepcook** [comment]
> Do you understand now the difference between with and without # on line 10?

Not really, I have the same result with or without the #

> > the zap goes to the 1st or second channel of my list
> 
> Random behavior?
> 
No key 1 for channel 1, key 2 for channel 2 etc etc....

**Comment by jeepcook** [comment]
Hello @GhostofGeeeee,

Some messages from this discussion have been deleted. Have this implementation a future ?

Thanks

**Comment by GhostofGeeeee** [comment]
These comments are now useless.
I'm ready and did a PullRequest on 6th March, now jbleyel is the lord over my code.

**Comment by GhostofGeeeee** [comment]
Now, we have a commit([[Subservices] Refactor and rework subservices access](https://github.com/openatv/enigma2/commit/99294564b4fc8194d8abdc9d140783f8790bc98a)) on master branch.

**Comment by jeepcook** [comment]
Great, thanks, I will migrate to 7.4 devel and test this
