### ISSUE TITLE
Subservices: Allow to choose to display progress bar

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3164]
Currently, for subservices we only have the start and end time for subservices programs. It would be more readable to have the possibility to display progress bar instead or in addiction to the current display.

**Comment by IanSav** [comment]
This control is a text only display so a progress bar graphical display is not available here.  I added the progress percentage, as a number, as well as the start and end time and found that the event name is truncated too much.  I should also note that the percentage does not update as this is a static screen.

![SubService](https://github.com/openatv/enigma2/assets/6904736/4daf0787-f100-4ac3-914d-33b1a694dd53)

I am concerned that removing the start and end times may make others unhappy.  Do you still want this change made?

**Comment by jeepcook** [comment]
Hello

Yes the epg is too much truncated. I can't decide for everyone. A graphical solution would have been better.

**Comment by IanSav** [comment]
@jbleyel and I have decided to provide an integer version of the progress.  That will give a bit more space back to the event name.  This screen may be replaced with a more comprehensive display at some later date.

**Comment by jeepcook** [comment]
Ok thanks. Note that my subservices screen is different with Metrix HD Skin. See screenshot.
![5002_0_1_113_1FDB_D596_DDDD0000_0_0_0_20240130100536](https://github.com/openatv/enigma2/assets/17811804/8fb09498-bb2c-4291-9b48-8f6e2bb1af4a)

**Comment by IanSav** [comment]
That is still a ChoiceBox based screen so the changes you see will be comparable.

**Comment by GhostofGeeeee** [comment]
This screen gets replaced by [[Subservices] Refactor and rework subservices access](https://github.com/openatv/enigma2/commit/99294564b4fc8194d8abdc9d140783f8790bc98a).
