### ISSUE TITLE
Default skin message box too small

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3166]
All info is not displayed because of the size. Screenshot attached.
![1_0_1_149C_7DB_2_11A0000_0_0_0_20231202172421](https://github.com/openatv/enigma2/assets/11910714/7f35cf48-123b-459b-8255-29f7713967fc)

**Comment by wedebe** [comment]
![20231203000339](https://github.com/openatv/enigma2/assets/9741693/776fe88f-3f83-4d08-83ae-4f2c57c5acfa)

I see this on image openATV 7.3 2023-12-01

**Comment by ian10951** [comment]
To be fair its not that the box is too small really its that the yes/no are postioned too high, they should be further down the box nearer the bottom.

**Comment by jbleyel** [comment]
The 2 images are from different skins.

**Comment by jbleyel** [comment]
Hi @ian10951 , what skin are you using?

**Comment by ian10951** [comment]
Its my own based on a very old Pli HD skin. Ive not got tound to coding in the message box yet so it reverts to the default ATV backup skin for that screen.

Hence me saying that there was an issue with the default skin in the thread title.

**Comment by jbleyel** [comment]
This is the default skin.

<img width="625" alt="Bildschirmfoto 2023-12-04 um 19 44 07" src="https://github.com/openatv/enigma2/assets/964927/09ce3a90-bbd4-4e08-be79-15ee33e9efce">

The problem is in your skin.
