### ISSUE TITLE
There appears to be a problem with Messagebox

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3178]
If a plugin uses self.session.open(MessageBox, it will crash the image. ( at least I believe it to be this )

This is only with the devlevel image, 7.3 is fine.

For example 

self.session.open(MessageBox,_("Download of " + name + " has started" ), MessageBox.TYPE_INFO, timeout = 5)

crashes and gives this error in the crash log

AttributeError: 'MessageBox' object has no attribute 'active_components'

Full crashlog attached.
[20231203-083124-enigma2-crash.log](https://github.com/openatv/enigma2/files/13578003/20231203-083124-enigma2-crash.log)

**Comment by jbleyel** [comment]
This is already fixed. Please update your box.
