### ISSUE TITLE
PowerTimers not running in OpenATV 7.3

### ISSUE THREAD

**Issue by pizzelnet** [openatv/enigma2#3181]
Since I upgrade my boxes to version 7.3 the power timers I have for the box to wake up and shut down do not run, both in an Octagon SF8008 and in an Octagon SF4008. I've been using OpenATV for ages and I had never had this problem before. Version 7.2 is the latest working for me.

I just somethings get it work disabling the timer and enabling it again but, as I need the timers to run daily, they won't run the next day.

Image/Box Model:
 - Version: 7.3
 - BoxModel: SF8008 + SF4008

**Comment by jbleyel** [comment]
Please provide more info about the affected PowerTimer. Screenshot or pm_timers.xml

**Comment by jbleyel** [comment]
No answer. No details.
