### ISSUE TITLE
Online translation feature 

### ISSUE THREAD

**Issue by Insprion80** [openatv/enigma2#3182]
Gents,

Is it possible to add online Google translate for txt and or dvb subtitles file attached to Sat channel, pure2 7.3 team already provide it in their image but make it limited for some devices. It is very important feature and will unlock a lot of contents to user who want to watch TV programs, News... etc from different languages resources.

Regards.

**Comment by Najar1991** [comment]
You mean Novaler right

**Comment by grumpynho** [comment]
Google to open-source enigma2? 🤮🤮

**Comment by jbleyel** [comment]
Novaler Is using a specific server for translation and this server is overloaded very fast and can’t be used for all.
All other online translation services are also not for free if you send that much requests.
We can try to implement this but you as user may need to pay for the api access.

**Comment by Insprion80** [comment]
> Novaler Is using a specific server for translation and this server is overloaded very fast and can’t be used for all. All other online translation services are also not for free if you send that much requests. We can try to implement this but you as user may need to pay for the api access.

Already they offer it for free and performing in acceptable way, however, I think it make sense to get paid features, especially the current update mainly improve what we already have long time ago.

**Comment by the-guard** [comment]
Teletext subtitle translation might be easy to implement, but the DVB subtitle is more challenging while the original DVB subtitle data is bitmap data which is needed to build the image, enhance it, and perform OCR before you can translate it all on-fly

This type of feature will never be free of charge as technically it needs dedicated hardware resources to handle the huge requests, each subtitle showing is a separate request for OCR and Translation, so a single movie might have 1000+ requests, imagine that 1000 persons using the service on the same time means 1 million requests in 2hrs.

Most of AI/Machine Translation services are paid, and if you find an open source to operate it to be able to handle these huge requests will be definitely costly.

**Comment by jbleyel** [comment]
There is no feasible way for non text based srt.

And the translation of text based srt is also not that simple because of the api calls.
You can’t get the translated string via api live because there will be a delay.
So you need the text a few seconds before it needs to display.

But the biggest challenge will be the api itself.
There’s no free of charge api available to handle this amount of requests.

**Comment by the-guard** [comment]
> There is no feasible way for non text based srt.
> 
> And the translation of text based srt is also not that simple because of the api calls. You can’t get the translated string via api live because there will be a delay. So you need the text a few seconds before it needs to display.
> 
> But the biggest challenge will be the api itself. There’s no free of charge api available to handle this amount of requests.

Definitely, there is a way for a none-text subtitle (DVB Subtitle) as someone releases a beta version based on your image here 
https://www.opena.tv/openatv-7-4-py3-12-2-openssl-3-2-1-a/65805-openatv-7-4-beta1-powered-translation-language.html

I have tested it myself, and I don't feel a delay in the translation response,  although there are some lags in UI when translation is enabled, but it should be a minor enhancement to handle multithreading tasks.

**Comment by jbleyel** [comment]
Where is the code for this?
I will never ever support closed source components in enigma.

**Comment by the-guard** [comment]
> Where is the code for this? I will never ever support closed source components in enigma.

I don't know who is the developer of this component as there is no information yet nor official website for this customisation yet, but my point here it is seems to be possible, and definitely it would be great if it is added to the official repository even if end users needs to pay for API access.

**Comment by jbleyel** [comment]
A non free api is not a problem if the users willing to pay.
The forum post also mentioned that it is only for VU+ and this makes no sense to me.

**Comment by Insprion80** [comment]
> A non free api is not a problem if the users willing to pay. The forum post also mentioned that it is only for VU+ and this makes no sense to me.

Actually it will not be for free or for VU+, it is still under evaluation as per their posts, our discussion based on the reason why we do not have this option even if we are ready to pay for it?

**Comment by jbleyel** [comment]
Duplicate #3332
