### ISSUE TITLE
[Channel List Menu] Suggestion: Replace `Show Transponder Information` with `Service Information`

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3183]
**Is your feature request related to a problem? Please describe.**
Currently the context menu opened from the highlighted service in the channel list shows an option
`Show Transponder Information`,
but no option to Show service information.
![Channel Info 20231207235249](https://github.com/openatv/enigma2/assets/9741693/544286bf-0286-4d49-a185-4e23ae1bfdf8)
Interestingly, this page does not show any button action to show channel info.
![Channel Info 20231207235305](https://github.com/openatv/enigma2/assets/9741693/d80a6d9d-23a0-417b-8987-12a1358a5a35)

From the main menu, however, `Information` > `Service` shows a `Service Information: Service & PID` page,
including [Blue button] action of 🟦 Transponder.
![Channel Info 20231207235213](https://github.com/openatv/enigma2/assets/9741693/21c8e5a7-9bf5-4892-b3d6-534458c3c8f8)

**Describe the solution you'd like**
Being able to view channel information from the channel list context menu.
![20231207235249-](https://github.com/openatv/enigma2/assets/9741693/3549de56-27c6-4e1d-b122-f68bf44cdf6d)
![Channel Info 20231207235213](https://github.com/openatv/enigma2/assets/9741693/7b812f71-6507-4b73-aaab-9375a67c359c)

**Describe alternatives you've considered**
Having to exit the channel list, open the main menu, then `Information` followed by `Service`.

**Additional context**
Transponder info would be easily accessible from the Blue button on the service info page.
Menu item should only be shown when `Settings mode` is set to `Intermediate` or `Expert`

**Comment by jbleyel** [comment]
You missed one important point.
The full serviceinfo is only available for the current active service.
That’s why there are no extra color buttons.

**Comment by wedebe** [comment]
Even better, looks good to me, thanks!
