### ISSUE TITLE
Last flash date it changes itself

### ISSUE THREAD

**Issue by pololoko111** [openatv/enigma2#3188]
If I switch between images in vu+multiboot, for example OpenBH then OpenVix Then OpenAtv 7.3 then OpenAtv 7.4 (Devel).
I noticed that the last flash date has changed. Although I didn't flash anything.

![flashdate](https://github.com/openatv/enigma2/assets/37630415/326611f8-ec3b-4c64-9b89-f713788f9532)

![flash2](https://github.com/openatv/enigma2/assets/37630415/bb7654e9-bd2b-48e8-9d11-2a1c6a71d8f7)

**Comment by jbleyel** [comment]
Please call this in a python console on this box:

```
from os import stat
from time import localtime
localtime(stat("/boot").st_ctime)
localtime(stat("/bin").st_ctime)
localtime(stat("/lib").st_ctime)
localtime(stat("/home").st_ctime)

```

and then post the output here.

**Comment by jbleyel** [comment]
Why closed?
It's not fixed.

**Comment by pololoko111** [comment]
I closed it because the problem is gone for now.
I installed fresh images on a new pendrive and the problem disappears.
This time I did not install OpenPli image. Maybe OpenPli was causing this problem.
For now it shows the dates correctly.
