### ISSUE TITLE
Question about broken/incompatible plugins in feeds

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3191]
**Is your feature request related to a problem? Please describe.**
There are a bunch of plugins which I guess mainly fell out of compatibility when openATV was shifted to Python3 (eg. those with `print "Blah"` statements). Other plugins are far more broken, an example being *service editor*
https://feeds2.mynonpublic.com/7.3/hd51/3rdparty/enigma2-plugin-systemplugins-serviceeditor_20090417-alpha_all.ipk

**Describe the solution you'd like**
Automated testing which would install each plugin from feeds and check there's at least no launch errors (as the Plugin Browser shows on load, see screenshot below).
But this would be a _lot_ of work to implement.

So, perhaps a [Broken Plugin] GitHub issue type so people can easily log troublesome plugins, with
the ability to exclude/remove them at the point of feeds generation.

**Describe alternatives you've considered**
Manually editing code for plugins I like the intent of.

![broken plugin-20231212024407](https://github.com/openatv/enigma2/assets/9741693/5edb790d-d7c8-49f5-b6b6-e900abad2a92)

**Additional context**
My question is - is it possible to exclude certain plugins from certain versions of certain images?
(eg. exclude _Service Editor_ from _openATV_ version _7.3 and above_)

Obviously, eevery plugin at some point would have worked with a certain image and version.

Including version compatibility within individual plugins is a disaster and something I'd advise againt, as Mozilla has experienced over the years with developers having to manually increment numbers or see their plugins automatically and wrongly dropped off marketplace/addon store.

**Comment by jbleyel** [comment]
This plugin will be no longer on the feed in a few days.
