### ISSUE TITLE
2K skins (2560*1440) ?!!

### ISSUE THREAD

**Issue by fairbird** [openatv/enigma2#3196]
Why OpenATV does not support 2k skins with resolution (2560*1440). Such as this skin ([hdsuisse.2k)](https://www.linuxsat-support.com/thread/156147-oe2-6-skin-hdsuisse-2k-for-dreambox-one-two/)

Skin work fine on DM920 with DreamOS images. But does not on Open source images.

Look on screenshot I have created channelselection screen test ...
This screenshot from skins tools All directions are clear

![Selection_001](https://github.com/openatv/enigma2/assets/1761779/d00a239e-21d8-4686-ac02-1d14a2e115d4)

This screenshot from device (It went to the right and the bottom side disappeared with 5 channels)

![2](https://github.com/openatv/enigma2/assets/1761779/d258df54-01b6-45cd-b8a4-0319265d3278)

And here is more screenshots to prove diffrence between FHD and WQHD plugins screen 

This is FHD skins (1920*1080) Look the screen of plugin (Normally display)

![11](https://github.com/openatv/enigma2/assets/1761779/f7f959ce-bb0f-41f3-8c5b-ee8750382aef)

![12](https://github.com/openatv/enigma2/assets/1761779/8dafc32b-7f03-45e3-b823-03c0067843dd)

This is WQHD skins (2560*1440) Look the screen of plugin (Small display) because skin of plugin is FHD not WQHD !!

![21](https://github.com/openatv/enigma2/assets/1761779/0d91bbfc-d059-4adc-b1fa-7915a2f5e157)

![22](https://github.com/openatv/enigma2/assets/1761779/d937e611-ec51-429d-8ebd-243138503f46)

**Comment by jbleyel** [comment]
First of all:
* What skin you are using on your DM920 with ATV and have you the permission of the author to run this skin?

**Comment by fairbird** [comment]
Already I have add name and link for skin in first post (hdsuisse.2k) ...
About the permission (No I did not asked him because I just test it. I don't use it constantly)

Or You can test this simple skin I have created include only (Infobar + channelSelection)
[2kskintest.zip](https://github.com/openatv/enigma2/files/13692759/2kskintest.zip)

**Comment by Papi2000-new** [comment]
your screenshots are in 1920x1080. That means, your framebuffer is running only in FHD (1920x1080). Why do you want to compress a high resolution graphics into FHD?
Bigger problem with that skin is, that it uses SVG-graphics, what is not (yet) impemented in oATV (maybe OE-A at all). So there is nosense, and even no way. to run that skin in an oATV image in next times. There are afaik no plans to implement SVG and compressed screens in skins.

**Comment by fairbird** [comment]
No my friend ... It is not about SVG graphics .. Please try my simple skin I have created for test only (you can download it from my previous replay) Skin depend on Label only without any graphics and look here on DreamOS image how works fine with all directions appear....

![1](https://github.com/openatv/enigma2/assets/1761779/439d142d-5601-4cc6-b81e-2a0d4d1c78e5)
.
![2](https://github.com/openatv/enigma2/assets/1761779/75148ac0-5533-477c-bfe0-1ceb86d8411b)
..
But on OpenATV or my images does not ..
.
![2](https://github.com/openatv/enigma2/assets/1761779/52699101-b300-4629-bcfc-205eb250327f)

**Comment by jbleyel** [comment]
Please provide the debug log.

**Comment by fairbird** [comment]
In attach 2 e2 debuge (Gemini dreamOS and OpenATV) !!
[E2_debuge.zip](https://github.com/openatv/enigma2/files/13693774/E2_debuge.zip)

**Comment by jbleyel** [comment]
That's a driver issue.

_22:51:18.2033 [fb] SetMode failed: wanted: 2560x1440x32, got 1920x1080x32_

The driver is closed source.

**Comment by IanSav** [comment]
> Already I have add name and link for skin in first post (hdsuisse.2k) ...
> About the permission (No I did not asked him because I just test it. I don't use it constantly)

> Or You can test this simple skin I have created include only (Infobar + channelSelection)
> [2kskintest.zip](https://github.com/openatv/enigma2/files/13693314/2kskintest.zip)

Your example would be significantly easier to review if it only contained valid openATV skin syntax.  Further, you would make a better case if you corrected all the skin errors being reported in the logs.

As @jbleyel reported, the resolution you are requesting is not valid on the hardware.

@jbleyel and I are investigating if we can determine the maximum frame buffer size so that we can adjust the integrated scaling engine to down scale skins to the maximum resolution offered by the hardware.

**Comment by jbleyel** [comment]
I will close this because this needs a lot of changes without guarantee.
DM is gone and no other vendor supports higher resolution then FHD.
