### ISSUE TITLE
Old EPG

### ISSUE THREAD

**Issue by SoSoSoStupid** [openatv/enigma2#3199]
Transponder have different EPG than EPG Cache(for upcoming events).
I think, if times are changed, EPG Cache get new data but if only EventInfo changed, there is no update.
(Maybe EPGCacheNowNext is different but not good and sufficient)

EPGRefresh isn't a part of openatv --> EPGRefresh isn't a part of solution! (I think a normal no enigma2 receiver can handle this without such a feature like EPGRefresh or TechniSat SFI)
I have old EPG data and I have to remove all to get new?

Please improve it, this is not feature request!
Thanks a lot!

**Comment by jbleyel** [comment]
You can't get EPG data if the transponder is not active.
You have to go to the channel or transponder of the channel.

We have no plan to create another plugin because EPG refresh already exists.
If you need more features in EPG refresh then make a feature request here -> https://github.com/oe-alliance/enigma2-plugins/issues

**Comment by jbleyel** [comment]
Is this problem only on ZDF?
Is this problem new or old?

**Comment by jbleyel** [comment]
Please monitor this issue also on other channels.

**Comment by jbleyel** [comment]
I have never notice such issue on ÖRR HD channels.
The upcoming events in 2 weeks have less info but after EPG Refresh the info will be updated.
I'm using EPG refresh once a day.

**Comment by jbleyel** [comment]
<img width="1059" alt="Bildschirmfoto 2023-12-20 um 21 25 29" src="https://github.com/openatv/enigma2/assets/964927/46a1ccf2-1aad-4cad-be36-e948edfab746">

**Comment by jbleyel** [comment]
<img width="1161" alt="Bildschirmfoto 2023-12-20 um 21 33 09" src="https://github.com/openatv/enigma2/assets/964927/9b066a66-49fb-4d80-9660-fa54e535f94a">


I can't make a screenshot tomorrow.

**Comment by jbleyel** [comment]
19:00 / Cache deleted -> same data.

**Comment by jbleyel** [comment]
<img width="1159" alt="Bildschirmfoto 2023-12-21 um 21 17 51" src="https://github.com/openatv/enigma2/assets/964927/fb5a81d9-f034-415b-8437-3f618275706c">

**Comment by jbleyel** [comment]
I have not deleted the cache!!!!

**Comment by jbleyel** [comment]
> 
> I found a [TODO](https://github.com/openatv/enigma2/commit/4c44dff624be13ae4bf54b80e1389bb9c9def596)!

That's for IceTV.

**Comment by jbleyel** [comment]
Please note .. I have not zapped to the affected channel and I have not cleared the cache but I got the new data in cache.
So what's the problem?
