### ISSUE TITLE
Subsupport plugin Menu titles and Event Text AutoScrool Issue in MyMetrixHD - OPEN ATV 7.3

### ISSUE THREAD

**Issue by ruipisco** [openatv/enigma2#3201]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
[[After the changes on 7 December of 2023 on the MyMetrixHd have deformated the menu titles on the PlugIn Subssuport, that makes the title letters are cut in half and text autoscrool on event does not work anymore]]

**Expected behaviour:**
[[All the titles in the plugins show the text without half cuted by the options padding, and text vertical autoscroll moves text from down to up.]]

**Has this issue started to happen just recently?**
Yes it worked before the update of OPEN ATV 7.3 on the 8 of December of 2023. 

**To reproduce:**
Steps to reproduce the behavior of the subssuport title issue:
1. Have to have installed SubSuport 1.5.7 plugin.
2. After the instalation Press the Green button and select any option of the subsupport plugin
3. See result/error on any title of the menus, that teh optins padding is over the title.

**Screenshots**
<img width="854" alt="Subsupport Menus Titles deformated " src="https://github.com/openatv/enigma2/assets/32041748/eb20cafa-9bd6-472b-b76f-60c6eb9b1b81">

**To reproduce:**
Steps to reproduce the behavior of the Vertical AutoScrool in channel selection issue:
1. Click Up Arrow to go to the channel selection list.
2. Select an channel that has an event that haves an big text that cannot be displayed in the blue event box above the mini Tv.
3. See result/error on the text cannot deslocate from down to up to let the user read the event details.

**Screenshots**
<img width="854" alt="Event Text AutoScrool" src="https://github.com/openatv/enigma2/assets/32041748/84ca2ad0-0704-4f65-9465-64e2095eb12c">

**Image/Box Model (please complete the following information):**
 - Version: OpenAtv 7.3
 - BoxModel: VuPlus Zero 4K

**Additional context**
@jbleyel Can you please help?

**Comment by jbleyel** [comment]
SubsSupportSettings is not in MetrixHD.

What you prefer for the EPG in Channelsection?

**Comment by ruipisco** [comment]
OK But when the skin template as change it add afected the SubSupport plugin Titles. 
for the EPG in the channel sele ction is uit possible to make the event text scroll work again?

**Comment by jbleyel** [comment]
Channelselection:

OLD:

		
```
		<widget source="ServiceEvent" render="MetrixHDRunningText" position="785,375" size="420,223" options="movetype=none,startdelay=600,steptime=60,direction=top,startpoint=0,wrap=1,always=0,repeat=2,oneshot=1" font="epg_info; 19" zPosition="2" backgroundColor="layer-b-background" foregroundColor="layer-b-accent1" transparent="0" halign="left" valign="top">
			<convert type="EventName">FullDescription</convert>
		</widget>		

```
NEW:


```
		<widget source="ServiceEvent" render="MetrixHDRunningText" position="685,428" size="520,173" options="movetype=none,startdelay=600,steptime=60,direction=top,startpoint=0,wrap=1,always=0,repeat=2,oneshot=1" font="epg_info; 19" zPosition="2" backgroundColor="layer-b-background" foregroundColor="layer-b-accent1" transparent="0" halign="left" valign="top">
			<convert type="EventName">FullDescription</convert>
		</widget>

```


As you can see, there is only a position change.

**Comment by jbleyel** [comment]
The Title of SubsSupportSettings should have no effect.

**Comment by GhostofGeeeee** [comment]
SubSupport looks like https://github.com/openatv/enigma2/issues/3166.

**Comment by jbleyel** [comment]
No. That's MessageBox.

**Comment by ruipisco** [comment]
if it goes to the old position does it work? can you test it ?
Probably when you changed the size the text scroll will need to be adjusted to know the new widget size values, so if the text of the event is bigger then it will need to scroll up?

**Comment by jbleyel** [comment]
looks like a bug in MetrixHDRunningText

**Comment by jbleyel** [comment]
config.plugins.MyMetrixLiteOther.showChannelListRunningtext = ConfigYesNo(default=False)

**Comment by ruipisco** [comment]
@jbleyel ok that's possible to solve and make it work again? For subbsupport where can we post the issues since there will be needed to update opensubtitles new api service?

**Comment by jbleyel** [comment]
You can't create an issue here -> https://github.com/oe-mirrors/subssupport because this is a fork.
This repro here is wrong.
We may should think about to create a new repro for subssupport.

**Comment by ruipisco** [comment]
for now it's working but i think it will not be working in 2024 since the opensubtitles.org API will be deprecated and the new rest API of opensubtitles.com will be the new one. Tanks!

**Comment by jbleyel** [comment]
New Subsupport Repro -> https://github.com/oe-alliance/subssupport

Note !!!
This is not yet on the feed because this needs to tested first.
