### ISSUE TITLE
Pressing the Green button on a Stream Relay channel causes the image to crash

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3233]
It used to offer either the plugins menu or Subservices menu if on a channel that offers them eg Sky Sports Top Event

But now since the recent changes to the choicebox it crashes.

Crashlog attached.
[20240113-135420-enigma2-crash.log](https://github.com/openatv/enigma2/files/13928196/20240113-135420-enigma2-crash.log)

The crash only occurs on channels that carry Subservices.

**Comment by IanSav** [comment]
Can you provide a screen capture of the ChoiceBox screen immediately prior to the crash.  The error appears to be an invalid ChoiceBox list item.  Unfortunately I can't replicate the issue as I don't have access to the appropriate services.

Your logs also seem to show a lot of other errors.  Do you know what is causing them?

**Comment by ian10951** [comment]
I cannot provide a screenshot prior to the crash because the screen just freezes right after the green button is pressed and the box becomes unresponsive to the remote. it doesnt crash right away, the screen remains frozen for about 2 seconds then it crashes but after its recovered there is still no response from the box when using the remote. Enigma2 has to be killed from telnet.

The other errors you menyion are all related to the freeze that comes just before the crash.

**Comment by IanSav** [comment]
Are you able to modify some code and try it on your box?

**Comment by ian10951** [comment]
I'm out at work right now, and posting from my phone. Soz.

**Comment by IanSav** [comment]
On lines 213-214 change:

		for index, item in enumerate(self.parent["list"].getList()):
			self.choiceList.append((index, item[0][0]))

to:

		for index, item in enumerate(self.parent["list"].getList()):
			print(f"[ChoiceBox] DEBUG: Summary item {index}: '{item}'.")
			self.choiceList.append((index, item[0][0]))

Try and reproduce the crash and provide the full log file for that run.

**Comment by ian10951** [comment]
Sorry I'm at work now.

Cant you just revert it ? It worked perfectly before the changes were made.

**Comment by IanSav** [comment]
No, there are too many fixes and improvements to justify a reversion without first investigating the issue.  If you can't help debug the issue we will need to wait to see if @jbleyel can reproduce the issue and help address the problem.  (I am in Australia and don't have access to the same types of services.)

**Comment by IanSav** [comment]
I have added the test code to the master branch to see if we can get more information on the issue.

**Comment by IanSav** [comment]
@jbleyel has explained the issue.  He is testing the fix now and will commit it shortly.

**Comment by ian10951** [comment]
Nice one as I wouldnt be able to help till much later tonight or even tomorrow.
