### ISSUE TITLE
Allow quit movie player with exit not working

### ISSUE THREAD

**Issue by steveuk23** [openatv/enigma2#3248]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
In the playback setting i have enabled "allow quit movie player with exit" option enabled  but it doesn't work on any of the selected options like ,with popup,behave like stop button etc  .]]

**Expected behaviour:**
When that option is enabled the movie should stop playing when i press the exit button on the remote.]]

**Has this issue started to happen just recently?**
Yes it's only a recent bug ?

**To reproduce:**
1. Go to...Menu
2. Press ...Setup
3. Press ...Playback, Recording & Timeshift
4. See result/error

**Screenshots**
![image](https://github.com/openatv/enigma2/assets/18037536/4bebadf8-1249-46f4-b6e8-3542e40de290)

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: SF8008

**Additional context**

**Comment by jbleyel** [comment]
Where exactly do you start the playback?
MovieSelection, EMC, etc ....

**Comment by jbleyel** [comment]
I have changed the setting like on your screenshot.
Then start playback then press exit and I get the same result like stop button.

Then I have changed the setting to "Without pop up" and the exit button stops playback as expected.

**Comment by steveuk23** [comment]
> Where exactly do you start the playback? MovieSelection, EMC, etc ....

Hi thanks for the reply.
I've just realised I've got the EMC plugin installed and setup.
So I'm starting it playing through there.

**Comment by jbleyel** [comment]
EMC is not using this setting.

**Comment by steveuk23** [comment]
> EMC is not using this setting.

Thanks yeah my fault forgot i installed that.
I've uninstalled it now and it is working,
However i have the option enabled to return me to the movie list when stopped playing but it returns me back to the live tv.
Doe's this happen for you ?
Cheers

**Comment by jbleyel** [comment]
The default stop action will return to live TV.
That’s the normal behavior.
