### ISSUE TITLE
This messageBox is wrong

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3251]
Steps:
- Have a running record
- Open for example a Setup Screen or RecordTimerOverview etc.
- Press PowerButton

Then we get a messageBox:
- Recording(s) are in progress or coming up in few seconds!
Entering standby, after recording the box will shutdown.

This bug is not young!

**Comment by jbleyel** [comment]
You are mixing 2 different things.
The running recording check has nothing todo with the ALLOW_SUSPEND.

**Comment by GhostofGeeeee** [comment]
I know you dislike my hint's.

But if this Bug is 3 month ignored, maybe help is needed.

**Comment by GhostofGeeeee** [comment]
This was the first step...
Please reopen for the second. It's not fixed at all.
