### ISSUE TITLE
SubServices: Allow streamlink protocol

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3253]
Hello,

Streamlinkwrapper (enigma2-plugin-extensions-streamlinkwrapper), allow to use directly streamlink protocol instead of using internal webserver. It works great as service but doesn't work as subservice.

Example with France TV Info:
4097:0:1:8C90:CE56:D596:DDDD0000:0:0:0:streamlink%3a//https%3a//www.youtube.com/watch?v=Z-Nwo-ypKtM:FRANCEINFO IPTV YT  --> is working as a service but not as subservice:

#FRANCEINFO
5002:0:1:8C90:CE56:D596:DDDD0000:0:0:0:http%3a//localhost%3a8088/https%3a//www.france.tv/franceinfo/direct.html:FRANCEINFO IPTV FTV
4097:0:1:8C90:CE56:D596:DDDD0000:0:0:0:streamlink%3a//https%3a//www.youtube.com/watch?v=Z-Nwo-ypKtM:FRANCEINFO IPTV YT
--> black screen on the second subservice

I think that only http(s) protocol is allowed.

The advantage of streamlinkwrapper is it is very faster than internal webserver (htp://localhost:8088)

OpenATV 7.3 / 7.4
SF8008

Thanks

**Comment by jbleyel** [comment]
Please try this:
[InfoBarGenerics.py.zip](https://github.com/openatv/enigma2/files/14392398/InfoBarGenerics.py.zip)

**Comment by jeepcook** [comment]
Hello,

Tried but I have a crash, see the log.
The subservices is :
5002:0:1:8C90:CE56:D596:DDDD0000:0:0:0:streamlink%3a//https%3a//www.youtube.com/watch?v=Z-Nwo-ypKtM:FRANCEINFO IPTV YT
[20240224-111853-enigma2-crash.log](https://github.com/openatv/enigma2/files/14392488/20240224-111853-enigma2-crash.log)

**Comment by jbleyel** [comment]
Please try again.
[InfoBarGenerics.py.zip](https://github.com/openatv/enigma2/files/14392504/InfoBarGenerics.py.zip)

**Comment by jeepcook** [comment]
I confirm now it's working.
Thanks

**Comment by jeepcook** [comment]
Thanks for this commit.

**Comment by jeepcook** [comment]
Hi @jbleyel

About this commit, blue button function has been changed, now simple press display "choose an extension"
![5002_0_1_BB6F_F1E_D596_DDDD0000_0_0_0_20240225085548](https://github.com/openatv/enigma2/assets/17811804/676b402b-6264-4efd-9f2c-20c54eac8af0)

instead of this one now enabled by long press blue button .
![5002_0_1_BB6F_F1E_D596_DDDD0000_0_0_0_20240225090538](https://github.com/openatv/enigma2/assets/17811804/2c0491f0-e42f-4410-94c8-2b6a11e9c466)

**Comment by jbleyel** [comment]
That’s nearly impossible.
You may have changed the blue button settings.

**Comment by jeepcook** [comment]
No changes for these buttons:
config.misc.ButtonSetup.f1=Module/Screens.Information/ServiceInformation
config.misc.ButtonSetup.red=Module/Screens.PluginBrowser/PluginBrowser
![4097_0_1_4E83_9FE_4DBB_DDDD0000_0_0_0_20240225093556](https://github.com/openatv/enigma2/assets/17811804/d5388391-fcde-4348-9ff9-78eb175c205a)
![4097_0_1_4E83_9FE_4DBB_DDDD0000_0_0_0_20240225093539](https://github.com/openatv/enigma2/assets/17811804/16267bd9-63e6-412b-9af4-336ce7919123)

**Comment by jbleyel** [comment]
config.workaround.blueswitch = ConfigSelection(default=0, choices=[
		(0, _("QuickMenu/Extensions")),
		(1, _("Extensions/QuickMenu"))
	])

**Comment by jbleyel** [comment]
<item level="0" text="BLUE switch: BLUE/BLUE long" description="Switch BLUE short (QuickMenu) with BLUE long (Extension Menu).">config.workaround.blueswitch</item>

**Comment by jeepcook** [comment]
Have I to do something with these lines?

**Comment by jbleyel** [comment]
> Have I to do something with these lines?

No .. the is the setting to define the blue button action.

**Comment by jeepcook** [comment]
Hello @jbleyel ,

Is see this ticket is closed. Has this update been commited to 7.4 branch? With the blue button fix?

Thanks

**Comment by jbleyel** [comment]
What you mean?
There is no blue button fix because there is no issue with that. Or do I miss something?

**Comment by jeepcook** [comment]
This update was to implement streamlink:// in subservices. And with your InfoBarGenerics.py patch we can now select a subservice  using streamlink. But during the test I tell you that this has an effect on the blue button which lost its native action.

See previous messages.

**Comment by jbleyel** [comment]
This commit cannot have any effect on the blue button-> https://github.com/openatv/enigma2/commit/9bd598c0d8de837c893b448aaec61d478b2422c0

There must be something else.

**Comment by jbleyel** [comment]
Please check this setting:

config.workaround.blueswitch

**Comment by jeepcook** [comment]
I don't have config.workaround.blueswitch in my /etc/enigma2/settings file.
Note if I don't use the InfoBarGenerics.py patch the blue button is ok.

**Comment by jbleyel** [comment]
I cannot reproduce this on my box.
I have the new InfoBarGenerics.py and no config.workaround.blueswitch in my settings.

Blue short -> QuickMenu
Blue Long -> Extensions Menu

**Comment by jbleyel** [comment]
Do you have 7.4 + Devel feed or only 7.4?

**Comment by jeepcook** [comment]
Only 7.4.

But I think that Blue short has to point to this screen, or not?
![image](https://github.com/openatv/enigma2/assets/17811804/ca24100b-896f-4fdd-9cfe-d41847f292c2)

**Comment by jeepcook** [comment]
But I have this one
![image](https://github.com/openatv/enigma2/assets/17811804/bd13360a-a3ba-4af0-b1eb-03df6ab8d06c)

**Comment by GhostofGeeeee** [comment]
> Note if I don't use the InfoBarGenerics.py patch the blue button is ok.

You can compare these files!
[with patch](https://github.com/openatv/enigma2/blob/dafc44ecd6df40ad5b2a6feb8bf016169465b6df/lib/python/Screens/InfoBarGenerics.py)
[without patch](https://github.com/openatv/enigma2/blob/9bd598c0d8de837c893b448aaec61d478b2422c0/lib/python/Screens/InfoBarGenerics.py)

> I don't have config.workaround.blueswitch in my /etc/enigma2/settings file.

then:
short -> QuickMenu
long  -> ExtensionMenu

else:
short -> ExtensionMenu
long  -> QuickMenu

**Comment by jbleyel** [comment]
Please wait a few days. There is a big update for 7.4 coming soon.

**Comment by jbleyel** [comment]
Or you use this:
[InfoBarGenerics.py.zip](https://github.com/openatv/enigma2/files/14791468/InfoBarGenerics.py.zip)

**Comment by jeepcook** [comment]
> Or you use this: [InfoBarGenerics.py.zip](https://github.com/openatv/enigma2/files/14791468/InfoBarGenerics.py.zip)

ok and will this version be commited ?

**Comment by jbleyel** [comment]
No. That’s a special version only for you because you have not the devel feed.

**Comment by jeepcook** [comment]
So I have to patch InfoBarGenerics.py until 7.5 is out?

**Comment by jbleyel** [comment]
> So I have to patch InfoBarGenerics.py until 7.5 is out?

No 7.4 release.

**Comment by jeepcook** [comment]
> > So I have to patch InfoBarGenerics.py until 7.5 is out?
> 
> No 7.4 release.

Oh yes I forgot 7.4 is in beta version.
Thanks

**Comment by jeepcook** [comment]
> Please wait a few days. There is a big update for 7.4 coming soon.

Update for streamlink is now commited on 7.4 Beta version. Thanks. 
But it wasn't a big 7.4 update.

**Comment by jbleyel** [comment]
The big update is not finished. That’s why we have splited.
