### ISSUE TITLE
No EPG in the InfoBar after last update

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3277]
As the title says, EPG is available from the single EPG but the InfoBar remains empty as does the display.

VU+ Solo4K

At first I thought it might be my skin but its the same in the Matrix Skin too.

I suspected this

https://github.com/openatv/enigma2/pull/3273

So Ive just reverted the EventName.py and EventTime.py and voila, I have EPG back again in my InfoBar and box display.

**Comment by jbleyel** [comment]
You may not have the latest updates.
Please provide the debug log if you have the latest version.

**Comment by ian10951** [comment]
Just checked and no further updates available.
![1_0_1_15B1_7D7_2_11A0000_0_0_0_20240313171246](https://github.com/openatv/enigma2/assets/11910714/87b64a7d-3a7a-4a4e-8926-b0825e5b5fec)

**Comment by ian10951** [comment]
Debug log as requested 

[20240313-172802-enigma2-debug.log](https://github.com/openatv/enigma2/files/14591459/20240313-172802-enigma2-debug.log)

**Comment by jbleyel** [comment]
Please extract the py from zip and put this file to "/usr/lib/enigma2/python"
[skin.py.zip](https://github.com/openatv/enigma2/files/14591619/skin.py.zip)

Then restart GUI and then provide the latest debug log.

**Comment by ian10951** [comment]
Log using the modified skin.py

[20240313-175403-enigma2-debug.log](https://github.com/openatv/enigma2/files/14591733/20240313-175403-enigma2-debug.log)

**Comment by jbleyel** [comment]
Do you have this file?

/usr/lib/enigma2/python/Components/Converter/EventInfo.pyc
or this
/usr/lib/enigma2/python/Components/Converter/EventInfo.py

**Comment by ian10951** [comment]
No

EventInfo.py does not exist, so if its supposed to then its not been added during the last update.

**Comment by jbleyel** [comment]
It's a new file added here -> 

https://github.com/openatv/enigma2/commit/810ab76925a70b5859423f42be9abc979716e38e

**Comment by ian10951** [comment]
Well Ive added it and things are even worse now.

Still no EPG and also no other infpormation at all in the InfoBar now

**Comment by jbleyel** [comment]
cat /var/lib/opkg/info/enigma2.list | grep Converter/E

**Comment by ian10951** [comment]
/usr/lib/enigma2/python/Components/Converter/EGAnalogic.pyc     0100644
/usr/lib/enigma2/python/Components/Converter/ExtendedServiceInfo.pyc    0100644
/usr/lib/enigma2/python/Components/Converter/EventTime.pyc      0100644
/usr/lib/enigma2/python/Components/Converter/EtAnalogClock.pyc  0100644
/usr/lib/enigma2/python/Components/Converter/EventName.pyc      0100644
/usr/lib/enigma2/python/Components/Converter/ExtremeInfo.pyc    0100644

**Comment by jbleyel** [comment]
cat /var/lib/opkg/info/enigma2.control

**Comment by ian10951** [comment]
root@vusolo4k:~# cat /var/lib/opkg/info/enigma2.control
Package: enigma2
Version: 7.4-devel+git33193+be5371a-r0
Description: Enigma2 is an experimental, but useful framebuffer-based frontend f
or DVB functions
 Enigma2 is an experimental, but useful framebuffer-based frontend for DVB
 functions.
Section: base
Priority: optional
Maintainer: OE-Alliance
License: GPL-2.0-only
Architecture: vusolo4k
OE: enigma2
Homepage: https:\\www.opena.tv
Depends: alsa-conf, enigma2-fonts, enigma2-plugin-font-wqy-microhei, enigma2-plu
gin-skins-metrix-atv, ethtool, font-valis-enigma, glibc-gconv-cp1250, glibc-gcon
v-iso8859-15, gstreamer1.0 (>= 1.22.8), hotplug-e2-helper, libavahi-client3 (>=
0.8), libavahi-common3 (>= 0.8), libc6 (>= 2.37), libcrypt2 (>= 4.4.33), libcryp
to3 (>= 3.1.0), libcurl4 (>= 8.0.1), libdreamdvd0 (>= 1.1+git220+375e791), libdv
bsi++1 (>= 0.3.9+git130+f3c40ea), libfreetype6 (>= 2.11.0), libfribidi0 (>= 1.0.
12), libgcc1 (>= 12.2.0), libgif7 (>= 5.2.1), libglib-2.0-0 (>= 2.74.6), libgomp
1 (>= 12.2.0), libgstpbutils-1.0-0 (>= 1.22.8), libjpeg62 (>= 2.1.5.1), libpng16
-16 (>= 1.6.39), libpython3.11-1.0 (>= 3.11.2), libsigc-2.0-0 (>= 2.10.7), libss
l3 (>= 3.1.0), libstdc++6 (>= 12.2.0), libtuxtxt0 (>= 2.0+git82+1402795), libtux
txt32bpp0 (>= 2.0+git82+1402795), libudfread0 (>= 1.0.0+git108+b3e6936), libxml2
 (>= 2.10.4), oe-alliance-branding, openatv-autorestore, python3-asyncio, python
3-codecs, python3-core, python3-crypt, python3-email, python3-fcntl, python3-ima
ge, python3-mime, python3-mmap, python3-netclient, python3-netifaces, python3-ne
tserver, python3-pickle, python3-pillow, python3-process, python3-pyusb, python3
-shell, python3-six, python3-smtpd, python3-threading, python3-treq, python3-twi
sted-core, python3-twisted-web, python3-xml, python3-zopeinterface, socketdaemon
, virtual/blindscan-dvbc
Recommends: glib-networking, glibc-gconv-utf-16, gstreamer1.0-plugin-subsink, gs
treamer1.0-plugins-bad-autoconvert, gstreamer1.0-plugins-bad-dash, gstreamer1.0-
plugins-bad-faad, gstreamer1.0-plugins-bad-hls, gstreamer1.0-plugins-bad-mpegpsd
emux, gstreamer1.0-plugins-bad-mpegtsdemux, gstreamer1.0-plugins-bad-opusparse,
gstreamer1.0-plugins-bad-rtmp, gstreamer1.0-plugins-bad-smoothstreaming, gstream
er1.0-plugins-bad-videoparsersbad, gstreamer1.0-plugins-base-alsa, gstreamer1.0-
plugins-base-app, gstreamer1.0-plugins-base-audioconvert, gstreamer1.0-plugins-b
ase-audiorate, gstreamer1.0-plugins-base-audioresample, gstreamer1.0-plugins-bas
e-ivorbisdec, gstreamer1.0-plugins-base-ogg, gstreamer1.0-plugins-base-opus, gst
reamer1.0-plugins-base-playback, gstreamer1.0-plugins-base-rawparse, gstreamer1.
0-plugins-base-subparse, gstreamer1.0-plugins-base-typefindfunctions, gstreamer1
.0-plugins-base-videoconvertscale, gstreamer1.0-plugins-base-vorbis, gstreamer1.
0-plugins-good-apetag, gstreamer1.0-plugins-good-audioparsers, gstreamer1.0-plug
ins-good-autodetect, gstreamer1.0-plugins-good-avi, gstreamer1.0-plugins-good-fl
ac, gstreamer1.0-plugins-good-flv, gstreamer1.0-plugins-good-icydemux, gstreamer
1.0-plugins-good-id3demux, gstreamer1.0-plugins-good-isomp4, gstreamer1.0-plugin
s-good-matroska, gstreamer1.0-plugins-good-rtp, gstreamer1.0-plugins-good-rtpman
ager, gstreamer1.0-plugins-good-rtsp, gstreamer1.0-plugins-good-soup, gstreamer1
.0-plugins-good-udp, gstreamer1.0-plugins-good-wavpack, gstreamer1.0-plugins-goo
d-wavparse, gstreamer1.0-plugins-ugly-amrnb, gstreamer1.0-plugins-ugly-amrwbdec,
 gstreamer1.0-plugins-ugly-asf, gstreamer1.0-plugins-ugly-cdio, gstreamer1.0-plu
gins-ugly-dvdsub, libdvdcss
Source: enigma2.bb
root@vusolo4k:~#

**Comment by jbleyel** [comment]
opkg list | grep 'enigma2 - 7'
opkg list-installed | grep 'enigma2 - 7'

**Comment by ian10951** [comment]
vusolo4k login: root
Password:
Last login: Wed Mar 13 18:30:51 GMT 2024 on pts/0
root@vusolo4k:~# opkg list | grep 'enigma2 - 7'
enigma2 - 7.4-devel+git33193+be5371a-r0 - Enigma2 is an experimental, but useful
 framebuffer-based frontend for DVB functions
enigma2 - 7.3+git33241+4b5256d-r0 - Enigma2 is an experimental, but useful frame
buffer-based frontend for DVB functions
oe-alliance-enigma2 - 7.3-r3 - Merge machine and distro options to create a enig
ma2 machine task/package
root@vusolo4k:~# opkg list-installed | grep 'enigma2 - 7'
enigma2 - 7.4-devel+git33193+be5371a-r0
oe-alliance-enigma2 - 7.3-r3
root@vusolo4k:~#

**Comment by ian10951** [comment]
Have you finished with me buddy ?

If so I will revert those 2 files again to give me my EPG back in my InfoBar and the progressbar back in my boxes display.

**Comment by jbleyel** [comment]
There is something wrong on the build system for 7.3 devel.

The 7.4 devel looks correct.

**Comment by ian10951** [comment]
Okay I will leave it with you.

Once youve sorted it can you post here please so I can get everything right to accept the new build as I'm currently using py files and I need to remove them to get any updates you may add to fix this issue.

**Comment by ian10951** [comment]
Yes I did try that.

But no pyc is created after a restart or reboot

**Comment by ian10951** [comment]
Ok this issue can now be closed as resolved.

I added the new EventInfo.py that has the python 3.11 fix manually and now a pyc file is indeed created and the EPG in the InfoBar and boxes display is again as it should be.
