### ISSUE TITLE
[DateTimeInput] Full minute/hour

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3280]
[I have a problem](https://github.com/openatv/enigma2/commit/33240170b6e61d776ded34d4fd32c9a495a9f153#commitcomment-139682449).
I initialize InstantRecordingEndTime with a time and 35 seconds deviation to the full minute.
If I change the time, I get the new displayed time +35 seconds. But I should get the full minute, because seconds are not displayed.
Except I do not make any changes, then it would be good to keep the 35 seconds.

Another ask!
```
class DateTime(Setup):
	def __init__(self, session, setupSection, default, smallStep=60):
```
Why "smallStep=60"? Then bigStep=3600 too!(`def __init__(self, session, setupSection, default, smallStep=60, bigStep=3600):`)

**Comment by jbleyel** [comment]
> Another ask!
> 
> ```
> class DateTime(Setup):
> 	def __init__(self, session, setupSection, default, smallStep=60):
> ```
> 
> Why "smallStep=60"? Then bigStep=3600 too!(`def __init__(self, session, setupSection, default, smallStep=60, bigStep=3600):`)

Can you please explain more. What's the issue of the steps?
