### ISSUE TITLE
Remaing time now missing in the InfoBar

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3281]
Just noticed that when using IanSavs new EventInfo.py that the remaining time of the current event is now missing ( see screenshot where I've drawn a red circle in the InfoBar )

If I revert to the old files then the remaing time is once again displayed correctly.

![1_0_19_22D5_434_1_C00000_0_0_0_20240314121909](https://github.com/openatv/enigma2/assets/11910714/bff62dce-327c-48f9-b61c-2f4458f87875)

**Comment by IanSav** [comment]
When you say "new" code, what is the "Enigma2 revision" number in MENU > Information > About openATV screen?

There were a few more changes this evening (Australia time).

**Comment by ian10951** [comment]
![1_0_1_788B_414_1_C00000_0_0_0_20240314125717](https://github.com/openatv/enigma2/assets/11910714/52d6cc9c-ba43-46f6-b71f-57883eefa67b)

**Comment by ian10951** [comment]
Ok my applogies.

I've just updated again and now the remaining time is showing again.

**Comment by IanSav** [comment]
When the 3.11 build reports were removed I switched to the newer 3.12 syntax.  I was under the impression that all openATV users were now using Python 3.12.  That is not the case.  @jbleyel and I have been adding compatibility patches to correct the issues of changed Python syntax.  Those patches will be removed when the older Python 3.11 builds finally stop.
