### ISSUE TITLE
Image crash

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3290]
Is there anything that can be done to prevent a crash when you enter the positioner setup menu whilst using a Stream Relay channel ?

I do understand that obviously the dish cannot be tweaked whilst on a Stream relay channel and that you have to be on a normal service to do this, but preventing it from crashing if you forget ( like I just did ) and do enter this menu whilst on a Stream Relay channel would be nice.

Crash log attached.
[20240418-130745-enigma2-crash.log](https://github.com/openatv/enigma2/files/15024664/20240418-130745-enigma2-crash.log)

**Comment by jbleyel** [comment]
Please use this PositionerSetup/plugin.py
[plugin.py.zip](https://github.com/openatv/enigma2/files/15026702/plugin.py.zip)

Reproduce the crash and post the debug log.

**Comment by ian10951** [comment]
[20240418-160623-enigma2-debug.log](https://github.com/openatv/enigma2/files/15026836/20240418-160623-enigma2-debug.log)

**Comment by ian10951** [comment]
I think possibly adding an exception stating "Please tune to a DVB channel first before entering this Menu" would probably surfice.

**Comment by jbleyel** [comment]
> I think possibly adding an exception stating "Please tune to a DVB channel first before entering this Menu" or words to that effect would probably surfice.

This will be an option but I don't like that.

**Comment by jbleyel** [comment]
Please try this:
[plugin.py.zip](https://github.com/openatv/enigma2/files/15027233/plugin.py.zip)

And send the debug log again.

**Comment by ian10951** [comment]
Tried the fix but it still crashes

Crashlog attached.
[20240419-063016-enigma2-crash.log](https://github.com/openatv/enigma2/files/15033515/20240419-063016-enigma2-crash.log)

**Comment by jbleyel** [comment]
Is there any issue if you switch to a non Stream Relay channel before you open the PositionerSetup?

**Comment by ian10951** [comment]
No none.

Works perfectly on any none Stream relay channel.

**Comment by jbleyel** [comment]
Okay. I will try to add a pre-check.

**Comment by jbleyel** [comment]
[plugin.py.zip](https://github.com/openatv/enigma2/files/15039314/plugin.py.zip)

**Comment by ian10951** [comment]
That
![1_0_19_83_6_85_C00000_0_0_0_20240419120514](https://github.com/openatv/enigma2/assets/11910714/6e712235-9e87-4492-8ed4-11754fb13677)
 stops the crash

**Comment by jbleyel** [comment]
How about the text?

**Comment by ian10951** [comment]
Perhaps add change to a none Stream Relay channel so the user doesnt just change to another channel which is using Stream Relay and then try again and get the same result.

**Comment by jbleyel** [comment]
Please provide the full sentence what you prefer.

**Comment by ian10951** [comment]
"Stream Relay is active, please change to a none Stream Relay channel"

I think that covers it, its simple and to the point
