### ISSUE TITLE
Navigation enhancement for subservices new implementation

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3291]
Following this commit https://github.com/openatv/enigma2/commit/99294564b4fc8194d8abdc9d140783f8790bc98a, I think a navigation enhancement would be welcome.

With the new mod, we now access to the subservices as a (temporary) bouquet. But if when we want to navigate through the initial playlist (button up/down), we navigate into the subservices list, not into the initial playlist. So we have to do blue button, select the initial playlist and the cursor is not on the previous selected channel except if the selected subservices is the first in the groupservices file for this channel.

The idea would be to automatically go back to the initial position in the the initial bouquet as it was the case with the previous functioning of subservices navigation and not navigate into the subservices screen.

Hope I am clear. Don't hesitate to ask for more informations if needed.

Thanks

OpenATV 7.4-devel 20240419

**Comment by IanSav** [comment]
I am not sure we fully understand your request.

If I follow your post correctly there is no sense of history with the ChannelSelection screen.  Remembering the history of navigation through the bouquets in this screen not currently possible.  Hence remembering how you get into the subservices (virtual) bouquet is also not tracked.

While such a facility may be possible I don't think this is on any current coding plans/roadmaps.

**Comment by jeepcook** [comment]
To be clear:
1- I have a list (list fav) with channel 1, channel 2, channel 3
1- I'm watching channel 2
2- I select a channel 2 subservice, example the 2nd in the list
3- I push up or down button, the navigation isn't into the list fav but into the subservices so I can't directly access to channel 1 or channel 3
4- The proposal is to navigate into the list fav, not into the subservices, I have the subservices button for that.

**Comment by GhostofGeeeee** [comment]
I think this will broke a consistent usage of ChannelSelection.
It will be possible that your subservice is not in the list you think. -> It will be Channel 1 selected, different to the playing service.

"and the cursor is not on the previous selected channel except if the selected subservices is the first in the groupservices file for this channel"
This is not a Subservice Issue. But I think it's a Issue(it's has been fixed with disabled multibouquet).
But only thinkable if the subservice is in the list and not only the referring subservice!

**Comment by GhostofGeeeee** [comment]
You can use "Key 0" and then up or down.

**Comment by jeepcook** [comment]
The 0 key is a workaround and will not work in the case of the sélection of more than one subservice from the same channel. 
Example channel1:
- zap to subservice 2
- zap to subservice 4
--> The 0 key will zap to subservice 2 not to the first subservice which is the channel 1 in the fav list.

My initial request for this update was just to have a progress bar in the subservice screen, not to have to do different manipulations to zap and stay in the favorite list.

**Comment by GhostofGeeeee** [comment]
With [this ](https://raw.githubusercontent.com/GhostofGeeeee/enigma2/b27dea862e5b504711541e5286fd551b337a38f7/lib/python/Screens/ChannelSelection.py) you can use ZapHistory. Not only Key 0 for last, now more history.
It's just a draft but I think you not agree the whole concept.

The concept you think is a bit different and ugly at this point and I can't imagine a consistent solution.
Maybe it's possible to compute the first Services and zap to but how to integrate this function on Menu/RC?

**Comment by jeepcook** [comment]
Hello,

With this patched file, I have an enigma2 bootloop.

**Comment by GhostofGeeeee** [comment]
I'm sorry, you need a current openATV.
But I have a new Version later, please wait.

**Comment by jeepcook** [comment]
OK I have the 20240505 7.4 version.

**Comment by GhostofGeeeee** [comment]
Sorry, you need Enigma2-Revision: 33295+80f8e8a

Then you can test my new Version with these 2 files.
https://raw.githubusercontent.com/GhostofGeeeee/enigma2/2535e59fe144adafb1bf299f991cb4b5ab82c366/lib/python/Screens/ChannelSelection.py

https://raw.githubusercontent.com/GhostofGeeeee/enigma2/2535e59fe144adafb1bf299f991cb4b5ab82c366/lib/python/Screens/InfoBarGenerics.py

**Comment by jeepcook** [comment]
Ok I have an upper enigma2 version 
![image](https://github.com/openatv/enigma2/assets/17811804/984dbc57-c0ba-4eaf-af38-2e32bc430592)

So I have to install an older one.

**Comment by jbleyel** [comment]
You need the devel feed.

**Comment by jeepcook** [comment]
Ok, I have now 
![image](https://github.com/openatv/enigma2/assets/17811804/ccb11c00-2219-45b1-bf67-564e8bf2607e)

Tests done. I think now it's easier to use. The 0 usage alternative to come back to the bouquet list is a good idea and work great.
We just lost the 0 functionality when we come back to the main bouquet for the current channel (the one used to access to subservices).
But I think now it's better human friendly.
Thanks

**Comment by jeepcook** [comment]
> We just lost the 0 functionality when we come back to the main bouquet for the current channel (the one used to access to subservices). But I think now it's better human friendly. Thanks

It's not really a problem because ZapHistory can be used

**Comment by jeepcook** [comment]
> Please give me an example to reproduce, to be sure that I understand you.

Process:
- you're on channel 1 and zap to channel 2
- you press 0 key, the zap is done to channel 1
- now you select a subservice from channel 1
- you press 0 do go back to the bouquet
- you press 0 again, this has no effect instead of zap to channel 2.

**Comment by GhostofGeeeee** [comment]
This is the curios scenario I know but:
> you press 0 again, this has no effect instead of zap to channel 2.

I expect zap to the selected subservice but you get channel 2 but you don't get channel 2?

**Comment by jeepcook** [comment]
Perhaps I do a mistake. Yes probably the 0 has to have as effect to zap to subservice.  I have to verify the operation of the old subservices version.

**Comment by jeepcook** [comment]
The same look
![image](https://github.com/openatv/enigma2/assets/17811804/56bee000-0a5e-42cb-90e3-72963838262c)

**Comment by GhostofGeeeee** [comment]
Current is TF1.
Key_0 won't zap to France 2?

**Comment by jeepcook** [comment]
I confirm that Key_0 zap to France 2 UHD

**Comment by GhostofGeeeee** [comment]
Works?

**Comment by jeepcook** [comment]
> Works?

What works ?

**Comment by GhostofGeeeee** [comment]
I have problems to follow you, is there still a problem?

**Comment by jeepcook** [comment]
The last test were made with the previous version of subservices, not the new one.  Since I said "Ok I just test the old version so here is the working scenario that doesn't work with the new version:"

**Comment by GhostofGeeeee** [comment]
old
previous
new
I have only one version of interest.

**Comment by jeepcook** [comment]
OK but the last tests were made to compare the difference between booth, 7.4 version and 7.5 devel version

**Comment by jeepcook** [comment]
Back to devel with a clean installation
![image](https://github.com/openatv/enigma2/assets/17811804/79fd9576-c6cc-421a-8107-4faab7370ba6)

- Zap to TF1
- Zap to MTV Unplugged DK
- Choose a subservice (MTV Unplugged DE)
- Select 0 on RC so back to main list so to MTV Unplugged DK
- Screen of ZapHistory:
![image](https://github.com/openatv/enigma2/assets/17811804/7ab7bf73-a59d-442d-b44a-5af4c78501fc)

- Exit this screen and select 0 on RC, the zap is to TF1 so is correct.

Did some similar tests with other channels. I think I had a problem with my previous devel image which should contain old patchs because now everything is Ok I think.

**Comment by jeepcook** [comment]
I have a question, when I zap across the ZapHistory list, the previous channel is not the previous watched channel but the previous in the ZapHistory. Is this the normal situation?

**Comment by GhostofGeeeee** [comment]
> now everything is Ok I think.

Nice.

> So the key_0 is the previous in the ZapHistory not the previous watched.

I remember discussion on forum, not easy, for this you can create a different issue...

**Comment by jeepcook** [comment]
> Thank you for your cooperation. I don't want to make a PullRequest until you're really happy with the whole concept. It's nice if this problem has improved, but we took the opportunity to rule out further problems (with subservices) and finally initiate final changes.

Sometimes I can be demanding but I like things done well. I think we now have a reliable solution. Hope other users enjoy.

Thanks for tour great job.

**Comment by jeepcook** [comment]
Cab I do the daily devel update for enigma2 (33302) and keep the new subservices functionality working?

**Comment by GhostofGeeeee** [comment]
> but we took the opportunity to rule out further problems (with subservices) and finally initiate final changes.

This should mean:
but lets take the opportunity to rule out further problems (with subservices) and after initiate final changes.

You can hold these [2 Files](https://github.com/openatv/enigma2/compare/master...GhostofGeeeee:enigma2:NewSubservices) (May 5, 2024). I let them uptodate.
![Unbenannt - Kopie](https://github.com/openatv/enigma2/assets/130693485/64b5de87-3a0c-4e63-8ede-35010cedd056)
![Unbenannt2 - Kopie](https://github.com/openatv/enigma2/assets/130693485/fa913bb0-97f6-4d54-838e-11a8e1bb0a4c)

**Comment by jeepcook** [comment]
> but lets take the opportunity to rule out further problems (with subservices) and after initiate final changes.

Ok, ok. What will be the others changes?

**Comment by GhostofGeeeee** [comment]
I give you a bit time to find more improvement ;)

**Comment by jeepcook** [comment]
Ok cool !

Minor change I think:

- Add the ability to have the serviceRef in the groupedservices file in lowercase instead of upper case. In fact I have my .tv generated by a plugin (e2m3u2b), it generate the serviceref in lower case but I have to have the reference in uppercase in groupedservices to have subservices working.

A more complex feature I think:
- Add the ability to have a different name of the channel in the groupedservices file than the one in the main bouquet. 
Example: I have a channel named ARTE in my bouquet, I'd like to name it [FR] ARTE HEVC in my groupedservices file but with the same ServiceRef and the same iptv url. Just a different name.

What do you think about this?

**Comment by GhostofGeeeee** [comment]
This is not the same construction site. But I will have a look on it.

**Comment by jeepcook** [comment]
> If you think there is a issue, use a different issue.

Ok I will do that.

**Comment by jeepcook** [comment]
I have a "crazy" idea I think ;-)
Because a lot of people don't know how to use subservices, don't know what is telnet or vi, don't know what is a ServiceRef etc etc.. they are unable to use the subservices functionality.

So the idea would be to add the possibility to create and maintain groupedservices file with the remote control.
This need to have a link between groupedservices file and a .tv file (named xxx.subservices.tv).
Each channel subservices would be separate by a marker named by the name of the channel (or information behind the #).
With the add to bouquet functionality and move mode, a channel would be to be add to a subservice by moving it in the good bookmark.

What do you think about this?

**Comment by GhostofGeeeee** [comment]
[But if you don't use subservices and create Bouquet with almost the same content(of groupedservices) you haven't it?](https://github.com/openatv/enigma2/issues/3163#issuecomment-1867863036)
No response, to late. You request is not wrong but not my challenge.

**Comment by jeepcook** [comment]
You told me to give you some implementation ideas. This was just one.

**Comment by GhostofGeeeee** [comment]
I told you:
but lets take the opportunity to rule out further problems (with **this new** subservices) and after initiate final changes.

**Comment by jbleyel** [comment]
> I have a "crazy" idea I think ;-) Because a lot of people don't know how to use subservices, don't know what is telnet or vi, don't know what is a ServiceRef etc etc.. they are unable to use the subservices functionality.
> 
> So the idea would be to add the possibility to create and maintain groupedservices file with the remote control. This need to have a link between groupedservices file and a .tv file (named xxx.subservices.tv). Each channel subservices would be separated by a marker named by the name of the channel (or information behind the #). With the add to bouquet functionality and move mode, a channel would be to be add to a subservice by moving it in the good bookmark.
> 
> What do you think about this?

I had exactly this idea, but this needs a major change of bouquet handling because the subservices bouquets are not always visible. You can only see one at a time.

**Comment by jeepcook** [comment]
> I told you: but lets take the opportunity to rule out further problems (with **this new** subservices) and after initiate final changes.

In the current state, the changes can now be committed. The developments are stable, I've seen no new issue.

 
> I had exactly this idea, but this needs a major change of bouquet handling because the subservices bouquets are not always visible. You can only see one at a time.

We could have a .tv file corresponding of the content of the groupedservices file and keep the current (the new one) subservice functionality with the furtive subservices bouquets.

**Comment by jbleyel** [comment]
> We could have a .tv file corresponding of the content of the groupedservices file and keep the current (the new one) subservice functionality with the furtive subservices bouquets.

As I said. This needs a change in core code.
And the new .tv files contains the content of one group not all groups!

**Comment by jeepcook** [comment]
> As I said. This needs a major change in core code and this will be not compatible with other images. And the new .tv files contains the content of one group not all groups! I'm also intending to remove the support for the old file and convert the old file to the new files if exists.
> 
> But there is a problem. The files with .tv extension are also handled by 3rd party tools and these tools may break if we add additional files. (Maybe!!!)

Yes I understand. That's why I think it's better to have the subservices function (with groupedservices files) separated to its build method. The corresponding .tv file should contain all subservices. This .tv has to be permanent. 
It will stay compatible with other images as .tv file, not as image of the groupedservices file.
Plugin like e2m3u2b (version by Pepsik), will not touch this .tv file. In fact the plugin just have effect on its owned created or modified .tv files.
What is your idea around "to remove the support of old file"? And what will be the new format?

Thanks

**Comment by jbleyel** [comment]
You missunderstand.
A .tv file contains always only one bouquet and not multiple.
That means you need a .tv file for each group.
Markers as split of the groups is not working.
That's exactly the problem of the current file.

I will never implement a single .tv file for multiple subservice groups.

**Comment by jbleyel** [comment]
A possible solution will be:
You need one file named **_subservicebouquets.tv_**
This file has the same syntax like bouquets.tv and contains all groups.
Each group needs a file named **_subservicebouquet.aaaa.tv_**
In this file you can define a Name and you can add the channels for this group.

This solution will be a small change in enigma core and you get all features like a normal bouquet.


That's an idea but the implementation and the performance needs to check.

**Comment by jeepcook** [comment]
Ok you're the expert ;-) . About performances, in my case I have currently 107 subservices groups, so 107 files will be analysed by e2.
A different screen of management or a filter has to be create to separate and not displaying tv bouquets and subservices bouquets in the same screen, I think.
What will be the syntax into subservicebouquet.xxxx.tv?

**Comment by jbleyel** [comment]
The amount of files will only affect the start time because they have to loaded.
I think I have a better idea.
Let me check.

**Comment by jbleyel** [comment]
Hi @jeepcook , do you really need a subservice bouquet modification on the box and not editing the file?
It's a lot of extra code and testing needed.
The easiest way will be a subservicebouquets.tv + subservicebouquet.aaaa.tv.
But this will end up with 108 extra files on your box.

There is a more difficult way by using the existing file.


Both solutions needs some extra code.

So now the question again.

Do you really need that and is this also needed by many other user?

**Comment by jbleyel** [comment]
We should also open a new issues for this topic and close this issue if the zap problem is fixed.

@GhostofGeeeee, @jeepcook  What's the latest version to fix the history zap issue.
Are these files well tested and are these files based on the latest master version?

**Comment by jeepcook** [comment]
> Do you really need that and is this also needed by many other user?

No, it was just a suggestion but for my part I have no difficulties to maintain groupedservices file.

> @GhostofGeeeee, @jeepcook What's the latest version to fix the history zap issue. Are these files well tested and are these files based on the latest master version?

I'm using this mod until few days, now everything works great. The concerning files are https://github.com/openatv/enigma2/compare/master...GhostofGeeeee:enigma2:NewSubservices

**Comment by jeepcook** [comment]
Thanks for the commit. Because there is no 7.4 tag, how to know if this has been commited to 7.4 release? And why no 7.4 tag here https://github.com/openatv/enigma2

**Comment by jbleyel** [comment]
You need 7.4 + devel feed.
The 7.4 branch will be creates if 7.3 is EOL.
This change may not come to 7.3.

**Comment by jeepcook** [comment]
> You need 7.4 + devel feed. The 7.4 branch will be created if 7.3 is EOL. This change may not come to 7.3.

Ok thanks, and in 7.4 beta?

**Comment by jbleyel** [comment]
The final 7.4 will have this.
The current 7.4 not .. you need 7.4 + the devel feed.

**Comment by jeepcook** [comment]
Finally implemented on 7.4 beta. Thanks
