### ISSUE TITLE
Strange error RemainingToText.

### ISSUE THREAD

**Issue by 68foxboris** [openatv/enigma2#3300]
Tell me, please. I use this converter in my build and there are no problems. I decided to try installing the skin OctEtFHD.There seem to be no problems with the converter either.
But when playing the recorded video, an error appears:

19:47:35.6930   File "/usr/lib/enigma2/python/Components/Converter/RemainingToText.py", line 171, in getText
19:47:35.6940     result = f"{signDuration}{duration // 3600}:{duration % 3600 // 60:02d}"
19:47:35.6946                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:47:35.6947 ValueError: Unknown format code 'd' for object of type 'float'
19:47:35.6948 [ePyObject] (CallObject(<bound method Poll.poll of <class 'Components.Converter.RemainingToText.RemainingToText'>(NoSeconds)>,()) failed)

If the video file is recorded from a stream, there are no problems. Only when playing any other video file.
There are no problems on PLi-FullHD, maybe the problem is in the skin.

**Comment by jbleyel** [comment]
Can you please provide the meta file from the recording.

**Comment by 68foxboris** [comment]
This does not depend on the video file. I installed the skin and this problem appeared. I installed this skin by default and immediately crashed:

22:09:00.9528   File "/usr/lib/enigma2/python/Components/Converter/RemainingToText.py", line 171, in getText
22:09:00.9534 ValueError: Unknown format code 'd' for object of type 'float'

I launch it with a different skin, there are no errors. The skin itself is here:https://github.com/norhap/OctEtFHD-skin

**Comment by jbleyel** [comment]
Please try this and provide the debug log.
[RemainingToText.py.zip](https://github.com/openatv/enigma2/files/15134722/RemainingToText.py.zip)

You need to extract the py from the zip and copy the py to 

/usr/lib/enigma2/python/Components/Converter/

**Comment by 68foxboris** [comment]
Replaced. On the skin PLi-FullHD:

05:52:22.1609   File "/usr/lib/enigma2/python/Components/Converter/RemainingToText.py", line 89, in getText
    traceback.print_stack()

but there is no crash.
On OctEtFHD:

05:55:02.8596   File "/usr/lib/enigma2/python/Components/Converter/RemainingToText.py", line 89, in getText
    traceback.print_stack()
05:55:03.8879   File "/usr/lib/enigma2/python/Components/Converter/RemainingToText.py", line 177, in getText
05:55:03.8888     result = f"{signDuration}{duration // 3600}:{duration % 3600 // 60:02d}"
05:55:03.8894                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:55:03.8894 ValueError: Unknown format code 'd' for object of type 'float'
05:55:03.8895 [ePyObject] (CallObject(<bound method Poll.poll of <class 'Components.Converter.RemainingToText.RemainingToText'>(NoSeconds)>,()) failed)

**Comment by jbleyel** [comment]
Now I’m confused.
Please ask @norhap if he can investigate.

**Comment by jbleyel** [comment]
The OctEtFHD is not compatible with openATV.

**Comment by jbleyel** [comment]
Please provide the full debug log if the error occours.

**Comment by 68foxboris** [comment]
Fixed after this:https://github.com/openatv/enigma2/commit/82398ff809319134332507c418c819f4bab86a24
and this:https://github.com/OpenPLi/enigma2/commit/ec247c6b1dbfbc07d21fcfbaa18de2a858e86b5d
