### ISSUE TITLE
[Question] How to access the user interface positioner wizard?

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3304]
I can't seem to find the ui positioner (align the red box to the edge of screen) during the Welcome Wizard (when I've clean flashed an image into another slot). Has this been removed intentional or in error?

**Comment by jbleyel** [comment]
What you mean with ui positioner?

**Comment by wedebe** [comment]
![posit20240501113908](https://github.com/openatv/enigma2/assets/9741693/42c2c3b0-8843-4234-9fc1-63c89697ea2b)


> What you mean with ui positioner?

**Comment by IanSav** [comment]
I will bring this code up to current standards and link it into the "Usage & GUI" menu.

**Comment by jbleyel** [comment]
This Screen in Wizard is not implemented in openATV.
You may have seen that in openVIX.

**Comment by wedebe** [comment]
> This Screen in Wizard is not implemented in openATV. You may have seen that in openVIX.

Ah, I've used openPLI and it features during setup there (although only briefly before it continues automatically to the next step). 

It's called overscan there, although the video isn't affected, just the OSD (in openATV at least)

**Comment by IanSav** [comment]
Did you ask because there is a need for it in openATV?

**Comment by wedebe** [comment]
> Did you ask because there is a need for it in openATV?

For some reason I thought it's something openATV had during setup at some point in history. Going way back to the last 6.2 image I can see I was imagining things, sorry!

**Comment by jbleyel** [comment]
This wizard was removed Sep. 2013.

**Comment by wedebe** [comment]
> This wizard was removed Sep. 2013.

Long before I started using E2 😂

**Comment by IanSav** [comment]
Because you brought the issue up I am preparing to allow the wizard to make a return should it be wanted.

**Comment by ian10951** [comment]
I'm confused by this.

Its already in ATV 7.3

Menu/Setup/Video/OSDPositionSettings

![1_0_19_93_2_85_C00000_0_0_0_20240517073943](https://github.com/openatv/enigma2/assets/11910714/324beafc-c9ff-4212-b4e2-37f681c5c52c)

**Comment by jbleyel** [comment]
This issue is beause of the Wizard.
The screen itself in menu is still there.
