### ISSUE TITLE
4097 player not present on latest 7.3

### ISSUE THREAD

**Issue by willow5** [openatv/enigma2#3307]
I have just installed the latest openatv 7.3 on a DM7020HD but the 4097 streamer does not appear to be there by default. I installed gstplayer and exteplayer but still 4097 streamer service is not present. Hiw can I enable the 4097 service please?

Thank you

**Comment by jbleyel** [comment]
We need more info.
For 4097 services you do not need gstplayer and exteplayer at all because it will be played out of the box using gstreamer internal player.
If you wanna use external player you need ServiceApp.

**Comment by jbleyel** [comment]
Please reopen if the issue still exists and provide more details.
