### ISSUE TITLE
PL Language error in openatv 7.4 

### ISSUE THREAD

**Issue by richard173** [openatv/enigma2#3324]
after setting the language to pl (only it is selected), everything is OK, but when we restart the system, the name of the month and day in the skin changes, e.g. the month should be displayed: Maj is May, Sobota is Saturday, change the language to pl again and save changes to ok, but when we restart the system I have English names again
receiver - VU+4KSE
current image - OPENATV 7.4

**Comment by richard173** [comment]
After today's update, the same problem
receiver - VU+UNO4KSE
current image - OPENATV 7.4 latest
![Uploading error.png…]()

**Comment by richard173** [comment]
After today's update, the same problem
receiver - VU+UNO4KSE
current image - OPENATV 7.4 latest
![error](https://github.com/openatv/enigma2/assets/70439427/43fa9ec2-a783-4fe5-a196-14fe7c1f75e2)

**Comment by jbleyel** [comment]
Looks like a Skin issue.

**Comment by pololoko111** [comment]
This is the skin's fault. Everything is well translated.No problem with Matrix or Algare skin.

**Comment by richard173** [comment]
> Is the Date name the only part in English after reboot or are there also other things?

the only thing is the month and day, the rest is translated, the problem also occurs on the Metrix skin

**Comment by richard173** [comment]
after turning on the receiver and entering the language settings on the first page, all descriptions at the bottom are translated into Polish except English (AU), (GB), (US) (image 1)
on the second page, the descriptions at the bottom are translated and the Polish language is selected and as you can see at the top at the time, the day is displayed in English (image 2), now just go back to the first page and back to the second page and the description of the day is displayed next to the clock correctly in Polish (image 3) we save and everything is ok, but after restarting the system the days and months are displayed in English again
![1](https://github.com/openatv/enigma2/assets/70439427/0ef56aff-cff2-4ab9-a9c2-477290d7684b)
![1](https://github.com/openatv/enigma2/assets/70439427/a2986f56-5dc2-43e9-9244-e918808e93c8)
![2](https://github.com/openatv/enigma2/assets/70439427/af9db8da-4aaf-4aa5-a70f-523e8a63b38d)
![2](https://github.com/openatv/enigma2/assets/70439427/01f24e1e-4e86-45d6-bfff-a31f181ecef4)
![3](https://github.com/openatv/enigma2/assets/70439427/a017ebe6-7cea-4e81-aa71-fcbc75073726)
