### ISSUE TITLE
hotkey setup

### ISSUE THREAD

**Issue by popking159** [openatv/enigma2#3334]
**Is your feature request related to a problem? Please describe.**
In Hotkey setup , it was available to assign a key for volume dwon and volume up , then it was deleted , then it is back again , it is good to be present but there is a problem , if i assign cross_left button for volume down , it works but each click on the cross_left button decreases the volume by one step , and if i hold the key , no acton and it is defined as unhandled key , the good function is to hold the cross_left key and the volume continues to decrease , 

**Describe the solution you'd like**
make the assignment with flage "r" 

**Describe alternatives you've considered**
may be modify class InfoBarChannelSelection in  InfoBarGennerics.py by adding this :
```
"volumeUp": (self.volumeUp, _("change Volume up")),
"volumeDown": (self.volumeDown, _("change Volume down")),
```
		

**Additional context**
![1infobarge](https://github.com/openatv/enigma2/assets/47087407/69e2f30e-1922-4e14-a1c2-3c8d1507403d)

regards

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/14cbfa7b7c412722b600a13feac065a21340435d

**Comment by popking159** [comment]
This is not I asked for .
After assignment, each click make the action by one step , so I must do many repeated click to increase or decrease volume  , 
If you can modify it by adding the flage "repeat" it will be enough.
If not you can go for alternative solution 
My alternative solution is to add these 2 line , for you it makes no sense, for me it makes sense , if These to line present, I can modify keymap.xml to add another 2 lines that will do my request.
<key id="KEY_LEFT" mapto="volumeDown" flags="mr" />
and the same for cross_right

All this because alot of users prefer to control volume by right and left , and control zap by up and down and service list by ok button .

Adding easy another control mode to many users is a good thing .
Refards

**Comment by jbleyel** [comment]
This is not that easy because you are using hotkey's and the "ButtonSetupActions" have no repeat flag.

**Comment by popking159** [comment]
> This is not that easy because you are using hotkey's and the "ButtonSetupActions" have no repeat flag.

No problem, I will do the modifications on my image . I did it already and it is working .

**Comment by jbleyel** [comment]
You can try this:

Create a this file "/etc/enigma2/keymap_usermod.xml" with this content:

Warning!!!

The left / right buttons may no longer working for other things.

```
<keymap>

	<map context="GlobalActions">
		<key id="KEY_RIGHT" mapto="volumeUp" flags="mr" />
		<key id="KEY_LEFT" mapto="volumeDown" flags="mr" />
	</map>

</keymap>

```

**Comment by popking159** [comment]
> You can try this:
> 
> Create a this file "/etc/enigma2/keymap_usermod.xml" with this content:
> 
> Warning!!!
> 
> The left / right buttons may no longer working for other things.
> 
> ```
> <keymap>
> 
> 	<map context="GlobalActions">
> 		<key id="KEY_RIGHT" mapto="volumeUp" flags="mr" />
> 		<key id="KEY_LEFT" mapto="volumeDown" flags="mr" />
> 	</map>
> 
> </keymap>
> ```

I will try , this method may be enough for me 
Thanks

**Comment by popking159** [comment]
I modified it a little
now it does what i want exactly
`<keymap>

	<map context="InfobarChannelSelection">
		<key id="KEY_RIGHT" mapto="volumeUp" flags="mr" />
		<key id="KEY_LEFT" mapto="volumeDown" flags="mr" />
	</map>

</keymap>`
