### ISSUE TITLE
TeamViewer in OpenATV (Yocto Linux).

### ISSUE THREAD

**Issue by yakuzja** [openatv/enigma2#3346]
Hello,

It is possibile to integrate into Yocto Linux Team Viewer:

Example:
https://www.teamviewer.com/en-us/global/support/knowledge-base/teamviewer-tensor-classic/teamviewer-embedded/installation/set-up-a-yocto-image-for-raspberry/

Maybe the User needs then to Setup his Account via Web Browser (TeamViewer Password and Login). 

Could someone make it possibile ? That WE can Access OpenATV from Notebook Directly ?

I also have sometime problems to use IPTV, using Plugin but it's possibile to make this as normal Channels.

Regards,
OpenATV User

**Comment by atvcaptain** [comment]
not possible the agent need a system with qt gui, e2 stb use only framebuffer
