### ISSUE TITLE
Automatic restore broken

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3370]
With the last big 7.4 update the automatic restore process is broken.

flag setting, plugins and fast are on the /media/hdd/image/config directory.

With the 20240624 version only the untar of enigma2settingsbackup.tar.gz is done, and the system boot immediately after so with turbo mode instead of fast mode.

So the installation of /media/hdd/images/ipk packages are not installed.
The installation of the content of installed-list.txt and the uninstallation of the content of removed-list.txt are not executed.

The log stop after the untar process.

Note that with 20240621 image there is no problem, the process is correctly executed. So the problem comes from the big merge of these last days.

After the boot, the immediately manual execution of the restore solve the issue, but it's not automatic.

**Image/Box Model (please complete the following information):**
 - Version: 7.4 20240624
 - BoxModel: SF8008

**Comment by jbleyel** [comment]
should be fixed in the next version

**Comment by jeepcook** [comment]
Ok thanks, could you please commit the fix in 7.4 branch? This fix is useful only for branch where we have images or where we can build one. So in our case 7.4, not master.
Thanks

**Comment by jeepcook** [comment]
Closed by error
