### ISSUE TITLE
OSC info. A small correction.

### ISSUE THREAD

**Issue by pololoko111** [openatv/enigma2#3377]
Request for a small correction. In OSCinfo, it does not show special characters in the readers tab.
My reader should have the name Vip+Max but it shows Vip%2bMax
Thank you in advance.

![osc](https://github.com/openatv/enigma2/assets/37630415/695cb753-7a73-4c19-ab28-66f17c915683)

**Comment by MrServo** [comment]
Done.  Thank you for reporting!
