### ISSUE TITLE
Button text missing on Skin Default

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3379]
This has been reported a number of times recently on various forums from people using various skins. My skin has the same issue too. It started after someone refactored some code a number of months ago.

To see the issue yourselves just boot the box into the Skin Default emergency skin and you will see all the coloured buttons are displayed but none have the text next to them stating what pressing a given button achieves. But as I said this issue is not limited to just the Skin Default skin, its present on quite a number of other skins too.

**Comment by jbleyel** [comment]
Please provide a screenshot of the affected screen.
We can fix the default skin but not the other skins because that needs to be done by the skinner.

**Comment by ian10951** [comment]
Its any screen that has coloured buttons, the text is always missing.

I've attached 2 random screens for you to see, but as i said its all of screens that have any coloured buttons displayed including the infobar.
![1_0_19_4488_4088_233A_EEEE0000_0_0_0_20240711093052](https://github.com/openatv/enigma2/assets/11910714/96f41db3-857b-4f10-be4a-2a9c10e2ea6e)
![1_0_19_4488_4088_233A_EEEE0000_0_0_0_20240711093116](https://github.com/openatv/enigma2/assets/11910714/f341d146-d6e1-4b8f-92c5-75ef9cafaf67)

**Comment by ian10951** [comment]
Its the same when using the GraphicalInfobar too and the normal Graphical EPG. Its most annoying.

![1_0_19_93_2_85_C00000_0_0_0_20240711094341](https://github.com/openatv/enigma2/assets/11910714/46f3c1e9-63ab-4eba-8dae-e61729b30c91)

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/99294564b4fc8194d8abdc9d140783f8790bc98a

**_- Make all button definitions follow the standards by replacing Button() with StaticText()._**

**Comment by jbleyel** [comment]
All color buttons will be StaticText step by step.

**Comment by ian10951** [comment]
Thanks for the fix.

However now I've updated to 7.4 stable I no longer have the dev level so it maybe a few days before I can report further on this. Hopefully though not to many and there will be a normal 7.4 image update available soon.

**Comment by jbleyel** [comment]
What you mean with fix?
There is no fix.
The change from Button to StaticText is from April 18 and already in the productive 7.4 image.

**Comment by ian10951** [comment]
Oh ok

Well its not working then as you can see from those screenshots.

**Comment by jbleyel** [comment]
You need to change the Skin.
The color button text needs to be a source widget like in 90% of the screens.

**Comment by ian10951** [comment]
Ok I will do that.

I at least am capable of doing that, but many others are not. I dont understand why changes have to be made that break things that a lot of people who are regular users can do nothing about. Everything worked perfectly before those changes so why fix something that isnt broken ?

Anyway Thank You for your suggestion and I at least will have my skin working properly again once I make these changes. However, that wont fix the default skin and I guess other users with this issue will just have to use another skin and get rid of their favoured skin because its now too old.

**Comment by jbleyel** [comment]
I'm pretty sure that all the other distributions will do that too.
The default skin needs some more fixes.

**Comment by wedebe** [comment]
Just my 2 cent here - shouldn't breaking, potentially breaking and significant / refactor changes be done on the development branch & version (7.5 as of now).

People stopped developing skins for the likes of Mozilla Thunderbird (mail client) 'cos of constant breaking changes and improvements. Granted, these changes are for the better in the long run, but at least provide a frozen/stable version. Furthermore, there are likely a number of skins no longer under development by their creators.

**Comment by jbleyel** [comment]
> Just my 2 cent here - shouldn't breaking, potentially breaking and significant / refactor changes be done on the development branch & version (7.5 as of now).
> 
> People stopped developing skins for the likes of Mozilla Thunderbird (mail client) 'cos of constant breaking changes and improvements. Granted, these changes are for the better in the long run, but at least provide a frozen/stable version. Furthermore, there are likely a number of skins no longer under development by their creators.

I understand your point.
But we do not differentiate between major and minor changes in enigma core.
The major version updates are mostly because of oe changes.

We always try to update the code without skin changes but this is not always possible.
And sometimes we just fix a very old bug in skins.

**Comment by jbleyel** [comment]
@ian10951 : Can we close this?

**Comment by ian10951** [comment]
I guess so.

Its not been fixed though in the default skin, but at least now your aware of the issue.
