### ISSUE TITLE
Error compiling OpenATV 7.4

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#3393]
Hello,

Despite of https://github.com/oe-alliance/oe-alliance-core/commit/41067e5bfb093ac3af0f28ee53c245409ef3a932 followed by https://github.com/oe-alliance/oe-alliance-core/commit/a62f8c261fe619579f44bcec87de03eb157ded18 , the compilation of OpenATV 7.4 is still broken with the same error:

`WARNING: redsea-git-r0 do_fetch: Failed to fetch URL git://github.com/windytan/redsea.git;protocol=http;branch=master;protocol=https, attempting MIRRORS if available
ERROR: redsea-git-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot-native/usr/bin/python3-native:/home/openatvbuilder/openatv7.4/build-enviroment/openembedded-core/scripts:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot/usr/bin/crossscripts:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot-native/usr/sbin:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot-native/usr/bin:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot-native/sbin:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/recipe-sysroot-native/bin:/home/openatvbuilder/openatv7.4/build-enviroment/bitbake/bin:/home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/hosttools"; export HOME="/home/openatvbuilder"; git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all lfs ls-files -l e9386d1ad8884b2c49ee1d0fb39360fd24493da7 failed with exit code 1, output:
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
        log

ERROR: redsea-git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/windytan/redsea.git;protocol=http;branch=master;protocol=https')
ERROR: Logfile of failure stored in: /home/openatvbuilder/openatv7.4/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/redsea/git/temp/log.do_fetch.27249
ERROR: Task (/home/openatvbuilder/openatv7.4/build-enviroment/meta-oe-alliance/meta-oe/recipes-multimedia/redsea/redsea_git.bb:do_fetch) failed with exit code '1'

[log.do_fetch.27249.zip](https://github.com/user-attachments/files/16476293/log.do_fetch.27249.zip)

**Image/Box Model (please complete the following information):**
 - Version: 7.4
 - BoxModel: SF8008
 - Ubuntu 24.04

**Additional context**
On your side I see compilation is ok on https://images.mynonpublic.com/openatv/build_status_arm_74.html , I don't understand why I still have this error

**Comment by atvcaptain** [comment]
on your build host a tool is missing  see this commit : https://github.com/openatv/enigma2/commit/8b52f91d776530814d9a8c9ded011dfc27357332

**Comment by jeepcook** [comment]
Hello,
Sorry, I didn't see this commit.
Thanks for your answer.
Regards
