### ISSUE TITLE
Stream Relay issue

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3395]
There is a problem with ATV and Stream Relay that is only evident on Sky UK SD, it is not present on Sky DE.

Other images such as OBH dont have the issue either, its only ATV that has this problem.

Basically every 60 seconds or so we get a freeze and the oscam log states no data from stream source.

Here is the Enigma2 debug when this occurs. In this example the Oscam freeze happened at exactly 08.20.22

08:20:23.1302 [eDVBServiceStream] stop streaming m_state 2
08:20:23.1325 [eFilePushThreadRecorder] stopping thread.
08:20:23.1328 [eDVBRecordStreamThread] cancelling aio
08:20:23.1329 [eDVBRecordStreamThread] all done
08:20:23.1329 [eDVBRecordFileThread] waiting for aio to complete
08:20:23.1330 [eDVBRecordFileThread] buffer usage histogram (40 buffers of 192 kB)
08:20:23.1330 [eDVBRecordFileThread]   1:    118
08:20:23.1330 [eDVBRecordFileThread]   2:     97
08:20:23.1330 [eFilePushThreadRecorder] THREAD STOP
08:20:23.1332 [eDVBServiceStream] stop streaming m_state 0
08:20:23.1355 [eDVBCAService] free slot 0 demux 0 for service 1:0:1:1901:7E4:2:11A0000:0:0:0:
08:20:23.1356 [eDVBCAService] free service 1:0:1:1901:7E4:2:11A0000:0:0:0:
08:20:23.1369 [eDVBServiceStream] stream ref: 1:0:1:1901:7E4:2:11A0000:0:0:0:
08:20:23.1373 [eDVBResourceManager] use cached_channel, frontend=0
08:20:23.1373 [eDVBServicePMTHandler] allocate Channel: res 0
08:20:23.1373 [eDVBServiceStream] STREAM service event 13
08:20:23.1374 [eDVBCIInterfaces] addPMTHandler 1:0:1:1901:7E4:2:11A0000:0:0:0:
08:20:23.1375 [eDVBChannel] getDemux cap=01
08:20:23.1375 [eDVBResourceManager] allocate demux cap=01
08:20:23.1375 [eDVBResourceManager] allocating shared demux adapter=0, demux=0, source=0
08:20:23.1375 [eDVBServicePMTHandler] ok ... now we start!!
08:20:23.1376 [eDVBServiceStream] STREAM service event 5
08:20:23.1376 [eDVBCAService] new service 1:0:1:1901:7E4:2:11A0000:0:0:0:
08:20:23.1377 [eDVBCAService] add demux 0 to slot 0 service 1:0:1:1901:7E4:2:11A0000:0:0:0:
08:20:23.1381 [eDVBDemux] open demux /dev/dvb/adapter0/demux0
08:20:23.1382 [eDVBSectionReader] DMX_SET_FILTER pid=0
08:20:23.1386 [eDVBServiceStream] STREAM service event 6
08:20:23.1386 [eDVBServiceStream] tuned.. m_state 1 m_want_record 0
08:20:23.1387 [eDVBDemux] open demux /dev/dvb/adapter0/demux0
08:20:23.1388 [eDVBSectionReader] DMX_SET_FILTER pid=18
08:20:23.1391 [eDVBChannel] getDemux cap=00
08:20:23.1393 [eDVBRecordStreamThread] allocated 40 buffers of 192 kB
08:20:23.1398 [eDVBServiceStream] start streaming...
08:20:23.1399 [eDVBServiceStream] no cached pids found
08:20:23.1400 [eDVBServiceStream] have 1 video stream(s) (0213), and 1 audio stream(s) (02a1), and the pcr pid is 0213, and the text pid is 025208:20:23.1401 [eDVBServiceStream] ADD PID: 0000
08:20:23.1401 [eDVBServiceStream] ADD PID: 0012
08:20:23.1401 [eDVBServiceStream] ADD PID: 0014
08:20:23.1402 [eDVBServiceStream] ADD PID: 0213
08:20:23.1402 [eDVBServiceStream] ADD PID: 0252
08:20:23.1402 [eDVBServiceStream] ADD PID: 02a1
08:20:23.1410 [setIoPrio] realtime level 7 ok
08:20:23.1411 [eFilePushThreadRecorder] THREAD START
08:20:23.2436 [eDVBServicePMTHandler] PATready
08:20:23.2437 [eDVBServicePMTHandler] PAT TSID: 0x07e4 (2020)
08:20:23.2438 [eDVBServicePMTHandler] use pmtpid 011c for service_id 1901
08:20:23.2438 [eDVBDemux] open demux /dev/dvb/adapter0/demux0
08:20:23.2439 [eDVBSectionReader] DMX_SET_FILTER pid=284
08:20:23.2443 [eDVBDemux] open demux /dev/dvb/adapter0/demux0
08:20:23.2443 [eDVBSectionReader] DMX_SET_FILTER pid=0
08:20:23.3844 [eDVBServiceStream] STREAM service event 5
08:20:23.3845 [eDVBServiceStream] start streaming...
08:20:23.3846 [eDVBServiceStream] no cached pids found
08:20:23.3846 [eDVBServiceStream] have 1 video stream(s) (0213), and 2 audio stream(s) (02a2, 02a1) (0252), and the pcr pid is 0213, and the text pid is 025208:20:23.3848 [eDVBServiceStream] ADD PID: 011c
08:20:23.3851 [eDVBServiceStream] ADD PID: 02a2
08:20:23.3853 [eDVBServiceStream] ADD PID: 0510
08:20:23.3855 [eDVBCIInterfaces] gotPMT
08:20:23.3856 [eDVBCAService] don't build/send the same CA PMT twice
08:20:23.3857 [eDVBDemux] open demux /dev/dvb/adapter0/demux0
08:20:23.3858 [eDVBSectionReader] DMX_SET_FILTER pid=284
08:20:25.0714 [eDVBDemux] open demux /dev/dvb/adapter0/demux0
08:20:25.0716 [eDVBSectionReader] DMX_SET_FILTER pid=18

Full log attached bellow. But basically something within ATV is stopping the relay stream and forcing it to have to restart again. I repeat other images with the exact same config files work perfectly.

**Comment by ian10951** [comment]
[20240806-081627-enigma2-debug.log](https://github.com/user-attachments/files/16506873/20240806-081627-enigma2-debug.log)

**Comment by jbleyel** [comment]
Someone or something is calling this:

`RESULT eDVBServiceStream::stop()
`

**Comment by ian10951** [comment]
Yes something within the ATV image is calling it, but there is nothing in the logs to indicate what, all the logs show is that it is happening.

**Comment by jbleyel** [comment]
> [20240806-081627-enigma2-debug.log](https://github.com/user-attachments/files/16506873/20240806-081627-enigma2-debug.log)
> 
> @ jbleyel or Captain
> 
> I can give you access to an 0963 card if you wish to test and see this for yourselves.

This won't work because we are in Germany.

**Comment by ian10951** [comment]
So you dont have a motorised dish ?

**Comment by jbleyel** [comment]
> So you dont have a motorised dish ?

No. Only Astra 19.2

**Comment by ian10951** [comment]
Oh Ok, thats a shame.

I've tried to compare the differences between OBH Stream Relay commits which works properly and ATV Stream Relay commits that doesnt, but sadly its above my paygrade. From what I can see though both images do it very differently.

**Comment by jbleyel** [comment]
The c++ streaming part is exactly the same on ATV and OBH.
Are you using the exact same version of OS cam on ATV and OBH?

**Comment by ian10951** [comment]
Yes identical and identical config files too.

**Comment by jbleyel** [comment]
Then I'm lost. Sorry.

**Comment by ian10951** [comment]
Ok thanks for trying.

I really didnt want to switch the OBH like others have done in order to have working Stream Relay for 28E, prefering instead to try to get it sorted in ATV, but alas its seems I now have little choice. I do appreciate your time spent on this though.

**Comment by betacentauri** [comment]
Can you provide an oscam log (with a matching e2 log)?

**Comment by jbleyel** [comment]
Please send me PM in ATV Forum with the Data and stop here.

**Comment by ian10951** [comment]
I cant figure out how to find you on the forum to send you a PM lol

So here are the logs you requested. Both E2 log and Oscam log.

The error and freeze happened at 17.34.34
[20240819-173201-enigma2-debug.log](https://github.com/user-attachments/files/16663085/20240819-173201-enigma2-debug.log)
[oscam.log](https://github.com/user-attachments/files/16663087/oscam.log)
