### ISSUE TITLE
Timeshift Position is incorrect on initial show

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#3411]
TimeshiftState screen (metrix hd) uses  serviceposition coverter to show where you are in the timeshift.

`			<convert type="ServicePosition">Position</convert>`

If you have timeshift turned off, but only enabled when you press pause. 
When Pause is pressed on live tv. The initial Position is completely wrong. and remains wrong. See screen shot. 

![image](https://github.com/user-attachments/assets/72cfa098-688c-4d5f-94a5-8c487c44e697)

But if you press play the number corrects itself. If your press pause again. The position is correct. 

![image](https://github.com/user-attachments/assets/fced021a-f718-4780-82b4-1081aeed3c3d)

This also effect "remaining" as it uses position in its calculations

**Comment by wedebe** [comment]
I logged this [exactly a year ago](#3039) (and it was already a bug for quite a while back then.

**Comment by kiddac** [comment]
I currently haven't got 2 boxes up and running at the moment. 
So I can't compare openatv 7.3 to openatv 7.4
But looking through all the commits in the last 12 months. It seems every file and screen is being initialised when engiam2 starts. Rather than when the file or screen is used. I think this is resulting in everything being wrongly initialised at the wrong point. 

I don't know the inner working of all this new startengima work, but my attention seems to think it might be something to do with processing.py which was added 9 months ago.
