### ISSUE TITLE
Include exFAT support by default?

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#3413]
exFAT is a popular filesystem format for pendrives and memory cards, Microsoft opened the spec in 2019 and [has been supported natively in Linux from kernal 5.4](https://en.wikipedia.org/wiki/ExFAT#Adoption)

Plugin `enigma2-plugin-drivers-exfat (1.0-r0)` adds support for the exFAT filesystem, but it would be great to have out-of-the-box support built into E2 images for a better user experience (many users won't know why their stick doesn't "just work") when they plug it in, or how to find the plugin they need. Mention exfat and they'd probably think of an obese former partner.

**Comment by jbleyel** [comment]
Sorry. This is wrong here.
Your other issue about this is on the correct git.
