### ISSUE TITLE
Infobargenerics.py broken bouquets list

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#3414]
First reported on opena.tv forum
https://www.opena.tv/viewtopic.php?t=66226

this code is what is causing the broken bouquets lists
Infobargenerics.py

```
def openBouquetEPG(self, bouquet=None, bouquets=None):
        if bouquet:
            self.StartBouquet = bouquet
        elif bouquets and not self.servicelist.isSubservices():  # Current service not found in any bouquet so add all services
            root = self.servicelist.getRoot()
            bouquets.insert(0, (self.servicelist.getServiceName(root), root))

        self.dlg_stack.append(self.session.openWithCallback(self.closed, EPGSelection, None, zapFunc=self.zapToService, EPGtype=self.EPGtype, StartBouquet=self.StartBouquet, StartRef=self.StartRef, bouquets=bouquets))
```
        
which gives this bouquet list and breaks things. Basically its duplicating the current bouquet at the begininng of the list.
        
![image](https://github.com/user-attachments/assets/e505cd8a-494f-4a2a-ad6b-30e59a9c7054)

where as if you remove the conditional subservice code it works perfectly fine. 

```
def openBouquetEPG(self, bouquet=None, bouquets=None):
        self.dlg_stack.append(self.session.openWithCallback(self.closed, EPGSelection, None, zapFunc=self.zapToService, EPGtype=self.EPGtype, StartBouquet=self.StartBouquet, StartRef=self.StartRef, bouquets=bouquets))
```

![image](https://github.com/user-attachments/assets/196ea9df-2763-4431-b568-1a79c06fba14)

**Comment by kiddac** [comment]
You might want to look at all your subservice work and see what else it broke.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/80f8e8a14e9305e619148a182dc33a88ab1ead56

**Comment by urie57** [comment]
> [80f8e8a](https://github.com/openatv/enigma2/commit/80f8e8a14e9305e619148a182dc33a88ab1ead56)
> 
> #2717

So are you referring to commits that have caused the problem,

Or will this ever be fixed 5 months now at least if we edit infobargenerics.py with @kiddac edits we can get it working on 7.4 and 7.5 but not really practical in the long run.

**Comment by jbleyel** [comment]
It will be fixed but it’s not that easy because @kiddac suggestion will break Subservice support.

**Comment by urie57** [comment]
@jbleyel thanks

**Comment by kiddac** [comment]
Subservice isn't even a thing on 28.2e UK sat. 
It seems a hell of  lot of effort seems to be put in and a serious amount of code change for a very minor thing that I assume is useless for the majority of your global users. 
Maybe one person asked for this change. 

I don't see the need of a subservice to be such a major thing. Its even taken over the green button??? Which I had to dig through all the settings to undo.

**Comment by jbleyel** [comment]
I think you are wrong.
The Subservices are frequently used and we have removed a lot of extra code because the new implementation is using the standard ChannelSelection and not extra Screens.
