### ISSUE TITLE
Ustym 4K Pro: ok.ru plugin streamlink Openatv 7.4,7.5 Enigma 2 offline python 3.12

### ISSUE THREAD

**Issue by Andrew135815** [openatv/enigma2#3417]
Hello,ok.ru.py python 3.12.Ustym 4K Pro OpenaTV 7.4/7.5 not working Enigma 2 offline,please help,important..: streamlinksrv manualstart debug

File "/usr/lib/python3.12/site-packages/streamlink/utils/module.py", line 34,
in exec_module
spec.loader.exec_module(mod)
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "/usr/lib/python3. File "", line 488, in call_with_frames_removed
File "/usr/lib/python3.12/site-packages/streamlink/plugins/vtvgo.py", line 13
in
from streamlink.plugin.api.webbrowser.aws_waf import AWSWAF
File "/usr/lib/python3.12/site-packages/streamlink/plugin/api/webbrowser/aws
af.py", line 6, in
import trio
import trio
ModuleNotFoundError: No module named 'trio'
[streamlinksrv][debug] Arguments:
[streamlinksrv][debug] url=https://mobile.ok.ru/video/351615524467
[streamlinksrv][debug] stream=['best']
[streamlinksrv][info] Found matching plugin for URL https://mobile.ok.ru/video
351615524467
351615524467
[streamlinksrv][error] Unable to validate response text: ValidationError(xml_fin
d):
ElementPath query './/a[@data-video]' did not return an element
[streamlinksrv][debug] Send Offline clip

**Comment by ian10951** [comment]
Have you tried ?

opkg install python3-trio

Or if its not on the feeds you can install the ipk

**Comment by Andrew135815** [comment]
Yes.Unfortunately, it doesn't work that way either.Please help.ok.ru py plugin amendment??

**Comment by jbleyel** [comment]
This is not an enigma issue.

**Comment by Andrew135815** [comment]
Please help not working

**Comment by Andrew135815** [comment]
> ian10951

Ian Please help
