### ISSUE TITLE
EMC crashes the box when no info is found

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#3418]
I think EMC needs an exception adding for when no info is found on the TMDb database.

10:49:39.0504 Traceback (most recent call last):
10:49:39.0506   File "/usr/lib/enigma2/python/skin.py", line 2221, in processScreen
10:49:39.0506   File "/usr/lib/enigma2/python/skin.py", line 2148, in processWidget
10:49:39.0507 skin.SkinError: [Skin] Error: Converter 'MovieBarInfo' not found!
10:49:53.4367 [eDVBPESReader] Created. Opening demux
10:49:53.4369 [eDVBPESReader] Created. Opening demux
10:54:49.6162 Traceback (most recent call last):
10:54:49.6165   File "/home/oe1/atv7.4/build-enviroment/builds/openatv/release/h9combose/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-enhancedmoviecenter/4.0.+git/image/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieInfo.py", line 332, in updateSelection
10:54:49.6235   File "/home/oe1/atv7.4/build-enviroment/builds/openatv/release/h9combose/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-enhancedmoviecenter/4.0.+git/image/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieInfo.py", line 64, in getMovieInfo
10:54:49.6239   File "/usr/lib/python3.12/site-packages/tmdbsimple/movies.py", line 73, in info
10:54:49.6247   File "/usr/lib/python3.12/site-packages/tmdbsimple/base.py", line 110, in _GET
10:54:49.6258   File "/usr/lib/python3.12/site-packages/tmdbsimple/base.py", line 105, in _request
10:54:49.6263   File "/usr/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
10:54:49.6306 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/movie/1337575?language=en&api_key=8789cfd3fbab7dccf1269c3d7d867aff
10:54:49.6341 [ePyObject] (PyObject_CallObject(<bound method MovieInfoTMDb.updateSelection of <class 'Plugins.Extensions.EnhancedMovieCenter.MovieInfo.MovieInfoTMDb'>>,()) failed)

**Comment by jbleyel** [comment]
Fixed in EMC
