### ISSUE TITLE
Remote control button labels mix up with Enigma menu strings

### ISSUE THREAD

**Issue by dikonov** [openatv/enigma2#3422]
**Describe the bug / Actual behaviour:**
I work to improve the 'ru' translation of the Enigma GUI and notice that the strings used to represent named Remote control buttons such as "TV" "AUDIO" "TEXT" "SUBTITLE" "MEDIA" etc. coinside with some menu items and other GUI elements.  The button names also appear in the menu as such, e.g. when functions are assigned to buttons. 

The problem is that the physical Remote buttons are labeled in English-Latin script and should be referred to using these English labels. On the othe hand, the coinsiding GUI items, e.g. MainMenu > Settings > "Audio" or "TV" in the TV channel list header must by translated. The translated strings use a different script and have little in common with the physical button labels. The GUI uses one single string for both cases and there is no good way out. Both translating them and leaving as-is are bad choices. 

**Expected behaviour:**
"Audio", "TV", "Text" other button names should be displayed as printed on the physical remote control.
"Audio", "TV", etc. as menu items and GUI labels should be translated.  

**Has this issue started to happen just recently?**
Bug exists since the code got written. 

**To reproduce:**
1. Change GUI language to any language that uses non-Latin script.
2. Just look at the menus.

**Image/Box Model (please complete the following information):**
 - Version: 7.4
 - BoxModel: any

**Additional context**

**Comment by miguellords** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by dikonov** [comment]
What is this? Why dlls? This is not a windoze OS.

**Comment by IanSav** [comment]
Can you please provide some examples of the issue.  You are the first to comment about inappropriate translations.  We need to better understand your issue before anything can be done.

**Comment by dikonov** [comment]
Here is a screenshot of the MainMenu > Settings > Usage & GUI > Remote Control button Settings

![ButtonsVSmenus](https://github.com/user-attachments/assets/859cb2b5-1979-4bd5-a00e-f72a3db5cfe5)

**Comment by dikonov** [comment]
A more general remark is that all Remote buttons are simply named in the GUI strings even without qoutes. It may create ambiguities. Arrow keys are commonly mentioned as "Left/Right" "Up/Down": "Long Left/Right", "Add legacy LEFT/RIGHT actions" etc.

Why not use mandatory quotes for ALL physical button names and 
Unicode pictograms for the arrow and multimedia keys instead? I tested  "▶▶"  instead of ">>" fro the fast-forward button label and it both works and looks better.

**Comment by IanSav** [comment]
All buttons should be shown as all uppercase.  So in text the buttons are LEFT, RIGHT, UP and DOWN.

This is what my screen looks like.  It is nothing like what you posted:
![Remote](https://github.com/user-attachments/assets/1b1d3bf2-7abb-48f8-a7a3-ecb4f6fca565)

The remote control button labels for the remote control help are not be translated.  The strings should exactly match the text on the remote controls.  I have avoided some of icons as they are not available in all character sets.  There are also some extreme complications trying to mix text and icons.

If you are talking about the Hotkey Settings screen then that has not yet been refactored so I am unsure how that may change.

If I have not addressed your issue then please explain it with more examples and a more detailed explanation.

**Comment by jbleyel** [comment]
Please check this -> https://github.com/openatv/enigma2/pull/3423/commits/192ecca7a852c9b1e1622ce54152d6badd765ae4

**Comment by dikonov** [comment]
> Please check this -> [192ecca](https://github.com/openatv/enigma2/commit/192ecca7a852c9b1e1622ce54152d6badd765ae4)

This should fix that particular menu!

As for my suggestion, these symbols are NOT icons. The ⯅⯆⯇⯈   ⏩⏪⏯ ⏸⏹⏺⏏  ⏻⏼  are regular text characters thart can be used alongside alphanumeric symbols without any special considerations. They are part of the Unicode standard and cover all essential pictograms of the remote controls. Using them would make long Enigma menus more concise and more readable. The default font and skin support such symbols out of the feed.
