### ISSUE TITLE
Some GUI strings are not available for translation

### ISSUE THREAD

**Issue by dikonov** [openatv/enigma2#3425]
**Describe the bug / Actual behaviour:**
Some GUI strings that should be translated are not found in the Weblate Enigma transalation project. There are some Audio Setting options and strings related to the bundled-default plugins (FanControl, Password changer, Enchanced MediaCenter).

**Expected behaviour:**
It should be possible to either find the strings in the main Enigma.po or the auxiliary plugin pos. However  they are not included there and remain untranslated and unreadable for non-English speakers.

**To reproduce:**
1. Switch to any 100% translated locale.
2. Open the Main Menu, Audio Settings, Usage and Interface settings. 
3. Look for strings that remain English (except for the physical button names)
4. 
**Screenshots**
Audio Settings menu
![missing_audiosettings](https://github.com/user-attachments/assets/16bbe369-5938-4a2f-a3d3-f6d35c0af6f2)

Two bundled plugins
![missing_plugins](https://github.com/user-attachments/assets/535116a6-af1a-4c2f-a9fd-af21ffce1b2a)
I cannot even find these strings in the code downloaded from the git. 

![missing_emc](https://github.com/user-attachments/assets/d5520b2e-fa21-48dd-8c4c-194e4e3df878)
This string cannot be treated as a brand-name. It must be translatable too. 

**Image/Box Model (please complete the following information):**
 - Version: 7.4. Latest update at 22.09.2024
 - BoxModel: Sezam Marvel   (it has a fan to control)

**Additional context**
I feel buffled by the fact that some strings related to the bundled optional plugins (e.g. Youtube, smth called IceTV, AI-subtitles) are included into the main .po file while some other plugins (FanControl, PasswdChanger), which perform basic system functions are not included.

**Comment by dikonov** [comment]
In addition I noticed that there are some TRANSLATED strings with typos that come neither from openatv-enigma2-7-0-po-ru.po nor from openatv-metrixhd-ru.po. Is there some other source of localized GUI strings in the system? 

I did not install any skins or side packages that might change the default Enigma GUI. All textual changes of the menu are done by replacing the sigle file /share/enigma2/po/ru/LC_MESSAGES/enigma2.mo

**Comment by dikonov** [comment]
![missing_blindscan](https://github.com/user-attachments/assets/7f453251-d13d-4be6-a3d7-1e085ddd269d)
The blind scan function is non-translatable, also the necessary strings are present in the .po.

**Comment by jbleyel** [comment]
> ![missing_blindscan](https://private-user-images.githubusercontent.com/4271322/369699466-7f453251-d13d-4be6-a3d7-1e085ddd269d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjU2NDEsIm5iZiI6MTcyNzAyNTM0MSwicGF0aCI6Ii80MjcxMzIyLzM2OTY5OTQ2Ni03ZjQ1MzI1MS1kMTNkLTRiZTYtYTNkNy0xZTA4NWRkZDI2OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTcxNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDcxMzFhZTlkNDViMzY3OWY5ZGYxYzdkNDZiNzNmOTEyZTIxZWFjYzJkMGIwODQ1ZjZkMjNjZDkzY2QyY2YyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.L9iHaxSFInplIm54NtYLdN1MfxbAFVfiRhwwV1gGXe0) The blind scan function is non-translatable, also the necessary strings are present in the .po.
> 
> https://github.com/oe-alliance/oe-alliance-plugins/tree/master/Blindscan/po Is it the right source to edit?

yes

**Comment by jbleyel** [comment]
The enigma2 translation will be updated from time to time based on weblate.
The plugin translation is separated if the plugin is not in the enigma2 git.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/101ec395be680a53c4ae7644abf341a386f491d4

**Comment by jbleyel** [comment]
By the way .. The name "Enhanced Movie Center" will be not translated is any language.
This is by design.

**Comment by dikonov** [comment]
> By the way .. The name "Enhanced Movie Center" will be not translated in any language. This is by design.

Imagine that part of the menu in _your_ box is written in arabic. You do not know how to read it and you cannot change it. Would you approve such "design"?

Some users are not able to read the alphabet used in this English-only name. Even those that know the letters cannot pronounce it and do not understand its meaning.

**Comment by dikonov** [comment]
> The enigma2 translation will be updated from time to time based on weblate. The plugin translation is separated if the plugin is not in the enigma2 git.

I cannot find the FanControl and Passord Changer plugins. They appear to be part of the main tree (there are alternative plugins for Fan Control, but these are different) BUT the exact strings the two plugins use are nowhere to be seen. I tried adding "FAN Control" to the Enigma .po manually to no avail.

**Comment by IanSav** [comment]
> Enigma has a very bad reputation among satellite tradesmen (I mean people who sell and install sat equipment) because of cryptic menus. I met people who are not able to use it even though they are pros and recommned clients to never touch Enigma boxes.

Have they used the HELP functions that have been added to OpenATV?  The help system is being expanded to all code under direct control of OpenATV.  Some of the code/plugins about which you are complaining are not directly managed by the OpenATV team.

**Comment by jbleyel** [comment]
> > The enigma2 translation will be updated from time to time based on weblate. The plugin translation is separated if the plugin is not in the enigma2 git.
> 
> I cannot find the FanControl and Password Changer plugins. They appear to be part of the main tree (There are alternative plugins for Fan Control, but these are different), BUT the exact strings the two plugins use are nowhere to be seen. I tried adding "FAN Control" to the Enigma .po manually to no avail.

https://github.com/oe-alliance/enigma2-plugins

**Comment by jbleyel** [comment]
The translation of the plugin name in menu or in other parts of enigma is not possible for some plugins. We need to fix this first before we can add the translation of this name.

**Comment by wedebe** [comment]
> > Enigma has a very bad reputation among satellite tradesmen (I mean people who sell and install sat equipment) because of cryptic menus. I met people who are not able to use it even though they are pros and recommned clients to never touch Enigma boxes.
> 
> Have they used the HELP functions that have been added to OpenATV? The help system is being expanded to all code under direct control of OpenATV. Some of the code/plugins about which you are complaining are not directly managed by the OpenATV team.

Help should merely be there to add extra instructions or details for a function, action, or feature. It should never be necessary for an end user/consumer to find a help article to explain what a button/menu item/etc... _does_. 

Granted, there's been a lot of work done on translations by various people, but there's still plenty of obtuse text, technical/linuxish jargon, lateral translations from (eg.) German and other linguistic quirks which put non-computer-minded people off using openATV (amongst other enigma2 images). It's something I've tried to lend my hand to but is incredibly time-consuming.

**Comment by wedebe** [comment]
> The enigma2 translation will be updated from time to time based on weblate. The plugin translation is separated if the plugin is not in the enigma2 git.

I think any plugins bundled with openATV by default should be moved into the enigma2 repo, the translations handled by each plugin, and those translations (where not used elsewhere in openATV) be removed from openATV po files. The current situation is very messy when it comes to having the most up-to-date text in the right place (those plugins would likely be used in other e2 images).

**Comment by jbleyel** [comment]
> > The enigma2 translation will be updated from time to time based on weblate. The plugin translation is separated if the plugin is not in the enigma2 git.
> 
> I think any plugins bundled with openATV by default should be moved into the enigma2 repo, the translations handled by each plugin, and those translations (where not used elsewhere in openATV) be removed from openATV po files. The current situation is very messy when it comes to having the most up-to-date text in the right place (those plugins would likely be used in other e2 images).

NO

**Comment by IanSav** [comment]
The point of the HELP button is NOT to provide a user manual on Enigma2 but rather to provide the current meanings of the currently available options.  That is, this is context sensitive help.

Improving the language and grammar is very time consuming.  It also triggers various differences of opinion.  All of Enigma2 can be improved with a language refinement.  Unfortunately there have been no volunteers prepared to take on the task correctly.

**Comment by IanSav** [comment]
> I think any plugins bundled with openATV by default should be moved into the enigma2 repo, the translations handled by each plugin, and those translations (where not used elsewhere in openATV) be removed from openATV po files. The current situation is very messy when it comes to having the most up-to-date text in the right place (those plugins would likely be used in other e2 images).

Some of the system plugins that are core to Enigma2 are slowly being integrated into the main code.  This will now work for all plugins.

**Comment by dikonov** [comment]
> > > Enigma has a very bad reputation among satellite tradesmen (I mean people who sell and install sat equipment) because of cryptic menus. I met people who are not able to use it even though they are pros and recommned clients to never touch Enigma boxes.
> > 
> > 
> > Have they used the HELP functions that have been added to OpenATV? The help system is being expanded to all code under direct control of OpenATV. Some of the code/plugins about which you are complaining are not directly managed by the OpenATV team.
> 
> Help should merely be there to add extra instructions or details for a function, action, or feature. It should never be necessary for an end user/consumer to find a help article to explain what a button/menu item/etc... _does_.
> 
> Granted, there's been a lot of work done on translations by various people, but there's still plenty of obtuse text, technical/linuxish jargon, lateral translations from (eg.) German and other linguistic quirks which put non-computer-minded people off using openATV (amongst other enigma2 images). It's something I've tried to lend my hand to but is incredibly time-consuming.

I second that. A lot of menu items and settings are not clear for average person even without the language barriers.

Sometimes translating them is in a more explanatory way is impossible because of the string length limits (text gets cut, obscured by other GUI elements or exceeds its designated area, like button labels bigger than the buttons themselves). 

Sometimes the original English wording is too abstract, which enable the same string to be used in different contexts, which in turn require different translations, e.g. "Deleted items" (There is no single word that would fit here as a translation of the word "item". I cannot be more specific because an "item" can be many different things in different contexts). "Go to first movie or last item" had to be translated as "Go to the first or the last movie" even though I am aware that theoretically the code might allow "the last item" to be a folder or smth else.

There are some specific Enigma-only terms like "bouquet", "picon", which sound not quite appropriate for neutral technical style. "Plugin" is a very bad term for Russian translation, because any equivalents which are not marked as IT-slang are multiword (and do not fit the length limits) and/or are too generic.

**Comment by jbleyel** [comment]
Hi @dikonov , the enigma internal strings can be well translated but we need to know if there is an English text block which is not absolutely clear.

The space usage is more like a skin problem.
Dynamic text sizes are probably possible but not that easy to implement.
