### ISSUE TITLE
Does it work on  device with hi3716mv430 ?

### ISSUE THREAD

**Issue by projectcad** [openatv/enigma2#3434]
When it is directly build from this source.. Does it work on any device with hi3716mv430 ?

**Comment by atvcaptain** [comment]
430 only works with zgemma h8 the device have enigma2 drivers

https://github.com/oe-alliance/oe-alliance-core/blob/5.4/meta-brands/meta-airdigital/conf/machine/h8.conf

**Comment by projectcad** [comment]
thanks...
