### ISSUE TITLE
Skin_display_picon 400x240 Display Tuner letters fix

### ISSUE THREAD

**Issue by urie57** [openatv/enigma2#3443]
Can edits from this post https://www.opena.tv/viewtopic.php?t=65008&start=80#p569156
be added to Skin_display_picon 400x240 for openatv 7.4 and 7.5 to fix tuner letters not displaying in LCD 
Also if possible changes since 7.3 means when recording ,
flashing symbol that did diplay on 7.3 in top right hand corner. That has been moved in openatv 7.4 does not display

**Comment by jbleyel** [comment]
@Makumbo : can you please take over?

**Comment by Makumbo** [comment]
I'm working on it.
Needs time...

**Comment by urie57** [comment]
> I'm working on it. Needs time...

Apreciated I know these take time you mentioned before

**Comment by Makumbo** [comment]
@jbleyel: Bin immernoch dran...

Dabei ist mir aufgefallen, dass beim Sendersuchlauf, Aufruf mit "**ServiceScanSummary**",
die Überschrift "_**Kanalsuche**_" **nicht** mehr wie früher erscheint, und der Fortschrittsbalken
**leer** bleibt (die Sendernamen darunter werden aber angezeigt)!

Kannst Du da mal nachschauen?

Danke - Makumbo

**Comment by Makumbo** [comment]
Danke fürs fixen!

**Comment by urie57** [comment]
I thank you both it may seem like a sillly request started with tuner letters not shown then went to recording symbol. And did not realise how much work is involved @Makumbo I did download the openatv-7.4-vuduo4k-20240814_usb image and yes you did have lots of helpfull comments in skin_display_picon.xml but I did have to try and convert all comments to english via google translator, 
And as some will know not always best even when posting on openatv forum. :)

**Comment by Makumbo** [comment]
The comments are in german, so I know (later) what happend there.
But the "old" parameters are still there, so that you know what has changed - I hope...

**Comment by Makumbo** [comment]
@jbleyel and @IanSav
The ServiceScan in 7.4 from 28th is OK now - But only on the Box LCD.
Thanks for that.

But on screen the progress bar has to be lower - 20 Pixel lower.
The "g" in german "Durchgang" protrudes into the bar (protrudes?) - see screenshot.
If the bar is 20 pixels lower, then the bar is exatly positioned between the
"Durchgang/Pass" text and the upper of the first channelname...

![ServicScanBar](https://github.com/user-attachments/assets/35707825-034d-4fc2-8582-888a1f9b2776)

**Comment by jbleyel** [comment]
> @jbleyel and @IanSav The ServiceScan in 7.4 from 28th is OK now - But only on the Box LCD. Thanks for that.
> 
> But on screen the progress bar has to be lower - 20 Pixel lower. The "g" in german "Durchgang" protrudes into the bar (protrudes?) - see screenshot. If the bar is 20 pixels lower, then the bar is exatly positioned between the "Durchgang/Pass" text and the upper of the first channelname...
> 
> ![ServicScanBar](https://private-user-images.githubusercontent.com/38384409/380942412-35707825-034d-4fc2-8582-888a1f9b2776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODI2ODQsIm5iZiI6MTczMDE4MjM4NCwicGF0aCI6Ii8zODM4NDQwOS8zODA5NDI0MTItMzU3MDc4MjUtMDM0ZC00ZmMyLTg1ODItODg4YTFmOWIyNzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA2MTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMWQxZWM3ZmFiMTZkMDIwZGNmOWE1OWUwNmFhOTMwMmFkZWFiMTg2NDdjYWFhNzNlODI2YjU5MTJjYWU0N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GA9lqtH_FqqJMAxOaweSFqSOvfeh4d7Uc2UftXSPA2E)

This needs to be changed in Metrix.

**Comment by Makumbo** [comment]
**400x240 Skin - optimized by Makumbo:**

Some of the new things:

Kept old comments but extended them, so you can see what exatly is going on.

Tunerletter at recordings in color red.

"REC" sign blinking (or constantly) centered on the progressbar
and centered between clock and date at standby.

MoviePlayer (if EnhancedMovieCenter is UNinstalled)
and EMCMoviePlayer same depiction - also at film selection.
Also here the "REC" sign blinking (or constantly) centered on the progressbar.

Progressbars gray; not so intrusive.

Preview images "prev" and "piconprev" new.

If you think of anything else or notice anything else, let me know...

[400x240 Skin 2024-11-03.zip](https://github.com/user-attachments/files/17610645/400x240.Skin.2024-11-03.zip)

**Comment by urie57** [comment]
@Makumbo , everything looking good and the progressbar in grey does make a difference : ) and also tuner letter trurning from gree to red.

Do you think you edits are now complete ? and if so will these be added to github to be included in images eventually.

**Comment by Makumbo** [comment]
> Do you think you edits are now complete ? and if so will these be added to github to be included in images eventually.

I could not testet all "screen=", but I made drawings with the coordinates etc. and so I saw, if and where the elements would be displayed - with the coordinates before and than with mine.

An Example from  "PackageActionSummary":
eLabel position="28,**368**" ...
eLabel position="58,**393**" ...

Yeah, right - y-position 368 or 393 on a display that ist only **240** pixel high... 

If you find any faults - tell me ;)

--

I hope that @jbleyel will put it in github and so make it available for all receivers with the 400x240 skin...

--

@jbleyel: screen name="**ChoiceBoxSummary**" (z.B. bei "Filmwiedergabe beenden") ist die einzige Funktion, die mich massiv stört!
Beim Bewegen des Cursors nach unten wandert ab dem dritten Mal der komplette Text nach oben - sieht furchtbar aus.

**Comment by urie57** [comment]
@Makumbo , not sure if iptv is allowed to be discussed but when playing stream normally start and end times are ok display screen is ,

![Capture main](https://github.com/user-attachments/assets/ad514d5c-2fa4-4b84-a9c0-71611572aadc)

But when playing same stream via xtreamity or xklass display is start and end times are the same

![Capture-xtreamity](https://github.com/user-attachments/assets/ea91eee7-950e-475b-873f-336a1bcf2c2d)

I have mentioned to @Kiddac on linuxsat 
https://www.linuxsat-support.com/thread/134771-skin-support-post-questions-for-all-my-skins-in-here/?postID=832255#post832255
but he does not have an stb with lcd display to test

**Comment by Makumbo** [comment]
Sorry - I do not know anything about streams.

Maybe they dont hand over the times to the skin.
In the first shot there is no tuner letter - also not handed over?

**Comment by urie57** [comment]
> Sorry - I do not know anything about streams.
> 
> Maybe they dont hand over the times to the skin. In the first shot there is no tuner letter - also not handed over?
No worrins yes no tuner letter not expecting one because via internet but could be something needing changed in plugin
thanks for replying

**Comment by Makumbo** [comment]
"They" will have to provide ( I think)

convert type="EventTime">**StartTime**</convert>
convert type="EventTime">**EndTime**</convert>
convert type="EventTime">**Remaining**</convert>

See
`<screen name="InfoBarSummary" position="0,0" size="400,240">`
in
"skin_display_picon.xml".

**Comment by jbleyel** [comment]
> @jbleyel: Baust Du den 'neuen' Skin ein?

Welchen Skin?

**Comment by Makumbo** [comment]
Na, den **400x240 Skin 2024-11-03.zip** von weiter oben.
Ist der komplett überarbeitete (weil urie57 'gemeckert' hat) ;)
400x240er Standard LCD Skin.

**Comment by Makumbo** [comment]
Danke!
Werde Vergleichsbilder alt/neu ins Forum stellen...
