### ISSUE TITLE
Timeshift in wrong destination

### ISSUE THREAD

**Issue by rchovan** [openatv/enigma2#3446]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.

**Describe the bug / Actual behaviour:**
Timeshift recordings are places in wrong destination. I can change path in GUI, but timeshift recordings are still stored in wrong destination. Tried reboot, etc.. This issue started with OpenATV 7.4 versions. Tried to wait for solving this issue, but so far no issue created for it.

**Expected behaviour:**
Place timeshift recordings in selected destination.

**Has this issue started to happen just recently?**
This issue started with OpenATV 7.4 versions

**To reproduce:**
Here are my settings for timeshift 
```
root@xpeedlx3:/etc/enigma2# grep timeshift settings 
config.timeshift.allowedPaths=['/media/hdd/movie/satelit/TimeShift/', '/media/hdd/timeshift/']
config.timeshift.autorecord=True
config.timeshift.checkEvents=15
config.timeshift.checkFreeSpace=8192
config.timeshift.favoriteSaveAction=noSave
config.timeshift.maxEvents=20
config.timeshift.maxHours=24
config.timeshift.path=/media/hdd/timeshift/
config.timeshift.startDelay=5
config.timeshift.stopWhileRecording=True
config.usage.allowed_timeshift_paths=['/media/hdd/timeshift/', '/media/hdd/movie/', '/media/hdd/movie/TimeShift/', '/media/hdd/movie/satelit/TimeShift/']
config.usage.timeshift_path=/media/hdd/movie/satelit/TimeShift/

```

In selected path are some files created 

root@xpeedlx3:/media/hdd/timeshift#  ls -l

```
-rw-------    2 root     root     2080677404 Oct 27 18:10 pts_livebuffer_1
-rw-r--r--    1 root     root           933 Oct 27 17:04 pts_livebuffer_1.eit
-rw-r--r--    1 root     root           911 Oct 27 17:04 pts_livebuffer_1.meta
-rw-r--r--    1 root     root             0 Oct 27 17:04 pts_livebuffer_1.sc
```

But main files are in wrong directory **'/media/hdd/movie/satelit'**

```
-rw-------    1 root     root      10521232 Oct 27 17:00 20241027 1700 - Nickelodeon CZ - 
-rw-r--r--    1 root     root           165 Oct 27 17:00 20241027 1700 - Nickelodeon CZ - 
-rw-------    1 root     root        319036 Oct 27 17:01 20241027 1701 - JimJam CZ -  
-rw-r--r--    1 root     root           697 Oct 27 17:01 20241027 1701 - JimJam CZ -
-rw-------    1 root     root       7935104 Oct 27 17:01 20241027 1701 - Nickelodeon CZ - 
-rw-r--r--    1 root     root           165 Oct 27 17:01 20241027 1701 - Nickelodeon CZ - 
-rw-------    1 root     root       8095844 Oct 27 17:04 20241027 1703 - JimJam CZ - 
-rw-r--r--    1 root     root           697 Oct 27 17:03 20241027 1703 - JimJam CZ - 
-rw-------    2 root     root     2080677404 Oct 27 18:10 20241027 1704 - HBO HD CZ -
-rw-r--r--    1 root     root           921 Oct 27 17:04 20241027 1704 - HBO HD CZ - 
```

**Screenshots**
Not needed

**Image/Box Model (please complete the following information):**
 - Version:  openATV 7.4.20241006 (2024-10-05)
 - BoxModel: Golden Interstart XPEED LX-3

**Additional context**

**Comment by Papi2000-new** [comment]
You have some config errors in your image.
Setup clean after a new flash without restoring any old informations.
If those definitiones and names change in a new image version, the image does NOT clean-up old values itself.
Delete the unwanted directory '/media/hdd/movie/satelit' includinf the subdirectory 'Timeshift'.

config.timeshift.path=/media/hdd/timeshift/
...
config.usage.timeshift_path=/media/hdd/movie/satelit/TimeShift/
looks bad for me.

**Comment by rchovan** [comment]
I did this today:

1. init 3
2. removed all timeshift lines from settings
``` 
root@xpeedlx3:/etc/enigma2# grep -i times settings 
root@xpeedlx3:/etc/enigma2#
```
3. updated to latest version
```
opkg update; opkg upgrade
```
4. reboot
```
root@xpeedlx3:/etc/enigma2# uptime
18:56:57 up 2 min,  1 user,  load average: 0,39, 0,31, 0,13

```
5. setup timeshift again over gui 
6. actual settings
```
root@xpeedlx3:/hdd/movie/satelit# grep -i times /etc/enigma2/settings 
config.timeshift.allowedPaths=['/media/hdd/movie/satelit/TimeShift/']
config.timeshift.checkEvents=480
config.timeshift.checkFreeSpace=8192
config.timeshift.favoriteSaveAction=savetimeshift
config.timeshift.path=/media/hdd/movie/satelit/TimeShift/
config.timeshift.startDelay=5
config.timeshift.stopWhileRecording=True
```
7. folder `/media/hdd/movie/satelit/TimeShift/`  contains this 
```
root@xpeedlx3:/hdd/movie/satelit# ls TimeShift/ -l
-rw-------    2 root     root      10203324 Oct 28 19:13 pts_livebuffer_1
-rw-r--r--    1 root     root           569 Oct 28 19:13 pts_livebuffer_1.eit
-rw-r--r--    1 root     root           169 Oct 28 19:13 pts_livebuffer_1.meta
-rw-r--r--    2 root     root             0 Oct 28 19:13 pts_livebuffer_1.sc
-rw-------    2 root     root      10203324 Oct 28 19:13 timeshift.lrrXq0
-rw-r--r--    2 root     root             0 Oct 28 19:13 timeshift.lrrXq0.sc
```
8.  and TimeShift recordings are placed again in folder with regular recordings, which is wrong by my opinion, because they were separated in previous release

@jbleyel  in previous version I had placed my timeshift recordings to `/media/hdd/movie/satelit/TimeShift/` but now they are mixed with my manual recordings in `/media/hdd/movie/satelit/`

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/0016fd10e7e905546285a51b70c898837b5b6d61

**Comment by rchovan** [comment]
thanks for commit, how to apply it on my box to test it ? 
I usually update over opkg  or download nightly build from https://images.mynonpublic.com/openatv/nightly/index.php?open=xpeedlx3  

Will be this commit in nightly build for example in 20241031 or 20241101 ?

**Comment by jbleyel** [comment]
You need to use ATV 7.5 and wait aprox 2 days.
