### ISSUE TITLE
fehlerhafte Subchannels in groupedservices

### ISSUE THREAD

**Issue by MrTreamer** [openatv/enigma2#3452]
Die für die Subchannels in OpenATV (Version: ab 7.4) verantworliche Datei
groupedservices
verweist auf falsche Channels, da bei einigen Kanälen die Transponderdaten (seit letzter Aktualisierung vor > 1 Jahr) geändert wurden.
Es kamen u.a. neue Sender hinzu, andere wurden verschoben, so dass sich bestimmte Sender-Parameter änderten.

alte Einträge, fehlerhaft:

`#` Sky Sport HD
1:0:19:6C:C:85:C00000:0:0:0: #Sky Sport News HD
1:0:19:81:6:85:C00000:0:0:0: #Sky Sport 1 HD
1:0:19:72:D:85:C00000:0:0:0: #Sky Sport 2 HD
1:0:19:10C:6:85:C00000:0:0:0: #Sky Sport 3 HD
1:0:19:116:D:85:C00000:0:0:0: #Sky Sport 4 HD
1:0:19:120:C:85:C00000:0:0:0: #Sky Sport 5 HD
1:0:19:12A:9:85:C00000:0:0:0: #Sky Sport 6 HD
1:0:19:134:4:85:C00000:0:0:0: #Sky Sport 7 HD
1:0:19:13E:2:85:C00000:0:0:0: #Sky Sport 8 HD
1:0:19:148:6:85:C00000:0:0:0: #Sky Sport 9 HD
1:0:19:152:A:85:C00000:0:0:0: #Sky Sport 10 HD
1:0:19:102:E:85:C00000:0:0:0: #Sky Sport 11 HD
1:0:19:17D:B:85:C00000:0:0:0: #Sky Sport 12 HD
1:0:19:182:B:85:C00000:0:0:0: #Sky Sport 13 HD
1:0:19:187:D:85:C00000:0:0:0: #Sky Sport 14 HD
1:0:19:84:9:85:C00000:0:0:0: #DAZN 1 Bar HD
1:0:19:7A:10:85:C00000:0:0:0: #DAZN 2 Bar HD
1:0:1F:229:10:85:C00000:0:0:0: #Sky Sport UHD
[...]
`#` Sky Bundesliga HD
1:0:19:69:C:85:C00000:0:0:0: #Sky Sport Bundesliga 1 HD
1:0:19:10B:6:85:C00000:0:0:0: #Sky Sport Bundesliga 2 HD
1:0:19:115:D:85:C00000:0:0:0: #Sky Sport Bundesliga 3 HD
1:0:19:11F:C:85:C00000:0:0:0: #Sky Sport Bundesliga 4 HD
1:0:19:129:9:85:C00000:0:0:0: #Sky Sport Bundesliga 5 HD
1:0:19:133:4:85:C00000:0:0:0: #Sky Sport Bundesliga 6 HD
1:0:19:13D:2:85:C00000:0:0:0: #Sky Sport Bundesliga 7 HD
1:0:19:147:6:85:C00000:0:0:0: #Sky Sport Bundesliga 8 HD
1:0:19:151:10:85:C00000:0:0:0: #Sky Sport Bundesliga 9 HD
1:0:19:101:E:85:C00000:0:0:0: #Sky Sport Bundesliga 10 HD
1:0:1F:228:10:85:C00000:0:0:0: #Sky Sport Bundesliga UHD

 neue korrigierte Einträge:

`#` Sky Sport HD
1:0:19:6C:C:85:C00000:0:0:0: #Sky Sport News HD
1:0:19:81:6:85:C00000:0:0:0: #Sky Sport Top Event
1:0:19:72:D:85:C00000:0:0:0: #Sky Sport Tennis
1:0:19:90:D:85:C00000:0:0:0: #Sky Sport Golf
1:0:19:8D:2:85:C00000:0:0:0: #Sky Sport Mix
1:0:19:91:4:85:C00000:0:0:0: #Sky Sport Premiere League
1:0:19:11:9:85:C00000:0:0:0: #Sky Sport F1
1:0:19:10C:6:85:C00000:0:0:0: #Sky Sport 1 HD
1:0:19:116:2:85:C00000:0:0:0: #Sky Sport 2 HD
1:0:19:120:C:85:C00000:0:0:0: #Sky Sport 3 HD
1:0:19:12A:4:85:C00000:0:0:0: #Sky Sport 4 HD
1:0:19:134:4:85:C00000:0:0:0: #Sky Sport 5 HD
1:0:19:13E:9:85:C00000:0:0:0: #Sky Sport 6 HD
1:0:19:148:9:85:C00000:0:0:0: #Sky Sport 7 HD
1:0:19:152:10:85:C00000:0:0:0: #Sky Sport 8 HD
1:0:19:102:B:85:C00000:0:0:0: #Sky Sport 9 HD
1:0:19:10D:B:85:C00000:0:0:0: #Sky Sport 10 HD
1:0:19:84:9:85:C00000:0:0:0: #DAZN 1 Bar HD
1:0:19:7A:9:85:C00000:0:0:0: #DAZN 2 Bar HD
1:0:1F:229:10:85:C00000:0:0:0: #Sky Sport UHD
[...]
`#` Sky Bundesliga HD
1:0:19:69:C:85:C00000:0:0:0: #Sky Sport Bundesliga HD
1:0:19:10B:6:85:C00000:0:0:0: #Sky Sport Bundesliga 1 HD
1:0:19:115:2:85:C00000:0:0:0: #Sky Sport Bundesliga 2 HD
1:0:19:11F:C:85:C00000:0:0:0: #Sky Sport Bundesliga 3 HD
1:0:19:129:4:85:C00000:0:0:0: #Sky Sport Bundesliga 4 HD
1:0:19:133:4:85:C00000:0:0:0: #Sky Sport Bundesliga 5 HD
1:0:19:13D:9:85:C00000:0:0:0: #Sky Sport Bundesliga 6 HD
1:0:19:147:9:85:C00000:0:0:0: #Sky Sport Bundesliga 7 HD
1:0:19:151:10:85:C00000:0:0:0: #Sky Sport Bundesliga 8 HD
1:0:19:101:B:85:C00000:0:0:0: #Sky Sport Bundesliga 9 HD
1:0:19:10F:B:85:C00000:0:0:0: #Sky Sport Bundesliga 10 HD
1:0:1F:228:10:85:C00000:0:0:0: #Sky Sport Bundesliga UHD

Da die SD Sender nicht mehr existieren, könnten evtl. auch nachfolgende Einträge gelöscht werden:
`#` Sky Sport
`#` Sky Bundesliga
`#` Eurosport

Nicht überprüft und ggf. zu korrigieren sind auch die Einträge
`#` Sky Sport Austria HD (korrigieren und erweitern)
`#` Sky Sport Austria (löschen)
`#` Sky Select (korrigieren und erweitern)

LG Mr. Treamer

**Comment by jbleyel** [comment]
Du kannst einfach die Datei berichtigen und hier als Kommentar hinzufügen. Oder PR machen.

**Comment by MrTreamer** [comment]
Hab ein PullRequest erstellt #3453 [data/groupedservices](data/groupedservices)
