### ISSUE TITLE
FileCommander extract abort

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3454]
**Describe the bug / Actual behaviour:**
I abort a extraction but get a screen, please wait... with a close button.

**Expected behaviour:**
Just abort no extraction screen.

**Has this issue started to happen just recently?**
No.

**To reproduce:**
1. Go to a archive file
2. Press OK
3. chose extract
4. abort or exit key
5. See result is the extraction screen

**Comment by jbleyel** [comment]
I cannot reproduce this.
After cancel it jumps back to then main screen of FileCommander.

What type of archive are you using and what size.

**Comment by GhostofGeeeee** [comment]
> What type of archive are you using and what size.

enigma2settingsbackup.tar.gz 35kB but alike.

You call this ["Cancel extraction"](https://github.com/openatv/enigma2/blob/f49cdbb9707d67c180d52bb43286a5666a51b6ac/lib/python/Plugins/Extensions/FileCommander/plugin.py#L1985)? Not this ["Cancel"](https://github.com/openatv/enigma2/blob/f49cdbb9707d67c180d52bb43286a5666a51b6ac/lib/python/Plugins/Extensions/FileCommander/plugin.py#L1448)!
