### ISSUE TITLE
Something missing at "ServiceScanSummary"

### ISSUE THREAD

**Issue by Makumbo** [openatv/enigma2#3455]
In "**skin_display.xml**" or "**skin_display_templates.xml**":

```
<screen name="ServiceScanSummary" position=...>
	<widget name="Title" position=.../>
	<widget name="scan_progress" position=.../>
	<panel name="SummaryClockPanel"/>
</screen> 
```

The ServiceScan runs OK and headline, progressbar and current time
are shown correctly on the LCD of the receiver.

**BUT**: If the scan is completed there is no notification of that!

Headline, progressbar and current time are still shown.

There is **no "Scanning completed, xx channels found" in the LCD** like on TV Screen.

**Comment by jbleyel** [comment]
If you wanna have status text then you need to use something like this:

<widget name="parent.scan_state" position=.../>

**Comment by Makumbo** [comment]
Like what?

**Comment by jbleyel** [comment]
`<widget name="parent.scan_state" position=.../>`

**Comment by Makumbo** [comment]
Habe mit
`<widget source="parent.scan_state" render="Label" position=.../>`
getestet.
Geht soweit, ABER zeigt während des gesamten Suchlaufs, und auch wenn er fertig ist,
immer nur "**Suchlauf zu 0% erledigt, 0 Sender gefunden.**" an.
Oder muß es anders als render="Label" heißen?

![Suche](https://github.com/user-attachments/assets/20b18700-ab0e-4a87-a1ed-8ee32e49dd02)

UND: Auch beim manuellen Suchlauf werden die unteren drei "Ja" / "Nein"
Optionen im LCD **nicht umgeschaltet**...

**Comment by jbleyel** [comment]
`<widget name="parent.scan_state" ...`

**Comment by Makumbo** [comment]
Wer lesen kann ist klar im Vorteil! ;)
"**name**" statt "**source**"
Das kommt davon, wenn man eine Zeile kopiert und einfügt
und dann darin nur "xxx" gegen "parent.scan_state" austauscht.

MEIN Fehler!

Hab' ich gedacht, Aber: **Mit "source=" bekomme ich wenigstens die
Ausgabe wie auf dem Screenshot.**

**Mit "name=" kommt gar KEIN Text!**

Egal ob

`<widget name="parent.scan_state" position="10,254" size="280,56" font="FdLcD;24" foregroundColor="#00FF00" valign="center" halign="left"/>
`

oder

`<widget name="parent.scan_state" render="Label" position="10,254" size="280,56" font="FdLcD;24" foregroundColor="#00FF00" valign="center" halign="left"/>
`

HILFE - Was mache ich falsch?

**Comment by jbleyel** [comment]
Probier mal das:
[ServiceScan.py.zip](https://github.com/user-attachments/files/17708505/ServiceScan.py.zip)

und das:

`<widget source="parent.scan_state" render="Label" position="10,254" size="280,56" font="FdLcD;24" foregroundColor="#00FF00" valign="center" halign="left"/>`

**Comment by Makumbo** [comment]
Habe ServiceScan.py nach usr/lib/enigma2/python/Screens kopiert,
die Zeile eingebaut (mit source=) und dann einen Neustart gemacht.

Sollte das .py nicht in .pyc gewandelt werden?
Hab ich da was falsch gemacht?

Danach gibt es eine Anzeige.
ABER: Wieder "Suchlauf zu 0% erledigt, 0 Sender gefunden."

Mit name= gibt es keine Anzeige.

**Comment by Makumbo** [comment]
Jetz wurde eine .pyc erzeugt.
Aber gleiches Ergebnis - 0%, 0 Sender.

![02](https://github.com/user-attachments/assets/80be5eb8-2ccd-42c9-a3a5-6b4caf084f4b)

Links neue .pyc, recht alte - nur in den ersten 2 Zeilen Unterschiede.

**Comment by Makumbo** [comment]
Jetzt aber erstmal ab ins Bett...

**Comment by jbleyel** [comment]
[ServiceScan.py.zip](https://github.com/user-attachments/files/17721100/ServiceScan.py.zip)

`<widget name="scan_state" position="10,254" size="280,56" font="FdLcD;24" foregroundColor="#00FF00" valign="center" halign="left"/>
`

**Comment by Makumbo** [comment]
PASST!

![01](https://github.com/user-attachments/assets/7f2b455c-dfb5-4f45-8b02-bf836e60f6e2)
![02](https://github.com/user-attachments/assets/f5bd14f7-3e22-4632-871d-9174813fd132)

Vielleich mach' ich die Uhr noch weg und dafür die Schrift etwas größer.

Danke!

**Comment by Makumbo** [comment]
So, habe den **480x320 Default Skin** nochmal überarbeitet.

Die 'riesigen' auskommentierten Teile sind weg, dafür
sind jetzt die "screen name=" Kommentare, die den Screen
beschreiben, etwas ausführlicher und in englisch.

**Und natürlich und vor allem ist jetzt das mit dem "SeviceScan"
drin, der von uns - also von Dir - erfolgreich eingebaut wurde.**

Auch die Vorschaubilder sind neu, da jetzt die Fortschrittsbalken
grau und nicht mehr mit 'stechendem' weiß gefüllt werden.

[480x320-usr-share-enigma2-display.zip](https://github.com/user-attachments/files/17770475/480x320-usr-share-enigma2-display.zip)

**Comment by Makumbo** [comment]
Image 7.4 vom 18.11.: Sehe gerade, dass das neue "ServiceScan.py" noch nicht im Image ist,
und deshalb dann auch die "xx Sender gefunden" Texte - noch - nicht angezeigt werden...

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/00d2c75d77dde83511eda13c7b6828139acc30c0
