### ISSUE TITLE
Some things i came accros.

### ISSUE THREAD

**Issue by neoatomic** [openatv/enigma2#349]
While translating i came across some issues. (openatv-5.3-dm800se-20160427 build)

The Memory page shows "OpenATV By the openATV Image Team."
Dont think its supposed to show there.?

![memory-en](https://cloud.githubusercontent.com/assets/7928052/14930759/bd9362f4-0e66-11e6-8d94-a2ad83bfc153.jpg)

I'm missing the icons from the QuickMenu (blue button)
This was working fine on the openatv-5.3-dm800se-20160419 build.?

![osd missing icons](https://cloud.githubusercontent.com/assets/7928052/14930760/bdb91300-0e66-11e6-9166-28cd0f12f723.jpg)

Log is confirming the issue. :

```
22:08:54.677 {   } Plugins/Extensions/Infopanel/plugin.py:428 ok [INFO-Panel] MenuItem: Infos
22:08:54.680 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/InfoPanel.png [No such file or directory]
22:08:54.680 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/InfoPanel.png
22:08:54.686 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/ImageVersion.png [No such file or directory]
22:08:54.686 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/ImageVersion.png
22:08:54.690 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/FreeSpace.png [No such file or directory]
22:08:54.690 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/FreeSpace.png
22:08:54.695 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/Kernel.png [No such file or directory]
22:08:54.695 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/Kernel.png
22:08:54.699 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/Mounts.png [No such file or directory]
22:08:54.700 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/Mounts.png
22:08:54.703 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/Network.png [No such file or directory]
22:08:54.703 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/Network.png
22:08:54.707 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/Ram.png [No such file or directory]
22:08:54.707 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/Ram.png
22:08:54.711 [ E ] base/cfile.h:17 CFile error /usr/share/enigma2/icons/SystemInfo.png [No such file or directory]
22:08:54.711 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open /usr/share/enigma2/icons/SystemInfo.png
```

The Plugin filter page is missing the explanations for the settings. (explanations are present in the translations po's)

![missing explanations plugin filter](https://cloud.githubusercontent.com/assets/7928052/14930758/bd8db606-0e66-11e6-9480-815252ba1b23.jpg)

Last i have a security cam that i use as IPTV (1080p) stream in my channel list, and it freezes after a few seconds. (btw working fine on my solo4k)
Looking at the error below it seems like the stream is freezing because of a missing codec.

```
23:44:12.668 [ E ] service/servicemp3.cpp:2041 gstBusCall [eServiceMP3] m_errorInfo.missing_codec = audio/x-mulaw
```

And a crash.log from a bad online update yesterday (box went into a boot loop) : http://pastebin.com/raw/xNnYH9Gj

I left the Debug log running in the background and extracted the errors/warnings. Maybe there are some that you like to review. : http://pastebin.com/raw/4RWfHYKc

And this explanation probbebly needs renaming.?
https://github.com/openatv/enigma2/blob/master/lib/python/Screens/SoftwareUpdate.py#L212

**Comment by neoatomic** [comment]
@atvcaptain Not sure if you are open to "general" suggestions/improvements.?

* "Panic channel" option should be hidden in the GUI if the "Enable panic button" is disabled.
https://github.com/openatv/enigma2/blob/master/data/setup.xml#L85

* The Satellites.xml gets overwritten on every online update.
I'm using my own custom settings-list & satellites.xml, but on every online update the satellites.xml gets overwritten, and i need to replace it with my own version again. Also i normaly remove my cable.xml & terrestrial.xml to save about 1mb of space.
(Maybe add an option to exclude the satellites.xml/cable.xml/terrestrial.xml from updating/overwriting in the Software Manager Setup section?)

* The DVD-player plugin is currently installed by default on a DM800se. 
As the box doesn't have an DVD slot, and pressed for free space, i don't think this should be installed by default .? (unless its needed for the PVR function)

* Media player location in main-menu
I prefer to have my "media-player" at the top (or second) of my "main-page", as I'm used to that from previous images.
When i enable the option to show the media player in main-menu its added between the "Settings" (item weight="95") and "Shutdown" (item weight="99") entry's.
Would it be possible to add a option to make the "item weight=" (of a plugin) editable, so that a user can chose where to place a plugin in the main-menu.?

* Removing the YouTube plugin on my Solo4k from the main-menu.
I cant find an option to remove it form the main menu?

* SoftwareUpdate.py may need some cleanup/attention.
Currently its using the OpenVix website for feed status etc, and references here also:
https://github.com/openatv/enigma2/blob/master/lib/python/Components/OnlineUpdateCheck.py#L67
https://github.com/openatv/enigma2/blob/master/data/skin_default.xml#L2001

**Comment by atvcaptain** [comment]
-> SoftwareUpdate.py  not use in current build only a dead file
-> Removing the YouTube plugin  this comes form close source vu plugin the time i move this to extention like all over vu models or use plugin sort move or hide infos
-> Media player location in main-menu  use plugin sort
-The DVD-player plugin all images have it the plugin self only for few bytes 
-> The Satellites.xml gets overwritten on every online update, dont overwrite default, add a user xml add to /etc/enigma2 and image found it self

-> "Panic channel"  i check this
