### ISSUE TITLE
[TRANSLATION]: Typo in po/de.po line 15146

### ISSUE THREAD

**Issue by 4l3x2k** [openatv/enigma2#361]
Translation of `msgid "Do you want to delete all other languages?"` should be `msgstr "Wollen Sie alle anderen Sprachen löschen?"`.

**Comment by madieatv** [comment]
fixed https://github.com/openatv/enigma2/commit/beea917fd861f449ff50858abc2ed2e183d26e2c

**Comment by 4l3x2k** [comment]
Test with Image from 2016-06-02 successful.
