### ISSUE TITLE
Segmentation fault enigma2 for et8500

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#400]
Use module CI+ and new drivers drivers-4.4.8-5.3.0-20160701 + mgcamd 
Zap to service using mgcamd:

> [EMCMS] python-mutagen is not available: No module named mutagen.mp3
> 20:15:44.392 Plugins/Extensions/EnhancedMovieCenter/EMCTasker.py:43 emcDebugOut EMC: Next trashcan cleanup in 345 minutes
> 20:15:44.393 dvb_ci/dvbci_session.cpp:259 receiveData slot: 0x7f1eb0 91 04 00 02 00 41
> 20:15:44.393 dvb_ci/dvbci_session.cpp:162 createSession APPLICATION MANAGER
> 20:15:44.393 dvb_ci/dvbci_session.cpp:214 createSession new session nb 2 0x1643698
> 20:15:44.393 dvb_ci/dvbci_session.cpp:100 sendOpenSessionResponse sendOpenSessionResponse
> Segmentation fault

**Comment by atvcaptain** [comment]
we wait for new updates, please wait

**Comment by Dima73** [comment]
This problem not solved.
Are there any news?

**Comment by atvcaptain** [comment]
have you test drivers from 20160715 i dont use mgcam , so i have no infos

**Comment by Dima73** [comment]
Drivers data20160715/image openatv 5.3,use oscam and ci+ module.

**Comment by atvcaptain** [comment]
and same crash or works ?

**Comment by Dima73** [comment]
20:52:48.461 dvb/epgcache.cpp:1558 startEPG [EPGC] start caching events
20:52:48.616 dvb/dvbtime.cpp:416 updateTime [eDVBLocalTimerHandler] Transponder time is 25.08.2016 20:52:49
20:52:48.616 dvb/dvbtime.cpp:429 updateTime [eDVBLocalTimerHandler] diff is 1
20:52:48.617 dvb/dvbtime.cpp:432 updateTime [eDVBLocalTimerHandler] diff < 120 .. use Transponder Time
20:52:48.617 dvb/dvbtime.cpp:49 setRTC [eDVBLocalTimerHandler] set RTC Time
20:52:49.000 dvb/dvbtime.cpp:502 updateTime [eDVBLocalTimerHandler] update RTC
20:52:49.000 dvb/dvbtime.cpp:522 updateTime [eDVBLocalTimerHandler] time update to 20:52:49
20:52:49.000 dvb/dvbtime.cpp:525 updateTime [eDVBLocalTimerHandler] m_time_difference is 1
20:52:49.000 dvb/dvbtime.cpp:529 updateTime [eDVBLocalTimerHandler] set Linux Time
20:52:49.000 dvb/dvbtime.cpp:540 updateTime [eDVBLocalTimerHandler] time after update is 20:52:49
Segmentation fault
