### ISSUE TITLE
UTF-8 Spanish characters not showing after last commits

### ISSUE THREAD

**Issue by pizzelnet** [openatv/enigma2#437]
After last commits of August 17, the enigma2 EPG doesn't show in the GUI the Spanish special characters (á é í ó ñ Á É Í Ó Ú Ñ) after downloading the MHW2 EPG data. The characters "ú and ü" are the only one loaded.
However, in OpenWebIf the characters are correctly shown.

![issue](https://cloud.githubusercontent.com/assets/9438117/17804032/0de536f2-65fa-11e6-8676-22a4536f7b3b.png)

![openwebif](https://cloud.githubusercontent.com/assets/9438117/17804323/6631d986-65fb-11e6-8591-66bbae2dada7.PNG)

**Comment by atvcaptain** [comment]
ok we check this thx for feedback

**Comment by arn354** [comment]
https://github.com/openatv/enigma2/commit/ca0b200f3a03c6f751109c020a5dd0442b32c333
Maybe that solves

**Comment by atvcaptain** [comment]
thx so i have now weekend free :)
