### ISSUE TITLE
Arduino Nano clone driver CH340G

### ISSUE THREAD

**Issue by ejalal** [openatv/enigma2#444]
Hi all,

Is there any way to add drivers for Arduino Nano clone CH340G in the future ? This one is not recognised as /dev/ttyACM0.

I need that to replace my expensive Arduino Uno to drive an Enigmalight setup.

**Comment by atvcaptain** [comment]
we have add for long time all openatv image: https://github.com/oe-alliance/oe-alliance-core/blob/3.4/meta-brands/meta-ceryon/recipes-linux/linux-ceryon-4.0.1/7000s/defconfig#L2342

you must only install the kernel drivers from feed

**Comment by ejalal** [comment]
Hi captain
I just plugged it and it wasn't recognised as /dev/ttyACM0 like the original Adruino.
kernel-module-cdc-acm is already installed.
After googling for some time, I found an alternative driver for this one when is located in http://www.wch.cn/download/CH341SER_LINUX_ZIP.html
Is it possible to include in one of the next builds ?

**Comment by atvcaptain** [comment]
you must install self  : opkg install kernel-module-ch341

**Comment by atvcaptain** [comment]
ah duo2 i see, i have forget, check next days i include the driver

**Comment by ejalal** [comment]
Great, can you also include it in solo4k please, it has the exact same problem

**Comment by atvcaptain** [comment]
yes i have add too

**Comment by ejalal** [comment]
Thanks a lot for tour great support
