### ISSUE TITLE
lib/python/Components/ScrollLabel.py causing ever decreasing text display widths

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#450]
This file is causing a problem on 2ndinfobar INFO and Plugin installs within many skins. The scrollboxs displayed decrease in width each time they scroll or are called. As an example, display 2nd infobar info (press OK twice from TV) and then change channel up/channel down and you will see the width of text displays gets narrower and narrower - It's as is each scroll is spawinging within the previous one
![4](https://cloud.githubusercontent.com/assets/17210151/18071873/f311d196-6e50-11e6-8d15-b577dc3dfa02.jpg)
![3](https://cloud.githubusercontent.com/assets/17210151/18071874/f312ffbc-6e50-11e6-9c6d-1f16171dc473.jpg)
![2](https://cloud.githubusercontent.com/assets/17210151/18071876/f31761d8-6e50-11e6-856f-4c57262492f7.jpg)
![1](https://cloud.githubusercontent.com/assets/17210151/18071875/f315deda-6e50-11e6-8a00-8dbb1bab051c.jpg)

**Comment by davesayers2014** [comment]
same issue here using a different skin
