### ISSUE TITLE
openatv crash - streaming

### ISSUE THREAD

**Issue by forall** [openatv/enigma2#454]
Hi,

When I watched tv over inteternet (streaming) my software was crashed.. This is a dmesg log:

[DMX]: paserband_remove_pid pid 0x0 not found

[DMX]: paserband_remove_pid pid 0x40d not found

CPU 1 Unable to handle kernel paging request at virtual address 00000028, epc == e0ce3a00, ra == e0ce3a00
Oops[#1]:
CPU: 1 PID: 731 Comm: enigma2 Tainted: P           O 3.13.5 #1
task: cef29220 ti: ce304000 task.ti: ce304000
$ 0   : 00000000 10008b00 000091c4 cf62a104
$ 4   : 10008b01 10008b01 000002e7 00000001
$ 8   : 00000000 84080008 800e2b9c 7fab1204
$12   : 7fa8fc50 00000000 019242d8 77a31400
$16   : cf5e4a80 cf5e4a80 00000000 00000000
$20   : 00000000 e10d73a0 e18f0000 e0d50000
$24   : 0049ba5c 8006ff60  
$28   : ce304000 ce305d18 e0d50000 e0ce3a00
Hi    : 00000008
Lo    : 00000000
epc   : e0ce3a00 NEXUS_BaseObject_P_RegisterUnregister+0x17c/0x3bc [dvb_base]
    Tainted: P           O
ra    : e0ce3a00 NEXUS_BaseObject_P_RegisterUnregister+0x17c/0x3bc [dvb_base]
Status: 10008b03        KERNEL EXL IE
Cause : 00800008
BadVA : 00000028
PrId  : 00025a11 (Broadcom BMIPS5000)
Modules linked in: tun ipv6 brcmfb(O) dvb_bcm7424(PO) dvb_base(PO) bcm_event(PO) procmk(O) rt5370sta(O) rt2800usb rt2800lib rt2x00usb rt2x00lib mac80211 xfs libcrc32c
Process enigma2 (pid: 731, threadinfo=ce304000, task=cef29220, tls=76695490)
Stack : cf501884 8006ff74 cf501880 0000006f cffe2134 e0e4a960 e10e0000 00000000
          00000000 00000200 ceb6cf80 e19f21cc 00000200 e18f0000 e0d50000 e0d37f5c
          cf5e4a00 e0e4b104 ceb6cf80 e19f3a8c cf5e4a80 8006ff74 00000000 e0d50c54
          00000000 e1b3d00c 10008b01 00000004 e1b3013c e18f54f4 e132f07c cfc19750
          cebdb188 80006b28 8005f5b4 00000000 00000000 8008db38 8201a338 8006ceb0
          ...
Call Trace:
[<e0ce3a00>] NEXUS_BaseObject_P_RegisterUnregister+0x17c/0x3bc [dvb_base]
[<e0d37f5c>] NEXUS_PidChannel_BaseObject_P_RegisterUnregister+0x34/0x40 [dvb_base]
[<e0d50c54>] NEXUS_PidChannel_Close+0x38/0x60 [dvb_base]
[<e18f54f4>] bcm7335_demux_release_priv+0x508/0x10fc [dvb_bcm7424]

Code: afa20010  0060f809  02602821 <8e430028> 10600041  8fa20010  12800011  00000000  8e430020
---[ end trace d4db0fb93dc0ee6e ]---

Software from 201060903

**Comment by atvcaptain** [comment]
less info, no infos about hardware you use etc.  but i think you use vu duo 2 ?, problem vu not fix any driver issue so we cant  help at this moment, open a ticket on vu plus web site and report the issue again

**Comment by forall** [comment]
Yes, I use vu+ duo2...but they said you youse different firmware... not original...?

**Comment by atvcaptain** [comment]
np demux issue was driver issues: send report to: http://vuplus.com/sub/sub0203.php

**Comment by forall** [comment]
@atvcaptain - I created a bug report.. I will see what they send to me...Thanks for help.
