### ISSUE TITLE
Improve the setting-restore

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#456]
Please add the ability to use a backup openPli format.
This plugin https://github.com/E2OpenPlugins/e2openplugin-AutoBackup
format PLi-AutoBackup.tar.gz

**Comment by arn354** [comment]
https://github.com/OpenPLi/openpli-oe-core/blob/master/meta-openpli/recipes-openpli/enigma2/settings-autorestore.bb
means we need this? 
Or read that file as alternative for atv-settings backup? I have not checked how content of PLi-AutoBackup.tar.gz looks like

**Comment by Dima73** [comment]
Now the file PLi-AutoBackup.tar.gz is not considered to restore atv-settings.
