### ISSUE TITLE
solo4k PiP problem -not sound for live tv service

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#465]
This is a general image problem openPLi/openATV
I really do not know much c+ code.
Let's solve this together.
All logs from the image openPLi.
Please help...

solo4k /skin Pli-HD --> start PiP --> open channel selector (Pli-HD use PiG) --> close  channel selector -->result - not sound !!!

This problem only live tv service and pip service is same.

Problem cause this
https://github.com/OpenPLi/enigma2/blob/master/lib/python/Screens/PictureInPicture.py#L39
Maybe this
https://github.com/OpenPLi/enigma2/blob/master/lib/dvb/decoder.cpp#L822
}
-	if (m_changed & changeAudio)
+	if ((m_changed & changeAudio) && m_decoder == 0)
	{
		if (m_audio)
			m_audio->stop();
		m_audio = 0;
	}

this start pip
<  1778.549> [eDVBServicePMTHandler] ok ... now we start!!
<  1778.549> [eDVBServicePlay] eventNewProgramInfo timeshift_enabled=0 timeshift_active=0
<  1778.549> [eDVBServicePlay] have 1 video stream(s) (0140), and 1 audio stream(s) (0191), and the pcr pid is 0140, and the text pid is ffffffff
<  1778.549> [eDVBChannel] getDemux cap=01
<  1778.549> [eTSMPEGDecoder] decoder state: play, vpid=0140, apid=0191
<  1778.549> [eDVBPCR1] DMX_SET_PES_FILTER pid=0x0140 ok
<  1778.549> [eDVBPCR1] DEMUX_START ok
<  1778.549> [eDVBAudio1] DMX_SET_PES_FILTER pid=0x0191 ok
<  1778.549> [eDVBAudio1] DEMUX_START ok
<  1778.549> [eDVBAudio1] AUDIO_SET_BYPASS bypass=1 ok
<  1778.549> [eDVBAudio1] AUDIO_PAUSE ok
<  1778.549> [eDVBAudio1] AUDIO_PLAY ok
<  1778.549> [eDVBVideo] Video Device: /dev/dvb/adapter0/video1
<  1778.550> [eDVBVideo] demux device: /dev/dvb/adapter0/demux0
<  1778.550> [eDVBVideo1] VIDEO_SET_STREAMTYPE 0 - ok
<  1778.550> [eDVBVideo1] DMX_SET_PES_FILTER pid=0x0140 ok
<  1778.550> [eDVBVideo1] DEMUX_START ok
<  1778.550> [eDVBVideo1] VIDEO_FREEZE ok
<  1778.550> [eDVBVideo1] VIDEO_PLAY ok
<  1778.555> [eDVBVideo1] VIDEO_SLOWMOTION 0 ok
<  1778.556> [eDVBVideo1] VIDEO_FAST_FORWARD 0 ok
<  1778.556> [eDVBVideo1] VIDEO_CONTINUE ok
<  1778.556> [eDVBAudio1] AUDIO_CONTINUE ok

this pip set false 
<  1787.087> action ->  InfobarChannelSelection keyUp
<  1787.129> [eTSMPEGDecoder] decoder state: play, vpid=ffffffff, apid=ffffffff
<  1787.129> [eDVBPCR1] DEMUX_STOP ok
<  1787.129> [eDVBPCR1] destroy
<  1787.129> [eDVBVideo1] DEMUX_STOP  ok
<  1787.136> [eDVBVideo1] VIDEO_STOP ok
<  1787.136> [eDVBVideo1] destroy
<  1787.136> [eDVBAudio1] AUDIO_STOP ok
<  1787.136> [eDVBAudio1] DEMUX_STOP ok
<  1787.159> [eDVBAudio1] AUDIO_CONTINUE ok
<  1787.160> [eDVBAudio1] destroy

AUDIO_STOP ok !!!
for pip service need  don't use audio

**Comment by atvcaptain** [comment]
with vu original image works ?

**Comment by Dima73** [comment]
Sorry, I have not yet been tested.
The receiver is only the second day I had.

**Comment by Dima73** [comment]
vu original image not this problem.
http://code.vuplus.com/gitweb/?p=vuplus_dvbapp;a=blobdiff;f=lib/dvb/decoder.cpp;h=e3d97afde68863fb8b5ff1f6ae63f6956ce1661a;hp=8a4a82df71f901ae812650ada61428b302605649;hb=b4526f440375abe6ad4e7b02f2300b7dc18c6b88;hpb=afa141eedd597d0468d33b97a79f738a9ebfd11f
please help...

**Comment by Dima73** [comment]
No one answer?

**Comment by atvcaptain** [comment]
vu have no prio at this time, we have many issues and no fixes too, we push boxes we get support, vu ignore us.

**Comment by Dima73** [comment]
I agree with you completely.
Help from the VU+, we can not wait.
Let's solve this in enigme2.
On the original image from the VU+ this problem has been fixed.

**Comment by atvcaptain** [comment]
yes with fcc code but this code not work with atv and pli, so not help , we wait for fcc fix from vu and we have it

**Comment by Dima73** [comment]
Maybe simple ?
D'ont use eDVBAudio1 https://github.com/openatv/enigma2/blob/master/lib/dvb/decoder.cpp#L31
for PiP video_decoder = 1 this is dev
so, maybe set this
sprintf(filename, "/dev/dvb/adapter%d/audio%d", demux ? demux->adapter : 0, 0);

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/commit/8cc2972343f53d698545800e396944f15a4a66ea
