### ISSUE TITLE
solo4k lcd display in shutdown

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#466]
image openATV:
shutdown or reboot solo4k --> lcd display dark screen ->this is OK

image openPli:
shutdown or reboot solo4k --> lcd display white screen, and then half of a green screen ->it is very ugly

Please help that where the lcd display is switched off in openATV?
I wanted to make a patch for openPli.

**Comment by atvcaptain** [comment]
look in atv standby.py no magic

**Comment by Dima73** [comment]
Thank you.
I came to the same idea.
But I was looking for in the code in c+ part openATV.
