### ISSUE TITLE
Wrong SNR for Vuplus DVB-S NIM(AVL6222) (DVB-S2)

### ISSUE THREAD

**Issue by pizzelnet** [openatv/enigma2#482]
The formula `ret = (int)((((double(snr) / (65536.0 / 100.0)) * 0.1244) + 2.5079) * 100);` in [https://github.com/openatv/enigma2/blob/master/lib/dvb/frontend.cpp](url) does not seem to work properly as the maximum percentage given is 93% instead of 100%.

**Comment by arn354** [comment]
seems that calculation is based on a maximum of 15db instead of 16db https://github.com/openatv/enigma2/blob/master/lib/dvb/frontend.cpp#L820

maybe it is sufficient to add sat_max = 1500 :
{
ret = (int)((((double(snr) / (65536.0 / 100.0)) * 0.1800) - 1.0000) * 100);
sat_max = 1500
}

**Comment by arn354** [comment]
thx for pullrequest :)
