### ISSUE TITLE
Ethernet problem

### ISSUE THREAD

**Issue by JideJames** [openatv/enigma2#510]
i just bought new Zgemma H2S but could connect to internet through Ethernet cable.

What can I do?

**Comment by atvcaptain** [comment]
image dont have a issue, check your hardware

**Comment by JideJames** [comment]
My ethernet cable works well with my sky box, desktop and other appliances but not with the zgemma.
This is my second zgemma box, after I returned the first one because of same problem.

how can I resolve this? is the any driver or ethernet software that I need to download or install in a brand new zgemma H2S box?

**Comment by JideJames** [comment]
or perhaps, where can I get an image software from?
maybe if I reflash, it will be corrected.

**Comment by atvcaptain** [comment]
http://images.mynonpublic.com/openatv/nightly/index.php?open=zgemmah2s
