### ISSUE TITLE
simple standby not work edision os mini plus

### ISSUE THREAD

**Issue by trikru** [openatv/enigma2#534]
Hello, i have updated my os mini plus with the openatv 5.3, build date 2016/12/12, when i try to put my os mini plus in standby mode, it doesn't work.
To be more specific it turns in standby for 1 second and after it came back active. 
So i need to put in deep-standby to force the decoder to remain off.

**Comment by atvcaptain** [comment]
looks hdmi -cec wake up your box , can you check this

**Comment by trikru** [comment]
Yes captain! My fault! Sorry for the loss of time
