### ISSUE TITLE
H1 image not detecting DVB-C tuner

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#544]
All builds currently available (going back around 1 week) do not detect the H1 DVB-C Tuner.  Missing a driver in the build?

**Comment by zgemma-star** [comment]
Which DVB-C tuner is build in your box.
With older image please check tuner configuration
TUNER B: ????

**Comment by p17blo** [comment]
TDA10024 (I thought all H1 had the same tuner)

**Comment by zgemma-star** [comment]
No, there are three version.
Found issue and a fix will come soon.

**Comment by atvcaptain** [comment]
fixed with new drivers

**Comment by p17blo** [comment]
Same issue has been re-instruduced.  Exactly the same tuner is now again unavailable with the latest updates on ATV
