### ISSUE TITLE
LED Clock Frozen

### ISSUE THREAD

**Issue by brock79** [openatv/enigma2#545]
Ran all available software updates on my Zgemma H2S box running Wooshbuild yesterday (22nd December 2016) and now when the LED Display clock is set to "Clock Always" the time freezes whenever the box is ON, if the box is in standby the time works fine but when it's out of standby the clock just stays on whatever time it was on. 

Other people on Techkings forums have also confirmed having this issue after installing recent updates.

**Comment by davesayers2014** [comment]
Same here on default openatv images

**Comment by arn354** [comment]
there was an update to F3LED plugin - https://github.com/oe-alliance/oe-alliance-plugins/commit/e51d5cf120e55d23e3e6d6d6b221ad77081ad849

use previous version - https://github.com/oe-alliance/oe-alliance-plugins/raw/9672861dabc4f1ede0cb7ef1d3fe09a5eb2af8a0/F3LEDControl/src/plugin.py 
i have not such box to check.

**Comment by brock79** [comment]
Thanks. Hopefully someone else can check that older version and confirm it works as I don't currently have the knowledge to do this.

**Comment by davesayers2014** [comment]
Sorry but where do I find F3LEDControl? I have had a look in the systemplugins folder but cant see it only VFDcontrol

**Comment by davesayers2014** [comment]
Edid I just added the plugin.py in vfd clock and that fixed it thanks

**Comment by davesayers2014** [comment]
brock79 all you need to do is copy all the text and past in Notepad and save as plugin.py ftp it to usr/lib/enigma2/python/Plugins/SystemPlugins/vfdcontrol save the pyo version to pc just in case then reboot box. Hopefully all works if not delete the py and pyo and replace with the original pyo file you saved.

**Comment by brock79** [comment]
Thanks a lot mate. I'll give that a whirl. 

I presume they will fix this by way of another software update at some point as well as its affected everyone who has updated recently.

**Comment by davesayers2014** [comment]
Yes at some point

**Comment by atvcaptain** [comment]
fixed

**Comment by brock79** [comment]
When you say fixed and closed does that mean a software update on the box with the fix is now available to everyone? If not I would personally say the issue isn't fixed as everyone who has updated has got this issue and has not been able to automatically resolve it.

**Comment by atvcaptain** [comment]
sure with software update, i think i must not say more

**Comment by brock79** [comment]
Thank you. It seems software updates are now fixing the issue.
