### ISSUE TITLE
CI module and PiP

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#550]
In some CI module is support "Multiple service support"
e.g. module NTV+ (russian) two channels can be decoded are on the same transponder.
When use PiP(pipzap mode) and zap to new pipzap service,service live tv it ceases to be decoded.
The same problems occur when recording / stream.
This happens on all the image.
It can be fixed?
Maybe here it will help:
https://github.com/Duckbox-Developers/libstb-hal-cst-next/commits/master/common
https://github.com/Duckbox-Developers/libstb-hal-cst-next/commits/master/libdvbci

**Comment by arn354** [comment]
i think i have one module and a card to check - i recall no problems but it was long time ago

**Comment by atvcaptain** [comment]
pip and ci was driver we cant fix any only request to driver teams

**Comment by Dima73** [comment]
I think it can be solved at the level of enigma2 code.
Only I do not have enough knowledge.
