### ISSUE TITLE
missing EPG after reboot

### ISSUE THREAD

**Issue by rchovan** [openatv/enigma2#551]
epg.dat in internal memory:
epg.dat is stored in internal flash /etc/enigma2/epg.dat. 
After reboot is this file missing and then I can't see any epg data in channel list. 

When epg.dat is stored in /media/hdd, then everything works fine.

**Comment by davesayers2014** [comment]
Why are you using internal flash? Epg should always be held on external storage or internal hard drive if epg.dat is corrupted you run the risk of bricking the box.

**Comment by arn354** [comment]
working in internal flash for ages.
if it is not there - it has other reasons. Enable E2 debug-log, restart gui, shutdown box. Then provide created log which includes the shutdown of e2. You should see soemthing there like:
19:25:52.8735 [   ] dvb/epgcache.cpp:1455 save [eEPGCache] store epg to realpath '/etc/epg.dat'
19:25:53.0455 [   ] dvb/epgcache.cpp:1501 save [eEPGCache] 107805 events written to /etc/epg.dat

if not something else is stated which will point to the right direction.

**Comment by rchovan** [comment]
@davesayers2014 , I know, that internal flash has lower read/write life than hdd, but  I do not understand, how can corrupted epg.dat file brick box ? Do I miss something ?

**Comment by arn354** [comment]
okeee :) never had that worst case scenario on i think 50+ boxes.

**Comment by davesayers2014** [comment]
Ok upto the end user where they want to store epg data

**Comment by rchovan** [comment]
does it affect how is box powered down ? Because when I run reboot from cli it start without EPG.
epg.dat is in place and it has 77 MB, 

**ls -l /hdd/epg.dat**
`-rw-r--r--    1 root     root        775904 Jan  3 18:04 /hdd/epg.dat
`

![image](https://cloud.githubusercontent.com/assets/6713920/21616027/44dbda06-d1e0-11e6-9420-38d2c11a967a.png)

**Comment by arn354** [comment]
at least save [EPGC] 3407 events written to /media/hdd/epg.dat should be stored.
thats probably not the complete epg for all your services - i also do not need epg for all channels but atleast i have way more events.

**Comment by arn354** [comment]
] dvb/epgcache.cpp:1281 load [EPGC] /media/hdd/epg.dat not found, try /epg.dat

in addition on start of e2 it does not find your /media/hdd/epg.dat - so nothing is read.

i don't know why your /media/hdd is not readable once e2 starts.

**Comment by rchovan** [comment]
reason, why E2 can't find epg.dat after reboot is:
``` ls -l /media/hdd/epg.dat
ls: /media/hdd/epg.dat: No such file or directory
```
because is missing. I did save epg before reboot and check, that file exist.

**Comment by arn354** [comment]
Then something weird is going on with your hdd

**Comment by rchovan** [comment]
I don't think that drive is faulty. It is server disk (http://www.harddrivesdirect.com/product_info.php?products_id=461830). Sometimes is epg read works, sometimes not. 

```
smartctl -H /dev/sda
smartctl 5.42 2011-10-20 r3458 [mips-linux-3.14.2] (local build)
Copyright (C) 2002-11 by Bruce Allen, http://smartmontools.sourceforge.net

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
Please note the following marginal Attributes:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
190 Airflow_Temperature_Cel 0x0022   055   040   045    Old_age   Always   In_the_past 45
```

**Comment by arn354** [comment]
see your other issue. something is wrong with kernel/driver.

**Comment by rchovan** [comment]
Why is epg.dat missing if is stored on hdd, not on internal flash ? 
I've copied from backup, and reload box. 

```
root@xpeedlx3:~# ls -l /media/hdd/epg.dat
-rw-r--r--    1 root     root        119861 Jan  6 11:18 /media/hdd/epg.dat
root@xpeedlx3:~# cd /media/hdd
root@xpeedlx3:/hdd# cp epg.dat.zal epg.dat

root@xpeedlx3:/hdd# ls -l epg.dat
-rw-r--r--    1 root     root       5587923 Jan  6 11:20 epg.dat

root@xpeedlx3:/hdd# reboot
Broadcast message from root@xpeedlx3 (pts/0) (Fri Jan  6 11:20:17 2017):
The system is going down for reboot NOW!

root@xpeedlx3:/hdd#
login as: root
root@192.168.2.7's password:

root@xpeedlx3:~# cd /media/hdd/epg.dat
-sh: cd: /media/hdd/epg.dat: Not a directory

root@xpeedlx3:~# ls -l epg.dat
ls: epg.dat: No such file or directory
```

**Comment by arn354** [comment]
sorry no idea. i dont have that box.

**Comment by betacentauri** [comment]
If epg file contains old data, it will be deleted from E2.

**Comment by rchovan** [comment]
Data are 2 maybe 3 days old. I have setup epg for 7 days. When I manually
load it,  they are displayed in channels list.

When are data old, deleted are only old events or whole epg.dat file ?

Dňa 6.1.2017 15:54 používateľ "Betacentauri" <notifications@github.com>
napísal:

**Comment by betacentauri** [comment]
It should only delete old events.

**Comment by antonys1981** [comment]
Im having problems with epg missing after a reboot also sometimes the channels slowly loses epg one by one whilst my box is on and tried different HDD and usb sticks with same result is this a atv issue ?

**Comment by antonys1981** [comment]
Update I re flashed with open vix and all works perfectly fine epg is retained so this confirms a atv 6.0 issue this problem is on both a zgemma h2h and mutant hd51 with cable tuners could someone please get back to me regarding this

**Comment by atvcaptain** [comment]
no issue with atv 6.1 and 6.2
