### ISSUE TITLE
reboot command does not work

### ISSUE THREAD

**Issue by rchovan** [openatv/enigma2#558]
When I run command "reboot" from cli, box is rebooted, but bootloader does not start. 
HDMI is off, LCD front panel is off. I need to turn it off by power switch, wait, and turn it on again. 
Then it start. 

My box is Xpeed LX3. 

p.s.: in other images (openPLI, openHDMU, openVIX, etc..) it works .

**Comment by atvcaptain** [comment]
create a serial log , this issue have nothing todo with e2 self, looks driver or kernel crashing and box stops responding

**Comment by rchovan** [comment]
Hi, here is shutdown log from serial console:
[shutdown.txt](https://github.com/openatv/enigma2/files/687737/shutdown.txt)

**Comment by arn354** [comment]
don't have that box but kernel crashes on shutdown. this also probably explains your other issue with epg.dat.

**Comment by arn354** [comment]
at least openVIX uses same drivers and kernel like openatv from oe-alliance - so no idea why it works there but not here.

**Comment by rchovan** [comment]
Hi, 
I've just tried latest openVIX 4.2.0.23. Restored my saved settings from openATV and it works without problem. Tried reboot box several times. Here is serial log: 
[openVIX.txt](https://github.com/openatv/enigma2/files/689547/openVIX.txt)

Kernel version is same, but build is different
openATV:
Linux version 3.14.2 (oe1@build3) (gcc version 5.3.0 (GCC) ) #1 SMP Sun Dec 4 23:44:18 CET 2016

openVIX:
Linux version 3.14.2 (vix@ns202814.ovh.net) (gcc version 5.3.0 (GCC) ) #1 SMP Mon Oct 10 09:15:07 BST 2016

**Comment by arn354** [comment]
https://github.com/oe-alliance/oe-alliance-core/tree/3.4/meta-brands/meta-ini/recipes-linux
last change for ini 3.14.2 is 3 months ago. so the initial builddate might look different but should be the same source.

**Comment by rchovan** [comment]
1. can I combine kernel from openVIX with rootfs from openATV ? 
2. do you have any new testing kernel ?

**Comment by rchovan** [comment]
this error does not exist on latest builds.. 
Closing issue
