### ISSUE TITLE
servicemp3 .cpp  with gst 010

### ISSUE THREAD

**Issue by tromoto** [openatv/enigma2#604]
Compile fails for gst 0.10 as (line 3238 etc) m_last_play_pos is not defined. 
Switch for AML based boxes to gst 1.x is not ready yet as sound does not work.

**Comment by christophecvr** [comment]
oeps Yes sorry wil change that.

But

**Comment by tromoto** [comment]
thx, ok have to recheck gst 1.x sink for AML, but sound (AC3) is still a no-no for AML aarch64, probably licensing issue and needs to be done in sw...

**Comment by christophecvr** [comment]
should be back ok on gst-0.1 
#2c7e9af40917750d5bfe20f92de61c4602b27a0d

**Comment by christophecvr** [comment]
just a question , is it only ac3 audio which does not work by AML ? cause if it is that the stb AML does not have a build in ac3 codec gues with gst-0.1 You just use a downmix plugin of gst

**Comment by christophecvr** [comment]
which sink source do You by AML and gst-0.1 ?

**Comment by tromoto** [comment]
mmmh, still not sure to be honest. I guess those ARC bins are enabled/disabled by uboot fpga setup. They are very secretive about it and it does seem to be box depended. The trouble is, switching to SW decode makes another hit on AV sync which is terrible anyway :)

**Comment by tromoto** [comment]
AML gst 0.1 sinks from OEA (PB), they used to work ok on 3.4. I did not touch AML sinks for 1.x for 6 months, have to check...

**Comment by christophecvr** [comment]
AML is the wetek machine I guess ?

**Comment by tromoto** [comment]
Odroidc2, but yes wetek as as well. Odroidc2 is still non working, have to push some drivers.

**Comment by christophecvr** [comment]
Apparently they are using there own closed source sinks , which means You must keep 0.1 or ...

**Comment by christophecvr** [comment]
Ok i find there sinks but they used there own decoding gst plugin to convert audio to raw. So they do not use any build in cap then

**Comment by christophecvr** [comment]
I well checked : about sync issues and ac3 sw decode (which is required on the aml types as fac I could see)

the code for position in by wetek is 

`unsigned int eServiceMP3::get_pts_pcrscr(void)
{
	int handle;
	int size;
	char s[16];
	unsigned int value = 0;

	handle = open("/sys/class/tsync/pts_pcrscr", O_RDONLY);
	if (handle < 0) {      
         return value;
	}
	size = read(handle, s, sizeof(s));
	if (size > 0) {
		value = strtoul(s, NULL, 16);
	}
	close(handle);
	return value;
}`

I could set that for the boxes into the gst-1.0 dvbmediasink sink and the think that audio sync should work when using sw decoding

Just I You gice me the excact MACHINE and MACHINEBUILD off all concerned stb's (you can find that into the env.source file.

**Comment by christophecvr** [comment]
and the for AML using gst-1.0

the position, will be in audiosink and acutally the function by gst-1.0 well the be 
`static gint64 gst_dvbaudiosink_get_decoder_time(GstDVBAudioSink *self)
{
#if defined(<willbe define for the concerned stb's>)
	int handle;
	gint64 size;
	char s[16];
	gint64 value = 0;

	handle = open("/sys/class/tsync/pts_pcrscr", O_RDONLY);
	if (handle < 0) {      
         return value;
	}
	size = read(handle, s, sizeof(s));
	if (size > 0) {
		value = strtoul(s, NULL, 16);
	}
	close(handle);
	return value;
#else
	gint64 cur = 0;
	if (self->fd < 0 || !self->playing || !self->pts_written)
		return GST_CLOCK_TIME_NONE;

	ioctl(self->fd, AUDIO_GET_PTS, &cur);
	if (cur)
	{
		self->lastpts = cur;
	}
	else
	{
		cur = self->lastpts;
	}
	cur *= 11111;
	cur -= self->timestamp_offset;

	return cur;
#endif
}`

**Comment by tromoto** [comment]
Huh, great!
well, if you are sure about it ( we do need some proper testing), you can check for #ifdef __aarch64__
in this way you are pretty sure to cover AML 9xx stuff (for now). 

But, let me check.. and thank you!

**Comment by christophecvr** [comment]
Yes I do not have a box , but will push an updated dvbmediasink and servicemp3

but in servicemp3 we are using 
#if HAVE_AMLOGIC  for those stb's or not ?

**Comment by tromoto** [comment]
that should be fine, but I really have to check, I do not think there is another box in OEA that needs 0.10, but not sure.

**Comment by christophecvr** [comment]
also another looks like that on those boxes , You only use downmixed audio for all. If that is the case I could also just use the gstreamer playbin position and audio synchronized by gstreamer that could maybe also work out also work out.

But what You could do is first just build one one of the concerned stb's a gst-1.0 image , then well check that gstreamer-1.0-plugin-dvbmediasink off oe-alliance 4.0 is used.

run a couple off ok media and a couple off not ok media with

GST_DEBUG=dvbaudiosink:4,dvbvideosink:4 enigma2-debug.sh

p.s. the enigma2-debug.sh is a copy off the enigma2.sh  but I modified two lines in it line nr 123 and 125 to 

`LD_PRELOAD=$LIBS /usr/bin/enigma2 --debug-no-color`

**Comment by atvcaptain** [comment]
only amlogic use gst 0.10 all other use gst 1.x, and we wait , sasa add gst 1.x for wetek, then this ready we drop gst 0.10 from git

**Comment by tromoto** [comment]
@christophecvr thx on suggestions, will try
AML gst1.x AV sink will probably be pushed today for Odroid

**Comment by atvcaptain** [comment]
we wait
