### ISSUE TITLE
Add Channel numbers on epg

### ISSUE THREAD

**Issue by davesayers2014** [openatv/enigma2#618]
Could this be looked at https://github.com/openatv/enigma2/pull/546 it was working fine on openatv 5.3 but every time I update to atv 6.0 it makes my box go into boot loop as soon as I add the py files so im not sure whats happening thanks.

**Comment by davesayers2014** [comment]
Can someone tell me if the branch for atv 6 is different for 5.3? At least then I can compare the changes

**Comment by Schimmelreiter** [comment]
5.3 = master and oe-alliance 3.4
6.0 = DEV and oe-alliance 4.0

**Comment by davesayers2014** [comment]
Thanks sorted it. Ill leave it for a dev to look at though because no doubt there will be an error somewhere if you want here are my changes https://github.com/davesayers2014/ATV6.0-Components

**Comment by davesayers2014** [comment]
updated the files to include the latest commits https://github.com/davesayers2014/ATV6.0-Components

**Comment by davesayers2014** [comment]
Bump can this be looked at I will include the latest commits soon

**Comment by davesayers2014** [comment]
Bump I cant seem to add the latest commits.

**Comment by davesayers2014** [comment]
Latest commits added to atv6.0 Components

**Comment by arn354** [comment]
where are latest files? i check again if the old crash is still there next weekend

**Comment by davesayers2014** [comment]
Link above this is for 6.0 only https://github.com/davesayers2014/ATV6.0-Components I have made no changes to the 5.3 files and still cannot recreate the crash reported in the last pull request

**Comment by davesayers2014** [comment]
If you get chance to look at it and still have crashes could this be discussed here https://www.opena.tv/english-section/28560-request-optional-channel-epg.html so we can try to work out whats happening and hopefully resolve it

**Comment by davesayers2014** [comment]
Hi @arn354 did you have chance to look at this? thanks

**Comment by arn354** [comment]
sorry not yet - was on holidays till yesterday

**Comment by davesayers2014** [comment]
Closed

**Comment by davesayers2014** [comment]
I think I have fixed bug if you want to check master is OpenATV 6.1 and OpenATV_6.2 branch is 6.2 https://github.com/davesayers2014/ATV6.0-Components
