### ISSUE TITLE
Wrong SNR for Octagon SF4008 "Si21662" (DVB-S2)

### ISSUE THREAD

**Issue by pizzelnet** [openatv/enigma2#639]
It seems that after the commit _[6429925](https://github.com/openatv/enigma2/commit/642992519c68af76f494f3790a992812068e993c#diff-e3339c476cfa702e84570deec3be6efa) [sf4008] add snr calculation_ the SNR is not calculated properly since the maximum value given in percentage is 63% whereas in images previous to that commit it was 99%.

Regarding the maximum in dB, I commited last night a change to 1620 but I'm not sure that 16.2dB is the maximum as I didn't notice I'm receiving a frequency in Astra 19.2º with 16.8dB, is this then the maximum?

With the same installation, in a Vu+Duo2 I'm getting the maximum dB in most of the transponders of Astra 19.2º, this is not the case with the Octagon tuner.

This is the formula in [frontend.cpp](https://github.com/openatv/enigma2/blob/DEV/lib/dvb/frontend.cpp):
```
ret = (int)(snr / 46.8);
sat_max = 1620;
```

No problem with the "Si21682" (DVB-T2,DVB-C) tuner.

How could we get the SNR percentage working properly again? Could the next be a possible solution?

ret = (int)(snr / **75**);
sat_max = **1680**;

**Comment by garmill** [comment]
I checked my 4008 and on 13E I get maximum 13db (and requesting the percentage in fact I get 81%). On the other hand googling i found users who got 14,2 db on 33E. You are sayng that on 19.2E you get 16.8 ... so i think that the max SNR depends (also) on the satellite (and that could also make sense).
the frontend.ccp supports only one sat_max.. can't be made depending on the satellite. Honestly I'll live with the snr in decibel. I know that 13db for me is the maximum (corresponding to a perfect image, fluid, open and blue sky, dish just tuned via instrumental check). I can't change satellite 'cause disk is 13E fixed. bye.

**Comment by pizzelnet** [comment]
Sorry, I forgot to close the issue as this was fixed with new drivers.
