### ISSUE TITLE
H1 image not detecting DVB-C tuner - Same issue as fixed in 544

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#645]
https://github.com/openatv/enigma2/issues/544

This same issue has been re-introduced.  Please can you ascertain the why this has occurred and fix

**Comment by p17blo** [comment]
Any update on this please? Alternatively, if you could point me towards how to manually install drivers? - I looked through the commits post issue #544 and I can't see how you've fixed it then

**Comment by p17blo** [comment]
Guys, please can we have a fix for this - It's been fixed once before, the fix must be known - If you tell me how to resolve this, I'll fix it myself.  @atvcaptain please can you advise here??

**Comment by atvcaptain** [comment]
update coming soon

**Comment by atvcaptain** [comment]
check images today new
