### ISSUE TITLE
DVB-C tuner always reports 29% or 229% SNR

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#646]
This has been an issue as long as I can remember - I assume it is a known issue but no fix.  DVB-C Tuner (and it doesn't matter which one), always report 29% or 229% SNR (Assuming there is a signal present).  It does not report correct SNR

**Comment by atvcaptain** [comment]
box model tuner model ?

**Comment by p17blo** [comment]
H1, H2, H.2H, H5 - All models all cable tuners

**Comment by davesayers2014** [comment]
My zgemma H2.H has recently changed from 229% to a constant 69%

**Comment by p17blo** [comment]
This does seem to have been fixed in a recent update.  Closing this off
