### ISSUE TITLE
Openwebif a number not str 

### ISSUE THREAD

**Issue by juanako79** [openatv/enigma2#648]
I updated today versión 5.3 2/3 más openwebif doesnt work, says %d format: a number is required, not str

**Comment by Schimmelreiter** [comment]
Using Spanish locale?

**Comment by juanako79** [comment]
Yes 

Enviado desde mi iPhone

**Comment by Schimmelreiter** [comment]
Known bug.

Delete the Spanish translation
`rm /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/locale/es/LC_MESSAGES/OpenWebif.mo`
and wait for the next update.

**Comment by Schimmelreiter** [comment]
Closed by https://github.com/oe-alliance/e2openplugin-OpenWebif/commit/8f35812c845053bc3ce10daa266e704d7fc484ad
