### ISSUE TITLE
Useless pages in First Start Wizard

### ISSUE THREAD

**Issue by Schimmelreiter** [openatv/enigma2#649]
There are useless pages shown in start wizard:
An increasing number of boxes does not have SCART or any other output anymore but only HDMI.

The page where one could earlier chose between HDMI, SCART, RGB is shown anyways with just one option, so no choice.
Can this be changed to auto-select this option and skip the whole page?

Example: Octagon SF4008 has only HDMI.

**Comment by arn354** [comment]
startwizard is a pain... i am allready looking into due to other reason. But you are right - if list returns only one item it should be autoselected.

**Comment by atvcaptain** [comment]
allready fixed we close it now
