### ISSUE TITLE
Openatv 6.0 not receiving nightly updates 

### ISSUE THREAD

**Issue by davesayers2014** [openatv/enigma2#656]
Hi im using OpenAtv 6.0 on zgemma H.2H and noticed that the last update was 08/03/17 while 5.3 has updates till today 13/03/17. Other boxes are receiving 6.0 updates but not zgemmas is there a reason for this?

**Comment by atvcaptain** [comment]
check tomorrow new updates coming

**Comment by CHazz** [comment]
the last weeks can't be upgraded Openatv 6.3 .. stuck on: "Downloading http://nonpublic.space/oea/6/armv7ahf/Packages.gz." it is not an internet problem

**Comment by atvcaptain** [comment]
delete the old feed and use https://bit.ly/2HsG4D7

**Comment by CHazz** [comment]
thanks for quick reply :)
