### ISSUE TITLE
Openatv 6.0 vu+ultimo4k tuner problem

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#657]
Report from the user...

Tuner I not FBC tuner.
Please see screenshots.
![img_0042](https://cloud.githubusercontent.com/assets/1756274/23916744/e5ba7332-08f5-11e7-9f5c-41376761a517.JPG)
![img_0043](https://cloud.githubusercontent.com/assets/1756274/23916761/f1e3dcd4-08f5-11e7-9868-d3b4e0f53f66.JPG)

**Comment by atvcaptain** [comment]
ok we check it

**Comment by olegcyprus** [comment]
Hi guys, I am the one suffering from this problem. I can not use my dvb s2 tuner because of this, could you please look at it. All other images I have tried do not have this mistake. Thank you.

**Comment by atvcaptain** [comment]
fixed with image 21.03.2017
