### ISSUE TITLE
InfoPanel / Quick Launch Icons

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#669]
Do we still need the icons for infopanel/quick launch. 

As a skinner I really dislike these icons. 
They serve no purpose. The icons don't really mean anything.
The icons are not the prettiest and are rather dated.
They are a pain to design skins around because they are so large and do not fit modern skin designs.
And as far as I am aware we can't even override the templatedMultiContent code in my skin code
(please do inform me if this is possible)

The only ones of any benefit are the USB and HDD icons used for HDDMount

So can we move with the times and remove these unnecessary icons. 

Thanks

**Comment by jbleyel** [comment]
Infopanel will be reworked for ATV 7.0
