### ISSUE TITLE
Unable to backup on Evo Slim 

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#670]
When attempting to run a full backup on Evo Slim, part of the backup completes, but then fails with the message: 
Image creation failed

Probable causes could be
wrong back-up destination
no space left on back-up device
no writing permission on back-up device

This is due to the bzip2 package being missing from the image.  Can you please amend build to include bzip2

**Comment by atvcaptain** [comment]
evoslim dont use bzip2

show complete e2 log with issue

**Comment by p17blo** [comment]
There was no log created (as no crash) so I"d have to manually start enigm2 in logging mode - I will revisit this shortly - But I can confidently say that installing bzip2 via OPKG resolved the issue.  I will capture logs next time I can return to this box

**Comment by p17blo** [comment]
Problem does not exist in latest factory images - Closing issue
