### ISSUE TITLE
Weird full stb freezing when recording "Rai Sport" channel

### ISSUE THREAD

**Issue by Tony-il-Capo** [openatv/enigma2#673]
Hi
I have some weird problem on my boxes, a Duo2 and a spark7162/sh4 one, both running OpenATV 6.0, both seem to complete freeze after some time if recording the channel Rai Sport from Hotbird 13E. Tried recording other channels for a few hours and no problems...

Channel broadcasts mostly FTA but also encrypted transmissions.
I only want to record the free stuff!

Boxes go to a complete freeze after some random time if there's a recording running on that channel, vfd, lcd and  tv picture completely freeze, ssh/telnet/openwebif connection is not possible, sound normally keeps going.

I've tried to change time sync to NTP but problem persists.

Could at least someone test this to see if it's reproducible?

Could the epg from that channel be causing this? It seems to me that this happens when a recording timer 'catches' multiple epg events, and when the next event is starting stb freezes, not sure about it.

**Comment by atvcaptain** [comment]
you need a serial cable for your duo2 and must log kernel infos with luck you see a info in the log when not , not easy to find your issue

**Comment by Tony-il-Capo** [comment]
Thanks but I don't have that cable...

I just disabled all epg types to test and then stopped enigma2, removed epg, restarted again, so I ended with no epg at all, then started a infinite recording on that channel, gone take a shower, came back, stb was completely frozen again.

I'm getting literally sick with this problem :( because I watch many volley from that channel.
I will try a clean flash (again!) and even switch tuner feeds.

It would be really helpful if someone else could test this.

**Comment by Tony-il-Capo** [comment]
I'm closing this as it difficult to reproduce and may be related to have oscam running. Shutting down oscam before recording seems to solve the problem. Remember that the channel is broadcasting fta stuff but still I can see it in oscam log, it's trying to descramble it.
