### ISSUE TITLE
MultiBoot STARTUP add support vs1500

### ISSUE THREAD

**Issue by Dima73** [openatv/enigma2#687]
root@vs1500:~# cat /sys/firmware/devicetree/base/bolt/tag
v1.07-r21root@vs1500:~#

need this:
self.bootloaderList = ('v1.07-r19', 'v1.07-r21')

**Comment by atvcaptain** [comment]
ok , look vs1500 now ready to sell
any other new with vs1500 ?

**Comment by Dima73** [comment]
The rest seems to be the same.

**Comment by Dima73** [comment]
Sorry,forgot...
elif ('boxmode' not in ENTRY and len(ENTRY) > 96) or ('boxmode' in ENTRY and len(ENTRY) > 114):

need len(ENTRY) > 115

**Comment by atvcaptain** [comment]
ok i change this, we dont have this model , so never check it :)
