### ISSUE TITLE
Setting AutoTimer on Stream causes crash

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#688]
I wasn't sure where to log this issue as it's with AutoTimer, which appears to be included in core build, but is essentially a plugin.  If this is logged in the wrong place, please could you point me to the correct place to log the issue.

The issue occurs when creating an autotimer from EPG for an IPTV Bouquet (Stream).  It will initially allow you to capture details of the autotimer, but at the point of final save a crash occurs and the autotimers.xml file is corrupted and blanked.

I also tested setting this up as a standard timer instead of an autotimer and all works fine.

I think this maybe down to the long string that comes with the stream URL

I've attached a crash log, although I've had to obfuscate some of it as it contained credentials

[enigma2_crash_1494983224.txt](https://github.com/openatv/enigma2/files/1007516/enigma2_crash_1494983224.txt)

**Comment by boojieben** [comment]
This is a massive bug. I can't believe it's been ignored for a month. I can't be the only person wanting to run series link on a stream?

**Comment by atvcaptain** [comment]
you use atv 5.3 its end of support, have you test with atv 6.0 or 6.1 too ?

**Comment by p17blo** [comment]
It's definitely the same error for 5.3 as it is for 6.0 so it's safe to assume that if no coding changes have been implemented for 6.1 that there error will persist.

**Comment by p17blo** [comment]
@atvcaptain I see there have been a number of commits for autotimer. Has this issue. Ow been addressed?

**Comment by almighty78** [comment]
This bug still exists and no indication if it will be fixed in future builds.

**Comment by jbleyel** [comment]
I have create a new AutoTimer for a IPTV Bouquet and for a single IPTV Channel.
NO PROBLEM.
OpenATV 6.3 / latest plugins from yesterday.

Are you really have IPTV bouquet issue or do you mean IPTV channel?
If you have an IPTV bouquet issue please provide the content of /etc/enigma2/bouquets.tv and mark the affected bouquet.

**Comment by jbleyel** [comment]
Can we close this?
