### ISSUE TITLE
EventView date/time edit

### ISSUE THREAD

**Issue by gersey** [openatv/enigma2#690]
I would like the "EventView.py" line 308 to be editable for translators because, for example the correct Hungarian format would be:

> %Y.%m.%d, %H:%M - %s (2017.05.19, 04:12 - program name)

`text += _('\n%d.%d.%d, %2d:%02d  -  %s')%(t[2], t[1], t[0], t[3], t[4], x[0])`

**Comment by atvcaptain** [comment]
allready fixed
