### ISSUE TITLE
Inputstream.Adaptive

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#705]
Can the Peak3d inputstream.adaptive be compiled for Mips to use with Kodi in OpenATV ?

Ive managed to install the Generic Linux version, which then does allow for BBCIplayer 3.xx versions to be installed and then Ive successfully compiled the libssd_wv.so for Mips, however when enabled it still states that its unable to load shared library's, so obviously I'm still missing something.

If the OpenATV Dev's could compile this for our platform, then it would not only allow for DASH streams to be played, which is cool, but more importantly it would allow for the playing of DRM protected content, yes that's correct, DRM, how awesome is that on our E2 boxes ? 

Many addons are now starting to use inputstream.adaptive and its sadly missing in our E2 Kodi versions. Ive searched everywhere online for a Mips version, but it just simply does not exist.

**Comment by ian10951** [comment]
Anyone ?

I saw in the release note of ATV 6.1 ( translated badly from German ) that the Dev's were looking for people to post idea's on how Kodi could be improved on Enigma2, well adding this would be the biggest improvement to Kodi running on E2 since it was first added to our boxes. But I think it has to be built together with Kodi and added to the Kodi recipes ? Anyway, I cannot build it, that's for sure.

**Comment by arn354** [comment]
Basically we were asking for People to apply changes - due to our limited ressources we can't maintain it care about everything.

**Comment by messi89** [comment]
Hi

Is there any news about the inputstream adaptive plugin on ATV ?

**Comment by jbleyel** [comment]
Can we close this?

**Comment by jbleyel** [comment]
Issue closed .. please open a new one if the error still exists.
