### ISSUE TITLE
EPG List Doesnt show when using 5002

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#707]
EPG list and Picons don't show from Streams placed in Bouquets when using either 4097, 5001 or 5002 from Serviceapp
The only way to get the EPG to show is to flag the Streams Service Ref as 1 in the stream which then overrides the Servicapp setting and so uses Gstreamer and not Exteplayer3 with ffmpeg, therefore making the Serviceapp setting redundant.

Its the same scenario if you flag the Stream itself with anything other than 1

Perhaps something simple similar to this can be added to the converter ?

if not sname.startswith('1'):
					sname = sname.replace('4097', '1', 1).replace('5001', '1', 1).replace('5002', '1', 1)
				if ':' in sname:
					sname = '_'.join(sname.split(':')[:10])

**Comment by arn354** [comment]
You could propose a pull-request once locally tested - maybe for picons first. You can find the used renderers here: https://github.com/openatv/enigma2/tree/master/lib/python/Components/Renderer
I am on holidays right now - could look into next week

**Comment by ian10951** [comment]
The strange thing is that the EPG is still passed to the InfoBar, although the Picon as stated is not, I presume this is because the Now and Next don't use the EPG DAT file ? But the 7 day EPG does.

**Comment by ian10951** [comment]
I've partially address this issue and I now have EPG when pressing the EPG/Info button, by editing the EpgList.py like so

[code]    def fillSingleEPG(self, service):
        t = time()
        epg_time = t - config.epg.histminutes.value * 60
        ext3=service.ref.toString()
        if ext3.startswith("5002:"):
            service2=ext3.replace("5002:","1:",1)
        else:
            service2=ext3		
        test = [ 'RIBDT', (service2, 0, -1, -1) ]
        self.list = self.queryEPG(test)
        self.l.setList(self.list)
        if t != epg_time:
            idx = 0
            for x in self.list:
                idx += 1
                if t < x[2] + x[3]:
                    break

            self.instance.moveSelectionTo(idx - 1)
        self.selectionChanged()

    def fillMultiEPG(self, services, stime = None):
        test=[]
        for service in services:
            ext3=service.ref.toString()
            if ext3.startswith("5002:"):
                service2=ext3.replace("5002:","1:",1)
            else:
                service2=ext3
            test.append((service2, 0, stime))
        test.insert(0, 'X0RIBDTCn')
        self.list = self.queryEPG(test)
        self.l.setList(self.list)
        self.selectionChanged()[/code]

However, the channels list in the Bouquets still doesnt have EPG against each channel as it should.

Does this use another file to populate and if so could you tell me what it is please, or is there still a problem with my modified code above ?

Ian.

**Comment by ian10951** [comment]
With today's update of Serviceapp to include the EPG fix that mx3L added nearly 12 months ago now and the removal of the obsolete check, this issue is now resolved.

Hopefully, the next update of Serviceapp wont take as long, because the Test branch has some new and very interesting mods.
