### ISSUE TITLE
Custom user-agent

### ISSUE THREAD

**Issue by messi89** [openatv/enigma2#712]
Hi guys

Is there an option on open atv to use a custom user-agent ? it will be usefull with some iptv server

Thanks

**Comment by 4l3x2k** [comment]
@messi89 
If you're using 4097 reference type (servicemp3) in your bouquet you could try to add the following to your path
`#User-Agent=<YourUserAgent>`.

The following is a complete bouquet entry example
```
#SERVICE 4097:0:2:0:0:0:0:0:0:0:http%3A//stream.klassikradio.de/movie/aac-64#User-Agent=Enigma2:Klassik Radio Movie
#DESCRIPTION: Klassik Radio Movie
```

If you're using a plugin you would need to ask the plugin community who maintain and develop the plugin.
