### ISSUE TITLE
Zgemma S2 box Crashes

### ISSUE THREAD

**Issue by Babloo85** [openatv/enigma2#718]
Hello I just bought a zGemma S2 box off eBay and it had so much crap from the previous user so I decided to reset to factory settings. It did restart the box and now its stuck in the loop where it shows we are really sorry your receiver encountered a problem and needs to be restarted. Please login to ******* and send file to opena.tv and then it restarts again.
Could anyone help please ?

![img_1373](https://user-images.githubusercontent.com/29802206/27745995-70a050cc-5dbd-11e7-8158-4c0ae017ed48.JPG)
![img_1371](https://user-images.githubusercontent.com/29802206/27745997-73cdcc34-5dbd-11e7-80cc-829de63c83d9.JPG)

**Comment by atvcaptain** [comment]
download a new image and install new http://images.mynonpublic.com/openatv/nightly/index.php?open=zgemmas2s

**Comment by Babloo85** [comment]
I just did it but still same error.

**Comment by atvcaptain** [comment]
not possible in fresh image no autobouquetsmaker include and you screen show this, you dont have install fresh

**Comment by Babloo85** [comment]
I install it again and send you the new picture in a bit. Because that screen is before installing.

**Comment by Titaniumviper** [comment]
Hello,
Did this ever get resolved as I am having the same issue

**Comment by AbuBaniaz** [comment]
Factory reset does not do what the name suggests. Best way to factory reset is to flash an image and not restore any settings or plugins.

BTW, the screenshot shows AutoBouquets, not AutoBouquetsmaker. Both plugins install and function fine on OpenATV. IMO, this issue should be closed
