### ISSUE TITLE
servicemp3.cpp m_to_paused error

### ISSUE THREAD

**Issue by Raxone** [openatv/enigma2#732]
Error on both enigma2 6.0 and 6.1 builds.

|   ^~~~~~~~~~~~~~~~~~~~
| service/servicemp3.cpp: In member function 'RESULT eServiceMP3::trickSeek(gdouble)':
| service/servicemp3.cpp:1200:4: error: 'm_to_paused' was not declared in this scope
|     m_to_paused = false;
|     ^~~~~~~~~~~

I fix it with comment 
//m_to_paused = false;
???

**Comment by atvcaptain** [comment]
you have forget say you use wetek with gst 0.10 or ?

**Comment by Raxone** [comment]
I use openatv git without any changes, gst is 0.10

**Comment by atvcaptain** [comment]
fixed
