### ISSUE TITLE
CrossEPG 0.6.2 returning DVB service

### ISSUE THREAD

**Issue by davesayers2014** [openatv/enigma2#739]
[Enigma2-debug-20170804_10-40-55.zip](https://github.com/openatv/enigma2/files/1199946/Enigma2-debug-20170804_10-40-55.zip)
Hi im using CrossEPG 0.6.2 on Zgemma H.2H as CrossEPG 0.8.3 doesnt work it gets stuck at 586 kb and 0.6.2 has been working fine until recently.

The issue is if I use Autobouquets Maker to scan for channels then run a crossepg scan it skips straight to DVB service without any errors but if I do a manual scan on my sat tuner crossepg works fine. Here is a log while doing a CrossEPG scan without doing a manual scan I hope someone can work out what is happening thanks

If needed I can provide more logs.

**Comment by davesayers2014** [comment]
No help? If in the wrong place then please link me to where I should be posting also why doesnt latest CrossEPG work?

**Comment by arn354** [comment]
crossepg and autobouquetsmaker are mostly used in the uk. maybe openVIX can be of a help.

**Comment by davesayers2014** [comment]
Latest crossepg works fine on Vix. Vix don't support zgemma so it will be unlikely to get help from them.

**Comment by davesayers2014** [comment]
Ok ill close this as it will probably never get looked at. Another thing to note is latest CrossEPG works on OpenATV on other boxes just not zgemma and CrossEPG works fine on unsupported vix images so im not sure who/where to report the issue and what the problem is thanks

**Comment by davesayers2014** [comment]
Thanks for fixing but communication with OpenATV is hard maybe due to language barrier, again thanks for fixing it. 

https://github.com/oe-alliance/oe-alliance-core/commit/54dd1ad868fb7a1a8b85b41879246d9be2c2cb7a
