### ISSUE TITLE
OpenVPN plugin can't select config file

### ISSUE THREAD

**Issue by maxbambi** [openatv/enigma2#745]
OpenVPN plugin simply sends the command "/etc/init.d/openvpn start" without any option.
A command with conf file name will be appreciate.

**Comment by arn354** [comment]
**https://github.com/oe-alliance/oe-alliance-core/blob/10764e1f81c7079c83c1a71ab64845d4e254d85c/meta-oe/recipes-connectivity/openvpn/openvpn/openvpn#L11**

/etc/init.d/openvpn looks in /etc/openvpn - please propose any change in oe-alliance as pull request.

**Comment by maxbambi** [comment]
Script /etc/init.d/openvpn works perfectly...
Using a terminal, you can start VPN with command 
`/etc/init.d/openvpn start pippo`
and pippo.conf will be used.
But there isn't a way to send this command in GUI.
I suggest a text field where user can write the name of conf file...
