### ISSUE TITLE
Unable to reference and skin - recordings and timeshift setup screens

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#747]
<screen name="setup_recording" ...> and <screen name="setup_timeshift" ...>
These references do not work. It just loads the default "Setup" screen.
Strange as most of the other references like setup_display, setup_epgmulti etc all work. 

The reason I need to reference these screens is because of the rather long text in the recording settings.
It just doesn't fit normal font sizes. It even breaks on Metrix skin. 

"Show recording symbol depending on recording type"
"Show warning before box restart based on recording type"

So can we fix the setup_recording reference, or can we alter this long text to something shorter.
"Show recording symbol..."
"Show warning before restart"

Also in setup.xml 
Clean network trash can's (spelling error - no apostrophe needed)

**Comment by atvcaptain** [comment]
fixed with image after 5.10.2017
