### ISSUE TITLE
Support for updated TP-LINK WIFI ADAPTERS

### ISSUE THREAD

**Issue by devlo** [openatv/enigma2#750]
Hi,
Any plans to support updated version of new TP-LINK 722N v2 wifi usb adapters?

https://wikidevi.com/wiki/TP-LINK_TL-WN722N_v2

Becasue they are not working on openatv 6.0/6.1 nightly.

They were added in april this year to rtl8188eu driver:

https://github.com/lwfinger/rtl8188eu/issues/206

**Comment by s3n0** [comment]
16.2.2018 - OpenATV 6.1
```
opkg list | grep 8188eu

enigma2-plugin-drivers-network-usb-r8188eu - 1.0-r2 - Single-Chip IEEE 802.11b/g/n 2T2R WLAN Controller with USB 2.0 Interface

firmware-rtl8188eu - 1.0-r1 - Firmware for RTL8188EU

kernel-module-r8188eu-4.10.6 - 4.10.6-.3 - r8188eu kernel module
 r8188eu kernel module; Realtek Wireless Lan Driver

```

**Comment by atvcaptain** [comment]
long time include i close
