### ISSUE TITLE
mmi_ui.cpp processMMIData

### ISSUE THREAD

**Issue by antoniovalenzuela** [openatv/enigma2#757]
Maybe it is not an issue but I need help on the following error.

- OpenATV 6.0 (DM900)
- CAM CI+ Conax
- Extension socketmmi 6.1+git24814+95368c6-r4
- Plugin ciplushelper 2.3-r12

Auth between host and cam is successfull but after connect Conax smartcard apperars the message "No Access (12)". I would like to know the meaning of code 12.

23:03:46.4670 mmi/mmi_ui.cpp:254 mmiScreenAddText [eMMI_UI] mmiScreenAddText(No access (12))
23:03:46.4671 mmi/mmi_ui.cpp:269 mmiScreenAddText [eMMI_UI] addText No access (12) with id 3
23:03:46.4671 mmi/mmi_ui.cpp:117 
processMMIData [eMMI_UI] No access (12)
23:03:46.4671 mmi/mmi_ui.cpp:288 mmiScreenFinish [eMMI_UI] mmiScreenFinish

[enigma2.txt](https://github.com/openatv/enigma2/files/1245343/enigma2.txt)

**Comment by arn354** [comment]
If i recall correctly the displayed messages are coming from the module itself and are not common between all available modules

**Comment by atvcaptain** [comment]
install ciplushelper 4.0
