### ISSUE TITLE
Plugin Feeds disappeared for Zgemma 

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#762]
A large number of plugins have disappeared from the installable list for Zgemma boxes.  Currently tested V6.0 and the likes of EPG Importer are missing, which are still available on the Vu box feeds - Even test Vu running 5.3 and plugin list is full.

I'm not sure what I can do to help assist identify the problem, but if you want any testing done, please let me know

**Comment by arn354** [comment]
5.3 is no longer maintained. Do not expect a fix for those feeds - they will be offline for other boxes aswell any time in the future.
6.0 or 6.1 should have the current feeds. If not - are all packages.gz's properly updated? Enter in telnet:
`opkg update`
post the result here.

**Comment by p17blo** [comment]
So firstly I was saying the feed is STILL PRESENT on 5.3 (for VU) - This was just for info.

Results from opkg updateon zgemma h5 running 6.0

`root@zgemmah5:~# opkg update
Downloading http://feeds2.mynonpublic.com/6.0/h5/3rdparty/Packages.gz.
Updated source 'openatv-3rdparty'.
Downloading http://feeds2.mynonpublic.com/6.0/h5/all/Packages.gz.
Updated source 'openatv-all'.
Downloading http://feeds2.mynonpublic.com/6.0/h5/h5/Packages.gz.
Updated source 'openatv-h5'.
Downloading http://feeds2.mynonpublic.com/6.0/h5/h5_3rdparty/Packages.gz.
Updated source 'openatv-h5_3rdparty'.
Downloading http://feeds2.mynonpublic.com/6.0/h5/mips32el/Packages.gz.
Updated source 'openatv-mips32el'.
Downloading http://secret.mynonpublic.com/mipsel/Packages.gz.
Updated source 'secret-feeds'.
Downloading http://ipab.tv/feeds/Packages.gz.
Updated source 'user-feeds'.
Downloading http://feeds2.mynonpublic.com/6.0/h5/zgemmah5/Packages.gz.
Updated source 'openatv-zgemmah5'.`

**Comment by p17blo** [comment]
@arn354 this seems to be affecting ONLY the H5 (I've checked other Zgemmas) - Any idea of how to fix?

**Comment by davesayers2014** [comment]
I haven't got an h5 to check but should the third party feeds package be empty? http://feeds2.mynonpublic.com/6.0/h5/h5_3rdparty/Packages.gz

**Comment by atvcaptain** [comment]
wait 24 h , build server have sync issue, we working on it

**Comment by p17blo** [comment]
This issue is now resolved
