### ISSUE TITLE
EPG Using 5002, 5001 and 4097 Fixed by Pli

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#767]
Is OpenATV going to follow suit ?

Pli have fixed this ongoing issue by simply removing an obsolete check.

https://github.com/OpenPLi/enigma2/commit/5a8a06308ac759174dcebb23158e55eeae5f8ade

We need ATV to do the same. We also need ATV to update to the latest mx3L Serviceapp too, there are many new modifications.

Ian.

**Comment by atvcaptain** [comment]
done
