### ISSUE TITLE
Zgemma LC running OpenATV 6.1, complete backup fails (Kernel Dump Error)

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#774]
Zgemma LC running OpenATV 6.1 (latest nightly release) does not allow a complete backup to be taken and fails with Kernel Dump Error

A key error displayed appears to be:
"chmod /hdd/bi/rootfs.bin: No such file or directory"

Upon checking that directory it contains:
root.ubi (file size 94,633,984)
ubinize.cfg (file size 103)
vmlinux.gz (file size 6,291,456)

Please advise if something is missing or how to fix

**Comment by arn354** [comment]
Please provide full debug-log of enigma2 including a failed backup process.

**Comment by atvcaptain** [comment]
must go, all zgemma work identically

**Comment by p17blo** [comment]
Please see attached log - It doesn't seem to capture a lot - This was collected using the syntax:

> init 4
> enigma2.sh >/tmp/log.txt

After logging was started and system was running, I ran a complete backup which generated the 'Kernal Dump Error' on the GUI screen

Is there a way to capture more detailed logging?

[log.txt](https://github.com/openatv/enigma2/files/1292339/log.txt)

**Comment by arn354** [comment]
why don't you use the simple option which is available to turn on debug-log in gui of enigma2?

**Comment by atvcaptain** [comment]
its user issue we close now here
