### ISSUE TITLE
OpenATV6.1 Creating AutoTimer on IPTV bouquet stream does not generate timer

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#775]
When selecting autotimer on an IPTV stream within a bouquet, an autotimer is created, however this does not generate a timer event and such nothing ever records

Please let me know if you need further information or logs as I will gladly provide these.

**Comment by almighty78** [comment]
I have the exact same problem. Running ATV6.1. I've tried this through the webif front end and the  "Test" on the autotimer only shows non-IPTV channels. It doesn't seem to be searching the EPG of the IPTV channels.

**Comment by arn354** [comment]
True - we are happy about any improvement provided as pull-request.

**Comment by almighty78** [comment]
Thank you arn354. Sorry I'm not very familiar with github. Is there anything you need me to do?

**Comment by jbleyel** [comment]
Do you really have EPG on a IPTV Channel.
If yes then create a issue here -> https://github.com/oe-alliance/enigma2-plugins

**Comment by jbleyel** [comment]
Fixed here -> https://github.com/oe-alliance/enigma2-plugins/issues/177

**Comment by jbleyel** [comment]
this is not an enigma2 issue.
