### ISSUE TITLE
Serviceapp

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#786]
mx3L has updated the Serviceapp plugin again this time to allow the exposure of all Exteplayer3 settings.

Post 654 here

https://forums.openpli.org/topic/41198-serviceapp-gstplayer-and-exteplayer3/page-33

This will allow many Exteplayer3 features to be used, by users and plugin writers.

Can you please build the latest Serviceapp so we too using OpenATV can have this update ?

Ian.

**Comment by thawtes** [comment]
already in the latest version...  (git106)

issue can be closed

**Comment by ian10951** [comment]
The current version we have may be the latest version number, but it most certainly does not have the latest code and updates. Some of these updates are very useful indeed.

So are you saying we are not going to get them until mx3L updates his version number ?

**Comment by thawtes** [comment]
branch develop needs to change with master... (openatv)
or
mx3l needs to update develop branch

**Comment by thawtes** [comment]
hi @atvcaptain , 
pls change bitbake code _**enigma2-plugin-systemplugins-serviceapp.bb**_

branch=develop to master branch for OE4.0 and OE4.1

if it is not a problem

thx

**Comment by ian10951** [comment]
Any update on this ?

Having the new options in our Serviceapp on ATV like Pli have in their version, would be of great benefit to all users and many would be grateful of the new Serviceapp build on the ATV feeds.

**Comment by atvcaptain** [comment]
done
