### ISSUE TITLE
Auto Resolution Plugin doesnt work with 720p/60fps

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#834]
There is no option to set the Auto Resolution settings when a stream uses 60fps and its in 720p

The result is the TV remains in 50fps mode and therefore the picture judders upon fast movement or if a banner moves across the screen.

A typical example of this is any stream from Fox Sports or ESPN Play when using Kodi

**Comment by jbleyel** [comment]
please open a issue here -> https://github.com/oe-alliance/enigma2-plugins
