### ISSUE TITLE
Error List when boot up !

### ISSUE THREAD

**Issue by thawtes** [openatv/enigma2#837]
hi, my device Vu+ Duo2 , latest openATV 6.1

ERROR LIST when Boot Up

[ E ] gdi/fblcd.cpp:37 eFbLCD [eFbLCD] /dev/fb1 No such file or directory
[ E ] gdi/fblcd.cpp:77 eFbLCD [eFbLCD] framebuffer /dev/fb1 not available
[ E ] gdi/fb.cpp:202 showConsole [fb] setting /dev/tty0 status failed.
[ E ] driver/rfmod.cpp:27 eRFmod [eRFmod] couldnt open /dev/rfmod0: No such file or directory
[ E ] driver/misc_options.cpp:48 detected_12V_output [Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: No such file or directory
{ E } skin.py:66 addSkin [SKIN ERROR] attempt to add a skin without filename
{ E } RecordTimer.py:36 <module> [RecordTimer] import from 'Screens.InfoBar import InfoBar' failed: cannot import name InfoBar
{ E } Components/InputDevice.py:48 getInputDevices [iInputDevices] getInputDevices  <ERROR: ioctl(EVIOCGNAME): [Errno 25] Inappropriate ioctl for device >
[ E ] driver/avswitch.cpp:108 haveScartSwitch [eAVSwitch] cannot open /proc/stb/avs/0/input_choices: No such file or directory
{ E } Plugins/Extensions/CutListEditor/plugin.py:19 <module> [CutListEditor] import MovieCut failed
{ E } Components/PluginComponent.py:56 readPluginList Plugin  Extensions/WebInterface failed to load: No module named plugin
{ E } Components/Pixmap.py:133 setPixmapNum setPixmapNum(0) failed! defined pixmaps: []
{ E } plugin/controllers/SR.py:24 __init__ SerienRecorder plugin not found
{ E } plugin/controllers/ER.py:25 __init__ EPG Refresh Plugin not found
[ E ] gdi/accel.cpp:357 accelAlloc [gAccel] accel alloc failed
[ E ] gdi/gpixmap.cpp:146 gSurface [gSurface] ERROR: accelAlloc failed

thanks...

**Comment by atvcaptain** [comment]
use you ready channel list or import ready setting ? can you test scan all tp new and check again

**Comment by thawtes** [comment]
all tp ok not problem..
**now i realized something, this problem only happens when the CI slot has modules !**

**Comment by thawtes** [comment]
after the last initscripts updates, the tuner problem no longer exists !

**Comment by Schimmelreiter** [comment]
Strange ... I don't see the link between those and your tuner problem ... especially as already the very first revision was heavily tested with exactly the Vu+ Duo2 
In fact, in my household it even was the Duo2 that gave the initial idea for all my latest backup & (fast) restore changes. ..
My wife occupies it all day long, so it always was the least updated box ... that made me look for ways to restore it fast and complete  (incl. the additional Sundtek-Tuners).
Our Duo2 has 4 DVB-S2 tuners and rest assured my wife would have let me know if only a single one of them was not working :)

**Comment by thawtes** [comment]
:) tuner problem is different from this list of problems!
no tuner problem after last update (initscripts packs).
this list is not relevant to tuner issue!
I wrote this error messages in order to correct the related error.

samples;
{ E } plugin/controllers/SR.py:24 init SerienRecorder plugin not found
{ E } plugin/controllers/ER.py:25 init EPG Refresh Plugin not found
{ E } Plugins/Extensions/CutListEditor/plugin.py:19 [CutListEditor] import MovieCut failed ...

I think that if they are corrected, the device startup speed may be better or it may work more stable.
so I wrote this list. :)

thanks...

**Comment by Schimmelreiter** [comment]
These two are simply to explain:
'''{ E } plugin/controllers/SR.py:24 init SerienRecorder plugin not found
{ E } plugin/controllers/ER.py:25 init EPG Refresh Plugin not found'''

They are caused by the OpenWebif trying to initialise its support for the EPGRefresh and the SerienRecorder plugins by importing their Webif integration code snippets.

If these plugins are found, support for them in OpenWebif is initiated, if not, then not :)

**Comment by thawtes** [comment]
thanks :)
