### ISSUE TITLE
Editing DNS via netwrk menu

### ISSUE THREAD

**Issue by davesayers2014** [openatv/enigma2#852]
Hi I have had issues changing DNS on box via network menu if you change the option and set a custom nameserver it doesn't remember the change after a reboot.

Solution Ive used is putty to talnet init 4 to put enigma2 to sleep then edited the resolv.conf file in etc then used init 3 to restart enigma2, editing the file whilst enigma2 is running doesn't save the changes on restart.

So maybe something can be changed within the network menu to be able to save the changes on restart.

Another option ive seen is,

you need to edit  a system file, comment out 5 lines towarsd the end of /etc/udhcpc.d/50default

Comment out the following lines (about line 45)
[code]
                if [ -x /sbin/resolvconf ]; then
                        echo -n "$R" | /sbin/resolvconf -a "${interface}.udhcpc"
                else
                        echo -n "$R" > "$RESOLV_CONF"
                fi

[code]
you may need to restart network after. Im not sure what issues it may cause editing 50default
[50default.zip](https://github.com/openatv/enigma2/files/1515388/50default.zip)

**Comment by atvcaptain** [comment]
fixed with 7.0 images
