### ISSUE TITLE
no indication LCD display

### ISSUE THREAD

**Issue by e2world** [openatv/enigma2#853]
Gigablue UE 4k playback via standard PVR function (EMC), no contents in LCD display

**Comment by arn354** [comment]
which lcd-skin? All? is the screen defined in the used lcd-skin xml?

**Comment by e2world** [comment]
Standard, no change LCD skin, no download LCD skin, myMetrixLite 1080p

**Comment by e2world** [comment]
Sorry my error does not default it is installed https://github.com/oe-alliance/enigma2-display-skins/tree/master/skins/display220/OE-A_LCDSkin_5

**Comment by atvcaptain** [comment]
no issue only info
