### ISSUE TITLE
French TV channel CANAL+ (DVB-T)  CI+ issue!

### ISSUE THREAD

**Issue by jeanpat2** [openatv/enigma2#855]
Module SmarCAM STRONG initialization error:

OK with OpenATV 5.3
Not OK OpenATV 5.4
Not OK with OpenATV 6.1 (and all alternatives images)

Gear: GigaBlue HD Quad Plus Module SmarCAM STRONG (TNT CANAL READY) (P/N :CI0311- CPT02 R1.2, SmarDTV SmarCAM 3, Version software 07.00.01.00.10.R) Card CANAL+ TNT CANAL READY (Nagravision 0 61.335.xxx.xxx xx)

**Comment by e2world** [comment]
@Papi2000
ci+ for legal rights not available in these images...

**Comment by jeanpat2** [comment]
OK I found a solution with ci plus helper plug in.
