### ISSUE TITLE
HDMI cec volume doesnt work within HBBTV

### ISSUE THREAD

**Issue by MartB** [openatv/enigma2#857]
Cant get it working on my VUSolo2 but i know its possible. Any pointers on where i need to look ?

Might this only be possible with a kernel level handling of the cec commands instead of userspace python as the hbbtv uses a different way to change volume ?

**Comment by MartB** [comment]
I just tested this today and its still applicable.

Im going to dump all the informations i gathered here, maybe we can try to fix this this year 👍 

**Gist:**
Basically the hbbtv plugin (https://github.com/oe-alliance/oe-alliance-plugins/blob/master/HbbTV/src/hbbtv.py#L18) locks the RemoteControl Input. Thus disabling the calls to the listeners which in turn stops the event processing for the HDMI-CEC driver 
- for the handler: https://github.com/openatv/enigma2/blob/6.4/lib/driver/hdmi_cec.cpp#L568
- for one of the places that stop the event calls https://github.com/openatv/enigma2/blob/6.4/lib/driver/rc.cpp#L66

**Proposed solution #1 - untested**
The RC driver could get an optional `ignoreLock` attribute that allows global system things like the HDMI-CEC driver to function even if another application locked the inputs.

One of the problems with this is that the HDMI-CEC driver needs some sort of selective "ignore" otherwise key events other than vol up/down could interfere with the hbbtv binary. 

**Proposed solution #2 - untested**
Hook `setVolume, volUp, volDown` inside https://github.com/openatv/enigma2/blob/6.4/lib/python/Components/VolumeControl.py calls and make them execute hdmicec calls.

This would be a system wide implementation but could end up super hacky and with unintended sideffects.

**Proposed solution #3 - tested working, bad UX**
Hook `_CB_CONTROL_VOLUME_UP` and `_CB_CONTROL_VOLUME_DOWN` of the hbbtv plugin and forward the inputs to the hdmicec driver using `eHdmiCEC.getInstance().sendMessage(adr, msg, len(data), str(data))`.

The only downside for this is, that no real keyDown + keyUp event chain is possible, as the callbacks only fire on keyUp resulting in a weird hdmi cec message and no key repeat support.

If i got something wrong, please correct me as thats the first time im playing around with enigma2.

**Comment by jbleyel** [comment]
Hi @MartB ,
Solution 1 is bad
Solution 2 is not so easy because VolumeControl will not called if volume forwarding enabled
Solution 3 seems to be the only way but there are some extra things todo in hdmicec module and we need to prevent break other images

**Comment by jbleyel** [comment]
Please add this to Components/hdmicec.py inside of the `HdmiCec` class.

```
	def keyVolUp(self):  # keyVolUp for hbbtv
		if self.volumeForwardingEnabled:
			self.keyEvent(115, 0)
			self.keyEvent(115, 1)
			return 1
		else:
			return 0

	def keyVolDown(self):  # keyVolDown for hbbtv
		if self.volumeForwardingEnabled:
			self.keyEvent(114, 0)
			self.keyEvent(114, 1)
			return 1
		else:
			return 0


```

Then add this to the init function of the VBHandler of the hbbtv plugin.


```
		self.hdmi_cec = None
		try:
			from Components.HdmiCec import hdmi_cec
			if hdmi_cec.instance and "keyVolUp" in hdmi_cec.instance:
				self.hdmi_cec = hdmi_cec.instance
		except ImportError:
			pass

```

Then add this to the beginning of the set_volume function in VBHandler.

```
		ret = 0
		if self.hdmi_cec:
			if volume == 5:
				ret = self.hdmi_cec.keyVolUp()
			else:
				ret = self.hdmi_cec.keyVolDown()
			if ret:
				return


```

**Comment by jbleyel** [comment]
closed by https://github.com/oe-alliance/oe-alliance-plugins/commit/91b2da33dcfe76562ab56fd1729ee5c179b0d971
