### ISSUE TITLE
TAP/TUN not installed/working on i55 image

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#868]
There has been an ongoing issue with TAP/TUN with Zgemma images.  In testing at least the new H5 image is working.  I have just reflashed the i55 with the latest nightly build (20180108) and upon installing OpenVPN either the TAP/TUN dependancies are not installing or the wrong kernal version are not installing.  I've even manually tried to install the dependancy (kernel-module-tun-4.10.12) which installs, but initiating openvpn causes a TAP/TUN failure.  Error is included below.  If there is anything else you would like me to do to help troubleshoot please let me know, otherwise could you please investigate and provide a fix?

`Wed Jan 10 15:37:22 2018 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Wed Jan 10 15:37:22 2018 Exiting due to fatal error`

**Comment by atvcaptain** [comment]
have you insmod the tun driver  check load  with

lsmod

**Comment by p17blo** [comment]
Not sure what I'm looking at there but here is the output of lsmod

`root@zgemmai55:/etc/openvpn# lsmod
Module                  Size  Used by
ipv6                  425362  35
boxmodel                1556  0
xfs                   803190  0
libcrc32c               1082  1 xfs
i55                  6978014  1
i55_3                  34257  1 i55
i55_2                  23103  0
i55_1                   8701  3 i55_2,i55_3,i55`

**Comment by p17blo** [comment]
OK, i think I understand what is needed - I'd manually installed the TUN package but it wasn't running, after a reboot it was running and now will connected.  
Should this have installed automatically as part of the OpenVPN dependencies?  I'm not sure why my experience is different on i55 to H5 when both were flashed, openvpn installed in the same manner

**Comment by atvcaptain** [comment]
the openvpn have a depend 

RRECOMMENDS_${PN} = "kernel-module-tun"

when load from feed and kernel-module-tun present its load too

after restart drivers load and proc interface was ready
