### ISSUE TITLE
IPTV recording settings handled differently to SAT recording

### ISSUE THREAD

**Issue by almighty78** [openatv/enigma2#869]
Hi,

It seems that the recording settings are only being applied to Satellite recordings and not IPTV recordings.
Specifically, 
1) Default action : When set to 'zap and record' it only gets applied to Sat recordings and not IPTV recordings
2) Composition of recording filenames : When set to 'standard' it looks like IPTV recordings still get long filename e.g. 20180110 2157 - Cartoon Network - The Amazing World of Gumball.stream
3) Recording Description : The details or description of the recorded program gets copied on Sat recordings but doesn't on IPTV recordings.

It could be the case that all the recording settings are not being applied to IPTV recordings. Just the ones above are the issues I personally encountered. 
I can supply logs files and any other information that's needed.
I'm using OpenATV 6.1.

**Comment by arn354** [comment]
yes - as you basically run a satellitereceiver and not a iptv client box.
we are happy about any improvement - but due to our lack of time (and/or knowledge) we are not able to implement everything anyone is expecting. In my case i do not use IPTV with my STB'S at all - so my interests in those requests are really low. I have other small and cheap android boxes or my tv to use IPTV.

**Comment by almighty78** [comment]
Thanks for the reply arn. My biggest issues with with the recording description not getting copied. I just wish I had the expertise to do it myself :-(

Thanks again.

**Comment by arn354** [comment]
maybe someone else jumps in

**Comment by betacentauri** [comment]
I looked into the code. The code generates a .meta file and if EPG data is present also a .eit file. Does e2 create these 2 files on your box?

**Comment by almighty78** [comment]
Hi Beta,

Three files are created by the recording. 
.stream (which is the actual video)
.stream.meta (seems to have the program description)
.streameit (yes thats streameit and not stream.eit)

Many thanks,

**Comment by betacentauri** [comment]
Oh, that looks line a bug. I try to look at it this evening. 

When you rename the streameit to stream.eit, do you see the recording description?

**Comment by almighty78** [comment]
Yep when I rename it I can see the description. I've even crontabbed an hourly script to rename the files for me. 
I appreciate your time and help.

**Comment by betacentauri** [comment]
Should be fixed in next build:
https://github.com/openatv/enigma2/commit/a5d122290f288768c3a15e1d45d8738192afe3c0

**Comment by AbuBaniaz** [comment]
This has been fixed. Can the OP or ATV team close please?
