### ISSUE TITLE
IPTV VOD Pause, FF and RW

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#880]
This has been broken for quite sometime because I believe it was reverted as the code broke pausing when using Timeshift.

So have you any plans to add this new fix ?

https://github.com/OpenPLi/enigma2/commit/e89a7bb4e97ab6283be4433e728c57ffe3760ac8

https://github.com/OpenPLi/enigma2/pull/1216

Ian.

**Comment by ian10951** [comment]
Further updates on this here

https://github.com/OpenPLi/enigma2/commit/825e7528e3323e8bb125140117f0f0a531c38b49

I think this is now finished, so I ask again is this going to be added to OpenATV ?

If not then I will have to just add this code to my own OpentATV 6.2 image.

**Comment by arn354** [comment]
you could create a Pull-Request against branch DEV or 6.2 - this would speed up things for sure :)

**Comment by neoatomic** [comment]
@ian10951 Hold down the left/right arrow to FF/RW. Pause isn't working here also.

**Comment by ian10951** [comment]
Well I've pointed the Devs to the code that will fix these issues, however I do not know how to add a Pull Request, so its a case of if they read this and then feel it worthwhile fixing.

Personally I think it is.

**Comment by arn354** [comment]
This code breaks plugins like enigma2-plugin-extensions-kicker and hbbtv.

**Comment by ian10951** [comment]
I didn't know that, however, its up to plugins to adapt to an image, not for an image to adapt to plugins in order for them to work correctly. So those plugin writers would have to "fix" those plugins if this update did indeed break them.

Its more important to have this issue fixed, than to not fix it in case it breaks these plugins, many many users, require this fix in the ATV image. I think the code has now been added to the latest Pli image, so why cant users of ATV have it too.

**Comment by atvcaptain** [comment]
hbbtv plugin was important plugin and its close,  use pli when you need this, we need hbbtv working for many other users and cant break this

**Comment by arn354** [comment]
this is important for you
other things are important for others

maybe there will be another solution or a fix for it - but right now no way in adding it.

**Comment by ian10951** [comment]
Of course I fully understand that, and totally agree, IPTV is secondary. However, surely there must be a fix to have both working correctly ?  I shall keep searching for one, ATV did in the past have this feature fully working, but it was disabled at some point I'm not sure why, I think it was to do with it breaking timeshift in some way. I would imagine it was always intended to be fixed, but then forgotten about perhaps ?

**Comment by arn354** [comment]
maybe the first two commits will not break anything - but also for that, someone has to port the changes to openatv codebase, test them and then provide a pull-request.

**Comment by ian10951** [comment]
Ok for now, until this issue is addressed, here's a simple plugin I've put together to enable the Pausing, FF and RW of VOD when played from Bouquets. 

Just start the stream as now by switching to the desired channel, then open the plugin and either press Red for Gstreamer and Mediaplayer or Green for Exteplayer3 and ffmpeg through Serviceapp if installed. 

I may at some point also mount the boxes HDD to the plugin, to enable the pausing and buffer creation of Live Streams too.

This is just a sticking plaster as it were, but it works for now at least.
[Stream Buffer.zip](https://github.com/openatv/enigma2/files/1734450/Stream.Buffer.zip)

**Comment by betacentauri** [comment]
athoik is working on a solution

**Comment by ian10951** [comment]
https://github.com/OpenPLi/enigma2/commit/1a7db237f41fe183585336922052c212ce733032

**Comment by jbleyel** [comment]
no news since 2018
