### ISSUE TITLE
Uunable to create full backup on Zgemma H9 - Logs attached

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#904]
Unable to create a complete backup on H9 - During creation, screen shows unable to mv root.ubifs, but checking HDD during backup shows hdd/bi/root.ubifs is created.  Full backup fails, leaving behind partial backup files.  Logs attached. Please advise

@atvcaptain can you help?
[Enigma2-debug-20180308_09-45-57.log](https://github.com/openatv/enigma2/files/1792422/Enigma2-debug-20180308_09-45-57.log)

**Comment by p17blo** [comment]
Further information FYI - This is a new install of latest nightly build for H9S (also tested H9T and earlier nightly builds) 20180308 - Nothing else added (no plugins etc), and boot up wizard run only - No other config changes made.

**Comment by arn354** [comment]
cmd3 = "mv %s/root.ubifs %s/root.%s" %(self.WORKDIR, self.WORKDIR, self.ROOTFSTYPE)

[FULL BACKUP] ROOTFSTYPE = > ubi<

ROOTFSTYPE seems to be wrong - at least the space looks weird and causes the mv command to be incomplete/split.

mv: can't rename '/hdd/bi/root.': No such file or directory
mv: can't rename 'ubi': No such file or directory

**Comment by p17blo** [comment]
@arn354 - Do I need to modify or test something on the box?

**Comment by p17blo** [comment]
I manually editted the ImageBackup.py file so that self.ROOTFSTYPE = "ubi" - Ran the backup which did not fail, so this is obviously the reason, but I have no idea how you would fix the root cause here.  Also, the backup that is created will not flash - It creates an H9 folder containing only 4 files, where as the factory image seems to be around 8, plus 2 more in the upper level directory

**Comment by atvcaptain** [comment]
i check this next days and fix both

**Comment by atvcaptain** [comment]
fixed, updates include in image 2018.03.11
