### ISSUE TITLE
Full Backup Image created on Zgemma H9 flashed but machine stuck on boot

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#906]
Re #904 
Image 2018.03.11 seemingly now enables a full backup on H9, However, the resulting image flashes on the box, but box will not boot (stuck on OpenATV boot logo) - Only way out of this is reflash back to factory image.
@atvcaptain - I have the resulting image files if you'd like to take a look at these, please let me know

**Comment by atvcaptain** [comment]
my backup works i have test it

**Comment by p17blo** [comment]
Tested with 12th March 2018 and now working OK. (Retested with March 11th and is not working, something must have been wrong with 11th March) - No worries as working ok now. Closing Ticket

**Comment by 649grant** [comment]
I have this same problem on latest build do a image backup when I try to flash it gets stook on boot
