### ISSUE TITLE
Zgemma H9 will not complete online flash

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#907]
@atvcaptain - Another H9 issue for you here

When selecting online flash, nightly images can be seen and selected. The image file can be seen to be downloading, and after pressing Green to commence flash after download, nothing happens.  OFGWRITE does not commence and no flashing occurs.

**Comment by atvcaptain** [comment]
you use new openatv image ofgwrite fixed for some days

**Comment by p17blo** [comment]
I’m now using the latest (March 12). And online flashing is not working   I have taken a video which I will make available to you via my Dropbox so you can see that ofgwrite never starts.

**Comment by p17blo** [comment]
Here is the video (No idea why it flipped, but you can flip it back in VLC)
https://www.dropbox.com/s/dywwwx35w26ro7o/h9error.mp4?dl=0
@atvcaptain

**Comment by atvcaptain** [comment]
fixed with new image 13.3.2018
