### ISSUE TITLE
Zgemma H9, Swapmanager causing system crash - logs attached

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#908]
And another error for you @atvcaptain 

Please refer to logs - Factory image, no changes (apart from running first boot wizard).  When entering swap manager (menu > info panel > plugins > SwapManager), system instantly crashed.  Debug logs attached, but the pertinent error here is as follows:

```
16:06:58.3551 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/Infopanel/SwapManager.py", line 188, in updateSwap2
16:06:58.3553 { D } IOError: [Errno 2] No such file or directory: '/proc/swaps'
16:06:58.3554 [ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<Tools.BoundFunction.boundFunction instance at 0xb07229e0>,(1,)) failed)
16:07:02.3783 [   ] gdi/grc.cpp:195 thread [gRC] main thread is non-idle! display spinner!
```

[Enigma2-debug-20180312_16-06-17.log](https://github.com/openatv/enigma2/files/1803312/Enigma2-debug-20180312_16-06-17.log)

**Comment by arn354** [comment]
If box is not capable (has not proc/swaps) - we can only hide that menupoint or you don't use it.

**Comment by p17blo** [comment]
Its only a text file?  I have been looking at other boxes - Here's sample content from the H7

```
root@zgemmah7:/proc# cat /proc/swaps
Filename                                Type            Size    Used    Priority
/dev/mmcblk0p10                         partition       502780  0       -1
/media/hdd/swapfile                     file            262140  0       -2
```

Enabling it is the problem as it attempts to read the file and in typical python style, throws it's toys out of the pram when the file is missing - Because it's a file within the /proc/ folder, I can't simply make a blank file for it to use, but it would seem that this would overcome the crash - And making an image that has a waiting crash seem not particular user friendly, so surely if the absence of /proc/swaps causes a crash, better crash detection is needed OR in this image, maybe the swap manager needs to be disabled?

**Comment by atvcaptain** [comment]
we change defconfig np

**Comment by p17blo** [comment]
Thanks @atvcaptain  - Does this mean that this should be resolved in March 13 build?

**Comment by atvcaptain** [comment]
root@zgemmah9s:~# cat /proc/swaps
Filename                                Type            Size    Used    Priority
root@zgemmah9s:~#
