### ISSUE TITLE
Zgemma H9 FHD Skin display problem

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#909]
Tested with multiple FHD Skins (1920 x 1080) but for the purposes of this issue I'll raise this under the default Metrix HD skin.  

Test of resolution passes OK with display as to be expected, after confirming FHD skin resolution and restarting GUI, the screen display then only shows about 1/4 of the actually skin

When viewing skin via webif, the display is fine, but viewing through HDMI socket (via TV with full 4k support), only 1/4 of the screen can be seen.

Screen shots attached of WEBIF and screen when FHD skin is selected and Gui Restarting
![screenshot](https://user-images.githubusercontent.com/17210151/37438777-78140e44-27ec-11e8-864a-fef2352ef013.jpg)
![img_6958](https://user-images.githubusercontent.com/17210151/37438778-784c9548-27ec-11e8-941b-1a034a1aede6.JPG)

When GUI restarted, problem persists (no matter how many times GUI restarts), but the correct display is seen when a full reboot is undertaken

Including logs from boot in standard skin, change to FHD skin, restart gui (1st Log)
Full reboot (2nd log)
[Enigma2-debug-20180315_02-09-40.log](https://github.com/openatv/enigma2/files/1813658/Enigma2-debug-20180315_02-09-40.log)
[Enigma2-debug-20180315_02-07-15.log](https://github.com/openatv/enigma2/files/1813659/Enigma2-debug-20180315_02-07-15.log)

**Comment by atvcaptain** [comment]
yes reboot after switch to fhd, this works, or test image today

**Comment by atvcaptain** [comment]
driver team say, its depends from hisi

**Comment by zgemma-star** [comment]
THis should been fixed long time ago and I assume it can been closed.

**Comment by madieatv** [comment]
ok
