### ISSUE TITLE
Zgemma H9 Factory Image missing dependant plugins?

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#910]
![screenshot](https://user-images.githubusercontent.com/17210151/37439448-17a8bda8-27f0-11e8-9672-00cd6e39e055.jpg)

Factory install, nothing added or removed,  is complaining of missing plugin SystemPlugins/blindscan

**Comment by atvcaptain** [comment]
ok i check this thx for info

**Comment by atvcaptain** [comment]
download the file: https://github.com/oe-alliance/oe-alliance-plugins/blob/master/Blindscan/src/dmmBlindScan.py  and copy to blindscan folder

**Comment by p17blo** [comment]
Will this be added into image or will it always need to be manually added?

**Comment by atvcaptain** [comment]
next update allways include was my mistake i have forget

**Comment by gerrykiddy** [comment]
I cannot add the XtreamTV plugin
