### ISSUE TITLE
Zgemma H9 (FHD?) Skin Refresh Delay

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#911]
I'm not entirely sure if this is an image issue or skin, but I have tested H9 and H7 side by side.  I realise they have different chips, but both are ARM.  Both boxes are very quick, but the screen refresh, particularly in FHD is particularly slow (you can see the screen building) on the H9 where it's instant on the H7 - I'm not even sure how to capture logs or what to look for here so really looking for pointers or at least for someone to check or maybe investigate.  I can provide video if needed.

**Comment by arn354** [comment]
it is driver issue and is being worked on - we can't do anything about it.

https://github.com/openatv/enigma2/commit/8cdda3d31a0e3a0ba95e22afaaa745a366a48921
https://github.com/oe-alliance/oe-alliance-core/commit/7f5a95d9ba7e55381075a8c55e87268f9d706dbe

**Comment by atvcaptain** [comment]
fixed with image 24.3
