### ISSUE TITLE
H9 splash image

### ISSUE THREAD

**Issue by p17blo** [openatv/enigma2#919]
The factory image does not seem to come with a splash.bin file (or anything similar) but still carries the OpenATV splash page after flashing.  How is the changed?

(I realise this maybe more than a question than an issue, but wasn't sure where better to place this)

**Comment by atvcaptain** [comment]
read the info how convert a picture with hitool after this replace the logo.bin that's all and flash image new with your private logo,bin

https://www.opena.tv/dinobot/38239-bootlogo-austausch-bei-der-dinobot.html
