### ISSUE TITLE
OE-A_LCD_1-9 Capture PNG

### ISSUE THREAD

**Issue by e2world** [openatv/enigma2#930]
OE-A_LCD_8![oe-a_lcd_8](https://user-images.githubusercontent.com/34108544/38381966-c6fd21f8-3908-11e8-9f3f-150ff42f779a.png)
OE-A_LCD_9![oe-a_lcd_9](https://user-images.githubusercontent.com/34108544/38381967-c719ed56-3908-11e8-9dd6-701f78955468.png)
OE-A_LCD_7![oe-a_lcd_7](https://user-images.githubusercontent.com/34108544/38381969-c73b84fc-3908-11e8-91dd-a90197e46fc4.png)
OE-A_LCD_6![oe-a_lcd_6](https://user-images.githubusercontent.com/34108544/38381970-c7544140-3908-11e8-8b60-a75930d26f66.png)
OE-A_LCD_5![oe-a_lcd_5](https://user-images.githubusercontent.com/34108544/38381971-c76ebebc-3908-11e8-9157-7c7b2559a704.png)
OE-A_LCD_4![oe-a_lcd_4](https://user-images.githubusercontent.com/34108544/38381972-c78b15da-3908-11e8-940a-85ab4c234e1e.png)
OE-A_LCD_3![oe-a_lcd_3](https://user-images.githubusercontent.com/34108544/38381973-c7a62ce4-3908-11e8-8891-706548b0b811.png)
OE-A_LCD_2![oe-a_lcd_2](https://user-images.githubusercontent.com/34108544/38381974-c7c8e324-3908-11e8-904e-d732f6dd734f.png)
OE-A_LCD_1![oe-a_lcd_1](https://user-images.githubusercontent.com/34108544/38381975-c7e5b9fe-3908-11e8-80a6-ae6b0e4241f5.png)

**Comment by arn354** [comment]
https://github.com/oe-alliance/enigma2-display-skins/commit/62e79bb1cea9721747f87a425f6ab0fd98f67b11

Thx

9 hab ich nicht genommen, das sieht doch komplett anders aus:
https://github.com/oe-alliance/enigma2-display-skins/blob/62e79bb1cea9721747f87a425f6ab0fd98f67b11/skins/display220/OE-A_LCDSkin_9/prev.png

**Comment by e2world** [comment]
Dann liegt ein C&P Fehler in der lcd.xml vor, denn das LCD sieht hier genauso aus.

**Comment by teamblue-e2** [comment]
2 png geht nicht,
was machen könntest unter beibehaltung der größe 220x176 auf schwarzem Hintergrund so versetzt, teilweise überlagert beide verkleinert darzustellen. Normal ist halt die vorschau das was man standardmässig im Betrieb sieht. Von daher wäre der screenshot ja schon richtig - nur weiß man dann halt auch nicht das mit so ner Uhr im Standby.

**Comment by e2world** [comment]
100% i.O. ist das aber auch nicht :(
![lcd](https://user-images.githubusercontent.com/34108544/38427078-93c594fe-39b8-11e8-92a2-bb44054c39cc.png)

**Comment by e2world** [comment]
Vielen Dank für das einbauen der neuen Vorschaubilder, gefällt mir gut. Soll ich für den OE-A_LCD_9 StandBy ein neues issues schreiben oder kann das bitte Jemand beheben (zwei weiße horizontale Striche im PNG)

**Comment by e2world** [comment]
Genau, auf dem Display sieht es genauso aus.
