### ISSUE TITLE
service language transmitted as lang1/lang2

### ISSUE THREAD

**Issue by vojtechj** [openatv/enigma2#935]
Hi,
I am new to github and enigma2, but I think I found a bug and a solution.

on line 153 in /lib/python/Screens/AudioSelection.py there is a prove:
`i = audio.getTrackInfo(x)
languages = i.getLanguage().split('/')`
 that sometimes a service's audio track language is transmitted as language1/language2 and not just language. For example Slovak / Czech and not just Slovak or Czech.

so the autolanguage setting will not work if I am assuming correctly that the language is selected according to code in /lib/python/Screens/InfoBar.py on line 408:
`lang = audioInfo.getLanguage()
	if langC.has_key(lang):
lang = langC[lang][0]`

if that's the case, then I suppose this should fix it:
`lang = audioInfo.getLanguage().split('/')[0]`

What do you think?

And what is with config.autolanguage.audio_usecache or "Prefer audio track stored by service" in the language settings?
I thought that if I set it to yes it will work like this:
- see if user previously selected some audio track language
- if yes set this language when switching program
- if the user didnt set anything the use the autolanguage1,2,3 or 4 option
should it work like this? because it is not.

Thank you

Vojtech

**Comment by atvcaptain** [comment]
ok i check this thx for the info
