### ISSUE TITLE
HbbTV displays wrong in 1080p skins

### ISSUE THREAD

**Issue by pizzelnet** [openatv/enigma2#940]
When using a full HD skin (1920x1080), the HbbTV plugin is displayed at 1280x720p. The video is scaled correctly, however the hbbtv content is not, showing the rest of the screen in black. This didn't happen with the former plugin NextHbbTV. Is there any possibility to fix this issue?

![1_0_19_401_4_20fa_dde0000_0_0_0_20180421174924](https://user-images.githubusercontent.com/9438117/39086055-66d42b60-458c-11e8-8c19-3ce41fea9899.jpg)

![1_0_19_602_6_20fa_dde0000_0_0_0_20180421174022](https://user-images.githubusercontent.com/9438117/39086011-da5244ba-458b-11e8-98dc-7c213555f46c.jpg)

**Comment by atvcaptain** [comment]
https://github.com/oe-alliance/webkit.org/commit/d54adae2fd34a44c787fc869f03b56401318f06c
