### ISSUE TITLE
Left and Right audio channels not working

### ISSUE THREAD

**Issue by ian10951** [openatv/enigma2#941]
If a BISS Feed for example is carrying English on the Left channel and say Spanish on the Right Channel, then its not possible to select either, selecting either Left or Right does nothing. The audio remains mixed in stereo.

Also its not possible to store the selected channel either. If you select Left or Right then exit, when you enter the audio selection menu again its back to stereo.

This was tested on a VU+ Solo2 with both ATV 6.1 and 6.2. Nether worked.

**Comment by jbleyel** [comment]
Please try again with ATV 7.0 and reopen if not fixed.
