### ISSUE TITLE
text bug in SoftwareManager/ImageBackup.py

### ISSUE THREAD

**Issue by atom89** [openatv/enigma2#955]
When an image backup is made, this line is seen in the output on the screen:
"Back-up Tool for a BRAND MODEL".
for some brand names it should be like this:
"Back-up Tool for an BRAND MODEL".
if the brand name starts with: a, e, i, o, u, (and some exeptions like the X in Xtrend) then it should be 'an' instead of 'a'

i have replaced line 255:

self.message += (_("Back-up Tool for a %s\n" %self.SHOWNAME)).upper()

with this:

if getMachineBrand().startswith('A') or getMachineBrand().startswith('E') or getMachineBrand().startswith('I') or getMachineBrand().startswith('O') or getMachineBrand().startswith('U') or getMachineBrand().startswith('Xt'):
    self.message += (_('Back-up Tool for an %s\n') % self.SHOWNAME).upper()
else:
    self.message += (_('Back-up Tool for a %s\n') % self.SHOWNAME).upper()

i also made a little change with the tanslatable part.
i changed this:
 (_("Back-up Tool for a %s\n" %self.SHOWNAME))
into this:
 (_('Back-up Tool for a %s\n') % self.SHOWNAME)

this makes it easier to tanslate.
in the old way there should be a translation for every BRAND and MODEL.

now it looks ok.

**Comment by arn354** [comment]
Can you create a pull-request?

**Comment by AbuBaniaz** [comment]
This should be closed as it was added here
https://github.com/openatv/enigma2/commit/a720c98313720d05795fae9a7bbf43dd6df651e2
