### ISSUE TITLE
Subtitle Positions

### ISSUE THREAD

**Issue by kiddac** [openatv/enigma2#956]
I notice on 1080 satellite boxes, the dvb subtitles still display as if the screen is 1280 x 720 and not 1920 x 1080. For example. 

![image](https://user-images.githubusercontent.com/6818561/39958058-5a8a3f1a-55f5-11e8-8888-7c445d18f909.png)

I can make the text go to the bottom by setting the position to fixed. Also the teletext subtitles are correct its just dvb subtitles that position wrong.

Is this a problem with how the component is written, or is this something that can be overwritten in the skin codes. 

Ta

**Comment by arn354** [comment]
Did you check the e2-log?
Is there a screen used to show the subtitle? 
I have no idea about the c++ part involved.

**Comment by atvcaptain** [comment]
have you test with original atv skin too ?
