### ISSUE TITLE
Fallback Tuner doesnt work on v6.2

### ISSUE THREAD

**Issue by Ntemis** [openatv/enigma2#972]
As the title says server is VUDUO2 and the client is gigablue GB800SE.
they were working just fine on (v6.1) and stopped working after the migration to v6.2  on both
Am only using DVB-T usbs not the internal DVB-C tuners if that helps in any way.
Also i only did the client first GB800SE and after i saw that stopped working i thought could be incompatibility issue between versions server v6.1 -> client v6.2  so i continued to upgrade VUDUO2 too to v6.2 but fixed nothing, so now both on v6.2 and issue persist

**Comment by arn354** [comment]
Nothing really changed related to Remote/Fallbacktuner and it works on other boxes.
Flash Image 6.2 - DO NOT RESTORE SETTINGS - check again.
Provide debug-logs in case it still not works.

**Comment by Ntemis** [comment]
Latest image resolves my issues after opkg update/upgrade on client

**Comment by arn354** [comment]
hmm- nothing changed :)
