### ISSUE TITLE
V6.2 automount via fstab doesnt work

### ISSUE THREAD

**Issue by Ntemis** [openatv/enigma2#974]
As the title says automounting a cifs share by editing /etc/fstab doesnt work
e.g i have this in mine
//vuduo2.local/harddisk/movie   /media/hdd	cifs    user=guest,pass=,_netdev,rw,uid=1000,iocharset=utf8     0 0
i even tried hardcoded ip of vuduo2 still doesn't work.
Box/client is connected by wifi (wireless) mentioning it in case is an issue with the wifi service to not starting on time but i doubt

**Comment by arn354** [comment]
fstab entry workshere as expected.
downsides are - fstab mounts are only executed once at boottime - they are not re-mounted.
At boottime there might be several cases where the fstab mount might fail (device is sleeping or busy), network not ready,...

Therefore i only use autofs for network based mountpoints.

**Comment by Ntemis** [comment]
ok closing this down, thanks
