### ISSUE TITLE
Service Double Subtitle Selecting 

### ISSUE THREAD

**Issue by thawtes** [openatv/enigma2#989]
hello
on some channels the subtitle is in use by default.
I have to manually disable it every once in a while.
the subtitle is still on display even though I have disabled it from the automatic selection screen. I've added a screenshot below you might guess the problem here.
If I do not remember the time wrong this problem was not until a few months ago.

![issue](http://666kb.com/i/dupk9rlw9ezkya6nr.png "problem 1")

![alt tag](http://666kb.com/i/dupka0ae4fotzpp2v.png "problem 2")

**Comment by thawtes** [comment]
this problem did not exist until 2-3 months ago

**Comment by thawtes** [comment]
I just tried openPLI
result: no problem

please fix this problem

thanks

**Comment by arn354** [comment]
added a commit - not sure but could be related

**Comment by thawtes** [comment]
thanks I will test it as soon as possible (wait new image build) and feedback.
and auto language selection (audio) was not working on same channels.
maybe this problem is solved.

**Comment by thawtes** [comment]
thank you @arn354 
problems fixed !
everything works fine
